// frontend/portal-vue/src/views/portal/apps/alliance/projects.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div>
        <h1 class="page-title">合作项目管理</h1>
        <p class="page-sub">管理校企合作项目，追踪项目阶段与里程碑。</p>
      </div>
      <el-button type="primary" @click="router.push('/portal/apps/alliance/projects/new')">
        <el-icon><Plus /></el-icon>
        新建项目
      </el-button>
    </div>

    <el-card shadow="never">
      <el-input
        v-model="search"
        placeholder="搜索项目名称..."
        clearable
        style="max-width: 320px; margin-bottom: 12px"
        @input="onSearch"
        @clear="onSearch"
      />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="项目名称" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" @click="router.push(`/portal/apps/alliance/projects/${row.id}`)">
              {{ row.name }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="前台展示" width="100">
          <template #default="{ row }">
            <el-switch :model-value="row.isPublic || false" @change="togglePublic(row)" />
          </template>
        </el-table-column>
        <el-table-column label="合作企业" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ enterpriseNames(row) }}</template>
        </el-table-column>
        <el-table-column label="合作类型" width="120">
          <template #default="{ row }">{{ row.type || '-' }}</template>
        </el-table-column>
        <el-table-column label="起止时间" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">{{ formatDate(row.startDate) }} ~ {{ formatDate(row.endDate) }}</template>
        </el-table-column>
        <el-table-column label="里程碑进度" width="180">
          <template #default="{ row }">
            <div class="progress-cell">
              <el-progress :percentage="progressOf(row)" :stroke-width="8" style="flex: 1" />
              <span class="progress-text">{{ progressOf(row) }}%</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column label="阶段" width="110">
          <template #default="{ row }">{{ phaseLabel(row.phase) }}</template>
        </el-table-column>
        <el-table-column label="更新时间" width="120">
          <template #default="{ row }">{{ formatDate(row.updatedAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/projects/${row.id}`)">查看</el-button>
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/projects/${row.id}/edit`)">编辑</el-button>
            <el-button link type="danger" size="small" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import {
  allianceProjectApi,
  enterpriseApi,
  milestoneApi,
  allianceLabel,
  formatDate,
  type AllianceProject,
  type AllianceEnterprise,
  type AllianceProjectMilestone,
} from './crud-shared';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');
const router = useRouter();

const items = ref<AllianceProject[]>([]);
const loading = ref(false);
const search = ref('');
const page = ref(1);
const pageSize = 20;
const total = ref(0);
const enterprises = ref<AllianceEnterprise[]>([]);
const milestones = ref<Record<string, AllianceProjectMilestone[]>>({});

async function loadEnterprises() {
  try {
    const res = await enterpriseApi.list({ limit: 200 });
    enterprises.value = res.items || [];
  } catch {
    // 忽略
  }
}

function enterpriseNames(row: AllianceProject): string {
  const ids = (row.enterpriseIds || []).map(String);
  if (ids.length === 0) return '-';
  return ids
    .map((eid) => enterprises.value.find((e) => e.id === eid)?.name || eid)
    .join('、');
}

function phaseLabel(v?: string): string {
  return allianceLabel('projectPhase', v);
}

function progressOf(row: AllianceProject): number {
  const ms = milestones.value[row.id] || [];
  if (ms.length === 0) return 0;
  const done = ms.filter((m) => m.isCompleted).length;
  return Math.round((done / ms.length) * 100);
}

async function loadItems() {
  loading.value = true;
  try {
    const res = await allianceProjectApi.list({
      search: search.value.trim() || undefined,
      limit: pageSize,
      offset: (page.value - 1) * pageSize,
    });
    items.value = res.items;
    total.value = res.total ?? 0;

    const map: Record<string, AllianceProjectMilestone[]> = {};
    const results = await Promise.all(
      res.items.map((p) => milestoneApi.list(p.id).catch(() => ({ items: [] as AllianceProjectMilestone[] }))),
    );
    res.items.forEach((p, i) => {
      map[p.id] = results[i].items || [];
    });
    milestones.value = map;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSearch() {
  page.value = 1;
  loadItems();
}

async function togglePublic(row: AllianceProject) {
  const next = !row.isPublic;
  try {
    await allianceProjectApi.update(row.id, { isPublic: next });
    row.isPublic = next;
    ElMessage.success(next ? '已设为前台展示' : '已取消前台展示');
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: AllianceProject) {
  try {
    await ElMessageBox.confirm(`确定要删除项目 ${row.name} 吗？`, '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    });
  } catch {
    return;
  }
  try {
    await allianceProjectApi.delete(row.id);
    ElMessage.success('已删除');
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(async () => {
  if (!auth.user) {
    try {
      await auth.fetchMe();
    } catch {
      // 忽略
    }
  }
  loadEnterprises();
  loadItems();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.page-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 16px; }
.page-title { margin: 0; font-size: 20px; font-weight: 600; }
.page-sub { margin: 4px 0 0; font-size: 13px; color: #909399; }
.pagination { margin-top: 16px; justify-content: flex-end; }
.progress-cell { display: flex; align-items: center; gap: 8px; }
.progress-text { font-size: 12px; color: #909399; }
</style>

// frontend/edu/app/portal/apps/alliance/projects/page.tsx
'use client'

import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { DateInput } from '@/components/shared/date-input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Progress } from '@/components/ui/progress'
import { Pencil, Trash2, ExternalLink } from 'lucide-react'
import { Link } from 'react-router'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceEnterpriseApi, allianceProjectApi } from '@/lib/api'
import { useToast, useAsync } from '@zhiyu/ui'
import { allianceLabel } from '@zhiyu/shared-types'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { usePagedList } from '@/hooks/use-paged-list'
import { FormFieldRow, FormFieldGrid } from '@/components/shared/form-field-row'
import { formatDate } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import type { AllianceProjectMilestone } from '@/lib/types'

export default function AllianceProjectsPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()

  // 企业全量映射（名称解析用，不随分页）
  const { data: entsData } = useAsync(
    async () => {
      if (!tenantId) return []
      const ents = await allianceEnterpriseApi.list({ limit: 200 })
      return ents.items || []
    },
    { deps: [tenantId, authLoading], onError: () => true },
  )
  const enterprises = entsData ?? []

  // 服务端分页列表
  const list = usePagedList(
    async ({ page, limit, search }) => {
      if (!tenantId) return { items: [], total: 0 }
      const data = await allianceProjectApi.list({ page, limit, search })
      return { items: data.items || [], total: data.total }
    },
    [tenantId, authLoading],
  )

  // 里程碑只拉当前页项目（分页/搜索变化时自动重拉）
  const { data: msData } = useAsync(
    async () => {
      const ms: Record<string, AllianceProjectMilestone[]> = {}
      const milestoneResults = await Promise.all(
        (list.items || []).map((p) =>
          allianceProjectApi.listMilestones(p.id).catch(() => ({ items: [] })),
        ),
      )
      ;(list.items || []).forEach((p, i) => {
        ms[p.id] = milestoneResults[i]?.items || []
      })
      return ms
    },
    { deps: [list.items, tenantId], onError: () => true },
  )

  const milestones = msData ?? {}

  const entName = (id: string) => enterprises.find((e) => e.id === id)?.name || id

  return (
    <PortalCrudPage
      title={t('合作项目管理')}
      description={t('管理校企合作项目，追踪项目阶段与里程碑。')}
      entityLabel={t('合作项目')}
      searchPlaceholder={t('搜索项目名称...')}
      createButtonLabel={t('新建项目')}
      items={list.items}
      loading={list.loading}
      error={list.error?.message ?? null}
      onRetry={list.refresh}
      searchValue={list.search}
      onSearchChange={(v: string) => {
        list.setSearch(v)
        list.setPage(1)
      }}
      pagination={list.pagination}
      importConfig={{
        importType: 'alliance-projects',
        entityLabel: t('合作项目'),
        templateFileName: t('合作项目批量导入模板.xlsx'),
      }}
      createHref="/portal/apps/alliance/projects/new"
      colSpan={9}
      renderTableHeader={() => (
        <>
          <TableHead>{t('项目名称')}</TableHead>
          <TableHead>{t('前台展示')}</TableHead>
          <TableHead>{t('合作企业')}</TableHead>
          <TableHead>{t('合作类型')}</TableHead>
          <TableHead>{t('起止时间')}</TableHead>
          <TableHead>{t('里程碑进度')}</TableHead>
          <TableHead>{t('阶段')}</TableHead>
          <TableHead>{t('更新时间')}</TableHead>
          <TableHead>{t('操作')}</TableHead>
        </>
      )}
      renderTableRow={(p: any, actions: any) => {
        const ms = (milestones ?? {})[p.id] || []
        const done = ms.filter((m) => m.isCompleted).length
        const progress = ms.length > 0 ? Math.round((done / ms.length) * 100) : 0
        const entIds: string[] = (p.enterpriseIds || []).map(String)
        const entNames = entIds.length > 0 ? entIds.map(entName).join('、') : '-'
        return (
          <>
            <TableCell className="font-medium">
              <Link to={`/portal/apps/alliance/projects/${p.id}`} className="hover:underline">
                {p.name}
              </Link>
            </TableCell>
            <TableCell>
              <Switch checked={p.isPublic || false} onCheckedChange={actions.toggle} />
            </TableCell>
            <TableCell className="max-w-[180px] truncate" title={entNames}>
              {entNames}
            </TableCell>
            <TableCell>{p.type || '-'}</TableCell>
            <TableCell className="whitespace-nowrap">
              {formatDate(p.startDate)} ~ {formatDate(p.endDate)}
            </TableCell>
            <TableCell>
              <div className="flex items-center gap-2">
                <Progress value={progress} className="w-20 h-2" />
                <span className="text-xs text-muted-foreground">{progress}%</span>
              </div>
            </TableCell>
            <TableCell>{allianceLabel('projectPhase', p.phase)}</TableCell>
            <TableCell>{formatDate(p.updatedAt)}</TableCell>
            <TableRowActions>
              <Link to={`/portal/apps/alliance/projects/${p.id}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="h-3.5 w-3.5 mr-1" />
                  {t('查看')}
                </Button>
              </Link>
              <Link to={`/portal/apps/alliance/projects/${p.id}/edit`}>
                <Button variant="ghost" size="sm">
                  <Pencil className="h-3.5 w-3.5 mr-1" />
                  {t('编辑')}
                </Button>
              </Link>
              <Button variant="ghost" size="sm" className="text-red-600" onClick={actions.delete}>
                <Trash2 className="h-3.5 w-3.5 mr-1" />
                {t('删除')}
              </Button>
            </TableRowActions>
          </>
        )
      }}
      createDefault={() =>
        ({
          id: '',
          name: '',
          phase: 'initiation',
          publishStatus: 'draft',
          isPublic: false as any,
          createdAt: '',
          updatedAt: '',
        }) as any
      }
      renderForm={(item: any, setItem: any) => (
        <div className="space-y-4">
          <FormFieldRow label={t('项目名称')} required>
            <Input
              value={item.name || ''}
              onChange={(e: any) => setItem({ ...item, name: e.target.value })}
            />
          </FormFieldRow>
          <FormFieldRow label={t('阶段')}>
            <Select
              value={item.phase || ''}
              onValueChange={(v: any) => setItem({ ...item, phase: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {['initiation', 'execution', 'acceptance', 'closure', 'archived', 'terminated'].map(
                  (v) => (
                    <SelectItem key={v} value={v}>
                      {allianceLabel('projectPhase', v)}
                    </SelectItem>
                  ),
                )}
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldGrid>
            <FormFieldRow label={t('开始日期')}>
              <DateInput
                type="date"
                value={item.startDate || ''}
                onChange={(e: any) => setItem({ ...item, startDate: e.target.value })}
              />
            </FormFieldRow>
            <FormFieldRow label={t('结束日期')}>
              <DateInput
                type="date"
                value={item.endDate || ''}
                onChange={(e: any) => setItem({ ...item, endDate: e.target.value })}
              />
            </FormFieldRow>
          </FormFieldGrid>
          <FormFieldRow label={t('描述')}>
            <Textarea
              value={item.description || ''}
              onChange={(e: any) => setItem({ ...item, description: e.target.value })}
              rows={3}
            />
          </FormFieldRow>
        </div>
      )}
      getDeleteDescription={(item: any) => (
        <>{t('确定要删除项目 {name} 吗？', { name: item.name })}</>
      )}
      onSave={async (item: any, isEdit: boolean) => {
        if (isEdit) await allianceProjectApi.update(item.id, item)
        else await allianceProjectApi.create(item)
        toast({ title: t('项目已{action}', { action: isEdit ? t('更新') : t('创建') }) })
        await list.refresh()
      }}
      onDelete={async (item: any) => {
        await allianceProjectApi.delete(item.id)
        toast({ title: t('已删除') })
        await list.refresh()
      }}
      onToggleEnabled={async (item: any) => {
        await allianceProjectApi.update(item.id, { isPublic: !item.isPublic })
        toast({ title: t('已{action}前台展示', { action: item.isPublic ? t('取消') : t('设为') }) })
        await list.refresh()
      }}
    />
  )
}
