// apps/edu/app/portal/workspace/_components/career-tab.tsx
'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import {
  Briefcase,
  Heart,
  BookOpen,
  Layers,
  FileText,
  Library,
  ClipboardList,
  Loader2,
  MapPin,
  ChevronRight,
} from 'lucide-react'
import { StatusBadge, useToast } from '@zhiyu/ui'
import { SectionCard } from './section-card'
import { favoriteApi, positionApi } from '@/lib/api'
import type { CareerPosition, Scenario, Course, QuestionBank, Exam } from '@/lib/types'
import type { FavoriteTargetType } from '@/lib/api'
import { JobCard } from '@/components/job/student/job-card'
import { SceneCard } from '@/components/scene/student/scene-card'

const coverGradients = [
  'linear-gradient(135deg,#1e3a8a,#3b7cff)',
  'linear-gradient(135deg,#7c2d12,#dc2626)',
  'linear-gradient(135deg,#064e3b,#0891b2)',
  'linear-gradient(135deg,#334155,#64748b)',
  'linear-gradient(135deg,#581c87,#a855f7)',
  'linear-gradient(135deg,#1e40af,#3b82f6)',
]

interface FavoritesState {
  jobs: CareerPosition[]
  scenes: Scenario[]
  courses: Course[]
  banks: QuestionBank[]
  exams: Exam[]
}

const emptyFavorites: FavoritesState = {
  jobs: [],
  scenes: [],
  courses: [],
  banks: [],
  exams: [],
}

const categoryConfig = {
  jobs: { label: '职业岗位', icon: Briefcase, color: 'blue' as const },
  scenes: { label: '实践场景', icon: Layers, color: 'amber' as const },
  courses: { label: '数字课程', icon: BookOpen, color: 'emerald' as const },
  exams: { label: '测评资源', icon: FileText, color: 'purple' as const },
}

// 分类 -> 收藏实体集合的键名映射（测评资源含题库与试卷）
const categoryKeys: Record<string, (keyof FavoritesState)[]> = {
  all: ['jobs', 'scenes', 'courses', 'banks', 'exams'],
  jobs: ['jobs'],
  scenes: ['scenes'],
  courses: ['courses'],
  exams: ['banks', 'exams'],
}

function CoverBadge({ label }: { label: string }) {
  return (
    <span className="absolute top-3 right-3 bg-white/25 backdrop-blur-sm text-white px-2.5 py-1 rounded-full text-[11px] font-medium border border-white/10">
      {label}
    </span>
  )
}

function CourseCoverCard({
  course,
  index,
  onUnfavorite,
}: {
  course: Course
  index: number
  onUnfavorite: () => void
}) {
  return (
    <div className="relative group">
      <Link href={`/lesson/landing/${course.id}`} className="group block no-underline text-inherit">
        <div className="bg-white rounded-2xl border border-[#e7e5e4] overflow-hidden hover:shadow-[0_8px_24px_rgba(0,0,0,0.08)] hover:border-emerald-200 hover:-translate-y-0.5 transition-all h-full flex flex-col shadow-[0_2px_6px_rgba(0,0,0,0.04)]">
          <div
            className="h-[110px] flex items-center justify-center shrink-0 relative bg-cover bg-center"
            style={
              course.coverImage
                ? { backgroundImage: `url('${course.coverImage}')` }
                : { background: coverGradients[index % coverGradients.length] }
            }
          >
            {!course.coverImage && (
              <span className="text-white text-lg font-bold drop-shadow-lg">
                {course.name.slice(0, 8)}
              </span>
            )}
            <CoverBadge label="已发布" />
            {course.batchName && (
              <span className="absolute bottom-3 left-3 bg-white/20 backdrop-blur-sm text-white px-2 py-0.5 rounded text-[10px] border border-white/10">
                {course.batchName}
              </span>
            )}
          </div>
          <div className="p-4 flex-1 flex flex-col">
            <h3 className="text-sm font-semibold text-slate-800 mb-1.5 truncate">{course.name}</h3>
            {course.majorName && (
              <p className="text-[11px] text-slate-400 mb-1 flex items-center gap-1">
                <MapPin className="w-3 h-3" /> {course.majorName}
              </p>
            )}
            <div className="mt-auto flex items-center justify-between text-[11px] text-slate-400 border-t border-slate-50 pt-2">
              <span className="flex items-center gap-1">
                <Layers className="w-3 h-3" /> {course.nodeCount} 节点
              </span>
              <span className="flex items-center gap-1">
                <BookOpen className="w-3 h-3" /> {course.resourceCount} 资源
              </span>
            </div>
          </div>
        </div>
      </Link>
      <button
        onClick={(e) => {
          e.stopPropagation()
          onUnfavorite()
        }}
        className="absolute top-2 left-2 z-10 flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-black/30 text-white/90 hover:text-rose-300 transition-colors"
        title="取消收藏"
      >
        <Heart className="w-3 h-3 fill-current" />
        取消收藏
      </button>
    </div>
  )
}

function BankCard({
  bank,
  index,
  onUnfavorite,
}: {
  bank: QuestionBank
  index: number
  onUnfavorite: () => void
}) {
  return (
    <div className="relative group">
      <Link
        href={`/evaluation/landing/banks/${bank.id}`}
        className="group block no-underline text-inherit"
      >
        <div className="bg-white rounded-2xl border border-[#e7e5e4] overflow-hidden hover:shadow-[0_8px_28px_rgba(0,0,0,0.1)] hover:border-purple-200 hover:-translate-y-1 transition-all h-full flex flex-col shadow-[0_2px_6px_rgba(0,0,0,0.04)]">
          <div
            className="h-[110px] flex items-center justify-center shrink-0 relative"
            style={
              bank.coverImage
                ? {
                    backgroundImage: `url('${bank.coverImage}')`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                  }
                : { background: coverGradients[(index + 2) % coverGradients.length] }
            }
          >
            {!bank.coverImage && <Library className="w-12 h-12 text-white/80" />}
            <CoverBadge label={`v${bank.version}`} />
          </div>
          <div className="p-4 flex-1 flex flex-col">
            <h3 className="text-sm font-semibold text-slate-800 mb-1.5 truncate">{bank.name}</h3>
            <p className="text-[11px] text-slate-400 leading-relaxed mb-3 line-clamp-2 flex-1">
              {bank.description || '暂无描述'}
            </p>
            <div className="flex items-center justify-between text-[11px] text-slate-400 border-t border-slate-50 pt-2">
              <span className="flex items-center gap-1">
                <FileText className="w-3 h-3" /> {bank.questionCount} 题
              </span>
              <span className="text-purple-500 group-hover:text-purple-600 font-medium">
                查看详情 →
              </span>
            </div>
          </div>
        </div>
      </Link>
      <button
        onClick={(e) => {
          e.stopPropagation()
          onUnfavorite()
        }}
        className="absolute top-2 left-2 z-10 flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-black/30 text-white/90 hover:text-rose-300 transition-colors"
        title="取消收藏"
      >
        <Heart className="w-3 h-3 fill-current" />
        取消收藏
      </button>
    </div>
  )
}

function ExamCard({
  exam,
  index,
  onUnfavorite,
}: {
  exam: Exam
  index: number
  onUnfavorite: () => void
}) {
  return (
    <div className="relative group">
      <Link
        href={`/evaluation/landing/exams/${exam.id}`}
        className="group block no-underline text-inherit"
      >
        <div className="bg-white rounded-2xl border border-[#e7e5e4] overflow-hidden hover:shadow-[0_8px_28px_rgba(0,0,0,0.1)] hover:border-purple-200 hover:-translate-y-1 transition-all h-full flex flex-col shadow-[0_2px_6px_rgba(0,0,0,0.04)]">
          <div
            className="h-[110px] flex items-center justify-center shrink-0 relative"
            style={
              exam.coverImage
                ? {
                    backgroundImage: `url('${exam.coverImage}')`,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                  }
                : { background: coverGradients[(index + 4) % coverGradients.length] }
            }
          >
            {!exam.coverImage && <ClipboardList className="w-12 h-12 text-white/80" />}
            <CoverBadge label={`${exam.duration} 分钟`} />
          </div>
          <div className="p-4 flex-1 flex flex-col">
            <h3 className="text-sm font-semibold text-slate-800 mb-1.5 truncate">{exam.name}</h3>
            <p className="text-[11px] text-slate-400 leading-relaxed mb-3 line-clamp-2 flex-1">
              {exam.description || '暂无描述'}
            </p>
            <div className="flex items-center justify-between text-[11px] text-slate-400 border-t border-slate-50 pt-2">
              <span className="flex items-center gap-1">
                <ClipboardList className="w-3 h-3" /> {exam.totalScore} 分
              </span>
              <StatusBadge status={exam.status} className="text-[10px] px-1.5 py-0.5 rounded" />
            </div>
          </div>
        </div>
      </Link>
      <button
        onClick={(e) => {
          e.stopPropagation()
          onUnfavorite()
        }}
        className="absolute top-2 left-2 z-10 flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-black/30 text-white/90 hover:text-rose-300 transition-colors"
        title="取消收藏"
      >
        <Heart className="w-3 h-3 fill-current" />
        取消收藏
      </button>
    </div>
  )
}

export function CareerTab() {
  const { toast } = useToast()
  const [activeCategory, setActiveCategory] = useState('all')
  const [loading, setLoading] = useState(true)
  const [favorites, setFavorites] = useState<FavoritesState>(emptyFavorites)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      setLoading(true)
      try {
        const [jobsRes, favRes] = await Promise.all([
          positionApi.listFavorites().catch(() => null),
          favoriteApi.list().catch(() => null),
        ])
        if (cancelled) return
        setFavorites({
          jobs: jobsRes?.items || [],
          scenes: favRes?.scene || [],
          courses: favRes?.course || [],
          banks: favRes?.question_bank || [],
          exams: favRes?.exam || [],
        })
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const removeFavorite = (key: keyof FavoritesState, id: string) => {
    setFavorites((prev) => ({
      ...prev,
      [key]: prev[key].filter((item) => item.id !== id),
    }))
  }

  const handleUnfavorite = async (
    key: keyof FavoritesState,
    id: string,
    targetType?: FavoriteTargetType,
  ) => {
    try {
      if (targetType) {
        await favoriteApi.toggle(targetType, id)
      } else {
        await positionApi.favorite(id)
      }
      removeFavorite(key, id)
    } catch {
      toast({ variant: 'destructive', title: '操作失败', description: '取消收藏失败，请稍后再试' })
    }
  }

  const cats = Object.entries(categoryConfig).map(([k, v]) => ({ id: k, ...v }))
  const visibleKeys = categoryKeys[activeCategory]

  const totalCount =
    favorites.jobs.length +
    favorites.scenes.length +
    favorites.courses.length +
    favorites.banks.length +
    favorites.exams.length

  return (
    <div className="space-y-5">
      <SectionCard title="我的收藏" icon={Heart} iconColor="rose">
        {/* 分类筛选 */}
        <div className="flex items-center gap-5 mb-5 border-b border-gray-100">
          <button
            onClick={() => setActiveCategory('all')}
            className={`text-sm pb-2 border-b-2 transition-colors ${
              activeCategory === 'all'
                ? 'text-rose-600 border-rose-600 font-medium'
                : 'text-gray-500 border-transparent hover:text-gray-700'
            }`}
          >
            全部收藏（{totalCount}）
          </button>
          {cats.map((c) => (
            <button
              key={c.id}
              onClick={() => setActiveCategory(c.id)}
              className={`text-sm pb-2 border-b-2 transition-colors flex items-center gap-1.5 ${
                activeCategory === c.id
                  ? 'text-rose-600 border-rose-600 font-medium'
                  : 'text-gray-500 border-transparent hover:text-gray-700'
              }`}
            >
              <c.icon className="w-3.5 h-3.5" />
              {c.label}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-16 text-gray-400">
            <Loader2 className="w-5 h-5 animate-spin mr-2" /> 加载收藏中...
          </div>
        ) : totalCount === 0 ? (
          <div className="text-center py-16 text-gray-400">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-rose-50 flex items-center justify-center">
              <Heart className="w-8 h-8 text-rose-200" />
            </div>
            <div className="text-[15px] font-medium text-gray-600">暂无收藏内容</div>
            <div className="text-[13px] mt-1">
              浏览岗位、场景、课程或测评资源时，点击“收藏”即可在这里查看
            </div>
            <div className="flex items-center justify-center gap-4 mt-4 text-xs text-rose-500">
              <Link href="/job/landing" className="hover:underline flex items-center gap-0.5">
                去收藏岗位 <ChevronRight className="w-3 h-3" />
              </Link>
              <Link href="/scene/landing" className="hover:underline flex items-center gap-0.5">
                去收藏场景 <ChevronRight className="w-3 h-3" />
              </Link>
              <Link href="/lesson/landing" className="hover:underline flex items-center gap-0.5">
                去收藏课程 <ChevronRight className="w-3 h-3" />
              </Link>
              <Link
                href="/evaluation/landing"
                className="hover:underline flex items-center gap-0.5"
              >
                去收藏测评 <ChevronRight className="w-3 h-3" />
              </Link>
            </div>
          </div>
        ) : (
          <>
            {/* 职业岗位 */}
            {visibleKeys.includes('jobs') && (
              <div className="mb-6">
                <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-blue-500" />
                  职业岗位
                  <span className="text-xs text-gray-400 font-normal">
                    （{favorites.jobs.length}）
                  </span>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                  {favorites.jobs.map((job, i) => (
                    <div key={job.id} className="relative group">
                      <JobCard position={job} index={i} />
                      <button
                        onClick={() => handleUnfavorite('jobs', job.id)}
                        className="absolute top-2 left-2 z-10 flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-black/30 text-white/90 hover:text-rose-300 transition-colors"
                        title="取消收藏"
                      >
                        <Heart className="w-3 h-3 fill-current" />
                        取消收藏
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 实践场景 */}
            {visibleKeys.includes('scenes') && (
              <div className="mb-6">
                <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Layers className="w-4 h-4 text-amber-500" />
                  实践场景
                  <span className="text-xs text-gray-400 font-normal">
                    （{favorites.scenes.length}）
                  </span>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                  {favorites.scenes.map((scene, i) => (
                    <div key={scene.id} className="relative group">
                      <SceneCard scenario={scene} index={i} taskCount={scene.taskCount} />
                      <button
                        onClick={() => handleUnfavorite('scenes', scene.id, 'scene')}
                        className="absolute top-2 left-2 z-10 flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-black/30 text-white/90 hover:text-rose-300 transition-colors"
                        title="取消收藏"
                      >
                        <Heart className="w-3 h-3 fill-current" />
                        取消收藏
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 数字课程 */}
            {visibleKeys.includes('courses') && (
              <div className="mb-6">
                <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <BookOpen className="w-4 h-4 text-emerald-500" />
                  数字课程
                  <span className="text-xs text-gray-400 font-normal">
                    （{favorites.courses.length}）
                  </span>
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                  {favorites.courses.map((course, i) => (
                    <CourseCoverCard
                      key={course.id}
                      course={course}
                      index={i}
                      onUnfavorite={() => handleUnfavorite('courses', course.id, 'course')}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* 测评资源（题库 + 试卷） */}
            {visibleKeys.includes('exams') && (
              <div className="mb-6">
                <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <FileText className="w-4 h-4 text-purple-500" />
                  测评资源
                  <span className="text-xs text-gray-400 font-normal">
                    （{favorites.banks.length + favorites.exams.length}）
                  </span>
                </h4>
                {favorites.banks.length > 0 && (
                  <div className="mb-4">
                    <div className="text-xs text-slate-500 mb-2 flex items-center gap-1.5">
                      <Library className="w-3.5 h-3.5" /> 题库
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                      {favorites.banks.map((bank, i) => (
                        <BankCard
                          key={bank.id}
                          bank={bank}
                          index={i}
                          onUnfavorite={() => handleUnfavorite('banks', bank.id, 'question_bank')}
                        />
                      ))}
                    </div>
                  </div>
                )}
                {favorites.exams.length > 0 && (
                  <div>
                    <div className="text-xs text-slate-500 mb-2 flex items-center gap-1.5">
                      <ClipboardList className="w-3.5 h-3.5" /> 试卷
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
                      {favorites.exams.map((exam, i) => (
                        <ExamCard
                          key={exam.id}
                          exam={exam}
                          index={i}
                          onUnfavorite={() => handleUnfavorite('exams', exam.id, 'exam')}
                        />
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </SectionCard>
    </div>
  )
}

// plus-ui/src-portal/views/portal/workspace/CareerTab.vue
<!--
  我的收藏 Tab（React career-tab 对位）。
  对齐原 React 版 career-tab.tsx：
  - 分类筛选：全部收藏（N）/ 职业岗位 / 实践场景 / 数字课程 / 测评资源（题库+试卷）；
  - 岗位收藏走 /job/positions/favorites 与 POST /job/positions/{id}/favorite（toggle）；
    其余走 GET /favorites 与 POST /favorites/{targetType}/{id}；
  - 岗位/场景卡片复用门户已有 JobCard / SceneCard（与 landing 页一致）；
  - 空态给出「去收藏岗位/场景/课程/测评」四个入口。
  数据加载与取消收藏逻辑沿用门户既有 views/portal/favorites.vue 的实现思路。
-->
<template>
  <SectionCard title="我的收藏" :icon="Star" icon-color="rose">
    <!-- 分类筛选 -->
    <div class="cat-tabs">
      <button
        type="button"
        class="cat-tab"
        :class="{ active: activeCategory === 'all' }"
        @click="activeCategory = 'all'"
      >
        全部收藏（{{ totalCount }}）
      </button>
      <button
        v-for="c in CATEGORIES"
        :key="c.id"
        type="button"
        class="cat-tab"
        :class="{ active: activeCategory === c.id }"
        @click="activeCategory = c.id"
      >
        <el-icon><component :is="c.icon" /></el-icon>{{ c.label }}
      </button>
    </div>

    <div v-if="loading" class="fav-loading">
      <el-icon class="is-loading"><Loading /></el-icon> 加载收藏中...
    </div>

    <div v-else-if="totalCount === 0" class="fav-empty">
      <div class="empty-icon"><el-icon :size="32"><Star /></el-icon></div>
      <div class="empty-title">暂无收藏内容</div>
      <div class="empty-sub">浏览岗位、场景、课程或测评资源时，点击“收藏”即可在这里查看</div>
      <div class="empty-links">
        <router-link to="/job/landing">去收藏岗位 <el-icon><ArrowRight /></el-icon></router-link>
        <router-link to="/scene/landing">去收藏场景 <el-icon><ArrowRight /></el-icon></router-link>
        <router-link to="/lesson/landing">去收藏课程 <el-icon><ArrowRight /></el-icon></router-link>
        <router-link to="/evaluation/landing">去收藏测评 <el-icon><ArrowRight /></el-icon></router-link>
      </div>
    </div>

    <template v-else>
      <!-- 职业岗位 -->
      <div v-if="visibleKeys.includes('jobs')" class="fav-block">
        <h4 class="block-title">
          <el-icon class="i-primary"><Briefcase /></el-icon>职业岗位
          <span class="block-count">（{{ favorites.jobs.length }}）</span>
        </h4>
        <div class="card-grid">
          <div v-for="job in favorites.jobs" :key="job.id" class="card-wrap">
            <JobCard :position="job" />
            <button type="button" class="unfav-btn" title="取消收藏" @click="unfavorite('jobs', job.id)">
              <el-icon><Star /></el-icon>取消收藏
            </button>
          </div>
        </div>
      </div>

      <!-- 实践场景 -->
      <div v-if="visibleKeys.includes('scenes')" class="fav-block">
        <h4 class="block-title">
          <el-icon class="i-amber"><Collection /></el-icon>实践场景
          <span class="block-count">（{{ favorites.scenes.length }}）</span>
        </h4>
        <div class="card-grid">
          <div v-for="scene in favorites.scenes" :key="scene.id" class="card-wrap">
            <SceneCard :scenario="scene" :task-count="scene.taskCount" />
            <button
              type="button"
              class="unfav-btn"
              title="取消收藏"
              @click="unfavorite('scenes', scene.id, 'scene')"
            >
              <el-icon><Star /></el-icon>取消收藏
            </button>
          </div>
        </div>
      </div>

      <!-- 数字课程 -->
      <div v-if="visibleKeys.includes('courses')" class="fav-block">
        <h4 class="block-title">
          <el-icon class="i-green"><Reading /></el-icon>数字课程
          <span class="block-count">（{{ favorites.courses.length }}）</span>
        </h4>
        <div class="card-grid">
          <div v-for="(course, i) in favorites.courses" :key="course.id" class="card-wrap">
            <router-link :to="`/lesson/landing/${course.id}`" class="cover-card">
              <div class="cover-head" :style="coverStyle(course.coverImage, i)">
                <span v-if="!course.coverImage" class="cover-text">{{ course.name.slice(0, 8) }}</span>
                <span class="cover-badge">已发布</span>
                <span v-if="course.batchName" class="cover-sub">{{ course.batchName }}</span>
              </div>
              <div class="cover-body">
                <h3 class="cover-title">{{ course.name }}</h3>
                <p v-if="course.majorName" class="cover-meta">
                  <el-icon><Location /></el-icon>{{ course.majorName }}
                </p>
                <div class="cover-foot">
                  <span><el-icon><Collection /></el-icon>{{ course.nodeCount }} 节点</span>
                  <span><el-icon><Reading /></el-icon>{{ course.resourceCount }} 资源</span>
                </div>
              </div>
            </router-link>
            <button
              type="button"
              class="unfav-btn"
              title="取消收藏"
              @click="unfavorite('courses', course.id, 'course')"
            >
              <el-icon><Star /></el-icon>取消收藏
            </button>
          </div>
        </div>
      </div>

      <!-- 测评资源（题库 + 试卷） -->
      <div v-if="visibleKeys.includes('banks')" class="fav-block">
        <h4 class="block-title">
          <el-icon class="i-primary"><Document /></el-icon>测评资源
          <span class="block-count">（{{ favorites.banks.length + favorites.exams.length }}）</span>
        </h4>

        <div v-if="favorites.banks.length > 0" class="sub-block">
          <div class="sub-title"><el-icon><Collection /></el-icon> 题库</div>
          <div class="card-grid">
            <div v-for="(bank, i) in favorites.banks" :key="bank.id" class="card-wrap">
              <router-link :to="`/evaluation/landing/banks/${bank.id}`" class="cover-card">
                <div class="cover-head" :style="coverStyle(bank.coverImage, i + 2)">
                  <el-icon v-if="!bank.coverImage" :size="48" class="cover-icon"><Collection /></el-icon>
                  <span class="cover-badge">{{ bank.version || 'V1.0' }}</span>
                </div>
                <div class="cover-body">
                  <h3 class="cover-title">{{ bank.name }}</h3>
                  <p class="cover-desc">{{ bank.description || '暂无描述' }}</p>
                  <div class="cover-foot">
                    <span><el-icon><Document /></el-icon>{{ bank.questionCount }} 题</span>
                    <span class="cover-link">查看详情 →</span>
                  </div>
                </div>
              </router-link>
              <button
                type="button"
                class="unfav-btn"
                title="取消收藏"
                @click="unfavorite('banks', bank.id, 'question_bank')"
              >
                <el-icon><Star /></el-icon>取消收藏
              </button>
            </div>
          </div>
        </div>

        <div v-if="favorites.exams.length > 0" class="sub-block">
          <div class="sub-title"><el-icon><Tickets /></el-icon> 试卷</div>
          <div class="card-grid">
            <div v-for="(exam, i) in favorites.exams" :key="exam.id" class="card-wrap">
              <router-link :to="`/evaluation/landing/exams/${exam.id}`" class="cover-card">
                <div class="cover-head" :style="coverStyle(exam.coverImage, i + 4)">
                  <el-icon v-if="!exam.coverImage" :size="48" class="cover-icon"><Tickets /></el-icon>
                  <span class="cover-badge">{{ exam.duration }} 分钟</span>
                </div>
                <div class="cover-body">
                  <h3 class="cover-title">{{ exam.name }}</h3>
                  <p class="cover-desc">{{ exam.description || '暂无描述' }}</p>
                  <div class="cover-foot">
                    <span><el-icon><Tickets /></el-icon>{{ exam.totalScore }} 分</span>
                    <span class="status-badge" :style="statusStyle(exam.status)">
                      {{ getStatusConfig(exam.status).label }}
                    </span>
                  </div>
                </div>
              </router-link>
              <button
                type="button"
                class="unfav-btn"
                title="取消收藏"
                @click="unfavorite('exams', exam.id, 'exam')"
              >
                <el-icon><Star /></el-icon>取消收藏
              </button>
            </div>
          </div>
        </div>
      </div>

    </template>
  </SectionCard>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import {
  ArrowRight,
  Briefcase,
  Collection,
  Document,
  Loading,
  Location,
  Reading,
  Star,
  Tickets
} from '@element-plus/icons-vue';
import { favoriteApi } from '@/api/portal';
import type { FavoriteTargetType } from '@/api/portal';
import { positionApi } from '@/api/job';
import type { CareerPosition } from '@/types/job';
import type { Scenario } from '@/types/scene';
import type { Course } from '@/types/lesson';
import type { Exam, QuestionBank } from '@/types/evaluation';
import JobCard from '@/views/landing/JobCard.vue';
import SceneCard from '@/views/landing/SceneCard.vue';
import SectionCard from './SectionCard.vue';
import { getStatusConfig } from './workspace-utils';

const COVER_GRADIENTS = [
  'linear-gradient(135deg,#1e3a8a,#3b7cff)',
  'linear-gradient(135deg,#7c2d12,#dc2626)',
  'linear-gradient(135deg,#064e3b,#0891b2)',
  'linear-gradient(135deg,#334155,#64748b)',
  'linear-gradient(135deg,#581c87,#a855f7)',
  'linear-gradient(135deg,#1e40af,#3b82f6)'
];

const CATEGORIES = [
  { id: 'jobs', label: '职业岗位', icon: Briefcase },
  { id: 'scenes', label: '实践场景', icon: Collection },
  { id: 'courses', label: '数字课程', icon: Reading },
  { id: 'exams', label: '测评资源', icon: Document }
];

type FavKey = 'jobs' | 'scenes' | 'courses' | 'banks' | 'exams';

// 分类 -> 收藏实体集合的键名映射（测评资源含题库与试卷）
const CATEGORY_KEYS: Record<string, FavKey[]> = {
  all: ['jobs', 'scenes', 'courses', 'banks', 'exams'],
  jobs: ['jobs'],
  scenes: ['scenes'],
  courses: ['courses'],
  exams: ['banks', 'exams']
};

const activeCategory = ref('all');
const loading = ref(true);

const favorites = reactive({
  jobs: [] as CareerPosition[],
  scenes: [] as Scenario[],
  courses: [] as Course[],
  banks: [] as QuestionBank[],
  exams: [] as Exam[]
});

const visibleKeys = computed(() => CATEGORY_KEYS[activeCategory.value] || CATEGORY_KEYS.all);

const totalCount = computed(
  () =>
    favorites.jobs.length +
    favorites.scenes.length +
    favorites.courses.length +
    favorites.banks.length +
    favorites.exams.length
);

function coverStyle(coverImage: string | undefined, index: number) {
  return coverImage
    ? { backgroundImage: `url('${coverImage}')`, backgroundSize: 'cover', backgroundPosition: 'center' }
    : { background: COVER_GRADIENTS[index % COVER_GRADIENTS.length] };
}

function statusStyle(status: string) {
  const cfg = getStatusConfig(status);
  return { color: cfg.color, background: cfg.bg };
}

async function unfavorite(key: FavKey, id: string, targetType?: FavoriteTargetType) {
  try {
    if (targetType) {
      await favoriteApi.toggle(targetType, id);
    } else {
      await positionApi.favorite(id);
    }
    // 局部剔除，避免整表重载
    const list = favorites[key] as unknown as { id: string }[];
    const idx = list.findIndex((item) => item.id === id);
    if (idx >= 0) list.splice(idx, 1);
  } catch {
    ElMessage.error('取消收藏失败，请稍后再试');
  }
}

onMounted(async () => {
  loading.value = true;
  try {
    const [jobsRes, favRes] = await Promise.all([
      positionApi.listFavorites().catch(() => null),
      favoriteApi.list().catch(() => null)
    ]);
    favorites.jobs = jobsRes?.items || [];
    favorites.scenes = favRes?.scene || [];
    favorites.courses = favRes?.course || [];
    favorites.banks = favRes?.question_bank || [];
    favorites.exams = favRes?.exam || [];
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
/* 分类筛选（下划线 tab，对齐 React UnderlineTabs 玫红强调色） */
.cat-tabs {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 20px;
  border-bottom: 1px solid #f3f4f6;
  margin-bottom: 20px;
}
.cat-tab {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  border: none;
  background: transparent;
  padding: 0 0 8px;
  font-size: 14px;
  color: #6b7280;
  cursor: pointer;
  border-bottom: 2px solid transparent;
  transition: color 0.2s, border-color 0.2s;
}
.cat-tab:hover {
  color: #e11d48;
}
.cat-tab.active {
  color: #e11d48;
  border-bottom-color: #e11d48;
  font-weight: 500;
}

.fav-loading {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 64px 0;
  color: #9ca3af;
}

/* 空态 */
.fav-empty {
  text-align: center;
  padding: 64px 0;
  color: #9ca3af;
}
.empty-icon {
  width: 64px;
  height: 64px;
  margin: 0 auto 16px;
  border-radius: 16px;
  background: #fff1f2;
  color: #fecdd3;
  display: flex;
  align-items: center;
  justify-content: center;
}
.empty-title {
  font-size: 15px;
  font-weight: 500;
  color: #4b5563;
}
.empty-sub {
  font-size: 13px;
  margin-top: 4px;
}
.empty-links {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  gap: 16px;
  margin-top: 16px;
  font-size: 12px;
}
.empty-links a {
  display: inline-flex;
  align-items: center;
  gap: 2px;
  color: #f43f5e;
  text-decoration: none;
}
.empty-links a:hover {
  text-decoration: underline;
}

/* 分组 */
.fav-block {
  margin-bottom: 24px;
}
.block-title {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0 0 12px;
  font-size: 14px;
  font-weight: 600;
  color: #111827;
}
.block-count {
  font-size: 12px;
  font-weight: 400;
  color: #9ca3af;
}
.i-primary { color: var(--el-color-primary); }
.i-amber { color: #f59e0b; }
.i-green { color: #10b981; }
.i-cyan { color: #06b6d4; }
.sub-block {
  margin-bottom: 16px;
}
.sub-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: #64748b;
  margin-bottom: 8px;
}
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 12px;
}
.card-wrap {
  position: relative;
}

/* 取消收藏按钮（覆盖卡片左上角，对齐 React 位置） */
.unfav-btn {
  position: absolute;
  top: 8px;
  left: 8px;
  z-index: 10;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  border: none;
  border-radius: 4px;
  background: rgba(0, 0, 0, 0.3);
  color: rgba(255, 255, 255, 0.9);
  font-size: 10px;
  padding: 2px 6px;
  cursor: pointer;
  transition: color 0.2s;
}
.unfav-btn:hover {
  color: #fda4af;
}
.unfav-btn.light {
  left: auto;
  right: 8px;
  background: rgba(0, 0, 0, 0.05);
  color: #6b7280;
}
.unfav-btn.light:hover {
  color: #f43f5e;
}

/* 课程/题库/试卷封面卡 */
.cover-card {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  overflow: hidden;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.04);
  text-decoration: none;
  color: inherit;
  transition: box-shadow 0.25s, transform 0.25s, border-color 0.25s;
}
.cover-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.08);
  border-color: var(--el-color-primary-light-7);
}
.cover-head {
  position: relative;
  height: 110px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background-size: cover;
  background-position: center;
}
.cover-text {
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.35);
}
.cover-icon {
  color: rgba(255, 255, 255, 0.8);
}
.cover-badge {
  position: absolute;
  top: 12px;
  right: 12px;
  background: rgba(255, 255, 255, 0.25);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: #fff;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 11px;
  font-weight: 500;
}
.cover-sub {
  position: absolute;
  bottom: 12px;
  left: 12px;
  background: rgba(255, 255, 255, 0.2);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: #fff;
  padding: 1px 8px;
  border-radius: 4px;
  font-size: 10px;
}
.cover-body {
  flex: 1;
  display: flex;
  flex-direction: column;
  padding: 16px;
}
.cover-title {
  margin: 0 0 6px;
  font-size: 14px;
  font-weight: 600;
  color: #1e293b;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.cover-meta {
  margin: 0 0 4px;
  font-size: 11px;
  color: #94a3b8;
  display: flex;
  align-items: center;
  gap: 4px;
}
.cover-desc {
  margin: 0 0 12px;
  flex: 1;
  font-size: 11px;
  color: #94a3b8;
  line-height: 1.6;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.cover-foot {
  margin-top: auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-top: 1px solid #f8fafc;
  padding-top: 8px;
  font-size: 11px;
  color: #94a3b8;
}
.cover-foot span {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.cover-link {
  color: var(--el-color-primary);
  font-weight: 500;
}
.status-badge {
  display: inline-flex;
  align-items: center;
  border-radius: 4px;
  padding: 2px 6px;
  font-size: 10px;
  font-weight: 500;
}

/* 收藏简卡 */
.mini-card {
  display: block;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  padding: 16px;
  text-decoration: none;
  color: inherit;
  transition: box-shadow 0.2s;
}
.mini-card:hover {
  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.08);
}
.mini-head {
  display: flex;
  align-items: center;
  gap: 8px;
}
.mini-avatar {
  font-size: 20px;
}
.mini-title {
  font-size: 14px;
  font-weight: 500;
  color: #111827;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.mini-desc {
  margin-top: 4px;
  font-size: 12px;
  color: #6b7280;
  min-height: 32px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.mini-meta {
  margin-top: 8px;
  font-size: 11px;
  color: #9ca3af;
}
</style>
