// frontend/edu/app/portal/workspace/_components/learning-tab.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { BarChart3, BookOpen, Clock, Layers, Play } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { StatusBadge } from '@zhiyu/ui'
import { SectionCard } from './section-card'
import { StatCard } from './stat-card'
import { portalApi } from '@/lib/api'
import type { WorkspaceCourse, WorkspaceSceneTask } from '@/lib/types'
import { DIFFICULTY_LABELS, DIFFICULTY_COLORS } from '@/lib/types'
import { lessonLandingHref, sceneLandingHref } from '@/lib/learn-links'
import { useT } from '@/lib/i18n/locale-provider'

export function LearningTab() {
  const router = useRouter()
  const t = useT()
  const [courses, setCourses] = useState<WorkspaceCourse[]>([])
  const [sceneTasks, setSceneTasks] = useState<WorkspaceSceneTask[]>([])
  const [loading, setLoading] = useState(true)
  const [courseFilter, setCourseFilter] = useState('all')
  const [sceneFilter, setSceneFilter] = useState('all')

  useEffect(() => {
    ;(async () => {
      setLoading(true)
      try {
        const res = await portalApi.workspaceDashboard({ role: 'student' })
        setCourses(res.courses || [])
        setSceneTasks(res.sceneTasks || [])
      } catch {
        setCourses([])
        setSceneTasks([])
      } finally {
        setLoading(false)
      }
    })()
  }, [])

  const filteredCourses = courses.filter((c) => {
    if (courseFilter !== 'all' && c.status !== courseFilter) return false
    return true
  })

  const filteredScenes = sceneTasks.filter((s) => {
    if (sceneFilter !== 'all' && s.status !== sceneFilter) return false
    return true
  })

  // 中文标签 → 颜色，由共享 DIFFICULTY_LABELS/DIFFICULTY_COLORS 派生（与后端 difficultyLabel 中文输出对齐）
  const difficultyColorMap: Record<string, string> = Object.fromEntries(
    Object.entries(DIFFICULTY_LABELS).map(([key, label]) => [label, DIFFICULTY_COLORS[key]]),
  )

  if (loading) {
    return (
      <div className="space-y-5">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard
            title={t('在修课程')}
            value="-"
            icon={BookOpen}
            trend={t('加载中...')}
            color="blue"
          />
          <StatCard
            title={t('场景任务')}
            value="-"
            icon={Layers}
            trend={t('加载中...')}
            color="green"
          />
          <StatCard
            title={t('学习时长')}
            value="-"
            icon={Clock}
            trend={t('加载中...')}
            color="amber"
          />
          <StatCard
            title={t('本周完成任务')}
            value="-"
            icon={BarChart3}
            trend={t('加载中...')}
            color="purple"
          />
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-5">
      {/* 顶部指标 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title={t('在修课程')}
          value={courses.length}
          icon={BookOpen}
          trend={t('本学期共 5 门')}
          color="blue"
        />
        <StatCard
          title={t('场景任务')}
          value={sceneTasks.length}
          icon={Layers}
          trend={t('2 个待完成')}
          color="green"
        />
        <StatCard
          title={t('学习时长')}
          value="86h"
          icon={Clock}
          trend={t('本月 +12h')}
          trendUp
          color="amber"
        />
        <StatCard
          title={t('本周完成任务')}
          value={12}
          icon={BarChart3}
          trend={t('较上周 +3')}
          trendUp
          color="purple"
        />
      </div>

      {/* 课程与任务内容 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* 实践场景（左侧） */}
        <SectionCard
          title={t('我的实践场景')}
          icon={Layers}
          iconColor="green"
          action={{ label: t('全部场景') }}
        >
          <Tabs value={sceneFilter} onValueChange={setSceneFilter}>
            <TabsList className="h-8 bg-gray-100 mb-4">
              <TabsTrigger
                value="all"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('全部')}
              </TabsTrigger>
              <TabsTrigger
                value="进行中"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('进行中')}
              </TabsTrigger>
              <TabsTrigger
                value="待提交"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('待提交')}
              </TabsTrigger>
              <TabsTrigger
                value="已完成"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('已完成')}
              </TabsTrigger>
            </TabsList>
          </Tabs>
          <div className="space-y-3">
            {filteredScenes.length === 0 && (
              <div className="py-8 text-center text-xs text-gray-400">{t('暂无实践场景')}</div>
            )}
            {filteredScenes.map((task) => (
              <div
                key={task.id}
                className="group p-4 rounded-xl border border-gray-100 bg-white hover:border-emerald-200 hover:shadow-sm transition-all cursor-pointer"
              >
                <div className="flex items-start gap-4">
                  <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-emerald-50 to-teal-50 text-emerald-600 flex items-center justify-center text-xl font-bold shrink-0">
                    {task.sceneName.charAt(0)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <div>
                        <h3 className="text-base font-semibold text-gray-900 group-hover:text-emerald-600 transition-colors">
                          {task.taskName}
                        </h3>
                        <p className="text-xs text-gray-500">
                          {t('{scene} · 目标岗位：{position}', {
                            scene: task.sceneName,
                            position: task.position,
                          })}
                        </p>
                      </div>
                      <StatusBadge status={task.status} className="shrink-0" />
                    </div>
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {task.abilityTags.map((tag) => (
                        <span
                          key={tag}
                          className="text-[10px] px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-600 font-medium"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                    <div className="flex items-center gap-4 mt-2 text-xs text-gray-500">
                      <span className="flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5" />
                        {t('截止 {deadline}', { deadline: task.deadline || t('未设置') })}
                      </span>
                      <span className={difficultyColorMap[task.difficulty]}>
                        {t('难度：{difficulty}', { difficulty: task.difficulty })}
                      </span>
                      {task.score !== undefined && (
                        <span className="text-emerald-600 font-medium">
                          {t('得分：{score}/{total}', {
                            score: task.score,
                            total: task.totalScore,
                          })}
                        </span>
                      )}
                    </div>
                  </div>
                  <Button
                    size="sm"
                    className="shrink-0 bg-emerald-600 hover:bg-emerald-700"
                    onClick={() => router.push(sceneLandingHref(task.scenarioId, task.resourceVersion))}
                  >
                    <Play className="w-3.5 h-3.5 mr-1" />
                    {task.status === '已完成' ? t('查看') : t('继续')}
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>

        {/* 混合课（右侧） */}
        <SectionCard
          title={t('我的课程')}
          icon={BookOpen}
          iconColor="blue"
          action={{ label: t('全部课程') }}
        >
          <Tabs value={courseFilter} onValueChange={setCourseFilter}>
            <TabsList className="h-8 bg-gray-100 mb-4">
              <TabsTrigger
                value="all"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('全部')}
              </TabsTrigger>
              <TabsTrigger
                value="进行中"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('进行中')}
              </TabsTrigger>
              <TabsTrigger
                value="未开始"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('未开始')}
              </TabsTrigger>
              <TabsTrigger
                value="已完成"
                className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
              >
                {t('已完成')}
              </TabsTrigger>
            </TabsList>
          </Tabs>
          <div className="space-y-3">
            {filteredCourses.length === 0 && (
              <div className="py-8 text-center text-xs text-gray-400">{t('暂无课程')}</div>
            )}
            {filteredCourses.map((course) => (
              <div
                key={course.id}
                className="group p-4 rounded-xl border border-gray-100 bg-white hover:border-primary/25 hover:shadow-sm transition-all cursor-pointer"
              >
                <div className="flex items-start gap-4">
                  <div className="w-14 h-14 rounded-xl bg-gradient-to-br from-primary/5 to-primary/10 text-primary flex items-center justify-center text-xl font-bold shrink-0">
                    {course.cover}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <div>
                        <h3 className="text-base font-semibold text-gray-900 group-hover:text-primary transition-colors">
                          {course.name}
                        </h3>
                        <p className="text-xs text-gray-500">
                          {course.code} · {course.teacher} ·{' '}
                          {t('{credit}学分', { credit: course.credit })} · {course.hours}
                          {t('学时')}
                        </p>
                      </div>
                      <Badge
                        variant="outline"
                        className="text-xs shrink-0 border-primary/15 text-primary bg-primary/5"
                      >
                        {t(course.type)}
                      </Badge>
                    </div>
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      <span className="text-[10px] px-2 py-0.5 rounded-md bg-primary/5 text-primary font-medium">
                        {t('{progress}% 完成', { progress: course.progress })}
                      </span>
                    </div>
                    {course.nextTask && (
                      <div className="flex items-center gap-2 mt-2 text-xs text-gray-500">
                        <Clock className="w-3.5 h-3.5" />
                        <span>
                          {t('下一步：')}
                          <span className="text-gray-900 font-medium">
                            {course.nextTask}
                          </span> · {t('截止 {deadline}', { deadline: course.nextDeadline ?? '-' })}
                        </span>
                      </div>
                    )}
                  </div>
                  <Button
                    size="sm"
                    className="shrink-0 bg-primary hover:bg-primary/90"
                    onClick={() => router.push(lessonLandingHref(course.id, course.resourceVersion))}
                  >
                    <Play className="w-3.5 h-3.5 mr-1" />
                    {course.status === '已完成' ? t('复习') : t('学习')}
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>
      </div>
    </div>
  )
}

// plus-ui/src-portal/views/portal/workspace/LearningTab.vue
<!--
  我的学习 Tab：顶部 4 指标 + 左「我的实践场景」/ 右「我的课程」，各带状态筛选。
  对齐原 React 版 learning-tab.tsx
  （dashboard?role=student 取 courses/sceneTasks；场景筛选 全部/进行中/待提交/已完成，
   课程筛选 全部/进行中/未开始/已完成；按钮跳 scene/lesson landing 并带排课 resourceVersion）。
-->
<template>
  <div class="learning-tab">
    <!-- 顶部指标 -->
    <div class="stat-grid">
      <StatCard
        title="在修课程"
        :value="loading ? '-' : courses.length"
        :icon="Reading"
        :trend="loading ? '加载中...' : '本学期共 5 门'"
        color="blue"
      />
      <StatCard
        title="场景任务"
        :value="loading ? '-' : sceneTasks.length"
        :icon="Collection"
        :trend="loading ? '加载中...' : '2 个待完成'"
        color="green"
      />
      <StatCard
        title="学习时长"
        :value="loading ? '-' : '86h'"
        :icon="Clock"
        :trend="loading ? '加载中...' : '本月 +12h'"
        :trend-up="!loading"
        color="amber"
      />
      <StatCard
        title="本周完成任务"
        :value="loading ? '-' : 12"
        :icon="Histogram"
        :trend="loading ? '加载中...' : '较上周 +3'"
        :trend-up="!loading"
        color="purple"
      />
    </div>

    <div v-if="!loading" class="content-grid">
      <!-- 实践场景 -->
      <SectionCard title="我的实践场景" :icon="Collection" icon-color="green" action-label="全部场景">
        <el-radio-group v-model="sceneFilter" size="small" class="filter-row">
          <el-radio-button value="all">全部</el-radio-button>
          <el-radio-button value="进行中">进行中</el-radio-button>
          <el-radio-button value="待提交">待提交</el-radio-button>
          <el-radio-button value="已完成">已完成</el-radio-button>
        </el-radio-group>

        <div class="item-list">
          <div v-if="filteredScenes.length === 0" class="empty-line">暂无实践场景</div>
          <div v-for="task in filteredScenes" :key="task.id" class="list-item scene-item">
            <div class="item-cover scene-cover">{{ task.sceneName.charAt(0) }}</div>
            <div class="item-body">
              <div class="item-head">
                <div class="item-head-text">
                  <h3 class="item-title">{{ task.taskName }}</h3>
                  <p class="item-sub">{{ task.sceneName }} · 目标岗位：{{ task.position }}</p>
                </div>
                <span class="status-badge" :style="statusStyle(task.status)">
                  {{ getStatusConfig(task.status).label }}
                </span>
              </div>
              <div class="tag-row">
                <span v-for="tag in task.abilityTags" :key="tag" class="ability-tag">{{ tag }}</span>
              </div>
              <div class="meta-row">
                <span class="meta-cell">
                  <el-icon><Clock /></el-icon>截止 {{ task.deadline || '未设置' }}
                </span>
                <span :style="{ color: DIFFICULTY_TEXT_COLORS[task.difficulty] || '#6b7280' }">
                  难度：{{ task.difficulty }}
                </span>
                <span v-if="task.score !== undefined" class="score-cell">
                  得分：{{ task.score }}/{{ task.totalScore }}
                </span>
              </div>
            </div>
            <el-button
              type="success"
              size="small"
              class="item-action"
              @click="goScene(task)"
            >
              <el-icon><VideoPlay /></el-icon>
              {{ task.status === '已完成' ? '查看' : '继续' }}
            </el-button>
          </div>
        </div>
      </SectionCard>

      <!-- 课程 -->
      <SectionCard title="我的课程" :icon="Reading" icon-color="blue" action-label="全部课程">
        <el-radio-group v-model="courseFilter" size="small" class="filter-row">
          <el-radio-button value="all">全部</el-radio-button>
          <el-radio-button value="进行中">进行中</el-radio-button>
          <el-radio-button value="未开始">未开始</el-radio-button>
          <el-radio-button value="已完成">已完成</el-radio-button>
        </el-radio-group>

        <div class="item-list">
          <div v-if="filteredCourses.length === 0" class="empty-line">暂无课程</div>
          <div v-for="course in filteredCourses" :key="course.id" class="list-item course-item">
            <div class="item-cover course-cover">{{ course.cover }}</div>
            <div class="item-body">
              <div class="item-head">
                <div class="item-head-text">
                  <h3 class="item-title">{{ course.name }}</h3>
                  <p class="item-sub">
                    {{ course.code }} · {{ course.teacher }} · {{ course.credit }}学分 ·
                    {{ course.hours }}学时
                  </p>
                </div>
                <span class="type-badge">{{ course.type }}</span>
              </div>
              <div class="tag-row">
                <span class="progress-tag">{{ course.progress }}% 完成</span>
              </div>
              <div v-if="course.nextTask" class="meta-row">
                <span class="meta-cell">
                  <el-icon><Clock /></el-icon>
                  下一步：<strong>{{ course.nextTask }}</strong> · 截止
                  {{ course.nextDeadline ?? '-' }}
                </span>
              </div>
            </div>
            <el-button type="primary" size="small" class="item-action" @click="goCourse(course)">
              <el-icon><VideoPlay /></el-icon>
              {{ course.status === '已完成' ? '复习' : '学习' }}
            </el-button>
          </div>
        </div>
      </SectionCard>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Clock, Collection, Histogram, Reading, VideoPlay } from '@element-plus/icons-vue';
import SectionCard from './SectionCard.vue';
import StatCard from './StatCard.vue';
import { workspaceDashboardApi } from './workspace-api';
import type { WorkspaceCourse, WorkspaceSceneTask } from './workspace-api';
import {
  DIFFICULTY_TEXT_COLORS,
  getStatusConfig,
  lessonLandingHref,
  sceneLandingHref
} from './workspace-utils';

const router = useRouter();

const courses = ref<WorkspaceCourse[]>([]);
const sceneTasks = ref<WorkspaceSceneTask[]>([]);
const loading = ref(true);
const courseFilter = ref('all');
const sceneFilter = ref('all');

const filteredCourses = computed(() =>
  courses.value.filter((c) => courseFilter.value === 'all' || c.status === courseFilter.value)
);
const filteredScenes = computed(() =>
  sceneTasks.value.filter((s) => sceneFilter.value === 'all' || s.status === sceneFilter.value)
);

function statusStyle(status: string) {
  const cfg = getStatusConfig(status);
  return { color: cfg.color, background: cfg.bg };
}

function goScene(task: WorkspaceSceneTask) {
  router.push(sceneLandingHref(task.scenarioId, task.resourceVersion));
}

function goCourse(course: WorkspaceCourse) {
  router.push(lessonLandingHref(course.id, course.resourceVersion));
}

onMounted(async () => {
  loading.value = true;
  try {
    const res = await workspaceDashboardApi.get({ role: 'student' });
    courses.value = res.courses || [];
    sceneTasks.value = res.sceneTasks || [];
  } catch {
    courses.value = [];
    sceneTasks.value = [];
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
.learning-tab {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.stat-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 16px;
}
@media (min-width: 640px) {
  .stat-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (min-width: 1024px) {
  .stat-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); }
}
.content-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 20px;
}
@media (min-width: 1024px) {
  .content-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
.filter-row {
  margin-bottom: 16px;
}
.item-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.empty-line {
  padding: 32px 0;
  text-align: center;
  font-size: 12px;
  color: #9ca3af;
}
.list-item {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  padding: 16px;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.scene-item:hover {
  border-color: #a7f3d0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}
.course-item:hover {
  border-color: var(--el-color-primary-light-7);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}
.item-cover {
  width: 56px;
  height: 56px;
  flex-shrink: 0;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  font-weight: 700;
}
.scene-cover {
  background: linear-gradient(135deg, #ecfdf5, #f0fdfa);
  color: #059669;
}
.course-cover {
  background: linear-gradient(135deg, var(--el-color-primary-light-9), var(--el-color-primary-light-8));
  color: var(--el-color-primary);
}
.item-body {
  flex: 1;
  min-width: 0;
}
.item-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 8px;
}
.item-head-text {
  min-width: 0;
}
.item-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #111827;
}
.item-sub {
  margin: 2px 0 0;
  font-size: 12px;
  color: #6b7280;
}
.status-badge {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  padding: 2px 10px;
  font-size: 12px;
  font-weight: 500;
}
.type-badge {
  flex-shrink: 0;
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 6px;
  border: 1px solid var(--el-color-primary-light-7);
  color: var(--el-color-primary);
  background: var(--el-color-primary-light-9);
}
.tag-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 8px;
}
.ability-tag {
  font-size: 10px;
  padding: 2px 8px;
  border-radius: 6px;
  background: #ecfdf5;
  color: #059669;
  font-weight: 500;
}
.progress-tag {
  font-size: 10px;
  padding: 2px 8px;
  border-radius: 6px;
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  font-weight: 500;
}
.meta-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 16px;
  margin-top: 8px;
  font-size: 12px;
  color: #6b7280;
}
.meta-cell {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.meta-cell strong {
  color: #111827;
  font-weight: 500;
}
.score-cell {
  color: #059669;
  font-weight: 500;
}
.item-action {
  flex-shrink: 0;
}
</style>
