// frontend/portal-vue/src/views/evaluation/components/question-grading-card.vue
<template>
  <div class="q-card" :class="{ 'q-subjective': !auto }">
    <!-- 卡片头 -->
    <div class="q-header" @click="expanded = !expanded">
      <div class="q-tag-group">
        <span class="q-type-badge" :class="{ 'badge-subjective': !auto }">{{ questionTypeLabel(question.type) }}</span>
        <span class="q-index">第 {{ index + 1 }} 题</span>
      </div>
      <span class="q-content-preview">{{ question.content }}</span>
      <div class="q-score-area" @click.stop>
        <template v-if="!auto">
          <ScoreInput
            :value="localScore"
            :max="question.score || 0"
            :disabled="isGraded"
            @update="onScoreInput"
            @blur="onScoreBlur"
          />
        </template>
        <template v-else>
          <span class="auto-score">{{ autoScore }}</span>
          <span class="auto-max">/ {{ question.score || 0 }}</span>
          <el-tag v-if="correct" type="success" size="small">
            <el-icon class="tag-icon"><CircleCheck /></el-icon>正确
          </el-tag>
          <el-tag v-else type="danger" size="small">
            <el-icon class="tag-icon"><CircleClose /></el-icon>错误
          </el-tag>
        </template>
        <el-icon class="q-chevron" @click.stop="expanded = !expanded">
          <ArrowUp v-if="expanded" />
          <ArrowDown v-else />
        </el-icon>
      </div>
    </div>

    <!-- 展开体 -->
    <div v-if="expanded" class="q-body">
      <p class="q-content">{{ question.content }}</p>

      <div v-if="question.options && question.options.length" class="q-options">
        <div v-for="(opt, oi) in question.options" :key="oi" class="opt-row" :class="optionClass(opt)">
          <span class="opt-letter">{{ String.fromCharCode(65 + oi) }}</span>
          <span class="opt-text">{{ opt }}</span>
          <el-icon v-if="isOptionCorrect(opt)" class="opt-icon opt-icon-ok"><CircleCheck /></el-icon>
          <el-icon v-else-if="isOptionSelected(opt)" class="opt-icon opt-icon-no"><CircleClose /></el-icon>
        </div>
      </div>

      <template v-if="!auto">
        <div class="student-answer-box">
          <div class="box-title">
            <el-icon class="box-title-icon"><User /></el-icon>学生答案
          </div>
          <p class="answer-text">{{ getAnswerLabel(answer) }}</p>
        </div>
        <!-- 参考答案（试卷类题目） -->
        <div class="ref-answer-box">
          <div class="ref-title">参考答案</div>
          <p class="ref-text">{{ getAnswerLabel(question.answer) }}</p>
          <p v-if="question.analysis" class="ref-analysis">{{ question.analysis }}</p>
        </div>
        <div class="teacher-score-row">
          <span class="teacher-label">教师评分</span>
          <ScoreInput
            :value="localScore"
            :max="question.score || 0"
            :disabled="isGraded"
            @update="onLocalOnly"
            @blur="onScoreBlur"
          />
        </div>
      </template>
      <template v-else>
        <div class="answer-compare">
          <div class="answer-pair">
            <span class="a-label">学生答案：</span>
            <span :class="correct ? 'a-correct' : 'a-wrong'">{{ getAnswerLabel(answer) }}</span>
          </div>
          <div class="answer-pair">
            <span class="a-label">正确答案：</span>
            <span class="a-correct">{{ getAnswerLabel(question.answer) }}</span>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ArrowDown, ArrowUp, CircleCheck, CircleClose, User } from '@element-plus/icons-vue';
import ScoreInput from './score-input.vue';
import {
  getAnswerLabel,
  getAutoScore,
  isAnswerCorrect,
  isAutoQuestion,
  questionTypeLabel,
  type ExamQuestionShape
} from './grading-utils';

// 客观题/主观题评分卡片（对齐 React exam-grading/QuestionGradingCard）
const props = defineProps<{
  question: ExamQuestionShape;
  index: number;
  answer: unknown;
  score: number;
  isGraded: boolean;
}>();
const emit = defineEmits<{ (e: 'score-change', questionId: string, newScore: number): void }>();

const localScore = ref(String(props.score));
const expanded = ref(!isAutoQuestion(props.question));
const prevScore = ref(props.score);

// 父级外部更新该题分数（自动评分回填等）时同步本地输入框（对齐 React 渲染期派生状态）
watch(
  () => props.score,
  (s) => {
    if (s !== prevScore.value) {
      prevScore.value = s;
      localScore.value = String(s);
    }
  }
);

const auto = computed(() => isAutoQuestion(props.question));
const correct = computed(() => isAnswerCorrect(props.question, props.answer));
const autoScore = computed(() => (auto.value ? getAutoScore(props.question, props.answer) : 0));

function commitIfValid(val: string): boolean {
  const num = parseFloat(val);
  const max = props.question.score || 0;
  if (!Number.isNaN(num) && num >= 0 && num <= max) {
    emit('score-change', props.question.id, num);
    return true;
  }
  return false;
}

// 仅当达到满分（含「一键满分」按钮）时同步提交，其余输入在失焦时提交
function onScoreInput(val: string) {
  localScore.value = val;
  if (val === String(props.question.score || 0)) commitIfValid(val);
}

// 展开体「教师评分」输入只更新本地，失焦统一提交（对齐 React setLocalScore + onBlur）
function onLocalOnly(val: string) {
  localScore.value = val;
}

function onScoreBlur() {
  if (!commitIfValid(localScore.value)) {
    localScore.value = String(props.score);
  }
}

function isOptionCorrect(opt: string): boolean {
  const ans = props.question.answer;
  return Array.isArray(ans) ? ans.includes(opt) : ans === opt;
}

function isOptionSelected(opt: string): boolean {
  const ans = props.answer;
  return Array.isArray(ans) ? (ans as string[]).includes(opt) : ans === opt;
}

function optionClass(opt: string): string {
  if (isOptionCorrect(opt)) return 'opt-correct';
  if (isOptionSelected(opt)) return 'opt-wrong';
  return 'opt-plain';
}
</script>

<style scoped>
.q-card {
  border: 1px solid #dcdfe6;
  border-radius: 8px;
  overflow: hidden;
  background: #fff;
}
.q-subjective {
  border-color: #f3d19e;
}
.q-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 16px;
  cursor: pointer;
  transition: background 0.2s;
}
.q-header:hover {
  background: #fafafa;
}
.q-subjective .q-header {
  background: rgba(253, 246, 236, 0.5);
}
.q-subjective .q-header:hover {
  background: rgba(253, 246, 236, 0.75);
}
.q-tag-group {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}
.q-type-badge {
  font-size: 10px;
  line-height: 20px;
  padding: 0 6px;
  border-radius: 9999px;
  border: 1px solid #dcdfe6;
  color: #606266;
  background: #fff;
  white-space: nowrap;
}
.badge-subjective {
  border-color: #f3d19e;
  color: #b88230;
}
.q-index {
  font-size: 12px;
  color: #c0c4cc;
  white-space: nowrap;
}
.q-content-preview {
  flex: 1;
  min-width: 0;
  font-size: 14px;
  font-weight: 500;
  color: #303133;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.q-score-area {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}
.auto-score {
  font-size: 14px;
  font-weight: 600;
  color: #606266;
}
.auto-max {
  font-size: 12px;
  color: #c0c4cc;
}
.q-chevron {
  color: #c0c4cc;
  cursor: pointer;
  margin-left: 2px;
}
.q-body {
  padding: 12px 16px 16px;
  border-top: 1px solid #f0f2f5;
  background: #fff;
  display: flex;
  flex-direction: column;
  gap: 14px;
}
.q-content {
  font-size: 14px;
  color: #303133;
  line-height: 1.6;
  font-weight: 500;
  margin: 0;
}
.q-options {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.opt-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  border-radius: 8px;
  border: 1px solid #ebeef5;
  font-size: 14px;
  transition: all 0.2s;
}
.opt-correct {
  background: #f0f9eb;
  border-color: #e1f3d8;
  color: #67c23a;
}
.opt-wrong {
  background: #fef0f0;
  border-color: #fde2e2;
  color: #f56c6c;
}
.opt-plain {
  background: rgba(247, 248, 250, 0.6);
  color: #606266;
}
.opt-letter {
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
  background: #fff;
  color: #909399;
  border: 1px solid #dcdfe6;
}
.opt-correct .opt-letter {
  background: #67c23a;
  color: #fff;
  border-color: #67c23a;
}
.opt-wrong .opt-letter {
  background: #f56c6c;
  color: #fff;
  border-color: #f56c6c;
}
.opt-text {
  flex: 1;
}
.opt-icon {
  flex-shrink: 0;
  font-size: 16px;
}
.opt-icon-ok {
  color: #67c23a;
}
.opt-icon-no {
  color: #f56c6c;
}
.student-answer-box {
  background: rgba(253, 246, 236, 0.5);
  border: 1px solid #faecd8;
  border-radius: 8px;
  padding: 12px;
}
.box-title {
  font-size: 12px;
  font-weight: 500;
  color: #b88230;
  display: flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 6px;
}
.box-title-icon {
  font-size: 12px;
}
.answer-text {
  font-size: 14px;
  color: #303133;
  line-height: 1.6;
  margin: 0;
  white-space: pre-wrap;
}
.ref-answer-box {
  background: #f0f9eb;
  border: 1px solid #e1f3d8;
  border-radius: 8px;
  padding: 12px;
}
.ref-title {
  font-size: 12px;
  font-weight: 500;
  color: #67c23a;
  margin-bottom: 6px;
}
.ref-text {
  font-size: 14px;
  color: #67c23a;
  line-height: 1.6;
  margin: 0;
  white-space: pre-wrap;
}
.ref-analysis {
  font-size: 12px;
  color: #909399;
  line-height: 1.6;
  margin: 6px 0 0;
  white-space: pre-wrap;
}
.teacher-score-row {
  display: flex;
  align-items: center;
  gap: 12px;
}
.teacher-label {
  font-size: 12px;
  color: #909399;
  flex-shrink: 0;
}
.answer-compare {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  background: #f8fafc;
  border-radius: 8px;
  padding: 10px 12px;
  font-size: 13px;
}
.answer-pair {
  display: flex;
  align-items: center;
  gap: 4px;
}
.a-label {
  color: #909399;
}
.a-correct {
  color: #67c23a;
  font-weight: 500;
}
.a-wrong {
  color: #f56c6c;
  font-weight: 500;
}
.tag-icon {
  margin-right: 2px;
  vertical-align: -2px;
}
</style>

// apps/edu/components/shared/exam-grading/question-grading-card.tsx
'use client'

import { useState } from 'react'
import { CheckCircle2, ChevronDown, ChevronUp, Trophy, User, XCircle } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'
import { QUESTION_TYPE_LABELS_SHORT } from '@zhiyu/shared-types'

export const questionTypeLabels = QUESTION_TYPE_LABELS_SHORT

export function toStringArray(v: any): string[] {
  if (Array.isArray(v)) return v.map((x) => String(x).toLowerCase())
  if (typeof v === 'string') return [v.toLowerCase()]
  return []
}

export function isAnswerCorrect(q: any, ans: any): boolean {
  const correct = toStringArray(q.answer)
  const type = q.type
  if (type === 'single') {
    const s = typeof ans === 'string' ? ans.toLowerCase() : ''
    return correct.length > 0 && s === correct[0]
  }
  if (type === 'multiple') {
    const given = toStringArray(ans)
    if (given.length !== correct.length) return false
    const m = new Map<string, number>()
    correct.forEach((c) => m.set(c, (m.get(c) || 0) + 1))
    for (const g of given) {
      const next = (m.get(g) || 0) - 1
      if (next < 0) return false
      m.set(g, next)
    }
    return true
  }
  if (type === 'judge' || type === 'judgment') {
    const s = typeof ans === 'string' ? ans.toLowerCase().trim() : ''
    if (correct.length === 0) return false
    const c = correct[0]
    return s === c || (s === '正确' && c === 'true') || (s === '错误' && c === 'false')
  }
  return false
}

export function getAutoScore(q: any, ans: any): number {
  const type = q.type
  if (type === 'single' || type === 'multiple') return isAnswerCorrect(q, ans) ? q.score || 0 : 0
  if (type === 'judge' || type === 'judgment') return isAnswerCorrect(q, ans) ? q.score || 0 : 0
  return 0
}

export function isAutoQuestion(q: any): boolean {
  const type = q.type
  return type === 'single' || type === 'multiple' || type === 'judge' || type === 'judgment'
}

export function getAnswerLabel(ans: any): string {
  if (Array.isArray(ans)) return ans.join('、')
  if (typeof ans === 'string') return ans
  return '未作答'
}

// ============================================================================
// 统一评分输入
// ============================================================================

export function ScoreInput({
  value,
  max,
  step = 0.5,
  disabled,
  onChange,
  onBlur,
  className,
}: {
  value: string
  max: number
  step?: number
  disabled?: boolean
  onChange: (val: string) => void
  onBlur: () => void
  className?: string
}) {
  return (
    <TooltipProvider delayDuration={200}>
      <div className={cn('flex items-center gap-1.5', className)}>
        <Input
          type="number"
          min={0}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onBlur={onBlur}
          disabled={disabled}
          className="w-16 h-8 text-right text-sm font-semibold border-slate-300 focus-visible:ring-primary"
        />
        <span className="text-xs text-gray-400">/ {max}</span>
        {!disabled && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="h-7 w-7 p-0 text-primary hover:text-primary hover:bg-primary/10"
                onClick={() => {
                  onChange(max.toString())
                }}
              >
                <Trophy className="h-3.5 w-3.5" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="top" className="text-xs">
              <p>一键满分</p>
            </TooltipContent>
          </Tooltip>
        )}
      </div>
    </TooltipProvider>
  )
}

// ============================================================================
// 客观题/主观题评分卡片
// ============================================================================

export function QuestionGradingCard({
  question,
  index,
  answer,
  score,
  isGraded,
  onScoreChange,
}: {
  question: any
  index: number
  answer: any
  score: number
  isGraded: boolean
  onScoreChange: (questionId: string, newScore: number) => void
}) {
  const [localScore, setLocalScore] = useState(score.toString())
  const [expanded, setExpanded] = useState(!isAutoQuestion(question))

  const commitIfValid = (val: string) => {
    const num = parseFloat(val)
    const max = question.score || 0
    if (!isNaN(num) && num >= 0 && num <= max) {
      onScoreChange(question.id, num)
      return true
    }
    return false
  }

  const handleScoreInput = (val: string) => {
    setLocalScore(val)
    // 仅当达到满分（含"一键满分"按钮）时同步提交，其余输入在失焦时提交
    if (val === String(question.score || 0)) {
      commitIfValid(val)
    }
  }

  const handleBlur = () => {
    if (!commitIfValid(localScore)) {
      setLocalScore(score.toString())
    }
  }

  const auto = isAutoQuestion(question)
  const correct = isAnswerCorrect(question, answer)
  const autoScore = auto ? getAutoScore(question, answer) : 0

  return (
    <Card
      className={cn(
        'border-slate-200 overflow-hidden transition-shadow',
        !auto && 'border-amber-200',
      )}
    >
      <CardContent className="p-0">
        <div
          className={cn(
            'flex items-center gap-3 px-4 py-3 cursor-pointer transition-colors',
            !auto ? 'bg-amber-50/50 hover:bg-amber-50/70' : 'bg-white hover:bg-gray-50/60',
          )}
          onClick={() => setExpanded(!expanded)}
        >
          <div className="flex items-center gap-2 shrink-0">
            <Badge
              variant="outline"
              className={cn(
                'text-[10px] h-5 px-1.5 shrink-0',
                !auto && 'border-amber-300 text-amber-700',
              )}
            >
              {questionTypeLabels[question.type] || question.type}
            </Badge>
            <span className="text-xs text-gray-400 shrink-0">第 {index + 1} 题</span>
          </div>
          <span className="text-sm font-medium text-gray-800 flex-1 truncate">
            {question.content}
          </span>
          <div className="flex items-center gap-2 shrink-0">
            {!auto ? (
              <ScoreInput
                value={localScore}
                max={question.score || 0}
                disabled={isGraded}
                onChange={handleScoreInput}
                onBlur={handleBlur}
              />
            ) : (
              <div className="flex items-center gap-1.5">
                <span className="text-sm font-semibold text-gray-700">{autoScore}</span>
                <span className="text-xs text-gray-400">/ {question.score || 0}</span>
                {correct ? (
                  <Badge
                    variant="outline"
                    className="bg-green-50 text-green-600 border-green-200 text-[10px] px-1.5 py-0 h-5 gap-1"
                  >
                    <CheckCircle2 className="h-3 w-3" />
                    正确
                  </Badge>
                ) : (
                  <Badge
                    variant="outline"
                    className="bg-red-50 text-red-600 border-red-200 text-[10px] px-1.5 py-0 h-5 gap-1"
                  >
                    <XCircle className="h-3 w-3" />
                    错误
                  </Badge>
                )}
              </div>
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0 ml-1"
              onClick={(e) => {
                e.stopPropagation()
                setExpanded(!expanded)
              }}
            >
              {expanded ? (
                <ChevronUp className="h-4 w-4 text-gray-400" />
              ) : (
                <ChevronDown className="h-4 w-4 text-gray-400" />
              )}
            </Button>
          </div>
        </div>

        {expanded && (
          <div className="px-4 pb-4 pt-3 border-t border-gray-100 space-y-4 bg-white">
            <p className="text-sm text-gray-800 leading-relaxed font-medium">{question.content}</p>

            {question.options && question.options.length > 0 && (
              <div className="space-y-2">
                {question.options.map((opt: string, idx: number) => {
                  const optLabel = String.fromCharCode(65 + idx)
                  const isSelected = Array.isArray(answer) ? answer.includes(opt) : answer === opt
                  const isCorrect = Array.isArray(question.answer)
                    ? question.answer.includes(opt)
                    : question.answer === opt
                  return (
                    <div
                      key={idx}
                      className={cn(
                        'flex items-center gap-3 text-sm px-3 py-2.5 rounded-lg border transition-colors',
                        isCorrect
                          ? 'bg-green-50 text-green-700 border-green-200'
                          : isSelected && !isCorrect
                            ? 'bg-red-50 text-red-700 border-red-200'
                            : 'bg-gray-50/50 text-gray-600 border-gray-100',
                      )}
                    >
                      <span
                        className={cn(
                          'w-6 h-6 flex items-center justify-center rounded-md text-xs font-semibold',
                          isCorrect
                            ? 'bg-green-500 text-white'
                            : isSelected && !isCorrect
                              ? 'bg-red-500 text-white'
                              : 'bg-white text-gray-500 border border-gray-200',
                        )}
                      >
                        {optLabel}
                      </span>
                      <span className="flex-1">{opt}</span>
                      {isCorrect && <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />}
                      {isSelected && !isCorrect && (
                        <XCircle className="h-4 w-4 text-red-500 shrink-0" />
                      )}
                    </div>
                  )
                })}
              </div>
            )}

            {!auto && (
              <div className="space-y-3">
                <div className="bg-amber-50/40 rounded-lg border border-amber-100 p-3">
                  <div className="text-xs text-amber-700 font-medium mb-1.5 flex items-center gap-1">
                    <User className="h-3 w-3" />
                    学生答案
                  </div>
                  <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                    {getAnswerLabel(answer)}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-xs text-gray-500 shrink-0">教师评分</span>
                  <ScoreInput
                    value={localScore}
                    max={question.score || 0}
                    disabled={isGraded}
                    onChange={setLocalScore}
                    onBlur={handleBlur}
                  />
                </div>
              </div>
            )}

            {auto && (
              <div className="flex flex-wrap items-center gap-4 bg-gray-50 rounded-lg px-3 py-2.5">
                <div className="text-sm">
                  <span className="text-gray-500">学生答案：</span>
                  <span
                    className={correct ? 'text-green-600 font-medium' : 'text-red-600 font-medium'}
                  >
                    {getAnswerLabel(answer)}
                  </span>
                </div>
                <div className="text-sm">
                  <span className="text-gray-500">正确答案：</span>
                  <span className="text-green-600 font-medium">
                    {getAnswerLabel(question.answer)}
                  </span>
                </div>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
