// apps/edu/app/affairs/batches/page.tsx
"use client"

import { BatchGroupPage } from "@/components/shared/batch-group-page"
import { batchApi } from "@/lib/api"

export default function BatchesPage() {
  return (
    <BatchGroupPage
      api={batchApi}
      subtitle="管理教务批次分组，关联审批流程"
      namePlaceholder="例如：2025秋季人才培养方案建设"
      workflowHint="批次内所有人培方案将使用相同的审批流程"
    />
  )
}

// plus-ui/src-portal/views/job/batches.vue
<template>
  <BatchGroupPage
    title="批次分组管理"
    subtitle="管理岗位建设批次分组，关联审批流程"
    :api="batchApi"
    name-placeholder="例如：2026春季电商实训岗位开发"
    workflow-hint="批次内所有岗位将强制使用相同的审批流程"
  />
</template>

<script setup lang="ts">
import BatchGroupPage from '@/components/batch-group-page.vue';
import { batchApi } from '@/api/job';
</script>
