// frontend/edu/app/evaluation/landing/exam-center/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router'
import {
  ArrowLeft,
  ClipboardList,
} from 'lucide-react'
import { SearchInput } from '@/components/shared/search-input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { examUsageApi, examApi } from '@/lib/api'
import type { ExamCenterItem, Exam } from '@/lib/types'
import { ExamCenterCard } from '@/components/evaluation/exam-center-card'
import { Footer } from '@/components/portal/footer'
import { useT } from '@/lib/i18n/locale-provider'

export default function ExamCenterPage() {
  const t = useT()
  const [items, setItems] = useState<ExamCenterItem[]>([])
  const [examCovers, setExamCovers] = useState<Record<string, string>>({})
  const [loading, setLoading] = useState(true)
  const [tab, setTab] = useState<'all' | 'mine'>('all')
  const [keyword, setKeyword] = useState('')

  useEffect(() => {
    examUsageApi
      .center()
      .then(setItems)
      .catch(() => setItems([]))
      .finally(() => setLoading(false))
    examApi
      .list({ status: 'published', limit: 1000 })
      .then((res) => {
        const map: Record<string, string> = {}
        ;(res.items || []).forEach((e: Exam) => {
          if (e.coverImage) map[e.id] = e.coverImage
        })
        setExamCovers(map)
      })
      .catch(() => {})
  }, [])

  const isStudent = items.length > 0 ? items[0]?.studentView : true

  const filtered = useMemo(() => {
    let list = items
    if (tab === 'mine') list = list.filter((i) => i.participatable)
    if (keyword.trim()) {
      const q = keyword.trim().toLowerCase()
      list = list.filter(
        (i) =>
          i.usageName.toLowerCase().includes(q) || i.examName.toLowerCase().includes(q),
      )
    }
    return list
  }, [items, tab, keyword])

  return (
    <div className="min-h-screen flex flex-col bg-[#f5f8ff]">
      {/* 页头 */}
      <div className="bg-gradient-to-br from-primary via-primary/75 to-primary/40">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-8 py-6 sm:py-8">
          <Link
            to="/evaluation/landing"
            className="inline-flex items-center gap-1.5 text-white/80 hover:text-white text-sm mb-4 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            {t('返回测评资源平台')}
          </Link>
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-2xl bg-white/15 backdrop-blur-sm border border-white/20 flex items-center justify-center">
              <ClipboardList className="w-7 h-7 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white">{t('考试中心')}</h1>
              <p className="text-sm text-white/80 mt-1">
                {t('查看全部考试与你可参加的考试，按班级开放')}
              </p>
            </div>
          </div>
        </div>
      </div>

      <main className="max-w-[1400px] mx-auto px-4 sm:px-8 py-6 w-full flex-1">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
          <Tabs value={tab} onValueChange={(v) => setTab(v as 'all' | 'mine')}>
            <TabsList className="bg-white p-1 rounded-xl border border-[#e7e5e4] shadow-sm h-11">
              <TabsTrigger
                value="all"
                className="px-5 rounded-[10px] text-[13px] data-[state=active]:bg-primary data-[state=active]:text-white"
              >
                {t('全部考试 ({n})', { n: items.length })}
              </TabsTrigger>
              {isStudent && (
                <TabsTrigger
                  value="mine"
                  className="px-5 rounded-[10px] text-[13px] data-[state=active]:bg-primary data-[state=active]:text-white"
                >
                  {t('我可参加 ({n})', { n: items.filter((i) => i.participatable).length })}
                </TabsTrigger>
              )}
            </TabsList>
          </Tabs>
          <SearchInput
            wrapperClassName="w-full sm:w-[320px]"
            iconClassName="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-[#94a3b8]"
            value={keyword}
            onChange={setKeyword}
            placeholder={t('搜索考试名称...')}
            inputClassName="pl-10 h-11 bg-white border-[#e7e5e4] rounded-xl text-sm shadow-sm focus:border-primary/30 focus:ring-2 focus:ring-primary/10 transition-all"
          />
        </div>

        {loading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {Array.from({ length: 6 }).map((_, i) => (
              <div
                key={i}
                className="bg-white rounded-2xl border border-[#e7e5e4] h-[220px] animate-pulse shadow-sm"
              />
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-20 text-[#94a3b8] bg-white rounded-2xl border border-[#e7e5e4] shadow-sm">
            <ClipboardList className="h-12 w-12 mx-auto mb-4 opacity-30" />
            <div className="text-[15px] font-medium text-[#475569]">{t('暂无考试')}</div>
            <div className="text-[13px] mt-1">{t('发布后的考试安排会展示在这里')}</div>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {filtered.map((item) => (
              <ExamCenterCard key={item.id} item={item} coverImage={examCovers[item.examId]} />
            ))}
          </div>
        )}
      </main>
      <Footer className="mt-auto" />
    </div>
  )
}

// frontend/portal-vue/src/views/landing/exam-center.vue
<template>
  <div class="exam-center-page">
    <!-- 页头 -->
    <div class="ec-header">
      <div class="ec-header-inner">
        <router-link to="/evaluation/landing" class="ec-back">
          <el-icon><ArrowLeft /></el-icon>
          返回测评资源平台
        </router-link>
        <div class="ec-title-group">
          <div class="ec-title-icon"><el-icon :size="26"><Notebook /></el-icon></div>
          <div>
            <h1 class="ec-title">考试中心</h1>
            <p class="ec-sub">查看全部考试与你可参加的考试，按班级开放</p>
          </div>
        </div>
      </div>
    </div>

    <main class="ec-main">
      <!-- 工具栏：Tab + 搜索 -->
      <div class="ec-toolbar">
        <div class="ec-tabs">
          <button
            type="button"
            :class="['ec-tab', { active: tab === 'all' }]"
            @click="tab = 'all'"
          >
            全部考试 ({{ items.length }})
          </button>
          <button
            v-if="isStudent"
            type="button"
            :class="['ec-tab', { active: tab === 'mine' }]"
            @click="tab = 'mine'"
          >
            我可参加 ({{ participatableCount }})
          </button>
        </div>
        <el-input
          v-model="keyword"
          class="ec-search"
          placeholder="搜索考试名称..."
          clearable
        />
      </div>

      <!-- 列表 -->
      <div v-if="loading" class="ec-grid">
        <div v-for="i in 6" :key="i" class="ec-skeleton" />
      </div>
      <div v-else-if="filtered.length === 0" class="ec-empty">
        <div class="ec-empty-icon"><el-icon :size="44"><Notebook /></el-icon></div>
        <div class="ec-empty-title">暂无考试</div>
        <div class="ec-empty-hint">发布后的考试安排会展示在这里</div>
      </div>
      <div v-else class="ec-grid">
        <ExamCenterCard
          v-for="item in filtered"
          :key="item.id"
          :item="item"
          :cover-image="examCovers[item.examId]"
        />
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ArrowLeft, Notebook } from '@element-plus/icons-vue';
import { examApi } from '@/api/evaluation';
import { request } from '@/api/http';
import type { Exam } from '@/types/evaluation';
import ExamCenterCard from './ExamCenterCard.vue';
import type { ExamCenterItem } from './evaluation-types';

const items = ref<ExamCenterItem[]>([]);
const examCovers = ref<Record<string, string>>({});
const loading = ref(true);
const tab = ref<'all' | 'mine'>('all');
const keyword = ref('');

const isStudent = computed(() => (items.value.length > 0 ? items.value[0].studentView : true));

const participatableCount = computed(() => items.value.filter((i) => i.participatable).length);

const filtered = computed(() => {
  let list = items.value;
  if (tab.value === 'mine') list = list.filter((i) => i.participatable);
  if (keyword.value.trim()) {
    const q = keyword.value.trim().toLowerCase();
    list = list.filter(
      (i) => i.usageName.toLowerCase().includes(q) || i.examName.toLowerCase().includes(q)
    );
  }
  return list;
});

onMounted(async () => {
  // examUsageApi.center() 未封装在 Vue api 层，直接按同一契约调用 GET /evaluation/exam-center
  // （对齐 React examUsageApi.center()；401 时 http.ts 统一跳转登录，等价 React）
  try {
    items.value = await request<ExamCenterItem[]>('/evaluation/exam-center');
  } catch {
    items.value = [];
  } finally {
    loading.value = false;
  }
  try {
    const res = await examApi.list({ status: 'published', limit: 1000 });
    const map: Record<string, string> = {};
    (res.items || []).forEach((e: Exam) => {
      if (e.coverImage) map[e.id] = e.coverImage;
    });
    examCovers.value = map;
  } catch {
    /* 封面加载失败不阻断列表 */
  }
});
</script>

<style scoped>
.exam-center-page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: #f5f8ff;
}

/* ===== 页头 ===== */
.ec-header {
  background: linear-gradient(135deg, var(--el-color-primary) 0%, var(--el-color-primary-light-3) 100%);
}
.ec-header-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding: 24px;
}
.ec-back {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 13px;
  text-decoration: none;
  margin-bottom: 16px;
  transition: color 0.2s;
}
.ec-back:hover {
  color: #fff;
}
.ec-title-group {
  display: flex;
  align-items: center;
  gap: 14px;
}
.ec-title-icon {
  width: 52px;
  height: 52px;
  border-radius: 14px;
  background: rgba(255, 255, 255, 0.15);
  border: 1px solid rgba(255, 255, 255, 0.25);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
}
.ec-title {
  margin: 0;
  font-size: 22px;
  font-weight: 700;
  color: #fff;
}
.ec-sub {
  margin: 4px 0 0;
  font-size: 13px;
  color: rgba(255, 255, 255, 0.85);
}

/* ===== 主体 ===== */
.ec-main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px 24px 48px;
  width: 100%;
  box-sizing: border-box;
  flex: 1;
}
.ec-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 14px;
  flex-wrap: wrap;
  margin-bottom: 20px;
}
.ec-tabs {
  display: flex;
  align-items: center;
  gap: 2px;
  background: #fff;
  padding: 4px;
  border: 1px solid #e7e5e4;
  border-radius: 12px;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.04);
}
.ec-tab {
  border: none;
  background: none;
  padding: 8px 18px;
  border-radius: 9px;
  font-size: 13px;
  color: #475569;
  cursor: pointer;
  transition: all 0.2s;
}
.ec-tab:hover {
  color: var(--el-color-primary);
}
.ec-tab.active {
  background: var(--el-color-primary);
  color: #fff;
  font-weight: 500;
}
.ec-search {
  width: 100%;
  max-width: 320px;
}
.ec-search :deep(.el-input__wrapper) {
  border-radius: 10px;
  box-shadow: 0 0 0 1px #e7e5e4 inset;
  background: #fff;
}
.ec-search :deep(.el-input__wrapper.is-focus) {
  box-shadow: 0 0 0 1px var(--el-color-primary) inset;
}

.ec-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 18px;
}
@media (min-width: 640px) {
  .ec-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (min-width: 1024px) {
  .ec-grid { grid-template-columns: repeat(3, 1fr); }
}
.ec-skeleton {
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 14px;
  height: 220px;
  animation: ec-pulse 1.6s ease-in-out infinite;
}
@keyframes ec-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.ec-empty {
  text-align: center;
  padding: 72px 0;
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 14px;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.03);
}
.ec-empty-icon {
  color: #cbd5e1;
  margin-bottom: 12px;
}
.ec-empty-title {
  font-size: 15px;
  font-weight: 500;
  color: #475569;
}
.ec-empty-hint {
  font-size: 13px;
  color: #94a3b8;
  margin-top: 4px;
}
</style>
