// apps/edu/components/scene/student/scene-card.tsx
'use client'

import Link from 'next/link'
import { Layers, MapPin } from 'lucide-react'
import type { Scenario } from '@/lib/types'
import { formatDate } from '@/lib/format-utils'
import { COVER_GRADIENTS } from '@/lib/cover-gradients'

interface SceneCardProps {
  scenario: Scenario
  index?: number
  taskCount?: number
  knowledgePointCount?: number
}

const industryTagMap: Record<string, { bg: string; text: string; border: string }> = {
  default: { bg: '#fff7ed', text: '#c2410c', border: '#ffedd5' },
}

const professionTagMap: Record<string, { bg: string; text: string; border: string }> = {
  default: {
    bg: 'color-mix(in srgb, var(--primary) 8%, white)',
    text: 'var(--primary)',
    border: 'color-mix(in srgb, var(--primary) 15%, white)',
  },
}

export function SceneCard({
  scenario,
  index = 0,
  taskCount = 0,
  knowledgePointCount = 0,
}: SceneCardProps) {
  const displayTitle = scenario.name
  const coverStyle = scenario.coverImage
    ? { backgroundImage: `url('${scenario.coverImage}')` }
    : { background: COVER_GRADIENTS[index % COVER_GRADIENTS.length] }

  const industryName =
    scenario.industryNames?.[0] || (scenario.industryIds?.length ? '已关联' : '未分类')
  const industryTag = industryTagMap.default
  const professionName =
    scenario.professionNames?.[0] || (scenario.professionIds?.length ? '已关联' : '未分类')
  const professionTag = professionTagMap.default
  const viewCount = scenario.viewCount ?? 0
  const creatorName = scenario.creatorName || scenario.creatorId?.slice(0, 8) || '-'

  return (
    <Link href={`/scene/landing/${scenario.id}`}>
      <div className="group bg-white rounded-2xl overflow-hidden border border-[#e7e5e4] transition-all duration-300 hover:-translate-y-2 hover:shadow-[0_20px_48px_rgba(0,0,0,0.1)] hover:border-primary/30 cursor-pointer h-full flex flex-col">
        <div
          className="h-44 relative bg-cover bg-center flex flex-col justify-end p-4"
          style={coverStyle}
        >
          {!scenario.coverImage && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <Layers className="w-12 h-12 text-[#334155]/45" strokeWidth={1.5} />
            </div>
          )}
          <div className="absolute top-3 left-3 right-3 z-10 flex justify-between">
            <div className="flex gap-1.5">
              <span className="bg-white/70 backdrop-blur-md px-2.5 py-1 rounded-md text-[11px] text-[#334155] font-medium border border-white/50">
                {scenario.version || 'v1.0'}
              </span>
              <span className="bg-white/70 backdrop-blur-md px-2.5 py-1 rounded-md text-[11px] text-[#334155] font-medium border border-white/50">
                创建人：{creatorName}
              </span>
            </div>
          </div>
          <div className="relative z-10">
            <div className="text-base font-bold leading-snug mb-1 line-clamp-2 text-[#1e293b] group-hover:text-[#0f172a] transition-colors">
              {displayTitle}
            </div>
            <div className="text-xs text-[#64748b]">
              场景编码：{scenario.code || scenario.id.slice(0, 8)}
            </div>
          </div>
        </div>
        <div className="p-5 flex-1 flex flex-col">
          <div className="grid grid-cols-3 gap-2 mb-4">
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{viewCount}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">浏览次数</div>
            </div>
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{taskCount || '-'}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">关联任务</div>
            </div>
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{knowledgePointCount || '-'}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">关联知识点</div>
            </div>
          </div>
          <div className="flex flex-wrap gap-2 mb-4">
            <span
              className="text-[11px] px-2.5 py-1 rounded-full flex items-center gap-1 font-medium border"
              style={{
                backgroundColor: industryTag.bg,
                color: industryTag.text,
                borderColor: industryTag.border,
              }}
            >
              <MapPin className="w-3 h-3" /> 面向行业：{industryName}
            </span>
            <span
              className="text-[11px] px-2.5 py-1 rounded-full flex items-center gap-1 font-medium border"
              style={{
                backgroundColor: professionTag.bg,
                color: professionTag.text,
                borderColor: professionTag.border,
              }}
            >
              <MapPin className="w-3 h-3" /> 适用专业：{professionName}
            </span>
          </div>
          <div className="mt-auto grid grid-cols-2 gap-x-6 gap-y-2.5">
            <span className="text-xs text-slate-500">收录：{formatDate(scenario.createdAt)}</span>
            <span className="text-xs text-slate-500">更新：{formatDate(scenario.updatedAt)}</span>
          </div>
        </div>
      </div>
    </Link>
  )
}

// frontend/portal-vue/src/views/landing/SceneCard.vue
<template>
  <!-- 场景卡片：对齐原 React 版 scene-card，
       点击跳转场景详情 /scene/landing/:id。 -->
  <router-link :to="`/scene/landing/${scenario.id}`" class="scene-card">
    <div class="scene-cover" :style="coverStyle">
      <el-icon v-if="!scenario.coverImage" class="scene-cover-icon"><Files /></el-icon>
      <div class="cover-chips">
        <span class="cover-chip">{{ scenario.version || 'V1.0' }}</span>
        <span class="cover-chip">创建人：{{ creatorName }}</span>
      </div>
      <div class="cover-title-block">
        <h3 class="scene-title">{{ scenario.name }}</h3>
        <div class="scene-code">场景编码：{{ scenario.code || scenario.id.slice(0, 8) }}</div>
      </div>
    </div>
    <div class="scene-body">
      <div class="stat-grid">
        <div class="stat-cell">
          <div class="stat-value">{{ scenario.viewCount ?? 0 }}</div>
          <div class="stat-label">浏览次数</div>
        </div>
        <div class="stat-cell">
          <div class="stat-value">{{ taskCount || '-' }}</div>
          <div class="stat-label">关联任务</div>
        </div>
        <div class="stat-cell">
          <div class="stat-value">{{ knowledgePointCount || '-' }}</div>
          <div class="stat-label">关联知识点</div>
        </div>
      </div>
      <div class="tag-row">
        <span class="tag tag-industry">
          <el-icon><Location /></el-icon>
          面向行业：{{ industryName }}
        </span>
        <span class="tag tag-major">
          <el-icon><Location /></el-icon>
          适用专业：{{ professionName }}
        </span>
      </div>
      <div class="meta-row">
        <span>收录：{{ formatDate(scenario.createdAt) }}</span>
        <span>更新：{{ formatDate(scenario.updatedAt) }}</span>
      </div>
    </div>
  </router-link>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Files, Location } from '@element-plus/icons-vue';
import type { Scenario } from '@/types/scene';
import { coverGradientFor, formatDate } from './evaluation-types';

const props = withDefaults(
  defineProps<{
    scenario: Scenario;
    taskCount?: number;
    knowledgePointCount?: number;
  }>(),
  { taskCount: 0, knowledgePointCount: 0 }
);

const coverStyle = computed(() =>
  props.scenario.coverImage
    ? { backgroundImage: `url('${props.scenario.coverImage}')` }
    : { background: coverGradientFor(props.scenario.id) }
);

const creatorName = computed(() => props.scenario.creatorName || props.scenario.creatorId?.slice(0, 8) || '-');
const industryName = computed(() =>
  props.scenario.industryNames?.[0] || (props.scenario.industryIds?.length ? '已关联' : '未分类')
);
const professionName = computed(() =>
  props.scenario.professionNames?.[0] || (props.scenario.professionIds?.length ? '已关联' : '未分类')
);
</script>

<style scoped>
.scene-card {
  display: flex;
  flex-direction: column;
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  overflow: hidden;
  height: 100%;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.04);
  transition: all 0.3s;
  text-decoration: none;
  color: inherit;
}
.scene-card:hover {
  transform: translateY(-8px);
  box-shadow: 0 20px 48px rgba(0, 0, 0, 0.1);
  border-color: var(--el-color-primary-light-5);
}

/* ===== 封面 ===== */
.scene-cover {
  height: 176px;
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  padding: 16px;
  flex-shrink: 0;
  background-size: cover;
  background-position: center;
}
.scene-cover-icon {
  position: absolute;
  inset: 0;
  margin: auto;
  width: 48px;
  height: 48px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 48px;
  pointer-events: none;
}
.cover-chips {
  position: absolute;
  top: 12px;
  left: 12px;
  right: 12px;
  z-index: 10;
  display: flex;
  gap: 6px;
}
.cover-chip {
  background: rgba(15, 23, 42, 0.4);
  backdrop-filter: blur(6px);
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 11px;
  color: #fff;
  font-weight: 500;
  border: 1px solid rgba(255, 255, 255, 0.2);
  white-space: nowrap;
}
.cover-title-block {
  position: relative;
  z-index: 1;
}
.scene-title {
  margin: 0 0 4px;
  font-size: 16px;
  font-weight: 700;
  line-height: 1.3;
  color: #fff;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.scene-code {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.85);
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}

/* ===== 正文 ===== */
.scene-body {
  padding: 20px;
  flex: 1;
  display: flex;
  flex-direction: column;
}
.stat-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
  margin-bottom: 16px;
}
.stat-cell {
  background: #f8fafc;
  border: 1px solid #f1f5f9;
  border-radius: 12px;
  padding: 10px;
  text-align: center;
}
.stat-value {
  font-size: 18px;
  font-weight: 700;
  color: #1e293b;
  line-height: 1.2;
}
.stat-label {
  font-size: 11px;
  color: #94a3b8;
  margin-top: 2px;
}
.tag-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 16px;
}
.tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 11px;
  padding: 4px 10px;
  border-radius: 999px;
  font-weight: 500;
  white-space: nowrap;
}
.tag-industry {
  background: #fff7ed;
  color: #c2410c;
  border: 1px solid #ffedd5;
}
.tag-major {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  border: 1px solid var(--el-color-primary-light-7);
}
.tag .el-icon {
  font-size: 12px;
}
.meta-row {
  margin-top: auto;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px 24px;
  font-size: 12px;
  color: #64748b;
}
</style>
