// frontend/portal-vue/src/views/portal/apps/alliance/brands.vue
<template>
  <div class="brands-page">
    <div class="page-head">
      <h1 class="page-title">品牌运营管理</h1>
      <p class="page-desc">管理六大品牌模块内容，配置前台展示</p>
    </div>
    <div class="brand-grid">
      <router-link
        v-for="card in brandCards"
        :key="card.type"
        :to="card.path"
        class="brand-card"
      >
        <div class="brand-card__head">
          <div class="brand-card__icon" :style="{ background: card.bg, color: card.color }">
            <el-icon :size="20"><component :is="card.icon" /></el-icon>
          </div>
          <span class="brand-card__title">{{ card.label }}</span>
        </div>
        <div class="brand-card__body">
          <p class="brand-card__desc">{{ card.desc }}</p>
          <p class="brand-card__count">{{ counts[card.type] || 0 }} 条内容</p>
        </div>
      </router-link>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { School, OfficeBuilding, Briefcase, Reading, User, Brush } from '@element-plus/icons-vue';
import { allianceBrandApi } from '@/api/alliance';
import { useAuthStore } from '@/stores/auth';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const counts = ref<Record<string, number>>({});

const brandCards = [
  { type: 'talent', label: '人才品牌', desc: '展示学生能力画像与典型就业案例', icon: School, color: '#2563eb', bg: '#eff6ff', path: '/portal/apps/alliance/brands/talent' },
  { type: 'employer', label: '雇主品牌', desc: '展示合作企业/机构的品牌形象', icon: OfficeBuilding, color: '#16a34a', bg: '#f0fdf4', path: '/portal/apps/alliance/brands/employer' },
  { type: 'job', label: '岗位品牌', desc: '展示优质岗位的品牌级运营', icon: Briefcase, color: '#ea580c', bg: '#fff7ed', path: '/portal/apps/alliance/brands/job' },
  { type: 'major', label: '专业品牌', desc: '展示专业建设水平与培养特色', icon: Reading, color: '#9333ea', bg: '#faf5ff', path: '/portal/apps/alliance/brands/major' },
  { type: 'teacher', label: '师资品牌', desc: '展示校本师资与产业导师', icon: User, color: '#dc2626', bg: '#fef2f2', path: '/portal/apps/alliance/brands/teacher' },
  { type: 'culture', label: '文化思政品牌', desc: '展示典型案例、思政资源与文化活动', icon: Brush, color: '#0891b2', bg: '#ecfeff', path: '/portal/apps/alliance/brands/culture' },
];

async function loadCounts() {
  if (!tenantId.value) return;
  try {
    const data = await allianceBrandApi.list({ limit: 500 });
    const c: Record<string, number> = {};
    for (const b of data.items || []) {
      c[b.brandType] = (c[b.brandType] || 0) + 1;
    }
    counts.value = c;
  } catch {
    counts.value = {};
  }
}

onMounted(loadCounts);
</script>

<style scoped>
.brands-page {
  min-height: 100%;
}
.page-head {
  margin-bottom: 24px;
}
.page-title {
  font-size: 20px;
  font-weight: 600;
  color: #0f172a;
  margin: 0;
}
.page-desc {
  margin-top: 4px;
  font-size: 13px;
  color: #64748b;
}
.brand-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}
.brand-card {
  display: block;
  border: 1px solid #e7e5e4;
  border-radius: 12px;
  background: #fff;
  padding: 20px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
  text-decoration: none;
  transition: box-shadow 0.2s;
}
.brand-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}
.brand-card__head {
  display: flex;
  align-items: center;
  gap: 12px;
  padding-bottom: 12px;
}
.brand-card__icon {
  width: 40px;
  height: 40px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.brand-card__title {
  font-size: 15px;
  font-weight: 600;
  color: #0f172a;
}
.brand-card__desc {
  font-size: 12px;
  color: #64748b;
  margin: 0 0 8px;
}
.brand-card__count {
  font-size: 13px;
  font-weight: 600;
  color: #0f172a;
  margin: 0;
}
@media (max-width: 992px) {
  .brand-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}
@media (max-width: 640px) {
  .brand-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// apps/edu/app/portal/apps/alliance/brands/page.tsx
'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { GraduationCap, Building, Briefcase, BookOpen, Users, Palette } from 'lucide-react'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceBrandApi } from '@/lib/api'

const brandCards = [
  {
    type: 'talent',
    label: '人才品牌',
    desc: '展示学生能力画像与典型就业案例',
    icon: GraduationCap,
    color: 'text-blue-600 bg-blue-50',
  },
  {
    type: 'employer',
    label: '雇主品牌',
    desc: '展示合作企业/机构的品牌形象',
    icon: Building,
    color: 'text-green-600 bg-green-50',
  },
  {
    type: 'job',
    label: '岗位品牌',
    desc: '展示优质岗位的品牌级运营',
    icon: Briefcase,
    color: 'text-orange-600 bg-orange-50',
  },
  {
    type: 'major',
    label: '专业品牌',
    desc: '展示专业建设水平与培养特色',
    icon: BookOpen,
    color: 'text-purple-600 bg-purple-50',
  },
  {
    type: 'teacher',
    label: '师资品牌',
    desc: '展示校本师资与产业导师',
    icon: Users,
    color: 'text-red-600 bg-red-50',
  },
  {
    type: 'culture',
    label: '文化思政品牌',
    desc: '展示典型案例、思政资源与文化活动',
    icon: Palette,
    color: 'text-cyan-600 bg-cyan-50',
  },
]

export default function AllianceBrandsPage() {
  const { tenantId } = usePortalAuth()
  const [counts, setCounts] = useState<Record<string, number>>({})

  useEffect(() => {
    if (!tenantId) return
    const loadCounts = async () => {
      try {
        const data = await allianceBrandApi.list()
        const c: Record<string, number> = {}
        for (const b of data.items || []) {
          c[b.brandType] = (c[b.brandType] || 0) + 1
        }
        setCounts(c)
      } catch {}
    }
    loadCounts()
  }, [tenantId])

  const pageMap: Record<string, string> = {
    talent: '/portal/apps/alliance/brands/talent',
    employer: '/portal/apps/alliance/brands/employer',
    job: '/portal/apps/alliance/brands/job',
    major: '/portal/apps/alliance/brands/major',
    teacher: '/portal/apps/alliance/brands/teacher',
    culture: '/portal/apps/alliance/brands/culture',
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-foreground">品牌运营管理</h1>
        <p className="text-muted-foreground text-sm mt-1">管理六大品牌模块内容，配置前台展示</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {brandCards.map((card) => {
          const Icon = card.icon
          const count = counts[card.type] || 0
          return (
            <Link key={card.type} href={pageMap[card.type]}>
              <Card className="hover:shadow-md transition-shadow cursor-pointer h-full">
                <CardHeader className="flex flex-row items-center gap-3 pb-2">
                  <div className={`p-2 rounded-lg ${card.color}`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <CardTitle className="text-base">{card.label}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-xs">{card.desc}</CardDescription>
                  <p className="text-sm font-semibold mt-2">{count} 条内容</p>
                </CardContent>
              </Card>
            </Link>
          )
        })}
      </div>
    </div>
  )
}
