// apps/edu/components/shared/landing-filter-row.tsx
'use client'

import { useRef, useState, useEffect } from 'react'

const ACCENT_CLASSES: Record<
  string,
  {
    selected: string
    unselected: string
    expand: string
    border: string
  }
> = {
  purple: {
    selected: 'bg-primary text-white border-primary shadow-sm',
    unselected:
      'bg-slate-50 text-[#475569] border-slate-200 hover:border-primary/30 hover:text-primary hover:bg-primary/5',
    expand: 'text-primary hover:text-primary',
    border: 'border-b border-dashed border-[#cbd5e1]',
  },
  emerald: {
    selected: 'bg-emerald-500 text-white border-emerald-500 shadow-sm',
    unselected:
      'bg-slate-50 text-[#475569] border-slate-200 hover:border-emerald-300 hover:text-emerald-600 hover:bg-emerald-50/50',
    expand: 'text-emerald-500 hover:text-emerald-600',
    border: 'border-b border-dashed border-[#cbd5e1]',
  },
  blue: {
    selected: 'bg-primary text-white border-primary shadow-sm',
    unselected:
      'bg-slate-50 text-[#475569] border-slate-200 hover:border-primary/30 hover:text-primary hover:bg-primary/5',
    expand: 'text-primary hover:text-primary',
    border: 'border-b border-dashed border-[#cbd5e1]',
  },
}

interface LandingFilterRowProps {
  label: string
  items: string[]
  selected: string
  onSelect: (item: string) => void
  showBorder?: boolean
  accentColor?: 'purple' | 'emerald' | 'blue'
}

export function LandingFilterRow({
  label,
  items,
  selected,
  onSelect,
  showBorder = true,
  accentColor = 'purple',
}: LandingFilterRowProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [expanded, setExpanded] = useState(false)
  const [overflow, setOverflow] = useState(false)

  useEffect(() => {
    const el = containerRef.current
    if (el) setOverflow(el.scrollHeight > el.clientHeight + 2)
  }, [items])

  const cls = ACCENT_CLASSES[accentColor] || ACCENT_CLASSES.purple

  if (items.length <= 1) return null

  return (
    <div className={`flex items-start gap-3 sm:gap-4 py-3 ${showBorder ? cls.border : ''}`}>
      <span className="text-sm text-[#374151] font-medium min-w-[40px] pt-1.5">{label}</span>
      <div className="flex-1 min-w-0">
        <div
          ref={containerRef}
          className={`flex flex-wrap gap-2.5 ${expanded ? '' : 'max-h-[80px] overflow-hidden'}`}
        >
          {items.map((item) => (
            <button
              key={item}
              onClick={() => onSelect(item)}
              className={`px-3.5 py-1.5 rounded-full text-[13px] border transition-all whitespace-nowrap ${
                selected === item ? cls.selected : cls.unselected
              }`}
            >
              {item}
            </button>
          ))}
        </div>
        {overflow && (
          <button
            onClick={() => setExpanded(!expanded)}
            className={`text-[12px] ${cls.expand} mt-1.5 font-medium`}
          >
            {expanded ? '收起' : '展开'}
          </button>
        )}
      </div>
    </div>
  )
}

// plus-ui/src-portal/views/landing/LandingFilterRow.vue
<template>
  <!-- 筛选行（行业/专业等 chip 组，超出一行自动折叠 + 展开/收起）：
       对齐原 React 版 landing-filter-row（accentColor=primary）。 -->
  <div v-if="items.length > 1" class="filter-row" :class="{ 'filter-row-border': showBorder }">
    <span class="filter-label">{{ label }}</span>
    <div class="filter-body">
      <div
        ref="containerRef"
        class="filter-chips"
        :class="{ 'filter-chips-collapsed': !expanded }"
      >
        <button
          v-for="item in items"
          :key="item"
          type="button"
          :class="['chip', { active: selected === item }]"
          @click="emit('update:selected', item)"
        >
          {{ item }}
        </button>
      </div>
      <button v-if="overflow" type="button" class="expand-btn" @click="expanded = !expanded">
        {{ expanded ? '收起' : '展开' }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';

const props = defineProps<{
  label: string;
  items: string[];
  selected: string;
  showBorder?: boolean;
}>();

const emit = defineEmits<{
  (e: 'update:selected', value: string): void;
}>();

const containerRef = ref<HTMLElement | null>(null);
const expanded = ref(false);
const overflow = ref(false);

function checkOverflow() {
  const el = containerRef.value;
  if (el) overflow.value = el.scrollHeight > el.clientHeight + 2;
}

onMounted(checkOverflow);
watch(() => props.items, checkOverflow);
</script>

<style scoped>
.filter-row {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  flex-wrap: wrap;
  padding: 12px 0;
}
.filter-row-border {
  border-bottom: 1px dashed #cbd5e1;
}
.filter-label {
  font-size: 14px;
  font-weight: 500;
  color: #374151;
  min-width: 40px;
  padding-top: 6px;
  flex-shrink: 0;
}
.filter-body {
  flex: 1;
  min-width: 0;
}
.filter-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 10px;
}
.filter-chips-collapsed {
  max-height: 80px;
  overflow: hidden;
}
.chip {
  border: 1px solid #e2e8f0;
  background: #f8fafc;
  color: #475569;
  font-size: 13px;
  padding: 6px 14px;
  border-radius: 999px;
  cursor: pointer;
  white-space: nowrap;
  transition: all 0.2s;
}
.chip:hover {
  border-color: var(--el-color-primary-light-5);
  color: var(--el-color-primary);
  background: var(--el-color-primary-light-9);
}
.chip.active {
  background: var(--el-color-primary);
  border-color: var(--el-color-primary);
  color: #fff;
  font-weight: 500;
  box-shadow: 0 2px 8px rgba(64, 158, 255, 0.3);
}
.expand-btn {
  border: none;
  background: none;
  color: var(--el-color-primary);
  font-size: 12px;
  font-weight: 500;
  margin-top: 6px;
  padding: 0;
  cursor: pointer;
}
</style>
