// apps/edu/app/portal/apps/page.tsx
'use client'

import { useState, useEffect, useRef, useMemo } from 'react'
import Link from 'next/link'
import {
  Settings,
  Users,
  Briefcase,
  Layers,
  CheckCircle,
  BookOpen,
  Sparkles,
  Share2,
  Calendar,
  BarChart3,
  Rocket,
  GraduationCap,
  ChevronRight,
  ExternalLink,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { TooltipProvider } from '@/components/ui/tooltip'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { getPlatformCardModules, platformModuleDefs } from '@/lib/navigation-config'
import { getServiceClickCounts, recordServiceClick } from '@/lib/frequent-services'
import { useT } from '@/lib/i18n/locale-provider'

const menuItems = [
  { id: 'system', label: '系统管理', icon: Settings },
  { id: 'career', label: '职业岗位学习平台', icon: Briefcase },
  { id: 'scene', label: '实践场景学习平台', icon: Layers },
  { id: 'course', label: '数字课程服务平台', icon: BookOpen },
  { id: 'ability', label: '能力评价与测评资源管理平台', icon: CheckCircle },
  { id: 'resource', label: '教学资源共享服务平台', icon: Share2 },
  { id: 'alliance', label: '产教协同与人才品牌运营平台', icon: Users },
  { id: 'affairs', label: '教务服务平台', icon: Calendar },
  { id: 'ai', label: 'AI 智能服务平台', icon: Sparkles },
  { id: 'opc', label: 'OPC专区', icon: Rocket },
  { id: 'decision', label: '敏捷决策中心', icon: BarChart3 },
  { id: 'research', label: '教科研服务中心', icon: GraduationCap },
]

const quickAccess = [
  { icon: Settings, label: '组织权限', href: '/portal/apps/system/org-user/roles' },
  { icon: Briefcase, label: '岗位资源管理', href: '/job/positions' },
  { icon: Layers, label: '场景资源管理', href: '/scene' },
  { icon: BarChart3, label: '日志管理', href: '/portal/apps/system/logs/login' },
]

interface PlatformStyle {
  iconColor: string
  iconBg: string
}

const platformStyles: Record<string, PlatformStyle> = {
  system: { iconColor: 'text-blue-600', iconBg: 'bg-blue-50' },
  alliance: { iconColor: 'text-rose-600', iconBg: 'bg-rose-50' },
  career: { iconColor: 'text-purple-600', iconBg: 'bg-purple-50' },
  course: { iconColor: 'text-amber-600', iconBg: 'bg-amber-50' },
  scene: { iconColor: 'text-cyan-600', iconBg: 'bg-cyan-50' },
  ability: { iconColor: 'text-emerald-600', iconBg: 'bg-emerald-50' },
  affairs: { iconColor: 'text-teal-600', iconBg: 'bg-teal-50' },
  ai: { iconColor: 'text-indigo-600', iconBg: 'bg-indigo-50' },
  resource: { iconColor: 'text-blue-600', iconBg: 'bg-blue-50' },
  opc: { iconColor: 'text-orange-600', iconBg: 'bg-orange-50' },
  decision: { iconColor: 'text-sky-600', iconBg: 'bg-sky-50' },
  research: { iconColor: 'text-violet-600', iconBg: 'bg-violet-50' },
}

interface ModuleItem {
  id: string
  title: string
  desc?: string
  href: string
}

interface FrequentService {
  href: string
  label: string
  icon: typeof Settings
}

interface ModuleSection {
  id: string
  label: string
  href: string
  icon: typeof Settings
  iconColor: string
  iconBg: string
  modules: ModuleItem[]
}

function ModuleCard({ module }: { module: ModuleItem }) {
  const t = useT()
  const isExternal = module.href.startsWith('http')
  const href = module.href

  const cardContent = (
    <>
      <h3 className="text-sm font-medium text-foreground group-hover:text-primary transition-colors mb-2 pr-2 leading-tight flex items-center gap-1">
        {t(module.title)}
        {isExternal && (
          <ExternalLink className="w-3 h-3 text-muted-foreground group-hover:text-primary/70" />
        )}
      </h3>
      <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2">
        {t(module.desc ?? '')}
      </p>
      <div className="absolute bottom-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
        <ChevronRight className="w-4 h-4 text-primary" />
      </div>
    </>
  )

  const className =
    'bg-card rounded-xl p-5 hover:shadow-lg hover:shadow-border/50 transition-all group relative border border-border hover:border-primary/20 block'

  if (isExternal) {
    return (
      <a
        key={module.id}
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        onClick={() => recordServiceClick(module.href)}
        className={className}
      >
        {cardContent}
      </a>
    )
  }

  if (href === '#') {
    return (
      <div key={module.id} className={`${className} cursor-default opacity-60`}>
        {cardContent}
      </div>
    )
  }

  return (
    <Link
      key={module.id}
      href={href}
      onClick={() => recordServiceClick(module.href)}
      className={className}
    >
      {cardContent}
    </Link>
  )
}

export default function AppsPage() {
  const t = useT()
  const { hasMenuPermission, subscriptionModules } = usePortalAuth()
  const [activeMenu, setActiveMenu] = useState(menuItems[0].id)
  const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({})
  const contentRef = useRef<HTMLDivElement>(null)
  const subscriptionLoading = subscriptionModules === null

  const allModules: ModuleSection[] = useMemo(() => {
    return menuItems
      .filter((item) => subscriptionModules?.[item.id] === true)
      .map((item) => {
        const modules = getPlatformCardModules(item.id).filter((m) => hasMenuPermission(m.href))
        return {
          id: item.id,
          label: item.label,
          href: platformModuleDefs[item.id]?.href ?? '#',
          icon: item.icon,
          ...platformStyles[item.id],
          modules,
        }
      })
      .filter((section) => section.modules.length > 0)
  }, [hasMenuPermission, subscriptionModules])

  const servicePool: FrequentService[] = useMemo(() => {
    const pool: FrequentService[] = quickAccess.map((item) => ({ ...item }))
    for (const section of allModules) {
      for (const m of section.modules) {
        if (!pool.some((p) => p.href === m.href)) {
          pool.push({ href: m.href, label: m.title, icon: section.icon })
        }
      }
    }
    return pool
  }, [allModules])

  const serviceClickCounts = useMemo(() => getServiceClickCounts(), [])

  const visibleQuickAccess = useMemo(() => {
    const visible = servicePool.filter((item) => hasMenuPermission(item.href))
    const hasClicks = visible.some((item) => (serviceClickCounts[item.href] || 0) > 0)
    if (!hasClicks) {
      return visible.filter((item) => quickAccess.some((q) => q.href === item.href)).slice(0, 6)
    }
    return [...visible]
      .sort((a, b) => (serviceClickCounts[b.href] || 0) - (serviceClickCounts[a.href] || 0))
      .slice(0, 6)
  }, [servicePool, serviceClickCounts, hasMenuPermission])

  useEffect(() => {
    const handleScroll = () => {
      if (!contentRef.current) return

      const scrollTop = contentRef.current.scrollTop
      let currentSection = menuItems[0].id

      for (const section of allModules) {
        const el = sectionRefs.current[section.id]
        if (el) {
          const offsetTop = el.offsetTop - 100
          if (scrollTop >= offsetTop) {
            currentSection = section.id
          }
        }
      }

      setActiveMenu(currentSection)
    }

    const contentEl = contentRef.current
    if (contentEl) {
      contentEl.addEventListener('scroll', handleScroll)
      return () => contentEl.removeEventListener('scroll', handleScroll)
    }
  }, [allModules])

  const scrollToSection = (sectionId: string) => {
    const el = sectionRefs.current[sectionId]
    if (el && contentRef.current) {
      const offsetTop = el.offsetTop - 20
      contentRef.current.scrollTo({ top: offsetTop, behavior: 'smooth' })
    }
    setActiveMenu(sectionId)
  }

  return (
    <TooltipProvider>
      <div className="min-h-[calc(100vh-3.5rem)] bg-[#f5f7fa] pt-0">
        {/* Quick Access Bar */}
        <div className="bg-background border-b border-border px-4 md:px-6 py-3 sticky top-14 z-10 shadow-sm space-y-2">
          <div className="hidden md:flex items-center gap-4">
            <div className="flex items-center gap-2 text-sm text-muted-foreground shrink-0">
              <Sparkles className="w-4 h-4 text-amber-500" />
              <span className="font-medium">{t('常用服务')}</span>
            </div>
            <div className="flex items-center gap-2 overflow-x-auto">
              {visibleQuickAccess.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  onClick={() => recordServiceClick(item.href)}
                  className="flex items-center gap-2 px-3 py-1.5 bg-muted rounded-lg hover:bg-primary/5 hover:text-primary transition-all shrink-0 group border border-border"
                >
                  <item.icon className="w-4 h-4 text-muted-foreground group-hover:text-primary transition-colors" />
                  <span className="text-sm text-muted-foreground group-hover:text-primary transition-colors">
                    {t(item.label)}
                  </span>
                </Link>
              ))}
            </div>
          </div>

          {/* 移动端分类芯片导航 */}
          <div className="md:hidden flex gap-2 overflow-x-auto scrollbar-hide -mx-1 px-1">
            {allModules.map((section) => (
              <button
                key={section.id}
                onClick={() => scrollToSection(section.id)}
                className={cn(
                  'shrink-0 px-3 py-1.5 rounded-full text-xs whitespace-nowrap transition-colors border',
                  activeMenu === section.id
                    ? 'bg-primary text-white border-primary'
                    : 'bg-muted text-muted-foreground border-border hover:text-foreground',
                )}
              >
                {t(section.label)}
              </button>
            ))}
          </div>
        </div>

        <div className="flex">
          {/* Left Sidebar */}
          <aside className="hidden md:block w-56 bg-background shrink-0 min-h-[calc(100vh-3.5rem-40px)] sticky top-[96px] self-start border-r border-border shadow-sm">
            <nav className="p-2 space-y-2">
              {menuItems
                .filter((m) => allModules.some((s) => s.id === m.id))
                .map((item) => {
                  const Icon = item.icon
                  const isActive = activeMenu === item.id
                  return (
                    <button
                      key={item.id}
                      onClick={() => scrollToSection(item.id)}
                      className={cn(
                        'w-full flex items-center gap-3 px-3 py-3 rounded-lg text-sm transition-all text-left group',
                        isActive
                          ? 'bg-primary text-white shadow-md shadow-primary/20'
                          : 'text-muted-foreground hover:bg-muted hover:text-foreground',
                      )}
                    >
                      <Icon
                        className={cn(
                          'w-4 h-4 shrink-0 transition-colors',
                          isActive
                            ? 'text-white'
                            : 'text-muted-foreground group-hover:text-muted-foreground',
                        )}
                      />
                      <span className="truncate">{t(item.label)}</span>
                      {isActive && <ChevronRight className="w-4 h-4 ml-auto text-white/70" />}
                    </button>
                  )
                })}
            </nav>
          </aside>

          {/* Main Content */}
          <main
            ref={contentRef}
            className="flex-1 px-4 pb-4 pt-4 overflow-y-auto max-h-[calc(100vh-3.5rem-40px)] relative"
          >
            {subscriptionLoading ? (
              <div className="flex items-center justify-center h-64">
                <div className="text-sm text-muted-foreground">{t('加载中...')}</div>
              </div>
            ) : allModules.length === 0 ? (
              <div className="flex items-center justify-center h-64">
                <div className="text-sm text-muted-foreground">
                  {t('暂无可用应用，请联系管理员开通套餐')}
                </div>
              </div>
            ) : (
              allModules.map((section) => {
                const SectionIcon = section.icon
                return (
                  <div
                    key={section.id}
                    ref={(el) => {
                      sectionRefs.current[section.id] = el
                    }}
                    className="mb-5"
                  >
                    {/* Section Title */}
                    <div className="flex items-center gap-3 mb-3">
                      <div
                        className={cn(
                          'w-9 h-9 rounded-lg flex items-center justify-center',
                          section.iconBg,
                        )}
                      >
                        <SectionIcon className={cn('w-5 h-5', section.iconColor)} />
                      </div>
                      {section.href && section.href !== '#' ? (
                        <Link
                          href={section.href}
                          className="text-base font-semibold text-foreground hover:text-primary transition-colors"
                        >
                          {t(section.label)}
                        </Link>
                      ) : (
                        <h2 className="text-base font-semibold text-foreground">{t(section.label)}</h2>
                      )}
                      <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full">
                        {t('{count} 个模块', { count: section.modules.length })}
                      </span>
                    </div>

                    {/* Module Cards Grid */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 gap-3 sm:gap-4">
                      {section.modules.map((module) => (
                        <ModuleCard key={module.id} module={module} />
                      ))}
                    </div>
                  </div>
                )
              })
            )}
          </main>
        </div>
      </div>
    </TooltipProvider>
  )
}

// frontend/portal-vue/src/views/portal/apps.vue
<template>
  <div class="apps-page">
    <!-- 常用服务栏 -->
    <div class="quick-bar">
      <div class="quick-head">
        <div class="quick-title">
          <el-icon :size="16" class="quick-spark"><MagicStick /></el-icon>
          <span>常用服务</span>
        </div>
        <div class="quick-chips">
          <button
            v-for="item in visibleQuickAccess"
            :key="item.href"
            type="button"
            class="quick-chip"
            @click="onServiceClick(item)"
          >
            <el-icon :size="16"><component :is="iconOf(item.icon)" /></el-icon>
            <span>{{ item.label }}</span>
          </button>
        </div>
      </div>
    </div>

    <div class="apps-body">
      <!-- 左侧栏（桌面端） -->
      <aside class="apps-aside">
        <nav class="aside-nav">
          <button
            v-for="item in visibleMenuItems"
            :key="item.id"
            type="button"
            class="aside-item"
            :class="{ active: activeMenu === item.id }"
            @click="scrollToSection(item.id)"
          >
            <el-icon :size="16"><component :is="iconOf(item.icon)" /></el-icon>
            <span class="aside-label">{{ item.label }}</span>
            <el-icon v-if="activeMenu === item.id" :size="16" class="aside-arrow"><Right /></el-icon>
          </button>
        </nav>
      </aside>

      <!-- 主内容 -->
      <main ref="contentRef" class="apps-main" @scroll="onScroll">
        <div v-if="authLoading" class="apps-state">
          <span>加载中...</span>
        </div>

        <div v-else-if="allModules.length === 0" class="apps-state">
          <span>暂无可用应用，请联系管理员开通套餐</span>
        </div>

        <template v-else>
          <div
            v-for="section in allModules"
            :key="section.id"
            :ref="(el) => setSectionRef(section.id, el)"
            class="module-section"
          >
            <div class="section-head">
              <div class="section-icon" :style="{ color: section.color, background: section.bg }">
                <el-icon :size="20"><component :is="iconOf(section.icon)" /></el-icon>
              </div>
              <a
                v-if="section.href && section.href !== '#'"
                class="section-title-link"
                @click="go(section.href)"
              >
                {{ section.label }}
              </a>
              <h2 v-else class="section-title">{{ section.label }}</h2>
              <span class="section-count">{{ section.modules.length }} 个模块</span>
            </div>

            <div class="module-grid">
              <div
                v-for="module in section.modules"
                :key="module.id"
                class="module-card"
                :class="{ 'module-card-disabled': module.href === '#' }"
                @click="onModuleClick(module)"
              >
                <h3 class="module-title">
                  {{ module.title }}
                  <el-icon v-if="isExternal(module.href)" :size="12" class="module-ext"><TopRight /></el-icon>
                </h3>
                <p class="module-desc">{{ module.desc || '' }}</p>
                <div class="module-enter">
                  <el-icon :size="16"><Right /></el-icon>
                </div>
              </div>
            </div>
          </div>
        </template>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import type { Component } from 'vue';
import {
  Briefcase,
  Calendar,
  CircleCheck,
  Grid,
  MagicStick,
  Promotion,
  Reading,
  Right,
  School,
  Setting,
  Share,
  TopRight,
  TrendCharts,
  UserFilled
} from '@element-plus/icons-vue';
import {
  APPS_MENU_ITEMS,
  APPS_PLATFORM_HREFS,
  APPS_PLATFORM_MODULES,
  APPS_PLATFORM_STYLES,
  APPS_QUICK_ACCESS,
  getServiceClickCounts,
  hasMenuPermission,
  loadPortalAuth,
  recordServiceClick,
  resolveActiveRole,
  type AppsModuleItem
} from './portal-navigation';
import type { Role } from '@/types/system';
import type { User } from '@/types/user';

const ICONS: Record<string, Component> = {
  setting: Setting,
  briefcase: Briefcase,
  layers: Grid,
  book: Reading,
  'check-circle': CircleCheck,
  share: Share,
  users: UserFilled,
  calendar: Calendar,
  sparkles: MagicStick,
  rocket: Promotion,
  'bar-chart': TrendCharts,
  'graduation-cap': School
};

function iconOf(key: string): Component {
  return ICONS[key] || Grid;
}

const router = useRouter();

/* ---------- 登录态 + 订阅 + 菜单权限 ---------- */
const authLoading = ref(true);
const user = ref<User | null>(null);
const roles = ref<Role[]>([]);
const activeRoleCode = ref<string | undefined>(undefined);
const menus = ref<unknown>(null);
const subscriptionModules = ref<Record<string, boolean> | null>(null);

function hasMenuPerm(path: string): boolean {
  return hasMenuPermission(activeRoleCode.value, menus.value, path, subscriptionModules.value);
}

interface ModuleSection {
  id: string;
  label: string;
  href: string;
  icon: string;
  color: string;
  bg: string;
  modules: AppsModuleItem[];
}

const allModules = computed<ModuleSection[]>(() => {
  return APPS_MENU_ITEMS.filter((item) => subscriptionModules.value?.[item.id] === true)
    .map((item) => {
      const modules = (APPS_PLATFORM_MODULES[item.id] || []).filter((m) => hasMenuPerm(m.href));
      const style = APPS_PLATFORM_STYLES[item.id] || { color: '#2563eb', bg: '#eff6ff' };
      return {
        id: item.id,
        label: item.label,
        href: APPS_PLATFORM_HREFS[item.id] ?? '#',
        icon: item.icon,
        color: style.color,
        bg: style.bg,
        modules
      };
    })
    .filter((section) => section.modules.length > 0);
});

const visibleMenuItems = computed(() =>
  APPS_MENU_ITEMS.filter((m) => allModules.value.some((s) => s.id === m.id))
);

/* ---------- 常用服务 ---------- */
interface ServiceItem {
  icon: string;
  label: string;
  href: string;
}

const servicePool = computed<ServiceItem[]>(() => {
  const pool: ServiceItem[] = APPS_QUICK_ACCESS.map((item) => ({ ...item }));
  for (const section of allModules.value) {
    for (const m of section.modules) {
      if (!pool.some((p) => p.href === m.href)) {
        pool.push({ href: m.href, label: m.title, icon: section.icon });
      }
    }
  }
  return pool;
});

const serviceClickCounts = ref<Record<string, number>>({});

const visibleQuickAccess = computed<ServiceItem[]>(() => {
  const visible = servicePool.value.filter((item) => hasMenuPerm(item.href));
  const hasClicks = visible.some((item) => (serviceClickCounts.value[item.href] || 0) > 0);
  if (!hasClicks) {
    return visible.filter((item) => APPS_QUICK_ACCESS.some((q) => q.href === item.href)).slice(0, 6);
  }
  return [...visible]
    .sort((a, b) => (serviceClickCounts.value[b.href] || 0) - (serviceClickCounts.value[a.href] || 0))
    .slice(0, 6);
});

/* ---------- 滚动监听 + 侧栏联动 ---------- */
const contentRef = ref<HTMLElement | null>(null);
const sectionEls: Record<string, HTMLElement | null> = {};
const activeMenu = ref(APPS_MENU_ITEMS[0].id);

function setSectionRef(id: string, el: unknown) {
  sectionEls[id] = (el as HTMLElement) || null;
}

function onScroll() {
  const el = contentRef.value;
  if (!el) return;
  const scrollTop = el.scrollTop;
  let current = APPS_MENU_ITEMS[0].id;
  for (const section of allModules.value) {
    const node = sectionEls[section.id];
    if (node) {
      const offsetTop = node.offsetTop - 100;
      if (scrollTop >= offsetTop) current = section.id;
    }
  }
  activeMenu.value = current;
}

function scrollToSection(sectionId: string) {
  const el = sectionEls[sectionId];
  const content = contentRef.value;
  if (el && content) {
    const offsetTop = el.offsetTop - 20;
    content.scrollTo({ top: offsetTop, behavior: 'smooth' });
  }
  activeMenu.value = sectionId;
}

/* ---------- 点击 ---------- */
function isExternal(href: string): boolean {
  return href.startsWith('http');
}

function go(href: string) {
  if (!href || href === '#') return;
  if (isExternal(href)) {
    window.open(href, '_blank', 'noopener,noreferrer');
    return;
  }
  router.push(href);
}

function onServiceClick(item: ServiceItem) {
  recordServiceClick(item.href);
  // YI Know 助手卡片（/portal/apps/ai/chat）在 Vue 无对话弹窗，落到 AI 落地页
  const target = item.href === '/portal/apps/ai/chat' ? '/portal/apps/ai/landing' : item.href;
  go(target);
}

function onModuleClick(module: AppsModuleItem) {
  recordServiceClick(module.href);
  if (module.href === '#') return;
  // YI Know 助手卡片（/portal/apps/ai/chat）在 Vue 无对话弹窗，落到 AI 落地页
  const target = module.href === '/portal/apps/ai/chat' ? '/portal/apps/ai/landing' : module.href;
  go(target);
}

onMounted(async () => {
  serviceClickCounts.value = getServiceClickCounts();
  try {
    const { me, subscriptionModules: subs } = await loadPortalAuth();
    user.value = me?.user ?? null;
    roles.value = me?.roles ?? [];
    subscriptionModules.value = subs;
    const active = resolveActiveRole(user.value?.id, roles.value);
    activeRoleCode.value = active?.code;
    const perms = active?.permissions as Record<string, unknown> | undefined;
    menus.value = perms?.menus ?? null;
  } finally {
    authLoading.value = false;
  }
});
</script>

<style scoped>
.apps-page {
  min-height: calc(100vh - 56px);
  background: #f5f7fa;
}

/* 常用服务栏 */
.quick-bar {
  position: sticky;
  top: 56px;
  z-index: 10;
  background: #fff;
  border-bottom: 1px solid #e5e7eb;
  padding: 12px 24px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}
.quick-head {
  display: flex;
  align-items: center;
  gap: 16px;
}
.quick-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #6b7280;
  flex-shrink: 0;
  font-weight: 500;
}
.quick-spark {
  color: #f59e0b;
}
.quick-chips {
  display: flex;
  align-items: center;
  gap: 8px;
  overflow-x: auto;
}
.quick-chip {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  background: #f4f4f5;
  font-size: 14px;
  color: #6b7280;
  cursor: pointer;
  white-space: nowrap;
  flex-shrink: 0;
  transition: all 0.2s;
}
.quick-chip:hover {
  background: rgba(64, 158, 255, 0.05);
  color: var(--el-color-primary, #409eff);
}

/* 主体 */
.apps-body {
  display: flex;
}
.apps-aside {
  display: none;
  width: 224px;
  flex-shrink: 0;
  background: #fff;
  min-height: calc(100vh - 56px - 56px);
  position: sticky;
  top: 112px;
  align-self: flex-start;
  border-right: 1px solid #e5e7eb;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}
@media (min-width: 768px) {
  .apps-aside {
    display: block;
  }
}
.aside-nav {
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.aside-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border: none;
  border-radius: 8px;
  background: transparent;
  font-size: 14px;
  color: #6b7280;
  cursor: pointer;
  text-align: left;
  width: 100%;
  transition: all 0.2s;
}
.aside-item:hover {
  background: #f4f4f5;
  color: #111827;
}
.aside-item.active {
  background: var(--el-color-primary, #409eff);
  color: #fff;
  box-shadow: 0 2px 8px rgba(64, 158, 255, 0.2);
}
.aside-label {
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.aside-arrow {
  color: rgba(255, 255, 255, 0.7);
}

/* 主内容 */
.apps-main {
  flex: 1;
  padding: 16px 24px;
  overflow-y: auto;
  max-height: calc(100vh - 56px - 56px);
}
.apps-state {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 256px;
  color: #6b7280;
  font-size: 14px;
}
.module-section {
  margin-bottom: 20px;
}
.section-head {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
}
.section-icon {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.section-title-link {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
  cursor: pointer;
  text-decoration: none;
}
.section-title-link:hover {
  color: var(--el-color-primary, #409eff);
}
.section-title {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
  margin: 0;
}
.section-count {
  font-size: 12px;
  color: #6b7280;
  background: #f4f4f5;
  padding: 2px 8px;
  border-radius: 999px;
}

.module-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 12px;
}
@media (min-width: 640px) {
  .module-grid {
    grid-template-columns: repeat(2, 1fr);
  }
}
@media (min-width: 1024px) {
  .module-grid {
    grid-template-columns: repeat(4, 1fr);
    gap: 16px;
  }
}
@media (min-width: 1280px) {
  .module-grid {
    grid-template-columns: repeat(5, 1fr);
  }
}

.module-card {
  position: relative;
  border-radius: 12px;
  padding: 20px;
  border: 1px solid #e5e7eb;
  background: #fff;
  cursor: pointer;
  transition: all 0.2s;
  min-height: 96px;
}
.module-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
  border-color: rgba(64, 158, 255, 0.2);
}
.module-card-disabled {
  cursor: default;
  opacity: 0.6;
}
.module-title {
  margin: 0 0 8px;
  font-size: 14px;
  font-weight: 500;
  color: #111827;
  display: flex;
  align-items: center;
  gap: 4px;
  line-height: 1.3;
  padding-right: 8px;
}
.module-card:not(.module-card-disabled):hover .module-title {
  color: var(--el-color-primary, #409eff);
}
.module-ext {
  color: #9ca3af;
}
.module-desc {
  margin: 0;
  font-size: 12px;
  color: #6b7280;
  line-height: 1.6;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.module-enter {
  position: absolute;
  bottom: 16px;
  right: 16px;
  color: var(--el-color-primary, #409eff);
  opacity: 0;
  transition: opacity 0.2s;
}
.module-card:not(.module-card-disabled):hover .module-enter {
  opacity: 1;
}
</style>
