// frontend/portal-vue/src/views/portal/workspace/AssessmentTab.vue
<!--
  测评认证 Tab：岗位能力认定结果表 + 参与的日常考试与期末测评清单 + 能力点认定明细弹窗。
  对齐原 React 版 assessment-tab.tsx
  （结果表 9 列含达成率/胜任度/认证得分；考试清单按 全部/待考/进行中/已完成 筛选；
   明细弹窗带请求序号守卫，避免连续点击后旧明细覆盖新选择）。
-->
<template>
  <div class="assessment-tab">
    <!-- ===== 岗位能力认定结果 ===== -->
    <SectionCard title="岗位能力认定结果" :icon="Trophy" icon-color="amber">
      <el-table :data="results" v-loading="resultsLoading" size="small" empty-text="暂无岗位能力认定结果">
        <el-table-column prop="positionName" label="岗位名称" min-width="140" />
        <el-table-column prop="studentName" label="姓名" width="100" />
        <el-table-column prop="studentId" label="学号" width="120" />
        <el-table-column label="所属院系" min-width="120">
          <template #default="{ row }">{{ row.department || '-' }}</template>
        </el-table-column>
        <el-table-column label="班级" min-width="110">
          <template #default="{ row }">{{ row.className || '-' }}</template>
        </el-table-column>
        <el-table-column label="岗位能力达成率" width="130">
          <template #default="{ row }">
            <strong>{{ achievementPercent(row) }}</strong>
          </template>
        </el-table-column>
        <el-table-column label="岗位胜任度" width="110">
          <template #default="{ row }">
            {{ row.positionCompetency != null ? `${row.positionCompetency.toFixed(1)}%` : '-' }}
          </template>
        </el-table-column>
        <el-table-column label="能力认证得分" width="120">
          <template #default="{ row }">
            {{ row.abilityCognitionScore != null ? row.abilityCognitionScore.toFixed(1) : '-' }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="110" align="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="openDetail(row.id)">
              <el-icon><View /></el-icon>查看明细
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </SectionCard>

    <!-- ===== 参与的考试/测评清单 ===== -->
    <SectionCard title="参与的日常考试与期末测评" :icon="DocumentChecked" icon-color="blue">
      <el-radio-group v-model="examFilter" size="small" class="filter-row">
        <el-radio-button value="all">全部</el-radio-button>
        <el-radio-button value="待考">待考</el-radio-button>
        <el-radio-button value="进行中">进行中</el-radio-button>
        <el-radio-button value="已完成">已完成</el-radio-button>
      </el-radio-group>

      <el-table :data="filteredExams" v-loading="loading" size="small" empty-text="暂无记录">
        <el-table-column label="序号" width="64">
          <template #default="{ $index }">{{ $index + 1 }}</template>
        </el-table-column>
        <el-table-column label="考试名称" min-width="200">
          <template #default="{ row }">
            <span class="exam-name">
              <el-icon><component :is="examTypeIcon(row.type)" /></el-icon>{{ row.name }}
            </span>
          </template>
        </el-table-column>
        <el-table-column prop="type" label="类型" width="120" />
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <span class="status-badge" :style="statusStyle(row.status)">
              {{ getStatusConfig(row.status).label }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="时间" min-width="200">
          <template #default="{ row }">
            <template v-if="row.startTime || row.endTime">
              {{ row.startTime || '-' }}{{ row.endTime ? ` ~ ${row.endTime}` : '' }}
            </template>
            <template v-else>-</template>
          </template>
        </el-table-column>
        <el-table-column label="时长" width="90">
          <template #default="{ row }">{{ row.duration }}分钟</template>
        </el-table-column>
        <el-table-column label="结果" width="100" align="right">
          <template #default="{ row }">
            <span v-if="row.score !== undefined" class="score">{{ row.score }}/{{ row.totalScore }}</span>
            <span v-else class="score-empty">-</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="90" align="right">
          <template #default="{ row }">
            <el-button
              link
              type="primary"
              size="small"
              @click="goExam(row)"
            >
              {{ row.status === '已完成' ? '查看' : '进入' }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </SectionCard>

    <!-- ===== 能力点认定明细弹窗 ===== -->
    <el-dialog v-model="detailOpen" title="能力点认定明细" width="720px">
      <p class="dialog-desc">
        {{ detail ? `${detail.studentName}（${detail.studentId}）· ${detail.positionName}` : '加载中...' }}
      </p>
      <div v-if="detailLoading" class="dialog-empty">加载中...</div>
      <template v-else-if="detail">
        <div class="detail-summary">
          <span>能力点达成 {{ detail.achievedAbilityPoints }}/{{ detail.totalAbilityPoints }}</span>
          <span>达标率 {{ (detail.achievementRate ?? 0).toFixed(1) }}%</span>
          <span>认定时间 {{ formatTime(detail.evaluationTime) }}</span>
        </div>
        <el-table
          v-if="detail.abilityPointDetails && detail.abilityPointDetails.length > 0"
          :data="detail.abilityPointDetails"
          size="small"
          max-height="50vh"
        >
          <el-table-column prop="abilityPointName" label="能力点" min-width="180" />
          <el-table-column label="得分" width="100">
            <template #default="{ row }">
              {{ row.maxScore != null ? `${row.score}/${row.maxScore}` : row.score }}
            </template>
          </el-table-column>
          <el-table-column label="档位" width="110">
            <template #default="{ row }">
              <el-tag
                v-if="row.levelLabel"
                size="small"
                :type="row.levelLabel === '未达标' ? 'danger' : 'primary'"
                effect="light"
              >
                {{ row.levelLabel }}
              </el-tag>
              <template v-else>-</template>
            </template>
          </el-table-column>
          <el-table-column label="权重" width="100">
            <template #default="{ row }">{{ row.weight != null ? `${row.weight}%` : '-' }}</template>
          </el-table-column>
          <el-table-column label="是否达成" width="110">
            <template #default="{ row }">
              <el-tag size="small" :type="row.achieved ? 'success' : 'danger'" effect="light">
                {{ row.achieved ? '已达成' : '未达成' }}
              </el-tag>
            </template>
          </el-table-column>
        </el-table>
        <div v-else class="dialog-empty">暂无能力点明细</div>
      </template>
      <div v-else class="dialog-empty">未找到结果明细</div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import type { Component } from 'vue';
import { DocumentChecked, School, Trophy, View } from '@element-plus/icons-vue';
import { jobAbilityResultApi } from '@/api/evaluation';
import type { JobAbilityResult } from '@/types/evaluation';
import SectionCard from './SectionCard.vue';
import { workspaceDashboardApi } from './workspace-api';
import type { WorkspaceExam } from './workspace-api';
import { examHref, getStatusConfig } from './workspace-utils';
import { formatDateTime } from '@/views/landing/evaluation-types';

const router = useRouter();

const TYPE_ICONS: Record<string, Component> = {
  随堂测: DocumentChecked,
  单元测试: DocumentChecked,
  在线测评: School,
  岗位能力认定: Trophy
};

const exams = ref<WorkspaceExam[]>([]);
const loading = ref(true);
const examFilter = ref('all');

const results = ref<JobAbilityResult[]>([]);
const resultsLoading = ref(true);
const detailOpen = ref(false);
const detailLoading = ref(false);
const detail = ref<JobAbilityResult | null>(null);
// 请求序号守卫：连续点击不同行时丢弃过期响应，避免旧明细覆盖新选择
let detailSeq = 0;

const filteredExams = computed(() =>
  examFilter.value === 'all' ? exams.value : exams.value.filter((e) => e.status === examFilter.value)
);

function examTypeIcon(type: string): Component {
  return TYPE_ICONS[type] || DocumentChecked;
}

function statusStyle(status: string) {
  const cfg = getStatusConfig(status);
  return { color: cfg.color, background: cfg.bg };
}

function achievementPercent(row: JobAbilityResult): string {
  return row.totalAbilityPoints > 0
    ? `${((row.achievedAbilityPoints / row.totalAbilityPoints) * 100).toFixed(0)}%`
    : '-';
}

function formatTime(value: string | Date | undefined): string {
  if (!value) return '-';
  return formatDateTime(value instanceof Date ? value.toISOString() : value);
}

function goExam(exam: WorkspaceExam) {
  // 试卷版本由作答页按 usage.examVersion 服务端解析，链接只带 usage
  if (!exam.examId) return;
  router.push(examHref(exam.examId, { usage: exam.id }));
}

async function openDetail(id: string) {
  const seq = ++detailSeq;
  detailOpen.value = true;
  detailLoading.value = true;
  detail.value = null;
  try {
    const res = await jobAbilityResultApi.get(id);
    if (seq !== detailSeq) return;
    detail.value = res;
  } catch {
    // 明细加载失败保持弹窗打开，展示兜底文案
  } finally {
    if (seq === detailSeq) detailLoading.value = false;
  }
}

onMounted(async () => {
  loading.value = true;
  try {
    const res = await workspaceDashboardApi.get({ role: 'student' });
    exams.value = res.exams || [];
  } catch {
    exams.value = [];
  } finally {
    loading.value = false;
  }

  // 岗位能力认定结果：学生仅可查看本人的认定结果（后端按角色过滤）
  resultsLoading.value = true;
  try {
    const res = await jobAbilityResultApi.list({ page: 1, limit: 50 });
    results.value = res.items || [];
  } catch {
    results.value = [];
  } finally {
    resultsLoading.value = false;
  }
});
</script>

<style scoped>
.assessment-tab {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.filter-row {
  margin-bottom: 16px;
}
.exam-name {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-weight: 500;
}
.status-badge {
  display: inline-flex;
  align-items: center;
  border-radius: 4px;
  padding: 2px 6px;
  font-size: 10px;
  font-weight: 500;
}
.score {
  color: #059669;
  font-weight: 600;
}
.score-empty {
  color: #9ca3af;
}
.dialog-desc {
  margin: 0 0 12px;
  font-size: 13px;
  color: #6b7280;
}
.detail-summary {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  margin-bottom: 16px;
  font-size: 13px;
  color: #6b7280;
}
.dialog-empty {
  padding: 40px 0;
  text-align: center;
  font-size: 14px;
  color: #9ca3af;
}
</style>

// frontend/edu/app/portal/workspace/_components/assessment-tab.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import { Award, Eye, FileCheck, GraduationCap } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { StatusBadge } from '@zhiyu/ui'
import { SectionCard } from './section-card'
import { portalApi, jobAbilityResultApi } from '@/lib/api'
import type { WorkspaceExam, JobAbilityResult } from '@/lib/types'
import { examHref } from '@/lib/learn-links'
import { cn } from '@/lib/utils'
import { formatDateTime } from '@/lib/format-utils'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { useT } from '@/lib/i18n/locale-provider'

const typeIconMap: Record<string, typeof GraduationCap> = {
  随堂测: FileCheck,
  单元测试: FileCheck,
  在线测评: GraduationCap,
  岗位能力认定: Award,
}

export function AssessmentTab() {
  const t = useT()
  const [exams, setExams] = useState<WorkspaceExam[]>([])
  const [loading, setLoading] = useState(true)
  const [examFilter, setExamFilter] = useState('all')

  const [results, setResults] = useState<JobAbilityResult[]>([])
  const [resultsLoading, setResultsLoading] = useState(true)
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailLoading, setDetailLoading] = useState(false)
  const [detail, setDetail] = useState<JobAbilityResult | null>(null)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      setLoading(true)
      try {
        const res = await portalApi.workspaceDashboard({ role: 'student' })
        if (!cancelled) setExams(res.exams || [])
      } catch {
        if (!cancelled) setExams([])
      } finally {
        if (!cancelled) setLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  // 岗位能力认定结果：学生仅可查看本人的认定结果（后端按角色过滤）
  useEffect(() => {
    let cancelled = false
    ;(async () => {
      setResultsLoading(true)
      try {
        const res = await jobAbilityResultApi.list({ page: 1, limit: 50 })
        if (!cancelled) setResults(res.items || [])
      } catch {
        if (!cancelled) setResults([])
      } finally {
        if (!cancelled) setResultsLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  // 请求序号守卫：连续点击不同行时丢弃过期响应，避免旧明细覆盖新选择
  const detailSeqRef = useRef(0)
  const openDetail = async (id: string) => {
    const seq = ++detailSeqRef.current
    setDetailOpen(true)
    setDetailLoading(true)
    setDetail(null)
    try {
      const res = await jobAbilityResultApi.get(id)
      if (seq !== detailSeqRef.current) return
      setDetail(res)
    } catch {
      // 明细加载失败保持弹窗打开，展示兜底文案
    } finally {
      if (seq === detailSeqRef.current) setDetailLoading(false)
    }
  }

  const filteredExams = examFilter === 'all' ? exams : exams.filter((e) => e.status === examFilter)

  return (
    <div className="space-y-5">
      {/* ===== 岗位能力认定结果 ===== */}
      <SectionCard title={t('岗位能力认定结果')} icon={Award} iconColor="amber">
        <div className="rounded-xl border border-gray-200 overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-gray-50">
                <TableHead className="text-xs">{t('岗位名称')}</TableHead>
                <TableHead className="text-xs">{t('姓名')}</TableHead>
                <TableHead className="text-xs">{t('学号')}</TableHead>
                <TableHead className="text-xs">{t('所属院系')}</TableHead>
                <TableHead className="text-xs">{t('班级')}</TableHead>
                <TableHead className="text-xs">{t('岗位能力达成率')}</TableHead>
                <TableHead className="text-xs">{t('岗位胜任度')}</TableHead>
                <TableHead className="text-xs">{t('能力认证得分')}</TableHead>
                <TableHead className="text-xs text-right w-20">{t('操作')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {resultsLoading && (
                <TableRow>
                  <TableCell colSpan={9} className="text-center text-xs text-gray-400 py-10">
                    {t('加载中...')}
                  </TableCell>
                </TableRow>
              )}
              {!resultsLoading &&
                results.map((result) => (
                  <TableRow key={result.id}>
                    <TableCell className="text-sm font-medium">{result.positionName}</TableCell>
                    <TableCell className="text-sm">{result.studentName}</TableCell>
                    <TableCell className="text-xs text-gray-500">{result.studentId}</TableCell>
                    <TableCell className="text-xs text-gray-500">
                      {result.department || '-'}
                    </TableCell>
                    <TableCell className="text-xs text-gray-500">
                      {result.className || '-'}
                    </TableCell>
                    <TableCell className="text-xs font-semibold">
                      {result.totalAbilityPoints > 0
                        ? `${((result.achievedAbilityPoints / result.totalAbilityPoints) * 100).toFixed(0)}%`
                        : '-'}
                    </TableCell>
                    <TableCell className="text-xs text-gray-500">
                      {result.positionCompetency != null
                        ? `${result.positionCompetency.toFixed(1)}%`
                        : '-'}
                    </TableCell>
                    <TableCell className="text-xs text-gray-500">
                      {result.abilityCognitionScore != null
                        ? result.abilityCognitionScore.toFixed(1)
                        : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="ghost"
                        className="text-[10px] h-7 px-2"
                        onClick={() => openDetail(result.id)}
                      >
                        <Eye className="mr-1 w-3 h-3" />
                        {t('查看明细')}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
            </TableBody>
          </Table>
          {!resultsLoading && results.length === 0 && (
            <div className="py-10 text-center text-xs text-gray-400">
              {t('暂无岗位能力认定结果')}
            </div>
          )}
        </div>
      </SectionCard>

      {/* ===== 参与的考试/测评清单 ===== */}
      <SectionCard title={t('参与的日常考试与期末测评')} icon={FileCheck} iconColor="blue">
        {/* 状态筛选 */}
        <Tabs value={examFilter} onValueChange={setExamFilter}>
          <TabsList className="h-8 bg-gray-100 mb-4">
            <TabsTrigger
              value="all"
              className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              {t('全部')}
            </TabsTrigger>
            <TabsTrigger
              value="待考"
              className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              {t('待考')}
            </TabsTrigger>
            <TabsTrigger
              value="进行中"
              className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              {t('进行中')}
            </TabsTrigger>
            <TabsTrigger
              value="已完成"
              className="text-xs px-3 data-[state=active]:bg-white data-[state=active]:shadow-sm"
            >
              {t('已完成')}
            </TabsTrigger>
          </TabsList>
        </Tabs>

        <div className="rounded-xl border border-gray-200 overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-gray-50">
                <TableHead className="text-xs w-8">{t('序号')}</TableHead>
                <TableHead className="text-xs">{t('考试名称')}</TableHead>
                <TableHead className="text-xs">{t('类型')}</TableHead>
                <TableHead className="text-xs">{t('状态')}</TableHead>
                <TableHead className="text-xs">{t('时间')}</TableHead>
                <TableHead className="text-xs">{t('时长')}</TableHead>
                <TableHead className="text-xs text-right">{t('结果')}</TableHead>
                <TableHead className="text-xs text-right w-20">{t('操作')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading && (
                <TableRow>
                  <TableCell colSpan={8} className="text-center text-xs text-gray-400 py-10">
                    {t('加载中...')}
                  </TableCell>
                </TableRow>
              )}
              {!loading &&
                filteredExams.map((exam, i) => {
                  const Icon = typeIconMap[exam.type]
                  return (
                    <TableRow key={exam.id}>
                      <TableCell className="text-xs text-gray-400">{i + 1}</TableCell>
                      <TableCell className="text-sm font-medium">
                        <div className="flex items-center gap-2">
                          <Icon className="w-4 h-4 text-gray-400" />
                          {exam.name}
                        </div>
                      </TableCell>
                      <TableCell className="text-xs">{t(exam.type)}</TableCell>
                      <TableCell>
                        <StatusBadge
                          status={exam.status}
                          className="text-[10px] px-1.5 py-0.5 rounded"
                        />
                      </TableCell>
                      <TableCell className="text-xs text-gray-500">
                        {exam.startTime || exam.endTime ? (
                          <span>
                            {exam.startTime || '-'}
                            {exam.endTime ? ` ~ ${exam.endTime}` : ''}
                          </span>
                        ) : (
                          '-'
                        )}
                      </TableCell>
                      <TableCell className="text-xs text-gray-500">
                        {t('{count}分钟', { count: exam.duration })}
                      </TableCell>
                      <TableCell className="text-xs text-right font-semibold">
                        {exam.score !== undefined ? (
                          <span className="text-emerald-600">
                            {exam.score}/{exam.totalScore}
                          </span>
                        ) : (
                          <span className="text-gray-400">-</span>
                        )}
                      </TableCell>
                      <TableCell className="text-right">
                        <Button size="sm" variant="ghost" className="text-[10px] h-7 px-2" asChild>
                          <Link
                            to={
                              // 试卷版本由作答页按 usage.examVersion 服务端解析，链接只带 usage
                              exam.examId ? examHref(exam.examId, { usage: exam.id }) : '#'
                            }
                          >
                            {exam.status === '已完成' ? t('查看') : t('进入')}
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  )
                })}
            </TableBody>
          </Table>
          {!loading && filteredExams.length === 0 && (
            <div className="py-10 text-center text-xs text-gray-400">{t('暂无记录')}</div>
          )}
        </div>
      </SectionCard>

      {/* ===== 能力点认定明细弹窗 ===== */}
      <Dialog open={detailOpen} onOpenChange={setDetailOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{t('能力点认定明细')}</DialogTitle>
            <DialogDescription>
              {detail
                ? `${detail.studentName}（${detail.studentId}）· ${detail.positionName}`
                : t('加载中...')}
            </DialogDescription>
          </DialogHeader>
          {detailLoading ? (
            <div className="py-10 text-center text-sm text-gray-400">{t('加载中...')}</div>
          ) : detail ? (
            <div className="space-y-4">
              <div className="flex items-center gap-4 text-sm">
                <span className="text-gray-500">
                  {t('能力点达成 {achieved}/{total}', {
                    achieved: detail.achievedAbilityPoints,
                    total: detail.totalAbilityPoints,
                  })}
                </span>
                <span className="text-gray-500">
                  {t('达标率 {rate}%', { rate: (detail.achievementRate ?? 0).toFixed(1) })}
                </span>
                <span className="text-gray-500">
                  {t('认定时间 {time}', { time: formatDateTime(detail.evaluationTime) })}
                </span>
              </div>
              {detail.abilityPointDetails && detail.abilityPointDetails.length > 0 ? (
                <div className="max-h-[50vh] overflow-y-auto rounded-lg border">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>{t('能力点')}</TableHead>
                        <TableHead className="w-[100px]">{t('得分')}</TableHead>
                        <TableHead className="w-[110px]">{t('档位')}</TableHead>
                        <TableHead className="w-[100px]">{t('权重')}</TableHead>
                        <TableHead className="w-[100px]">{t('是否达成')}</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {detail.abilityPointDetails.map((point, index) => (
                        <TableRow key={point.abilityPointId || index}>
                          <TableCell className="text-sm">{point.abilityPointName}</TableCell>
                          <TableCell className="text-sm">
                            {point.maxScore != null
                              ? `${point.score}/${point.maxScore}`
                              : point.score}
                          </TableCell>
                          <TableCell className="text-sm">
                            {point.levelLabel ? (
                              <Badge
                                variant="outline"
                                className={cn(
                                  'text-xs',
                                  point.levelLabel === '未达标'
                                    ? 'bg-red-50 text-red-600 border-red-200'
                                    : 'bg-primary/5 text-primary border-primary/15',
                                )}
                              >
                                {t(point.levelLabel)}
                              </Badge>
                            ) : (
                              '-'
                            )}
                          </TableCell>
                          <TableCell className="text-sm text-gray-500">
                            {point.weight != null ? `${point.weight}%` : '-'}
                          </TableCell>
                          <TableCell>
                            <Badge
                              variant="outline"
                              className={cn(
                                'text-xs',
                                point.achieved
                                  ? 'bg-green-50 text-green-600 border-green-200'
                                  : 'bg-red-50 text-red-600 border-red-200',
                              )}
                            >
                              {point.achieved ? t('已达成') : t('未达成')}
                            </Badge>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              ) : (
                <div className="py-8 text-center text-sm text-gray-400">{t('暂无能力点明细')}</div>
              )}
            </div>
          ) : (
            <div className="py-10 text-center text-sm text-gray-400">{t('未找到结果明细')}</div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
