// plus-ui/src-portal/views/portal/workspace/CommunityTab.vue
<!--
  学习社区 Tab（React community-tab 对位）。
  对齐原 React 版 community-tab.tsx：
  - 顶部 4 指标（热门话题 / 我的提问 / 学习小组 / 我的导师）；
  - 左 2/3 话题列表（热门话题/最新发布/我的提问）与详情（返回列表 / 回复流 / 楼中楼回复 / 回复框）；
  - 右 1/3 侧边栏（学习小组 / 我的导师 / 社区规范，需求明确保留演示数据）；
  - 发起提问弹窗（标题必填 128、标签选填 32、内容必填）；
  - 排序切换与详情加载均带请求序号守卫，丢弃过期响应。
  话题/回复接口沿用门户既有 api/portal.ts portalCommunityApi（同 React 契约）。
-->
<template>
  <div class="community-tab">
    <!-- 统计 -->
    <div class="stat-grid">
      <StatCard title="热门话题" :value="totalTopics" :icon="Sunny" trend="按阅读热度排序" color="rose" />
      <StatCard
        title="我的提问"
        :value="mineTotal"
        :icon="ChatDotSquare"
        :trend="mineTotal > 0 ? `${mineTotal} 个提问` : '暂未发起'"
        color="blue"
      />
      <StatCard title="学习小组" :value="STUDY_GROUPS.length" :icon="UserFilled" trend="3 个可加入" color="green" />
      <StatCard title="我的导师" :value="MENTORS.length" :icon="Medal" trend="可在线咨询" color="amber" />
    </div>

    <div class="post-row">
      <el-button type="primary" :disabled="!!detail" @click="postOpen = true">
        <el-icon><Plus /></el-icon>发起提问
      </el-button>
    </div>

    <div class="community-layout">
      <!-- 话题列表 / 详情 -->
      <div class="main-col">
        <div v-if="detail" class="detail-card">
          <button type="button" class="back-btn" @click="closeDetail">
            <el-icon><ArrowLeft /></el-icon>返回列表
          </button>

          <div v-if="detailLoading" class="loading-block">
            <el-icon class="is-loading"><Loading /></el-icon>加载中...
          </div>
          <template v-else>
            <div class="detail-head">
              <span class="avatar lg">{{ avatarChar(detail.authorName) }}</span>
              <div class="detail-head-body">
                <div class="detail-title-row">
                  <h2 class="detail-title">{{ detail.title }}</h2>
                  <span v-if="detail.viewCount >= 50" class="hot-badge">
                    <el-icon><Sunny /></el-icon>热门
                  </span>
                </div>
                <div class="detail-meta">
                  <span class="author">{{ detail.authorName }}</span>
                  <el-tag v-if="detail.tag" size="small" type="info" effect="plain">{{ detail.tag }}</el-tag>
                  <span>{{ formatDateTime(detail.createdAt) }}</span>
                  <span class="meta-cell"><el-icon><ChatDotSquare /></el-icon>{{ detail.replyCount }} 回复</span>
                  <span>{{ detail.viewCount }} 浏览</span>
                </div>
              </div>
            </div>

            <div class="detail-content">{{ detail.content }}</div>

            <!-- 回复流 -->
            <h3 class="reply-title">全部回复（{{ replies.length }}）</h3>
            <div class="reply-list">
              <el-empty v-if="replies.length === 0" description="暂无回复，快来抢沙发～" :image-size="60" />
              <div v-for="reply in replies" :key="reply.id" class="reply-item">
                <span class="avatar sm">{{ avatarChar(reply.authorName) }}</span>
                <div class="reply-body">
                  <div class="reply-meta">
                    <span class="author">{{ reply.authorName }}</span>
                    <span v-if="reply.parentAuthorName" class="reply-to">
                      回复 @{{ reply.parentAuthorName }}
                    </span>
                    <span>{{ formatDateTime(reply.createdAt) }}</span>
                  </div>
                  <p class="reply-content">{{ reply.content }}</p>
                  <button type="button" class="reply-btn" @click="replyingTo = reply">
                    <el-icon><ChatDotRound /></el-icon>回复
                  </button>
                </div>
              </div>
            </div>

            <!-- 回复输入 -->
            <div class="reply-input">
              <div v-if="replyingTo" class="reply-hint">
                <span>回复 @{{ replyingTo.authorName }} 的评论</span>
                <button type="button" class="cancel-btn" @click="replyingTo = null">取消</button>
              </div>
              <div class="reply-box">
                <el-input
                  v-model="replyText"
                  type="textarea"
                  :rows="2"
                  resize="none"
                  placeholder="写下你的回复..."
                />
                <el-button
                  type="primary"
                  :loading="replySubmitting"
                  :disabled="!replyText.trim() || replySubmitting"
                  @click="submitReply"
                >
                  <el-icon><Promotion /></el-icon>回复
                </el-button>
              </div>
            </div>
          </template>
        </div>

        <div v-else>
          <el-radio-group v-model="sort" class="sort-tabs" @change="onSortChange">
            <el-radio-button value="hot">热门话题</el-radio-button>
            <el-radio-button value="latest">最新发布</el-radio-button>
            <el-radio-button value="mine">我的提问</el-radio-button>
          </el-radio-group>

          <div v-if="loading" class="loading-block">
            <el-icon class="is-loading"><Loading /></el-icon>加载中...
          </div>
          <div v-else-if="topics.length === 0" class="topics-empty">
            <el-empty
              :description="sort === 'mine' ? '你还没有发起过提问' : '暂无话题，来发第一帖吧'"
            >
              <el-button type="primary" size="small" @click="postOpen = true">
                <el-icon><Plus /></el-icon>{{ sort === 'mine' ? '去提问' : '发起提问' }}
              </el-button>
            </el-empty>
          </div>
          <div v-else class="topic-list">
            <div v-for="topic in topics" :key="topic.id" class="topic-item" @click="openDetail(topic)">
              <span class="avatar lg">{{ avatarChar(topic.authorName) }}</span>
              <div class="topic-body">
                <div class="topic-title-row">
                  <h3 class="topic-title">{{ topic.title }}</h3>
                  <span v-if="topic.viewCount >= 50" class="hot-badge">
                    <el-icon><Sunny /></el-icon>热门
                  </span>
                </div>
                <div class="topic-meta">
                  <span class="author">{{ topic.authorName }}</span>
                  <el-tag v-if="topic.tag" size="small" type="info" effect="plain">{{ topic.tag }}</el-tag>
                </div>
                <div class="topic-stats">
                  <span class="meta-cell"><el-icon><ChatDotSquare /></el-icon>{{ topic.replyCount }} 回复</span>
                  <span>{{ topic.viewCount }} 浏览</span>
                  <span>{{ formatDateTime(topic.createdAt) }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- 侧边栏 -->
      <div class="side-col">
        <SectionCard title="学习小组" :icon="UserFilled" icon-color="blue">
          <div class="side-list">
            <div v-for="group in STUDY_GROUPS" :key="group.id" class="side-row">
              <div>
                <p class="side-name">{{ group.name }}</p>
                <p class="side-sub">{{ group.members }} 人</p>
              </div>
              <el-button size="small" :type="group.active ? 'primary' : 'default'">
                {{ group.active ? '加入' : '已满' }}
              </el-button>
            </div>
          </div>
        </SectionCard>

        <SectionCard title="我的导师" :icon="Medal" icon-color="amber">
          <div class="side-list">
            <div v-for="mentor in MENTORS" :key="mentor.id" class="side-row">
              <span class="avatar amber">{{ mentor.avatar }}</span>
              <div class="side-grow">
                <p class="side-name">{{ mentor.name }}</p>
                <p class="side-sub">{{ mentor.role }}</p>
              </div>
              <el-button size="small">咨询</el-button>
            </div>
          </div>
        </SectionCard>

        <SectionCard title="社区规范" :icon="ChatRound" icon-color="green">
          <ul class="rules">
            <li>请友善交流，尊重他人观点</li>
            <li>提问前建议先搜索已有话题</li>
            <li>鼓励分享学习笔记与实践经验</li>
            <li>禁止发布与教学无关的内容</li>
          </ul>
        </SectionCard>
      </div>
    </div>

    <!-- 发帖弹窗 -->
    <el-dialog v-model="postOpen" title="发起提问" width="520px">
      <p class="dialog-desc">分享你的学习问题或经验，和同学们一起交流。</p>
      <div class="post-form">
        <div class="field-row">
          <label class="field-label">标题</label>
          <el-input v-model="postTitle" maxlength="128" placeholder="一句话说清你的问题" />
        </div>
        <div class="field-row">
          <label class="field-label">标签（选填）</label>
          <el-input v-model="postTag" maxlength="32" placeholder="如：网络技术" />
        </div>
        <div class="field-row">
          <label class="field-label">内容</label>
          <el-input v-model="postContent" type="textarea" :rows="5" placeholder="补充详细描述，便于同学们解答" />
        </div>
      </div>
      <template #footer>
        <el-button @click="postOpen = false">取消</el-button>
        <el-button type="primary" :loading="postSubmitting" @click="submitPost">发布</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import {
  ArrowLeft,
  ChatDotRound,
  ChatDotSquare,
  ChatRound,
  Loading,
  Medal,
  Plus,
  Promotion,
  Sunny,
  UserFilled
} from '@element-plus/icons-vue';
import { portalCommunityApi } from '@/api/portal';
import type { CommunityReply, CommunityTopic, CommunityTopicSort } from '@/types/portal';
import { formatDateTime } from '@/views/landing/evaluation-types';
import SectionCard from './SectionCard.vue';
import StatCard from './StatCard.vue';

// 右侧学习小组/导师保持演示数据（需求明确保留 mock）
const STUDY_GROUPS = [
  { id: 'g1', name: '网络技术学习小组', members: 28, active: true },
  { id: 'g2', name: 'Linux运维互助群', members: 16, active: true },
  { id: 'g3', name: '岗位面试经验分享', members: 45, active: false },
  { id: 'g4', name: '技能大赛备赛组', members: 12, active: true }
];
const MENTORS = [
  { id: 'm1', name: '王教授', role: '网络基础课程教师', avatar: '王' },
  { id: 'm2', name: '李老师', role: '企业导师 · 华为', avatar: '李' },
  { id: 'm3', name: '张老师', role: 'Linux系统管理教师', avatar: '张' }
];

const sort = ref<CommunityTopicSort>('latest');
const topics = ref<CommunityTopic[]>([]);
const hotTotal = ref(0);
const mineTotal = ref(0);
const loading = ref(true);
// 排序切换请求序号 / 详情加载序号：丢弃过期响应
let loadSeq = 0;
let detailSeq = 0;

const detail = ref<CommunityTopic | null>(null);
const replies = ref<CommunityReply[]>([]);
const detailLoading = ref(false);
const replyingTo = ref<CommunityReply | null>(null);
const replyText = ref('');
const replySubmitting = ref(false);

const postOpen = ref(false);
const postTitle = ref('');
const postTag = ref('');
const postContent = ref('');
const postSubmitting = ref(false);

const totalTopics = computed(() => hotTotal.value || topics.value.length);

function avatarChar(name?: string): string {
  return name ? name.charAt(0) : '?';
}

async function loadTopics(s: CommunityTopicSort) {
  const seq = ++loadSeq;
  loading.value = true;
  try {
    const [res, mineRes, hotRes] = await Promise.all([
      portalCommunityApi.listTopics({ sort: s, limit: 50 }),
      portalCommunityApi.listTopics({ sort: 'mine', limit: 1 }),
      portalCommunityApi.listTopics({ sort: 'hot', limit: 1 })
    ]);
    // 快速切换排序时丢弃过期响应，防止旧排序列表覆盖新排序
    if (seq !== loadSeq) return;
    topics.value = res.items;
    mineTotal.value = mineRes.total;
    hotTotal.value = hotRes.total;
  } catch (e) {
    if (seq !== loadSeq) return;
    ElMessage.error((e as Error).message || '加载学习社区话题失败');
    topics.value = [];
  } finally {
    if (seq === loadSeq) loading.value = false;
  }
}

function onSortChange() {
  loadTopics(sort.value);
}

async function openDetail(topic: CommunityTopic) {
  const seq = ++detailSeq;
  detail.value = topic;
  detailLoading.value = true;
  replies.value = [];
  replyingTo.value = null;
  replyText.value = '';
  try {
    const [topicDetail, replyRes] = await Promise.all([
      portalCommunityApi.getTopic(topic.id),
      portalCommunityApi.listReplies(topic.id)
    ]);
    if (seq !== detailSeq) return;
    detail.value = topicDetail;
    replies.value = replyRes.items;
  } catch (e) {
    if (seq !== detailSeq) return;
    ElMessage.error((e as Error).message || '加载话题详情失败');
    detail.value = null;
  } finally {
    if (seq === detailSeq) detailLoading.value = false;
  }
}

function closeDetail() {
  // 使进行中的详情请求过期，避免迟到的响应重新弹出详情
  detailSeq += 1;
  detail.value = null;
  replyingTo.value = null;
  replyText.value = '';
  loadTopics(sort.value);
}

async function submitPost() {
  const title = postTitle.value.trim();
  const content = postContent.value.trim();
  if (!title) {
    ElMessage.warning('请填写标题');
    return;
  }
  if (!content) {
    ElMessage.warning('请填写内容');
    return;
  }
  postSubmitting.value = true;
  try {
    await portalCommunityApi.createTopic({ title, content, tag: postTag.value.trim() || undefined });
    ElMessage.success('发布成功');
    postOpen.value = false;
    postTitle.value = '';
    postTag.value = '';
    postContent.value = '';
    await loadTopics(sort.value);
  } catch (e) {
    ElMessage.error((e as Error).message || '发布失败，请稍后重试');
  } finally {
    postSubmitting.value = false;
  }
}

async function submitReply() {
  const content = replyText.value.trim();
  if (!detail.value || !content) return;
  replySubmitting.value = true;
  try {
    await portalCommunityApi.createReply(detail.value.id, {
      content,
      parentId: replyingTo.value?.id
    });
    ElMessage.success('回复成功');
    replyText.value = '';
    replyingTo.value = null;
    const [topicDetail, replyRes] = await Promise.all([
      portalCommunityApi.getTopic(detail.value.id),
      portalCommunityApi.listReplies(detail.value.id)
    ]);
    detail.value = topicDetail;
    replies.value = replyRes.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '回复失败');
  } finally {
    replySubmitting.value = false;
  }
}

onMounted(() => loadTopics(sort.value));
</script>

<style scoped>
.community-tab {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.stat-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 16px;
}
@media (min-width: 640px) {
  .stat-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (min-width: 1024px) {
  .stat-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); }
}
.post-row {
  display: flex;
  justify-content: flex-end;
}
.community-layout {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 20px;
}
@media (min-width: 1024px) {
  .community-layout { grid-template-columns: repeat(3, minmax(0, 1fr)); }
  .main-col { grid-column: span 2; }
}
.side-col {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* 头像 */
.avatar {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  font-weight: 500;
}
.avatar.lg { width: 40px; height: 40px; font-size: 14px; }
.avatar.sm { width: 32px; height: 32px; font-size: 12px; background: #f3f4f6; color: #4b5563; }
.avatar.amber { width: 40px; height: 40px; font-size: 14px; background: #fffbeb; color: #d97706; }

/* 列表 */
.sort-tabs {
  margin-bottom: 16px;
}
.loading-block {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 64px 0;
  color: #9ca3af;
}
.topics-empty {
  padding: 32px;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
}
.topic-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.topic-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 16px;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  cursor: pointer;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.topic-item:hover {
  border-color: var(--el-color-primary-light-7);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}
.topic-body {
  flex: 1;
  min-width: 0;
}
.topic-title-row,
.detail-title-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}
.topic-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: #111827;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.hot-badge {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  gap: 2px;
  font-size: 12px;
  padding: 1px 8px;
  border-radius: 999px;
  background: #fff1f2;
  color: #e11d48;
  border: 1px solid #ffe4e6;
}
.topic-meta,
.topic-stats,
.detail-meta,
.reply-meta {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 12px;
  font-size: 12px;
  color: #6b7280;
}
.topic-stats {
  margin-top: 8px;
  color: #9ca3af;
}
.meta-cell {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.author {
  font-weight: 500;
  color: #374151;
}

/* 详情 */
.detail-card {
  padding: 20px;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}
.back-btn,
.reply-btn,
.cancel-btn {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  border: none;
  background: transparent;
  font-size: 12px;
  color: #6b7280;
  cursor: pointer;
  padding: 0;
}
.back-btn {
  margin-bottom: 16px;
}
.back-btn:hover,
.reply-btn:hover {
  color: var(--el-color-primary);
}
.detail-head {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}
.detail-head-body {
  flex: 1;
  min-width: 0;
}
.detail-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #111827;
}
.detail-content {
  white-space: pre-wrap;
  font-size: 14px;
  color: #374151;
  line-height: 1.8;
  background: #f9fafb;
  border-radius: 12px;
  padding: 16px;
  margin: 16px 0 20px;
}
.reply-title {
  margin: 0 0 12px;
  font-size: 14px;
  font-weight: 600;
  color: #111827;
}
.reply-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-bottom: 20px;
}
.reply-item {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}
.reply-body {
  flex: 1;
  min-width: 0;
}
.reply-to {
  color: #9ca3af;
}
.reply-content {
  margin: 4px 0 0;
  font-size: 14px;
  color: #374151;
  white-space: pre-wrap;
}
.reply-input {
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #f9fafb;
  padding: 12px;
}
.reply-hint {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 12px;
  color: #6b7280;
  margin-bottom: 8px;
}
.reply-box {
  display: flex;
  align-items: flex-end;
  gap: 8px;
}

/* 侧栏 */
.side-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.side-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px;
  border-radius: 12px;
  background: #f9fafb;
}
.side-grow {
  flex: 1;
  min-width: 0;
}
.side-name {
  margin: 0;
  font-size: 14px;
  font-weight: 500;
  color: #111827;
}
.side-sub {
  margin: 0;
  font-size: 12px;
  color: #6b7280;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.rules {
  margin: 0;
  padding-left: 16px;
  font-size: 12px;
  color: #6b7280;
}
.rules li {
  margin-bottom: 8px;
}

/* 弹窗 */
.dialog-desc {
  margin: 0 0 16px;
  font-size: 13px;
  color: #6b7280;
}
.post-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.field-row {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.field-label {
  font-size: 12px;
  font-weight: 500;
  color: #4b5563;
}
</style>

// frontend/edu/app/portal/workspace/_components/community-tab.tsx
'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  ArrowLeft,
  Flame,
  Loader2,
  MessageCircle,
  MessageSquare,
  Plus,
  Reply,
  Send,
  ThumbsUp,
  Users,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useToast, EmptyState } from '@zhiyu/ui'
import { SectionCard } from './section-card'
import { StatCard } from './stat-card'
import { portalCommunityApi } from '@/lib/api'
import { reportError } from '@/lib/error-handling'
import { formatDateTime } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import type { CommunityReply, CommunityTopic, CommunityTopicSort } from '@/lib/types'

// 右侧学习小组/导师保持演示数据（需求明确保留 mock）
const studyGroups = [
  { id: 'g1', name: '网络技术学习小组', members: 28, active: true },
  { id: 'g2', name: 'Linux运维互助群', members: 16, active: true },
  { id: 'g3', name: '岗位面试经验分享', members: 45, active: false },
  { id: 'g4', name: '技能大赛备赛组', members: 12, active: true },
]

const mentors = [
  { id: 'm1', name: '王教授', role: '网络基础课程教师', avatar: '王' },
  { id: 'm2', name: '李老师', role: '企业导师 · 华为', avatar: '李' },
  { id: 'm3', name: '张老师', role: 'Linux系统管理教师', avatar: '张' },
]

function avatarChar(name: string, url?: string) {
  if (url) return null
  return name ? name.charAt(0) : '?'
}

export function CommunityTab() {
  const { toast } = useToast()
  const t = useT()

  const SORTS: { id: CommunityTopicSort; label: string }[] = [
    { id: 'hot', label: t('热门话题') },
    { id: 'latest', label: t('最新发布') },
    { id: 'mine', label: t('我的提问') },
  ]

  const [sort, setSort] = useState<CommunityTopicSort>('latest')
  const [topics, setTopics] = useState<CommunityTopic[]>([])
  const [hotTotal, setHotTotal] = useState(0)
  const [mineTotal, setMineTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  // 排序切换请求序号：丢弃过期响应
  const loadSeqRef = useRef(0)
  // 详情加载序号守卫：返回列表/连续打开不同话题时丢弃过期响应
  const detailSeqRef = useRef(0)

  // 帖子详情
  const [detail, setDetail] = useState<CommunityTopic | null>(null)
  const [replies, setReplies] = useState<CommunityReply[]>([])
  const [detailLoading, setDetailLoading] = useState(false)
  const [replyingTo, setReplyingTo] = useState<CommunityReply | null>(null)
  const [replyText, setReplyText] = useState('')
  const [replySubmitting, setReplySubmitting] = useState(false)

  // 发帖弹窗
  const [postOpen, setPostOpen] = useState(false)
  const [postTitle, setPostTitle] = useState('')
  const [postTag, setPostTag] = useState('')
  const [postContent, setPostContent] = useState('')
  const [postSubmitting, setPostSubmitting] = useState(false)

  const loadTopics = useCallback(async (s: CommunityTopicSort) => {
    const seq = ++loadSeqRef.current
    setLoading(true)
    try {
      const [res, mineRes, hotRes] = await Promise.all([
        portalCommunityApi.listTopics({ sort: s, limit: 50 }),
        portalCommunityApi.listTopics({ sort: 'mine', limit: 1 }),
        portalCommunityApi.listTopics({ sort: 'hot', limit: 1 }),
      ])
      // 快速切换排序时丢弃过期响应，防止旧排序列表覆盖新排序
      if (seq !== loadSeqRef.current) return
      setTopics(res.items)
      setMineTotal(mineRes.total)
      setHotTotal(hotRes.total)
    } catch (e) {
      if (seq !== loadSeqRef.current) return
      reportError(e, '加载学习社区话题失败')
      setTopics([])
    } finally {
      if (seq === loadSeqRef.current) setLoading(false)
    }
  }, [])

  useEffect(() => {
    ;(async () => {
      await loadTopics(sort)
    })()
  }, [sort, loadTopics])

  const openDetail = useCallback(async (topic: CommunityTopic) => {
    const seq = ++detailSeqRef.current
    setDetail(topic)
    setDetailLoading(true)
    setReplies([])
    setReplyingTo(null)
    setReplyText('')
    try {
      const [topicDetail, replyRes] = await Promise.all([
        portalCommunityApi.getTopic(topic.id),
        portalCommunityApi.listReplies(topic.id),
      ])
      if (seq !== detailSeqRef.current) return
      setDetail(topicDetail)
      setReplies(replyRes.items)
    } catch (e) {
      if (seq !== detailSeqRef.current) return
      reportError(e, '加载话题详情失败')
      setDetail(null)
    } finally {
      if (seq === detailSeqRef.current) setDetailLoading(false)
    }
  }, [])

  const closeDetail = useCallback(() => {
    // 使进行中的详情请求过期，避免迟到的响应重新弹出详情
    detailSeqRef.current += 1
    setDetail(null)
    setReplyingTo(null)
    setReplyText('')
    loadTopics(sort)
  }, [loadTopics, sort])

  const submitPost = async () => {
    const title = postTitle.trim()
    const content = postContent.trim()
    if (!title) {
      toast({ title: t('请填写标题'), variant: 'destructive' })
      return
    }
    if (!content) {
      toast({ title: t('请填写内容'), variant: 'destructive' })
      return
    }
    setPostSubmitting(true)
    try {
      await portalCommunityApi.createTopic({ title, content, tag: postTag.trim() || undefined })
      toast({ title: t('发布成功') })
      setPostOpen(false)
      setPostTitle('')
      setPostTag('')
      setPostContent('')
      await loadTopics(sort)
    } catch (e) {
      reportError(e, '发布话题失败')
      toast({
        variant: 'destructive',
        title: t('发布失败'),
        description: e instanceof Error ? e.message : t('请稍后重试'),
      })
    } finally {
      setPostSubmitting(false)
    }
  }

  const submitReply = async () => {
    const content = replyText.trim()
    if (!detail || !content) return
    setReplySubmitting(true)
    try {
      await portalCommunityApi.createReply(detail.id, {
        content,
        parentId: replyingTo?.id,
      })
      toast({ title: t('回复成功') })
      setReplyText('')
      setReplyingTo(null)
      const [topicDetail, replyRes] = await Promise.all([
        portalCommunityApi.getTopic(detail.id),
        portalCommunityApi.listReplies(detail.id),
      ])
      setDetail(topicDetail)
      setReplies(replyRes.items)
    } catch (e) {
      reportError(e, '回复失败')
    } finally {
      setReplySubmitting(false)
    }
  }

  const totalTopics = hotTotal || topics.length

  return (
    <div className="space-y-5">
      {/* 统计 */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title={t('热门话题')}
          value={totalTopics}
          icon={Flame}
          trend={t('按阅读热度排序')}
          color="rose"
        />
        <StatCard
          title={t('我的提问')}
          value={mineTotal}
          icon={MessageSquare}
          trend={mineTotal > 0 ? t('{count} 个提问', { count: mineTotal }) : t('暂未发起')}
          color="blue"
        />
        <StatCard
          title={t('学习小组')}
          value={studyGroups.length}
          icon={Users}
          trend={t('3 个可加入')}
          color="green"
        />
        <StatCard
          title={t('我的导师')}
          value={mentors.length}
          icon={ThumbsUp}
          trend={t('可在线咨询')}
          color="amber"
        />
      </div>

      <div className="flex justify-end">
        <Button
          className="bg-primary hover:bg-primary/90"
          onClick={() => setPostOpen(true)}
          disabled={!!detail}
        >
          <Plus className="w-4 h-4 mr-1" />
          {t('发起提问')}
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
        {/* 话题列表 / 详情 */}
        <div className="lg:col-span-2">
          {detail ? (
            <div className="p-5 rounded-xl border border-gray-100 bg-white shadow-sm">
              <button
                className="flex items-center gap-1 text-xs text-gray-500 hover:text-primary transition-colors mb-4"
                onClick={closeDetail}
              >
                <ArrowLeft className="w-3.5 h-3.5" />
                {t('返回列表')}
              </button>

              {detailLoading ? (
                <div className="flex items-center justify-center py-16 text-gray-400">
                  <Loader2 className="w-5 h-5 animate-spin mr-2" />
                  {t('加载中...')}
                </div>
              ) : (
                <>
                  <div className="flex items-start gap-3">
                    <Avatar className="w-10 h-10 shrink-0">
                      {detail.avatarUrl ? (
                        <img
                          src={detail.avatarUrl}
                          alt={detail.authorName}
                          width={40}
                          height={40}
                          className="h-full w-full object-cover"
                        />
                      ) : (
                        <AvatarFallback className="bg-primary/5 text-primary text-sm font-medium">
                          {avatarChar(detail.authorName)}
                        </AvatarFallback>
                      )}
                    </Avatar>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h2 className="text-base font-semibold text-gray-900">{detail.title}</h2>
                        {detail.viewCount >= 50 && (
                          <Badge className="text-xs bg-rose-50 text-rose-600 hover:bg-rose-50 border-rose-100">
                            <Flame className="w-3 h-3 mr-0.5" />
                            {t('热门')}
                          </Badge>
                        )}
                      </div>
                      <div className="flex flex-wrap items-center gap-3 text-xs text-gray-500 mb-3">
                        <span className="font-medium text-gray-700">{detail.authorName}</span>
                        {detail.tag && (
                          <Badge
                            variant="outline"
                            className="text-[10px] px-1.5 py-0 border-gray-100 text-gray-500"
                          >
                            {detail.tag}
                          </Badge>
                        )}
                        <span>{formatDateTime(detail.createdAt)}</span>
                        <span className="flex items-center gap-1">
                          <MessageSquare className="w-3.5 h-3.5" />
                          {t('{count} 回复', { count: detail.replyCount })}
                        </span>
                        <span>{t('{count} 浏览', { count: detail.viewCount })}</span>
                      </div>
                    </div>
                  </div>

                  <div className="whitespace-pre-wrap text-sm text-gray-700 leading-7 bg-gray-50 rounded-xl p-4 mb-5">
                    {detail.content}
                  </div>

                  {/* 回复流 */}
                  <h3 className="text-sm font-semibold text-gray-900 mb-3">
                    {t('全部回复（{count}）', { count: replies.length })}
                  </h3>
                  <div className="space-y-4 mb-5">
                    {replies.length === 0 && (
                      <EmptyState compact title={t('暂无回复，快来抢沙发～')} titleClassName="text-gray-400" />
                    )}
                    {replies.map((reply) => (
                      <div key={reply.id} className="flex items-start gap-3">
                        <Avatar className="w-8 h-8 shrink-0">
                          {reply.avatarUrl ? (
                            <img
                              src={reply.avatarUrl}
                              alt={reply.authorName}
                              width={32}
                              height={32}
                              className="h-full w-full object-cover"
                            />
                          ) : (
                            <AvatarFallback className="bg-gray-50 text-gray-600 text-xs font-medium">
                              {avatarChar(reply.authorName)}
                            </AvatarFallback>
                          )}
                        </Avatar>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 text-xs text-gray-500 mb-0.5">
                            <span className="font-medium text-gray-700">{reply.authorName}</span>
                            {reply.parentAuthorName && (
                              <span className="text-gray-400">
                                {t('回复 @{name}', { name: reply.parentAuthorName })}
                              </span>
                            )}
                            <span>{formatDateTime(reply.createdAt)}</span>
                          </div>
                          <p className="text-sm text-gray-700 whitespace-pre-wrap">
                            {reply.content}
                          </p>
                          <button
                            className="flex items-center gap-1 mt-1 text-xs text-gray-400 hover:text-primary transition-colors"
                            onClick={() => setReplyingTo(reply)}
                          >
                            <Reply className="w-3 h-3" />
                            {t('回复')}
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* 回复输入 */}
                  <div className="rounded-xl border border-gray-100 bg-gray-50 p-3">
                    {replyingTo && (
                      <div className="flex items-center justify-between text-xs text-gray-500 mb-2">
                        <span>{t('回复 @{name} 的评论', { name: replyingTo.authorName })}</span>
                        <button
                          className="text-gray-400 hover:text-gray-600"
                          onClick={() => setReplyingTo(null)}
                        >
                          {t('取消')}
                        </button>
                      </div>
                    )}
                    <div className="flex items-end gap-2">
                      <Textarea
                        placeholder={t('写下你的回复...')}
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value)}
                        className="min-h-[60px] bg-white text-sm resize-none"
                        rows={2}
                      />
                      <Button
                        className="bg-primary hover:bg-primary/90 shrink-0"
                        size="sm"
                        disabled={!replyText.trim() || replySubmitting}
                        onClick={submitReply}
                      >
                        {replySubmitting ? (
                          <Loader2 className="w-3.5 h-3.5 animate-spin" />
                        ) : (
                          <Send className="w-3.5 h-3.5" />
                        )}
                        {t('回复')}
                      </Button>
                    </div>
                  </div>
                </>
              )}
            </div>
          ) : (
            <Tabs
              value={sort}
              onValueChange={(v) => setSort(v as CommunityTopicSort)}
              className="w-full"
            >
              <TabsList className="h-9 bg-white border border-gray-100 shadow-sm mb-4 p-1">
                {SORTS.map((s) => (
                  <TabsTrigger
                    key={s.id}
                    value={s.id}
                    className="text-sm px-4 data-[state=active]:bg-primary data-[state=active]:text-white"
                  >
                    {s.label}
                  </TabsTrigger>
                ))}
              </TabsList>

              <TabsContent value={sort} className="mt-0">
                {loading ? (
                  <div className="flex items-center justify-center py-16 text-gray-400">
                    <Loader2 className="w-5 h-5 animate-spin mr-2" />
                    {t('加载中...')}
                  </div>
                ) : topics.length === 0 ? (
                  <EmptyState
                    className="p-8 rounded-xl border border-gray-100 bg-white text-gray-400"
                    icon={
                      sort === 'mine' ? (
                        <MessageSquare className="w-12 h-12 opacity-40" />
                      ) : (
                        <Flame className="w-12 h-12 opacity-40" />
                      )
                    }
                    title={t(sort === 'mine' ? '你还没有发起过提问' : '暂无话题，来发第一帖吧')}
                    titleClassName="text-gray-400"
                    action={
                      <Button
                        className="bg-primary hover:bg-primary/90"
                        size="sm"
                        onClick={() => setPostOpen(true)}
                      >
                        <Plus className="w-4 h-4 mr-1" />
                        {t(sort === 'mine' ? '去提问' : '发起提问')}
                      </Button>
                    }
                  />
                ) : (
                  <div className="space-y-3">
                    {topics.map((topic) => (
                      <div
                        key={topic.id}
                        className="p-4 rounded-xl border border-gray-100 bg-white hover:border-primary/25 hover:shadow-sm transition-all cursor-pointer"
                        onClick={() => openDetail(topic)}
                      >
                        <div className="flex items-start gap-3">
                          <Avatar className="w-10 h-10 shrink-0">
                            {topic.avatarUrl ? (
                              <img
                                src={topic.avatarUrl}
                                alt={topic.authorName}
                                width={40}
                                height={40}
                                className="h-full w-full object-cover"
                              />
                            ) : (
                              <AvatarFallback className="bg-primary/5 text-primary text-sm font-medium">
                                {avatarChar(topic.authorName)}
                              </AvatarFallback>
                            )}
                          </Avatar>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 mb-1">
                              <h3 className="text-sm font-semibold text-gray-900 hover:text-primary transition-colors truncate">
                                {topic.title}
                              </h3>
                              {topic.viewCount >= 50 && (
                                <Badge className="text-xs bg-rose-50 text-rose-600 hover:bg-rose-50 border-rose-100 shrink-0">
                                  <Flame className="w-3 h-3 mr-0.5" />
                                  {t('热门')}
                                </Badge>
                              )}
                            </div>
                            <div className="flex items-center gap-3 text-xs text-gray-500 mb-2">
                              <span className="font-medium text-gray-700">{topic.authorName}</span>
                              {topic.tag && (
                                <Badge
                                  variant="outline"
                                  className="text-[10px] px-1.5 py-0 border-gray-100 text-gray-500"
                                >
                                  {topic.tag}
                                </Badge>
                              )}
                            </div>
                            <div className="flex items-center gap-4 text-xs text-gray-400">
                              <span className="flex items-center gap-1">
                                <MessageSquare className="w-3.5 h-3.5" />
                                {t('{count} 回复', { count: topic.replyCount })}
                              </span>
                              <span>{t('{count} 浏览', { count: topic.viewCount })}</span>
                              <span>{formatDateTime(topic.createdAt)}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </TabsContent>
            </Tabs>
          )}
        </div>

        {/* 侧边栏 */}
        <div className="space-y-5">
          {/* 学习小组 */}
          <SectionCard title={t('学习小组')} icon={Users} iconColor="blue">
            <div className="space-y-2">
              {studyGroups.map((group) => (
                <div
                  key={group.id}
                  className="flex items-center justify-between p-3 rounded-xl bg-gray-50 hover:bg-gray-100 transition-colors cursor-pointer"
                >
                  <div>
                    <p className="text-sm font-medium text-gray-900">{group.name}</p>
                    <p className="text-xs text-gray-500">
                      {t('{count} 人', { count: group.members })}
                    </p>
                  </div>
                  <Button
                    size="sm"
                    variant={group.active ? 'default' : 'outline'}
                    className={
                      group.active
                        ? 'bg-primary hover:bg-primary/90 text-xs'
                        : 'text-xs border-gray-200 text-gray-600'
                    }
                  >
                    {t(group.active ? '加入' : '已满')}
                  </Button>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* 导师/教师 */}
          <SectionCard title={t('我的导师')} icon={ThumbsUp} iconColor="amber">
            <div className="space-y-3">
              {mentors.map((mentor) => (
                <div key={mentor.id} className="flex items-center gap-3">
                  <Avatar className="w-10 h-10">
                    <AvatarFallback className="bg-amber-50 text-amber-600 text-sm font-medium">
                      {mentor.avatar}
                    </AvatarFallback>
                  </Avatar>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900">{mentor.name}</p>
                    <p className="text-xs text-gray-500 truncate">{mentor.role}</p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    className="text-xs border-gray-200 text-gray-700 hover:bg-gray-50 shrink-0"
                  >
                    {t('咨询')}
                  </Button>
                </div>
              ))}
            </div>
          </SectionCard>

          {/* 社区公告 */}
          <SectionCard title={t('社区规范')} icon={MessageCircle} iconColor="green">
            <ul className="space-y-2 text-xs text-gray-500">
              <li>• {t('请友善交流，尊重他人观点')}</li>
              <li>• {t('提问前建议先搜索已有话题')}</li>
              <li>• {t('鼓励分享学习笔记与实践经验')}</li>
              <li>• {t('禁止发布与教学无关的内容')}</li>
            </ul>
          </SectionCard>
        </div>
      </div>

      {/* 发帖弹窗 */}
      <Dialog open={postOpen} onOpenChange={setPostOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t('发起提问')}</DialogTitle>
            <DialogDescription>{t('分享你的学习问题或经验，和同学们一起交流。')}</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-gray-600">{t('标题')}</label>
              <Input
                placeholder={t('一句话说清你的问题')}
                value={postTitle}
                maxLength={128}
                onChange={(e) => setPostTitle(e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-gray-600">{t('标签（选填）')}</label>
              <Input
                placeholder={t('如：网络技术')}
                value={postTag}
                maxLength={32}
                onChange={(e) => setPostTag(e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-gray-600">{t('内容')}</label>
              <Textarea
                placeholder={t('补充详细描述，便于同学们解答')}
                value={postContent}
                rows={5}
                onChange={(e) => setPostContent(e.target.value)}
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setPostOpen(false)}>
                {t('取消')}
              </Button>
              <Button
                className="bg-primary hover:bg-primary/90"
                disabled={postSubmitting}
                onClick={submitPost}
              >
                {postSubmitting && <Loader2 className="w-4 h-4 mr-1 animate-spin" />}
                {t('发布')}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
