// plus-ui/src-portal/components/archive-list-page.vue
<template>
  <div class="archive-page">
    <!-- 页头 -->
    <div class="page-header">
      <h2 class="page-title">{{ pageTitle }}</h2>
      <p v-if="pageDescription" class="page-subtitle">{{ pageDescription }}</p>
    </div>

    <div class="archive-body">
      <!-- 侧栏：专业 / 类型筛选 -->
      <el-card v-if="sidebarItems.length > 0" shadow="never" class="sidebar-card">
        <div class="sidebar-title">{{ sidebarTitle }}</div>
        <el-scrollbar max-height="500px">
          <div class="sidebar-list">
            <div
              class="sidebar-item"
              :class="{ active: sidebarSelectedId === null }"
              @click="onSidebarSelect(null)"
            >
              全部专业
            </div>
            <div
              v-for="item in sidebarItems"
              :key="item.id"
              class="sidebar-item"
              :class="{ active: sidebarSelectedId === item.id }"
              @click="onSidebarSelect(item.id)"
            >
              {{ item.name }}
            </div>
          </div>
        </el-scrollbar>
      </el-card>

      <!-- 主区 -->
      <div class="archive-main">
        <!-- 搜索 -->
        <el-card shadow="never" class="search-card">
          <el-input
            :model-value="searchValue"
            :placeholder="searchPlaceholder"
            clearable
            @update:model-value="onSearchChange"
          >
            <template #prefix><el-icon><Search /></el-icon></template>
          </el-input>
        </el-card>

        <!-- 批量操作条 -->
        <div v-if="hasBatchOps && selectedIds.length > 0" class="batch-bar">
          <span class="batch-tip">已选择 {{ selectedIds.length }} 个{{ entityLabel }}</span>
          <div class="batch-actions">
            <el-button v-if="onBatchRestore" size="small" :loading="busy" @click="handleBatchRestore">
              <el-icon><RefreshLeft /></el-icon>
              批量恢复
            </el-button>
            <el-button
              v-if="onBatchDelete"
              size="small"
              type="danger"
              plain
              @click="batchDeleteVisible = true"
            >
              <el-icon><Delete /></el-icon>
              批量删除
            </el-button>
          </div>
        </div>

        <!-- 列表 -->
        <el-card shadow="never" class="table-card">
          <el-table v-loading="loading" :data="items" stripe @selection-change="onSelectionChange">
            <el-table-column v-if="hasBatchOps" type="selection" width="46" />

            <el-table-column
              v-for="col in columns"
              :key="col.prop || col.label"
              :prop="col.prop"
              :label="col.label"
              :width="col.width"
              :min-width="col.minWidth"
            >
              <template #default="{ row }">
                <CellRenderer :content="resolveCell(col, row)" />
              </template>
            </el-table-column>

            <el-table-column label="状态" width="110">
              <template #default="{ row }">
                <el-tag type="info" effect="plain">{{ renderStatus(row) }}</el-tag>
              </template>
            </el-table-column>

            <el-table-column label="操作" width="190" fixed="right">
              <template #default="{ row }">
                <router-link v-if="detailHref" :to="detailHref(row)" class="action-link">查看</router-link>
                <el-button size="small" type="primary" link :disabled="busy" @click="handleRestore(row)">
                  恢复
                </el-button>
                <el-button
                  v-if="onDelete"
                  size="small"
                  type="danger"
                  link
                  :disabled="busy"
                  @click="handleDelete(row)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>

          <el-empty v-if="!loading && items.length === 0" :description="emptyMessage" />
        </el-card>
      </div>
    </div>

    <!-- 删除确认 -->
    <el-dialog v-model="deleteDialogVisible" title="确认删除" width="420px">
      <span>{{ deleteDescription }}</span>
      <template #footer>
        <el-button @click="deleteDialogVisible = false">取消</el-button>
        <el-button type="danger" :loading="busy" @click="confirmDelete">删除</el-button>
      </template>
    </el-dialog>

    <!-- 批量删除确认 -->
    <el-dialog v-model="batchDeleteVisible" title="确认批量删除" width="420px">
      <span>确定删除选中的 {{ selectedIds.length }} 个{{ entityLabel }}吗？删除后不可恢复。</span>
      <template #footer>
        <el-button @click="batchDeleteVisible = false">取消</el-button>
        <el-button type="danger" :loading="busy" @click="confirmBatchDelete">删除</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, h, ref, type VNode } from 'vue';
import { Delete, RefreshLeft, Search } from '@element-plus/icons-vue';
import { contentStatusLabel } from '@/types/content-status';

export interface ArchiveColumn {
  label: string;
  prop?: string;
  width?: string | number;
  minWidth?: string | number;
  formatter?: (row: Record<string, any>) => string;
  cell?: (row: Record<string, any>) => VNode | string;
}

type Row = Record<string, any>;

const props = withDefaults(
  defineProps<{
    entityLabel: string;
    pageTitle: string;
    pageDescription?: string;
    sidebarTitle?: string;
    sidebarItems?: { id: string; name: string }[];
    sidebarSelectedId?: string | null;
    onSidebarSelect?: (id: string | null) => void;
    items: Row[];
    loading?: boolean;
    onRestore: (item: Row) => Promise<void>;
    onDelete?: (item: Row) => Promise<void>;
    onBatchRestore?: (ids: string[]) => Promise<void>;
    onBatchDelete?: (ids: string[]) => Promise<void>;
    detailHref?: (item: Row) => string;
    searchPlaceholder?: string;
    searchValue?: string;
    onSearchChange?: (value: string) => void;
    columns: ArchiveColumn[];
    renderStatus?: (item: Row) => string;
    emptyMessage?: string;
  }>(),
  {
    pageDescription: '',
    sidebarTitle: '筛选',
    sidebarItems: () => [],
    sidebarSelectedId: null,
    onSidebarSelect: () => {},
    loading: false,
    onDelete: undefined,
    onBatchRestore: undefined,
    onBatchDelete: undefined,
    detailHref: undefined,
    searchPlaceholder: '搜索...',
    searchValue: '',
    onSearchChange: () => {},
    renderStatus: (item: Row) => contentStatusLabel(String(item?.status || 'archived')),
    emptyMessage: '暂无归档数据'
  }
);

const selectedIds = ref<string[]>([]);
const deleteTarget = ref<Row | null>(null);
const deleteDialogVisible = ref(false);
const batchDeleteVisible = ref(false);
const busy = ref(false);

const hasBatchOps = computed(() => !!(props.onBatchRestore || props.onBatchDelete));

const deleteDescription = computed(() =>
  deleteTarget.value ? `确定永久删除「${deleteTarget.value.name}」吗？此操作不可恢复。` : ''
);

// 轻量渲染器：将 cell()/formatter() 返回的 VNode 或字符串渲染进表格单元格。
const CellRenderer = (p: { content: VNode | string | number }) =>
  typeof p.content === 'string' || typeof p.content === 'number' ? h('span', String(p.content)) : p.content;

function resolveCell(col: ArchiveColumn, row: Row): VNode | string {
  if (col.cell) return col.cell(row);
  if (col.formatter) return col.formatter(row);
  const v = col.prop ? row[col.prop] : '';
  return v == null || v === '' ? '-' : String(v);
}

function onSelectionChange(selection: Row[]) {
  selectedIds.value = selection.map((it) => String(it.id));
}

async function handleRestore(row: Row) {
  if (busy.value) return;
  busy.value = true;
  try {
    await props.onRestore(row);
  } finally {
    busy.value = false;
  }
}

function handleDelete(row: Row) {
  deleteTarget.value = row;
  deleteDialogVisible.value = true;
}

async function confirmDelete() {
  if (!deleteTarget.value || !props.onDelete || busy.value) return;
  busy.value = true;
  try {
    await props.onDelete(deleteTarget.value);
    selectedIds.value = selectedIds.value.filter((id) => id !== deleteTarget.value!.id);
    deleteTarget.value = null;
    deleteDialogVisible.value = false;
  } finally {
    busy.value = false;
  }
}

async function handleBatchRestore() {
  if (!props.onBatchRestore || selectedIds.value.length === 0 || busy.value) return;
  busy.value = true;
  try {
    await props.onBatchRestore([...selectedIds.value]);
    selectedIds.value = [];
  } finally {
    busy.value = false;
  }
}

async function confirmBatchDelete() {
  if (!props.onBatchDelete || selectedIds.value.length === 0 || busy.value) return;
  busy.value = true;
  try {
    await props.onBatchDelete([...selectedIds.value]);
    selectedIds.value = [];
    batchDeleteVisible.value = false;
  } finally {
    busy.value = false;
  }
}
</script>

<style scoped>
.archive-page {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.page-header {
  margin-bottom: 4px;
}
.page-title {
  font-size: 20px;
  font-weight: 600;
  margin: 0;
}
.page-subtitle {
  font-size: 13px;
  color: #909399;
  margin: 4px 0 0;
}
.archive-body {
  display: flex;
  gap: 16px;
  align-items: flex-start;
}
.sidebar-card {
  width: 256px;
  flex-shrink: 0;
}
.sidebar-title {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 12px;
}
.sidebar-list {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.sidebar-item {
  padding: 6px 8px;
  font-size: 13px;
  border-radius: 4px;
  cursor: pointer;
  color: #606266;
}
.sidebar-item:hover {
  background: #f5f7fa;
}
.sidebar-item.active {
  background: #409eff;
  color: #fff;
}
.archive-main {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.search-card :deep(.el-card__body) {
  padding: 16px;
}
.batch-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border: 1px solid #ebeef5;
  border-radius: 6px;
  background: #fff;
}
.batch-tip {
  font-size: 13px;
  color: #909399;
}
.batch-actions {
  display: flex;
  gap: 8px;
}
.table-card :deep(.el-card__body) {
  padding: 0;
}
.action-link {
  margin-right: 12px;
  color: #409eff;
  text-decoration: none;
  font-size: 13px;
}
.action-link:hover {
  text-decoration: underline;
}
</style>

// apps/edu/components/shared/archive-list-page.tsx
"use client"

import { useState, type ReactNode } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Checkbox } from "@/components/ui/checkbox"
import { cn } from "@/lib/utils"
import { Search, GraduationCap, Eye, RotateCcw, Trash2 } from "lucide-react"
import { StatusBadge } from "@/components/shared/status-badge"
import { TableRowActions } from "@/components/shared/table-row-actions"
import { ConfirmDialog } from "@/components/shared/confirm-dialog"

export interface ArchiveColumn<T> {
  header: string
  className?: string
  cell: (item: T) => ReactNode
}

export interface ArchiveListPageProps<
  T extends { id: string; name: string; status: string }
> {
  entityLabel: string
  pageTitle: string
  pageDescription: string

  sidebarTitle: string
  sidebarItems: { id: string; name: string }[]
  sidebarSelectedId: string | null
  onSidebarSelect: (id: string | null) => void

  items: T[]
  loading: boolean

  onRestore: (item: T) => Promise<void>
  onDelete?: (item: T) => Promise<void>
  onBatchRestore?: (ids: string[]) => Promise<void>
  onBatchDelete?: (ids: string[]) => Promise<void>

  detailHref: (item: T) => string

  searchPlaceholder: string
  searchValue: string
  onSearchChange: (value: string) => void

  columns: ArchiveColumn<T>[]

  renderStatus?: (item: T) => ReactNode
  emptyMessage?: string
}

export function ArchiveListPage<
  T extends { id: string; name: string; status: string }
>({
  entityLabel,
  pageTitle,
  pageDescription,
  sidebarTitle,
  sidebarItems,
  sidebarSelectedId,
  onSidebarSelect,
  items,
  loading,
  onRestore,
  onDelete,
  onBatchRestore,
  onBatchDelete,
  detailHref,
  searchPlaceholder,
  searchValue,
  onSearchChange,
  columns,
  renderStatus,
  emptyMessage = `暂无归档${entityLabel}`,
}: ArchiveListPageProps<T>) {
  const [selectedIds, setSelectedIds] = useState<string[]>([])
  const [deleteTarget, setDeleteTarget] = useState<T | null>(null)

  const hasBatchOps = !!(onBatchRestore || onBatchDelete)

  const handleSelect = (id: string, checked: boolean) => {
    setSelectedIds((prev) =>
      checked
        ? prev.includes(id)
          ? prev
          : [...prev, id]
        : prev.filter((item) => item !== id)
    )
  }

  const handleSelectAll = (checked: boolean) => {
    setSelectedIds(checked ? items.map((p) => p.id) : [])
  }

  const allSelected =
    items.length > 0 && items.every((p) => selectedIds.includes(p.id))
  const someSelected =
    items.some((p) => selectedIds.includes(p.id)) && !allSelected

  const handleBatchRestore = async () => {
    if (!onBatchRestore || selectedIds.length === 0) return
    await onBatchRestore(selectedIds)
    setSelectedIds([])
  }

  const handleBatchDelete = async () => {
    if (!onBatchDelete || selectedIds.length === 0) return
    await onBatchDelete(selectedIds)
    setSelectedIds([])
  }

  const handleRestore = async (item: T) => {
    await onRestore(item)
  }

  const handleDelete = async (item: T) => {
    if (!onDelete) return
    setDeleteTarget(item)
  }

  const confirmDelete = async () => {
    if (!deleteTarget || !onDelete) return
    await onDelete(deleteTarget)
    setSelectedIds((prev) => prev.filter((id) => id !== deleteTarget.id))
    setDeleteTarget(null)
  }

  const colSpan = columns.length + (hasBatchOps ? 2 : 1)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">{pageTitle}</h1>
        <p className="text-muted-foreground mt-1">{pageDescription}</p>
      </div>

      <div className="flex gap-4 items-start">
        <div className="w-64 shrink-0 rounded-lg border border-gray-100 bg-white shadow-sm p-4">
          <h3 className="text-sm font-semibold mb-3 flex items-center gap-1.5">
            <GraduationCap className="h-4 w-4 text-primary" />
            {sidebarTitle}
          </h3>
          <ScrollArea className="h-[500px]">
            <div className="space-y-1">
              <button
                onClick={() => onSidebarSelect(null)}
                className={cn(
                  "w-full text-left px-2 py-1.5 text-sm rounded-md transition-colors",
                  sidebarSelectedId === null
                    ? "bg-primary text-primary-foreground"
                    : "hover:bg-muted"
                )}
              >
                全部专业
              </button>
              {sidebarItems.map((item) => (
                <button
                  key={item.id}
                  onClick={() => onSidebarSelect(item.id)}
                  className={cn(
                    "w-full text-left px-2 py-1.5 text-sm rounded-md transition-colors",
                    sidebarSelectedId === item.id
                      ? "bg-primary text-primary-foreground"
                      : "hover:bg-muted"
                  )}
                >
                  {item.name}
                </button>
              ))}
            </div>
          </ScrollArea>
        </div>

        <div className="flex-1 min-w-0 space-y-4">
          <div className="rounded-lg border border-gray-100 bg-white shadow-sm p-4">
            <div className="relative">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder={searchPlaceholder}
                className="pl-9"
                value={searchValue}
                onChange={(e) => onSearchChange(e.target.value)}
              />
            </div>
          </div>

          {hasBatchOps && selectedIds.length > 0 && (
            <div className="flex items-center justify-between rounded-lg border border-gray-100 bg-white shadow-sm p-3">
              <span className="text-sm text-muted-foreground">
                已选择{" "}
                <span className="font-medium text-foreground">
                  {selectedIds.length}
                </span>{" "}
                个{entityLabel}
              </span>
              <div className="flex items-center gap-2">
                {onBatchRestore && (
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-8 text-xs"
                    onClick={handleBatchRestore}
                  >
                    <RotateCcw className="mr-1.5 h-3.5 w-3.5" />
                    批量恢复
                  </Button>
                )}
                {onBatchDelete && (
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-8 text-xs text-red-600 hover:text-red-700 hover:bg-red-50"
                    onClick={handleBatchDelete}
                  >
                    <Trash2 className="mr-1.5 h-3.5 w-3.5" />
                    批量删除
                  </Button>
                )}
              </div>
            </div>
          )}

          <div className="rounded-lg border border-gray-100 bg-white shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <Table className="min-w-[900px] w-full">
                <TableHeader>
                  <TableRow>
                    {hasBatchOps && (
                      <TableHead className="w-10 px-3">
                        <Checkbox
                          checked={
                            someSelected ? "indeterminate" : allSelected
                          }
                          onCheckedChange={(checked) =>
                            handleSelectAll(checked === true)
                          }
                          aria-label="全选"
                        />
                      </TableHead>
                    )}
                    {columns.map((col, i) => (
                      <TableHead key={i} className={col.className}>
                        {col.header}
                      </TableHead>
                    ))}
                    <TableHead className="w-20">状态</TableHead>
                    <TableHead className="w-28 text-right px-3">操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {loading ? (
                    <TableRow>
                      <TableCell
                        colSpan={colSpan}
                        className="text-center py-10 text-muted-foreground"
                      >
                        加载中...
                      </TableCell>
                    </TableRow>
                  ) : items.length === 0 ? (
                    <TableRow>
                      <TableCell
                        colSpan={colSpan}
                        className="text-center py-10 text-muted-foreground"
                      >
                        {emptyMessage}
                      </TableCell>
                    </TableRow>
                  ) : (
                    items.map((item) => {
                      const isSelected = selectedIds.includes(item.id)
                      return (
                        <TableRow
                          key={item.id}
                          className="group"
                          data-state={isSelected ? "selected" : undefined}
                        >
                          {hasBatchOps && (
                            <TableCell className="px-3">
                              <Checkbox
                                checked={isSelected}
                                onCheckedChange={(checked) =>
                                  handleSelect(item.id, checked === true)
                                }
                                aria-label={`选择 ${item.name}`}
                              />
                            </TableCell>
                          )}
                          {columns.map((col, i) => (
                            <TableCell key={i} className={col.className}>
                              {col.cell(item)}
                            </TableCell>
                          ))}
                          <TableCell>
                            {renderStatus ? (
                              renderStatus(item)
                            ) : (
                              <StatusBadge status={item.status} />
                            )}
                          </TableCell>
                          <TableRowActions className="px-3">
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 px-2 text-xs"
                              asChild
                            >
                              <Link href={detailHref(item)}>
                                <Eye className="mr-1 h-3 w-3" />
                                查看
                              </Link>
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 px-2 text-xs text-blue-600 hover:text-blue-700"
                              onClick={() => handleRestore(item)}
                            >
                              <RotateCcw className="mr-1 h-3 w-3" />
                              恢复
                            </Button>
                            {onDelete && (
                              <Button
                                variant="ghost"
                                size="sm"
                                className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                                onClick={() => handleDelete(item)}
                              >
                                <Trash2 className="mr-1 h-3 w-3" />
                                删除
                              </Button>
                            )}
                          </TableRowActions>
                        </TableRow>
                      )
                    })
                  )}
                </TableBody>
              </Table>
            </div>
          </div>
        </div>
      </div>

      <ConfirmDialog
        open={deleteTarget !== null}
        onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}
        title="确认删除"
        description={deleteTarget ? `确定永久删除 "${deleteTarget.name}" 吗？此操作不可恢复。` : ""}
        variant="destructive"
        onConfirm={confirmDelete}
      />
    </div>
  )
}
