// frontend/portal-vue/src/views/library/_components/CitationStatsPanel.vue
<template>
  <div class="citation-panel">
    <div class="left-col">
      <div class="stat-card">
        <div class="stat-num">{{ statCount }}</div>
        <div class="stat-label">{{ statLabel }}</div>
      </div>
      <button type="button" class="zero-card" @click="dialogOpen = true">
        <div class="zero-num">{{ stats?.zeroCount ?? '-' }}</div>
        <div class="zero-label">零引用{{ entityLabel }}</div>
        <div class="zero-action">去管理 ›</div>
      </button>
    </div>

    <div class="chart-card">
      <div class="chart-head">
        <span class="chart-title">引用次数分布</span>
        <span class="chart-sub">共 {{ stats?.total ?? '-' }} 个{{ entityLabel }}</span>
      </div>
      <div v-if="chartData.length" class="bars">
        <div v-for="b in chartData" :key="b.label" class="bar-col">
          <span class="bar-count">{{ b.count }}</span>
          <div class="bar-track">
            <div class="bar" :style="{ height: barHeight(b.count) }"></div>
          </div>
          <span class="bar-label">{{ b.label }}</span>
        </div>
      </div>
      <div v-else class="chart-empty">暂无统计数据</div>
    </div>

    <UncitedResourcesDialog
      v-model="dialogOpen"
      :title="dialogTitle"
      :entity-label="entityLabel"
      :fetch-uncited="fetchUncited"
      :delete-item="deleteItem"
      @deleted="onUncitedDeleted"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import UncitedResourcesDialog from './UncitedResourcesDialog.vue';
import type { CitationStats, UncitedItem } from './types';

const props = defineProps<{
  entityLabel: string;
  dialogTitle: string;
  fetchStats: () => Promise<CitationStats>;
  fetchUncited: (params: {
    startDate?: string;
    endDate?: string;
    limit: number;
    offset: number;
  }) => Promise<{ items: UncitedItem[]; total: number }>;
  deleteItem: (id: string) => Promise<unknown>;
  statCount: number;
  statLabel: string;
}>();
const emit = defineEmits<{ (e: 'deleted'): void }>();

const stats = ref<CitationStats | null>(null);
const dialogOpen = ref(false);

const chartData = computed(() => stats.value?.buckets || []);
const maxCount = computed(() => Math.max(1, ...chartData.value.map((b) => b.count)));

function barHeight(count: number): string {
  if (count <= 0) return '2px';
  return `${Math.max(6, Math.round((count / maxCount.value) * 80))}px`;
}

async function loadStats(): Promise<void> {
  try {
    stats.value = await props.fetchStats();
  } catch {
    stats.value = null;
  }
}

function onUncitedDeleted(): void {
  emit('deleted');
  void loadStats();
}

onMounted(() => {
  void loadStats();
});
</script>

<style scoped>
.citation-panel {
  display: flex;
  gap: 12px;
  margin-bottom: 16px;
}
.left-col {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 208px;
  flex-shrink: 0;
}
.stat-card {
  flex: 1;
  min-height: 0;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px;
  border-radius: 12px;
  background: linear-gradient(135deg, #eef2ff, #f5f7ff);
}
.stat-num {
  font-size: 24px;
  font-weight: 700;
  color: #303133;
}
.stat-label {
  font-size: 12px;
  color: #94a3b8;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.zero-card {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: flex-start;
  padding: 16px;
  border: 0;
  border-radius: 12px;
  cursor: pointer;
  text-align: left;
  background: linear-gradient(135deg, #fff1f2, #fff7ed);
  transition: background 0.2s;
}
.zero-card:hover {
  background: linear-gradient(135deg, #ffe4e6, #ffedd5);
}
.zero-num {
  font-size: 24px;
  font-weight: 700;
  color: #f43f5e;
}
.zero-label {
  font-size: 12px;
  color: #fb7185;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.zero-action {
  font-size: 11px;
  font-weight: 500;
  color: #f43f5e;
}
.chart-card {
  flex: 1;
  min-width: 0;
  padding: 16px;
  border-radius: 12px;
  background: #fff;
  border: 1px solid #f1f5f9;
}
.chart-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 12px;
}
.chart-title {
  font-size: 14px;
  font-weight: 600;
  color: #334155;
}
.chart-sub {
  font-size: 12px;
  color: #94a3b8;
}
.bars {
  display: flex;
  align-items: flex-end;
  gap: 12px;
  height: 112px;
}
.bar-col {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100%;
}
.bar-count {
  font-size: 11px;
  color: #64748b;
  margin-bottom: 4px;
}
.bar-track {
  flex: 1;
  width: 100%;
  max-width: 40px;
  display: flex;
  align-items: flex-end;
  justify-content: center;
}
.bar {
  width: 100%;
  border-radius: 4px 4px 0 0;
  background: #6366f1;
  min-height: 2px;
}
.bar-label {
  font-size: 10px;
  color: #94a3b8;
  margin-top: 4px;
  white-space: nowrap;
}
.chart-empty {
  height: 112px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  color: #cbd5e1;
}
</style>

// apps/edu/components/shared/citation-stats-panel.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { BarChart3, FileX2, ChevronRight } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts'
import type { CitationStats, UncitedItem } from '@/lib/types/library'
import { UncitedResourcesDialog } from './uncited-resources-dialog'

interface CitationStatsPanelProps {
  /** 实体名称，如「知识点」「资源」 */
  entityLabel: string
  /** 弹窗标题，如「零引用知识点」 */
  dialogTitle: string
  fetchStats: (params?: { resourceType?: string }) => Promise<CitationStats>
  fetchUncited: (params: {
    resourceType?: string
    startDate?: string
    endDate?: string
    limit: number
    offset: number
  }) => Promise<{ items: UncitedItem[]; total: number }>
  deleteItem: (id: string) => Promise<unknown>
  /** 批量删除成功后回调（刷新页面列表/统计） */
  onDeleted?: () => void
  /** 单类型视图下按类型过滤统计 */
  resourceType?: string
  /** 左侧指标卡片（与零引用卡片上下排列，各占一半高度） */
  statCount?: number
  statLabel?: string
  statIcon?: ReactNode
  statGradient?: string
  /** 统计卡片图标底色的样式类 */
  statIconWrapClass?: string
}

/**
 * 库页面顶部指标区：左侧「总数」与「零引用」卡片上下排列（各半高），
 * 右侧引用次数分布柱状图占满整列（总高度一致）。
 * 引用次数由后端统计（课程/节点/题库等引用源），分桶：0/1-5/6-10/11-100/100 以上。
 */
export function CitationStatsPanel({
  entityLabel,
  dialogTitle,
  fetchStats,
  fetchUncited,
  deleteItem,
  onDeleted,
  resourceType,
  statCount,
  statLabel,
  statIcon,
  statGradient = 'from-primary/5 to-primary/10',
  statIconWrapClass = 'bg-primary/10',
}: CitationStatsPanelProps) {
  const [stats, setStats] = useState<CitationStats | null>(null)
  const [dialogOpen, setDialogOpen] = useState(false)

  const loadStats = useCallback(async () => {
    try {
      const res = await fetchStats(resourceType ? { resourceType } : undefined)
      setStats(res)
    } catch {
      setStats(null)
    }
  }, [fetchStats, resourceType])

  // 将首载视为外部事件：在微任务回调中分发加载，避免 effect 体内同步 setState
  useEffect(() => {
    Promise.resolve().then(loadStats)
  }, [loadStats])

  const chartData = stats?.buckets || []

  return (
    <div className="flex flex-col lg:flex-row gap-3">
      <div className="flex flex-col gap-3 lg:w-52 shrink-0">
        {statCount !== undefined && (
          <Card className={`border-0 shadow-sm bg-gradient-to-br ${statGradient} flex-1 min-h-0`}>
            <CardContent className="p-4 flex items-center gap-3 h-full">
              <div
                className={`w-10 h-10 rounded-lg ${statIconWrapClass} flex items-center justify-center shrink-0`}
              >
                {statIcon}
              </div>
              <div className="min-w-0">
                <div className="text-2xl font-bold">{statCount}</div>
                <div className="text-xs opacity-70 truncate">{statLabel}</div>
              </div>
            </CardContent>
          </Card>
        )}
        <button
          type="button"
          onClick={() => setDialogOpen(true)}
          title={`点击查看并批量删除从未被引用的${entityLabel}`}
          className="text-left cursor-pointer rounded-xl border-0 shadow-sm bg-gradient-to-br from-rose-50 to-orange-50 hover:from-rose-100 hover:to-orange-100 transition-colors p-4 flex-1 min-h-0 flex flex-col justify-between"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-rose-500/10 flex items-center justify-center shrink-0">
              <FileX2 className="size-5 text-rose-500" />
            </div>
            <div className="min-w-0">
              <div className="text-2xl font-bold text-rose-500">{stats?.zeroCount ?? '-'}</div>
              <div className="text-xs text-rose-400 truncate">零引用{entityLabel}</div>
            </div>
          </div>
          <div className="flex items-center gap-0.5 text-[11px] font-medium text-rose-500/80">
            去管理
            <ChevronRight className="size-3.5" />
          </div>
        </button>
      </div>

      <Card className="border-0 shadow-sm flex-1 min-w-0">
        <CardContent className="p-4">
          <div className="flex items-center gap-2 mb-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/10 flex items-center justify-center">
              <BarChart3 className="size-4 text-indigo-500" />
            </div>
            <div>
              <div className="text-sm font-semibold text-slate-700">引用次数分布</div>
              <div className="text-xs text-slate-400">
                共 {stats?.total ?? '-'} 个{entityLabel}
              </div>
            </div>
          </div>
          <div className="h-28">
            {chartData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 4, right: 4, left: -28, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" vertical={false} />
                  <XAxis
                    dataKey="label"
                    tick={{ fontSize: 10, fill: '#94a3b8' }}
                    axisLine={false}
                    tickLine={false}
                  />
                  <YAxis tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} />
                  <Tooltip
                    cursor={{ fill: 'rgba(99,102,241,0.06)' }}
                    contentStyle={{ fontSize: 12, borderRadius: 8 }}
                    formatter={(value: any) => [`${value} 个`, '数量']}
                  />
                  <Bar dataKey="count" fill="#6366f1" radius={[4, 4, 0, 0]} maxBarSize={36} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-full flex items-center justify-center text-xs text-slate-300">
                暂无统计数据
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <UncitedResourcesDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        title={dialogTitle}
        entityLabel={entityLabel}
        fetchUncited={(params) =>
          fetchUncited(resourceType ? { ...params, resourceType } : params)
        }
        deleteItem={deleteItem}
        onDeleted={() => {
          onDeleted?.()
          void loadStats()
        }}
      />
    </div>
  )
}
