// frontend/portal-vue/src/views/job/position-builder/EditorShell.vue
<template>
  <!-- 全屏编辑外壳（对齐 React frontend/edu/components/shared/editor-shell.tsx mode="fullscreen"） -->
  <div class="editor-shell">
    <div class="shell-header">
      <div class="header-left">
        <el-button text class="back-btn" @click="emit('back')">
          <el-icon><Close /></el-icon>
          {{ backText }}
        </el-button>
        <el-divider direction="vertical" />
        <el-tag type="primary" effect="dark" class="step-tag">步骤 {{ step }}</el-tag>
        <span class="step-label">{{ stepLabel }}</span>
      </div>
      <div class="header-right">
        <span v-if="loadingText" class="loading-text">
          <el-icon class="is-loading"><Loading /></el-icon>
          {{ loadingText }}
        </span>
        <el-button :disabled="isSaving || saveDisabled" @click="emit('save-draft')">
          <el-icon><Files /></el-icon>
          {{ isSaving ? '保存中...' : '保存草稿' }}
        </el-button>
        <el-button @click="emit('preview')">
          <el-icon><View /></el-icon>
          预览
        </el-button>
        <el-button v-if="canPrev" @click="emit('prev')">
          <el-icon><ArrowLeft /></el-icon>
          上一步
        </el-button>
        <el-button v-if="canNext" type="primary" :disabled="nextDisabled" @click="emit('next')">
          {{ nextText }}
          <el-icon><ArrowRight /></el-icon>
        </el-button>
        <el-button v-else type="primary" @click="emit('submit')">
          <el-icon><Check /></el-icon>
          {{ submitText }}
        </el-button>
      </div>
    </div>

    <div class="shell-body">
      <div v-if="title" class="page-title">
        <h1>{{ title }}</h1>
        <p v-if="subtitle">{{ subtitle }}</p>
      </div>
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  ArrowLeft,
  ArrowRight,
  Check,
  Close,
  Files,
  Loading,
  View
} from '@element-plus/icons-vue';

withDefaults(
  defineProps<{
    backText?: string;
    step: number;
    stepLabel: string;
    isSaving?: boolean;
    saveDisabled?: boolean;
    canPrev?: boolean;
    canNext?: boolean;
    /** 下一步按钮文案（对齐 React EditorShell nextText，缺省「下一步」） */
    nextText?: string;
    /** 下一步按钮禁用（对齐 React EditorShell nextDisabled） */
    nextDisabled?: boolean;
    submitText?: string;
    loadingText?: string;
    title?: string;
    subtitle?: string;
  }>(),
  {
    backText: '取消',
    isSaving: false,
    saveDisabled: false,
    canPrev: false,
    canNext: false,
    nextText: '下一步',
    nextDisabled: false,
    submitText: '完成配置',
    loadingText: '',
    title: '',
    subtitle: ''
  }
);

const emit = defineEmits<{
  (e: 'back'): void;
  (e: 'save-draft'): void;
  (e: 'preview'): void;
  (e: 'prev'): void;
  (e: 'next'): void;
  (e: 'submit'): void;
}>();
</script>

<style scoped>
.editor-shell {
  position: fixed;
  inset: 0;
  z-index: 1000;
  overflow: auto;
  background: #f5f7fa;
}
.shell-header {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 24px;
  background: #fff;
  border-bottom: 1px solid #ebeef5;
}
.header-left,
.header-right {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}
.back-btn {
  font-size: 14px;
}
.step-tag {
  flex-shrink: 0;
}
.step-label {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
}
.loading-text {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  color: #909399;
}
.shell-body {
  max-width: 1400px;
  margin: 0 auto;
  padding: 24px;
}
.page-title h1 {
  margin: 0;
  font-size: 20px;
  font-weight: 600;
  color: #303133;
}
.page-title p {
  margin: 4px 0 0;
  font-size: 13px;
  color: #909399;
}
.page-title {
  margin-bottom: 24px;
}
</style>

// apps/edu/components/shared/editor-shell.tsx
'use client'

import React from 'react'
import { X, ArrowLeft, ArrowRight, Save, Eye, Check, Send, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { TopNav } from '@/components/portal/top-nav'

export interface EditorShellProps {
  mode: 'fullscreen' | 'inline'

  backText: string
  onBack: () => void

  step?: number
  stepLabel?: string

  onSaveDraft?: () => void
  isSaving?: boolean
  saveText?: string
  saveDisabled?: boolean

  onPreview?: () => void

  onPrev?: () => void

  onNext?: () => void
  nextText?: string
  nextDisabled?: boolean

  onSubmit?: () => void
  submitText?: string
  submitDisabled?: boolean

  loadingText?: string

  headerTitle?: React.ReactNode

  title?: string
  subtitle?: string

  contentMaxWidth?: string

  children: React.ReactNode
}

export function EditorShell({
  mode,
  backText,
  onBack,
  step,
  stepLabel,
  onSaveDraft,
  isSaving = false,
  saveText,
  saveDisabled,
  onPreview,
  onPrev,
  onNext,
  nextText = '下一步',
  nextDisabled,
  onSubmit,
  submitText = '提交审批',
  submitDisabled,
  loadingText,
  headerTitle,
  title,
  subtitle,
  contentMaxWidth,
  children,
}: EditorShellProps) {
  const backIcon =
    mode === 'fullscreen' ? <X className="h-4 w-4 mr-2" /> : <ArrowLeft className="h-4 w-4 mr-1" />
  const stickyClass = mode === 'fullscreen' ? 'sticky top-14 z-10' : 'sticky top-0 z-30'
  const mxWidth = contentMaxWidth || (mode === 'fullscreen' ? 'max-w-full' : 'max-w-[1400px]')
  const defaultSaveText = isSaving ? '保存中...' : '保存草稿'

  const headerBar = (
    <div
      className={`bg-white border-b border-gray-100 ${stickyClass} ${mode === 'fullscreen' ? 'mt-14' : ''}`}
    >
      <div className={`${mxWidth} mx-auto px-6 py-4 flex items-center justify-between`}>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={onBack}>
            {backIcon}
            {backText}
          </Button>
          {headerTitle && <h1 className="text-lg font-semibold text-gray-900">{headerTitle}</h1>}
          {step !== undefined && (
            <>
              <div className="h-5 w-px bg-gray-200" />
              <div className="flex items-center gap-2">
                <Badge className="bg-primary text-primary-foreground">步骤 {step}</Badge>
                {stepLabel && (
                  <span className="text-sm font-medium text-gray-800">{stepLabel}</span>
                )}
              </div>
            </>
          )}
        </div>
        <div className="flex items-center gap-3">
          {loadingText && (
            <span className="text-xs text-muted-foreground flex items-center">
              <Loader2 className="mr-1 h-3 w-3 animate-spin" />
              {loadingText}
            </span>
          )}
          {onSaveDraft && (
            <Button
              variant="outline"
              size="sm"
              onClick={onSaveDraft}
              disabled={isSaving || saveDisabled}
            >
              <Save className="mr-2 h-4 w-4" />
              {saveText || defaultSaveText}
            </Button>
          )}
          {onPreview && (
            <Button variant="outline" size="sm" onClick={onPreview}>
              <Eye className="mr-2 h-4 w-4" />
              预览
            </Button>
          )}
          {onPrev && (
            <Button variant="outline" size="sm" onClick={onPrev}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              上一步
            </Button>
          )}
          {onNext && (
            <Button size="sm" onClick={onNext} disabled={nextDisabled}>
              {nextText}
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          )}
          {!onNext && onSubmit && (
            <Button size="sm" onClick={onSubmit} disabled={submitDisabled}>
              {mode === 'inline' && <Send className="mr-2 h-4 w-4" />}
              {mode === 'fullscreen' && <Check className="mr-2 h-4 w-4" />}
              {submitText}
            </Button>
          )}
        </div>
      </div>
    </div>
  )

  const pageTitle = title ? (
    <div className="mb-8">
      <h1 className="text-2xl font-semibold text-gray-800">{title}</h1>
      {subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}
    </div>
  ) : null

  if (mode === 'fullscreen') {
    return (
      <div className="fixed inset-0 bg-background z-50 overflow-auto">
        <TopNav />
        {headerBar}
        <div className={`${mxWidth} mx-auto px-6 py-8`}>
          {pageTitle}
          {children}
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#f5f7fa]">
      {headerBar}
      <div className={`${mxWidth} mx-auto px-6 py-6`}>
        {pageTitle}
        {children}
      </div>
    </div>
  )
}
