// frontend/portal-vue/src/views/portal/workspace/ScheduleGrid.vue
<!--
  学期周课表网格（7 列星期 × 节次行），学生/教师工作台「我的课表」共用。
  对齐原 React 版 shared/schedule-grid.tsx
  （节次行优先取节次配置并按 sortOrder 排序，缺省时从课表条目的 periods 归并；
   按周次过滤支持单/双周；场景课带「场景」徽标；提供 href 时整卡可跳转）。
-->
<template>
  <div class="schedule-grid-wrap">
    <div v-if="loading" class="grid-loading">加载中...</div>
    <el-empty v-else-if="!hasData && !alwaysShow" :description="emptyText" />
    <table v-else class="schedule-table">
      <thead>
        <tr>
          <th class="period-col">节次</th>
          <th v-for="d in DAY_LABELS" :key="d">{{ d }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in displayRows" :key="row.key">
          <td class="period-cell">
            <div class="period-label">{{ row.label }}</div>
            <div v-if="row.time" class="period-time">{{ row.time }}</div>
          </td>
          <td v-for="(_, dayIdx) in DAY_LABELS" :key="dayIdx" class="slot-cell">
            <div class="slot-inner">
              <component
                v-for="entry in cellEntries(dayIdx + 1, row.key)"
                :is="entryHref(entry) ? 'router-link' : 'div'"
                :key="entry.id"
                :to="entryHref(entry)"
                class="entry-link"
              >
                <div class="entry-card" :class="entry.type === 'scene' ? 'is-scene' : 'is-course'">
                  <div class="entry-head">
                    <span class="entry-name">{{ entry.courseName }}</span>
                    <span v-if="entry.type === 'scene'" class="entry-badge">场景</span>
                  </div>
                  <div v-if="entry.teacherName" class="entry-meta">
                    <el-icon><User /></el-icon>{{ entry.teacherName }}
                  </div>
                  <div v-if="entry.venueName" class="entry-meta">
                    <el-icon><Location /></el-icon>{{ entry.venueName }}
                  </div>
                  <div class="entry-meta">
                    第{{ entry.startWeek }}-{{ entry.endWeek }}周{{ weekPatternSuffix(entry.weekPattern) }}
                  </div>
                </div>
              </component>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Location, User } from '@element-plus/icons-vue';
import type { PeriodSlot, ScheduleEntry } from '@/types/affairs';

const props = withDefaults(
  defineProps<{
    entries: ScheduleEntry[];
    periodSlots?: PeriodSlot[];
    week?: number;
    loading?: boolean;
    emptyText?: string;
    alwaysShow?: boolean;
    getEntryHref?: (entry: ScheduleEntry) => string | undefined;
  }>(),
  {
    periodSlots: () => [],
    loading: false,
    emptyText: '暂无课表数据',
    alwaysShow: false
  }
);

const DAY_LABELS = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];

interface GridRow {
  key: string;
  label: string;
  time?: string;
}

/** 按周次过滤：startWeek <= week <= endWeek 且周次模式匹配 */
const visibleEntries = computed(() => {
  const entries = props.entries || [];
  const week = props.week;
  if (!week) return entries;
  return entries.filter((e) => {
    if (e.startWeek > week || e.endWeek < week) return false;
    if (e.weekPattern === 'odd') return week % 2 === 1;
    if (e.weekPattern === 'even') return week % 2 === 0;
    return true;
  });
});

const rows = computed<GridRow[]>(() => {
  if (props.periodSlots && props.periodSlots.length > 0) {
    return [...props.periodSlots]
      .sort((a, b) => a.sortOrder - b.sortOrder)
      .map((s) => ({
        key: s.name,
        label: s.name,
        time: s.startTime
          ? `${s.startTime.slice(0, 5)}${s.endTime ? `-${s.endTime.slice(0, 5)}` : ''}`
          : undefined
      }));
  }
  const names = new Set<string>();
  for (const e of visibleEntries.value) {
    for (const p of e.periods || []) names.add(p);
  }
  return Array.from(names)
    .sort((a, b) => a.localeCompare(b, 'zh-CN', { numeric: true }))
    .map((name) => ({ key: name, label: name }));
});

const hasData = computed(() => rows.value.length > 0);

const displayRows = computed<GridRow[]>(() => {
  if (hasData.value) return rows.value;
  if (props.periodSlots && props.periodSlots.length > 0) {
    return [...props.periodSlots]
      .sort((a, b) => a.sortOrder - b.sortOrder)
      .map((s) => ({ key: s.name, label: s.name }));
  }
  return [{ key: '__empty', label: '暂无节次' }];
});

const cellMap = computed(() => {
  const map = new Map<string, ScheduleEntry[]>();
  for (const e of visibleEntries.value) {
    for (const p of e.periods || []) {
      const key = `${e.dayOfWeek}:${p}`;
      const list = map.get(key) || [];
      list.push(e);
      map.set(key, list);
    }
  }
  return map;
});

function cellEntries(dayOfWeek: number, periodKey: string): ScheduleEntry[] {
  return cellMap.value.get(`${dayOfWeek}:${periodKey}`) || [];
}

function entryHref(entry: ScheduleEntry): string | undefined {
  return props.getEntryHref?.(entry);
}

function weekPatternSuffix(pattern: string): string {
  if (pattern === 'odd') return '（单周）';
  if (pattern === 'even') return '（双周）';
  return '';
}
</script>

<style scoped>
.schedule-grid-wrap {
  overflow-x: auto;
}
.grid-loading {
  padding: 64px 0;
  text-align: center;
  font-size: 14px;
  color: #9ca3af;
}
.schedule-table {
  min-width: 840px;
  width: 100%;
  border-collapse: collapse;
}
.schedule-table th {
  border: 1px solid #ebeef5;
  background: rgba(245, 247, 250, 0.6);
  padding: 8px 4px;
  font-size: 12px;
  font-weight: 500;
  color: #909399;
  width: 130px;
}
.schedule-table th.period-col {
  width: 80px;
}
.schedule-table td {
  border: 1px solid #ebeef5;
  padding: 4px;
  vertical-align: top;
}
.period-cell {
  background: rgba(245, 247, 250, 0.4);
  padding: 6px 8px !important;
}
.period-label {
  font-size: 12px;
  font-weight: 500;
  color: #374151;
}
.period-time {
  font-size: 10px;
  color: #909399;
}
.slot-inner {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-height: 32px;
}
.entry-link {
  display: block;
  text-decoration: none;
  color: inherit;
}
.entry-card {
  max-width: 130px;
  border: 1px solid;
  border-radius: 6px;
  padding: 4px;
  font-size: 11px;
  line-height: 1.3;
  transition: box-shadow 0.2s;
}
.entry-card.is-course {
  border-color: #bfdbfe;
  background: #eff6ff;
}
.entry-card.is-scene {
  border-color: #fed7aa;
  background: #fff7ed;
}
.entry-link:hover .entry-card {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}
.entry-head {
  display: flex;
  align-items: center;
  gap: 4px;
}
.entry-name {
  font-weight: 500;
  color: #111827;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.entry-badge {
  flex-shrink: 0;
  border-radius: 999px;
  background: #ffedd5;
  color: #ea580c;
  padding: 0 6px;
  font-size: 10px;
  font-weight: 500;
}
.entry-meta {
  display: flex;
  align-items: center;
  gap: 2px;
  margin-top: 2px;
  color: #909399;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// apps/edu/components/shared/schedule-grid.tsx
"use client"

import { useMemo } from "react"
import Link from "next/link"
import { MapPin, User } from "lucide-react"
import { cn } from "@/lib/utils"
import type { PeriodSlot, ScheduleEntry } from "@/lib/types"

const DAY_LABELS = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]

const WEEK_PATTERN_SUFFIX: Record<string, string> = {
  all: "",
  odd: "（单周）",
  even: "（双周）",
}

/** 按周次过滤：startWeek <= week <= endWeek 且周次模式匹配 */
export function filterEntriesByWeek(entries: ScheduleEntry[], week?: number): ScheduleEntry[] {
  if (!week) return entries
  return entries.filter((e) => {
    if (e.startWeek > week || e.endWeek < week) return false
    if (e.weekPattern === "odd") return week % 2 === 1
    if (e.weekPattern === "even") return week % 2 === 0
    return true
  })
}

interface ScheduleGridProps {
  entries: ScheduleEntry[]
  periodSlots?: PeriodSlot[]
  week?: number
  loading?: boolean
  emptyText?: string
  onEntryClick?: (entry: ScheduleEntry) => void
  getEntryHref?: (entry: ScheduleEntry) => string | undefined
  onCellClick?: (dayOfWeek: number, periodSlotKey: string) => void
  /** 即使无条目也渲染空表格（排课页始终显示网格） */
  alwaysShow?: boolean
}

interface GridRow {
  key: string
  label: string
  time?: string
}

/** 周课表网格（7 列星期 × 节次行），排课页与学生/教师工作台共用 */
export function ScheduleGrid({
  entries,
  periodSlots,
  week,
  loading,
  emptyText = "暂无课表数据",
  onEntryClick,
  getEntryHref,
  onCellClick,
  alwaysShow,
}: ScheduleGridProps) {
  const visibleEntries = useMemo(() => filterEntriesByWeek(entries, week), [entries, week])

  const rows = useMemo<GridRow[]>(() => {
    if (periodSlots && periodSlots.length > 0) {
      return [...periodSlots]
        .sort((a, b) => a.sortOrder - b.sortOrder)
        .map((s) => ({
          key: s.name,
          label: s.name,
          time: s.startTime ? `${s.startTime.slice(0, 5)}${s.endTime ? `-${s.endTime.slice(0, 5)}` : ""}` : undefined,
        }))
    }
    const names = new Set<string>()
    for (const e of visibleEntries) {
      for (const p of e.periods || []) names.add(p)
    }
    return Array.from(names)
      .sort((a, b) => a.localeCompare(b, "zh-CN", { numeric: true }))
      .map((name) => ({ key: name, label: name }))
  }, [periodSlots, visibleEntries])

  const cellMap = useMemo(() => {
    const map = new Map<string, ScheduleEntry[]>()
    for (const e of visibleEntries) {
      for (const p of e.periods || []) {
        const key = `${e.dayOfWeek}:${p}`
        const list = map.get(key) || []
        list.push(e)
        map.set(key, list)
      }
    }
    return map
  }, [visibleEntries])

  const renderCard = (entry: ScheduleEntry) => {
    const isScene = entry.type === "scene"
    const href = getEntryHref?.(entry)
    const clickable = !!href || !!onEntryClick
    const card = (
      <div
        className={cn(
          "w-full rounded-md border p-1.5 text-left text-xs leading-4",
          isScene ? "border-orange-200 bg-orange-50" : "border-blue-200 bg-blue-50",
          clickable && "cursor-pointer transition-shadow hover:shadow-md"
        )}
      >
        <div className="flex items-center gap-1">
          <span className="truncate font-medium text-gray-900">{entry.courseName}</span>
          {isScene && (
            <span className="shrink-0 rounded-full bg-orange-100 px-1.5 py-px text-[10px] font-medium text-orange-600">
              场景
            </span>
          )}
        </div>
        {entry.teacherName && (
          <div className="mt-0.5 flex items-center gap-0.5 text-muted-foreground">
            <User className="h-3 w-3 shrink-0" />
            <span className="truncate">{entry.teacherName}</span>
          </div>
        )}
        {entry.venueName && (
          <div className="flex items-center gap-0.5 text-muted-foreground">
            <MapPin className="h-3 w-3 shrink-0" />
            <span className="truncate">{entry.venueName}</span>
          </div>
        )}
        <div className="mt-0.5 text-muted-foreground">
          第{entry.startWeek}-{entry.endWeek}周{WEEK_PATTERN_SUFFIX[entry.weekPattern] || ""}
        </div>
      </div>
    )
    if (href) {
      return (
        <Link key={entry.id} href={href} className="block">
          {card}
        </Link>
      )
    }
    if (onEntryClick) {
      return (
        <button key={entry.id} type="button" className="block w-full" onClick={() => onEntryClick(entry)}>
          {card}
        </button>
      )
    }
    return <div key={entry.id}>{card}</div>
  }

  if (loading) {
    return <div className="py-16 text-center text-sm text-muted-foreground">加载中...</div>
  }

  const hasData = rows.length > 0
  if (!hasData && !alwaysShow) {
    return <div className="py-16 text-center text-sm text-muted-foreground">{emptyText}</div>
  }

  // 始终渲染时用节次数据兜底，fallback 为空数组
  const displayRows = hasData ? rows : (periodSlots && periodSlots.length > 0
    ? [...periodSlots].sort((a, b) => a.sortOrder - b.sortOrder).map((s) => ({ key: s.name, label: s.name } as GridRow))
    : [{ key: "__empty", label: "暂无节次" } as GridRow])

  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[840px] border-collapse">
        <thead>
          <tr>
            <th className="w-[110px] border bg-muted/40 px-2 py-2 text-xs font-medium text-muted-foreground">节次</th>
            {DAY_LABELS.map((d) => (
              <th key={d} className="border bg-muted/40 px-2 py-2 text-xs font-medium text-muted-foreground">
                {d}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {displayRows.map((row) => (
            <tr key={row.key}>
              <td className="border bg-muted/20 px-2 py-1.5 align-top">
                <div className="text-xs font-medium text-gray-700">{row.label}</div>
                {row.time && <div className="text-[10px] text-muted-foreground">{row.time}</div>}
              </td>
              {DAY_LABELS.map((_, dayIdx) => {
                const dayEntries = cellMap.get(`${dayIdx + 1}:${row.key}`) || []
                return (
                  <td key={dayIdx} className={cn("border px-1 py-1 align-top", onCellClick && "cursor-pointer hover:bg-blue-50/40 transition-colors")}
                    onClick={() => { if (onCellClick && dayEntries.length === 0) onCellClick(dayIdx + 1, row.key) }}>
                    <div className="space-y-1 min-h-[2rem]">{dayEntries.map(renderCard)}</div>
                  </td>
                )
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
