// plus-ui/src-portal/views/library/_components/TagFilterBar.vue
<template>
  <div class="tag-filter-bar">
    <span class="filter-label">标签筛选：</span>
    <template v-if="tags.length">
      <button
        v-for="tag in tags"
        :key="tag.id"
        type="button"
        class="filter-chip"
        :style="chipStyle(tag)"
        @click="toggle(tag.id)"
      >
        <span class="dot" :style="{ backgroundColor: isSelected(tag.id) ? '#fff' : tag.color }" />
        <span>{{ tag.name }}</span>
        <span v-if="isSelected(tag.id)" class="close">✕</span>
      </button>
      <button v-if="modelValue.length" type="button" class="clear-btn" @click="emit('update:modelValue', [])">
        清除筛选
      </button>
    </template>
    <span v-else-if="!loading" class="empty">暂无标签，请先在「标签管理」中创建后再进行标签筛选</span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useTags } from './useTags';
import type { TagItem } from '@/types/library';

const props = defineProps<{ modelValue: string[] }>();
const emit = defineEmits<{ (e: 'update:modelValue', v: string[]): void }>();

const { tags, loading } = useTags();

const selected = computed(() => new Set(props.modelValue));

function isSelected(id: string): boolean {
  return selected.value.has(id);
}

function toggle(id: string): void {
  const next = new Set(props.modelValue);
  if (next.has(id)) next.delete(id);
  else next.add(id);
  emit('update:modelValue', Array.from(next));
}

function chipStyle(tag: TagItem): Record<string, string> {
  return isSelected(tag.id)
    ? {
        background: tag.color,
        color: '#fff',
        borderColor: tag.color,
        boxShadow: `0 2px 8px ${tag.color}30`
      }
    : {
        background: '#f8fafc',
        color: '#64748b',
        borderColor: '#e2e8f0'
      };
}
</script>

<style scoped>
.tag-filter-bar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
  padding: 12px;
  margin-bottom: 12px;
  border: 1px solid #f1f5f9;
  border-radius: 12px;
  background: #fff;
}
.filter-label {
  font-size: 13px;
  color: #94a3b8;
  margin-right: 4px;
  flex-shrink: 0;
}
.filter-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 12px;
  border: 1px solid;
  border-radius: 9999px;
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}
.filter-chip .dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
}
.filter-chip .close {
  font-size: 11px;
  margin-left: 2px;
}
.clear-btn {
  margin-left: auto;
  padding: 5px 12px;
  border: 1px solid #fecaca;
  border-radius: 9999px;
  background: #fef2f2;
  color: #f87171;
  font-size: 12px;
  cursor: pointer;
}
.empty {
  font-size: 13px;
  color: #94a3b8;
}
</style>

// apps/edu/components/shared/tag-filter-bar.tsx
'use client'

import { X } from 'lucide-react'
import { useTags } from './use-tags'

interface TagFilterBarProps {
  value: string[]
  onChange: (tagIds: string[]) => void
  className?: string
}

/**
 * 列表顶部标签筛选栏：标签云多选（OR 语义，命中任一标签即显示）。
 * 与搜索条件叠加生效；无标签数据时展示引导文案。
 */
export function TagFilterBar({ value, onChange, className }: TagFilterBarProps) {
  const { tags, loading } = useTags()
  const selected = new Set(value)

  const toggle = (id: string) => {
    const next = new Set(value)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    onChange(Array.from(next))
  }

  if (loading) return null
  if (tags.length === 0) {
    return (
      <div className={`bg-white rounded-xl p-3 border border-slate-100 shadow-sm ${className ?? ''}`}>
        <span className="text-sm text-slate-400">
          暂无标签，请先在「标签管理」中创建后再进行标签筛选
        </span>
      </div>
    )
  }

  return (
    <div
      className={`bg-white rounded-xl p-3 flex gap-2 flex-wrap items-center border border-slate-100 shadow-sm ${className ?? ''}`}
    >
      <span className="text-sm text-slate-400 mr-1 shrink-0">标签筛选：</span>
      {tags.map((tag) => {
        const active = selected.has(tag.id)
        return (
          <button
            key={tag.id}
            onClick={() => toggle(tag.id)}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all cursor-pointer border-none"
            style={{
              background: active ? tag.color : '#f8fafc',
              color: active ? '#fff' : '#64748b',
              border: `1px solid ${active ? tag.color : '#e2e8f0'}`,
              boxShadow: active ? `0 2px 8px ${tag.color}30` : 'none',
            }}
          >
            <span
              className="w-2 h-2 rounded-full"
              style={{ backgroundColor: active ? '#fff' : tag.color }}
            />
            {tag.name}
            {active && <X className="size-3 ml-0.5" />}
          </button>
        )
      })}
      {value.length > 0 && (
        <button
          onClick={() => onChange([])}
          className="ml-auto px-3 py-1.5 text-xs text-red-400 hover:text-red-600 font-medium border border-red-200 rounded-xl bg-red-50 hover:bg-red-100 transition-colors"
        >
          清除筛选
        </button>
      )}
    </div>
  )
}
