// apps/edu/components/evaluation/manual-question-dialog.tsx
'use client'

import { useState, useMemo, useRef, useEffect } from 'react'
import { Search, Plus, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Checkbox } from '@/components/ui/checkbox'
import { useData } from '@/components/providers/data-provider'
import type { Question, QuestionType, EvalKnowledgePoint } from '@/lib/types'
import { QUESTION_TYPES, QUESTION_TYPE_LABELS, DIFFICULTY_LABELS, QUESTION_TYPE_BADGE_CLASSES } from '@/lib/types'
import { knowledgeApi } from '@/lib/api'
import { reportError } from '@/lib/error-handling'
import { cn } from '@/lib/utils'
import { useT } from '@/lib/i18n/locale-provider'

const TYPE_COLORS = QUESTION_TYPE_BADGE_CLASSES

interface ManualQuestionDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  selectedQuestionIds: string[]
  onAddQuestions: (questions: Question[]) => void
}

export function ManualQuestionDialog({
  open,
  onOpenChange,
  selectedQuestionIds,
  onAddQuestions,
}: ManualQuestionDialogProps) {
  const { questionBanks, getQuestionsByBank, loadBankQuestions } = useData()
  const t = useT()

  const scrollRef = useRef<HTMLDivElement>(null)
  const [selectedBankId, setSelectedBankId] = useState<string>('')
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState<QuestionType | 'all'>('all')
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [knowledgePoints, setKnowledgePoints] = useState<EvalKnowledgePoint[]>([])
  const [loadingQuestions, setLoadingQuestions] = useState(false)

  const publishedBanks = useMemo(() => {
    return questionBanks.filter((bank) => bank.status === 'published')
  }, [questionBanks])

  useEffect(() => {
    ;(async () => {
      if (open && publishedBanks.length > 0 && !selectedBankId) {
        const firstBankId = publishedBanks[0].id
        setSelectedBankId(firstBankId)
      }
    })()
  }, [open, publishedBanks, selectedBankId])

  useEffect(() => {
    ;(async () => {
      if (selectedBankId) {
        setLoadingQuestions(true)
        try {
          await loadBankQuestions?.(selectedBankId)
        } finally {
          setLoadingQuestions(false)
        }
      }
    })()
  }, [selectedBankId, loadBankQuestions])

  useEffect(() => {
    if (!open) return
    let cancelled = false
    knowledgeApi
      .list({ limit: 10000 })
      .then((res) => {
        if (!cancelled) setKnowledgePoints(res.items.map((kp) => ({ id: kp.id, name: kp.name })))
      })
      .catch((err) => reportError(err, '加载知识点列表'))
    return () => {
      cancelled = true
    }
  }, [open])

  const selectedBank = useMemo(() => {
    return questionBanks.find((b) => b.id === selectedBankId)
  }, [questionBanks, selectedBankId])

  const questions = useMemo(() => {
    if (!selectedBankId) return []
    return getQuestionsByBank(selectedBankId)
  }, [selectedBankId, getQuestionsByBank])

  const filteredQuestions = useMemo(() => {
    return questions.filter((q) => {
      const matchSearch = q.content.toLowerCase().includes(search.toLowerCase())
      const matchType = typeFilter === 'all' || q.type === typeFilter
      const notAlreadyAdded = !selectedQuestionIds.includes(q.id)
      return matchSearch && matchType && notAlreadyAdded
    })
  }, [questions, search, typeFilter, selectedQuestionIds])

  const handleToggle = (questionId: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      if (next.has(questionId)) {
        next.delete(questionId)
      } else {
        next.add(questionId)
      }
      return next
    })
  }

  const handleAddSelected = () => {
    const questionsToAdd = questions.filter((q) => selectedIds.has(q.id))
    onAddQuestions(questionsToAdd)
    setSelectedIds(new Set())
    onOpenChange(false)
  }

  const handleSelectAll = () => {
    if (selectedIds.size === filteredQuestions.length) {
      setSelectedIds(new Set())
    } else {
      setSelectedIds(new Set(filteredQuestions.map((q) => q.id)))
    }
  }

  const handleClose = () => {
    setSelectedIds(new Set())
    setSearch('')
    setTypeFilter('all')
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent size="xl" className="flex h-[85vh] flex-col overflow-hidden p-0">
        <DialogHeader className="shrink-0 border-b px-6 py-4">
          <DialogTitle>{t('手动抽题')}</DialogTitle>
          <DialogDescription>{t('从已发布的题库中选择题目添加到试卷')}</DialogDescription>
        </DialogHeader>

        <div className="shrink-0 border-b px-6 py-3">
          <div className="flex items-center gap-3">
            <Select
              value={selectedBankId}
              onValueChange={(v) => {
                setSelectedBankId(v)
                setSelectedIds(new Set())
              }}
            >
              <SelectTrigger className="w-64">
                <SelectValue placeholder={t('选择题库')} />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  {publishedBanks.length === 0 ? (
                    <SelectItem value="none" disabled>
                      {t('暂无已发布的题库')}
                    </SelectItem>
                  ) : (
                    publishedBanks.map((bank) => (
                      <SelectItem key={bank.id} value={bank.id}>
                        {t('{name} ({n} 题)', { name: bank.name, n: bank.questionCount })}
                      </SelectItem>
                    ))
                  )}
                </SelectGroup>
              </SelectContent>
            </Select>

            {selectedBankId && (
              <>
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder={t('搜索题目内容...')}
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="pl-9"
                  />
                </div>
                <Select
                  value={typeFilter}
                  onValueChange={(v) => setTypeFilter(v as QuestionType | 'all')}
                >
                  <SelectTrigger className="w-32">
                    <SelectValue placeholder={t('全部类型')} />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectItem value="all">{t('全部类型')}</SelectItem>
                      {QUESTION_TYPES.map((type) => (
                        <SelectItem key={type} value={type}>
                          {t(QUESTION_TYPE_LABELS[type])}
                        </SelectItem>
                      ))}
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </>
            )}
          </div>
        </div>

        {selectedBankId ? (
          <>
            <div className="shrink-0 flex items-center justify-between border-b px-6 py-2">
              <div className="flex items-center gap-2">
                <Checkbox
                  checked={
                    filteredQuestions.length > 0 && selectedIds.size === filteredQuestions.length
                  }
                  onCheckedChange={handleSelectAll}
                />
                <span className="text-sm text-muted-foreground">
                  {t('已选')}{' '}
                  <span className="font-medium text-foreground">{selectedIds.size}</span> /{' '}
                  {filteredQuestions.length} {t('题')}
                  {selectedBank && <span className="mx-1">·</span>}
                  {selectedBank && <span>{selectedBank.name}</span>}
                </span>
              </div>
              <Button size="sm" disabled={selectedIds.size === 0} onClick={handleAddSelected}>
                <Plus className="mr-1 size-4" />
                {t('添加选中题目 ({n})', { n: selectedIds.size })}
              </Button>
            </div>
            <ScrollArea className="flex-1">
              <div ref={scrollRef} className="p-4 space-y-2">
                {filteredQuestions.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-16 text-center">
                    {loadingQuestions ? (
                      <>
                        <div className="size-8 mb-3 animate-spin rounded-full border-2 border-slate-300 border-t-primary" />
                        <p className="text-sm text-muted-foreground">{t('加载题目中...')}</p>
                      </>
                    ) : (
                      <>
                        <Search className="size-10 text-muted-foreground/30 mb-3" />
                        <p className="text-sm text-muted-foreground">
                          {questions.length === 0 ? t('该题库暂无题目') : t('没有找到匹配的题目')}
                        </p>
                      </>
                    )}
                  </div>
                ) : (
                  filteredQuestions.map((question) => {
                    const kpNames = (question.knowledgePoints || [])
                      .map((id) => knowledgePoints.find((k) => k.id === id)?.name)
                      .filter(Boolean) as string[]
                    const isSelected = selectedIds.has(question.id)
                    return (
                      <div
                        key={question.id}
                        className={cn(
                          'flex items-start gap-3 rounded-lg border p-3.5 transition-all cursor-pointer',
                          isSelected
                            ? 'border-primary/60 bg-primary/5 shadow-sm'
                            : 'hover:bg-muted/50 hover:border-slate-300',
                        )}
                        onClick={() => handleToggle(question.id)}
                      >
                        <Checkbox
                          checked={isSelected}
                          onCheckedChange={() => handleToggle(question.id)}
                          onClick={(e) => e.stopPropagation()}
                          className="mt-0.5"
                        />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm line-clamp-2 font-medium">{question.content}</p>
                          <div className="flex items-center gap-1.5 mt-1.5 flex-wrap">
                            <Badge
                              className={`text-xs text-white hover:opacity-90 ${TYPE_COLORS[question.type]}`}
                            >
                              {t(QUESTION_TYPE_LABELS[question.type])}
                            </Badge>
                            {question.difficulty && (
                              <Badge variant="outline" className="text-xs">
                                {t(DIFFICULTY_LABELS[question.difficulty])}
                              </Badge>
                            )}
                            <span className="text-xs text-muted-foreground">
                              {t('{n} 分', { n: question.score })}
                            </span>
                            {kpNames.length > 0 && (
                              <span className="text-xs text-muted-foreground truncate max-w-[200px]">
                                {kpNames.join('、')}
                              </span>
                            )}
                          </div>
                        </div>
                        {isSelected && <Check className="size-5 text-primary shrink-0 mt-0.5" />}
                      </div>
                    )
                  })
                )}
              </div>
            </ScrollArea>
          </>
        ) : (
          <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">
            {t('请先选择一个题库')}
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

// frontend/portal-vue/src/views/evaluation/components/manual-question-dialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    title="手动抽题"
    width="820px"
    top="6vh"
    append-to-body
    destroy-on-close
    @update:model-value="handleClose"
  >
    <div class="md-toolbar">
      <el-select v-model="selectedBankId" placeholder="选择题库" style="width: 260px" @change="onBankChange">
        <el-option v-for="b in publishedBanks" :key="b.id" :label="bankLabel(b)" :value="b.id" />
      </el-select>
      <template v-if="selectedBankId">
        <el-input v-model="search" placeholder="搜索题目内容..." clearable style="flex: 1" />
        <el-select v-model="typeFilter" style="width: 130px">
          <el-option label="全部类型" value="all" />
          <el-option v-for="t in QUESTION_TYPES" :key="t" :label="QUESTION_TYPE_LABELS[t]" :value="t" />
        </el-select>
      </template>
    </div>

    <div v-if="selectedBankId" class="md-head">
      <el-checkbox
        :model-value="filteredQuestions.length > 0 && selectedIds.length === filteredQuestions.length"
        @change="(v: boolean | string | number) => handleSelectAll(!!v)"
      >
        已选 {{ selectedIds.length }} / {{ filteredQuestions.length }} 题
      </el-checkbox>
      <el-button type="primary" size="small" :disabled="selectedIds.length === 0" @click="handleAddSelected">
        添加选中题目 ({{ selectedIds.length }})
      </el-button>
    </div>

    <div v-loading="loadingQuestions" class="md-body">
      <el-empty v-if="selectedBankId && !loadingQuestions && filteredQuestions.length === 0"
        :description="questions.length === 0 ? '该题库暂无题目' : '没有找到匹配的题目'" :image-size="60" />
      <div v-else-if="selectedBankId" class="md-list">
        <div
          v-for="q in filteredQuestions"
          :key="q.id"
          class="md-card"
          :class="{ selected: selectedIds.includes(q.id) }"
          @click="toggle(q.id)"
        >
          <el-checkbox :model-value="selectedIds.includes(q.id)" @click.stop @change="() => toggle(q.id)" />
          <div class="md-card-body">
            <p class="md-content">{{ q.content }}</p>
            <div class="md-meta">
              <el-tag size="small" :color="typeColor(q.type)" style="color: #fff; border: none">{{ typeLabel(q.type) }}</el-tag>
              <el-tag v-if="q.difficulty" size="small" type="info">{{ difficultyLabel(q.difficulty) }}</el-tag>
              <span class="dim">{{ q.score }} 分</span>
              <span v-if="kpNames(q).length > 0" class="dim md-kp">{{ kpNames(q).join('、') }}</span>
            </div>
          </div>
        </div>
      </div>
      <el-empty v-else description="请先选择一个题库" :image-size="60" />
    </div>
  </el-dialog>
</template>

<script setup lang="ts">
// 手动抽题弹窗：对齐 React frontend/edu/components/evaluation/manual-question-dialog.tsx
import { computed, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { questionApi, questionBankApi } from '@/api/evaluation';
import { knowledgeApi } from '@/api/lesson';
import { QUESTION_TYPES, QUESTION_TYPE_LABELS, QUESTION_TYPE_COLORS, DIFFICULTY_LABELS } from '@/types/evaluation';
import type { Question, QuestionBank, QuestionType } from '@/types/evaluation';

interface EvalKnowledgePoint {
  id: string;
  name: string;
}

const props = defineProps<{
  modelValue: boolean;
  selectedQuestionIds: string[];
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'add-questions', questions: Question[]): void;
}>();

const banks = ref<QuestionBank[]>([]);
const questions = ref<Question[]>([]);
const knowledgePoints = ref<EvalKnowledgePoint[]>([]);
const selectedBankId = ref('');
const search = ref('');
const typeFilter = ref<QuestionType | 'all'>('all');
const selectedIds = ref<string[]>([]);
const loadingQuestions = ref(false);

const publishedBanks = computed(() => banks.value.filter((b) => b.status === 'published'));

const filteredQuestions = computed(() =>
  questions.value.filter((q) => {
    const matchSearch = q.content.toLowerCase().includes(search.value.toLowerCase());
    const matchType = typeFilter.value === 'all' || q.type === typeFilter.value;
    const notAdded = !props.selectedQuestionIds.includes(q.id);
    return matchSearch && matchType && notAdded;
  })
);

async function loadBanks() {
  try {
    const res = await questionBankApi.list({ limit: 200 });
    banks.value = res.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载题库失败');
  }
}

async function loadKnowledgePoints() {
  try {
    const res = await knowledgeApi.list({ limit: 1000 });
    knowledgePoints.value = res.items.map((kp) => ({ id: kp.id, name: kp.name }));
  } catch {
    knowledgePoints.value = [];
  }
}

async function loadQuestions() {
  if (!selectedBankId.value) return;
  loadingQuestions.value = true;
  try {
    const res = await questionApi.list({ bankId: selectedBankId.value, limit: 500 });
    questions.value = res.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载题目失败');
  } finally {
    loadingQuestions.value = false;
  }
}

watch(
  () => props.modelValue,
  async (open) => {
    if (!open) return;
    await loadBanks();
    await loadKnowledgePoints();
    if (publishedBanks.value.length > 0 && !selectedBankId.value) {
      selectedBankId.value = publishedBanks.value[0].id;
      await loadQuestions();
    }
  }
);

function onBankChange() {
  selectedIds.value = [];
  void loadQuestions();
}

function bankLabel(b: QuestionBank): string {
  return `${b.name} (${b.questionCount ?? 0} 题)`;
}

function toggle(id: string) {
  selectedIds.value = selectedIds.value.includes(id)
    ? selectedIds.value.filter((x) => x !== id)
    : [...selectedIds.value, id];
}

function handleSelectAll(checked: boolean) {
  selectedIds.value = checked ? filteredQuestions.value.map((q) => q.id) : [];
}

function handleAddSelected() {
  const toAdd = questions.value.filter((q) => selectedIds.value.includes(q.id));
  emit('add-questions', toAdd);
  selectedIds.value = [];
  emit('update:modelValue', false);
}

function handleClose(v: boolean) {
  if (!v) {
    selectedIds.value = [];
    search.value = '';
    typeFilter.value = 'all';
  }
  emit('update:modelValue', v);
}

function typeLabel(t: QuestionType): string {
  return QUESTION_TYPE_LABELS[t] || t;
}
function typeColor(t: QuestionType): string {
  return QUESTION_TYPE_COLORS[t] || '#909399';
}
function difficultyLabel(d: string): string {
  return DIFFICULTY_LABELS[d] || d;
}
function kpNames(q: Question): string[] {
  return (q.knowledgePoints || [])
    .map((id) => knowledgePoints.value.find((k) => k.id === id)?.name)
    .filter(Boolean) as string[];
}
</script>

<style scoped>
.md-toolbar {
  display: flex;
  gap: 10px;
  margin-bottom: 12px;
}
.md-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}
.md-body {
  min-height: 240px;
  max-height: 54vh;
  overflow-y: auto;
}
.md-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.md-card {
  display: flex;
  gap: 10px;
  align-items: flex-start;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  padding: 10px 12px;
  cursor: pointer;
  transition: all 0.2s;
}
.md-card:hover {
  border-color: #a0cfff;
}
.md-card.selected {
  border-color: #409eff;
  background: #f0f7ff;
}
.md-card-body {
  flex: 1;
  min-width: 0;
}
.md-content {
  margin: 0 0 6px;
  font-size: 13px;
  color: #303133;
  line-height: 1.5;
}
.md-meta {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px;
}
.dim {
  font-size: 12px;
  color: #909399;
}
.md-kp {
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
