// apps/edu/components/evaluation/random-question-dialog.tsx
'use client'

import { useState, useMemo, useCallback, useEffect } from 'react'
import { Shuffle, AlertCircle, X, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'
import { MultiSelectSearch } from '@/components/ui/multi-select-search'
import { useData } from '@/components/providers/data-provider'
import { knowledgeApi, questionApi } from '@/lib/api'
import { fetchAllPages } from '@/lib/fetch-all'
import { reportError } from '@/lib/error-handling'
import type { Question, QuestionType, Difficulty, EvalKnowledgePoint } from '@/lib/types'
import { QUESTION_TYPE_LABELS, DIFFICULTY_LABELS, QUESTION_TYPE_BADGE_CLASSES } from '@/lib/types'
import { useT } from '@/lib/i18n/locale-provider'

interface RandomQuestionDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  selectedQuestionIds: string[]
  onAddQuestions: (questions: Question[]) => void
}

const questionTypes: QuestionType[] = [
  'single',
  'multiple',
  'judge',
  'fill',
  'short_answer',
  'essay',
]
const difficulties: Difficulty[] = ['easy', 'medium', 'hard']

const TYPE_COLORS = QUESTION_TYPE_BADGE_CLASSES

// ---- weight dimension helpers ----

type WeightDimension = 'bank' | 'type' | 'difficulty' | 'knowledge'

const DIM_LABEL: Record<WeightDimension, string> = {
  bank: '按题库比例',
  type: '按题型比例',
  difficulty: '按难度比例',
  knowledge: '按知识点比例',
}

export function RandomQuestionDialog({
  open,
  onOpenChange,
  selectedQuestionIds,
  onAddQuestions,
}: RandomQuestionDialogProps) {
  const { questionBanks } = useData()
  const t = useT()

  const publishedBanks = useMemo(
    () => questionBanks.filter((bank) => bank.status === 'published'),
    [questionBanks],
  )

  const [questions, setQuestions] = useState<Question[]>([])
  const [, setLoadingQuestions] = useState(false)

  useEffect(() => {
    if (!open) return
    let cancelled = false
    ;(async () => {
      setLoadingQuestions(true)
      try {
        // 分页合并全量拉取，避免超过后端 maxPageSize(200) 截断抽题池
        const items = await fetchAllPages((page, pageSize) =>
          questionApi.list({ limit: pageSize, offset: page * pageSize }),
        )
        if (cancelled) return
        setQuestions(
          items.map((q) => ({
            ...q,
            createdAt: (q.createdAt as unknown as string) || new Date().toISOString(),
          })),
        )
      } catch (err) {
        reportError(err, '加载题目列表')
      } finally {
        if (!cancelled) setLoadingQuestions(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [open])

  // ---- filters ----
  const [selectedBankIds, setSelectedBankIds] = useState<string[]>([])
  const [selectedTypes, setSelectedTypes] = useState<QuestionType[]>([])
  const [selectedDifficulties, setSelectedDifficulties] = useState<Difficulty[]>([])
  const [selectedKnowledgePoints, setSelectedKnowledgePoints] = useState<string[]>([])
  const [count, setCount] = useState(5)

  // ---- weight ----
  const [weightDimension, setWeightDimension] = useState<WeightDimension | ''>('')
  const [weightValues, setWeightValues] = useState<Record<string, number>>({})

  // ---- preview ----
  const [previewQuestions, setPreviewQuestions] = useState<Question[] | null>(null)

  // ---- knowledge points ----
  const [knowledgePoints, setKnowledgePoints] = useState<EvalKnowledgePoint[]>([])
  const [loadingKnowledgePoints, setLoadingKnowledgePoints] = useState(false)

  useEffect(() => {
    if (!open) return
    let cancelled = false
    ;(async () => {
      setLoadingKnowledgePoints(true)
      try {
        const res = await knowledgeApi.list({ limit: 1000 })
        if (cancelled) return
        setKnowledgePoints(res.items.map((kp) => ({ id: kp.id, name: kp.name })))
      } catch (_err) {
        // ignore
      } finally {
        if (!cancelled) setLoadingKnowledgePoints(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [open])

  // ---- computed pools ----

  const basePool = useMemo(() => {
    return questions.filter((q) => {
      if (selectedQuestionIds.includes(q.id)) return false
      const bank = questionBanks.find((b) => b.id === q.bankId)
      return bank?.status === 'published'
    })
  }, [questions, questionBanks, selectedQuestionIds])

  const filteredPool = useMemo(() => {
    let pool = [...basePool]
    if (selectedBankIds.length > 0) pool = pool.filter((q) => selectedBankIds.includes(q.bankId))
    if (selectedTypes.length > 0) pool = pool.filter((q) => selectedTypes.includes(q.type))
    if (selectedDifficulties.length > 0)
      pool = pool.filter((q) => q.difficulty && selectedDifficulties.includes(q.difficulty))
    if (selectedKnowledgePoints.length > 0)
      pool = pool.filter((q) =>
        q.knowledgePoints?.some((kp) => selectedKnowledgePoints.includes(kp)),
      )
    return pool
  }, [basePool, selectedBankIds, selectedTypes, selectedDifficulties, selectedKnowledgePoints])

  // ---- weight dimension keys ----
  const weightKeys = useMemo(() => {
    if (!weightDimension) return []
    switch (weightDimension) {
      case 'bank':
        return selectedBankIds.length > 0 ? selectedBankIds : publishedBanks.map((b) => b.id)
      case 'type':
        return questionTypes
      case 'difficulty':
        return difficulties
      case 'knowledge':
        return selectedKnowledgePoints.length > 0
          ? selectedKnowledgePoints
          : knowledgePoints.map((k) => k.id)
    }
  }, [weightDimension, selectedBankIds, selectedKnowledgePoints, publishedBanks, knowledgePoints])

  // 可用的权重维度（排除仅 1 个选项的维度）
  const availableDimensions = useMemo((): WeightDimension[] => {
    const dims: WeightDimension[] = []
    const bankKeys = selectedBankIds.length > 0 ? selectedBankIds : publishedBanks.map((b) => b.id)
    if (bankKeys.length >= 2) dims.push('bank')
    const typeKeys = selectedTypes.length > 0 ? selectedTypes : questionTypes
    if (typeKeys.length >= 2) dims.push('type')
    const diffKeys = selectedDifficulties.length > 0 ? selectedDifficulties : difficulties
    if (diffKeys.length >= 2) dims.push('difficulty')
    const kpKeys =
      selectedKnowledgePoints.length > 0
        ? selectedKnowledgePoints
        : knowledgePoints.map((k) => k.id)
    if (kpKeys.length >= 2) dims.push('knowledge')
    return dims
  }, [
    publishedBanks,
    selectedBankIds,
    selectedTypes,
    selectedDifficulties,
    selectedKnowledgePoints,
    knowledgePoints,
  ])

  // ---- largest-remainder proportional allocation ----
  const allocateProportions = useCallback(
    (total: number, entries: string[], weights: Record<string, number>): Record<string, number> => {
      const active = entries.filter((k) => (weights[k] ?? 0) > 0)
      const items = active.length > 0 ? active : entries
      const rawSum = items.reduce((s, k) => s + (weights[k] || 0), 0)
      const fracs = items.map((k) => ({
        key: k,
        frac: rawSum > 0 ? (total * (weights[k] || 0)) / rawSum : total / items.length,
      }))
      // floor first, track remainders
      const result: Record<string, number> = {}
      let allocated = 0
      const remainders: { key: string; rem: number }[] = []
      fracs.forEach(({ key, frac }) => {
        const floor = Math.floor(frac)
        result[key] = floor
        allocated += floor
        remainders.push({ key, rem: frac - floor })
      })
      // distribute leftover by largest remainder
      remainders.sort((a, b) => b.rem - a.rem)
      for (let i = 0; i < total - allocated; i++) {
        if (i < remainders.length) result[remainders[i].key]++
      }
      return result
    },
    [],
  )

  // ---- random selection ----
  const doRandomSelect = useCallback(() => {
    let allSelected: Question[] = []

    if (weightDimension && weightKeys.length > 0) {
      const allocation = allocateProportions(count, weightKeys, weightValues)
      const used = new Set<string>()

      Object.entries(allocation).forEach(([key, target]) => {
        if (target <= 0) return
        const candidates = filteredPool.filter((q) => {
          if (used.has(q.id)) return false
          if (weightDimension === 'bank') return q.bankId === key
          if (weightDimension === 'type') return q.type === key
          if (weightDimension === 'difficulty') return q.difficulty === key
          return q.knowledgePoints?.includes(key)
        })
        const take = Math.min(target, candidates.length)
        for (let i = 0; i < take; i++) {
          const idx = Math.floor(Math.random() * candidates.length)
          const q = candidates.splice(idx, 1)[0]
          allSelected.push(q)
          used.add(q.id)
        }
      })

      // fill remaining
      if (allSelected.length < count) {
        const remaining = filteredPool.filter((q) => !used.has(q.id))
        const need = count - allSelected.length
        for (let i = 0; i < Math.min(need, remaining.length); i++) {
          const idx = Math.floor(Math.random() * remaining.length)
          const q = remaining.splice(idx, 1)[0]
          allSelected.push(q)
          used.add(q.id)
        }
      }
    } else {
      const shuffled = [...filteredPool]
      for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
      }
      allSelected = shuffled.slice(0, Math.min(count, shuffled.length))
    }

    // Fisher-Yates shuffle
    for (let i = allSelected.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      ;[allSelected[i], allSelected[j]] = [allSelected[j], allSelected[i]]
    }
    setPreviewQuestions(allSelected)
  }, [filteredPool, weightDimension, weightKeys, weightValues, count, allocateProportions])

  // ---- actions ----
  const handleClose = () => {
    setSelectedBankIds([])
    setSelectedTypes([])
    setSelectedDifficulties([])
    setSelectedKnowledgePoints([])
    setCount(5)
    setWeightDimension('')
    setWeightValues({})
    setPreviewQuestions(null)
    onOpenChange(false)
  }

  const handleConfirm = () => {
    if (previewQuestions && previewQuestions.length > 0) {
      onAddQuestions(previewQuestions)
    }
    handleClose()
  }

  const toggleType = (type: QuestionType) => {
    setSelectedTypes((prev) =>
      prev.includes(type) ? prev.filter((t) => t !== type) : [...prev, type],
    )
  }

  const toggleDifficulty = (difficulty: Difficulty) => {
    setSelectedDifficulties((prev) =>
      prev.includes(difficulty) ? prev.filter((d) => d !== difficulty) : [...prev, difficulty],
    )
  }

  const toggleWeightDim = (dim: WeightDimension) => {
    if (weightDimension === dim) {
      setWeightDimension('')
      setWeightValues({})
    } else {
      setWeightDimension(dim)
      setWeightValues({})
    }
  }

  const removeFromPreview = (qid: string) => {
    setPreviewQuestions((prev) => (prev ? prev.filter((q) => q.id !== qid) : null))
  }

  const countSliderMax = Math.max(1, Math.min(50, filteredPool.length))

  // ---- render helpers ----
  const renderWeightSliderRow = (key: string, label: string) => {
    const raw = weightValues[key] ?? 0
    return (
      <div key={key} className="flex items-center gap-3">
        <span className="text-xs w-20 truncate shrink-0">{label}</span>
        <Slider
          value={[raw]}
          min={0}
          max={100}
          step={1}
          onValueChange={([v]) => setWeightValues((prev) => ({ ...prev, [key]: v }))}
          className="flex-1"
        />
        <Input
          type="number"
          min={0}
          max={100}
          value={raw || ''}
          placeholder="0"
          onChange={(e) =>
            setWeightValues((prev) => ({
              ...prev,
              [key]: Math.max(0, Math.min(100, parseInt(e.target.value) || 0)),
            }))
          }
          className="h-7 w-14 text-xs"
        />
      </div>
    )
  }

  const weightKeyLabel = (key: string): string => {
    if (weightDimension === 'bank') return publishedBanks.find((b) => b.id === key)?.name || key
    if (weightDimension === 'type') return QUESTION_TYPE_LABELS[key as QuestionType]
    if (weightDimension === 'difficulty') return DIFFICULTY_LABELS[key as Difficulty]
    return knowledgePoints.find((k) => k.id === key)?.name || key
  }

  // ---- render ----

  if (previewQuestions) {
    return (
      <Dialog open={open} onOpenChange={handleClose}>
        <DialogContent size="lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shuffle className="size-5" />
              {t('抽题预览')}
            </DialogTitle>
            <DialogDescription>
              {t('已抽取 {n} 道题目，可移除不需要的题目后确认加入', { n: previewQuestions.length })}
            </DialogDescription>
          </DialogHeader>
          <div className="max-h-[55vh] overflow-y-auto space-y-2">
            {previewQuestions.length === 0 ? (
              <div className="py-12 text-center text-sm text-muted-foreground">
                {t('未抽到符合条件的题目，请调整筛选条件后重试')}
              </div>
            ) : (
              previewQuestions.map((q, i) => {
                const bankName = questionBanks.find((b) => b.id === q.bankId)?.name
                const kpNames = (q.knowledgePoints || [])
                  .map((id) => knowledgePoints.find((k) => k.id === id)?.name)
                  .filter(Boolean) as string[]
                return (
                  <div key={q.id} className="flex items-center gap-3 rounded-lg border p-3">
                    <span className="text-xs text-muted-foreground w-5 shrink-0">{i + 1}.</span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm line-clamp-1">{q.content}</p>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge className={`text-xs text-white ${TYPE_COLORS[q.type]}`}>
                          {t(QUESTION_TYPE_LABELS[q.type])}
                        </Badge>
                        {q.difficulty && (
                          <Badge variant="outline" className="text-xs">
                            {t(DIFFICULTY_LABELS[q.difficulty])}
                          </Badge>
                        )}
                        {bankName && (
                          <span className="text-xs text-muted-foreground">{bankName}</span>
                        )}
                        {kpNames.length > 0 && (
                          <span className="text-xs text-muted-foreground truncate max-w-[200px]">
                            {kpNames.join('、')}
                          </span>
                        )}
                      </div>
                    </div>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="size-7 shrink-0"
                      onClick={() => removeFromPreview(q.id)}
                    >
                      <X className="size-4" />
                    </Button>
                  </div>
                )
              })
            )}
          </div>
          <DialogFooter className="flex-col gap-2 sm:flex-row">
            <div className="flex-1" />
            <div className="flex gap-2">
              <Button variant="outline" onClick={() => setPreviewQuestions(null)}>
                <RefreshCw className="mr-2 size-4" />
                {t('重新抽题')}
              </Button>
              <Button onClick={handleConfirm} disabled={previewQuestions.length === 0}>
                {t('确认加入试卷')}
              </Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    )
  }

  const filterSummary = [
    selectedBankIds.length > 0 && t('题库 {n} 个', { n: selectedBankIds.length }),
    selectedTypes.length > 0 && t('题型 {n} 种', { n: selectedTypes.length }),
    selectedDifficulties.length > 0 && t('难度 {n} 级', { n: selectedDifficulties.length }),
    selectedKnowledgePoints.length > 0 &&
      t('知识点 {n} 个', { n: selectedKnowledgePoints.length }),
  ]
    .filter(Boolean)
    .join('，')

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent size="lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Shuffle className="size-5" />
            {t('随机抽题')}
          </DialogTitle>
          <DialogDescription>
            {t('从已发布题库中随机抽取题目，可配置筛选条件与比例分配')}
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-4 max-h-[58vh] overflow-y-auto pr-1">
          {/* 题库 */}
          <div>
            <Label className="text-sm font-medium mb-2 block">{t('选择题库')}</Label>
            {publishedBanks.length === 0 ? (
              <p className="text-sm text-muted-foreground">{t('暂无已发布的题库')}</p>
            ) : (
              <MultiSelectSearch
                options={publishedBanks.map((b) => ({
                  label: b.name,
                  value: b.id,
                  subtitle: t('{n}题', { n: b.questionCount }),
                }))}
                selected={selectedBankIds}
                onChange={(ids) => {
                  setSelectedBankIds(ids)
                  setWeightDimension('')
                  setWeightValues({})
                }}
                placeholder={t('不选则从全部题库抽取')}
                searchPlaceholder={t('搜索题库名称...')}
              />
            )}
          </div>

          {/* 题型 */}
          <div>
            <Label className="text-sm font-medium mb-2 block">{t('题目类型')}</Label>
            <div className="flex flex-wrap gap-1.5">
              {questionTypes.map((type) => (
                <Badge
                  key={type}
                  variant={selectedTypes.includes(type) ? 'default' : 'outline'}
                  className="cursor-pointer select-none"
                  onClick={() => {
                    toggleType(type)
                    setWeightDimension('')
                    setWeightValues({})
                  }}
                >
                  {t(QUESTION_TYPE_LABELS[type])}
                </Badge>
              ))}
            </div>
          </div>

          {/* 难度 */}
          <div>
            <Label className="text-sm font-medium mb-2 block">{t('难度等级')}</Label>
            <div className="flex flex-wrap gap-1.5">
              {difficulties.map((d) => (
                <Badge
                  key={d}
                  variant={selectedDifficulties.includes(d) ? 'default' : 'outline'}
                  className="cursor-pointer select-none"
                  onClick={() => {
                    toggleDifficulty(d)
                    setWeightDimension('')
                    setWeightValues({})
                  }}
                >
                  {t(DIFFICULTY_LABELS[d])}
                </Badge>
              ))}
            </div>
          </div>

          {/* 知识点 (always expanded) */}
          <div>
            <Label className="text-sm font-medium mb-2 block">{t('知识点')}</Label>
            {loadingKnowledgePoints ? (
              <p className="text-sm text-muted-foreground py-1">{t('加载中...')}</p>
            ) : (
              <MultiSelectSearch
                options={knowledgePoints.map((kp) => ({ label: kp.name, value: kp.id }))}
                selected={selectedKnowledgePoints}
                onChange={(ids) => {
                  setSelectedKnowledgePoints(ids)
                  setWeightDimension('')
                  setWeightValues({})
                }}
                placeholder={t('不选则包含全部知识点')}
                searchPlaceholder={t('搜索知识点...')}
              />
            )}
          </div>

          {/* 按比例分配 */}
          {availableDimensions.length > 0 && (
            <div>
              <Label className="text-sm font-medium mb-2 block">{t('按比例分配')}</Label>
              <div className="flex flex-wrap gap-1.5 mb-2">
                {availableDimensions.map((dim) => (
                  <Badge
                    key={dim}
                    variant={weightDimension === dim ? 'default' : 'outline'}
                    className="cursor-pointer select-none"
                    onClick={() => toggleWeightDim(dim)}
                  >
                    {t(DIM_LABEL[dim])}
                  </Badge>
                ))}
              </div>
              {weightDimension && weightKeys.length > 0 && (
                <div className="rounded-lg border bg-muted/30 p-3 space-y-2 max-h-48 overflow-y-auto">
                  {weightKeys.map((key) => renderWeightSliderRow(key, t(weightKeyLabel(key))))}
                  <p className="text-xs text-muted-foreground pt-1">
                    {t('输入的数字按比例折算，无需凑满 100')}
                  </p>
                </div>
              )}
            </div>
          )}

          {/* 抽取数量 */}
          <div className="rounded-lg border p-4">
            <div className="flex items-center justify-between mb-2">
              <Label className="text-sm font-medium">{t('抽取数量')}</Label>
              <Input
                type="number"
                min={1}
                max={countSliderMax}
                value={count}
                onChange={(e) =>
                  setCount(Math.max(1, Math.min(countSliderMax, parseInt(e.target.value) || 1)))
                }
                className="h-7 w-16 text-xs text-center"
              />
            </div>
            <Slider
              value={[count]}
              min={1}
              max={countSliderMax}
              step={1}
              onValueChange={([v]) => setCount(v)}
            />
            <p className="text-xs text-muted-foreground mt-2">
              {filterSummary
                ? t('筛选条件：{summary}', { summary: filterSummary })
                : t('未设置筛选，从全部题目中抽取')}
              {t('｜可用题目池：{n} 道', { n: filteredPool.length })}
              {count > filteredPool.length && (
                <span className="text-amber-600 ml-1">{t('（超过可用数量，将全部抽取）')}</span>
              )}
            </p>
          </div>
        </div>

        <DialogFooter className="flex-col gap-2 sm:flex-row">
          <div className="flex-1 text-sm text-muted-foreground">
            {filteredPool.length === 0 ? (
              <span className="text-destructive flex items-center gap-1">
                <AlertCircle className="size-4" />
                {t('当前条件下没有可用题目')}
              </span>
            ) : (
              <span>{t('实际抽取 {n} 道题目', { n: Math.min(count, filteredPool.length) })}</span>
            )}
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={handleClose}>
              {t('取消')}
            </Button>
            <Button onClick={doRandomSelect} disabled={filteredPool.length === 0}>
              <Shuffle className="mr-2 size-4" />
              {t('随机抽题')}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/portal-vue/src/views/evaluation/components/random-question-dialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    :title="previewQuestions ? '抽题预览' : '随机抽题'"
    width="760px"
    top="6vh"
    append-to-body
    destroy-on-close
    @update:model-value="handleClose"
  >
    <!-- 预览视图 -->
    <template v-if="previewQuestions">
      <p class="rd-hint">已抽取 {{ previewQuestions.length }} 道题目，可移除不需要的题目后确认加入</p>
      <div class="rd-preview">
        <el-empty v-if="previewQuestions.length === 0" description="未抽到符合条件的题目，请调整筛选条件后重试" :image-size="60" />
        <div v-for="(q, i) in previewQuestions" :key="q.id" class="rd-preview-card">
          <span class="rd-idx">{{ i + 1 }}.</span>
          <div class="rd-preview-body">
            <p class="rd-preview-content">{{ q.content }}</p>
            <div class="rd-preview-meta">
              <el-tag size="small" :color="typeColor(q.type)" style="color: #fff; border: none">{{ typeLabel(q.type) }}</el-tag>
              <el-tag v-if="q.difficulty" size="small" type="info">{{ difficultyLabel(q.difficulty) }}</el-tag>
              <span v-if="bankName(q.bankId)" class="dim">{{ bankName(q.bankId) }}</span>
            </div>
          </div>
          <el-button link type="danger" @click="removeFromPreview(q.id)">移除</el-button>
        </div>
      </div>
    </template>

    <!-- 筛选视图 -->
    <template v-else>
      <div class="rd-body">
        <div class="rd-section">
          <div class="rd-label">选择题库</div>
          <el-select v-model="selectedBankIds" multiple collapse-tags clearable filterable placeholder="不选则从全部题库抽取" style="width: 100%" @change="resetWeight">
            <el-option v-for="b in publishedBanks" :key="b.id" :label="b.name" :value="b.id" />
          </el-select>
        </div>

        <div class="rd-section">
          <div class="rd-label">题目类型</div>
          <el-checkbox-group v-model="selectedTypes" @change="resetWeight">
            <el-checkbox-button v-for="t in QUESTION_TYPES" :key="t" :value="t">{{ QUESTION_TYPE_LABELS[t] }}</el-checkbox-button>
          </el-checkbox-group>
        </div>

        <div class="rd-section">
          <div class="rd-label">难度等级</div>
          <el-checkbox-group v-model="selectedDifficulties" @change="resetWeight">
            <el-checkbox-button v-for="d in difficulties" :key="d" :value="d">{{ DIFFICULTY_LABELS[d] }}</el-checkbox-button>
          </el-checkbox-group>
        </div>

        <div class="rd-section">
          <div class="rd-label">知识点</div>
          <el-select v-model="selectedKnowledgePoints" multiple collapse-tags clearable filterable placeholder="不选则包含全部知识点" style="width: 100%" :loading="loadingKnowledgePoints" @change="resetWeight">
            <el-option v-for="kp in knowledgePoints" :key="kp.id" :label="kp.name" :value="kp.id" />
          </el-select>
        </div>

        <div v-if="availableDimensions.length > 0" class="rd-section">
          <div class="rd-label">按比例分配</div>
          <div class="rd-dims">
            <el-checkbox-button
              v-for="dim in availableDimensions"
              :key="dim"
              :model-value="weightDimension === dim"
              @change="() => toggleWeightDim(dim)"
            >
              {{ DIM_LABEL[dim] }}
            </el-checkbox-button>
          </div>
          <div v-if="weightDimension && weightKeys.length > 0" class="rd-weights">
            <div v-for="key in weightKeys" :key="key" class="rd-weight-row">
              <span class="rd-weight-label">{{ weightKeyLabel(key) }}</span>
              <el-input-number
                :model-value="weightValues[key] ?? 0"
                :min="0"
                :max="100"
                size="small"
                controls-position="right"
                @update:model-value="(v: number | undefined) => setWeight(key, v || 0)"
              />
            </div>
            <p class="dim">输入的数字按比例折算，无需凑满 100</p>
          </div>
        </div>

        <div class="rd-section">
          <div class="rd-label">抽取数量</div>
          <el-input-number v-model="count" :min="1" :max="countSliderMax" size="small" />
          <p class="dim rd-summary">
            {{ filterSummary || '未设置筛选，从全部题目中抽取' }}｜可用题目池：{{ filteredPool.length }} 道
            <span v-if="count > filteredPool.length" class="rd-warn">（超过可用数量，将全部抽取）</span>
          </p>
        </div>
      </div>
    </template>

    <template #footer>
      <template v-if="previewQuestions">
        <el-button @click="previewQuestions = null">重新抽题</el-button>
        <el-button type="primary" :disabled="previewQuestions.length === 0" @click="handleConfirm">确认加入试卷</el-button>
      </template>
      <template v-else>
        <span class="rd-footer-info">
          <span v-if="filteredPool.length === 0" class="rd-warn">当前条件下没有可用题目</span>
          <span v-else class="dim">实际抽取 {{ Math.min(count, filteredPool.length) }} 道题目</span>
        </span>
        <el-button @click="handleClose(false)">取消</el-button>
        <el-button type="primary" :disabled="filteredPool.length === 0" @click="doRandomSelect">随机抽题</el-button>
      </template>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
// 随机抽题弹窗：对齐原 React 版 random-question-dialog.tsx
import { computed, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { questionApi, questionBankApi } from '@/api/evaluation';
import { knowledgeApi } from '@/api/lesson';
import { fetchAllPages } from '@/components/common/content-list-page.types';
import { QUESTION_TYPES, QUESTION_TYPE_LABELS, QUESTION_TYPE_COLORS, DIFFICULTY_LABELS } from '@/types/evaluation';
import type { Difficulty, Question, QuestionBank, QuestionType } from '@/types/evaluation';

type WeightDimension = 'bank' | 'type' | 'difficulty' | 'knowledge';

const DIM_LABEL: Record<WeightDimension, string> = {
  bank: '按题库比例',
  type: '按题型比例',
  difficulty: '按难度比例',
  knowledge: '按知识点比例'
};

const difficulties: Difficulty[] = ['easy', 'medium', 'hard'];

interface EvalKnowledgePoint {
  id: string;
  name: string;
}

const props = defineProps<{
  modelValue: boolean;
  selectedQuestionIds: string[];
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'add-questions', questions: Question[]): void;
}>();

const banks = ref<QuestionBank[]>([]);
const questions = ref<Question[]>([]);
const knowledgePoints = ref<EvalKnowledgePoint[]>([]);
const loadingKnowledgePoints = ref(false);

const selectedBankIds = ref<string[]>([]);
const selectedTypes = ref<QuestionType[]>([]);
const selectedDifficulties = ref<Difficulty[]>([]);
const selectedKnowledgePoints = ref<string[]>([]);
const count = ref(5);

const weightDimension = ref<WeightDimension | ''>('');
const weightValues = ref<Record<string, number>>({});
const previewQuestions = ref<Question[] | null>(null);

const publishedBanks = computed(() => banks.value.filter((b) => b.status === 'published'));

const basePool = computed(() =>
  questions.value.filter((q) => {
    if (props.selectedQuestionIds.includes(q.id)) return false;
    const bank = banks.value.find((b) => b.id === q.bankId);
    return bank?.status === 'published';
  })
);

const filteredPool = computed(() => {
  let pool = [...basePool.value];
  if (selectedBankIds.value.length > 0) pool = pool.filter((q) => selectedBankIds.value.includes(q.bankId));
  if (selectedTypes.value.length > 0) pool = pool.filter((q) => selectedTypes.value.includes(q.type));
  if (selectedDifficulties.value.length > 0)
    pool = pool.filter((q) => q.difficulty && selectedDifficulties.value.includes(q.difficulty as Difficulty));
  if (selectedKnowledgePoints.value.length > 0)
    pool = pool.filter((q) => q.knowledgePoints?.some((kp) => selectedKnowledgePoints.value.includes(kp)));
  return pool;
});

const weightKeys = computed<string[]>(() => {
  if (!weightDimension.value) return [];
  switch (weightDimension.value) {
    case 'bank':
      return selectedBankIds.value.length > 0 ? selectedBankIds.value : publishedBanks.value.map((b) => b.id);
    case 'type':
      return QUESTION_TYPES as string[];
    case 'difficulty':
      return difficulties as string[];
    case 'knowledge':
      return selectedKnowledgePoints.value.length > 0
        ? selectedKnowledgePoints.value
        : knowledgePoints.value.map((k) => k.id);
  }
});

const availableDimensions = computed<WeightDimension[]>(() => {
  const dims: WeightDimension[] = [];
  const bankKeys = selectedBankIds.value.length > 0 ? selectedBankIds.value : publishedBanks.value.map((b) => b.id);
  if (bankKeys.length >= 2) dims.push('bank');
  const typeKeys = selectedTypes.value.length > 0 ? selectedTypes.value : (QUESTION_TYPES as string[]);
  if (typeKeys.length >= 2) dims.push('type');
  const diffKeys = selectedDifficulties.value.length > 0 ? selectedDifficulties.value : (difficulties as string[]);
  if (diffKeys.length >= 2) dims.push('difficulty');
  const kpKeys = selectedKnowledgePoints.value.length > 0
    ? selectedKnowledgePoints.value
    : knowledgePoints.value.map((k) => k.id);
  if (kpKeys.length >= 2) dims.push('knowledge');
  return dims;
});

const countSliderMax = computed(() => Math.max(1, Math.min(50, filteredPool.value.length)));

const filterSummary = computed(() => {
  const parts: string[] = [];
  if (selectedBankIds.value.length > 0) parts.push(`题库 ${selectedBankIds.value.length} 个`);
  if (selectedTypes.value.length > 0) parts.push(`题型 ${selectedTypes.value.length} 种`);
  if (selectedDifficulties.value.length > 0) parts.push(`难度 ${selectedDifficulties.value.length} 级`);
  if (selectedKnowledgePoints.value.length > 0) parts.push(`知识点 ${selectedKnowledgePoints.value.length} 个`);
  return parts.length > 0 ? `筛选条件：${parts.join('，')}` : '';
});

async function loadData() {
  try {
    const [bankRes, allQuestions] = await Promise.all([
      questionBankApi.list({ limit: 200 }),
      fetchAllPages<Question>((page, pageSize) => questionApi.list({ limit: pageSize, offset: page * pageSize }))
    ]);
    banks.value = bankRes.items;
    questions.value = allQuestions;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载题目列表失败');
  }
}

async function loadKnowledgePoints() {
  loadingKnowledgePoints.value = true;
  try {
    const res = await knowledgeApi.list({ limit: 1000 });
    knowledgePoints.value = res.items.map((kp) => ({ id: kp.id, name: kp.name }));
  } catch {
    knowledgePoints.value = [];
  } finally {
    loadingKnowledgePoints.value = false;
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (!open) return;
    void loadData();
    void loadKnowledgePoints();
  }
);

function allocateProportions(total: number, entries: string[], weights: Record<string, number>): Record<string, number> {
  const active = entries.filter((k) => (weights[k] ?? 0) > 0);
  const items = active.length > 0 ? active : entries;
  const rawSum = items.reduce((s, k) => s + (weights[k] || 0), 0);
  const fracs = items.map((k) => ({
    key: k,
    frac: rawSum > 0 ? (total * (weights[k] || 0)) / rawSum : total / items.length
  }));
  const result: Record<string, number> = {};
  let allocated = 0;
  const remainders: { key: string; rem: number }[] = [];
  fracs.forEach(({ key, frac }) => {
    const floor = Math.floor(frac);
    result[key] = floor;
    allocated += floor;
    remainders.push({ key, rem: frac - floor });
  });
  remainders.sort((a, b) => b.rem - a.rem);
  for (let i = 0; i < total - allocated; i++) {
    if (i < remainders.length) result[remainders[i].key]++;
  }
  return result;
}

function doRandomSelect() {
  let allSelected: Question[] = [];
  const pool = filteredPool.value;

  if (weightDimension.value && weightKeys.value.length > 0) {
    const allocation = allocateProportions(count.value, weightKeys.value, weightValues.value);
    const used = new Set<string>();

    Object.entries(allocation).forEach(([key, target]) => {
      if (target <= 0) return;
      const candidates = pool.filter((q) => {
        if (used.has(q.id)) return false;
        if (weightDimension.value === 'bank') return q.bankId === key;
        if (weightDimension.value === 'type') return q.type === key;
        if (weightDimension.value === 'difficulty') return q.difficulty === key;
        return q.knowledgePoints?.includes(key);
      });
      const take = Math.min(target, candidates.length);
      for (let i = 0; i < take; i++) {
        const idx = Math.floor(Math.random() * candidates.length);
        const q = candidates.splice(idx, 1)[0];
        allSelected.push(q);
        used.add(q.id);
      }
    });

    if (allSelected.length < count.value) {
      const remaining = pool.filter((q) => !used.has(q.id));
      const need = count.value - allSelected.length;
      for (let i = 0; i < Math.min(need, remaining.length); i++) {
        const idx = Math.floor(Math.random() * remaining.length);
        allSelected.push(remaining.splice(idx, 1)[0]);
        used.add(allSelected[allSelected.length - 1].id);
      }
    }
  } else {
    const shuffled = [...pool];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    allSelected = shuffled.slice(0, Math.min(count.value, shuffled.length));
  }

  for (let i = allSelected.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [allSelected[i], allSelected[j]] = [allSelected[j], allSelected[i]];
  }
  previewQuestions.value = allSelected;
}

function handleConfirm() {
  if (previewQuestions.value && previewQuestions.value.length > 0) {
    emit('add-questions', previewQuestions.value);
  }
  handleClose(false);
}

function resetWeight() {
  weightDimension.value = '';
  weightValues.value = {};
}

function toggleWeightDim(dim: WeightDimension) {
  if (weightDimension.value === dim) {
    weightDimension.value = '';
    weightValues.value = {};
  } else {
    weightDimension.value = dim;
    weightValues.value = {};
  }
}

function setWeight(key: string, v: number) {
  weightValues.value = { ...weightValues.value, [key]: Math.max(0, Math.min(100, v)) };
}

function removeFromPreview(qid: string) {
  previewQuestions.value = previewQuestions.value ? previewQuestions.value.filter((q) => q.id !== qid) : null;
}

function handleClose(v: boolean) {
  if (!v) {
    selectedBankIds.value = [];
    selectedTypes.value = [];
    selectedDifficulties.value = [];
    selectedKnowledgePoints.value = [];
    count.value = 5;
    weightDimension.value = '';
    weightValues.value = {};
    previewQuestions.value = null;
  }
  emit('update:modelValue', v);
}

function typeLabel(t: QuestionType): string {
  return QUESTION_TYPE_LABELS[t] || t;
}
function typeColor(t: QuestionType): string {
  return QUESTION_TYPE_COLORS[t] || '#909399';
}
function difficultyLabel(d: string): string {
  return DIFFICULTY_LABELS[d] || d;
}
function bankName(bankId: string): string {
  return banks.value.find((b) => b.id === bankId)?.name || '';
}
function weightKeyLabel(key: string): string {
  if (weightDimension.value === 'bank') return banks.value.find((b) => b.id === key)?.name || key;
  if (weightDimension.value === 'type') return QUESTION_TYPE_LABELS[key as QuestionType] || key;
  if (weightDimension.value === 'difficulty') return DIFFICULTY_LABELS[key] || key;
  return knowledgePoints.value.find((k) => k.id === key)?.name || key;
}
</script>

<style scoped>
.rd-hint {
  margin: 0 0 12px;
  font-size: 13px;
  color: #909399;
}
.rd-body {
  max-height: 56vh;
  overflow-y: auto;
  padding-right: 4px;
}
.rd-section {
  margin-bottom: 14px;
}
.rd-label {
  font-size: 13px;
  font-weight: 600;
  color: #606266;
  margin-bottom: 6px;
}
.rd-dims {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 8px;
}
.rd-weights {
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background: #f7f8fa;
  padding: 10px 12px;
  max-height: 200px;
  overflow-y: auto;
}
.rd-weight-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 8px;
}
.rd-weight-label {
  font-size: 12px;
  color: #606266;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.rd-summary {
  margin-top: 6px;
}
.rd-warn {
  color: #e6a23c;
}
.rd-footer-info {
  flex: 1;
  text-align: left;
  font-size: 12px;
}
.rd-preview {
  max-height: 54vh;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.rd-preview-card {
  display: flex;
  gap: 10px;
  align-items: flex-start;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  padding: 10px 12px;
}
.rd-idx {
  width: 20px;
  flex-shrink: 0;
  color: #909399;
  font-size: 12px;
  line-height: 20px;
}
.rd-preview-body {
  flex: 1;
  min-width: 0;
}
.rd-preview-content {
  margin: 0 0 6px;
  font-size: 13px;
  color: #303133;
  line-height: 1.5;
}
.rd-preview-meta {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 6px;
}
.dim {
  font-size: 12px;
  color: #909399;
}
</style>
