// frontend/edu/app/evaluation/lesson-results/daily-exams/page.tsx
'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router'
import {
  BookOpen,
  CheckCircle2,
  ClipboardList,
  Eye,
  PenLine,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import { listAll } from '@zhiyu/api-client'
import { examUsageApi, examResultApi } from '@/lib/api'
import type { ExamResult, ExamUsage } from '@/lib/types'
import { formatDateTime } from '@/lib/format-utils'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { SearchInput } from '@/components/shared/search-input'
import { EmptyState } from '@zhiyu/ui'
import { useT } from '@/lib/i18n/locale-provider'

interface UsageStats {
  submitted: number
  pending: number
  graded: number
}

export default function DailyExamsPage() {
  const t = useT()
  const [usages, setUsages] = useState<ExamUsage[]>([])
  const [usageStats, setUsageStats] = useState<Record<string, UsageStats>>({})
  const [selectedUsageId, setSelectedUsageId] = useState<string | null>(null)
  const [results, setResults] = useState<ExamResult[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  // 统计选中项：避免对全部 usage 并发请求（N+1 打爆后端）
  const loadStats = useCallback(async (usageId: string) => {
    try {
      // 全量分页拉取该考试安排的提交记录，避免超过 500 条时提交人数被截断低估
      const list = await listAll((p, ps) =>
        examResultApi.list({ usageId, limit: ps, offset: p * ps }),
      )
      setUsageStats((prev) => ({
        ...prev,
        [usageId]: {
          submitted: list.length,
          pending: list.filter((x) => x.gradingStatus !== 'evaluated').length,
          graded: list.filter((x) => x.gradingStatus === 'evaluated').length,
        },
      }))
    } catch {
      setUsageStats((prev) => ({ ...prev, [usageId]: { submitted: 0, pending: 0, graded: 0 } }))
    }
  }, [])

  // 已统计过的考试安排（去重，避免重复请求）
  const statsDoneRef = useRef<Set<string>>(new Set())
  // 结果列表请求序号守卫：切换考试安排时丢弃过期响应，防止旧安排数据错位/乱序覆盖
  const resultsSeqRef = useRef(0)

  useEffect(() => {
    const load = async () => {
      try {
        // scope=all：课程节点随时作答（always）的自动考试安排不在管理列表默认范围，日常考试需全量
        const items = await listAll((p, ps) =>
          examUsageApi.list({ limit: ps, offset: p * ps, scope: 'all' }),
        )
        setUsages(items)
        const firstId = items[0]?.id ?? null
        setSelectedUsageId((prev) => prev ?? firstId)
        if (firstId) {
          // 登记 statsDoneRef，避免随后选中 effect 对首个安排重复发起统计请求
          statsDoneRef.current.add(firstId)
          void loadStats(firstId)
        }
      } catch {
        /* ignore */
      }
      setLoading(false)
    }
    load()
  }, [loadStats])

  useEffect(() => {
    if (!selectedUsageId) return
    const seq = ++resultsSeqRef.current
    listAll((p, ps) => examResultApi.list({ usageId: selectedUsageId, limit: ps, offset: p * ps }))
      .then((items) => {
        if (seq !== resultsSeqRef.current) return
        setResults(items)
      })
      .catch(() => {
        if (seq !== resultsSeqRef.current) return
        setResults([])
      })
  }, [selectedUsageId])

  // 切换选中项时统计其数据（已统计过的跳过，避免重复请求）
  useEffect(() => {
    if (selectedUsageId && !statsDoneRef.current.has(selectedUsageId)) {
      statsDoneRef.current.add(selectedUsageId)
      void loadStats(selectedUsageId)
    }
  }, [selectedUsageId, loadStats])

  const filteredUsages = useMemo(() => {
    if (!search.trim()) return usages
    const q = search.trim().toLowerCase()
    return usages.filter((u) => u.name.toLowerCase().includes(q))
  }, [usages, search])

  const selectedUsage = usages.find((u) => u.id === selectedUsageId) || null
  const selectedStats = selectedUsageId ? usageStats[selectedUsageId] : undefined

  if (loading)
    return (
      <div className="h-screen flex items-center justify-center text-gray-400">{t('加载中...')}</div>
    )

  return (
    <div className="h-screen flex flex-col bg-gray-50">
      <div className="bg-white border-b border-gray-200 shrink-0">
        <div className="max-w-[1600px] mx-auto px-6 py-4">
          <h1 className="text-xl font-semibold text-foreground">{t('日常考试评价')}</h1>
          <p className="text-sm text-gray-500 mt-0.5">{t('选择考试安排，查看学生提交并进行评分')}</p>
        </div>
      </div>

      <div className="flex-1 flex flex-col md:flex-row overflow-hidden max-w-[1600px] mx-auto w-full">
        <div className="w-full md:w-80 shrink-0 bg-white border-r border-gray-200 flex flex-col max-h-[50vh] md:max-h-none">
          <div className="p-4 border-b border-gray-100">
            <SearchInput
              wrapperClassName="w-full"
              iconClassName="absolute left-2.5 top-2.5 h-4 w-4 text-gray-400"
              placeholder={t('搜索考试名称...')}
              inputClassName="pl-9 text-sm"
              value={search}
              onChange={setSearch}
            />
          </div>
          <div className="flex-1 overflow-y-auto p-3 space-y-1.5">
            {filteredUsages.map((u) => {
              const st = usageStats[u.id]
              const pending = st?.pending || 0
              return (
                <button
                  key={u.id}
                  onClick={() => {
                    // 切换安排时先清空旧结果，避免新安排数据返回前表格仍展示上一安排的学生/得分记录
                    setResults([])
                    setSelectedUsageId(u.id)
                  }}
                  className={cn(
                    'w-full text-left rounded-xl p-3 transition-all border',
                    selectedUsageId === u.id
                      ? 'bg-primary/[0.06] border-primary/30 shadow-sm ring-1 ring-primary/10'
                      : 'bg-white border-gray-100 hover:border-gray-300 hover:shadow-sm',
                  )}
                >
                  <p
                    className={cn(
                      'text-sm font-semibold truncate',
                      selectedUsageId === u.id ? 'text-primary' : 'text-gray-800',
                    )}
                  >
                    {u.name}
                  </p>
                  <div className="flex items-center justify-between mt-1">
                    <span className="text-[11px] text-gray-400 truncate">
                      {t('已提交 {n} 人', { n: st?.submitted || 0 })}
                    </span>
                    {pending > 0 && (
                      <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-amber-50 text-amber-600 font-medium border border-amber-100">
                        {t('待评 {n}', { n: pending })}
                      </span>
                    )}
                  </div>
                </button>
              )
            })}
            {filteredUsages.length === 0 && (
              <EmptyState
                compact
                title={t('暂无考试安排')}
                className="py-8"
                titleClassName="text-gray-400"
              />
            )}
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {selectedUsage ? (
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-semibold text-gray-800">{selectedUsage.name}</h2>
                  <div className="flex items-center gap-2 mt-1.5">
                    <Badge variant="outline" className="text-xs font-normal text-gray-500">
                      {selectedUsage.status === 'finished'
                        ? t('已结束')
                        : selectedUsage.status === 'in_progress'
                          ? t('进行中')
                          : t('待开始')}
                    </Badge>
                    <span className="text-xs text-gray-400">
                      {t('{submitted} 份提交 · 待评 {pending} · 已评 {graded}', {
                        submitted: selectedStats?.submitted || 0,
                        pending: selectedStats?.pending || 0,
                        graded: selectedStats?.graded || 0,
                      })}
                    </span>
                  </div>
                </div>
              </div>

              <div className="rounded-xl border border-gray-200 overflow-hidden bg-white">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-gray-50">
                      <TableHead className="text-xs">{t('学生')}</TableHead>
                      <TableHead className="text-xs">{t('班级')}</TableHead>
                      <TableHead className="text-xs">{t('年级')}</TableHead>
                      <TableHead className="text-xs">{t('得分')}</TableHead>
                      <TableHead className="text-xs">{t('评分状态')}</TableHead>
                      <TableHead className="text-xs">{t('提交时间')}</TableHead>
                      <TableHead className="text-xs text-right w-40">{t('操作')}</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {results.map((r) => (
                      <TableRow key={r.id}>
                        <TableCell className="text-sm font-medium">{r.studentName}</TableCell>
                        <TableCell className="text-xs text-gray-500">{r.className}</TableCell>
                        <TableCell className="text-xs text-gray-500">{r.grade}</TableCell>
                        <TableCell className="text-sm font-semibold">
                          {r.score}/{r.totalScore}
                        </TableCell>
                        <TableCell>
                          {r.gradingStatus === 'evaluated' ? (
                            <Badge
                              variant="outline"
                              className="text-[10px] bg-green-50 text-green-600 border-green-200 gap-1"
                            >
                              <CheckCircle2 className="h-3 w-3" />
                              {t('已评分')}
                            </Badge>
                          ) : (
                            <Badge
                              variant="outline"
                              className="text-[10px] bg-amber-50 text-amber-600 border-amber-200"
                            >
                              {t('待评分')}
                            </Badge>
                          )}
                        </TableCell>
                        <TableCell className="text-xs text-gray-500">
                          {formatDateTime(r.submitTime)}
                        </TableCell>
                        <TableCell className="text-right">
                          <Button variant="outline" size="sm" className="h-7 text-xs px-2" asChild>
                            <Link to={`/evaluation/lesson-results/daily-exams/${r.id}`}>
                              <Eye className="mr-1 h-3 w-3" />
                              {t('查看')}
                            </Link>
                          </Button>
                          {r.gradingStatus === 'evaluated' ? (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 text-xs text-green-600 px-2"
                              disabled
                            >
                              <CheckCircle2 className="mr-1 h-3 w-3" />
                              {t('已评分')}
                            </Button>
                          ) : (
                            <Button size="sm" className="h-7 text-xs px-2" asChild>
                              <Link to={`/evaluation/lesson-results/daily-exams/${r.id}`}>
                                <PenLine className="mr-1 h-3 w-3" />
                                {t('评分')}
                              </Link>
                            </Button>
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
                {results.length === 0 && (
                  <EmptyState
                    icon={<ClipboardList className="h-10 w-10 opacity-40" />}
                    title={t('暂无学生提交记录')}
                    titleClassName="text-gray-400"
                  />
                )}
              </div>
            </div>
          ) : (
            <EmptyState
              icon={<BookOpen className="h-12 w-12 opacity-50" />}
              title={t('请在左侧选择一个考试安排')}
              titleClassName="text-gray-400"
              className="h-full"
            />
          )}
        </div>
      </div>
    </div>
  )
}

// plus-ui/src-portal/views/evaluation/daily-exams.vue
<template>
  <div class="daily-exams-page">
    <div class="page-header">
      <div>
        <h2 class="page-title">日常考试评价</h2>
        <p class="page-sub">选择考试安排，查看学生提交并进行评分</p>
      </div>
    </div>

    <div v-if="loading" class="loading-full">加载中...</div>

    <div v-else class="master-detail">
      <!-- 左侧：考试安排列表 -->
      <aside class="usage-panel">
        <div class="usage-search">
          <el-input
            v-model="search"
            placeholder="搜索考试名称..."
            clearable
            :prefix-icon="Search"
          />
        </div>
        <div class="usage-list">
          <div
            v-for="u in filteredUsages"
            :key="u.id"
            class="usage-item"
            :class="{ active: selectedUsageId === u.id }"
            @click="selectUsage(u.id)"
          >
            <p class="usage-name" :class="{ active: selectedUsageId === u.id }">{{ u.name }}</p>
            <div class="usage-meta">
              <span class="usage-submitted">已提交 {{ statsOf(u.id)?.submitted || 0 }} 人</span>
              <span v-if="(statsOf(u.id)?.pending || 0) > 0" class="usage-pending">待评 {{ statsOf(u.id)?.pending || 0 }}</span>
            </div>
          </div>
          <div v-if="filteredUsages.length === 0" class="usage-empty">
            <el-icon class="empty-icon"><Tickets /></el-icon>
            <span>暂无考试安排</span>
          </div>
        </div>
      </aside>

      <!-- 右侧：选中安排的提交记录 -->
      <section class="detail-panel">
        <template v-if="selectedUsage">
          <div class="detail-head">
            <div>
              <h3 class="detail-title">{{ selectedUsage.name }}</h3>
              <div class="detail-sub">
                <el-tag size="small" :type="usageStatusTagType(selectedUsage.status)">{{ usageStatusLabel(selectedUsage.status) }}</el-tag>
                <span class="detail-stats">{{ selectedStats?.submitted || 0 }} 份提交 · 待评 {{ selectedStats?.pending || 0 }} · 已评 {{ selectedStats?.graded || 0 }}</span>
              </div>
            </div>
          </div>

          <div class="table-card">
            <el-table :data="results" stripe>
              <el-table-column label="学生" min-width="120">
                <template #default="{ row }"><span class="cell-student">{{ row.studentName }}</span></template>
              </el-table-column>
              <el-table-column label="班级" prop="className" min-width="110">
                <template #default="{ row }"><span class="cell-dim">{{ row.className }}</span></template>
              </el-table-column>
              <el-table-column label="年级" prop="grade" min-width="90">
                <template #default="{ row }"><span class="cell-dim">{{ row.grade }}</span></template>
              </el-table-column>
              <el-table-column label="得分" width="100">
                <template #default="{ row }"><span class="cell-score">{{ row.score }}/{{ row.totalScore }}</span></template>
              </el-table-column>
              <el-table-column label="评分状态" width="100">
                <template #default="{ row }">
                  <el-tag v-if="row.gradingStatus === 'evaluated'" type="success" size="small">
                    <el-icon class="tag-icon"><CircleCheck /></el-icon>已评分
                  </el-tag>
                  <el-tag v-else type="warning" size="small">待评分</el-tag>
                </template>
              </el-table-column>
              <el-table-column label="提交时间" width="150">
                <template #default="{ row }"><span class="cell-dim">{{ formatDateTime(row.submitTime) }}</span></template>
              </el-table-column>
              <el-table-column label="操作" width="180" align="right">
                <template #default="{ row }">
                  <el-button size="small" @click="goDetail(row.id)">
                    <el-icon class="btn-icon"><View /></el-icon>查看
                  </el-button>
                  <el-button
                    v-if="row.gradingStatus === 'evaluated'"
                    size="small"
                    disabled
                    class="graded-btn"
                  >
                    <el-icon class="btn-icon"><CircleCheck /></el-icon>已评分
                  </el-button>
                  <el-button v-else size="small" type="primary" @click="goDetail(row.id)">
                    <el-icon class="btn-icon"><EditPen /></el-icon>评分
                  </el-button>
                </template>
              </el-table-column>
              <template #empty>
                <div class="table-empty">
                  <el-icon class="empty-icon-lg"><Tickets /></el-icon>
                  <span>暂无学生提交记录</span>
                </div>
              </template>
            </el-table>
          </div>
        </template>

        <div v-else class="no-selection">
          <el-icon class="empty-icon-xl"><Reading /></el-icon>
          <span>请在左侧选择一个考试安排</span>
        </div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { Search, View, EditPen, CircleCheck, Tickets, Reading } from '@element-plus/icons-vue';
import { examUsageApi, examResultApi } from '@/api/evaluation';
import type { ExamResult, ExamUsage } from '@/types/evaluation';

interface UsageStats {
  submitted: number;
  pending: number;
  graded: number;
}

const router = useRouter();
const usages = ref<ExamUsage[]>([]);
const usageStats = ref<Record<string, UsageStats>>({});
const selectedUsageId = ref<string | null>(null);
const results = ref<ExamResult[]>([]);
const loading = ref(true);
const search = ref('');

// 分页全量拉取：后端列表接口单页上限 200，逐页合并避免静默截断（对齐 React listAll）
const PAGE_SIZE = 200;
const MAX_PAGES = 1000;
async function listAll<T>(
  fetcher: (page: number, pageSize: number) => Promise<{ items: T[] }>
): Promise<T[]> {
  const all: T[] = [];
  for (let page = 0; ; page++) {
    if (page >= MAX_PAGES) {
      throw new Error('fetchAllPages: 超过最大页数，疑似分页未生效，已中止');
    }
    const res = await fetcher(page, PAGE_SIZE);
    const items = res.items || [];
    all.push(...items);
    if (items.length < PAGE_SIZE) break;
  }
  return all;
}

// 统计选中项：避免对全部 usage 并发请求（N+1 打爆后端）；
// 全量分页拉取该考试安排的提交记录，避免超过 500 条时提交人数被截断低估
async function loadStats(usageId: string) {
  try {
    const list = await listAll((p, ps) => examResultApi.list({ usageId, limit: ps, offset: p * ps }));
    usageStats.value = {
      ...usageStats.value,
      [usageId]: {
        submitted: list.length,
        pending: list.filter((x) => x.gradingStatus !== 'evaluated').length,
        graded: list.filter((x) => x.gradingStatus === 'evaluated').length
      }
    };
  } catch {
    usageStats.value = {
      ...usageStats.value,
      [usageId]: { submitted: 0, pending: 0, graded: 0 }
    };
  }
}

// 已统计过的考试安排（去重，避免重复请求）
const statsDone = new Set<string>();
// 结果列表请求序号守卫：切换考试安排时丢弃过期响应，防止旧安排数据错位/乱序覆盖
let resultsSeq = 0;

async function loadUsages() {
  try {
    // scope=all：课程节点随时作答（always）的自动考试安排不在管理列表默认范围，日常考试需全量
    const items = await listAll((p, ps) =>
      examUsageApi.list({ limit: ps, offset: p * ps, scope: 'all' })
    );
    usages.value = items;
    const firstId = items[0]?.id ?? null;
    if (firstId) {
      // 登记 statsDone，避免随后选中 effect 对首个安排重复发起统计请求
      statsDone.add(firstId);
      selectedUsageId.value = firstId;
      void loadStats(firstId);
    }
  } catch {
    /* ignore */
  }
  loading.value = false;
}

watch(selectedUsageId, (id) => {
  if (!id) return;
  const seq = ++resultsSeq;
  listAll((p, ps) =>
    examResultApi.list({ usageId: id, limit: ps, offset: p * ps })
  )
    .then((items) => {
      if (seq !== resultsSeq) return;
      results.value = items;
    })
    .catch(() => {
      if (seq !== resultsSeq) return;
      results.value = [];
    });
  // 切换选中项时统计其数据（已统计过的跳过，避免重复请求）
  if (!statsDone.has(id)) {
    statsDone.add(id);
    void loadStats(id);
  }
});

function selectUsage(id: string) {
  // 切换安排时先清空旧结果，避免新安排数据返回前表格仍展示上一安排的学生/得分记录
  results.value = [];
  selectedUsageId.value = id;
}

function goDetail(resultId: string) {
  router.push(`/evaluation/lesson-results/daily-exams/${resultId}`);
}

function statsOf(id: string): UsageStats | undefined {
  return usageStats.value[id];
}

const filteredUsages = computed(() => {
  if (!search.value.trim()) return usages.value;
  const q = search.value.trim().toLowerCase();
  return usages.value.filter((u) => u.name.toLowerCase().includes(q));
});
const selectedUsage = computed(
  () => usages.value.find((u) => u.id === selectedUsageId.value) || null
);
const selectedStats = computed(() =>
  selectedUsageId.value ? usageStats.value[selectedUsageId.value] : undefined
);

function usageStatusLabel(s: string): string {
  if (s === 'finished') return '已结束';
  if (s === 'in_progress') return '进行中';
  return '待开始';
}
function usageStatusTagType(s: string): 'success' | 'info' | 'warning' {
  if (s === 'finished') return 'info';
  if (s === 'in_progress') return 'success';
  return 'warning';
}

function formatDateTime(s?: string): string {
  if (!s) return '-';
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return '-';
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

onMounted(loadUsages);
</script>

<style scoped>
.daily-exams-page {
  padding: 16px;
}
.page-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 16px;
}
.page-title {
  font-size: 20px;
  font-weight: 700;
  margin: 0;
}
.page-sub {
  color: #909399;
  margin: 8px 0 0;
  font-size: 13px;
}
.loading-full {
  height: 320px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #909399;
  font-size: 14px;
}

.master-detail {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  height: calc(100vh - 210px);
  min-height: 420px;
}

/* 左侧考试安排 */
.usage-panel {
  width: 300px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 8px;
  overflow: hidden;
  height: 100%;
}
.usage-search {
  padding: 12px;
  border-bottom: 1px solid #f0f2f5;
}
.usage-list {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.usage-item {
  padding: 12px;
  border-radius: 10px;
  border: 1px solid #ebeef5;
  cursor: pointer;
  transition: all 0.2s;
  background: #fff;
}
.usage-item:hover {
  border-color: #c0c4cc;
}
.usage-item.active {
  background: rgba(64, 158, 255, 0.06);
  border-color: rgba(64, 158, 255, 0.4);
  box-shadow: 0 0 0 1px rgba(64, 158, 255, 0.1);
}
.usage-name {
  font-size: 14px;
  font-weight: 600;
  color: #303133;
  margin: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.usage-name.active {
  color: #409eff;
}
.usage-meta {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 4px;
  gap: 8px;
}
.usage-submitted {
  font-size: 11px;
  color: #c0c4cc;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.usage-pending {
  flex-shrink: 0;
  font-size: 10px;
  line-height: 18px;
  padding: 0 6px;
  border-radius: 9999px;
  background: #fdf6ec;
  color: #e6a23c;
  font-weight: 500;
  border: 1px solid #faecd8;
}
.usage-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 32px 0;
  color: #c0c4cc;
  font-size: 13px;
}

/* 右侧提交记录 */
.detail-panel {
  flex: 1;
  min-width: 0;
  height: 100%;
  overflow-y: auto;
}
.detail-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}
.detail-title {
  font-size: 20px;
  font-weight: 600;
  color: #303133;
  margin: 0;
}
.detail-sub {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 6px;
}
.detail-stats {
  font-size: 12px;
  color: #c0c4cc;
}
.table-card {
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 8px;
  overflow: hidden;
}
.cell-student {
  font-size: 14px;
  font-weight: 500;
}
.cell-dim {
  font-size: 12px;
  color: #909399;
}
.cell-score {
  font-size: 14px;
  font-weight: 600;
}
.tag-icon {
  margin-right: 2px;
  vertical-align: -2px;
}
.btn-icon {
  margin-right: 3px;
  vertical-align: -2px;
}
.graded-btn {
  color: #67c23a;
}
.table-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 48px 0;
  color: #c0c4cc;
  font-size: 14px;
}
.empty-icon {
  font-size: 20px;
}
.empty-icon-lg {
  font-size: 40px;
  opacity: 0.4;
}
.empty-icon-xl {
  font-size: 48px;
  opacity: 0.5;
}
.no-selection {
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  color: #c0c4cc;
  font-size: 14px;
}
</style>
