// apps/edu/app/evaluation/scene-results/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import {
  BookOpen,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Eye,
  FileText,
  GraduationCap,
  Layers,
  PenLine,
  Search,
  Users,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import {
  scenarioApi,
  evaluationResultApi,
  userManagementApi,
  positionApi,
  taskApi,
} from '@/lib/api'
import type { SceneEvaluationResult } from '@/lib/types'
import { EVAL_METHOD_LABELS_GRADING } from '@/lib/types'

interface TaskStudent {
  studentId: string
  studentName: string
  studentNumber: string
  className: string
  enrollmentYear: number
  result: SceneEvaluationResult
}

interface TaskMethodGroup {
  methodKey: string
  students: TaskStudent[]
  pendingCount: number
  gradedCount: number
  weight: number
}

interface TaskGroup {
  taskId: string
  taskName: string
  methods: TaskMethodGroup[]
}

interface ScenarioGroup {
  positionName: string
  scenarios: {
    scenarioId: string
    scenarioName: string
    scenarioCode: string
    taskCount: number
    pendingCount: number
    gradedCount: number
    studentCount: number
  }[]
}

export default function GradingPage() {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedScenarioId, setSelectedScenarioId] = useState<string | null>(null)
  const [expandedTasks, setExpandedTasks] = useState<Set<string>>(new Set())

  const [scenarios, setScenarios] = useState<any[]>([])
  const [results, setResults] = useState<SceneEvaluationResult[]>([])
  const [userMap, setUserMap] = useState<Map<string, any>>(new Map())
  const [, setPositionMap] = useState<Map<string, string>>(new Map())
  const [taskNameMap, setTaskNameMap] = useState<Map<string, any>>(new Map())
  const [loading, setLoading] = useState(true)

  // 场景列表、用户、岗位、任务等基础数据只加载一次，与选中场景无关
  useEffect(() => {
    const load = async () => {
      try {
        const [scRes, userRes, posRes, taskRes] = await Promise.all([
          scenarioApi.list({ limit: 200 }).catch(() => ({ items: [] as any[] })),
          userManagementApi.list({ limit: 1000 }).catch(() => ({ items: [] as any[] })),
          positionApi.list({ limit: 500 }).catch(() => ({ items: [] as any[] })),
          taskApi.list({ limit: 10000 }).catch(() => ({ items: [] as any[] })),
        ])

        const pMap = new Map<string, string>()
        ;(posRes.items || []).forEach((p: any) => pMap.set(p.id, p.name))
        setPositionMap(pMap)

        const loadedScenarios = (scRes.items || [])
          .filter((s: any) => s.status === 'published')
          .map((s: any) => ({
            ...s,
            positionName: pMap.get(s.careerPositionId) || '未分类',
          }))
        setScenarios(loadedScenarios)
        setSelectedScenarioId((prev) => prev ?? loadedScenarios[0]?.id ?? null)

        const uMap = new Map<string, any>()
        ;(userRes.items || []).forEach((u: any) => uMap.set(u.id, u))
        setUserMap(uMap)

        const tMap = new Map<string, any>()
        ;(taskRes.items || []).forEach((t: any) => tMap.set(t.id, t))
        setTaskNameMap(tMap)
      } catch {
        /* ignore */
      }
      setLoading(false)
    }
    load()
  }, [])

  useEffect(() => {
    if (!selectedScenarioId) return
    evaluationResultApi
      .list({ sceneId: selectedScenarioId, limit: 500 })
      .then((res) => setResults(res.items || []))
      .catch(() => setResults([]))
  }, [selectedScenarioId])

  const scenarioGroups = useMemo<ScenarioGroup[]>(() => {
    const map = new Map<string, ScenarioGroup>()
    for (const scenario of scenarios) {
      // results 只包含当前选中场景的数据，非选中场景无法获得统计，置空避免串数据
      const subs =
        scenario.id === selectedScenarioId ? results.filter((s) => s.taskId) : []
      const pending = subs.filter((s) => s.status === 'pending').length
      const graded = subs.filter((s) => s.status === 'evaluated').length

      const item = {
        scenarioId: scenario.id,
        scenarioName: scenario.name,
        scenarioCode: scenario.code,
        taskCount: new Set(subs.map((s) => s.taskId)).size,
        pendingCount: pending,
        gradedCount: graded,
        studentCount: new Set(subs.map((s) => s.evaluateeId)).size,
      }

      const pos = scenario.positionName || '未分类'
      if (!map.has(pos)) {
        map.set(pos, { positionName: pos, scenarios: [] })
      }
      map.get(pos)!.scenarios.push(item)
    }
    return Array.from(map.values())
  }, [scenarios, results, selectedScenarioId])

  const filteredGroups = useMemo(() => {
    if (!searchQuery.trim()) return scenarioGroups
    const q = searchQuery.trim().toLowerCase()
    return scenarioGroups
      .map((g) => ({
        ...g,
        scenarios: g.scenarios.filter(
          (s) =>
            s.scenarioName.toLowerCase().includes(q) || s.scenarioCode.toLowerCase().includes(q),
        ),
      }))
      .filter((g) => g.scenarios.length > 0)
  }, [scenarioGroups, searchQuery])

  const selectedScenario = useMemo(
    () => scenarios.find((s) => s.id === selectedScenarioId),
    [selectedScenarioId, scenarios],
  )

  const taskGroups = useMemo<TaskGroup[]>(() => {
    if (!selectedScenarioId) return []
    const scenarioSubs = results
    const taskMap = new Map<string, TaskGroup>()

    const getMethodWeight = (
      taskInfo: any,
      methodKey: string,
      knownMethodCount: number,
    ): number => {
      const configured = taskInfo?.evalData?.methodWeights?.[methodKey]
      if (typeof configured === 'number') return configured
      return knownMethodCount > 0 ? 100 / knownMethodCount : 100
    }

    for (const sub of scenarioSubs) {
      const user = userMap.get(sub.evaluateeId)
      const taskStudent: TaskStudent = {
        studentId: sub.evaluateeId,
        studentName: user?.name || '未知',
        studentNumber: user?.studentNo || '-',
        className: user?.className || '-',
        enrollmentYear: user?.enrollmentYear || 0,
        result: sub,
      }

      const existing = taskMap.get(sub.taskId)
      const taskInfo = taskNameMap.get(sub.taskId)
      const evalMethods: string[] = taskInfo?.evalData?.evaluationMethods || []
      if (existing) {
        const method = existing.methods.find((f) => f.methodKey === sub.methodKey)
        if (method) {
          method.students.push(taskStudent)
          method.pendingCount += sub.status === 'pending' ? 1 : 0
          method.gradedCount += sub.status === 'evaluated' ? 1 : 0
        } else {
          const knownCount = evalMethods.length || existing.methods.length + 1
          existing.methods.push({
            methodKey: sub.methodKey,
            students: [taskStudent],
            pendingCount: sub.status === 'pending' ? 1 : 0,
            gradedCount: sub.status === 'evaluated' ? 1 : 0,
            weight: getMethodWeight(taskInfo, sub.methodKey, knownCount),
          })
        }
      } else {
        const knownCount = evalMethods.length || 1
        taskMap.set(sub.taskId, {
          taskId: sub.taskId,
          taskName: taskInfo?.name || sub.taskId,
          methods: [
            {
              methodKey: sub.methodKey,
              students: [taskStudent],
              pendingCount: sub.status === 'pending' ? 1 : 0,
              gradedCount: sub.status === 'evaluated' ? 1 : 0,
              weight: getMethodWeight(taskInfo, sub.methodKey, knownCount),
            },
          ],
        })
      }
    }

    return Array.from(taskMap.values())
  }, [selectedScenarioId, results, userMap, taskNameMap])

  const toggleTask = (taskId: string) => {
    setExpandedTasks((prev) => {
      const next = new Set(prev)
      if (next.has(taskId)) next.delete(taskId)
      else next.add(taskId)
      return next
    })
  }

  const groupStudents = (students: TaskStudent[]) => {
    const yearMap = new Map<number, Map<string, TaskStudent[]>>()
    for (const s of students) {
      if (!yearMap.has(s.enrollmentYear)) yearMap.set(s.enrollmentYear, new Map())
      const classMap = yearMap.get(s.enrollmentYear)!
      if (!classMap.has(s.className)) classMap.set(s.className, [])
      classMap.get(s.className)!.push(s)
    }
    const groups: { year: number; classes: { className: string; students: TaskStudent[] }[] }[] = []
    for (const [year, classMap] of yearMap) {
      const classes: { className: string; students: TaskStudent[] }[] = []
      for (const [className, classStudents] of classMap) {
        classes.push({ className, students: classStudents })
      }
      classes.sort((a, b) => a.className.localeCompare(b.className, 'zh-CN'))
      groups.push({ year, classes })
    }
    groups.sort((a, b) => b.year - a.year)
    return groups
  }

  const expandAll = () => setExpandedTasks(new Set(taskGroups.map((t) => t.taskId)))
  const collapseAll = () => setExpandedTasks(new Set())

  function TaskMethodTabs({ task }: { task: TaskGroup }) {
    const [activeMethod, setActiveMethod] = useState(task.methods[0]?.methodKey || '')
    const activeMethodData = task.methods.find((f) => f.methodKey === activeMethod)
    const yearGroups = activeMethodData ? groupStudents(activeMethodData.students) : []

    return (
      <div className="px-4 pb-4 border-t border-gray-100 bg-gray-50/30">
        {task.methods.length > 1 && (
          <div className="flex items-center gap-2 pt-3 mb-3 overflow-x-auto scrollbar-hide">
            {task.methods.map((m) => (
              <button
                key={m.methodKey}
                onClick={() => setActiveMethod(m.methodKey)}
                className={cn(
                  'flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all shrink-0',
                  activeMethod === m.methodKey
                    ? 'bg-primary text-primary-foreground shadow-sm'
                    : 'bg-white text-gray-600 border border-gray-200 hover:border-gray-300 hover:bg-gray-50',
                )}
              >
                {EVAL_METHOD_LABELS_GRADING[m.methodKey] || m.methodKey}
                <span className="ml-1 flex items-center gap-1">
                  {m.pendingCount > 0 && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-amber-400/20 text-amber-700 font-medium">
                      {m.pendingCount}
                    </span>
                  )}
                  {m.gradedCount > 0 && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-green-400/20 text-green-700 font-medium">
                      {m.gradedCount}
                    </span>
                  )}
                </span>
              </button>
            ))}
          </div>
        )}
        {activeMethodData && activeMethodData.students.length === 0 ? (
          <div className="py-8 text-center text-gray-400 text-sm bg-white rounded-lg border border-dashed border-gray-200 mt-3">
            暂无学生提交记录
          </div>
        ) : (
          <div className="space-y-3 mt-3">
            {yearGroups.map((yearGroup) => (
              <Card key={yearGroup.year} className="overflow-hidden border-gray-200">
                <div className="px-3 py-2 bg-gray-50 border-b border-gray-100 flex items-center gap-2">
                  <GraduationCap className="h-3.5 w-3.5 text-gray-500" />
                  <span className="text-xs font-semibold text-gray-700">{yearGroup.year} 届</span>
                  <span className="text-[10px] text-gray-400">
                    {yearGroup.classes.reduce((s, c) => s + c.students.length, 0)} 人
                  </span>
                </div>
                <div className="p-3 space-y-3">
                  {yearGroup.classes.map((classGroup) => (
                    <div key={classGroup.className}>
                      <div className="flex items-center gap-1.5 mb-2">
                        <Users className="h-3 w-3 text-gray-400" />
                        <span className="text-xs font-medium text-gray-600">
                          {classGroup.className}
                        </span>
                        <span className="text-[10px] text-gray-400">
                          {classGroup.students.length} 人
                        </span>
                      </div>
                      <div className="grid grid-cols-1 xl:grid-cols-2 gap-2">
                        {classGroup.students.map((item) => (
                          <div
                            key={item.studentId}
                            className="flex items-center justify-between p-2.5 bg-white rounded-lg border border-gray-100 hover:border-primary/20 hover:shadow-sm transition-all"
                          >
                            <div className="flex items-center gap-2.5 min-w-0">
                              <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary/20 to-primary/5 text-primary text-xs font-bold">
                                {item.studentName.charAt(0)}
                              </div>
                              <div className="min-w-0">
                                <div className="flex items-center gap-1.5 flex-wrap">
                                  <span className="font-medium text-gray-800 text-sm truncate">
                                    {item.studentName}
                                  </span>
                                  <span className="text-[10px] text-gray-400">
                                    {item.studentNumber}
                                  </span>
                                </div>
                                <div className="flex items-center gap-2 mt-0.5">
                                  {item.result.status === 'pending' ? (
                                    <span className="text-[10px] text-amber-600 font-medium">
                                      待评分
                                    </span>
                                  ) : item.result.totalScore != null ? (
                                    <span className="text-[10px] text-gray-500 font-medium">
                                      得分 {item.result.totalScore}/{item.result.maxScore}
                                    </span>
                                  ) : null}
                                </div>
                              </div>
                            </div>
                            <div className="flex items-center gap-1.5 shrink-0">
                              <Button
                                variant="outline"
                                size="sm"
                                className="h-7 text-xs px-2"
                                asChild
                              >
                                <Link href={`/evaluation/scene-results/${item.result.id}`}>
                                  <Eye className="mr-1 h-3 w-3" />
                                  查看
                                </Link>
                              </Button>
                              {item.result.status === 'pending' ? (
                                <Button size="sm" className="h-7 text-xs px-2" asChild>
                                  <Link href={`/evaluation/scene-results/${item.result.id}`}>
                                    <PenLine className="mr-1 h-3 w-3" />
                                    评分
                                  </Link>
                                </Button>
                              ) : (
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-7 text-xs text-green-600 px-2"
                                  disabled
                                >
                                  <CheckCircle2 className="mr-1 h-3 w-3" />
                                  已评分
                                </Button>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    )
  }

  if (loading)
    return <div className="h-screen flex items-center justify-center text-gray-400">加载中...</div>

  return (
    <div className="h-screen flex flex-col bg-gray-50">
      <div className="bg-white border-b border-gray-200 shrink-0">
        <div className="max-w-[1600px] mx-auto px-6 py-4">
          <h1 className="text-xl font-semibold text-foreground">场景任务评价</h1>
          <p className="text-sm text-gray-500 mt-0.5">选择场景与任务，查看学生提交并进行评分</p>
        </div>
      </div>

      <div className="flex-1 flex flex-col md:flex-row overflow-hidden max-w-[1600px] mx-auto w-full">
        <div className="w-full md:w-80 shrink-0 bg-white border-r border-gray-200 flex flex-col max-h-[50vh] md:max-h-none">
          <div className="p-4 border-b border-gray-100">
            <div className="relative w-full">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-400" />
              <Input
                placeholder="搜索场景..."
                className="pl-9 text-sm"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-3 space-y-5">
            {filteredGroups.map((group) => (
              <div key={group.positionName}>
                <div className="flex items-center gap-1.5 px-2 mb-2">
                  <Layers className="h-3.5 w-3.5 text-gray-400" />
                  <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">
                    {group.positionName}
                  </span>
                </div>
                <div className="space-y-1.5">
                  {group.scenarios.map((sc) => (
                    <button
                      key={sc.scenarioId}
                      onClick={() => setSelectedScenarioId(sc.scenarioId)}
                      className={cn(
                        'w-full text-left rounded-xl p-3 transition-all border',
                        selectedScenarioId === sc.scenarioId
                          ? 'bg-primary/[0.06] border-primary/30 shadow-sm ring-1 ring-primary/10'
                          : 'bg-white border-gray-100 hover:border-gray-300 hover:shadow-sm',
                      )}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <p
                            className={cn(
                              'text-sm font-semibold truncate',
                              selectedScenarioId === sc.scenarioId
                                ? 'text-primary'
                                : 'text-gray-800',
                            )}
                          >
                            {sc.scenarioName}
                          </p>
                          <p className="text-[11px] text-gray-400 mt-0.5">{sc.scenarioCode}</p>
                        </div>
                        <div className="flex flex-col items-end gap-1 shrink-0">
                          {sc.pendingCount > 0 && (
                            <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-amber-50 text-amber-600 font-medium border border-amber-100">
                              {sc.pendingCount}
                            </span>
                          )}
                          {sc.gradedCount > 0 && (
                            <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-green-50 text-green-600 font-medium border border-green-100">
                              {sc.gradedCount}
                            </span>
                          )}
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {selectedScenario ? (
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-semibold text-gray-800">{selectedScenario.name}</h2>
                  <div className="flex items-center gap-2 mt-1.5">
                    <Badge variant="outline" className="text-xs font-normal text-gray-500">
                      {selectedScenario.code}
                    </Badge>
                    <span className="text-xs text-gray-400">{results.length} 条提交记录</span>
                  </div>
                </div>
                {taskGroups.length > 0 && (
                  <div className="flex items-center gap-2">
                    <Button variant="outline" size="sm" className="h-8 text-xs" onClick={expandAll}>
                      全部展开
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-8 text-xs"
                      onClick={collapseAll}
                    >
                      全部收起
                    </Button>
                  </div>
                )}
              </div>

              {taskGroups.length === 0 ? (
                <Card className="border-dashed border-gray-200">
                  <CardContent className="py-12 text-center text-gray-400">
                    <FileText className="h-10 w-10 mx-auto mb-3 opacity-50" />
                    <p className="text-sm">该场景下暂无学生提交记录</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {taskGroups.map((task) => {
                    const isExpanded = expandedTasks.has(task.taskId)
                    const taskResults = results.filter((r) => r.taskId === task.taskId)
                    const totalStudents = new Set(taskResults.map((r) => r.evaluateeId)).size
                    const totalPending = task.methods.reduce((s, f) => s + f.pendingCount, 0)
                    const totalGraded = task.methods.reduce((s, f) => s + f.gradedCount, 0)

                    const taskScore = task.methods.reduce((sum, m) => {
                      const graded = m.students.filter((s) => s.result.status === 'evaluated')
                      if (graded.length === 0) return sum
                      const methodScore =
                        graded.reduce(
                          (acc, s) =>
                            acc + ((s.result.totalScore ?? 0) / (s.result.maxScore || 1)) * 100,
                          0,
                        ) / graded.length
                      return sum + (methodScore * (m.weight || 0)) / 100
                    }, 0)

                    return (
                      <Collapsible
                        key={task.taskId}
                        open={isExpanded}
                        onOpenChange={() => toggleTask(task.taskId)}
                      >
                        <Card className="overflow-hidden border-gray-200 shadow-sm">
                          <CollapsibleTrigger asChild>
                            <div className="p-4 flex items-center justify-between cursor-pointer hover:bg-gray-50/60 transition-colors">
                              <div className="flex items-center gap-4 min-w-0">
                                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 text-primary">
                                  <FileText className="h-5 w-5" />
                                </div>
                                <div className="min-w-0">
                                  <div className="flex items-center gap-2 flex-wrap">
                                    <p className="text-sm font-bold text-gray-800 truncate">
                                      {task.taskName}
                                    </p>
                                    {totalGraded > 0 && (
                                      <Badge
                                        variant="outline"
                                        className="text-[10px] font-normal bg-primary/5 text-primary border-primary/20"
                                      >
                                        均分 {taskScore.toFixed(1)}
                                      </Badge>
                                    )}
                                  </div>
                                  <div className="flex items-center gap-2 mt-1.5 flex-wrap">
                                    {task.methods.map((m) => (
                                      <Badge
                                        key={m.methodKey}
                                        variant="outline"
                                        className="text-[10px] font-normal bg-gray-50 text-gray-600 border-gray-200"
                                      >
                                        {EVAL_METHOD_LABELS_GRADING[m.methodKey] || m.methodKey}
                                      </Badge>
                                    ))}
                                  </div>
                                </div>
                              </div>
                              <div className="flex items-center gap-4 shrink-0">
                                <div className="flex items-center gap-3 text-xs">
                                  <div className="text-center min-w-[48px]">
                                    <p className="font-semibold text-gray-800">{totalStudents}</p>
                                    <p className="text-[10px] text-gray-400">学生</p>
                                  </div>
                                  <div className="w-px h-6 bg-gray-200" />
                                  <div className="text-center min-w-[48px]">
                                    <p
                                      className={cn(
                                        'font-semibold',
                                        totalPending > 0 ? 'text-amber-600' : 'text-gray-800',
                                      )}
                                    >
                                      {totalPending}
                                    </p>
                                    <p className="text-[10px] text-gray-400">待评</p>
                                  </div>
                                  <div className="text-center min-w-[48px]">
                                    <p className="font-semibold text-green-600">{totalGraded}</p>
                                    <p className="text-[10px] text-gray-400">已评</p>
                                  </div>
                                </div>
                                <div className="flex h-7 w-7 items-center justify-center rounded-full bg-gray-50">
                                  {isExpanded ? (
                                    <ChevronUp className="h-4 w-4 text-gray-500" />
                                  ) : (
                                    <ChevronDown className="h-4 w-4 text-gray-500" />
                                  )}
                                </div>
                              </div>
                            </div>
                          </CollapsibleTrigger>
                          <CollapsibleContent>
                            <TaskMethodTabs task={task} />
                          </CollapsibleContent>
                        </Card>
                      </Collapsible>
                    )
                  })}
                </div>
              )}
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-gray-400">
              <BookOpen className="h-12 w-12 mb-3 opacity-50" />
              <p className="text-sm">请在左侧选择一个场景</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// plus-ui/src-portal/views/evaluation/scene-results.vue
<template>
  <div class="scene-results">
    <div class="topbar">
      <h2 class="page-title">场景任务评价</h2>
      <p class="page-sub">选择场景与任务，查看学生提交并进行评分</p>
    </div>

    <div class="layout">
      <!-- 左侧场景列表（按岗位分组） -->
      <div class="side-col">
        <el-input v-model="searchQuery" placeholder="搜索场景..." clearable class="side-search" />
        <div class="scenario-list">
          <template v-for="group in filteredGroups" :key="group.positionName">
            <div class="pos-group-label">{{ group.positionName }}</div>
            <div
              v-for="sc in group.scenarios"
              :key="sc.scenarioId"
              class="scenario-item"
              :class="{ active: selectedScenarioId === sc.scenarioId }"
              @click="selectScenario(sc.scenarioId)"
            >
              <div class="scenario-main">
                <div class="scenario-name">{{ sc.scenarioName }}</div>
                <div class="scenario-code">{{ sc.scenarioCode }}</div>
              </div>
              <div class="scenario-badges">
                <span v-if="sc.pendingCount" class="badge pending">{{ sc.pendingCount }}</span>
                <span v-if="sc.gradedCount" class="badge graded">{{ sc.gradedCount }}</span>
              </div>
            </div>
          </template>
          <el-empty v-if="filteredGroups.length === 0" description="暂无已发布场景" :image-size="60" />
        </div>
      </div>

      <!-- 右侧任务结果 -->
      <div class="main-col">
        <template v-if="selectedScenario">
          <div class="main-header">
            <div>
              <h3 class="scenario-title">{{ selectedScenario.name }}</h3>
              <span class="scenario-count">{{ results.length }} 条提交记录</span>
            </div>
            <div v-if="taskGroups.length">
              <el-button size="small" @click="expandAll">全部展开</el-button>
              <el-button size="small" @click="collapseAll">全部收起</el-button>
            </div>
          </div>

          <el-empty v-if="taskGroups.length === 0" description="该场景下暂无学生提交记录" />
          <el-collapse v-else v-model="expandedTasks" class="task-collapse">
            <el-collapse-item v-for="task in taskGroups" :key="task.taskId" :name="task.taskId">
              <template #title>
                <div class="task-header">
                  <span class="task-name">{{ task.taskName }}</span>
                  <div class="task-stats">
                    <span>学生 {{ task.totalStudents }}</span>
                    <span class="pending">待评 {{ task.totalPending }}</span>
                    <span class="graded">已评 {{ task.totalGraded }}</span>
                    <el-tag v-if="task.totalGraded" size="small" type="info">均分 {{ task.taskScore.toFixed(1) }}</el-tag>
                  </div>
                </div>
              </template>

              <!-- 测评方法 tabs -->
              <el-tabs v-if="task.methods.length" v-model="activeMethod[task.taskId]" class="method-tabs">
                <el-tab-pane v-for="m in task.methods" :key="m.methodKey" :label="methodTabLabel(m)" :name="m.methodKey">
                  <template v-for="s in m.students" :key="s.studentId" class="student-list">
                    <div class="student-row">
                      <div class="student-info">
                        <span class="student-name">{{ s.studentName }}</span>
                        <span class="student-no">{{ s.studentNumber }}</span>
                      </div>
                      <div class="student-score">
                        <span v-if="s.result.status === 'pending'" class="pending">待评分</span>
                        <span v-else-if="s.result.totalScore != null" class="score">得分 {{ s.result.totalScore }}/{{ s.result.maxScore }}</span>
                      </div>
                      <div class="student-actions">
                        <el-button size="small" @click="$router.push(`/evaluation/scene-results/${s.result.id}`)">
                          {{ s.result.status === 'pending' ? '评分' : '查看' }}
                        </el-button>
                        <el-tag v-if="s.result.status !== 'pending'" size="small" type="success">已评分</el-tag>
                      </div>
                    </div>
                  </template>
                </el-tab-pane>
              </el-tabs>
              <el-empty v-else description="暂无学生提交记录" :image-size="50" />
            </el-collapse-item>
          </el-collapse>
        </template>
        <el-empty v-else description="请在左侧选择一个场景" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { scenarioApi, taskApi } from '@/api/scene';
import { positionApi } from '@/api/job';
import { evaluationResultApi } from '@/api/evaluation';
import { userManagementApi } from '@/api/portal';
import { EVAL_METHOD_LABELS_GRADING } from '@/types/lesson';
import type { Scenario } from '@/types/scene';
import type { CareerPosition } from '@/types/job';
import type { User } from '@/types/user';
import type { SceneEvaluationResult } from '@/types/evaluation';

interface TaskStudent {
  studentId: string;
  studentName: string;
  studentNumber: string;
  result: SceneEvaluationResult;
}
interface TaskGroup {
  taskId: string;
  taskName: string;
  totalStudents: number;
  totalPending: number;
  totalGraded: number;
  taskScore: number;
  methods: { methodKey: string; students: TaskStudent[]; pendingCount: number; gradedCount: number; weight: number }[];
}

const searchQuery = ref('');
const selectedScenarioId = ref<string | null>(null);
const scenarios = ref<Scenario[]>([]);
const results = ref<SceneEvaluationResult[]>([]);
const userMap = ref(new Map<string, User>());
const taskMap = ref(new Map<string, { id: string; name: string; evalData?: any }>());
const expandedTasks = ref<string[]>([]);
const activeMethod = reactive<Record<string, string>>({});
const loading = ref(true);

const scenarioGroups = computed(() => {
  const map = new Map<string, { positionName: string; scenarios: any[] }>();
  for (const s of scenarios.value) {
    const subs = s.id === selectedScenarioId.value ? results.value.filter((r) => r.taskId) : [];
    const item = {
      scenarioId: s.id,
      scenarioName: s.name,
      scenarioCode: s.code || '',
      pendingCount: subs.filter((r) => r.status === 'pending').length,
      gradedCount: subs.filter((r) => r.status === 'evaluated').length
    };
    const pos = (s as any).positionName || '未分类';
    if (!map.has(pos)) map.set(pos, { positionName: pos, scenarios: [] });
    map.get(pos)!.scenarios.push(item);
  }
  return Array.from(map.values());
});
const filteredGroups = computed(() => {
  const q = searchQuery.value.trim().toLowerCase();
  if (!q) return scenarioGroups.value;
  return scenarioGroups.value
    .map((g) => ({ ...g, scenarios: g.scenarios.filter((s) => s.scenarioName.toLowerCase().includes(q) || s.scenarioCode.toLowerCase().includes(q)) }))
    .filter((g) => g.scenarios.length > 0);
});
const selectedScenario = computed(() => scenarios.value.find((s) => s.id === selectedScenarioId.value) || null);

const taskGroups = computed<TaskGroup[]>(() => {
  const map = new Map<string, TaskGroup>();
  for (const sub of results.value) {
    const user = userMap.value.get(sub.evaluateeId);
    const student: TaskStudent = {
      studentId: sub.evaluateeId,
      studentName: user?.name || '未知',
      studentNumber: user?.studentNo || '-',
      result: sub
    };
    const taskInfo = taskMap.value.get(sub.taskId);
    const existing = map.get(sub.taskId);
    if (existing) {
      const method = existing.methods.find((m) => m.methodKey === sub.methodKey);
      if (method) {
        method.students.push(student);
        method.pendingCount += sub.status === 'pending' ? 1 : 0;
        method.gradedCount += sub.status === 'evaluated' ? 1 : 0;
      } else {
        existing.methods.push({ methodKey: sub.methodKey, students: [student], pendingCount: sub.status === 'pending' ? 1 : 0, gradedCount: sub.status === 'evaluated' ? 1 : 0, weight: 100 });
      }
    } else {
      map.set(sub.taskId, {
        taskId: sub.taskId,
        taskName: taskInfo?.name || sub.taskId,
        totalStudents: 0,
        totalPending: 0,
        totalGraded: 0,
        taskScore: 0,
        methods: [{ methodKey: sub.methodKey, students: [student], pendingCount: sub.status === 'pending' ? 1 : 0, gradedCount: sub.status === 'evaluated' ? 1 : 0, weight: 100 }]
      });
    }
  }
  map.forEach((g) => {
    g.totalStudents = new Set(results.value.filter((r) => r.taskId === g.taskId).map((r) => r.evaluateeId)).size;
    g.totalPending = g.methods.reduce((s, m) => s + m.pendingCount, 0);
    g.totalGraded = g.methods.reduce((s, m) => s + m.gradedCount, 0);
    // 任务均分：各测评方式加权
    let weighted = 0;
    let totalWeight = 0;
    for (const m of g.methods) {
      const graded = m.students.filter((s) => s.result.status === 'evaluated');
      if (!graded.length) continue;
      const methodScore = graded.reduce((acc, s) => acc + ((s.result.totalScore ?? 0) / (s.result.maxScore || 1)) * 100, 0) / graded.length;
      weighted += methodScore * (m.weight || 0);
      totalWeight += m.weight || 0;
    }
    g.taskScore = totalWeight > 0 ? weighted / totalWeight : 0;
  });
  return Array.from(map.values());
});

function methodTabLabel(m: { methodKey: string; pendingCount: number; gradedCount: number }) {
  const label = EVAL_METHOD_LABELS_GRADING[m.methodKey] || m.methodKey;
  return `${label}${m.pendingCount ? ` 待评${m.pendingCount}` : ''}${m.gradedCount ? ` 已评${m.gradedCount}` : ''}`;
}
function expandAll() { expandedTasks.value = taskGroups.value.map((t) => t.taskId); }
function collapseAll() { expandedTasks.value = []; }

async function load() {
  loading.value = true;
  try {
    const [scRes, userRes, posRes] = await Promise.all([
      scenarioApi.list({ limit: 200 }),
      userManagementApi.list({ limit: 1000 }),
      positionApi.list({ limit: 500 })
    ]);
    const pMap = new Map<string, string>();
    (posRes.items || []).forEach((p: CareerPosition) => pMap.set(p.id, p.name));
    scenarios.value = (scRes.items || [])
      .filter((s) => s.status === 'published')
      .map((s) => ({ ...s, positionName: pMap.get(s.careerPositionId || '') || '未分类' } as any));
    if (!selectedScenarioId.value) selectedScenarioId.value = scenarios.value[0]?.id || null;
    const m = new Map<string, User>();
    (userRes.items || []).forEach((u) => m.set(u.id, u));
    userMap.value = m;
  } catch {
    /* ignore */
  } finally {
    loading.value = false;
  }
}

async function selectScenario(id: string) {
  selectedScenarioId.value = id;
  results.value = [];
  taskMap.value = new Map();
  try {
    // 分页全量拉取结果 + 任务
    const allResults: SceneEvaluationResult[] = [];
    let offset = 0;
    const ps = 200;
    for (;;) {
      const r = await evaluationResultApi.list({ sceneId: id, limit: ps, offset });
      allResults.push(...r.items);
      if (r.items.length < ps || offset + ps >= (r.total || 0)) break;
      offset += ps;
    }
    const tasks: any[] = [];
    offset = 0;
    for (;;) {
      const r = await taskApi.list({ scenarioId: id, limit: ps, offset });
      tasks.push(...(r.items || []));
      if ((r.items || []).length < ps || offset + ps >= (r.total || 0)) break;
      offset += ps;
    }
    results.value = allResults;
    const tMap = new Map<string, any>();
    tasks.forEach((t) => { tMap.set(t.id, t); activeMethod[t.id] = ''; });
    taskMap.value = tMap;
  } catch {
    results.value = [];
    taskMap.value = new Map();
  }
}

onMounted(async () => {
  await load();
  if (selectedScenarioId.value) await selectScenario(selectedScenarioId.value);
});
</script>

<style scoped>
.scene-results { padding: 16px; height: calc(100vh - 90px); display: flex; flex-direction: column; }
.topbar { margin-bottom: 12px; }
.page-title { font-size: 20px; font-weight: 700; margin: 0; }
.page-sub { color: #909399; margin: 8px 0 0; }
.layout { flex: 1; display: flex; gap: 16px; overflow: hidden; }
.side-col { width: 300px; flex-shrink: 0; background: #fff; border-radius: 8px; padding: 12px; display: flex; flex-direction: column; }
.side-search { margin-bottom: 8px; }
.scenario-list { flex: 1; overflow-y: auto; }
.pos-group-label { font-size: 11px; color: #909399; text-transform: uppercase; padding: 8px 2px 4px; font-weight: 600; }
.scenario-item { display: flex; align-items: center; justify-content: space-between; padding: 10px 12px; border-radius: 8px; cursor: pointer; margin-bottom: 4px; border: 1px solid transparent; }
.scenario-item:hover { background: #f5f7fa; }
.scenario-item.active { background: #ecf5ff; border-color: #409eff; }
.scenario-name { font-size: 13px; font-weight: 600; color: #303133; }
.scenario-item.active .scenario-name { color: #409eff; }
.scenario-code { font-size: 11px; color: #909399; }
.scenario-badges { display: flex; gap: 4px; }
.badge { font-size: 10px; padding: 1px 6px; border-radius: 10px; }
.badge.pending { background: #fdf6ec; color: #e6a23c; }
.badge.graded { background: #f0f9eb; color: #67c23a; }
.main-col { flex: 1; overflow-y: auto; background: #fff; border-radius: 8px; padding: 16px; }
.main-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
.scenario-title { font-size: 16px; font-weight: 700; margin: 0; }
.scenario-count { color: #909399; font-size: 12px; }
.task-collapse { border: none; }
.task-header { display: flex; align-items: center; justify-content: space-between; flex: 1; padding-right: 12px; }
.task-name { font-weight: 600; }
.task-stats { display: flex; gap: 10px; align-items: center; color: #909399; font-size: 12px; }
.pending { color: #e6a23c; }
.graded { color: #67c23a; }
.method-tabs { margin-top: 4px; }
.student-row { display: flex; align-items: center; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #fafafa; }
.student-info { display: flex; align-items: center; gap: 8px; min-width: 0; }
.student-name { font-weight: 500; }
.student-no { color: #909399; font-size: 12px; }
.student-score .score { color: #606266; font-size: 12px; }
.student-actions { display: flex; align-items: center; gap: 8px; }
</style>
