// plus-ui/src-portal/views/portal/login.vue
<template>
  <div class="portal-login-page">
    <div class="decor">
      <div class="blob blob-1" />
      <div class="blob blob-2" />
      <div class="blob blob-3" />
    </div>

    <div class="login-panel">
      <router-link to="/changelog" class="changelog-link" title="查看平台更新记录">
        <el-icon><Clock /></el-icon>
        <span>更新记录</span>
      </router-link>

      <div class="brand-area">
        <h1 class="brand-title">场景化数智教学服务平台</h1>
      </div>

      <el-card shadow="never" class="login-card">
        <div class="login-heading">
          <h2 class="login-title">账号登录</h2>
          <p class="login-subtitle">使用学校分配的账号登录系统</p>
        </div>

        <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon class="error-alert" />

        <el-form label-position="top" @submit.prevent="handleSubmit">
          <el-form-item label="账号">
            <el-input v-model="username" placeholder="请输入账号" autocomplete="username" />
          </el-form-item>
          <el-form-item label="密码">
            <el-input
              v-model="password"
              type="password"
              placeholder="请输入密码"
              autocomplete="current-password"
              show-password
              @keyup.enter="handleSubmit"
            />
          </el-form-item>

          <el-form-item v-if="captchaRequired" label="验证码">
            <div class="captcha-row">
              <el-input
                v-model="captchaCode"
                placeholder="请输入验证码"
                maxlength="6"
                autocomplete="off"
                @keyup.enter="handleSubmit"
              />
              <img
                v-if="captcha?.image"
                :src="captcha.image"
                alt="验证码"
                class="captcha-img"
                title="点击刷新验证码"
                @click="loadCaptcha"
              />
              <div v-else class="captcha-loading">验证码加载中...</div>
            </div>
            <div class="captcha-tip">点击图片可刷新验证码</div>
          </el-form-item>

          <el-form-item>
            <el-button type="primary" size="large" class="submit-btn" :loading="loading" @click="handleSubmit">
              {{ loading ? '登录中...' : '登 录' }}
            </el-button>
          </el-form-item>
        </el-form>

        <div v-if="isDev" class="dev-accounts">
          <p class="dev-title">测试账号（仅开发环境显示）：</p>
          <ul>
            <li>学校管理员：school / school123</li>
            <li>教师：teacher / teacher123</li>
            <li>学生：student / student123</li>
          </ul>
        </div>
      </el-card>

      <p class="copyright">
        版权所有 © 2020-2026 杭州知与未来科技有限公司 ｜ 软件著作权登记号：2020SR0123456 ｜ 京ICP备2025105397号-1
      </p>
    </div>

    <el-dialog v-model="showTenantSelect" title="选择租户" width="420px" :close-on-click-modal="false">
      <p class="tenant-tip">您的账号关联了多个学校，请选择要登录的学校</p>
      <div class="tenant-list">
        <button
          v-for="opt in tenantOptions"
          :key="opt.tenantId"
          type="button"
          class="tenant-item"
          :disabled="selectingTenant"
          @click="handleSelectTenant(opt.tenantId)"
        >
          <span class="tenant-name">{{ opt.tenantName }}</span>
          <span class="tenant-id">{{ opt.tenantId }}</span>
        </button>
      </div>
      <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon style="margin-top: 12px" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { setToken, removeToken } from '@/api/http';
import { authApi } from '@/api/auth';
import type { CaptchaData, LoginResponse, TenantOption } from '@/api/auth';
import { useAuthStore } from '@/stores/auth';
import { getDeviceId } from '@/utils/device';

interface RoleInfo {
  id: string;
  code: string;
}

const ROLE_PRIORITY = ['school_admin', 'teacher', 'student', 'enterprise_mentor'];
const STORAGE_PREFIX = 'zhiyu-active-role:';

function resolveActiveRole(userId: string | undefined, roles: RoleInfo[] | undefined): RoleInfo | undefined {
  if (!roles || roles.length === 0) return undefined;
  if (userId) {
    try {
      const saved = localStorage.getItem(STORAGE_PREFIX + userId);
      if (saved) {
        const found = roles.find((r) => r.id === saved);
        if (found) return found;
      }
    } catch {
      // ignore storage errors
    }
  }
  for (const code of ROLE_PRIORITY) {
    const found = roles.find((r) => r.code === code);
    if (found) return found;
  }
  return roles[0];
}

function getPostLoginPath(roleCode?: string): string {
  switch (roleCode) {
    case 'school_admin':
      return '/portal/apps';
    case 'teacher':
    case 'student':
      return '/portal/workspace';
    default:
      return '/portal';
  }
}

const router = useRouter();
const auth = useAuthStore();

const isDev = import.meta.env.DEV;

const username = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

const tenantOptions = ref<TenantOption[]>([]);
let preAuthToken = '';
const showTenantSelect = ref(false);
const selectingTenant = ref(false);

const captchaRequired = ref(false);
const captcha = ref<CaptchaData | null>(null);
const captchaCode = ref('');

async function loadCaptcha() {
  try {
    captcha.value = await authApi.captcha();
  } catch (e) {
    captcha.value = null;
    error.value = (e as Error).message || '验证码加载失败';
  }
  captchaCode.value = '';
}

async function doLogin(token: string) {
  setToken(token, 'portal');
  auth.token = token;
  try {
    const me = await auth.fetchMe();
    const roles = (me.roles ?? []) as unknown as RoleInfo[];
    const activeRole = resolveActiveRole(me.user?.id, roles);
    await router.replace(getPostLoginPath(activeRole?.code));
  } catch (e) {
    removeToken('portal');
    auth.token = '';
    auth.user = null;
    throw e;
  }
}

async function handleSelectTenant(tenantId: string) {
  selectingTenant.value = true;
  try {
    const res = await authApi.selectTenant({ preAuthToken, tenantId });
    await doLogin(res.token);
  } catch (e) {
    error.value = (e as Error).message || '选择租户失败';
    showTenantSelect.value = false;
  } finally {
    selectingTenant.value = false;
  }
}

async function handleSubmit() {
  error.value = '';
  if (!username.value || !password.value) {
    error.value = '请输入账号和密码';
    return;
  }
  if (captchaRequired.value && !captchaCode.value.trim()) {
    error.value = '请先输入验证码';
    return;
  }
  loading.value = true;
  try {
    const res: LoginResponse = await authApi.portalLogin({
      username: username.value,
      password: password.value,
      deviceId: getDeviceId(),
      ...(captchaRequired.value && captcha.value && captchaCode.value.trim()
        ? { captchaId: captcha.value.captchaId, captchaCode: captchaCode.value.trim() }
        : {})
    });
    if (res.needsTenantSelection && res.preAuthToken && res.tenants) {
      tenantOptions.value = res.tenants;
      preAuthToken = res.preAuthToken;
      showTenantSelect.value = true;
      loading.value = false;
      return;
    }
    await doLogin(res.token);
  } catch (e) {
    // http.ts 只透传 error 文案、丢弃 code，故按后端稳定文案区分验证码错误
    const msg = (e as Error).message || '';
    if (msg === '请完成验证码') {
      captchaRequired.value = true;
      await loadCaptcha();
      error.value = '请先输入验证码后再登录';
    } else if (msg === '验证码不正确，请重试') {
      await loadCaptcha();
      error.value = '验证码不正确，请重试';
    } else {
      error.value = msg || '登录失败';
    }
    loading.value = false;
  }
}
</script>

<style scoped>
.portal-login-page {
  position: relative;
  min-height: 100vh;
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding: 48px 16px;
  background: linear-gradient(135deg, #f6f9ff 0%, #f7f9fc 50%, #eef3fb 100%);
  overflow: hidden;
}
.decor { position: absolute; inset: 0; pointer-events: none; }
.blob { position: absolute; border-radius: 50%; filter: blur(60px); background: rgba(64, 158, 255, 0.12); }
.blob-1 { width: 420px; height: 420px; top: -120px; left: -120px; }
.blob-2 { width: 420px; height: 420px; bottom: -120px; right: -120px; }
.blob-3 { width: 220px; height: 220px; top: 40%; left: 55%; background: rgba(64, 158, 255, 0.08); }
.login-panel { position: relative; width: 100%; max-width: 440px; }
.changelog-link {
  position: absolute;
  top: 0;
  right: 0;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 6px 10px;
  border: 1px solid #e6ebf3;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.8);
  font-size: 12px;
  color: #8a94a6;
  text-decoration: none;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
  transition: all 0.2s;
}
.changelog-link:hover {
  border-color: rgba(64, 158, 255, 0.4);
  color: #409eff;
}
.brand-area {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  margin-bottom: 28px;
}
.brand-title {
  margin: 0;
  font-size: 24px;
  font-weight: 700;
  letter-spacing: 0.5px;
  background: linear-gradient(90deg, #409eff, #66b1ff);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
.login-card {
  border-radius: 14px;
  border: 1px solid #e8ecf3;
  padding: 8px 12px;
  box-shadow: 0 16px 40px -20px rgba(64, 158, 255, 0.4);
}
.login-heading { text-align: center; margin-bottom: 16px; }
.login-title { margin: 0; font-size: 18px; font-weight: 600; color: #333; }
.login-subtitle { margin: 4px 0 0; font-size: 12px; color: #98a2b3; }
.error-alert { margin-bottom: 14px; }
.submit-btn { width: 100%; }
.captcha-row { display: flex; gap: 8px; width: 100%; align-items: center; }
.captcha-img {
  height: 40px;
  width: 110px;
  cursor: pointer;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  flex-shrink: 0;
  object-fit: cover;
}
.captcha-loading {
  height: 40px;
  width: 110px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  font-size: 12px;
  color: #c0c4cc;
}
.captcha-tip { margin-top: 4px; font-size: 12px; color: #c0c4cc; line-height: 1.4; }
.dev-accounts {
  margin-top: 16px;
  padding: 12px;
  border: 1px dashed #e6ebf3;
  border-radius: 8px;
  background: #fafbfc;
  font-size: 12px;
  color: #c0c4cc;
}
.dev-title { margin: 0 0 4px; color: #909399; font-weight: 500; }
.dev-accounts ul { margin: 0; padding-left: 16px; line-height: 1.8; }
.copyright {
  margin-top: 24px;
  padding: 0 16px;
  text-align: center;
  font-size: 12px;
  line-height: 1.6;
  color: #c0c4cc;
}
.tenant-tip { color: #606266; margin: 0 0 12px; line-height: 1.6; }
.tenant-list { display: flex; flex-direction: column; gap: 8px; }
.tenant-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px 14px;
  border: 1px solid #e4e7ed;
  border-radius: 6px;
  cursor: pointer;
  background: #fff;
  font-size: 14px;
  color: #303133;
  transition: all 0.2s;
}
.tenant-item:hover:not(:disabled) { border-color: #409eff; color: #409eff; }
.tenant-item:disabled { cursor: not-allowed; opacity: 0.6; }
.tenant-name { font-weight: 500; }
.tenant-id { font-size: 12px; color: #c0c4cc; }
</style>

// frontend/edu/app/portal/login/page.tsx
'use client'

import { useState } from 'react'
import { Link } from 'react-router'
import { useNavigate } from 'react-router'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { PasswordInput } from '@zhiyu/ui'
import { Label } from '@/components/ui/label'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import { AlertCircle, User, Lock, Building2, History } from 'lucide-react'
import { authApi, setToken, removeToken, getDeviceId } from '@/lib/api'
import type { TenantOption } from '@/lib/api'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { useAuth } from '@/components/auth-provider'
import { useT } from '@/lib/i18n/locale-provider'
import { resolveActiveRole } from '@/lib/active-role'
import CaptchaInput from '@/components/shared/captcha-input'

function getPostLoginPath(roleCode?: string): string {
  switch (roleCode) {
    case 'school_admin':
      return '/portal/apps'
    case 'teacher':
    case 'student':
      return '/portal/workspace'
    default:
      return '/portal'
  }
}

export default function PortalLoginPage() {
  const t = useT()
  const navigate = useNavigate()
  const { refresh } = usePortalAuth()
  const { refresh: refreshRootAuth } = useAuth()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [tenantOptions, setTenantOptions] = useState<TenantOption[]>([])
  const [preAuthToken, setPreAuthToken] = useState('')
  const [showTenantSelect, setShowTenantSelect] = useState(false)
  const [selectingTenant, setSelectingTenant] = useState(false)
  // 防爆破验证码：后端返回 captcha_required 后展示，输入完成后随登录请求提交
  const [captchaRequired, setCaptchaRequired] = useState(false)
  const [captchaAnswer, setCaptchaAnswer] = useState<{ id: string; code: string } | null>(null)
  const [captchaVersion, setCaptchaVersion] = useState(0)

  const handleCaptchaPass = (captchaId: string, code: string) => {
    setCaptchaAnswer({ id: captchaId, code })
  }

  const refreshCaptcha = () => {
    setCaptchaVersion((v) => v + 1)
    setCaptchaAnswer(null)
  }

  const doLogin = async (token: string) => {
    setToken(token, 'portal')
    try {
      await Promise.all([refresh(), refreshRootAuth()])
      const me = await authApi.portalMe()
      const activeRole = resolveActiveRole(me.user?.id, me.roles)
      navigate(getPostLoginPath(activeRole?.code), { replace: true })
    } catch (err) {
      // 会话校验失败：清除刚写入的 token，避免"已登录但停在登录页"的中间态
      removeToken('portal')
      throw err
    }
  }

  const handleSelectTenant = async (tenantId: string) => {
    setSelectingTenant(true)
    try {
      const res = await authApi.selectTenant({ preAuthToken, tenantId })
      await doLogin(res.token)
    } catch (err: any) {
      setError(err.message || t('选择租户失败'))
      setShowTenantSelect(false)
    } finally {
      setSelectingTenant(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')

    if (captchaRequired && !captchaAnswer) {
      setError(t('请先输入验证码'))
      return
    }

    setLoading(true)

    try {
      const res = await authApi.portalLogin({
        username,
        password,
        deviceId: getDeviceId(),
        ...(captchaAnswer
          ? { captchaId: captchaAnswer.id, captchaCode: captchaAnswer.code }
          : {}),
      })
      if (res.needsTenantSelection && res.preAuthToken && res.tenants) {
        setTenantOptions(res.tenants)
        setPreAuthToken(res.preAuthToken)
        setShowTenantSelect(true)
        setLoading(false)
        return
      }
      await doLogin(res.token)
    } catch (err: any) {
      // 后端要求验证码：展示输入框并提示；验证码错误：刷新验证码
      if (err?.code === 'captcha_required') {
        // 验证码已消费/过期：刷新验证码并清空已填字符（否则旧 id 永远校验失败）
        refreshCaptcha()
        setCaptchaRequired(true)
        setError(t('请先输入验证码后再登录'))
      } else if (err?.code === 'captcha_wrong') {
        refreshCaptcha()
        setError(t('验证码不正确，请重试'))
      } else {
        setError(err.message || t('登录失败'))
      }
      setLoading(false)
    }
  }

  return (
    <div className="relative flex min-h-screen items-start justify-center overflow-hidden bg-gradient-to-br from-[#f6f9ff] via-[#f7f9fc] to-[#eef3fb] p-4 pt-12 sm:pt-16">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -left-40 -top-40 h-[560px] w-[560px] rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute -bottom-40 -right-40 h-[560px] w-[560px] rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute left-1/3 top-1/2 h-64 w-64 rounded-full bg-primary/5 blur-3xl" />
        <div className="absolute left-1/4 top-1/4 h-32 w-32 rounded-full bg-cyan-500/10 blur-2xl" />
        <svg
          className="absolute left-1/3 top-1/3 h-96 w-96 text-primary/5"
          viewBox="0 0 200 200"
          fill="none"
        >
          <polygon points="100,0 200,100 100,200 0,100" />
        </svg>
        <svg
          className="absolute bottom-1/4 right-1/4 h-48 w-48 text-primary/5"
          viewBox="0 0 200 200"
          fill="none"
        >
          <polygon points="100,20 180,100 100,180 20,100" />
        </svg>
      </div>

      <div className="relative w-full max-w-md">
        <div className="relative mb-8 flex flex-col items-center gap-4">
          <div className="absolute right-0 top-0">
            <Link
              to="/changelog"
              title={t('查看平台更新记录')}
              className="group flex items-center gap-0 rounded-full border border-[#e6ebf3] bg-white/80 px-2.5 py-1.5 text-xs text-[#8a94a6] shadow-sm backdrop-blur transition-all hover:gap-1 hover:border-primary/30 hover:bg-white hover:text-primary"
            >
              <History className="h-3.5 w-3.5 shrink-0" />
              <span className="max-w-0 overflow-hidden whitespace-nowrap opacity-0 transition-all duration-200 group-hover:max-w-[8rem] group-hover:opacity-100">
                {t('查看平台更新记录')}
              </span>
            </Link>
          </div>
          <img
            src="/logo.png?v=2"
            alt="知育"
            width={369}
            height={139}
            className="h-16 w-auto object-contain drop-shadow-sm"
          />
          <div className="flex flex-col items-center gap-1.5">
            <h1 className="bg-gradient-to-r from-primary via-primary to-primary/60 bg-clip-text text-2xl sm:text-[26px] font-bold tracking-wide text-transparent">
              {t('场景化数智教学服务平台')}
            </h1>
          </div>
        </div>

        <Card className="relative overflow-hidden rounded-2xl border border-[#e8ecf3] bg-white/95 shadow-[0_24px_70px_-28px] shadow-primary/25 backdrop-blur-xl">
          <div className="absolute left-0 right-0 top-0 h-1 bg-gradient-to-r from-primary via-primary/70 to-primary/30" />
          <CardContent className="px-6 py-8 sm:px-9 sm:py-9">
            <div className="mb-7 flex flex-col items-center gap-1.5">
              <h2 className="text-lg font-semibold text-[#333]">{t('账号登录')}</h2>
              <p className="text-xs text-[#98a2b3]">{t('使用学校分配的账号登录系统')}</p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="space-y-1.5">
                <Label htmlFor="username" className="text-sm font-medium text-slate-600">
                  {t('账号')}
                </Label>
                <div className="relative">
                  <User className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                  <Input
                    id="username"
                    placeholder={t('请输入账号')}
                    className="h-11 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm transition-all placeholder:text-slate-400 hover:border-slate-300 focus-visible:border-primary/60 focus-visible:bg-white focus-visible:ring-primary/20"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    autoComplete="username"
                    required
                  />
                </div>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="password" className="text-sm font-medium text-slate-600">
                  {t('密码')}
                </Label>
                <div className="relative">
                  <Lock className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                  <PasswordInput
                    id="password"
                    placeholder={t('请输入密码')}
                    className="h-11 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm transition-all placeholder:text-slate-400 hover:border-slate-300 focus-visible:border-primary/60 focus-visible:bg-white focus-visible:ring-primary/20"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    autoComplete="current-password"
                    required
                  />
                </div>
              </div>

              {captchaRequired && (
                <CaptchaInput
                  key={captchaVersion}
                  onPass={handleCaptchaPass}
                  onError={() => setCaptchaRequired(true)}
                />
              )}

              {error && (
                <div className="flex items-center gap-2 rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">
                  <AlertCircle className="h-4 w-4 shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              <Button
                type="submit"
                className="h-11 w-full rounded-lg bg-gradient-to-r from-primary via-primary to-primary/80 text-base shadow-lg shadow-primary/30 transition-all hover:-translate-y-px hover:shadow-xl hover:shadow-primary/30 active:translate-y-0 disabled:translate-y-0"
                disabled={loading}
                size="lg"
              >
                {loading ? t('登录中...') : t('登 录')}
              </Button>
            </form>

            {process.env.NODE_ENV !== 'production' && (
              <div className="mt-6 rounded-xl border border-dashed border-[#e6ebf3] bg-[#fafbfc] p-3.5 text-xs text-slate-400">
                <p className="mb-1 font-medium text-slate-500">
                  {t('测试账号（仅开发环境显示）：')}
                </p>
                <ul className="space-y-0.5">
                  <li>{t('学校管理员：school / school123')}</li>
                  <li>{t('教师：teacher / teacher123')}</li>
                  <li>{t('学生：student / student123')}</li>
                </ul>
              </div>
            )}
          </CardContent>
        </Card>

        <p className="mt-7 px-6 text-center text-xs leading-relaxed text-slate-400">
          {t('版权所有 © 2020-2026 杭州知与未来科技有限公司 ｜ 软件著作权登记号：2020SR0123456 ｜ 京ICP备2025105397号-1')}
        </p>
      </div>

      <Dialog open={showTenantSelect} onOpenChange={setShowTenantSelect}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t('选择租户')}</DialogTitle>
            <DialogDescription>{t('您的账号关联了多个学校，请选择要登录的学校')}</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-2 py-4">
            {tenantOptions.map((t) => (
              <Button
                key={t.tenantId}
                variant="outline"
                className="justify-start gap-3 h-auto py-4"
                onClick={() => handleSelectTenant(t.tenantId)}
                disabled={selectingTenant}
              >
                <Building2 className="h-5 w-5 text-primary shrink-0" />
                <div className="text-left">
                  <div className="font-medium">{t.tenantName}</div>
                  <div className="text-xs text-muted-foreground">{t.tenantId}</div>
                </div>
              </Button>
            ))}
          </div>
          {error && (
            <div className="flex items-center gap-2 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
              <AlertCircle className="h-4 w-4 shrink-0" />
              {error}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
