// frontend/portal-vue/src/views/portal/apps/alliance/achievements.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div>
        <h1 class="page-title">合作成果管理</h1>
        <p class="page-sub">管理校企合作产出的各类成果</p>
      </div>
      <el-button type="primary" @click="router.push('/portal/apps/alliance/achievements/new')">
        <el-icon><Plus /></el-icon>
        新建成果
      </el-button>
    </div>

    <el-card shadow="never">
      <el-input
        v-model="search"
        placeholder="搜索成果名称..."
        clearable
        style="max-width: 320px; margin-bottom: 12px"
        @input="onSearch"
        @clear="onSearch"
      />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="成果名称" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" @click="router.push(`/portal/apps/alliance/achievements/${row.id}`)">
              {{ row.title }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="前台展示" width="100">
          <template #default="{ row }">
            <el-switch :model-value="row.isPublic || false" @change="togglePublic(row)" />
          </template>
        </el-table-column>
        <el-table-column label="合作企业" min-width="160" show-overflow-tooltip>
          <template #default="{ row }">{{ enterpriseNames(row) }}</template>
        </el-table-column>
        <el-table-column label="关联项目" min-width="140" show-overflow-tooltip>
          <template #default="{ row }">{{ projectName(row) }}</template>
        </el-table-column>
        <el-table-column label="类型" width="120">
          <template #default="{ row }">{{ typeLabel(row.type) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/achievements/${row.id}`)">查看</el-button>
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/achievements/${row.id}/edit`)">编辑</el-button>
            <el-button link type="danger" size="small" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import {
  achievementApi,
  listAllEnterprises,
  listAllProjects,
  fetchAllianceDict,
  allianceLabel,
  type AllianceAchievement,
  type AllianceEnterprise,
  type AllianceProject,
} from './crud-shared';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');
const router = useRouter();

const items = ref<AllianceAchievement[]>([]);
const loading = ref(false);
const search = ref('');
const page = ref(1);
const pageSize = 20;
const total = ref(0);
const enterprises = ref<AllianceEnterprise[]>([]);
const projects = ref<AllianceProject[]>([]);
const typeDict = ref<{ code: string; name: string }[]>([]);

async function loadRefs() {
  try {
    const [ents, projs] = await Promise.all([listAllEnterprises(), listAllProjects()]);
    enterprises.value = ents;
    projects.value = projs;
  } catch {
    // 名称映射失败仅退化为原始 id，不阻塞列表
  }
}

function typeLabel(v?: string): string {
  const d = typeDict.value.find((x) => x.code === v);
  if (d) return d.name;
  return allianceLabel('achievementType', v);
}

function enterpriseNames(row: AllianceAchievement): string {
  const ids = (row.enterpriseIds || []).map(String);
  if (ids.length === 0) return '-';
  return ids
    .map((eid) => enterprises.value.find((e) => e.id === eid)?.name || eid)
    .join('、');
}

function projectName(row: AllianceAchievement): string {
  const pid = (row.projectIds || [])[0];
  if (!pid) return '-';
  return projects.value.find((p) => p.id === pid)?.name || '-';
}

async function loadItems() {
  loading.value = true;
  try {
    const res = await achievementApi.list({
      search: search.value.trim() || undefined,
      limit: pageSize,
      offset: (page.value - 1) * pageSize,
    });
    items.value = res.items;
    total.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSearch() {
  page.value = 1;
  loadItems();
}

async function togglePublic(row: AllianceAchievement) {
  const next = !row.isPublic;
  try {
    await achievementApi.update(row.id, { ...row, isPublic: next });
    row.isPublic = next;
    ElMessage.success(next ? '已开启前台展示' : '已取消前台展示');
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: AllianceAchievement) {
  try {
    await ElMessageBox.confirm(`确定要删除成果「${row.title}」吗？`, '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    });
  } catch {
    return;
  }
  try {
    await achievementApi.delete(row.id);
    ElMessage.success('成果已删除');
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(async () => {
  if (!auth.user) {
    try {
      await auth.fetchMe();
    } catch {
      // 未登录态由路由守卫兜底，此处忽略
    }
  }
  loadRefs();
  fetchAllianceDict('achievement_type').then((list) => {
    typeDict.value = list.map((d) => ({ code: d.code, name: d.name }));
  });
  loadItems();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.page-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 16px; }
.page-title { margin: 0; font-size: 20px; font-weight: 600; }
.page-sub { margin: 4px 0 0; font-size: 13px; color: #909399; }
.pagination { margin-top: 16px; justify-content: flex-end; }
</style>

// apps/edu/app/portal/apps/alliance/achievements/page.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Pencil, Trash2, ExternalLink } from 'lucide-react'
import Link from 'next/link'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceAchievementApi, allianceEnterpriseApi, allianceProjectApi } from '@/lib/api'
import { useToast } from '@zhiyu/ui'
import { allianceLabel } from '@zhiyu/shared-types'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { FormFieldRow } from '@/components/shared/form-field-row'
import { formatDate } from '@/lib/format-utils'
import { Switch } from '@/components/ui/switch'
import type { AllianceAchievement, AllianceEnterprise, AllianceProject } from '@/lib/types'

export default function AllianceAchievementsPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const [items, setItems] = useState<AllianceAchievement[]>([])
  const [enterprises, setEnterprises] = useState<AllianceEnterprise[]>([])
  const [projects, setProjects] = useState<AllianceProject[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchItems = useCallback(async () => {
    if (!tenantId) return
    setLoading(true)
    setError(null)
    try {
      const [data, ents, projs] = await Promise.all([
        allianceAchievementApi.list(),
        allianceEnterpriseApi.list({ limit: 200 }),
        allianceProjectApi.list({ limit: 200 }),
      ])
      setItems(data.items || [])
      setEnterprises(ents.items || [])
      setProjects(projs.items || [])
    } catch (e: any) {
      setError(e.message || '加载失败')
    } finally {
      setLoading(false)
    }
  }, [tenantId])

  useEffect(() => {
    if (authLoading || !tenantId) return
    // 首屏加载：async IIFE 包裹，避免在 effect 体内同步触发 setState
    ;(async () => {
      await fetchItems()
    })()
  }, [tenantId, authLoading, fetchItems])

  return (
    <PortalCrudPage
      title="合作成果管理"
      description="管理校企合作产出的各类成果"
      entityLabel="合作成果"
      searchPlaceholder="搜索成果名称..."
      createButtonLabel="新增成果"
      items={items}
      loading={loading}
      error={error}
      onRetry={fetchItems}
      filterItems={(filtered, search) =>
        filtered.filter((a) => !search || a.title.toLowerCase().includes(search.toLowerCase()))
      }
      importConfig={{
        importType: 'alliance-achievements',
        entityLabel: '合作成果',
        templateFileName: '合作成果批量导入模板.xlsx',
      }}
      createHref="/portal/apps/alliance/achievements/new"
      colSpan={8}
      renderTableHeader={() => (
        <>
          <TableHead>成果名称</TableHead>
          <TableHead>前台展示</TableHead>
          <TableHead>合作企业</TableHead>
          <TableHead>关联项目</TableHead>
          <TableHead>类型</TableHead>
          <TableHead>发布时间</TableHead>
          <TableHead>创建人</TableHead>
          <TableHead>操作</TableHead>
        </>
      )}
      renderTableRow={(item: any, actions: any) => {
        const entIds: string[] = (item.enterpriseIds || []).map(String)
        const project = projects.find((p) => p.id === (item.projectIds || [])[0])
        return (
          <>
            <TableCell className="font-medium">
              <Link
                href={`/portal/apps/alliance/achievements/${item.id}`}
                className="hover:underline"
              >
                {item.title}
              </Link>
            </TableCell>
            <TableCell>
              <Switch checked={item.isPublic || false} onCheckedChange={actions.toggle} />
            </TableCell>
            <TableCell className="max-w-[160px]">
              {entIds.length > 0
                ? entIds.map((eid) => enterprises.find((e) => e.id === eid)?.name || eid).join('、')
                : '-'}
            </TableCell>
            <TableCell>{project?.name || '-'}</TableCell>
            <TableCell>{allianceLabel('achievementType', item.type)}</TableCell>
            <TableCell>{formatDate(item.achievementDate)}</TableCell>
            <TableCell>{item.createdBy || '-'}</TableCell>
            <TableRowActions>
              <Link href={`/portal/apps/alliance/achievements/${item.id}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="h-3.5 w-3.5 mr-1" />
                  查看
                </Button>
              </Link>
              <Link href={`/portal/apps/alliance/achievements/${item.id}/edit`}>
                <Button variant="ghost" size="sm">
                  <Pencil className="h-3.5 w-3.5 mr-1" />
                  编辑
                </Button>
              </Link>
              <Button variant="ghost" size="sm" className="text-red-600" onClick={actions.delete}>
                <Trash2 className="h-3.5 w-3.5 mr-1" />
                删除
              </Button>
            </TableRowActions>
          </>
        )
      }}
      createDefault={() =>
        ({
          id: '',
          title: '',
          type: 'custom',
          status: 'draft',
          isPublic: false as any,
          description: '',
          coverImage: '',
          viewCount: 0,
          enabled: true as any,
          createdAt: '',
          updatedAt: '',
        }) as AllianceAchievement & { enabled?: boolean }
      }
      renderForm={(item: any, setItem: any) => (
        <div className="space-y-4">
          <FormFieldRow label="成果标题" required>
            <Input
              value={item.title || ''}
              onChange={(e: any) => setItem({ ...item, title: e.target.value })}
            />
          </FormFieldRow>
          <FormFieldRow label="成果类型">
            <Select
              value={item.type || 'custom'}
              onValueChange={(v: any) => setItem({ ...item, type: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="job">岗位成果</SelectItem>
                <SelectItem value="scene">场景成果</SelectItem>
                <SelectItem value="course">课程成果</SelectItem>
                <SelectItem value="custom">自定义</SelectItem>
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldRow label="状态">
            <Select
              value={item.status || 'draft'}
              onValueChange={(v: any) => setItem({ ...item, status: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="draft">草稿</SelectItem>
                <SelectItem value="published">已发布</SelectItem>
                <SelectItem value="archived">已归档</SelectItem>
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldRow label="描述">
            <Textarea
              value={item.description || ''}
              onChange={(e: any) => setItem({ ...item, description: e.target.value })}
              rows={4}
            />
          </FormFieldRow>
          <FormFieldRow label="封面图 URL">
            <Input
              value={item.coverImage || ''}
              onChange={(e: any) => setItem({ ...item, coverImage: e.target.value })}
              placeholder="https://..."
            />
          </FormFieldRow>
        </div>
      )}
      getDeleteDescription={(item: any) => <>确定要删除成果「{item.title}」吗？</>}
      onSave={async (item: any, isEdit: boolean) => {
        if (isEdit) {
          await allianceAchievementApi.update(item.id, item)
        } else {
          await allianceAchievementApi.create(item)
        }
        toast({ title: `成果已${isEdit ? '更新' : '创建'}` })
        await fetchItems()
      }}
      onDelete={async (item: any) => {
        await allianceAchievementApi.delete(item.id)
        toast({ title: '成果已删除' })
        await fetchItems()
      }}
      onToggleEnabled={async (item: any) => {
        // 全量回传：后端 PUT 为全列覆盖，避免部分字段被清空
        await allianceAchievementApi.update(item.id, { ...item, isPublic: !item.isPublic })
        toast({ title: item.isPublic ? '已取消前台展示' : '已开启前台展示' })
      }}
    />
  )
}
