// frontend/portal-vue/src/views/portal/workspace/TeacherPortraitsTab.vue
<!--
  我的学生 Tab（教师）。
  对齐原 React 版 teacher-portraits-tab.tsx（524 行）：
  - 数据源：GET /evaluation/job-ability/results（page/limit 分页，page 从 1 起），全量分页拉取避免 >200 截断；
    同一学生保留达成率最高的一条；
  - 顶部三卡：总学生数 / 当前筛选（班级）/ 匹配结果人数；
  - 左侧导航：搜索（专业/班级/姓名/学号）+「全部班级」+ 按专业分组的班级列表（含人数）；
  - 右侧列表：搜索（姓名/学号）+ 学生卡（等级色条 + 头像 + 等级徽标 + 学号/班级/专业/达成率）
    与三个操作：查看画像（内嵌学生画像）/ 学业成绩（成绩单弹窗）/ 能力档案（能力报告弹窗）；
  - 「查看画像」进入后展示「返回学生列表」+ PortraitTab（同 React 复用学生画像组件）。
-->
<template>
  <!-- 查看某个学生画像 -->
  <div v-if="selectedUserId" class="portrait-wrap">
    <el-button link class="back-btn" @click="selectedUserId = null">
      <el-icon><ArrowLeft /></el-icon>返回学生列表
    </el-button>
    <PortraitTab :user-id="selectedUserId" />
  </div>

  <!-- 加载态 -->
  <SectionCard v-else-if="loading" title="我的学生" :icon="User" icon-color="blue">
    <div class="loading-block">
      <el-icon class="is-loading" :size="28"><Loading /></el-icon>
      <span>正在加载学生数据...</span>
    </div>
  </SectionCard>

  <template v-else>
    <SectionCard title="我的学生" :icon="User" icon-color="blue">
      <!-- 概览三卡 -->
      <div class="stat-grid">
        <div class="stat-card primary">
          <span class="stat-icon primary"><el-icon :size="20"><UserFilled /></el-icon></span>
          <div>
            <p class="stat-label">总学生数</p>
            <p class="stat-value">{{ students.length }}</p>
          </div>
        </div>
        <div class="stat-card primary">
          <span class="stat-icon primary"><el-icon :size="20"><School /></el-icon></span>
          <div>
            <p class="stat-label">当前筛选</p>
            <p class="stat-value">{{ selectedClassName }}</p>
          </div>
        </div>
        <div class="stat-card amber">
          <span class="stat-icon amber"><el-icon :size="20"><Histogram /></el-icon></span>
          <div>
            <p class="stat-label">匹配结果</p>
            <p class="stat-value">{{ filteredStudents.length }} 人</p>
          </div>
        </div>
      </div>

      <div class="portraits-grid">
        <!-- 左侧班级导航 -->
        <div class="nav-col">
          <div class="nav-panel">
            <div class="nav-head">
              <el-input
                v-model="navSearch"
                size="small"
                placeholder="搜索姓名或学号..."
                clearable
                :prefix-icon="Search"
              />
            </div>
            <el-scrollbar class="nav-list">
              <button
                type="button"
                class="nav-all"
                :class="{ active: selectedClass === 'all' }"
                @click="selectedClass = 'all'"
              >
                <span class="nav-dot" :class="{ active: selectedClass === 'all' }" />
                <span>全部班级</span>
                <span class="nav-count">{{ students.length }}</span>
              </button>
              <div class="nav-groups">
                <div v-for="group in groupedByClass" :key="group.major" class="nav-group">
                  <div class="nav-group-title">{{ group.major }}</div>
                  <div class="nav-group-body">
                    <button
                      v-for="cls in group.classes"
                      :key="cls.className"
                      type="button"
                      class="nav-class"
                      :class="{ active: selectedClass === cls.className }"
                      @click="selectedClass = cls.className"
                    >
                      <span class="nav-class-left">
                        <span class="nav-dot" :class="{ active: selectedClass === cls.className }" />
                        <span>{{ cls.className }}</span>
                      </span>
                      <span class="nav-count">{{ cls.count }}</span>
                    </button>
                  </div>
                </div>
              </div>
            </el-scrollbar>
          </div>
        </div>

        <!-- 右侧学生列表 -->
        <div class="list-col">
          <el-input
            v-model="searchTerm"
            class="list-search"
            placeholder="搜索姓名或学号..."
            clearable
            :prefix-icon="Search"
          />

          <div v-if="filteredStudents.length === 0" class="empty-block">
            <el-icon :size="44"><Search /></el-icon>
            <p class="empty-title">暂无匹配的学生</p>
            <p class="empty-sub">请尝试调整搜索条件或筛选班级</p>
          </div>

          <el-scrollbar v-else max-height="60vh">
            <div class="student-list">
              <div v-for="student in filteredStudents" :key="student.userId" class="student-card">
                <span class="grade-bar" :style="{ background: gradeBar(student.grade) }" />
                <div class="student-body">
                  <span class="student-avatar">{{ student.name.charAt(0) }}</span>
                  <div class="student-main">
                    <div class="student-row-top">
                      <div class="student-name-row">
                        <span class="student-name">{{ student.name }}</span>
                        <span
                          v-if="student.grade"
                          class="grade-chip"
                          :style="gradeChipStyle(student.grade)"
                        >
                          {{ student.grade }}
                        </span>
                      </div>
                      <div class="student-actions">
                        <el-button size="small" type="primary" @click="selectedUserId = student.userId">
                          <el-icon><View /></el-icon>查看画像
                        </el-button>
                        <el-button size="small" class="act-amber" @click="openGradeReport(student)">
                          <el-icon><Document /></el-icon>学业成绩
                        </el-button>
                        <el-button size="small" class="act-primary" @click="openAbilityProfile(student)">
                          <el-icon><Aim /></el-icon>能力档案
                        </el-button>
                      </div>
                    </div>
                    <div class="student-meta">
                      <el-tag size="small" effect="plain">{{ student.studentNo }}</el-tag>
                      <span class="meta-sep">|</span>
                      <span>{{ student.className }}</span>
                      <span class="meta-sep">|</span>
                      <span>{{ student.majorName }}</span>
                      <span class="meta-sep">|</span>
                      <span>达成率 {{ student.achievementRate.toFixed(1) }}%</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </el-scrollbar>
        </div>
      </div>
    </SectionCard>

    <!-- 成绩单弹窗 -->
    <el-dialog v-model="gradeReportOpen" width="520px">
      <template #header>
        <div class="dlg-head">
          <span class="dlg-title amber"><el-icon><Document /></el-icon>查看学生成绩单</span>
          <p class="dlg-desc">
            {{ activeStudent?.name }} · {{ activeStudent?.studentNo }} · {{ activeStudent?.className }}
          </p>
        </div>
      </template>
      <el-table :data="gradeReportRows" size="small">
        <el-table-column prop="label" label="指标" min-width="140" />
        <el-table-column label="数值" min-width="140">
          <template #default="{ row }">
            <span
              v-if="row.label === '认定等级'"
              class="grade-chip"
              :style="gradeChipStyle(activeStudent?.grade)"
            >
              {{ activeStudent?.grade || '-' }}
            </span>
            <template v-else>{{ row.value }}</template>
          </template>
        </el-table-column>
      </el-table>
    </el-dialog>

    <!-- 能力报告弹窗 -->
    <el-dialog v-model="abilityProfileOpen" width="480px">
      <template #header>
        <div class="dlg-head">
          <span class="dlg-title"><el-icon><Aim /></el-icon>查看学生能力报告</span>
          <p class="dlg-desc">
            {{ activeStudent?.name }} · {{ activeStudent?.majorName }} · {{ activeStudent?.className }}
          </p>
        </div>
      </template>
      <div class="ability-body">
        <template v-if="activeStudent?.abilities?.length">
          <div v-for="(a, i) in activeStudent.abilities" :key="i" class="ability-row">
            <div class="ability-head">
              <span class="ability-name">{{ a.name }}</span>
              <span class="ability-score">{{ a.score.toFixed(1) }}/100</span>
            </div>
            <el-progress :percentage="Math.min(a.score, 100)" :show-text="false" :stroke-width="8" />
          </div>
        </template>
        <p v-else class="empty-line">暂无能力点数据</p>
        <div class="ability-foot">
          <span class="ability-foot-label">综合评级</span>
          <span class="grade-chip" :style="gradeChipStyle(activeStudent?.grade)">
            {{ activeStudent?.grade || '-' }}
          </span>
        </div>
      </div>
    </el-dialog>
  </template>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import {
  Aim,
  ArrowLeft,
  Document,
  Histogram,
  Loading,
  School,
  Search,
  User,
  UserFilled,
  View
} from '@element-plus/icons-vue';
import { jobAbilityResultApi } from '@/api/evaluation';
import type { JobAbilityResult } from '@/types/evaluation';
import SectionCard from './SectionCard.vue';
import PortraitTab from './PortraitTab.vue';

interface StudentRow {
  userId: string;
  name: string;
  studentNo: string;
  className: string;
  majorName: string;
  grade?: string;
  achievementRate: number;
  totalPoints: number;
  achievedPoints: number;
  abilities: { name: string; score: number }[];
}

/** 等级 → 徽标配色（对齐 React gradeColorMap） */
const GRADE_CHIP: Record<string, { color: string; bg: string; border: string }> = {
  卓越: { color: '#047857', bg: '#d1fae5', border: '#a7f3d0' },
  优秀: { color: '#047857', bg: '#d1fae5', border: '#a7f3d0' },
  良好: { color: '#1d4ed8', bg: '#dbeafe', border: '#bfdbfe' },
  达标: { color: '#1d4ed8', bg: '#dbeafe', border: '#bfdbfe' },
  未达标: { color: '#b45309', bg: '#fef3c7', border: '#fde68a' }
};

/** 等级 → 卡片左侧色条（对齐 React gradeBgMap） */
const GRADE_BAR: Record<string, string> = {
  卓越: 'linear-gradient(180deg, #10b981, #059669)',
  优秀: 'linear-gradient(180deg, #10b981, #059669)',
  良好: 'linear-gradient(180deg, #3b82f6, #2563eb)',
  达标: 'linear-gradient(180deg, #3b82f6, #2563eb)',
  未达标: 'linear-gradient(180deg, #f59e0b, #d97706)'
};

const PAGE_SIZE = 200;
const MAX_PAGES = 1000;

const searchTerm = ref('');
const navSearch = ref('');
const selectedClass = ref<string>('all');
const selectedUserId = ref<string | null>(null);
const gradeReportOpen = ref(false);
const abilityProfileOpen = ref(false);
const activeStudent = ref<StudentRow | null>(null);
const allResults = ref<JobAbilityResult[]>([]);
const loading = ref(true);

const students = computed<StudentRow[]>(() => {
  const map = new Map<string, StudentRow>();
  allResults.value.forEach((r) => {
    const uid = r.userId;
    if (!uid) return;
    const existing = map.get(uid);
    if (existing && existing.achievementRate >= r.achievementRate) return;
    const abilities = Array.isArray(r.abilityPointDetails)
      ? r.abilityPointDetails.map((a) => ({ name: a.abilityPointName || '', score: a.score || 0 }))
      : [];
    map.set(uid, {
      userId: uid,
      name: r.studentName,
      studentNo: r.studentId || '',
      className: r.className || '',
      majorName: r.majorName || '',
      grade: r.grade || undefined,
      achievementRate: r.achievementRate,
      totalPoints: r.totalAbilityPoints,
      achievedPoints: r.achievedAbilityPoints,
      abilities
    });
  });
  return Array.from(map.values());
});

const groupedByClass = computed(() => {
  const majorMap = new Map<string, Map<string, string[]>>();
  students.value.forEach((s) => {
    const major = s.majorName || '未分类';
    if (!majorMap.has(major)) majorMap.set(major, new Map());
    const gradeMap = majorMap.get(major)!;
    const cls = s.className || '未分班';
    if (!gradeMap.has(cls)) gradeMap.set(cls, []);
    const q = navSearch.value.trim().toLowerCase();
    if (
      q &&
      !major.toLowerCase().includes(q) &&
      !cls.toLowerCase().includes(q) &&
      !s.name.toLowerCase().includes(q) &&
      !s.studentNo.toLowerCase().includes(q)
    )
      return;
    gradeMap.get(cls)!.push(s.userId);
  });
  const result: { major: string; classes: { className: string; count: number }[] }[] = [];
  majorMap.forEach((classMap, major) => {
    const classes = Array.from(classMap.entries())
      .map(([className, userIds]) => ({ className, count: userIds.length }))
      .sort((a, b) => a.className.localeCompare(b.className));
    if (classes.length > 0) result.push({ major, classes });
  });
  return result.sort((a, b) => a.major.localeCompare(b.major));
});

const filteredStudents = computed(() => {
  let list = students.value;
  if (selectedClass.value !== 'all') {
    list = list.filter((s) => s.className === selectedClass.value);
  }
  if (searchTerm.value) {
    const q = searchTerm.value.toLowerCase();
    list = list.filter(
      (s) => s.name.toLowerCase().includes(q) || s.studentNo.toLowerCase().includes(q)
    );
  }
  return list;
});

const selectedClassName = computed(() =>
  selectedClass.value === 'all' ? '全部班级' : selectedClass.value
);

const gradeReportRows = computed(() => [
  { label: '总能力点', value: activeStudent.value?.totalPoints ?? '-' },
  { label: '已达成能力点', value: activeStudent.value?.achievedPoints ?? '-' },
  {
    label: '达标率',
    value:
      activeStudent.value != null ? `${activeStudent.value.achievementRate.toFixed(1)}%` : '-'
  },
  { label: '认定等级', value: activeStudent.value?.grade || '-' }
]);

function gradeChipStyle(grade?: string) {
  const conf = GRADE_CHIP[grade || ''] || { color: '#374151', bg: '#f3f4f6', border: '#e5e7eb' };
  return { color: conf.color, backgroundColor: conf.bg, borderColor: conf.border };
}

function gradeBar(grade?: string): string {
  return GRADE_BAR[grade || ''] || 'linear-gradient(180deg, #9ca3af, #6b7280)';
}

function openGradeReport(student: StudentRow) {
  activeStudent.value = student;
  gradeReportOpen.value = true;
}

function openAbilityProfile(student: StudentRow) {
  activeStudent.value = student;
  abilityProfileOpen.value = true;
}

/** 全量分页拉取（对齐 React fetchAllPages：page 从 1 起，页满则继续，超页数熔断） */
async function loadAllResults(): Promise<JobAbilityResult[]> {
  const all: JobAbilityResult[] = [];
  for (let page = 0; ; page++) {
    if (page >= MAX_PAGES) {
      throw new Error(`分页拉取超过最大页数 ${MAX_PAGES}，疑似分页未生效，已中止`);
    }
    const res = await jobAbilityResultApi.list({ page: page + 1, limit: PAGE_SIZE });
    const items = res.items || [];
    all.push(...items);
    if (items.length < PAGE_SIZE) break;
  }
  return all;
}

onMounted(async () => {
  try {
    allResults.value = await loadAllResults();
  } catch (e) {
    allResults.value = [];
    ElMessage.error((e as Error).message || '加载学生能力数据失败');
  } finally {
    loading.value = false;
  }
});
</script>

<style scoped>
.portrait-wrap {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.back-btn {
  align-self: flex-start;
  font-size: 14px;
  color: #6b7280;
}
.back-btn:hover {
  color: #111827;
}
.loading-block {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 64px 0;
  font-size: 14px;
  color: #6b7280;
}
.loading-block :deep(.el-icon) {
  color: var(--el-color-primary);
}

/* 概览三卡 */
.stat-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 16px;
  margin-bottom: 20px;
}
@media (min-width: 640px) {
  .stat-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
}
.stat-card {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px;
  border: 1px solid;
  border-radius: 8px;
}
.stat-card.primary {
  border-color: var(--el-color-primary-light-7);
  background: var(--el-color-primary-light-9);
}
.stat-card.amber {
  border-color: #fde68a;
  background: linear-gradient(135deg, #fffbeb, #fef3c7);
}
.stat-icon {
  width: 40px;
  height: 40px;
  flex-shrink: 0;
  border-radius: 8px;
  color: #fff;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.06);
}
.stat-icon.primary {
  background: linear-gradient(135deg, var(--el-color-primary), var(--el-color-primary-light-3));
}
.stat-icon.amber {
  background: linear-gradient(135deg, #f59e0b, #d97706);
}
.stat-label {
  margin: 0;
  font-size: 11px;
  font-weight: 500;
  color: var(--el-color-primary);
}
.stat-card.amber .stat-label {
  color: #d97706;
}
.stat-value {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
  color: var(--el-color-primary);
}
.stat-card.amber .stat-value {
  color: #b45309;
}

/* 主体两栏 */
.portraits-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 24px;
}
@media (min-width: 1024px) {
  .portraits-grid { grid-template-columns: repeat(12, minmax(0, 1fr)); }
  .nav-col { grid-column: span 3; }
  .list-col { grid-column: span 9; }
}
.nav-panel {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #fff;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
  overflow: hidden;
}
.nav-head {
  padding: 12px;
  border-bottom: 1px solid #e5e7eb;
  background: linear-gradient(90deg, #f9fafb, #fff);
}
.nav-list {
  max-height: calc(100vh - 520px);
  min-height: 240px;
  padding: 8px;
}
.nav-all,
.nav-class {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 12px;
  border: 1px solid transparent;
  border-radius: 8px;
  background: transparent;
  font-size: 14px;
  color: #4b5563;
  cursor: pointer;
  transition: background-color 0.2s, color 0.2s;
}
.nav-all:hover,
.nav-class:hover {
  background: #f9fafb;
  color: #111827;
}
.nav-all.active,
.nav-class.active {
  background: var(--el-color-primary-light-9);
  border-color: var(--el-color-primary-light-7);
  color: var(--el-color-primary);
  font-weight: 600;
}
.nav-class {
  justify-content: space-between;
}
.nav-class-left {
  display: flex;
  align-items: center;
  gap: 10px;
}
.nav-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #d1d5db;
  flex-shrink: 0;
}
.nav-dot.active {
  background: var(--el-color-primary);
}
.nav-count {
  margin-left: auto;
  font-size: 12px;
  font-weight: 500;
  color: #9ca3af;
}
.nav-all.active .nav-count,
.nav-class.active .nav-count {
  color: var(--el-color-primary);
}
.nav-groups {
  margin-top: 4px;
  border-top: 1px solid #f3f4f6;
  padding-top: 4px;
}
.nav-group {
  margin-bottom: 2px;
}
.nav-group-title {
  padding: 8px 12px;
  font-size: 12px;
  font-weight: 600;
  color: #6b7280;
}
.nav-group-body {
  margin-left: 12px;
  padding-left: 8px;
  border-left: 2px solid #f3f4f6;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

/* 学生列表 */
.list-search {
  margin-bottom: 16px;
}
.empty-block {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 4px;
  padding: 64px 0;
  color: #9ca3af;
}
.empty-block :deep(.el-icon) {
  color: #e5e7eb;
  margin-bottom: 8px;
}
.empty-title {
  margin: 0;
  font-size: 14px;
  font-weight: 500;
}
.empty-sub {
  margin: 0;
  font-size: 12px;
}
.empty-line {
  padding: 16px 0;
  text-align: center;
  font-size: 14px;
  color: #9ca3af;
}
.student-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding-right: 4px;
}
.student-card {
  position: relative;
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  overflow: hidden;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.student-card:hover {
  border-color: var(--el-color-primary-light-7);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}
.grade-bar {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 4px;
}
.student-body {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 16px 16px 16px 20px;
}
.student-avatar {
  width: 44px;
  height: 44px;
  flex-shrink: 0;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--el-color-primary), var(--el-color-primary-light-3));
  color: #fff;
  font-size: 14px;
  font-weight: 700;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
.student-main {
  flex: 1;
  min-width: 0;
}
.student-row-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  flex-wrap: wrap;
}
.student-name-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.student-name {
  font-size: 14px;
  font-weight: 600;
  color: #111827;
}
.grade-chip {
  display: inline-block;
  padding: 1px 8px;
  border: 1px solid;
  border-radius: 999px;
  font-size: 10px;
  font-weight: 600;
}
.student-actions {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-wrap: wrap;
}
.student-actions :deep(.el-button) {
  margin-left: 0;
}
.act-amber {
  border-color: #fde68a;
  color: #d97706;
}
.act-primary {
  border-color: var(--el-color-primary-light-7);
  color: var(--el-color-primary);
}
.student-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-top: 6px;
  font-size: 12px;
  color: #6b7280;
}
.meta-sep {
  color: #d1d5db;
}

/* 弹窗 */
.dlg-head {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.dlg-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 16px;
  font-weight: 600;
  color: #111827;
}
.dlg-title :deep(.el-icon) {
  color: var(--el-color-primary);
}
.dlg-title.amber :deep(.el-icon) {
  color: #d97706;
}
.dlg-desc {
  margin: 0;
  font-size: 13px;
  color: #6b7280;
}
.ability-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.ability-row {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.ability-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 12px;
}
.ability-name {
  font-weight: 500;
  color: #4b5563;
}
.ability-score {
  font-weight: 600;
  color: #111827;
}
.ability-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-top: 1px solid #f3f4f6;
  padding-top: 12px;
  font-size: 14px;
}
.ability-foot-label {
  color: #6b7280;
}
</style>

// apps/edu/app/portal/workspace/_components/teacher-portraits-tab.tsx
'use client'

import { useState, useMemo, useEffect } from 'react'
import {
  User,
  Search,
  ChevronLeft,
  GraduationCap,
  Users,
  Eye,
  BarChart3,
  FileText,
  Target,
  Loader2,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { SectionCard } from './section-card'
import { PortraitTab } from './portrait-tab'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import { Progress } from '@/components/ui/progress'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { jobAbilityResultApi } from '@/lib/api'
import type { JobAbilityResult, JobAbilityPointDetail } from '@/lib/api'

const gradeColorMap: Record<string, string> = {
  卓越: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  优秀: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  良好: 'bg-blue-100 text-blue-700 border-blue-200',
  达标: 'bg-blue-100 text-blue-700 border-blue-200',
  未达标: 'bg-amber-100 text-amber-700 border-amber-200',
}

const gradeBgMap: Record<string, string> = {
  卓越: 'from-emerald-500 to-emerald-600',
  优秀: 'from-emerald-500 to-emerald-600',
  良好: 'from-blue-500 to-blue-600',
  达标: 'from-blue-500 to-blue-600',
  未达标: 'from-amber-500 to-amber-600',
}

interface StudentRow {
  userId: string
  name: string
  studentNo: string
  className: string
  majorName: string
  grade?: string
  achievementRate: number
  totalPoints: number
  achievedPoints: number
  abilities: { name: string; score: number }[]
}

function getGradeBg(grade?: string) {
  return gradeBgMap[grade || ''] || 'from-gray-400 to-gray-500'
}

function getGradeColor(grade?: string) {
  return gradeColorMap[grade || ''] || 'bg-gray-100 text-gray-700'
}

export function TeacherPortraitsTab() {
  const [searchTerm, setSearchTerm] = useState('')
  const [navSearch, setNavSearch] = useState('')
  const [selectedClass, setSelectedClass] = useState<string>('all')
  const [selectedUserId, setSelectedUserId] = useState<string | null>(null)
  const [gradeReportOpen, setGradeReportOpen] = useState(false)
  const [abilityProfileOpen, setAbilityProfileOpen] = useState(false)
  const [activeStudent, setActiveStudent] = useState<StudentRow | null>(null)
  const [allResults, setAllResults] = useState<JobAbilityResult[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let cancelled = false
    jobAbilityResultApi
      .list({ limit: 200 })
      .then((res) => {
        if (!cancelled) {
          setAllResults(res.items || [])
          setLoading(false)
        }
      })
      .catch(() => {
        if (!cancelled) {
          setAllResults([])
          setLoading(false)
        }
      })
    return () => {
      cancelled = true
    }
  }, [])

  const students = useMemo(() => {
    const map = new Map<string, StudentRow>()
    allResults.forEach((r) => {
      const uid = r.userId
      if (!uid) return
      const existing = map.get(uid)
      if (existing && existing.achievementRate >= r.achievementRate) return
      const abilities: { name: string; score: number }[] = Array.isArray(r.abilityPointDetails)
        ? (r.abilityPointDetails as unknown as JobAbilityPointDetail[]).map((a) => ({
            name: a.abilityPointName || '',
            score: a.score || 0,
          }))
        : []
      map.set(uid, {
        userId: uid,
        name: r.studentName,
        studentNo: r.studentId || '',
        className: r.className || '',
        majorName: r.majorName || '',
        grade: r.grade || undefined,
        achievementRate: r.achievementRate,
        totalPoints: r.totalAbilityPoints,
        achievedPoints: r.achievedAbilityPoints,
        abilities,
      })
    })
    return Array.from(map.values())
  }, [allResults])

  const groupedByClass = useMemo(() => {
    const majorMap = new Map<string, Map<string, string[]>>()
    students.forEach((s) => {
      const major = s.majorName || '未分类'
      if (!majorMap.has(major)) majorMap.set(major, new Map())
      const gradeMap = majorMap.get(major)!
      const cls = s.className || '未分班'
      if (!gradeMap.has(cls)) gradeMap.set(cls, [])
      const q = navSearch.trim().toLowerCase()
      if (
        q &&
        !major.toLowerCase().includes(q) &&
        !cls.toLowerCase().includes(q) &&
        !s.name.toLowerCase().includes(q) &&
        !s.studentNo.toLowerCase().includes(q)
      )
        return
      gradeMap.get(cls)!.push(s.userId)
    })
    const result: { major: string; classes: { className: string; count: number }[] }[] = []
    majorMap.forEach((classMap, major) => {
      const classes = Array.from(classMap.entries())
        .map(([className, userIds]) => ({ className, count: userIds.length }))
        .sort((a, b) => a.className.localeCompare(b.className))
      if (classes.length > 0) result.push({ major, classes })
    })
    return result.sort((a, b) => a.major.localeCompare(b.major))
  }, [students, navSearch])

  const filteredStudents = useMemo(() => {
    let list = students
    if (selectedClass !== 'all') {
      list = list.filter((s) => s.className === selectedClass)
    }
    if (searchTerm) {
      const q = searchTerm.toLowerCase()
      list = list.filter(
        (s) => s.name.toLowerCase().includes(q) || s.studentNo.toLowerCase().includes(q),
      )
    }
    return list
  }, [students, selectedClass, searchTerm])

  const selectedClassName = selectedClass === 'all' ? '全部班级' : selectedClass

  if (selectedUserId) {
    return (
      <div className="space-y-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setSelectedUserId(null)}
          className="text-sm text-gray-500 hover:text-gray-900 -ml-2"
        >
          <ChevronLeft className="h-4 w-4 mr-1" />
          返回学生列表
        </Button>
        <PortraitTab userId={selectedUserId} />
      </div>
    )
  }

  if (loading) {
    return (
      <SectionCard title="我的学生" icon={User} iconColor="blue">
        <div className="flex items-center justify-center py-16">
          <Loader2 className="h-8 w-8 animate-spin text-blue-500" />
          <span className="ml-3 text-sm text-gray-500">正在加载学生数据...</span>
        </div>
      </SectionCard>
    )
  }

  return (
    <>
      <SectionCard title="我的学生" icon={User} iconColor="blue">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5">
          <div className="rounded-lg bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200 p-3.5 flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center shadow-sm">
              <Users className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-blue-500 font-medium">总学生数</p>
              <p className="text-lg font-bold text-blue-700">{students.length}</p>
            </div>
          </div>
          <div className="rounded-lg bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200 p-3.5 flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center shadow-sm">
              <GraduationCap className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-blue-500 font-medium">当前筛选</p>
              <p className="text-lg font-bold text-blue-700">{selectedClassName}</p>
            </div>
          </div>
          <div className="rounded-lg bg-gradient-to-br from-amber-50 to-amber-100 border border-amber-200 p-3.5 flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-amber-500 to-amber-600 flex items-center justify-center shadow-sm">
              <BarChart3 className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-amber-500 font-medium">匹配结果</p>
              <p className="text-lg font-bold text-amber-700">{filteredStudents.length} 人</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-3">
            <div className="rounded-xl border bg-white shadow-sm overflow-hidden">
              <div className="border-b bg-gradient-to-r from-gray-50 to-white p-3">
                <div className="relative">
                  <Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-gray-400" />
                  <Input
                    placeholder="搜索姓名或学号..."
                    value={navSearch}
                    onChange={(e) => setNavSearch(e.target.value)}
                    className="h-9 pl-8 text-xs border-gray-200 bg-white focus:border-blue-300"
                  />
                </div>
              </div>
              <div className="max-h-[calc(100vh-520px)] overflow-y-auto p-2">
                <button
                  onClick={() => setSelectedClass('all')}
                  className={`flex w-full items-center rounded-lg px-3 py-2 text-left text-sm transition-all ${
                    selectedClass === 'all'
                      ? 'bg-gradient-to-r from-blue-50 to-blue-100/50 text-blue-700 font-semibold shadow-sm border border-blue-200'
                      : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                  }`}
                >
                  <div
                    className={`w-1.5 h-1.5 rounded-full mr-2.5 ${selectedClass === 'all' ? 'bg-blue-500' : 'bg-gray-300'}`}
                  />
                  <span>全部班级</span>
                  <span
                    className={`ml-auto text-xs font-medium ${selectedClass === 'all' ? 'text-blue-500' : 'text-gray-400'}`}
                  >
                    {students.length}
                  </span>
                </button>
                <div className="mt-1 border-t border-gray-100 pt-1">
                  {groupedByClass.map(({ major, classes }) => (
                    <div key={major} className="mb-0.5">
                      <div className="flex items-center rounded-lg px-3 py-2 text-xs font-semibold text-gray-500">
                        {major}
                      </div>
                      <div className="ml-3 space-y-0.5 border-l-2 border-gray-100 pl-2">
                        {classes.map(({ className, count }) => {
                          const isActive = selectedClass === className
                          return (
                            <button
                              key={className}
                              onClick={() => setSelectedClass(className)}
                              className={`flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm transition-all ${
                                isActive
                                  ? 'bg-gradient-to-r from-blue-50 to-blue-100/50 text-blue-700 font-semibold border border-blue-200 shadow-sm'
                                  : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                              }`}
                            >
                              <div className="flex items-center gap-2.5">
                                <div
                                  className={`w-1.5 h-1.5 rounded-full ${isActive ? 'bg-blue-500' : 'bg-gray-300'}`}
                                />
                                <span>{className}</span>
                              </div>
                              <span
                                className={`text-xs font-medium ${isActive ? 'text-blue-500' : 'text-gray-400'}`}
                              >
                                {count}
                              </span>
                            </button>
                          )
                        })}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-9">
            <div className="relative mb-4">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                placeholder="搜索姓名或学号..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-9 h-10 text-sm border-gray-200 bg-white focus:border-blue-300 rounded-xl"
              />
            </div>

            {filteredStudents.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-gray-400">
                <Search className="w-12 h-12 mb-3 text-gray-200" />
                <p className="text-sm font-medium">暂无匹配的学生</p>
                <p className="text-xs mt-1">请尝试调整搜索条件或筛选班级</p>
              </div>
            ) : (
              <div className="space-y-3 max-h-[60vh] overflow-auto pr-1">
                {filteredStudents.map((student) => {
                  const gradeColors = getGradeColor(student.grade)
                  return (
                    <div
                      key={student.userId}
                      className="group relative rounded-xl border border-gray-100 bg-white hover:border-blue-200 hover:shadow-md transition-all cursor-pointer overflow-hidden"
                    >
                      <div
                        className={`absolute left-0 top-0 bottom-0 w-1 bg-gradient-to-b ${getGradeBg(student.grade)}`}
                      />
                      <div className="p-4 pl-5">
                        <div className="flex items-center gap-4">
                          <Avatar className="w-11 h-11 ring-2 ring-white shadow-sm">
                            <AvatarFallback className="bg-gradient-to-br from-blue-500 to-blue-600 text-white text-sm font-bold">
                              {student.name.charAt(0)}
                            </AvatarFallback>
                          </Avatar>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center justify-between gap-2">
                              <div className="flex items-center gap-2">
                                <span className="text-sm font-semibold text-gray-900">
                                  {student.name}
                                </span>
                                {student.grade && (
                                  <Badge
                                    className={`text-[10px] font-semibold border ${gradeColors}`}
                                  >
                                    {student.grade}
                                  </Badge>
                                )}
                              </div>
                              <div className="flex items-center gap-1.5">
                                <Button
                                  size="sm"
                                  className="h-8 gap-1.5 text-xs bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white shadow-sm"
                                  onClick={(e) => {
                                    e.stopPropagation()
                                    setSelectedUserId(student.userId)
                                  }}
                                >
                                  <Eye className="w-3.5 h-3.5" />
                                  查看画像
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-8 gap-1.5 text-xs border-amber-200 text-amber-600 hover:bg-amber-50"
                                  onClick={(e) => {
                                    e.stopPropagation()
                                    setActiveStudent(student)
                                    setGradeReportOpen(true)
                                  }}
                                >
                                  <FileText className="w-3.5 h-3.5" />
                                  学业成绩
                                </Button>
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-8 gap-1.5 text-xs border-blue-200 text-blue-600 hover:bg-blue-50"
                                  onClick={(e) => {
                                    e.stopPropagation()
                                    setActiveStudent(student)
                                    setAbilityProfileOpen(true)
                                  }}
                                >
                                  <Target className="w-3.5 h-3.5" />
                                  能力档案
                                </Button>
                              </div>
                            </div>
                            <div className="flex items-center gap-2 mt-1.5 flex-wrap">
                              <Badge
                                variant="outline"
                                className="text-[11px] text-gray-500 border-gray-200 bg-gray-50/50"
                              >
                                {student.studentNo}
                              </Badge>
                              <span className="text-[11px] text-gray-400">|</span>
                              <span className="text-xs text-gray-500">{student.className}</span>
                              <span className="text-[11px] text-gray-400">|</span>
                              <span className="text-xs text-gray-500">{student.majorName}</span>
                              <span className="text-[11px] text-gray-400">|</span>
                              <span className="text-xs text-gray-500">
                                达成率 {student.achievementRate.toFixed(1)}%
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      </SectionCard>
      <Dialog open={gradeReportOpen} onOpenChange={setGradeReportOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-amber-600" />
              查看学生成绩单
            </DialogTitle>
            <DialogDescription>
              {activeStudent?.name} · {activeStudent?.studentNo} · {activeStudent?.className}
            </DialogDescription>
          </DialogHeader>
          <Table>
            <TableHeader>
              <TableRow className="bg-gray-50">
                <TableHead className="text-xs">指标</TableHead>
                <TableHead className="text-xs">数值</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="text-sm font-medium">总能力点</TableCell>
                <TableCell className="text-sm">{activeStudent?.totalPoints ?? '-'}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="text-sm font-medium">已达成能力点</TableCell>
                <TableCell className="text-sm">{activeStudent?.achievedPoints ?? '-'}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="text-sm font-medium">达标率</TableCell>
                <TableCell className="text-sm">
                  {activeStudent?.achievementRate.toFixed(1) ?? '-'}%
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="text-sm font-medium">认定等级</TableCell>
                <TableCell>
                  <Badge className={`text-xs ${getGradeColor(activeStudent?.grade)}`}>
                    {activeStudent?.grade || '-'}
                  </Badge>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </DialogContent>
      </Dialog>
      <Dialog open={abilityProfileOpen} onOpenChange={setAbilityProfileOpen}>
        <DialogContent size="sm">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Target className="h-5 w-5 text-blue-600" />
              查看学生能力报告
            </DialogTitle>
            <DialogDescription>
              {activeStudent?.name} · {activeStudent?.majorName} · {activeStudent?.className}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            {activeStudent?.abilities?.length ? (
              activeStudent.abilities.map((a, i) => (
                <div key={i} className="space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-gray-600 font-medium">{a.name}</span>
                    <span className="text-gray-900 font-semibold">{a.score.toFixed(1)}/100</span>
                  </div>
                  <Progress value={Math.min(a.score, 100)} className="h-2" />
                </div>
              ))
            ) : (
              <p className="text-sm text-gray-400 text-center py-4">暂无能力点数据</p>
            )}
            <div className="pt-2 border-t border-gray-100">
              <div className="flex items-center justify-between text-sm">
                <span className="text-gray-500">综合评级</span>
                <Badge className={`text-xs font-bold ${getGradeColor(activeStudent?.grade)}`}>
                  {activeStudent?.grade || '-'}
                </Badge>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
