// frontend/portal-vue/src/views/ai/landing.vue
<template>
  <div class="ai-landing">
    <!-- Hero -->
    <section class="hero">
      <div class="hero-inner">
        <div class="hero-flex">
          <div class="hero-left">
            <div class="hero-badge"><el-icon><MagicStick /></el-icon>AI 智能服务平台</div>
            <h1 class="hero-title">
              AI 赋能场景化数智教学
              <span class="hero-sub">培养适应复合型岗位新需求人才</span>
            </h1>
            <p class="hero-desc">融合场景化数智教学模式，为职业教育提供智能化教学辅助、岗位能力评估、个性化学习路径规划等全方位AI服务，助力培养适应产业需求的高素质技术技能人才。</p>
            <el-button class="hero-cta" round @click="scrollToSquare">逛逛 AI 广场</el-button>
          </div>
          <div class="hero-right">
            <div class="hero-card">
              <div class="hero-brand"><el-icon><MagicStick /></el-icon>YI KNOW</div>
              <div class="hero-card-title">职业教育场景化教学智能助理</div>
              <div class="hero-card-slogan">You Ask · I Know · 你问，我懂</div>
              <p class="hero-card-desc">集成多元大模型能力，以知识库与智能体全面赋能职业教育场景化教学</p>
              <el-button class="hero-card-btn" round @click="ykOpen = true">立即体验 <span>→</span></el-button>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- 统计条 -->
    <div class="stats-wrap">
      <div class="stats-bar">
        <div class="stat-item">
          <div class="stat-icon" style="background: #409eff"><el-icon><Cpu /></el-icon></div>
          <div class="stat-text">
            <div class="stat-value">{{ stats.agentTotal ?? '-' }}</div>
            <div class="stat-label">已发布智能体</div>
          </div>
        </div>
        <div class="stat-item">
          <div class="stat-icon" style="background: #10b981"><el-icon><Collection /></el-icon></div>
          <div class="stat-text">
            <div class="stat-value">{{ stats.kbTotal ?? '-' }}</div>
            <div class="stat-label">已发布知识库</div>
          </div>
        </div>
        <div class="stat-item">
          <div class="stat-icon" style="background: #8b5cf6"><el-icon><Link /></el-icon></div>
          <div class="stat-text">
            <div class="stat-value">{{ integrations.length }}</div>
            <div class="stat-label">第三方服务</div>
          </div>
        </div>
      </div>
    </div>

    <main class="landing-main">
      <!-- 我的工坊 -->
      <section id="studio" class="scroll-anchor">
        <StudioSection />
      </section>

      <!-- AI 广场 -->
      <section id="square" class="scroll-anchor square-section">
        <div class="section-title">
          <span class="title-bar" />
          <h2>AI 广场</h2>
          <p>全校师生共建共享的智能体、知识库与第三方服务</p>
        </div>

        <FlatBlock
          title="智能体"
          desc="点开即聊的 AI 助手"
          icon="🤖"
          :count="stats.agentTotal"
          more-href="/portal/apps/ai/hall/agents"
          more-label="查看更多"
          empty-label="暂无已发布智能体"
          :has-items="agents.length > 0"
        >
          <AgentHallCard v-for="a in agents" :key="a.id" :agent="a" />
        </FlatBlock>

        <FlatBlock
          title="知识库"
          desc="可提问的资料库"
          icon="📚"
          :count="stats.kbTotal"
          more-href="/portal/apps/ai/hall/kbs"
          more-label="查看更多"
          empty-label="暂无已发布知识库"
          :has-items="kbs.length > 0"
        >
          <KbHallCard v-for="kb in kbs" :key="kb.id" :kb="kb" />
        </FlatBlock>

        <FlatBlock
          title="第三方服务"
          desc="管理员精选挂接的外部智能体与应用"
          icon="🔗"
          :count="integrations.length"
          empty-label="暂无第三方服务"
          :has-items="integrations.length > 0"
        >
          <IntegrationLinkCard v-for="it in integrations" :key="it.id" :item="it" />
        </FlatBlock>
      </section>

      <!-- 底部行动卡 -->
      <section class="cta-card">
        <div class="cta-icon"><el-icon><MagicStick /></el-icon></div>
        <div class="cta-text">
          <h2>把你的知识变成全校可用的 AI 服务</h2>
          <p>上传资料建成知识库，或配置一个专属智能体，审核通过后即可发布到广场。</p>
        </div>
        <el-button class="cta-btn" round @click="scrollToStudio">去工坊创作</el-button>
      </section>
    </main>

    <!-- YIKnow 聊天弹窗 -->
    <el-dialog
      v-model="ykOpen"
      class="yk-dialog"
      width="min(1240px, 94vw)"
      :close-on-click-modal="false"
      destroy-on-close
    >
      <div class="yk-dialog-body">
        <YiKnowChat v-if="ykOpen" />
      </div>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Collection, Cpu, Link, MagicStick } from '@element-plus/icons-vue';
import { aiCenterSquareApi } from '@/api/ai';
import type { AIAgent, AIKnowledgeBase, AIIntegration } from '@/types/ai';
import { aiSquareExt } from './ai-api';
import StudioSection from './studio-section.vue';
import AgentHallCard from './components/AgentHallCard.vue';
import KbHallCard from './components/KbHallCard.vue';
import IntegrationLinkCard from './components/IntegrationLinkCard.vue';
import FlatBlock from './components/FlatBlock.vue';
import YiKnowChat from './yi-know-chat.vue';

const FLAT_SIZE = 6;

const stats = ref<{ agentTotal?: number; kbTotal?: number }>({});
const agents = ref<AIAgent[]>([]);
const kbs = ref<AIKnowledgeBase[]>([]);
const integrations = ref<AIIntegration[]>([]);
const ykOpen = ref(false);

async function load() {
  try {
    const [agentRes, kbRes, intRes] = await Promise.all([
      aiCenterSquareApi.agents({ sort: 'hot', pageSize: FLAT_SIZE }),
      aiCenterSquareApi.kbs({ sort: 'hot', pageSize: FLAT_SIZE }),
      aiSquareExt.integrations()
    ]);
    agents.value = agentRes.items;
    stats.value = { ...stats.value, agentTotal: agentRes.total };
    kbs.value = kbRes.items;
    stats.value = { ...stats.value, kbTotal: kbRes.total };
    integrations.value = intRes.items;
  } catch {
    /* 加载失败静默降级，保留空态 */
  }
}

function scrollToSquare() {
  document.getElementById('square')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
function scrollToStudio() {
  document.getElementById('studio')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

onMounted(() => {
  load();
  // 锚点定位：/square、/studio 旧路由重定向到本页 #square/#studio
  const hash = window.location.hash.slice(1);
  if (hash) {
    setTimeout(() => {
      document.getElementById(hash)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  }
});
</script>

<style scoped>
.ai-landing {
  max-width: 1400px;
  margin: 0 auto;
}
.hero {
  background: linear-gradient(135deg, #409eff, #79bbff);
  border-radius: 0 0 16px 16px;
  padding: 48px 32px;
}
.hero-inner {
  max-width: 1200px;
  margin: 0 auto;
}
.hero-flex {
  display: flex;
  align-items: center;
  gap: 40px;
}
.hero-left {
  flex: 1;
  min-width: 0;
}
.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: #fff;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 2px;
  border: 1px solid rgba(255, 255, 255, 0.35);
  background: rgba(255, 255, 255, 0.12);
  padding: 6px 14px;
  border-radius: 999px;
  margin-bottom: 20px;
}
.hero-title {
  font-size: 32px;
  font-weight: 700;
  color: #fff;
  margin: 0;
  line-height: 1.3;
}
.hero-sub {
  display: block;
  font-size: 22px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.85);
  margin-top: 8px;
}
.hero-desc {
  color: rgba(255, 255, 255, 0.85);
  font-size: 14px;
  line-height: 1.7;
  max-width: 560px;
  margin: 16px 0 24px;
}
.hero-cta {
  --el-button-bg-color: #fff;
  --el-button-text-color: #409eff;
  --el-button-hover-bg-color: #fde047;
  --el-button-hover-text-color: #334155;
  border: none;
  height: 40px;
  padding: 0 24px;
  font-weight: 600;
}
.hero-right {
  flex-shrink: 0;
}
.hero-card {
  width: 340px;
  border: 1px solid rgba(255, 255, 255, 0.25);
  background: rgba(255, 255, 255, 0.12);
  backdrop-filter: blur(12px);
  border-radius: 16px;
  padding: 32px;
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.15);
  color: #fff;
}
.hero-brand {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 2px;
  border: 1px solid rgba(255, 255, 255, 0.3);
  background: rgba(255, 255, 255, 0.1);
  padding: 4px 12px;
  border-radius: 999px;
  margin-bottom: 20px;
}
.hero-card-title {
  font-size: 24px;
  font-weight: 700;
  line-height: 1.3;
}
.hero-card-slogan {
  font-size: 14px;
  color: rgba(255, 255, 255, 0.75);
  margin-top: 8px;
}
.hero-card-desc {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.6);
  line-height: 1.6;
  margin: 16px 0 24px;
}
.hero-card-btn {
  --el-button-bg-color: #fff;
  --el-button-text-color: #409eff;
  --el-button-hover-bg-color: #fde047;
  --el-button-hover-text-color: #334155;
  border: none;
  height: 40px;
  padding: 0 24px;
  font-weight: 600;
}
.stats-wrap {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 32px;
}
.stats-bar {
  display: flex;
  gap: 16px;
  margin-top: -20px;
  position: relative;
  z-index: 2;
}
.stat-item {
  flex: 1;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.08);
  padding: 16px 20px;
  display: flex;
  align-items: center;
  gap: 14px;
}
.stat-icon {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 22px;
}
.stat-value {
  font-size: 20px;
  font-weight: 700;
  color: #0f172a;
}
.stat-label {
  color: #64748b;
  font-size: 12px;
  margin-top: 2px;
}
.landing-main {
  max-width: 1200px;
  margin: 0 auto;
  padding: 32px;
  display: flex;
  flex-direction: column;
  gap: 40px;
}
.scroll-anchor {
  scroll-margin-top: 20px;
}
.section-title {
  margin-bottom: 16px;
}
.section-title h2 {
  font-size: 20px;
  font-weight: 700;
  color: #0f172a;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 8px;
}
.title-bar {
  display: inline-block;
  width: 4px;
  height: 20px;
  border-radius: 2px;
  background: linear-gradient(180deg, #409eff, #79bbff);
  margin-right: 4px;
}
.section-title p {
  color: #909399;
  font-size: 14px;
  margin: 6px 0 0 12px;
}
.flat-block {
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.04);
  overflow: hidden;
  margin-bottom: 16px;
}
.flat-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 20px 24px;
  border-bottom: 1px solid #f0f0f0;
}
.flat-head-left {
  display: flex;
  align-items: center;
  gap: 12px;
}
.flat-icon {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  background: var(--el-color-primary-light-9);
  border: 1px solid var(--el-color-primary-light-7);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  flex-shrink: 0;
}
.flat-title {
  font-size: 16px;
  font-weight: 700;
  color: #0f172a;
  margin: 0;
  display: flex;
  align-items: center;
  gap: 8px;
}
.flat-count {
  color: #64748b;
  font-size: 13px;
  font-weight: 400;
}
.flat-desc {
  color: #94a3b8;
  font-size: 12px;
  margin: 2px 0 0;
}
.flat-more {
  color: var(--el-color-primary);
  font-size: 14px;
  text-decoration: none;
  flex-shrink: 0;
}
.flat-more:hover {
  text-decoration: underline;
}
.flat-body {
  padding: 20px;
}
.flat-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 20px;
}
.flat-empty {
  border: 1px dashed #e4e7ed;
  border-radius: 12px;
  padding: 40px;
  text-align: center;
}
.flat-empty p {
  color: #909399;
  font-size: 14px;
  margin: 0;
}
.cta-card {
  background: linear-gradient(90deg, #409eff, #409eff);
  border-radius: 16px;
  padding: 24px 32px;
  box-shadow: 0 8px 24px rgba(22, 119, 255, 0.25);
  display: flex;
  align-items: center;
  gap: 16px;
  position: relative;
  overflow: hidden;
}
.cta-icon {
  width: 56px;
  height: 56px;
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.15);
  border: 1px solid rgba(255, 255, 255, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 28px;
  flex-shrink: 0;
}
.cta-text {
  flex: 1;
  min-width: 0;
}
.cta-text h2 {
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  margin: 0;
}
.cta-text p {
  color: rgba(255, 255, 255, 0.8);
  font-size: 14px;
  margin: 6px 0 0;
  max-width: 640px;
}
.cta-btn {
  --el-button-bg-color: #fff;
  --el-button-text-color: #409eff;
  border: none;
  height: 40px;
  padding: 0 24px;
  font-weight: 600;
  flex-shrink: 0;
}
.yk-dialog-body {
  height: 80vh;
}
</style>

// frontend/edu/app/portal/apps/ai/landing/page.tsx
'use client'

// AI 智能服务中心前台主页（/portal/apps/ai/landing）v1.3
// 单页集成（spec §2.1）：YIKnow hero（全局助手主推 + 对话入口）→ 我的工坊（#studio）
// → AI 广场平铺（#square：智能体/知识库/第三方服务三区，取消 Tab，各配专属卡片样式，
// 「查看更多」进大厅页 hall/agents、hall/kbs）。
// 旧路由 /square、/studio 重定向至本页对应锚点；大厅页路由 /hall/* 独立存在。
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import { Bot, BookOpen, Blocks, ArrowRight, Sparkles } from 'lucide-react'
import { LandingShell } from '@/components/shared/landing-shell'
import { YIKnowChatDialog, useYIKnowChatDialog } from '../_components/yi-know-chat-dialog'
import { aiCenterSquareApi } from '@/lib/api'
import type { AIAgent, AIKnowledgeBase, AIIntegration } from '@/lib/api'
import { useT } from '@/lib/i18n/locale-provider'
import { reportError } from '@/lib/error-handling'
import { StudioSection } from '../_components/studio-section'
import { AgentHallCard, KbHallCard, IntegrationLinkCard } from '../_components/hall-cards'

const FLAT_SIZE = 6

interface LandingData {
  agents: AIAgent[]
  agentTotal: number
  kbs: AIKnowledgeBase[]
  kbTotal: number
  integrations: AIIntegration[]
}

export default function AILandingPage() {
  const t = useT()
  const { openChat, dialogProps } = useYIKnowChatDialog()
  const [data, setData] = useState<LandingData | null>(null)
  const squareRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    let cancelled = false
    Promise.all([
      aiCenterSquareApi.agents({ sort: 'hot', pageSize: FLAT_SIZE }),
      aiCenterSquareApi.kbs({ sort: 'hot', pageSize: FLAT_SIZE }),
      aiCenterSquareApi.integrations(),
    ])
      .then(([agents, kbs, integrations]) => {
        if (cancelled) return
        setData({
          agents: agents.items,
          agentTotal: agents.total,
          kbs: kbs.items,
          kbTotal: kbs.total,
          integrations: integrations.items,
        })
      })
      .catch((err) => {
        if (!cancelled) reportError(err, 'ai-landing')
      })
    return () => {
      cancelled = true
    }
  }, [])

  // 锚点定位：/square、/studio 旧路由重定向到本页 #square/#studio，加载后平滑滚动到对应区块
  useEffect(() => {
    const hash = window.location.hash.slice(1)
    if (!hash) return
    const timer = setTimeout(() => {
      document.getElementById(hash)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }, 100)
    return () => clearTimeout(timer)
  }, [])

  return (
    <>
    <LandingShell
      hero={{
        badge: t('AI 智能服务平台'),
        // 两行标题对齐 /job/landing 风格：首行白色，次行 text-white/80
        title: (
          <>
            {t('AI 赋能场景化数智教学')}
            <br />
            <span className="text-white/80">{t('培养适应复合型岗位新需求人才')}</span>
          </>
        ),
        description: t(
          '融合场景化数智教学模式，为职业教育提供智能化教学辅助、岗位能力评估、个性化学习路径规划等全方位AI服务，助力培养适应产业需求的高素质技术技能人才。',
        ),
        // 仅保留「逛逛 AI 广场」（滚动到 AI 广场区块，LandingShell listRef=#square）
        ctaLabel: t('逛逛 AI 广场'),
        right: (
          // v2.4：hero 右侧 YIKnow 品牌展示卡（品牌标签 + 定位 + 口号 + 能力说明 + 立即体验）
          <div className="rounded-2xl border border-white/20 bg-white/10 backdrop-blur-md p-8 shadow-xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-3 py-1 text-xs font-semibold tracking-widest text-white/90 mb-5">
              <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
              YI KNOW
            </div>
            <div className="text-2xl font-bold text-white leading-snug">
              {t('职业教育场景化教学智能助理')}
            </div>
            <div className="text-sm text-white/70 mt-2">
              You Ask · I Know · {t('你问，我懂')}
            </div>
            <p className="text-xs text-white/60 leading-relaxed mt-4">
              {t('集成多元大模型能力，以知识库与智能体全面赋能职业教育场景化教学')}
            </p>
            <button
              onClick={openChat}
              className="inline-flex items-center gap-1.5 mt-6 rounded-full bg-white text-primary px-6 h-10 text-sm font-semibold leading-10 hover:bg-yellow-300 hover:text-slate-800 transition-colors"
            >
              {t('立即体验')}
              <span aria-hidden>→</span>
            </button>
          </div>
        ),
      }}
      stats={[
        { icon: Bot, value: data?.agentTotal ?? '-', label: t('已发布智能体') },
        { icon: BookOpen, value: data?.kbTotal ?? '-', label: t('已发布知识库') },
        { icon: Blocks, value: data?.integrations.length ?? '-', label: t('第三方服务') },
      ]}
      listRef={squareRef}
    >
      <div className="space-y-14">
        {/* 第一区：我的工坊（师生主诉求：创建/管理） */}
        <section id="studio" className="scroll-mt-20">
          <StudioSection />
        </section>

        {/* 第二区：AI 广场（平铺三板块，无 Tab） */}
        <section id="square" ref={squareRef} className="scroll-mt-20 space-y-8">
          <div>
            <h2 className="text-xl font-bold text-[#0f172a] flex items-center gap-2">
              <span className="w-1 h-5 rounded-full bg-gradient-to-b from-primary/80 to-primary/70" />
              {t('AI 广场')}
            </h2>
            <p className="text-sm text-muted-foreground mt-1.5 ml-3">
              {t('全校师生共建共享的智能体、知识库与第三方服务')}
            </p>
          </div>

          {/* 智能体板块 */}
          <FlatBlock
            title={t('智能体')}
            desc={t('点开即聊的 AI 助手')}
            icon={<Bot className="w-5 h-5 text-primary" />}
            count={data?.agentTotal}
            moreHref="/portal/apps/ai/hall/agents"
            moreLabel={t('查看更多')}
            emptyLabel={t('暂无已发布智能体')}
            hasItems={!!data && data.agents.length > 0}
          >
            {data?.agents.map((a) => <AgentHallCard key={a.id} agent={a} />)}
          </FlatBlock>

          {/* 知识库板块 */}
          <FlatBlock
            title={t('知识库')}
            desc={t('可提问的资料库')}
            icon={<BookOpen className="w-5 h-5 text-primary" />}
            count={data?.kbTotal}
            moreHref="/portal/apps/ai/hall/kbs"
            moreLabel={t('查看更多')}
            emptyLabel={t('暂无已发布知识库')}
            hasItems={!!data && data.kbs.length > 0}
          >
            {data?.kbs.map((kb) => <KbHallCard key={kb.id} kb={kb} />)}
          </FlatBlock>

          {/* 第三方服务板块 */}
          <FlatBlock
            title={t('第三方服务')}
            desc={t('管理员精选挂接的外部智能体与应用')}
            icon={<Blocks className="w-5 h-5 text-primary" />}
            count={data?.integrations.length}
            emptyLabel={t('暂无第三方服务')}
            hasItems={!!data && data.integrations.length > 0}
          >
            {data?.integrations.map((it) => <IntegrationLinkCard key={it.id} item={it} />)}
          </FlatBlock>
        </section>

        {/* 底部行动卡：引导创作 */}
        <section className="bg-gradient-to-r from-primary via-primary to-primary/80 rounded-2xl p-6 sm:p-8 shadow-[0_8px_24px_rgba(22,119,255,0.25)] relative overflow-hidden">
          <div className="absolute top-[-60px] right-[-40px] w-64 h-64 rounded-full bg-white/10 blur-3xl pointer-events-none" />
          <div className="relative z-10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-5">
            <div className="flex items-start gap-4">
              <div className="w-14 h-14 rounded-2xl bg-white/15 backdrop-blur-sm border border-white/20 flex items-center justify-center shrink-0">
                <Sparkles className="w-7 h-7 text-white" />
              </div>
              <div>
                <h2 className="text-lg font-bold text-white">
                  {t('把你的知识变成全校可用的 AI 服务')}
                </h2>
                <p className="text-sm text-white/80 mt-1 max-w-xl">
                  {t('上传资料建成知识库，或配置一个专属智能体，审核通过后即可发布到广场。')}
                </p>
              </div>
            </div>
            <div className="flex gap-2.5 shrink-0">
              <button
                onClick={() =>
                  document.getElementById('studio')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
                }
                className="rounded-full bg-white text-primary hover:bg-primary/5 px-6 h-10 text-sm font-semibold shadow-lg transition-all hover:-translate-y-0.5"
              >
                {t('去工坊创作')}
              </button>
            </div>
          </div>
        </section>
      </div>
    </LandingShell>
      {/* v2.7：YIKnow 聊天统一弹窗入口 */}
      <YIKnowChatDialog {...dialogProps} />
    </>
  )
}

function FlatBlock({
  title,
  desc,
  icon,
  count,
  moreHref,
  moreLabel,
  emptyLabel,
  emptyHref,
  hasItems,
  children,
}: {
  title: string
  desc: string
  icon: React.ReactNode
  count?: number
  moreHref?: string
  moreLabel?: string
  emptyLabel: string
  emptyHref?: string
  hasItems: boolean
  children?: React.ReactNode
}) {
  const t = useT()
  return (
    <div className="bg-white rounded-2xl border border-[#e7e5e4] shadow-[0_4px_20px_rgba(0,0,0,0.04)] overflow-hidden">
      <div className="px-6 pt-5 pb-4 flex items-center justify-between gap-4 border-b border-slate-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/10 flex items-center justify-center shrink-0">
            {icon}
          </div>
          <div>
            <h3 className="text-base font-bold text-[#0f172a] flex items-center gap-2">
              {title}
              {count != null && (
                <span className="text-[13px] text-[#64748b] font-normal">({count})</span>
              )}
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">{desc}</p>
          </div>
        </div>
        {moreHref && (
          <Link
            to={moreHref}
            className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline shrink-0"
          >
            {moreLabel}
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        )}
      </div>
      <div className="p-5">
        {hasItems ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">{children}</div>
        ) : (
          <div className="rounded-xl border border-dashed border-border py-10 text-center">
            <p className="text-sm text-muted-foreground">{t(emptyLabel)}</p>
            {emptyHref && (
              <a
                href={emptyHref}
                className="inline-flex items-center mt-3 rounded-full bg-primary text-white px-5 h-9 text-sm font-medium hover:bg-primary/90"
              >
                {t('去创建')}
              </a>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
