// frontend/portal-vue/src/views/ai/components/AgentForm.vue
<template>
  <div class="agent-form">
    <!-- 基本信息 -->
    <el-card shadow="never" class="form-card">
      <template #header>
        <div class="card-head">
          <div class="card-title">基本信息</div>
          <div class="card-desc">名称、头像与分类决定了它在大厅中的展示与筛选</div>
        </div>
      </template>
      <el-form label-position="top">
        <el-form-item label="名称">
          <el-input v-model="name" placeholder="智能体名称" maxlength="100" />
        </el-form-item>
        <el-form-item label="头像">
          <div class="avatar-row">
            <span
              v-for="e in PRESET_AVATARS"
              :key="e"
              class="avatar-opt"
              :class="{ active: avatar === e }"
              @click="setAvatar(e)"
            >{{ e }}</span>
            <el-input v-model="avatar" class="avatar-input" maxlength="8" placeholder="输入 emoji" />
          </div>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="description" placeholder="描述智能体的用途" maxlength="200" />
        </el-form-item>
        <el-form-item label="封面">
          <div class="cover-row">
            <el-button size="small" :loading="coverUploading" @click="pickCover">上传封面</el-button>
            <span v-if="coverUrl" class="cover-preview" :style="{ backgroundImage: `url('${coverUrl}')` }" />
            <el-button v-if="coverUrl" size="small" text type="danger" @click="coverUrl = ''">移除</el-button>
            <input ref="coverInput" type="file" accept="image/*" style="display: none" @change="onCoverPick" />
          </div>
        </el-form-item>
        <el-form-item>
          <ClassifySelects :value="classify" @update:value="onClassify" />
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 对话设定 -->
    <el-card shadow="never" class="form-card">
      <template #header>
        <div class="card-head">
          <div class="card-title">对话设定</div>
          <div class="card-desc">开场白与角色提示词直接决定对话风格与回答边界</div>
        </div>
      </template>
      <el-form label-position="top">
        <el-form-item label="开场白">
          <el-input v-model="greeting" type="textarea" :rows="2" maxlength="500" placeholder="用户进入对话时展示的欢迎语" />
        </el-form-item>
        <el-form-item>
          <div class="prompt-label">
            <span>角色提示词</span>
            <span :class="['prompt-count', { over: promptLen > MAX_PROMPT_LEN }]">{{ promptLen }}/4000 字</span>
          </div>
          <el-input v-model="systemPrompt" type="textarea" :rows="8" placeholder="定义智能体的角色设定与回答规则" />
        </el-form-item>
      </el-form>
    </el-card>

    <!-- 关联知识库 -->
    <el-card shadow="never" class="form-card">
      <template #header>
        <div class="card-head">
          <div class="card-title">关联知识库</div>
          <div class="card-desc">勾选后对话将基于库内文档检索回答（我创建的 / 共享给我的 / 广场已发布）</div>
        </div>
      </template>
      <div class="kb-head">
        <span>关联知识库</span>
        <span class="kb-count">最多关联 5 个知识库（已选 {{ kbIds.length }}/5）</span>
      </div>
      <div class="kb-list">
        <div v-if="loadingKbs" class="kb-loading">加载中...</div>
        <p v-else-if="!kbOptions.length" class="kb-empty">暂无可关联的知识库</p>
        <label
          v-for="kb in kbOptions"
          :key="kb.id"
          class="kb-item"
          :class="{ disabled: !kbIds.includes(kb.id) && kbIds.length >= MAX_KB }"
        >
          <el-checkbox
            :model-value="kbIds.includes(kb.id)"
            :disabled="!kbIds.includes(kb.id) && kbIds.length >= MAX_KB"
            @change="toggleKb(kb.id)"
          />
          <span class="kb-name">{{ kb.name }}</span>
          <span class="kb-docs">{{ kb.docCount }} 个文档</span>
        </label>
      </div>
    </el-card>

    <div class="form-actions">
      <el-button type="primary" :loading="submitting" @click="submit">{{ submitLabel }}</el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { aiCenterKbApi, aiCenterSquareApi } from '@/api/ai';
import type { AIAgent, AIKnowledgeBase } from '@/types/ai';
import { aiKbExt, fileApi } from '../ai-api';
import ClassifySelects from './ClassifySelects.vue';
import type { ClassifyValue } from './ClassifySelects.vue';

const MAX_PROMPT_LEN = 4000;
const MAX_KB = 5;
const PRESET_AVATARS = ['🤖', '🧠', '📚', '💡', '🎓', '🧪', '📝', '🗣️', '🔬', '🎨', '🎵', '⚽'];

interface AgentInput {
  name: string;
  avatar?: string;
  description?: string;
  coverImage?: string;
  greeting?: string;
  systemPrompt: string;
  kbIds?: string[];
  majorId?: string;
  departmentId?: string;
}

const props = defineProps<{
  initial?: AIAgent;
  submitLabel: string;
  onSubmit: (input: AgentInput) => Promise<void>;
  onLiveChange?: (v: { prompt: string; name: string; avatar: string }) => void;
}>();

const name = ref(props.initial?.name ?? '');
const avatar = ref(props.initial?.avatar ?? '🤖');
const description = ref(props.initial?.description ?? '');
const greeting = ref(props.initial?.greeting ?? '');
const systemPrompt = ref(props.initial?.systemPrompt ?? '');
const classify = ref<ClassifyValue>({
  majorId: props.initial?.majorId ?? '',
  departmentId: props.initial?.departmentId ?? '',
  kbType: ''
});
const kbIds = ref<string[]>(props.initial?.kbIds ?? []);
const coverUrl = ref(props.initial?.coverImage ?? '');
const coverUploading = ref(false);
const coverInput = ref<HTMLInputElement | null>(null);
const kbOptions = ref<AIKnowledgeBase[]>([]);
const loadingKbs = ref(true);
const submitting = ref(false);

const promptLen = computed(() => Array.from(systemPrompt.value).length);

function emitLive() {
  props.onLiveChange?.({ prompt: systemPrompt.value, name: name.value, avatar: avatar.value });
}
function setName(v: string) {
  name.value = v;
  emitLive();
}
function setAvatar(v: string) {
  avatar.value = v;
  emitLive();
}
function setPrompt(v: string) {
  systemPrompt.value = v;
  emitLive();
}

function onClassify(v: ClassifyValue) {
  classify.value = v;
}

function toggleKb(id: string) {
  if (kbIds.value.includes(id)) {
    kbIds.value = kbIds.value.filter((x) => x !== id);
  } else if (kbIds.value.length < MAX_KB) {
    kbIds.value = [...kbIds.value, id];
  }
}

async function loadKbOptions() {
  const results = await Promise.allSettled([
    aiKbExt.listMine({ scope: 'owned' }),
    aiKbExt.listMine({ scope: 'collaborating' }),
    aiCenterSquareApi.kbs({ pageSize: 100 })
  ]);
  const seen = new Map<string, AIKnowledgeBase>();
  for (const r of results) {
    if (r.status === 'fulfilled') {
      for (const kb of r.value.items) if (!seen.has(kb.id)) seen.set(kb.id, kb);
    }
  }
  kbOptions.value = Array.from(seen.values());
  loadingKbs.value = false;
}

function pickCover() {
  coverInput.value?.click();
}
async function onCoverPick(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  input.value = '';
  if (!file) return;
  if (file.size > 5 * 1024 * 1024) {
    ElMessage.warning('文件大小不能超过 5MB');
    return;
  }
  if (!file.type.startsWith('image/')) {
    ElMessage.warning('请上传图片文件');
    return;
  }
  coverUploading.value = true;
  try {
    const res = await fileApi.upload(file);
    coverUrl.value = res.url;
  } catch (err) {
    ElMessage.error((err as Error).message || '上传失败');
  } finally {
    coverUploading.value = false;
  }
}

async function submit() {
  if (!name.value.trim()) {
    ElMessage.warning('请填写名称');
    return;
  }
  if (!systemPrompt.value.trim()) {
    ElMessage.warning('请填写角色提示词');
    return;
  }
  submitting.value = true;
  try {
    await props.onSubmit({
      name: name.value.trim(),
      avatar: avatar.value.trim(),
      description: description.value.trim(),
      coverImage: coverUrl.value || undefined,
      greeting: greeting.value.trim(),
      systemPrompt: systemPrompt.value.trim(),
      kbIds: kbIds.value,
      majorId: classify.value.majorId || undefined,
      departmentId: classify.value.departmentId || undefined
    });
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    submitting.value = false;
  }
}

onMounted(loadKbOptions);
</script>

<style scoped>
.agent-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}
.form-card :deep(.el-card__header) {
  padding: 16px 20px 12px;
  border-bottom: 1px dashed #e7e5e4;
}
.card-head .card-title {
  font-size: 14px;
  font-weight: 600;
  color: #0f172a;
}
.card-desc {
  font-size: 12px;
  color: #909399;
  margin-top: 4px;
}
.avatar-row {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-wrap: wrap;
}
.avatar-opt {
  width: 36px;
  height: 36px;
  border-radius: 6px;
  border: 1px solid #dcdfe6;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
  cursor: pointer;
}
.avatar-opt.active {
  border-color: var(--el-color-primary);
  background: var(--el-color-primary-light-9);
}
.avatar-input {
  width: 120px;
}
.cover-row {
  display: flex;
  align-items: center;
  gap: 12px;
}
.cover-preview {
  width: 60px;
  height: 40px;
  border-radius: 6px;
  background-size: cover;
  background-position: center;
  border: 1px solid #e4e7ed;
}
.prompt-label {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  margin-bottom: 6px;
  font-size: 14px;
  color: #606266;
}
.prompt-count {
  font-size: 12px;
  color: #909399;
}
.prompt-count.over {
  color: #f56c6c;
}
.kb-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
  font-size: 14px;
  color: #606266;
}
.kb-count {
  font-size: 12px;
  color: #909399;
}
.kb-list {
  border: 1px solid #dcdfe6;
  border-radius: 6px;
  max-height: 256px;
  overflow-y: auto;
}
.kb-loading,
.kb-empty {
  padding: 16px;
  text-align: center;
  color: #909399;
  font-size: 14px;
  margin: 0;
}
.kb-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 16px;
  font-size: 14px;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;
}
.kb-item:last-child {
  border-bottom: none;
}
.kb-item:hover {
  background: #f5f7fa;
}
.kb-item.disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.kb-name {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.kb-docs {
  color: #909399;
  font-size: 12px;
}
.form-actions {
  display: flex;
  justify-content: flex-end;
}
</style>

// frontend/edu/app/portal/apps/ai/studio/components/agent-form.tsx
'use client'

// 智能体编辑共用表单（新建/编辑页共用，v2.6 分卡片版：基本信息 / 对话设定 / 关联知识库）。
// 实时试聊面板由编辑页右栏承载（onPromptChange 上提当前提示词），表单内不再内嵌。
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Loader2 } from 'lucide-react'
import { useToast } from '@zhiyu/ui'
import { aiCenterKbApi, aiCenterSquareApi, fileApi } from '@/lib/api'
import { CoverImageUpload } from '@/components/shared/cover-image-upload'
import type { AIAgent, AIAgentInput, AIKnowledgeBase } from '@/lib/api'
import { useT } from '@/lib/i18n/locale-provider'
import { ClassifySelects, type ClassifyValue } from '../../_components/classify-selects'
import { EditorCard } from '../../_components/studio-editor-shell'

const MAX_PROMPT_LEN = 4000
const MAX_KB = 5
const PRESET_AVATARS = ['🤖', '🧠', '📚', '💡', '🎓', '🧪', '📝', '🗣️', '🔬', '🎨', '🎵', '⚽']

interface AgentFormProps {
  initial?: AIAgent
  submitLabel: string
  onSubmit: (input: AIAgentInput) => Promise<void>
  /** 表单实时状态上提（编辑页右栏实时试聊用：提示词 + 名称 + 头像） */
  onLiveChange?: (v: { prompt: string; name: string; avatar: string }) => void
}

export function AgentForm({ initial, submitLabel, onSubmit, onLiveChange }: AgentFormProps) {
  const t = useT()
  const { toast } = useToast()
  const [name, setNameState] = useState(initial?.name ?? '')
  const [avatar, setAvatarState] = useState(initial?.avatar ?? '🤖')
  const [description, setDescription] = useState(initial?.description ?? '')
  const [greeting, setGreeting] = useState(initial?.greeting ?? '')
  const [systemPrompt, setSystemPromptState] = useState(initial?.systemPrompt ?? '')
  const liveRef = { prompt: systemPrompt, name, avatar }
  const emitLive = (patch: Partial<typeof liveRef>) => {
    onLiveChange?.({ ...liveRef, ...patch })
  }
  const setName = (v: string) => {
    setNameState(v)
    emitLive({ name: v })
  }
  const setAvatar = (v: string) => {
    setAvatarState(v)
    emitLive({ avatar: v })
  }
  const setSystemPrompt = (v: string) => {
    setSystemPromptState(v)
    emitLive({ prompt: v })
  }
  const [classify, setClassify] = useState<ClassifyValue>({
    majorId: initial?.majorId ?? '',
    departmentId: initial?.departmentId ?? '',
    kbType: '',
  })
  const [kbIds, setKbIds] = useState<string[]>(initial?.kbIds ?? [])
  const [coverUrl, setCoverUrl] = useState(initial?.coverImage ?? '')
  const [coverUploading, setCoverUploading] = useState(false)
  const [kbOptions, setKbOptions] = useState<AIKnowledgeBase[]>([])
  const [loadingKbs, setLoadingKbs] = useState(true)
  const [submitting, setSubmitting] = useState(false)

  // 三路合并去重：我创建的 / 共享给我的 / 广场已发布的（spec §3.1 AG-1 关联范围）
  useEffect(() => {
    let cancelled = false
    Promise.allSettled([
      aiCenterKbApi.listMine({ scope: 'owned' }),
      aiCenterKbApi.listMine({ scope: 'collaborating' }),
      aiCenterSquareApi.kbs({ pageSize: 100 }),
    ]).then((results) => {
      if (cancelled) return
      const seen = new Map<string, AIKnowledgeBase>()
      for (const r of results) {
        if (r.status === 'fulfilled') {
          for (const kb of r.value.items) {
            if (!seen.has(kb.id)) seen.set(kb.id, kb)
          }
        }
      }
      setKbOptions(Array.from(seen.values()))
      setLoadingKbs(false)
    })
    return () => {
      cancelled = true
    }
  }, [])

  const toggleKb = useCallback((id: string) => {
    setKbIds((prev) => {
      if (prev.includes(id)) return prev.filter((x) => x !== id)
      if (prev.length >= MAX_KB) return prev
      return [...prev, id]
    })
  }, [])

  const promptLen = useMemo(() => Array.from(systemPrompt).length, [systemPrompt])

  // 封面上传（复用通用 CoverImageUpload，fileApi 本地存储，≤5MB）
  const handleCoverUpload = async (file: File) => {
    if (file.size > 5 * 1024 * 1024) {
      toast({ variant: 'destructive', title: t('提示'), description: t('文件大小不能超过 5MB') })
      return
    }
    if (!file.type.startsWith('image/')) {
      toast({ variant: 'destructive', title: t('提示'), description: t('请上传图片文件') })
      return
    }
    setCoverUploading(true)
    try {
      const res = await fileApi.upload(file)
      setCoverUrl(res.url)
    } catch (err: unknown) {
      toast({
        variant: 'destructive',
        title: t('上传失败'),
        description: err instanceof Error ? err.message : undefined,
      })
    } finally {
      setCoverUploading(false)
    }
  }

  const handleSubmit = async () => {
    if (!name.trim()) {
      toast({ title: t('请填写名称'), variant: 'destructive' })
      return
    }
    if (!systemPrompt.trim()) {
      toast({ title: t('请填写角色提示词'), variant: 'destructive' })
      return
    }
    setSubmitting(true)
    try {
      await onSubmit({
        name: name.trim(),
        avatar: avatar.trim(),
        description: description.trim(),
        coverImage: coverUrl || undefined,
        greeting: greeting.trim(),
        systemPrompt: systemPrompt.trim(),
        kbIds,
        majorId: classify.majorId || undefined,
        departmentId: classify.departmentId || undefined,
      })
    } catch (err) {
      toast({
        title: t('操作失败'),
        description: err instanceof Error ? err.message : undefined,
        variant: 'destructive',
      })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="space-y-5">
      <EditorCard title={t('基本信息')} desc={t('名称、头像与分类决定了它在大厅中的展示与筛选')}>
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label>{t('名称')}</Label>
          <Input
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder={t('智能体名称')}
            maxLength={100}
          />
        </div>
        <div className="space-y-2">
          <Label>{t('头像')}</Label>
          <div className="flex items-center gap-2 flex-wrap">
            {PRESET_AVATARS.map((emoji) => (
              <button
                key={emoji}
                type="button"
                onClick={() => setAvatar(emoji)}
                className={`w-9 h-9 rounded-md border text-lg flex items-center justify-center transition-colors ${
                  avatar === emoji
                    ? 'border-primary bg-primary/10'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                {emoji}
              </button>
            ))}
            <Input
              value={avatar}
              onChange={(e) => setAvatar(e.target.value)}
              className="w-20"
              maxLength={8}
              placeholder={t('输入 emoji')}
            />
          </div>
        </div>
      </div>

      <div className="space-y-2">
        <Label>{t('描述')}</Label>
        <Input
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder={t('描述智能体的用途')}
          maxLength={200}
        />
      </div>

      <div className="space-y-2 max-w-[400px] mt-4">
        <CoverImageUpload
          imageUrl={coverUrl}
          uploading={coverUploading}
          label={t('封面')}
          alt={t('智能体封面')}
          onUpload={handleCoverUpload}
          onRemove={() => setCoverUrl('')}
        />
      </div>

      <div className="mt-4">
        <ClassifySelects value={classify} onChange={setClassify} />
      </div>
      </EditorCard>

      <EditorCard title={t('对话设定')} desc={t('开场白与角色提示词直接决定对话风格与回答边界')}>
      <div className="space-y-2">
        <Label>{t('开场白')}</Label>
        <Textarea
          value={greeting}
          onChange={(e) => setGreeting(e.target.value)}
          placeholder={t('用户进入对话时展示的欢迎语')}
          rows={2}
          maxLength={500}
        />
      </div>

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label>{t('角色提示词')}</Label>
          <span className={`text-xs ${promptLen > MAX_PROMPT_LEN ? 'text-red-600' : 'text-muted-foreground'}`}>
            {t('{count}/4000 字', { count: promptLen })}
          </span>
        </div>
        <Textarea
          value={systemPrompt}
          onChange={(e) => setSystemPrompt(e.target.value)}
          placeholder={t('定义智能体的角色设定与回答规则')}
          rows={8}
        />
      </div>

      </EditorCard>

      <EditorCard
        title={t('关联知识库')}
        desc={t('勾选后对话将基于库内文档检索回答（我创建的 / 共享给我的 / 广场已发布）')}
      >
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label>{t('关联知识库')}</Label>
          <span className="text-xs text-muted-foreground">
            {t('最多关联 5 个知识库（已选 {count}/5）', { count: kbIds.length })}
          </span>
        </div>
        <div className="rounded-md border border-gray-200 divide-y divide-gray-100 max-h-64 overflow-y-auto">
          {loadingKbs ? (
            <div className="px-4 py-6 text-sm text-muted-foreground flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" />
              {t('加载中...')}
            </div>
          ) : kbOptions.length === 0 ? (
            <p className="px-4 py-6 text-sm text-muted-foreground">{t('暂无可关联的知识库')}</p>
          ) : (
            kbOptions.map((kb) => {
              const checked = kbIds.includes(kb.id)
              const disabled = !checked && kbIds.length >= MAX_KB
              return (
                <label
                  key={kb.id}
                  className={`flex items-center gap-3 px-4 py-2.5 text-sm ${
                    disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer hover:bg-muted/50'
                  }`}
                >
                  <Checkbox checked={checked} disabled={disabled} onCheckedChange={() => toggleKb(kb.id)} />
                  <span className="flex-1 truncate">{kb.name}</span>
                  <span className="text-xs text-muted-foreground">
                    {t('{count} 个文档', { count: kb.docCount })}
                  </span>
                </label>
              )
            })
          )}
        </div>
      </div>
      </EditorCard>

      <div className="flex justify-end">
        <Button onClick={handleSubmit} disabled={submitting} className="px-8">
          {submitting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
          {submitLabel}
        </Button>
      </div>
    </div>
  )
}
