// apps/edu/app/portal/workspace/_components/school-admin-resources-tab.tsx
'use client'

import { useEffect, useState } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  BookOpen,
  Briefcase,
  CheckSquare,
  ClipboardList,
  Database,
  FileText,
  Layers,
  TrendingUp,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { SectionCard } from './section-card'
import { portalApi } from '@/lib/api'
import type { WorkspaceDashboard } from '@/lib/types'
import { Line, LineChart, XAxis, YAxis, CartesianGrid, ResponsiveContainer } from 'recharts'
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart'

const iconMap: Record<string, LucideIcon> = {
  'book-open': BookOpen,
  layers: Layers,
  briefcase: Briefcase,
  'file-text': FileText,
  'check-circle': CheckSquare,
}

const resourceTrendItems = [
  { key: 'courses', label: '课程', icon: BookOpen, color: '#3b82f6' },
  { key: 'scenarios', label: '场景', icon: Layers, color: '#10b981' },
  { key: 'careerPositions', label: '岗位', icon: Briefcase, color: '#8b5cf6' },
  { key: 'questionBanks', label: '题库', icon: Database, color: '#06b6d4' },
  { key: 'exams', label: '试卷', icon: FileText, color: '#f97316' },
  { key: 'examUsages', label: '考试', icon: CheckSquare, color: '#ef4444' },
]

export function SchoolAdminResourcesTab() {
  const [dashboard, setDashboard] = useState<WorkspaceDashboard | null>(null)

  useEffect(() => {
    portalApi
      .workspaceDashboard({ role: 'school_admin' })
      .then(setDashboard)
      .catch(() => setDashboard(null))
  }, [])

  const resourceStats = dashboard?.resourceStats || []
  const todos = dashboard?.todos || []
  const pendingCount = todos.reduce((acc, item) => acc + item.count, 0)
  const growth = dashboard?.resourceGrowth || []

  return (
    <div className="space-y-3">
      {/* 资源存量指标 */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        {resourceStats.map((item) => {
          const Icon = iconMap[item.icon || ''] || Database
          return (
            <Card
              key={item.label}
              className="border-0 shadow-sm bg-gradient-to-br from-white to-gray-50/50"
            >
              <CardContent className="p-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-primary/5 flex items-center justify-center text-primary">
                    <Icon className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="text-xl font-bold text-gray-900">{item.value}</p>
                    <p className="text-xs text-gray-500">{item.label}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
        <div className="lg:col-span-3 space-y-4">
          {/* 资源增长趋势（每种资源一张卡片） */}
          <SectionCard title="资源增长趋势" icon={TrendingUp} iconColor="blue">
            {growth.length === 0 ? (
              <div className="py-10 text-center text-sm text-gray-400">暂无增长数据</div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
                {resourceTrendItems.map((item) => (
                  <ResourceTrendCard
                    key={item.key}
                    item={item}
                    data={growth.map((g) => ({
                      date: g.date,
                      value: g[item.key as keyof typeof g] as number,
                    }))}
                  />
                ))}
              </div>
            )}
          </SectionCard>
        </div>

        <div>
          <SectionCard title="待审批资源" icon={ClipboardList} iconColor="amber">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-sm text-gray-500">待审批总数</span>
                <Badge variant="destructive" className="text-xs">
                  {pendingCount}
                </Badge>
              </div>
              {todos.length === 0 && (
                <div className="py-4 text-center text-xs text-gray-400">暂无待审批</div>
              )}
              {todos.map((item) => (
                <div key={item.id} className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">{item.title}</span>
                  <Badge variant="secondary" className="text-xs">
                    {item.count}
                  </Badge>
                </div>
              ))}
            </div>
          </SectionCard>
        </div>
      </div>
    </div>
  )
}

function ResourceTrendCard({
  item,
  data,
}: {
  item: (typeof resourceTrendItems)[number]
  data: { date: string; value: number }[]
}) {
  const Icon = item.icon
  const latest = data[data.length - 1]?.value ?? 0
  return (
    <Card className="border border-gray-100 shadow-sm">
      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center"
              style={{ backgroundColor: `${item.color}1a`, color: item.color }}
            >
              <Icon className="w-4 h-4" />
            </div>
            <span className="text-sm font-semibold text-gray-900">{item.label}资源增长</span>
          </div>
          <div className="text-right">
            <p className="text-lg font-bold" style={{ color: item.color }}>
              {latest}
            </p>
            <p className="text-xs text-gray-400">今日新增</p>
          </div>
        </div>
        <div className="h-20 w-full">
          <ChartContainer config={{}} className="h-full w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={data} margin={{ top: 4, right: 4, bottom: 0, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" vertical={false} />
                <XAxis
                  dataKey="date"
                  tick={{ fontSize: 10 }}
                  stroke="#94a3b8"
                  tickLine={false}
                  axisLine={false}
                  minTickGap={16}
                />
                <YAxis hide />
                <ChartTooltip content={<ChartTooltipContent />} />
                <Line
                  type="monotone"
                  dataKey="value"
                  name={item.label}
                  stroke={item.color}
                  strokeWidth={2}
                  dot={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </ChartContainer>
        </div>
      </CardContent>
    </Card>
  )
}

// frontend/portal-vue/src/views/portal/workspace/SchoolAdminResourcesTab.vue
<!--
  资源运营 Tab（学校管理员）。
  对齐原 React 版 school-admin-resources-tab.tsx（206 行）：
  - 数据源：GET /portal/workspace/dashboard?role=school_admin（resourceStats / resourceGrowth / todos）；
  - 资源存量指标：6 张存量卡（图标 + 数量 + 名称）；
  - 资源增长趋势：岗位/场景/课程/题库/试卷/考试 各一张卡（今日新增 + 走势），空态「暂无增长数据」；
    React 用 recharts 折线，Vue 门户不引入新依赖，改用等价的内联 SVG 折线（同一份 resourceGrowth 数据，
    含首尾日期刻度与各点 title 悬浮值）；
  - 待审批资源：待审批总数 + 逐项计数，空态「暂无待审批」。
-->
<template>
  <div class="admin-resources">
    <!-- 资源存量指标 -->
    <div class="stock-grid">
      <div v-for="item in resourceStats" :key="item.label" class="stock-card">
        <span class="stock-icon">
          <el-icon :size="20"><component :is="resourceIcon(item.icon)" /></el-icon>
        </span>
        <div>
          <p class="stock-value">{{ item.value }}</p>
          <p class="stock-label">{{ item.label }}</p>
        </div>
      </div>
      <div v-if="resourceStats.length === 0" class="empty-line">暂无资源存量数据</div>
    </div>

    <div class="resources-grid">
      <div class="grid-main">
        <SectionCard title="资源增长趋势" :icon="TrendCharts" icon-color="blue">
          <div v-if="growth.length === 0" class="empty-line">暂无增长数据</div>
          <div v-else class="trend-grid">
            <div v-for="item in TREND_ITEMS" :key="item.key" class="trend-card">
              <div class="trend-head">
                <div class="trend-title">
                  <span
                    class="trend-icon"
                    :style="{ backgroundColor: `${item.color}1a`, color: item.color }"
                  >
                    <el-icon :size="16"><component :is="item.icon" /></el-icon>
                  </span>
                  <span class="trend-name">{{ item.label }}资源增长</span>
                </div>
                <div class="trend-latest">
                  <p class="trend-value" :style="{ color: item.color }">{{ latestOf(item.key) }}</p>
                  <p class="trend-hint">今日新增</p>
                </div>
              </div>

              <!-- 内联 SVG 折线（替代 React recharts LineChart，数据同源） -->
              <div class="trend-chart">
                <svg viewBox="0 0 100 40" preserveAspectRatio="none" class="spark">
                  <line x1="0" y1="20" x2="100" y2="20" class="spark-grid" />
                  <polyline :points="sparkPoints(item.key)" :stroke="item.color" class="spark-line" />
                  <circle
                    v-for="(pt, idx) in sparkDots(item.key)"
                    :key="idx"
                    :cx="pt.x"
                    :cy="pt.y"
                    r="1"
                    :fill="item.color"
                  >
                    <title>{{ pt.date }}：{{ pt.value }}</title>
                  </circle>
                </svg>
                <div class="spark-axis">
                  <span>{{ growth[0]?.date }}</span>
                  <span>{{ growth[growth.length - 1]?.date }}</span>
                </div>
              </div>
            </div>
          </div>
        </SectionCard>
      </div>

      <div class="grid-side">
        <SectionCard title="待审批资源" :icon="Tickets" icon-color="amber">
          <div class="pending-body">
            <div class="pending-total">
              <span class="pending-label">待审批总数</span>
              <el-tag size="small" type="danger" effect="light">{{ pendingCount }}</el-tag>
            </div>
            <div v-if="todos.length === 0" class="empty-line small">暂无待审批</div>
            <div v-for="item in todos" :key="item.id" class="pending-row">
              <span class="pending-name">{{ item.title }}</span>
              <el-tag size="small" type="info" effect="light">{{ item.count }}</el-tag>
            </div>
          </div>
        </SectionCard>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import type { Component } from 'vue';
import {
  Briefcase,
  Checked,
  Coin,
  Collection,
  Document,
  Reading,
  Tickets,
  TrendCharts
} from '@element-plus/icons-vue';
import SectionCard from './SectionCard.vue';
import { workspaceDashboardApi } from './workspace-api';
import type {
  WorkspaceResourceGrowth,
  WorkspaceResourceStat,
  WorkspaceTodo
} from './workspace-api';

type GrowthKey = 'careerPositions' | 'scenarios' | 'courses' | 'questionBanks' | 'exams' | 'examUsages';

/** 后端下发的 icon key → Element Plus 图标（对齐 React iconMap） */
const ICON_MAP: Record<string, Component> = {
  'book-open': Reading,
  layers: Collection,
  briefcase: Briefcase,
  'file-text': Document,
  'check-circle': Checked
};

/** 六类资源趋势卡（对齐 React resourceTrendItems，含配色） */
const TREND_ITEMS: { key: GrowthKey; label: string; icon: Component; color: string }[] = [
  { key: 'careerPositions', label: '岗位', icon: Briefcase, color: '#8b5cf6' },
  { key: 'scenarios', label: '场景', icon: Collection, color: '#10b981' },
  { key: 'courses', label: '课程', icon: Reading, color: '#3b82f6' },
  { key: 'questionBanks', label: '题库', icon: Coin, color: '#06b6d4' },
  { key: 'exams', label: '试卷', icon: Document, color: '#f97316' },
  { key: 'examUsages', label: '考试', icon: Checked, color: '#ef4444' }
];

const resourceStats = ref<WorkspaceResourceStat[]>([]);
const todos = ref<WorkspaceTodo[]>([]);
const growth = ref<WorkspaceResourceGrowth[]>([]);

const pendingCount = computed(() => todos.value.reduce((acc, item) => acc + item.count, 0));

function resourceIcon(key?: string): Component {
  return ICON_MAP[key || ''] || Coin;
}

function seriesOf(key: GrowthKey): { date: string; value: number }[] {
  return growth.value.map((g) => ({ date: g.date, value: g[key] ?? 0 }));
}

function latestOf(key: GrowthKey): number {
  const series = seriesOf(key);
  return series[series.length - 1]?.value ?? 0;
}

/** 折线点：viewBox 100×40，纵向留 4 单位边距，全 0 时贴底 */
function sparkDots(key: GrowthKey): { x: number; y: number; date: string; value: number }[] {
  const series = seriesOf(key);
  if (series.length === 0) return [];
  const max = Math.max(...series.map((s) => s.value), 1);
  const step = series.length > 1 ? 100 / (series.length - 1) : 0;
  return series.map((s, i) => ({
    x: series.length > 1 ? i * step : 50,
    y: 36 - (s.value / max) * 32,
    date: s.date,
    value: s.value
  }));
}

function sparkPoints(key: GrowthKey): string {
  return sparkDots(key)
    .map((p) => `${p.x.toFixed(2)},${p.y.toFixed(2)}`)
    .join(' ');
}

onMounted(async () => {
  try {
    const res = await workspaceDashboardApi.get({ role: 'school_admin' });
    resourceStats.value = res.resourceStats || [];
    todos.value = res.todos || [];
    growth.value = res.resourceGrowth || [];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载资源运营数据失败');
  }
});
</script>

<style scoped>
.admin-resources {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

/* 存量卡 */
.stock-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}
@media (min-width: 768px) {
  .stock-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
}
@media (min-width: 1024px) {
  .stock-grid { grid-template-columns: repeat(6, minmax(0, 1fr)); }
}
.stock-card {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px;
  border-radius: 12px;
  background: linear-gradient(135deg, #fff, rgba(249, 250, 251, 0.5));
  border: 1px solid #f3f4f6;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}
.stock-icon {
  width: 40px;
  height: 40px;
  flex-shrink: 0;
  border-radius: 8px;
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
.stock-value {
  margin: 0;
  font-size: 20px;
  font-weight: 700;
  color: #111827;
}
.stock-label {
  margin: 0;
  font-size: 12px;
  color: #6b7280;
}

/* 主体 */
.resources-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 16px;
}
@media (min-width: 1024px) {
  .resources-grid { grid-template-columns: repeat(4, minmax(0, 1fr)); }
  .grid-main { grid-column: span 3; }
}
.trend-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 12px;
}
@media (min-width: 640px) {
  .trend-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (min-width: 1280px) {
  .trend-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
}
.trend-card {
  border: 1px solid #f3f4f6;
  border-radius: 12px;
  background: #fff;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
  padding: 16px;
}
.trend-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 8px;
}
.trend-title {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}
.trend-icon {
  width: 32px;
  height: 32px;
  flex-shrink: 0;
  border-radius: 8px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
.trend-name {
  font-size: 14px;
  font-weight: 600;
  color: #111827;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.trend-latest {
  text-align: right;
  flex-shrink: 0;
}
.trend-value {
  margin: 0;
  font-size: 18px;
  font-weight: 700;
}
.trend-hint {
  margin: 0;
  font-size: 12px;
  color: #9ca3af;
}
.trend-chart {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.spark {
  width: 100%;
  height: 80px;
  overflow: visible;
}
.spark-grid {
  stroke: #f0f0f0;
  stroke-width: 0.5;
  stroke-dasharray: 3 3;
}
.spark-line {
  fill: none;
  stroke-width: 1.5;
  vector-effect: non-scaling-stroke;
}
.spark-axis {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 10px;
  color: #94a3b8;
}

/* 待审批 */
.pending-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.pending-total {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.pending-label {
  font-size: 14px;
  color: #6b7280;
}
.pending-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  font-size: 14px;
}
.pending-name {
  color: #374151;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.empty-line {
  grid-column: 1 / -1;
  padding: 40px 0;
  text-align: center;
  font-size: 14px;
  color: #9ca3af;
}
.empty-line.small {
  padding: 16px 0;
  font-size: 12px;
}
</style>
