// apps/edu/app/portal/workspace/_components/workspace-schedule-grid.tsx
'use client'

import { useState, useMemo, type ReactNode } from 'react'
import { useRouter } from 'next/navigation'
import {
  MapPin,
  User,
  ChevronLeft,
  ChevronRight,
  CalendarDays,
  ExternalLink,
  FileCheck,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { cn } from '@/lib/utils'
// 演示数据：以下 import 来自占位 mock 文件，后续应替换为真实 API（详见该文件头部说明）
import { allPeriods, days, type ScheduleEvent } from '../_data/workspace-student-types'
import { formatDate , formatYMD } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'

interface ScheduleGridProps {
  events: ScheduleEvent[]
}

type ViewType = 'year' | 'month' | 'week'

const typeStyles: Record<
  ScheduleEvent['type'],
  { bg: string; border: string; badge: string; label: string; actionColor: string }
> = {
  course: {
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    badge: 'border-blue-300 text-blue-600',
    label: '课程',
    actionColor: 'blue',
  },
  scene: {
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    badge: 'border-orange-300 text-orange-600',
    label: '岗位场景',
    actionColor: 'orange',
  },
  exam: {
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    badge: 'border-purple-300 text-purple-600',
    label: '考试/测评',
    actionColor: 'purple',
  },
  todo: {
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    badge: 'border-gray-300 text-gray-600',
    label: '待办',
    actionColor: 'gray',
  },
}

function getStudentActionUrls(
  event: ScheduleEvent,
): { learnUrl: string; isActionable: true } | { isActionable: false } {
  if (event.type === 'scene' && event.scenarioId) {
    return {
      learnUrl: `/scene/landing/${event.scenarioId}`,
      isActionable: true,
    }
  }
  if (event.type === 'course' && event.courseId) {
    return {
      learnUrl: `/lesson/landing/${event.courseId}`,
      isActionable: true,
    }
  }
  return { isActionable: false }
}

function getWeekStart(date: Date) {
  const d = new Date(date)
  const day = d.getDay()
  const diff = d.getDate() - day + (day === 0 ? -6 : 1)
  return new Date(d.setDate(diff))
}

function getWeekEnd(weekStart: Date) {
  const end = new Date(weekStart)
  end.setDate(end.getDate() + 6)
  return end
}

function dateKey(d: Date): string {
  return formatYMD(d)
}

// 事件可带可选的 date（单次安排）；未带 date 的事件视为每周重复安排，始终显示
function isEventInWeek(event: ScheduleEvent, weekStart: Date, weekEnd: Date): boolean {
  const date = (event as ScheduleEvent & { date?: string }).date
  if (!date) return true
  const key = date.slice(0, 10)
  return key >= dateKey(weekStart) && key <= dateKey(weekEnd)
}

function getWeeksInMonth(year: number, month: number) {
  const firstDay = new Date(year, month - 1, 1)
  const lastDay = new Date(year, month, 0)
  const startDay = firstDay.getDay() || 7
  const totalDays = lastDay.getDate()
  return Math.ceil((totalDays + startDay - 1) / 7)
}

export function WorkspaceScheduleGrid({ events }: ScheduleGridProps) {
  const t = useT()
  const [view, setView] = useState<ViewType>('week')
  const [currentDate, setCurrentDate] = useState(() => new Date())

  const year = currentDate.getFullYear()
  const month = currentDate.getMonth() + 1

  const weekStart = useMemo(() => getWeekStart(currentDate), [currentDate])
  const weekEnd = useMemo(() => getWeekEnd(weekStart), [weekStart])
  const weekIndex = useMemo(() => {
    const firstDay = new Date(year, month - 1, 1)
    const startDay = firstDay.getDay() || 7
    const offset = weekStart.getDate() + startDay - 2
    return Math.floor(offset / 7) + 1
  }, [year, month, weekStart])

  const handleYearChange = (val: string) => {
    const d = new Date(currentDate)
    d.setFullYear(Number(val))
    setCurrentDate(d)
  }

  const handleMonthChange = (val: string) => {
    const d = new Date(currentDate)
    d.setMonth(Number(val) - 1)
    setCurrentDate(d)
  }

  const handleWeekChange = (val: string) => {
    const targetWeek = Number(val)
    const firstDay = new Date(year, month - 1, 1)
    const startDay = firstDay.getDay() || 7
    const targetDate = new Date(year, month - 1, 1 + (targetWeek - 1) * 7 - (startDay - 1))
    setCurrentDate(targetDate)
  }

  const prevPeriod = () => {
    const d = new Date(currentDate)
    if (view === 'week') d.setDate(d.getDate() - 7)
    if (view === 'month') d.setMonth(d.getMonth() - 1)
    if (view === 'year') d.setFullYear(d.getFullYear() - 1)
    setCurrentDate(d)
  }

  const nextPeriod = () => {
    const d = new Date(currentDate)
    if (view === 'week') d.setDate(d.getDate() + 7)
    if (view === 'month') d.setMonth(d.getMonth() + 1)
    if (view === 'year') d.setFullYear(d.getFullYear() + 1)
    setCurrentDate(d)
  }

  const goToday = () => setCurrentDate(new Date())

  const weeksInMonth = getWeeksInMonth(year, month)

  return (
    <div className="space-y-4">
      {/* 工具栏 */}
      <div className="flex flex-col xl:flex-row xl:items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-blue-50 text-blue-600">
            <CalendarDays className="w-5 h-5" />
          </div>
          <div>
            <div className="text-base font-semibold text-gray-900">
              {t('{year}年{month}月', { year, month })}
              {view === 'week' && t(' · 第{week}周', { week: weekIndex })}
            </div>
            {view === 'week' && (
              <div className="text-xs text-gray-500">
                {formatDate(weekStart)} - {formatDate(weekEnd)}
              </div>
            )}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* 年/月/周选择器 */}
          {view !== 'year' && (
            <>
              <Select value={String(year)} onValueChange={handleYearChange}>
                <SelectTrigger className="w-[108px] h-9 text-xs">
                  <SelectValue placeholder={t('年份')} />
                </SelectTrigger>
                <SelectContent>
                  {[2025, 2026, 2027].map((y) => (
                    <SelectItem key={y} value={String(y)} className="text-xs">
                      {t('{year}年', { year: y })}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>

              <Select value={String(month)} onValueChange={handleMonthChange}>
                <SelectTrigger className="w-[100px] h-9 text-xs">
                  <SelectValue placeholder={t('月份')} />
                </SelectTrigger>
                <SelectContent>
                  {Array.from({ length: 12 }, (_, i) => i + 1).map((m) => (
                    <SelectItem key={m} value={String(m)} className="text-xs">
                      {t('{month}月', { month: m })}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </>
          )}

          {view === 'week' && (
            <Select value={String(weekIndex)} onValueChange={handleWeekChange}>
              <SelectTrigger className="w-[112px] h-9 text-xs">
                <SelectValue placeholder={t('周次')} />
              </SelectTrigger>
              <SelectContent>
                {Array.from({ length: weeksInMonth }, (_, i) => i + 1).map((w) => (
                  <SelectItem key={w} value={String(w)} className="text-xs">
                    {t('第{week}周', { week: w })}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}

          <div className="flex items-center">
            <Button
              variant="outline"
              size="icon"
              className="h-9 w-9 rounded-r-none border-r-0"
              onClick={prevPeriod}
              aria-label={t('上一周')}
            >
              <ChevronLeft className="w-4 h-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              className="h-9 w-9 rounded-l-none"
              onClick={nextPeriod}
              aria-label={t('下一周')}
            >
              <ChevronRight className="w-4 h-4" />
            </Button>
          </div>

          <Button variant="outline" size="sm" className="h-9 text-xs" onClick={goToday}>
            {t('今天')}
          </Button>

          <Tabs value={view} onValueChange={(v) => setView(v as ViewType)}>
            <TabsList className="h-9">
              <TabsTrigger value="year" className="text-xs px-3">
                {t('年')}
              </TabsTrigger>
              <TabsTrigger value="month" className="text-xs px-3">
                {t('月')}
              </TabsTrigger>
              <TabsTrigger value="week" className="text-xs px-3">
                {t('周')}
              </TabsTrigger>
            </TabsList>
          </Tabs>
        </div>
      </div>

      {/* 视图内容 */}
      {view === 'week' && <WeekView events={events} weekStart={weekStart} weekEnd={weekEnd} />}
      {view === 'month' && <MonthView year={year} month={month} events={events} />}
      {view === 'year' && <YearView events={events} />}
    </div>
  )
}

function ScheduleEventPopover({ event, children }: { event: ScheduleEvent; children: ReactNode }) {
  const action = getStudentActionUrls(event)
  const router = useRouter()
  const t = useT()

  if (!action.isActionable) {
    return <>{children}</>
  }

  const isCourse = event.type === 'course'
  const borderColor = isCourse ? 'border-blue-200' : 'border-orange-200'
  const textColor = isCourse ? 'text-blue-600' : 'text-orange-600'
  const hoverBg = isCourse ? 'hover:bg-blue-50' : 'hover:bg-orange-50'
  const lightBg = isCourse ? 'bg-blue-50/50' : 'bg-orange-50/50'
  const lightBorder = isCourse ? 'border-blue-100' : 'border-orange-100'

  return (
    <Popover>
      <PopoverTrigger asChild>{children}</PopoverTrigger>
      <PopoverContent
        side="right"
        align="start"
        sideOffset={6}
        className="w-72 p-4 bg-white shadow-xl border-gray-200 rounded-xl"
      >
        <div className="space-y-3">
          <div className="flex items-center gap-1.5 pb-2 border-b border-gray-100">
            <span className="text-sm font-semibold text-gray-800 truncate flex-1">
              {event.title}
            </span>
            {event.tag && (
              <Badge variant="secondary" className="text-[10px] h-4 px-1.5">
                {event.tag}
              </Badge>
            )}
          </div>
          <div className="space-y-1 text-xs text-gray-500">
            {event.teacher && (
              <div className="flex items-center gap-1">
                <User className="h-3 w-3" />
                {event.teacher}
              </div>
            )}
            {event.location && (
              <div className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                {event.location}
              </div>
            )}
            {event.description && <div className="truncate">{event.description}</div>}
          </div>
          <div className={`rounded-lg border p-2 ${lightBg} ${lightBorder}`}>
            <span className="text-[10px] text-gray-400 block mb-1.5">{t('操作')}</span>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                className={`flex-1 justify-center text-[11px] h-7 px-2 ${borderColor} ${textColor} ${hoverBg}`}
                onClick={() => router.push(action.learnUrl)}
              >
                <ExternalLink className="h-3.5 w-3.5 mr-1" />
                {t('前往学习')}
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="flex-1 justify-center text-[11px] h-7 px-2 border-gray-200 text-gray-400 cursor-not-allowed"
                disabled
              >
                <FileCheck className="h-3.5 w-3.5 mr-1" />
                {t('查看测评结果')}
              </Button>
            </div>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  )
}

function WeekView({
  events,
  weekStart,
  weekEnd,
}: {
  events: ScheduleEvent[]
  weekStart: Date
  weekEnd: Date
}) {
  // 事件需属于当前周（weekStart ~ weekEnd）才显示，避免其他周的安排出现在本周视图
  const t = useT()
  const weekEvents = events.filter((e) => isEventInWeek(e, weekStart, weekEnd))
  return (
    <div className="border border-gray-200 rounded-xl overflow-x-auto bg-white shadow-sm">
      <div className="grid grid-cols-8 min-w-[760px] bg-gray-50">
        <div className="p-3 text-sm font-semibold text-gray-700 border-r border-gray-200 flex items-center justify-center">
          {t('节次 / 星期')}
        </div>
        {days.map((d) => (
          <div
            key={d}
            className="p-3 text-sm font-semibold text-gray-700 text-center border-r border-gray-200 last:border-r-0"
          >
            {t(d)}
          </div>
        ))}
      </div>

      {allPeriods.map((period) => (
        <div key={period} className="grid grid-cols-8 min-w-[760px] border-t border-gray-200">
          <div className="p-3 text-xs text-gray-500 border-r border-gray-200 bg-gray-50/50 flex items-center justify-center font-medium">
            {t(period)}
          </div>
          {[1, 2, 3, 4, 5, 6, 7].map((dayOfWeek) => {
            const event = weekEvents.find((e) => e.dayOfWeek === dayOfWeek && e.period === period)
            const card = event ? (
              <div
                className={cn(
                  'w-full h-full rounded-lg p-2 text-xs space-y-1 transition-all hover:shadow-sm hover:scale-[1.02] cursor-pointer',
                  typeStyles[event.type].bg,
                  'border',
                  typeStyles[event.type].border,
                )}
              >
                <div className="flex items-center gap-1">
                  <Badge
                    variant="outline"
                    className={cn('text-[10px] h-4 px-1 font-medium', typeStyles[event.type].badge)}
                  >
                    {t(typeStyles[event.type].label)}
                  </Badge>
                  {event.tag && (
                    <span className="text-[10px] text-gray-500 truncate">{event.tag}</span>
                  )}
                </div>
                <div className="font-semibold text-gray-900 truncate">{event.title}</div>
                {event.description && (
                  <div className="text-[10px] text-gray-500 truncate">{event.description}</div>
                )}
                {event.teacher && (
                  <div className="text-[10px] text-gray-500 flex items-center gap-1">
                    <User className="h-3 w-3" />
                    {event.teacher}
                  </div>
                )}
                {event.location && (
                  <div className="text-[10px] text-gray-500 flex items-center gap-1">
                    <MapPin className="h-3 w-3" />
                    {event.location}
                  </div>
                )}
              </div>
            ) : null
            return (
              <div
                key={dayOfWeek}
                className={cn(
                  'p-1.5 border-r border-gray-200 last:border-r-0 min-h-[90px]',
                  !event && 'bg-gray-50/30',
                )}
              >
                {event ? (
                  <ScheduleEventPopover event={event}>{card}</ScheduleEventPopover>
                ) : (
                  <div className="w-full h-full min-h-[70px] rounded-lg border border-dashed border-gray-200 flex items-center justify-center text-gray-300">
                    <span className="text-[10px]">-</span>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      ))}
    </div>
  )
}

function MonthView({
  year,
  month,
  events,
}: {
  year: number
  month: number
  events: ScheduleEvent[]
}) {
  const firstDay = new Date(year, month - 1, 1)
  const lastDay = new Date(year, month, 0)
  const daysInMonth = lastDay.getDate()
  const startDayOfWeek = firstDay.getDay()
  const calendarDays: (number | null)[] = []
  for (let i = 0; i < startDayOfWeek; i++) calendarDays.push(null)
  for (let i = 1; i <= daysInMonth; i++) calendarDays.push(i)

  const t = useT()
  const weekDays = [t('日'), t('一'), t('二'), t('三'), t('四'), t('五'), t('六')]

  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden bg-white shadow-sm p-5">
      <div className="grid grid-cols-7 gap-1 mb-2">
        {weekDays.map((d) => (
          <div key={d} className="text-center text-xs text-gray-500 py-2 font-medium">
            {t('周{day}', { day: d })}
          </div>
        ))}
      </div>
      <div className="grid grid-cols-7 gap-2">
        {calendarDays.map((day, index) => {
          // 单次事件（带 date）按日期精确匹配，避免在当月所有同星期格重复出现；
          // 未带 date 的事件视为每周重复安排，按星期匹配
          const dayEvents = day
            ? events.filter((e) => {
                const eventDate = (e as ScheduleEvent & { date?: string }).date
                if (eventDate) {
                  return eventDate.slice(0, 10) === `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
                }
                return e.dayOfWeek === (index % 7 || 7)
              })
            : []
          return (
            <div
              key={index}
              className={cn(
                'min-h-[100px] rounded-lg border p-2 transition-colors',
                day ? 'border-gray-100 hover:bg-gray-50 cursor-pointer' : 'border-transparent',
              )}
            >
              {day && (
                <>
                  <div className="text-sm font-medium text-gray-700 mb-1">{day}</div>
                  <div className="space-y-1">
                    {dayEvents.slice(0, 3).map((e) => {
                      const eventCard = (
                        <div
                          className={cn(
                            'text-[10px] px-1.5 py-0.5 rounded truncate border',
                            typeStyles[e.type].bg,
                            typeStyles[e.type].border,
                            typeStyles[e.type].badge,
                          )}
                        >
                          {e.title}
                        </div>
                      )
                      return (
                        <ScheduleEventPopover key={e.id} event={e}>
                          {eventCard}
                        </ScheduleEventPopover>
                      )
                    })}
                    {dayEvents.length > 3 && (
                      <div className="text-[10px] text-gray-400 pl-1">
                        {t('+{count} 项', { count: dayEvents.length - 3 })}
                      </div>
                    )}
                  </div>
                </>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

function YearView({ events }: { events: ScheduleEvent[] }) {
  const t = useT()
  const months = Array.from({ length: 12 }, (_, i) => i + 1)
  return (
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      {months.map((m) => {
        const monthEvents = events.filter((e) => e.dayOfWeek % 4 === m % 4).slice(0, 4)
        return (
          <div
            key={m}
            className="border border-gray-200 rounded-xl bg-white p-4 hover:shadow-sm transition-shadow cursor-pointer"
          >
            <div className="text-sm font-semibold text-gray-900 mb-3">
              {t('{month}月', { month: m })}
            </div>
            <div className="space-y-1.5">
              {monthEvents.map((e) => {
                const eventCard = (
                  <div
                    className={cn(
                      'text-[10px] px-2 py-1 rounded truncate border',
                      typeStyles[e.type].bg,
                      typeStyles[e.type].border,
                      typeStyles[e.type].badge,
                    )}
                  >
                    {e.title}
                  </div>
                )
                return (
                  <ScheduleEventPopover key={e.id} event={e}>
                    {eventCard}
                  </ScheduleEventPopover>
                )
              })}
              {monthEvents.length === 0 && (
                <div className="text-[10px] text-gray-400">{t('暂无安排')}</div>
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}

// frontend/portal-vue/src/views/portal/workspace/WorkspaceScheduleGrid.vue
<!--
  工作台课表网格（年 / 月 / 周 三视图 + 年月周下拉 + 上下翻页 + 今天）。
  对齐原 React 版 workspace-schedule-grid.tsx（595 行）：
  - 周视图：8 列（节次/星期 + 周一~周日）× 10 节次行，事件卡按 type 取色并挂气泡；
  - 月视图：日历格，带 date 的单次事件按日期匹配、不带 date 的按星期每周重复，超 3 条折叠为「+N 项」；
  - 年视图：12 个月卡片，仅带 date 的单次事件按月归类（每月最多 4 条），否则显示「暂无安排」。
-->
<template>
  <div class="ws-grid">
    <!-- 工具栏 -->
    <div class="grid-toolbar">
      <div class="toolbar-left">
        <span class="toolbar-icon"><el-icon :size="20"><Calendar /></el-icon></span>
        <div>
          <div class="toolbar-title">
            {{ year }}年{{ month }}月<template v-if="view === 'week'"> · 第{{ weekIndex }}周</template>
          </div>
          <div v-if="view === 'week'" class="toolbar-sub">
            {{ formatYMD(weekStart) }} - {{ formatYMD(weekEnd) }}
          </div>
        </div>
      </div>

      <div class="toolbar-right">
        <template v-if="view !== 'year'">
          <el-select v-model="yearSel" size="default" class="sel-year" placeholder="年份">
            <el-option v-for="y in YEAR_OPTIONS" :key="y" :label="`${y}年`" :value="y" />
          </el-select>
          <el-select v-model="monthSel" size="default" class="sel-month" placeholder="月份">
            <el-option v-for="m in 12" :key="m" :label="`${m}月`" :value="m" />
          </el-select>
        </template>

        <el-select
          v-if="view === 'week'"
          v-model="weekSel"
          size="default"
          class="sel-week"
          placeholder="周次"
        >
          <el-option v-for="w in weeksInMonth" :key="w" :label="`第${w}周`" :value="w" />
        </el-select>

        <el-button-group>
          <el-button :icon="ArrowLeft" aria-label="上一周" @click="prevPeriod" />
          <el-button :icon="ArrowRight" aria-label="下一周" @click="nextPeriod" />
        </el-button-group>

        <el-button @click="goToday">今天</el-button>

        <el-radio-group v-model="view" size="default">
          <el-radio-button value="year">年</el-radio-button>
          <el-radio-button value="month">月</el-radio-button>
          <el-radio-button value="week">周</el-radio-button>
        </el-radio-group>
      </div>
    </div>

    <!-- 周视图 -->
    <div v-if="view === 'week'" class="week-view">
      <div class="week-inner">
        <div class="week-row week-head">
          <div class="week-cell head-cell period-head">节次 / 星期</div>
          <div v-for="d in WEEK_DAY_LABELS" :key="d" class="week-cell head-cell">{{ d }}</div>
        </div>
        <div v-for="row in weekRows" :key="row.period" class="week-row">
          <div class="week-cell period-cell">{{ row.period }}</div>
          <div
            v-for="(cell, dayIdx) in row.cells"
            :key="dayIdx"
            class="week-cell slot-cell"
            :class="{ empty: !cell }"
          >
            <WorkspaceEventPopover v-if="cell" :event="cell">
              <div class="event-card" :class="`type-${cell.type}`">
                <div class="event-top">
                  <span class="event-badge">{{ TYPE_LABELS[cell.type] }}</span>
                  <span v-if="cell.tag" class="event-tag">{{ cell.tag }}</span>
                </div>
                <div class="event-title">{{ cell.title }}</div>
                <div v-if="cell.description" class="event-line">{{ cell.description }}</div>
                <div v-if="cell.teacher" class="event-line">
                  <el-icon><User /></el-icon>{{ cell.teacher }}
                </div>
                <div v-if="cell.location" class="event-line">
                  <el-icon><Location /></el-icon>{{ cell.location }}
                </div>
              </div>
            </WorkspaceEventPopover>
            <div v-else class="event-placeholder">-</div>
          </div>
        </div>
      </div>
    </div>

    <!-- 月视图 -->
    <div v-else-if="view === 'month'" class="month-view">
      <div class="month-head">
        <div v-for="d in WEEK_SHORT_LABELS" :key="d" class="month-head-cell">周{{ d }}</div>
      </div>
      <div class="month-body">
        <div
          v-for="(cell, index) in monthCells"
          :key="index"
          class="month-cell"
          :class="{ blank: cell.day === null }"
        >
          <template v-if="cell.day !== null">
            <div class="month-day">{{ cell.day }}</div>
            <div class="month-events">
              <WorkspaceEventPopover v-for="e in cell.events.slice(0, 3)" :key="e.id" :event="e">
                <div class="event-chip" :class="`type-${e.type}`">{{ e.title }}</div>
              </WorkspaceEventPopover>
              <div v-if="cell.events.length > 3" class="month-more">
                +{{ cell.events.length - 3 }} 项
              </div>
            </div>
          </template>
        </div>
      </div>
    </div>

    <!-- 年视图 -->
    <div v-else class="year-view">
      <div v-for="cell in yearCells" :key="cell.month" class="year-card">
        <div class="year-card-title">{{ cell.month }}月</div>
        <div class="year-card-body">
          <WorkspaceEventPopover v-for="e in cell.events" :key="e.id" :event="e">
            <div class="event-chip" :class="`type-${e.type}`">{{ e.title }}</div>
          </WorkspaceEventPopover>
          <div v-if="cell.events.length === 0" class="year-empty">暂无安排</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ArrowLeft, ArrowRight, Calendar, Location, User } from '@element-plus/icons-vue';
import WorkspaceEventPopover from './WorkspaceEventPopover.vue';
import type { WorkspaceScheduleEvent, WorkspaceScheduleEventType } from './workspace-api';
import {
  ALL_PERIODS,
  WEEK_DAY_LABELS,
  WEEK_SHORT_LABELS,
  formatYMD,
  getWeekEnd,
  getWeekIndex,
  getWeekStart,
  getWeekTargetDate,
  getWeeksInMonth
} from './workspace-utils';

const props = defineProps<{ events: WorkspaceScheduleEvent[] }>();

const YEAR_OPTIONS = [2025, 2026, 2027];
const TYPE_LABELS: Record<WorkspaceScheduleEventType, string> = {
  course: '课程',
  scene: '岗位场景',
  exam: '考试/测评',
  todo: '待办'
};

type ViewType = 'year' | 'month' | 'week';

const view = ref<ViewType>('week');
const currentDate = ref(new Date());

const year = computed(() => currentDate.value.getFullYear());
const month = computed(() => currentDate.value.getMonth() + 1);
const weekStart = computed(() => getWeekStart(currentDate.value));
const weekEnd = computed(() => getWeekEnd(weekStart.value));
// 基于绝对日期差计算周次（第 1 周为包含当月 1 号的那一周），避免跨月错算
const weekIndex = computed(() => getWeekIndex(weekStart.value, year.value, month.value));
const weeksInMonth = computed(() => getWeeksInMonth(year.value, month.value));

/* 下拉选择：与 currentDate 双向同步 */
const yearSel = ref(year.value);
const monthSel = ref(month.value);
const weekSel = ref(weekIndex.value);
watch([year, month, weekIndex], ([y, m, w]) => {
  yearSel.value = y;
  monthSel.value = m;
  weekSel.value = w;
});
watch(yearSel, (val) => {
  if (val === year.value) return;
  const d = new Date(currentDate.value);
  d.setFullYear(val);
  currentDate.value = d;
});
watch(monthSel, (val) => {
  if (val === month.value) return;
  const d = new Date(currentDate.value);
  d.setMonth(val - 1);
  currentDate.value = d;
});
watch(weekSel, (val) => {
  if (val === weekIndex.value) return;
  currentDate.value = getWeekTargetDate(year.value, month.value, val);
});

function prevPeriod() {
  const d = new Date(currentDate.value);
  if (view.value === 'week') d.setDate(d.getDate() - 7);
  if (view.value === 'month') d.setMonth(d.getMonth() - 1);
  if (view.value === 'year') d.setFullYear(d.getFullYear() - 1);
  currentDate.value = d;
}

function nextPeriod() {
  const d = new Date(currentDate.value);
  if (view.value === 'week') d.setDate(d.getDate() + 7);
  if (view.value === 'month') d.setMonth(d.getMonth() + 1);
  if (view.value === 'year') d.setFullYear(d.getFullYear() + 1);
  currentDate.value = d;
}

function goToday() {
  currentDate.value = new Date();
}

/* ---------- 周视图：事件需属于当前周（不带 date 视为每周重复） ---------- */
function inCurrentWeek(event: WorkspaceScheduleEvent): boolean {
  if (!event.date) return true;
  const key = event.date.slice(0, 10);
  return key >= formatYMD(weekStart.value) && key <= formatYMD(weekEnd.value);
}

const weekEvents = computed(() => props.events.filter(inCurrentWeek));

/** 周视图行：每行一个节次，7 列按星期取当格事件（无则 null） */
const weekRows = computed(() =>
  ALL_PERIODS.map((period) => ({
    period,
    cells: [1, 2, 3, 4, 5, 6, 7].map(
      (day) =>
        weekEvents.value.find((e) => e.dayOfWeek === day && e.period === period) ||
        (null as WorkspaceScheduleEvent | null)
    )
  }))
);

/* ---------- 月视图 ---------- */
const calendarDays = computed<(number | null)[]>(() => {
  const firstDay = new Date(year.value, month.value - 1, 1);
  const daysInMonth = new Date(year.value, month.value, 0).getDate();
  const startDayOfWeek = firstDay.getDay();
  const days: (number | null)[] = [];
  for (let i = 0; i < startDayOfWeek; i++) days.push(null);
  for (let i = 1; i <= daysInMonth; i++) days.push(i);
  return days;
});

/**
 * 月视图格子：单次事件（带 date）按日期精确匹配，避免在当月所有同星期格重复出现；
 * 未带 date 的事件视为每周重复安排，按星期匹配。
 */
const monthCells = computed(() =>
  calendarDays.value.map((day, index) => {
    if (day === null) return { day, events: [] as WorkspaceScheduleEvent[] };
    const key = `${year.value}-${String(month.value).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    return {
      day,
      events: props.events.filter((e) =>
        e.date ? e.date.slice(0, 10) === key : e.dayOfWeek === (index % 7 || 7)
      )
    };
  })
);

/* ---------- 年视图：仅带 date 的单次事件按月归类（每月最多 4 条） ---------- */
const yearCells = computed(() =>
  Array.from({ length: 12 }, (_, i) => i + 1).map((m) => {
    const monthKey = `${year.value}-${String(m).padStart(2, '0')}`;
    return {
      month: m,
      events: props.events
        .filter((e) => (e.date ? e.date.slice(0, 7) === monthKey : false))
        .slice(0, 4)
    };
  })
);
</script>

<style scoped>
.ws-grid {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

/* ===== 工具栏 ===== */
.grid-toolbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 8px;
}
.toolbar-icon {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  background: #eff6ff;
  color: #2563eb;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
.toolbar-title {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
}
.toolbar-sub {
  font-size: 12px;
  color: #6b7280;
}
.toolbar-right {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
}
.sel-year { width: 108px; }
.sel-month { width: 100px; }
.sel-week { width: 112px; }

/* ===== 周视图 ===== */
.week-view {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  overflow-x: auto;
  background: #fff;
}
.week-inner {
  min-width: 760px;
}
.week-row {
  display: grid;
  grid-template-columns: repeat(8, minmax(0, 1fr));
  border-top: 1px solid #e5e7eb;
}
.week-row.week-head {
  border-top: none;
  background: #f9fafb;
}
.week-cell {
  border-right: 1px solid #e5e7eb;
}
.week-cell:last-child {
  border-right: none;
}
.head-cell {
  padding: 12px;
  font-size: 14px;
  font-weight: 600;
  color: #374151;
  text-align: center;
}
.period-cell {
  padding: 12px;
  font-size: 12px;
  font-weight: 500;
  color: #6b7280;
  background: rgba(249, 250, 251, 0.6);
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
}
.slot-cell {
  padding: 6px;
  min-height: 90px;
}
.slot-cell.empty {
  background: rgba(249, 250, 251, 0.4);
}
.event-placeholder {
  width: 100%;
  min-height: 70px;
  border: 1px dashed #e5e7eb;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  color: #d1d5db;
}
.event-card {
  width: 100%;
  border-radius: 8px;
  border: 1px solid;
  padding: 8px;
  font-size: 12px;
  cursor: pointer;
  transition: box-shadow 0.2s, transform 0.2s;
}
.event-card:hover {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  transform: scale(1.02);
}
.type-course { background: #eff6ff; border-color: #bfdbfe; }
.type-scene { background: #fff7ed; border-color: #fed7aa; }
.type-exam { background: #f5f3ff; border-color: #ddd6fe; }
.type-todo { background: #f9fafb; border-color: #e5e7eb; }
.event-top {
  display: flex;
  align-items: center;
  gap: 4px;
}
.event-badge {
  font-size: 10px;
  line-height: 16px;
  padding: 0 4px;
  border-radius: 4px;
  border: 1px solid currentColor;
  font-weight: 500;
}
.type-course .event-badge { color: #2563eb; }
.type-scene .event-badge { color: #ea580c; }
.type-exam .event-badge { color: #7c3aed; }
.type-todo .event-badge { color: #4b5563; }
.event-tag,
.event-line {
  font-size: 10px;
  color: #6b7280;
  display: flex;
  align-items: center;
  gap: 4px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.event-title {
  margin-top: 2px;
  font-weight: 600;
  color: #111827;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* ===== 月视图 ===== */
.month-view {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #fff;
  padding: 20px;
}
.month-head {
  display: grid;
  grid-template-columns: repeat(7, minmax(0, 1fr));
  gap: 4px;
  margin-bottom: 8px;
}
.month-head-cell {
  text-align: center;
  font-size: 12px;
  font-weight: 500;
  color: #6b7280;
  padding: 8px 0;
}
.month-body {
  display: grid;
  grid-template-columns: repeat(7, minmax(0, 1fr));
  gap: 8px;
}
.month-cell {
  min-height: 100px;
  border: 1px solid #f3f4f6;
  border-radius: 8px;
  padding: 8px;
  transition: background-color 0.2s;
}
.month-cell:not(.blank):hover {
  background: #f9fafb;
  cursor: pointer;
}
.month-cell.blank {
  border-color: transparent;
}
.month-day {
  font-size: 14px;
  font-weight: 500;
  color: #374151;
  margin-bottom: 4px;
}
.month-events {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.month-more {
  font-size: 10px;
  color: #9ca3af;
  padding-left: 4px;
}
.event-chip {
  font-size: 10px;
  padding: 2px 6px;
  border-radius: 4px;
  border: 1px solid;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  cursor: pointer;
}
.event-chip.type-course { color: #2563eb; }
.event-chip.type-scene { color: #ea580c; }
.event-chip.type-exam { color: #7c3aed; }
.event-chip.type-todo { color: #4b5563; }

/* ===== 年视图 ===== */
.year-view {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 16px;
}
@media (min-width: 768px) {
  .year-view { grid-template-columns: repeat(3, minmax(0, 1fr)); }
}
@media (min-width: 1024px) {
  .year-view { grid-template-columns: repeat(4, minmax(0, 1fr)); }
}
.year-card {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #fff;
  padding: 16px;
  transition: box-shadow 0.2s;
}
.year-card:hover {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}
.year-card-title {
  font-size: 14px;
  font-weight: 600;
  color: #111827;
  margin-bottom: 12px;
}
.year-card-body {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.year-empty {
  font-size: 10px;
  color: #9ca3af;
}
</style>
