// apps/edu/app/library/my-resources/page.tsx
'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  BookOpen,
  Lightbulb,
  Award,
  MessageSquare,
  FileText,
  Table,
  Image,
  Link,
  Music,
  Video,
  Archive,
  Building,
  Wrench,
  AppWindow,
  HelpCircle,
} from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Table as ShadcnTable,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  knowledgeApi,
  abilityApi,
  certificateLibraryApi,
  onSiteQuestionLibraryApi,
  resourceLibraryApi,
} from '@/lib/api'
import type {
  KnowledgePoint,
  AbilityPoint,
  CertificateLibraryItem,
  ResourceLibraryItem,
  OnSiteQuestionLibraryItem,
} from '@/lib/types'
import { RESOURCE_TYPE_LABELS, type ResourceKind } from '@/lib/types/library'
import { useAuth } from '@/components/auth-provider'
import { useToast } from '@zhiyu/ui'

// 资源类型展示顺序（与共享 RESOURCE_TYPE_LABELS 对应）
const RESOURCE_KINDS: ResourceKind[] = Object.keys(RESOURCE_TYPE_LABELS) as ResourceKind[]

const RESOURCE_ICONS: Record<ResourceKind, React.ReactNode> = {
  document: <FileText className="size-4" />,
  spreadsheet: <Table className="size-4" />,
  image: <Image className="size-4" aria-label="图片" />,
  link: <Link className="size-4" />,
  audio: <Music className="size-4" />,
  video: <Video className="size-4" />,
  archive: <Archive className="size-4" />,
  venue: <Building className="size-4" />,
  facility: <Wrench className="size-4" />,
  software: <AppWindow className="size-4" />,
  other: <HelpCircle className="size-4" />,
}

type TabKey = 'knowledge' | 'ability' | 'certificates' | 'questions' | `resource:${ResourceKind}`

interface TabDef {
  key: TabKey
  label: string
  icon: React.ReactNode
}

function buildTabs(): TabDef[] {
  const tabs: TabDef[] = [
    { key: 'knowledge', label: '知识点库', icon: <BookOpen className="size-4" /> },
    { key: 'ability', label: '能力点库', icon: <Lightbulb className="size-4" /> },
    { key: 'certificates', label: '证书库', icon: <Award className="size-4" /> },
  ]
  for (const kind of RESOURCE_KINDS) {
    tabs.push({
      key: `resource:${kind}`,
      label: RESOURCE_TYPE_LABELS[kind],
      icon: RESOURCE_ICONS[kind],
    })
  }
  tabs.push({ key: 'questions', label: '现场问答题库', icon: <MessageSquare className="size-4" /> })
  return tabs
}

const TABS = buildTabs()

export default function MyResourcesPage() {
  const { toast } = useToast()
  const { user } = useAuth()
  const [activeTab, setActiveTab] = useState<TabKey>('knowledge')

  const [knowledgeItems, setKnowledgeItems] = useState<KnowledgePoint[]>([])
  const [abilityItems, setAbilityItems] = useState<AbilityPoint[]>([])
  const [certificateItems, setCertificateItems] = useState<CertificateLibraryItem[]>([])
  const [questionItems, setQuestionItems] = useState<OnSiteQuestionLibraryItem[]>([])
  const [resourceItemsMap, setResourceItemsMap] = useState<
    Record<ResourceKind, ResourceLibraryItem[]>
  >(() => {
    const m = {} as Record<ResourceKind, ResourceLibraryItem[]>
    for (const k of RESOURCE_KINDS) m[k] = []
    return m
  })

  const [loadingKnowledge, setLoadingKnowledge] = useState(false)
  const [loadingAbility, setLoadingAbility] = useState(false)
  const [loadingCertificates, setLoadingCertificates] = useState(false)
  const [loadingQuestions, setLoadingQuestions] = useState(false)
  const [loadingResourceKind, setLoadingResourceKind] = useState<ResourceKind | null>(null)

  // 记录已成功加载过的资源类型，避免空数据时 effect 反复触发加载
  const loadedResourceKinds = useRef<Set<ResourceKind>>(new Set())
  // 任一列表超过后端 maxPageSize=200 被截断时置 true，展示兜底提示
  const [truncated, setTruncated] = useState(false)

  const userId = user?.id

  // TODO: 列表接口后端上限 maxPageSize=200，此处全量展示会被截断，需改为服务端分页
  const loadKnowledge = useCallback(async () => {
    setLoadingKnowledge(true)
    try {
      const res = await knowledgeApi.list({ creatorId: userId!, limit: 200 })
      setKnowledgeItems(res.items)
      if (res.total > res.items.length) setTruncated(true)
    } catch (err: any) {
      toast({ variant: 'destructive', title: '加载知识点失败', description: err.message })
    } finally {
      setLoadingKnowledge(false)
    }
  }, [userId, toast])

  const loadAbilities = useCallback(async () => {
    setLoadingAbility(true)
    try {
      const res = await abilityApi.list({ creatorId: userId!, limit: 200 })
      setAbilityItems(res.items)
      if (res.total > res.items.length) setTruncated(true)
    } catch (err: any) {
      toast({ variant: 'destructive', title: '加载能力点失败', description: err.message })
    } finally {
      setLoadingAbility(false)
    }
  }, [userId, toast])

  const loadCertificates = useCallback(async () => {
    setLoadingCertificates(true)
    try {
      const res = await certificateLibraryApi.list({ creatorId: userId!, limit: 200 })
      setCertificateItems(res.items)
      if (res.total > res.items.length) setTruncated(true)
    } catch (err: any) {
      toast({ variant: 'destructive', title: '加载证书失败', description: err.message })
    } finally {
      setLoadingCertificates(false)
    }
  }, [userId, toast])

  const loadQuestions = useCallback(async () => {
    setLoadingQuestions(true)
    try {
      const res = await onSiteQuestionLibraryApi.list({ creatorId: userId!, limit: 200 })
      setQuestionItems(res.items)
      if (res.total > res.items.length) setTruncated(true)
    } catch (err: any) {
      toast({ variant: 'destructive', title: '加载问答题失败', description: err.message })
    } finally {
      setLoadingQuestions(false)
    }
  }, [userId, toast])

  const loadResourceKind = useCallback(
    async (kind: ResourceKind) => {
      setLoadingResourceKind(kind)
      try {
        const res = await resourceLibraryApi.list({
          uploadedBy: userId!,
          resourceType: kind,
          limit: 200,
        })
        setResourceItemsMap((prev) => ({ ...prev, [kind]: res.items }))
        loadedResourceKinds.current.add(kind)
      } catch (err: any) {
        toast({ variant: 'destructive', title: '加载资源失败', description: err.message })
      } finally {
        setLoadingResourceKind(null)
      }
    },
    [userId, toast],
  )

  useEffect(() => {
    if (!userId) return

    // 将 tab 切换视为外部事件：在微任务回调中分发加载，避免在 effect 体内同步 setState
    Promise.resolve().then(() => {
      if (activeTab === 'knowledge' && knowledgeItems.length === 0) {
        loadKnowledge()
      } else if (activeTab === 'ability' && abilityItems.length === 0) {
        loadAbilities()
      } else if (activeTab === 'certificates' && certificateItems.length === 0) {
        loadCertificates()
      } else if (activeTab === 'questions' && questionItems.length === 0) {
        loadQuestions()
      } else if (activeTab.startsWith('resource:')) {
        const kind = activeTab.replace('resource:', '') as ResourceKind
        if (!loadedResourceKinds.current.has(kind)) {
          loadResourceKind(kind)
        }
      }
    })
  }, [
    activeTab,
    userId,
    knowledgeItems.length,
    abilityItems.length,
    certificateItems.length,
    questionItems.length,
    loadKnowledge,
    loadAbilities,
    loadCertificates,
    loadQuestions,
    loadResourceKind,
  ])

  const countForTab = (tab: TabKey) => {
    if (tab === 'knowledge') return knowledgeItems.length
    if (tab === 'ability') return abilityItems.length
    if (tab === 'certificates') return certificateItems.length
    if (tab === 'questions') return questionItems.length
    if (tab.startsWith('resource:')) {
      const kind = tab.replace('resource:', '') as ResourceKind
      return resourceItemsMap[kind].length
    }
    return 0
  }

  return (
    <div className="p-6 space-y-5">
      {truncated && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-2.5 text-sm text-amber-700">
          部分数据超过单次加载上限（200 条），当前仅展示前 200 条，请按条件筛选查看完整数据。
        </div>
      )}
      <Card className="border-0 shadow-sm bg-gradient-to-br from-primary/5 to-primary/10">
        <CardContent className="p-4 flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
            <FileText className="size-5 text-primary" />
          </div>
          <div>
            <div className="text-2xl font-bold text-primary">{countForTab(activeTab)}</div>
            <div className="text-xs text-primary">
              {TABS.find((t) => t.key === activeTab)?.label} · 共 {countForTab(activeTab)} 项
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-0 shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base font-semibold">我的资源</CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as TabKey)}>
            <TabsList className="mb-4 flex-wrap h-auto gap-1">
              {TABS.map((tab) => (
                <TabsTrigger key={tab.key} value={tab.key} className="gap-1.5">
                  {tab.icon}
                  {tab.label}
                  <span className="text-xs text-muted-foreground ml-0.5">
                    {countForTab(tab.key)}
                  </span>
                </TabsTrigger>
              ))}
            </TabsList>

            <TabsContent value="knowledge">
              {renderTable(
                loadingKnowledge,
                knowledgeItems,
                ['名称', '编码', '描述'],
                (item: KnowledgePoint) => (
                  <TableRow key={item.id} className="border-b last:border-0 hover:bg-slate-50/50">
                    <TableCell className="p-3">
                      <div className="flex items-center gap-2">
                        <BookOpen className="size-4 text-primary" />
                        <span className="text-sm font-medium text-slate-700">{item.name}</span>
                      </div>
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400">{item.code || '-'}</TableCell>
                    <TableCell className="p-3 text-sm text-slate-400 max-w-[300px] truncate">
                      {item.description || '-'}
                    </TableCell>
                  </TableRow>
                ),
              )}
            </TabsContent>

            <TabsContent value="ability">
              {renderTable(
                loadingAbility,
                abilityItems,
                ['名称', '分类', '描述'],
                (item: AbilityPoint) => (
                  <TableRow key={item.id} className="border-b last:border-0 hover:bg-slate-50/50">
                    <TableCell className="p-3">
                      <div className="flex items-center gap-2">
                        <Lightbulb className="size-4 text-amber-500" />
                        <span className="text-sm font-medium text-slate-700">{item.name}</span>
                      </div>
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400">
                      {item.attributes?.join('、') || '-'}
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400 max-w-[300px] truncate">
                      {item.description || '-'}
                    </TableCell>
                  </TableRow>
                ),
              )}
            </TabsContent>

            <TabsContent value="certificates">
              {renderTable(
                loadingCertificates,
                certificateItems,
                ['名称', '描述', '链接'],
                (item: CertificateLibraryItem) => (
                  <TableRow key={item.id} className="border-b last:border-0 hover:bg-slate-50/50">
                    <TableCell className="p-3">
                      <div className="flex items-center gap-2">
                        <Award className="size-4 text-emerald-500" />
                        <span className="text-sm font-medium text-slate-700">{item.name}</span>
                      </div>
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400 max-w-[300px] truncate">
                      {item.description || '-'}
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400 max-w-[200px] truncate">
                      {item.url || '-'}
                    </TableCell>
                  </TableRow>
                ),
              )}
            </TabsContent>

            {RESOURCE_KINDS.map((kind) => (
              <TabsContent key={kind} value={`resource:${kind}`}>
                {renderTable(
                  loadingResourceKind === kind,
                  resourceItemsMap[kind],
                  ['名称', '描述'],
                  (item: ResourceLibraryItem) => (
                    <TableRow key={item.id} className="border-b last:border-0 hover:bg-slate-50/50">
                      <TableCell className="p-3">
                        <div className="flex items-center gap-2">
                          {RESOURCE_ICONS[kind]}
                          <span className="text-sm font-medium text-slate-700">{item.name}</span>
                        </div>
                      </TableCell>
                      <TableCell className="p-3 text-sm text-slate-400 max-w-[400px] truncate">
                        {item.description || '-'}
                      </TableCell>
                    </TableRow>
                  ),
                )}
              </TabsContent>
            ))}

            <TabsContent value="questions">
              {renderTable(
                loadingQuestions,
                questionItems,
                ['题目', '题型', '分值'],
                (item: OnSiteQuestionLibraryItem) => (
                  <TableRow key={item.id} className="border-b last:border-0 hover:bg-slate-50/50">
                    <TableCell className="p-3">
                      <div className="flex items-center gap-2">
                        <MessageSquare className="size-4 text-rose-500" />
                        <span className="text-sm font-medium text-slate-700">
                          {item.questionText}
                        </span>
                      </div>
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400">
                      <span className="inline-flex items-center rounded-md bg-slate-100 px-2 py-0.5 text-xs font-medium text-slate-600">
                        {item.questionType}
                      </span>
                    </TableCell>
                    <TableCell className="p-3 text-sm text-slate-400">{item.score}</TableCell>
                  </TableRow>
                ),
              )}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}

function renderTable<T>(
  loading: boolean,
  items: T[],
  headerLabels: string[],
  renderRow: (item: T) => React.ReactNode,
) {
  return (
    <div className="rounded-lg border">
      <ShadcnTable>
        <TableHeader>
          <TableRow className="bg-slate-50/50 hover:bg-slate-50/50">
            {headerLabels.map((label) => (
              <TableHead
                key={label}
                className="text-left p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider"
              >
                {label}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {loading && (
            <TableRow>
              <TableCell
                colSpan={headerLabels.length}
                className="p-12 text-center text-muted-foreground"
              >
                加载中...
              </TableCell>
            </TableRow>
          )}
          {!loading && items.length === 0 && (
            <TableRow>
              <TableCell
                colSpan={headerLabels.length}
                className="p-12 text-center text-muted-foreground"
              >
                暂无数据
              </TableCell>
            </TableRow>
          )}
          {items.map(renderRow)}
        </TableBody>
      </ShadcnTable>
    </div>
  )
}

// frontend/portal-vue/src/views/library/my-resources.vue
<template>
  <div class="my-resources">
    <el-card shadow="never" class="summary-card">
      <div class="summary">
        <div class="count">{{ currentCount }}</div>
        <div class="label">{{ currentLabel }} · 共 {{ currentCount }} 项</div>
      </div>
    </el-card>

    <el-card shadow="never">
      <template #header>
        <span class="card-title">我的资源</span>
      </template>
      <el-tabs v-model="activeTab" @tab-change="onTabChange">
        <el-tab-pane label="知识点库" name="knowledge" />
        <el-tab-pane label="能力点库" name="ability" />
        <el-tab-pane label="证书库" name="certificates" />
        <el-tab-pane v-for="kind in resourceKinds" :key="kind" :label="resourceTypeLabels[kind]" :name="'resource:' + kind" />
        <el-tab-pane label="现场问答题库" name="questions" />
      </el-tabs>

      <el-table v-loading="currentLoading" :data="currentItems" stripe>
        <el-table-column
          v-for="col in currentColumns"
          :key="col.label"
          :label="col.label"
          :prop="col.prop"
          :formatter="col.formatter"
          show-overflow-tooltip
        />
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { knowledgeApi } from '@/api/lesson';
import { abilityApi, certificateLibraryApi } from '@/api/job';
import { onSiteQuestionLibraryApi, resourceLibraryApi } from '@/api/library';
import { RESOURCE_TYPE_LABELS, type ResourceKind } from '@/types/library';
import type { KnowledgePoint } from '@/types/lesson';
import type { AbilityPoint, CertificateLibraryItem } from '@/types/job';
import type { OnSiteQuestionLibraryItem, ResourceLibraryItem } from '@/types/library';
import { useAuthStore } from '@/stores/auth';

const auth = useAuthStore();
const userId = computed(() => auth.user?.id || '');

const resourceKinds = Object.keys(RESOURCE_TYPE_LABELS) as ResourceKind[];
const resourceTypeLabels = RESOURCE_TYPE_LABELS;

const activeTab = ref('knowledge');
const knowledgeItems = ref<KnowledgePoint[]>([]);
const abilityItems = ref<AbilityPoint[]>([]);
const certificateItems = ref<CertificateLibraryItem[]>([]);
const questionItems = ref<OnSiteQuestionLibraryItem[]>([]);
const resourceItemsMap = reactive<Record<string, ResourceLibraryItem[]>>({});
const loading = reactive<Record<string, boolean>>({});
const loaded = reactive<Record<string, boolean>>({});

interface Column {
  label: string;
  prop?: string;
  formatter?: (row: unknown) => string;
}

const knowledgeColumns: Column[] = [
  { label: '名称', prop: 'name' },
  { label: '编码', prop: 'code' },
  { label: '描述', prop: 'description' }
];
const abilityColumns: Column[] = [
  { label: '名称', prop: 'name' },
  { label: '分类', formatter: (row) => (row as AbilityPoint).attributes?.join('、') || '-' },
  { label: '描述', prop: 'description' }
];
const certificateColumns: Column[] = [
  { label: '名称', prop: 'name' },
  { label: '描述', prop: 'description' },
  { label: '链接', prop: 'url' }
];
const resourceColumns: Column[] = [
  { label: '名称', prop: 'name' },
  { label: '描述', prop: 'description' }
];
const questionColumns: Column[] = [
  { label: '题目', prop: 'questionText' },
  { label: '题型', prop: 'questionType' },
  { label: '分值', prop: 'score' }
];

const currentItems = computed<unknown[]>(() => {
  if (activeTab.value === 'knowledge') return knowledgeItems.value;
  if (activeTab.value === 'ability') return abilityItems.value;
  if (activeTab.value === 'certificates') return certificateItems.value;
  if (activeTab.value === 'questions') return questionItems.value;
  const kind = activeTab.value.replace('resource:', '') as ResourceKind;
  return resourceItemsMap[kind] || [];
});
const currentColumns = computed<Column[]>(() => {
  if (activeTab.value === 'knowledge') return knowledgeColumns;
  if (activeTab.value === 'ability') return abilityColumns;
  if (activeTab.value === 'certificates') return certificateColumns;
  if (activeTab.value === 'questions') return questionColumns;
  return resourceColumns;
});
const currentLoading = computed(() => loading[activeTab.value] || false);
const currentCount = computed(() => currentItems.value.length);
const currentLabel = computed(() => {
  if (activeTab.value === 'knowledge') return '知识点库';
  if (activeTab.value === 'ability') return '能力点库';
  if (activeTab.value === 'certificates') return '证书库';
  if (activeTab.value === 'questions') return '现场问答题库';
  return resourceTypeLabels[activeTab.value.replace('resource:', '') as ResourceKind];
});

// 后端列表接口上限 maxPageSize=200，分页全量拉取避免静默截断（对齐 React fetchAllPages）
async function fetchAllPages<T>(
  fn: (limit: number, offset: number) => Promise<{ items: T[]; total?: number }>
): Promise<T[]> {
  const PAGE = 200;
  const all: T[] = [];
  for (let p = 0; p < 1000; p++) {
    const res = await fn(PAGE, p * PAGE);
    const its = res.items || [];
    all.push(...its);
    if (its.length < PAGE) break;
  }
  return all;
}

async function loadKnowledge() {
  if (loaded.knowledge) return;
  loading.knowledge = true;
  try {
    knowledgeItems.value = await fetchAllPages((limit, offset) =>
      knowledgeApi.list({ creatorId: userId.value, limit, offset })
    );
    loaded.knowledge = true;
  } catch {
    ElMessage.error('加载知识点失败');
  } finally {
    loading.knowledge = false;
  }
}
async function loadAbility() {
  if (loaded.ability) return;
  loading.ability = true;
  try {
    abilityItems.value = await fetchAllPages((limit, offset) =>
      abilityApi.list({ creatorId: userId.value, limit, offset })
    );
    loaded.ability = true;
  } catch {
    ElMessage.error('加载能力点失败');
  } finally {
    loading.ability = false;
  }
}
async function loadCertificates() {
  if (loaded.certificates) return;
  loading.certificates = true;
  try {
    certificateItems.value = await fetchAllPages((limit, offset) =>
      certificateLibraryApi.list({ creatorId: userId.value, limit, offset })
    );
    loaded.certificates = true;
  } catch {
    ElMessage.error('加载证书失败');
  } finally {
    loading.certificates = false;
  }
}
async function loadQuestions() {
  if (loaded.questions) return;
  loading.questions = true;
  try {
    questionItems.value = await fetchAllPages((limit, offset) =>
      onSiteQuestionLibraryApi.list({ creatorId: userId.value, limit, offset })
    );
    loaded.questions = true;
  } catch {
    ElMessage.error('加载问答题失败');
  } finally {
    loading.questions = false;
  }
}
async function loadResourceKind(kind: ResourceKind) {
  const key = 'resource:' + kind;
  if (loaded[key]) return;
  loading[key] = true;
  try {
    resourceItemsMap[kind] = await fetchAllPages((limit, offset) =>
      resourceLibraryApi.list({ uploadedBy: userId.value, resourceType: kind, limit, offset })
    );
    loaded[key] = true;
  } catch {
    ElMessage.error('加载资源失败');
  } finally {
    loading[key] = false;
  }
}

function onTabChange(name: string | number) {
  const n = String(name);
  if (n === 'knowledge') loadKnowledge();
  else if (n === 'ability') loadAbility();
  else if (n === 'certificates') loadCertificates();
  else if (n === 'questions') loadQuestions();
  else if (n.startsWith('resource:')) loadResourceKind(n.replace('resource:', '') as ResourceKind);
}

onMounted(loadKnowledge);
</script>

<style scoped>
.my-resources { padding: 16px; }
.summary-card { margin-bottom: 16px; }
.summary { display: flex; align-items: center; gap: 12px; }
.count { font-size: 28px; font-weight: 700; color: #409eff; }
.label { color: #909399; font-size: 13px; }
.card-title { font-size: 16px; font-weight: 600; }
</style>
