// apps/edu/app/library/resources/page.tsx
"use client"

import { useEffect, useMemo, useState } from "react"
import {
  FileText, Table, Image, Link, Music, Video, Archive,
  Building, Wrench, AppWindow, HelpCircle, Pencil, Plus, Search, Trash2, ExternalLink,
} from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { resourceLibraryApi } from "@/lib/api"
import { RESOURCE_TYPE_LABELS, type ResourceLibraryItem } from "@/lib/types/library"
import { useToast } from "@/hooks/use-toast"

const TYPE_ICONS: Record<string, React.ReactNode> = {
  document: <FileText className="h-4 w-4" />,
  spreadsheet: <Table className="h-4 w-4" />,
  image: <Image className="h-4 w-4" />,
  link: <Link className="h-4 w-4" />,
  audio: <Music className="h-4 w-4" />,
  video: <Video className="h-4 w-4" />,
  archive: <Archive className="h-4 w-4" />,
  venue: <Building className="h-4 w-4" />,
  facility: <Wrench className="h-4 w-4" />,
  software: <AppWindow className="h-4 w-4" />,
  other: <HelpCircle className="h-4 w-4" />,
}

export default function ResourcesPage() {
  const { toast } = useToast()
  const [items, setItems] = useState<ResourceLibraryItem[]>([])
  const [loading, setLoading] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")
  const [typeFilter, setTypeFilter] = useState("")

  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<ResourceLibraryItem | null>(null)
  const [name, setName] = useState("")
  const [resourceType, setResourceType] = useState("document")
  const [url, setUrl] = useState("")
  const [description, setDescription] = useState("")
  const [thumbnail, setThumbnail] = useState("")
  const [fileSize, setFileSize] = useState("")

  const loadItems = async () => {
    setLoading(true)
    try {
      const params: any = { limit: 200 }
      if (searchQuery) params.search = searchQuery
      if (typeFilter) params.resourceType = typeFilter
      const res = await resourceLibraryApi.list(params)
      setItems(res.items)
    } catch (err: any) {
      toast({ variant: "destructive", title: "加载失败", description: err.message || "无法获取资源列表" })
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { loadItems() }, [searchQuery, typeFilter])

  const handleOpenAdd = () => {
    setEditingItem(null)
    setName("")
    setResourceType("document")
    setUrl("")
    setDescription("")
    setThumbnail("")
    setFileSize("")
    setIsDialogOpen(true)
  }

  const handleOpenEdit = (item: ResourceLibraryItem) => {
    setEditingItem(item)
    setName(item.name)
    setResourceType(item.resourceType)
    setUrl(item.url || "")
    setDescription(item.description || "")
    setThumbnail(item.thumbnail || "")
    setFileSize(item.fileSize ? String(item.fileSize) : "")
    setIsDialogOpen(true)
  }

  const handleDelete = async (id: string) => {
    if (!confirm("确定要删除该资源吗？")) return
    try {
      await resourceLibraryApi.delete(id)
      toast({ title: "删除成功" })
      loadItems()
    } catch (err: any) {
      toast({ variant: "destructive", title: "删除失败", description: err.message })
    }
  }

  const handleSubmit = async () => {
    if (!name.trim()) {
      toast({ variant: "destructive", title: "名称不能为空" })
      return
    }
    const sizeNum = fileSize ? parseInt(fileSize, 10) : undefined
    try {
      if (editingItem) {
        await resourceLibraryApi.update(editingItem.id, {
          name: name.trim(),
          resourceType: resourceType as any,
          url: url.trim() || undefined,
          description: description.trim() || undefined,
          thumbnail: thumbnail.trim() || undefined,
          fileSize: sizeNum,
        } as any)
        toast({ title: "更新成功" })
      } else {
        await resourceLibraryApi.create({
          name: name.trim(),
          resourceType: resourceType as any,
          url: url.trim() || undefined,
          description: description.trim() || undefined,
          thumbnail: thumbnail.trim() || undefined,
          fileSize: sizeNum,
        } as any)
        toast({ title: "创建成功" })
      }
      setIsDialogOpen(false)
      loadItems()
    } catch (err: any) {
      toast({ variant: "destructive", title: "保存失败", description: err.message })
    }
  }

  function formatSize(bytes?: number) {
    if (!bytes) return "-"
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }

  return (
    <div className="p-6 space-y-4">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-lg">场景任务资源库</CardTitle>
          <Button onClick={handleOpenAdd}>
            <Plus className="h-4 w-4 mr-1" />新增资源
          </Button>
        </CardHeader>
        <CardContent>
          <div className="flex gap-3 mb-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="搜索资源名称或描述..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={typeFilter} onValueChange={(v) => setTypeFilter(v === "all" ? "" : v)}>
              <SelectTrigger className="w-40">
                <SelectValue placeholder="资源类型" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">全部类型</SelectItem>
                {Object.entries(RESOURCE_TYPE_LABELS).map(([key, label]) => (
                  <SelectItem key={key} value={key}>{label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="border rounded-lg">
            <table className="w-full">
              <thead>
                <tr className="border-b bg-muted/50">
                  <th className="text-left p-3 text-sm font-medium">名称</th>
                  <th className="text-left p-3 text-sm font-medium">类型</th>
                  <th className="text-left p-3 text-sm font-medium">链接</th>
                  <th className="text-left p-3 text-sm font-medium">大小</th>
                  <th className="text-left p-3 text-sm font-medium">描述</th>
                  <th className="text-right p-3 text-sm font-medium">操作</th>
                </tr>
              </thead>
              <tbody>
                {loading && (
                  <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">加载中...</td></tr>
                )}
                {!loading && items.length === 0 && (
                  <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">暂无数据</td></tr>
                )}
                {items.map((item) => (
                  <tr key={item.id} className="border-b last:border-0 hover:bg-muted/30">
                    <td className="p-3">
                      <div className="flex items-center gap-2">
                        {TYPE_ICONS[item.resourceType] || TYPE_ICONS.other}
                        <span>{item.name}</span>
                      </div>
                    </td>
                    <td className="p-3">
                      <Badge variant="outline">{RESOURCE_TYPE_LABELS[item.resourceType] || item.resourceType}</Badge>
                    </td>
                    <td className="p-3">
                      {item.url ? (
                        <a href={item.url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-primary hover:underline">
                          <ExternalLink className="h-3 w-3" />访问
                        </a>
                      ) : "-"}
                    </td>
                    <td className="p-3 text-sm text-muted-foreground">{formatSize(item.fileSize)}</td>
                    <td className="p-3 text-sm max-w-[200px] truncate">{item.description || "-"}</td>
                    <td className="p-3 text-right">
                      <Button variant="ghost" size="sm" onClick={() => handleOpenEdit(item)}>
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => handleDelete(item.id)}>
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editingItem ? "编辑资源" : "新增资源"}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>名称 *</Label>
              <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="资源名称" />
            </div>
            <div>
              <Label>资源类型 *</Label>
              <Select value={resourceType} onValueChange={setResourceType}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {Object.entries(RESOURCE_TYPE_LABELS).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>链接/地址</Label>
              <Input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="资源URL" />
            </div>
            <div>
              <Label>缩略图</Label>
              <Input value={thumbnail} onChange={(e) => setThumbnail(e.target.value)} placeholder="缩略图URL" />
            </div>
            <div>
              <Label>文件大小（字节）</Label>
              <Input value={fileSize} onChange={(e) => setFileSize(e.target.value)} placeholder="文件大小" />
            </div>
            <div>
              <Label>描述</Label>
              <Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="资源描述" rows={3} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>取消</Button>
            <Button onClick={handleSubmit}>保存</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/portal-vue/src/views/library/resources.vue
<template>
  <div class="resources-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <span class="card-title">教学资源库</span>
          <el-button type="primary" @click="openAdd">新建资源</el-button>
        </div>
      </template>

      <!-- 类型筛选 -->
      <div class="filter-bar">
        <el-button v-for="type in allTypes" :key="type" size="small" round :type="filterType === type ? 'primary' : 'default'" @click="toggleType(type)">
          {{ RESOURCE_TYPE_LABELS[type] }}
        </el-button>
        <el-button v-if="filterType || searchQuery" size="small" text type="danger" @click="clearFilter">清除筛选</el-button>
      </div>

      <el-input v-model="searchQuery" placeholder="搜索资源名称..." clearable style="max-width: 320px; margin-bottom: 12px" @input="onSearch" @clear="onSearch" />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="资源" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">{{ row.name }}</template>
        </el-table-column>
        <el-table-column label="类型" width="130">
          <template #default="{ row }">{{ typeLabel(row.resourceType) }}</template>
        </el-table-column>
        <el-table-column label="链接" width="90">
          <template #default="{ row }">
            <a v-if="row.url && isSafeLinkUrl(row.url)" :href="row.url" target="_blank" rel="noreferrer">访问</a>
            <span v-else>-</span>
          </template>
        </el-table-column>
        <el-table-column label="大小" width="100">
          <template #default="{ row }">{{ formatSize(row.fileSize) }}</template>
        </el-table-column>
        <el-table-column label="描述" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.description || '-' }}</template>
        </el-table-column>
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openEdit(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination v-if="total > pageSize" v-model:current-page="page" :page-size="pageSize" :total="total" layout="prev, pager, next, total" class="pagination" @current-change="loadItems" />
    </el-card>

    <!-- 新增/编辑弹窗 -->
    <el-dialog v-model="dialogOpen" :title="editingItem ? '编辑资源' : '新建资源'" width="520px">
      <el-form :model="form" label-width="80px">
        <el-form-item label="名称"><el-input v-model="form.name" placeholder="输入资源名称" /></el-form-item>
        <el-form-item label="类型">
          <el-select v-model="form.resourceType" :disabled="!!editingItem" style="width: 100%">
            <el-option v-for="(label, key) in RESOURCE_TYPE_LABELS" :key="key" :label="label" :value="key" />
          </el-select>
        </el-form-item>
        <el-form-item v-if="form.resourceType === 'link'" label="URL">
          <el-input v-model="form.url" placeholder="https://..." />
        </el-form-item>
        <el-form-item v-if="isFileType" label="文件">
          <el-upload :auto-upload="false" :limit="1" :on-change="onFileChange" :file-list="fileList" accept="*">
            <el-button size="small">选择文件</el-button>
          </el-upload>
        </el-form-item>
        <el-form-item label="标签">
          <el-select v-model="form.tagIds" multiple style="width: 100%" placeholder="选择标签">
            <el-option v-for="t in tags" :key="t.id" :label="t.name" :value="t.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2" placeholder="输入资源简介、用途说明等" /></el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogOpen = false">取消</el-button>
        <el-button type="primary" :loading="submitting" @click="submit">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { UploadFile } from 'element-plus';
import { resourceLibraryApi, tagApi } from '@/api/library';
import { fileApi } from '@/api/import-export';
import { RESOURCE_TYPE_LABELS } from '@/types/library';
import type { ResourceKind, ResourceLibraryItem, TagItem } from '@/types/library';
import { formatSize, isSafeLinkUrl } from '@/utils/format';

const PAGE_SIZE = 200;
const fileTypesWithUpload = ['document', 'spreadsheet', 'image', 'audio', 'video', 'archive'];
const TAG_RESOURCE_TYPE = 'resource_library';

const allTypes = Object.keys(RESOURCE_TYPE_LABELS) as ResourceKind[];

function typeLabel(kind: string): string {
  return RESOURCE_TYPE_LABELS[kind as ResourceKind] || kind;
}

const items = ref<ResourceLibraryItem[]>([]);
const tags = ref<TagItem[]>([]);
const loading = ref(false);
const searchQuery = ref('');
const filterType = ref<ResourceKind | null>(null);
const page = ref(1);
const total = ref(0);
const pageSize = PAGE_SIZE;

const dialogOpen = ref(false);
const editingItem = ref<ResourceLibraryItem | null>(null);
const submitting = ref(false);
const fileList = ref<UploadFile[]>([]);
const currentFile = ref<File | null>(null);
const form = reactive({ name: '', resourceType: 'document' as ResourceKind, url: '', description: '', tagIds: [] as string[] });

const isFileType = computed(() => fileTypesWithUpload.includes(form.resourceType));

async function loadItems() {
  loading.value = true;
  try {
    const res = await resourceLibraryApi.list({
      ...(filterType.value ? { resourceType: filterType.value } : {}),
      ...(searchQuery.value ? { search: searchQuery.value } : {}),
      limit: PAGE_SIZE,
      offset: (page.value - 1) * PAGE_SIZE
    });
    items.value = res.items;
    total.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

async function loadTags() {
  try {
    const res = await tagApi.list();
    tags.value = res.items;
  } catch {
    /* 标签加载失败不阻断 */
  }
}

function onSearch() {
  page.value = 1;
  loadItems();
}
function toggleType(type: ResourceKind) {
  filterType.value = filterType.value === type ? null : type;
  page.value = 1;
  loadItems();
}
function clearFilter() {
  filterType.value = null;
  searchQuery.value = '';
  page.value = 1;
  loadItems();
}

function onFileChange(file: UploadFile) {
  currentFile.value = file.raw || null;
}

function resetForm() {
  form.name = '';
  form.resourceType = 'document';
  form.url = '';
  form.description = '';
  form.tagIds = [];
  fileList.value = [];
  currentFile.value = null;
}
function openAdd() {
  editingItem.value = null;
  resetForm();
  dialogOpen.value = true;
}
function openEdit(item: ResourceLibraryItem) {
  editingItem.value = item;
  form.name = item.name;
  form.resourceType = item.resourceType;
  form.url = item.url || '';
  form.description = item.description || '';
  form.tagIds = [];
  fileList.value = [];
  currentFile.value = null;
  dialogOpen.value = true;
}

async function submit() {
  if (!form.name.trim()) {
    ElMessage.warning('名称不能为空');
    return;
  }
  submitting.value = true;
  try {
    let finalUrl = form.resourceType === 'link' && form.url.trim() ? form.url.trim() : undefined;
    let finalSize: number | undefined = editingItem.value?.fileSize;
    // 文件类型：先上传文件
    if (isFileType.value && currentFile.value) {
      const up = await fileApi.upload(currentFile.value);
      finalUrl = up.url;
      finalSize = up.size;
    }
    const payload = {
      name: form.name.trim(),
      resourceType: form.resourceType,
      url: finalUrl,
      description: form.description.trim() || undefined,
      fileSize: finalSize,
      thumbnail: form.resourceType === 'image' ? finalUrl || undefined : undefined
    };
    let targetId = editingItem.value?.id;
    if (editingItem.value) {
      await resourceLibraryApi.update(editingItem.value.id, payload);
      ElMessage.success('更新成功');
    } else {
      const created = await resourceLibraryApi.create(payload);
      targetId = created.id;
      ElMessage.success('创建成功');
    }
    // 保存标签绑定
    if (targetId && form.tagIds.length) {
      try {
        await tagApi.setBindings({ resourceType: TAG_RESOURCE_TYPE, resourceId: targetId, tagIds: form.tagIds });
      } catch {
        ElMessage.warning('标签保存失败');
      }
    }
    dialogOpen.value = false;
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    submitting.value = false;
  }
}

async function confirmDelete(item: ResourceLibraryItem) {
  try {
    await ElMessageBox.confirm('确定要删除该资源吗？此操作不可恢复。', '确认删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  try {
    await resourceLibraryApi.delete(item.id);
    ElMessage.success('删除成功');
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(() => {
  loadItems();
  loadTags();
});
</script>

<style scoped>
.resources-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.filter-bar { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }
.pagination { margin-top: 16px; justify-content: flex-end; }
</style>
