// plus-ui/src-portal/views/portal/alliance/components/AllianceDetailShell.vue
<template>
  <div class="ads" :style="{ background: pageBackground }">
    <!-- 标题区 -->
    <section class="ads-header">
      <div v-if="coverImage" class="ads-cover-bg">
        <img :src="coverImage" alt="" aria-hidden="true" />
        <div class="ads-cover-mask" />
      </div>
      <div class="ads-header-inner">
        <nav v-if="showBack && crumbs.length" class="ads-crumbs">
          <template v-for="(crumb, idx) in crumbs" :key="idx">
            <el-icon v-if="idx > 0" class="ads-chev"><ArrowRight /></el-icon>
            <router-link v-if="crumb.href && idx < crumbs.length - 1" :to="crumb.href" class="ads-crumb-link">{{ crumb.label }}</router-link>
            <span v-else class="ads-crumb" :class="{ last: idx === crumbs.length - 1 }">{{ crumb.label }}</span>
          </template>
        </nav>

        <div class="ads-title-row">
          <img v-if="iconImage" :src="iconImage.src" :alt="iconImage.alt" class="ads-icon-img" :style="{ background: iconGradient }" />
          <div v-else-if="icon" class="ads-icon-box" :style="{ background: iconGradient }">
            <el-icon :size="44" color="#fff"><component :is="icon" /></el-icon>
          </div>
          <div class="ads-title-text">
            <h1 class="ads-title">{{ title }}</h1>
            <p v-if="subtitle" class="ads-subtitle">{{ subtitle }}</p>
            <div v-if="badges.length" class="ads-badges">
              <span
                v-for="(b, i) in badges"
                :key="i"
                class="ads-badge"
                :style="b.background ? { background: b.background, color: b.color || '#fff', borderColor: 'transparent' } : {}"
              >{{ b.text }}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="ads-body">
      <div class="ads-body-inner">
        <div v-if="stats.length" class="ads-stats">
          <div v-for="stat in stats" :key="stat.label" class="ads-stat">
            <div class="ads-stat-icon" :style="{ background: stat.gradient }">
              <el-icon :size="22" color="#fff"><component :is="stat.icon" /></el-icon>
            </div>
            <div class="ads-stat-text">
              <p class="ads-stat-value">{{ stat.value }}</p>
              <p class="ads-stat-label">{{ stat.label }}</p>
            </div>
          </div>
        </div>

        <el-tabs v-model="activeTab" class="ads-tabs">
          <el-tab-pane v-for="tab in tabs" :key="tab.value" :name="tab.value">
            <template #label>
              <span class="ads-tab-label">{{ tab.label }}</span>
              <span v-if="tab.count != null" class="ads-tab-count">{{ tab.count }}</span>
            </template>
            <slot :name="tab.value" />
          </el-tab-pane>
        </el-tabs>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { ArrowRight } from '@element-plus/icons-vue';

export interface BreadcrumbItem {
  label: string;
  href?: string;
}
export interface DetailStat {
  label: string;
  value: string | number;
  icon: any;
  gradient: string;
}
export interface DetailBadge {
  text: string;
  background?: string;
  color?: string;
}
export interface DetailTab {
  value: string;
  label: string;
  count?: number;
}

const props = withDefaults(
  defineProps<{
    breadcrumbs?: BreadcrumbItem[];
    backHref: string;
    backLabel?: string;
    showBack?: boolean;
    icon?: any;
    iconImage?: { src: string; alt: string };
    iconGradient?: string;
    title: string;
    subtitle?: string;
    badges?: DetailBadge[];
    stats?: DetailStat[];
    tabs: DetailTab[];
    pageGradient?: string;
    coverImage?: string;
  }>(),
  {
    showBack: true,
    iconGradient: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    badges: () => [],
    stats: () => [],
    pageGradient: 'linear-gradient(180deg, #f8fafc 0%, #ffffff 30%, rgba(239,246,255,0.4) 100%)',
  },
);

const crumbs = computed<BreadcrumbItem[]>(() => {
  if (props.breadcrumbs && props.breadcrumbs.length) return props.breadcrumbs;
  return props.showBack ? [{ label: props.backLabel || '返回列表', href: props.backHref }] : [];
});

const pageBackground = computed(() => {
  // 接受 tailwind 式 from/via/to 的近似色板；默认蓝紫渐变
  return props.pageGradient.includes('linear-gradient')
    ? props.pageGradient
    : 'linear-gradient(180deg, #f8fafc 0%, #ffffff 30%, rgba(239,246,255,0.4) 100%)';
});

const activeTab = ref(props.tabs[0]?.value ?? '');
</script>

<style scoped>
.ads { min-height: 100vh; }
.ads-header { position: relative; padding: 12px 0 32px; overflow: hidden; }
.ads-cover-bg { position: absolute; inset: 0; overflow: hidden; }
.ads-cover-bg img { width: 100%; height: 100%; object-fit: cover; filter: blur(40px); transform: scale(1.1); opacity: 0.5; }
.ads-cover-mask { position: absolute; inset: 0; background: linear-gradient(to bottom, rgba(255,255,255,0.55), rgba(255,255,255,0.75), rgba(255,255,255,0.95)); }
.ads-header-inner { position: relative; max-width: 1280px; margin: 0 auto; padding: 0 24px; }
.ads-crumbs { display: flex; align-items: center; gap: 4px; flex-wrap: wrap; font-size: 13px; color: #94a3b8; margin-bottom: 16px; }
.ads-chev { color: #cbd5e1; }
.ads-crumb-link { color: #94a3b8; text-decoration: none; white-space: nowrap; transition: color 0.2s; }
.ads-crumb-link:hover { color: #409eff; }
.ads-crumb { color: #94a3b8; white-space: nowrap; }
.ads-crumb.last { color: #334155; font-weight: 500; max-width: 260px; overflow: hidden; text-overflow: ellipsis; }
.ads-title-row { display: flex; align-items: flex-start; gap: 20px; flex-wrap: wrap; }
.ads-icon-box { width: 96px; height: 96px; border-radius: 24px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; box-shadow: 0 10px 20px rgba(0,0,0,0.15); }
.ads-icon-img { width: 80px; height: 80px; border-radius: 24px; object-fit: cover; box-shadow: 0 10px 20px rgba(0,0,0,0.15); flex-shrink: 0; border: 1px solid rgba(255,255,255,0.4); }
.ads-title-text { flex: 1; min-width: 0; }
.ads-title { font-size: 32px; font-weight: 800; color: #0f172a; line-height: 1.1; margin-bottom: 8px; word-break: break-word; }
.ads-subtitle { color: #64748b; font-size: 16px; }
.ads-badges { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-top: 12px; }
.ads-badge { display: inline-flex; align-items: center; padding: 4px 12px; border-radius: 9999px; background: rgba(255,255,255,0.7); border: 1px solid #e2e8f0; color: #475569; font-size: 12px; font-weight: 500; }
.ads-body { padding-bottom: 96px; }
.ads-body-inner { max-width: 1280px; margin: 0 auto; padding: 0 24px; }
.ads-stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 40px; }
.ads-stat { display: flex; align-items: center; gap: 16px; background: #fff; border-radius: 24px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); padding: 24px; }
.ads-stat-icon { width: 48px; height: 48px; border-radius: 16px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; box-shadow: 0 4px 10px rgba(0,0,0,0.12); }
.ads-stat-text { min-width: 0; }
.ads-stat-value { font-size: 24px; font-weight: 800; color: #0f172a; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.ads-stat-label { font-size: 12px; color: #64748b; font-weight: 500; }
.ads-tabs { background: #fff; border-radius: 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); padding: 8px 20px 20px; border: 1px solid #f1f5f9; }
.ads-tab-label { margin-right: 6px; }
.ads-tab-count { display: inline-flex; align-items: center; justify-content: center; min-width: 20px; height: 20px; padding: 0 6px; border-radius: 9999px; background: #f1f5f9; color: #64748b; font-size: 11px; font-weight: 500; line-height: 1; }
@media (max-width: 768px) {
  .ads-stats { grid-template-columns: repeat(2, 1fr); }
  .ads-title { font-size: 24px; }
  .ads-icon-box { width: 72px; height: 72px; border-radius: 18px; }
}
</style>

// frontend/edu/components/alliance/alliance-detail-shell.tsx
'use client'

// 联盟「企业视角」详情壳：breadcrumbs/stats/cover 渐变视觉（企业/品牌详情类页面用）。
// 与 components/shared/alliance-detail-shell.tsx（「门户视角」壳：notFound/loading/URL Tab 同步）并存，
// 两者 props 形态刻意不同（视觉 vs 行为），改动前先确认目标页面组归属，避免双向漂移。

import { Link } from 'react-router'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ChevronRight, type LucideIcon } from 'lucide-react'
import { EmptyState } from '@zhiyu/ui'
import { useT } from '@/lib/i18n/locale-provider'

export interface DetailStat {
  label: string
  value: React.ReactNode
  icon: LucideIcon
  /** tailwind 渐变类，如 'from-blue-500 to-blue-600' */
  gradient: string
}

export interface DetailTab {
  value: string
  label: string
  count?: number
  content: React.ReactNode
}

export interface BreadcrumbItem {
  label: string
  href?: string
}

interface AllianceDetailShellProps {
  /** 面包屑导航（如：联盟首页 > 列表 > 当前对象）；提供时优先于 backHref 按钮 */
  breadcrumbs?: BreadcrumbItem[]
  backHref: string
  backLabel?: string
  /** 隐藏返回按钮/面包屑（如企业端预览 Dialog 内，无导航语境） */
  showBack?: boolean
  /** 无 logo/图片时的渐变图标头像 */
  icon?: LucideIcon
  iconImage?: { src: string; alt: string }
  iconGradient?: string
  title: string
  subtitle?: React.ReactNode
  badges?: React.ReactNode[]
  stats?: DetailStat[]
  tabs: DetailTab[]
  /** 页面背景渐变（默认蓝紫调） */
  pageGradient?: string
  /** 头图：存在时标题区以封面模糊图 + 白色遮罩为背景 */
  coverImage?: string
}

/** 信息块：原型统一样式（label 上、value 下，灰底圆角） */
export function DetailInfoBlock({
  label,
  value,
}: {
  label: string
  value?: React.ReactNode
}) {
  return (
    <div className="p-4 rounded-2xl bg-slate-50">
      <p className="text-xs text-slate-400 mb-1">{label}</p>
      <p className="text-sm font-semibold text-slate-900">{value ?? '-'}</p>
    </div>
  )
}

/** 空态：原型统一样式（居中图标 + 文案） */
export function DetailEmpty({ icon: Icon, title }: { icon?: LucideIcon; title: string }) {
  return (
    <EmptyState
      icon={Icon ? <Icon className="h-10 w-10 opacity-50" /> : undefined}
      title={title}
      titleClassName="text-slate-500"
      className="py-16"
    />
  )
}

/** 详情卡片：渐变竖条标题 + 白卡（原型详情页统一样式） */
export function DetailSectionCard({
  icon: Icon,
  title,
  children,
  className,
}: {
  icon?: LucideIcon
  title: React.ReactNode
  children?: React.ReactNode
  className?: string
}) {
  return (
    <Card className={`border-0 shadow-sm rounded-3xl ${className ?? ''}`}>
      <CardHeader>
        <CardTitle className="text-lg flex items-center gap-2">
          <div className="h-6 w-1.5 rounded-full bg-gradient-to-b from-primary/80 to-primary/60" />
          {Icon ? <Icon className="h-4 w-4" /> : null}
          {title}
        </CardTitle>
      </CardHeader>
      {children && <CardContent>{children}</CardContent>}
    </Card>
  )
}

/**
 * 联盟前台详情页公共壳：浅渐变全屏背景（无边框/无分区）+ 面包屑 + 头像/标题/徽章 + 统计卡 + 圆角 Tabs。
 * 合作企业/合作项目/合作成果/专家详情页复用；企业端「预览展示页」同步复用。
 */
export function AllianceDetailShell({
  breadcrumbs,
  backHref,
  backLabel,
  showBack = true,
  icon: Icon,
  iconImage,
  iconGradient = 'from-blue-500 to-blue-600',
  title,
  subtitle,
  badges,
  stats,
  tabs,
  pageGradient = 'from-slate-50 via-white to-blue-50/40',
  coverImage,
}: AllianceDetailShellProps) {
  const t = useT()
  const crumbs = breadcrumbs ?? (showBack ? [{ label: backLabel || t('返回列表'), href: backHref }] : [])
  return (
    <div className={`min-h-screen bg-gradient-to-b ${pageGradient}`}>
      {/* 标题区：无独立背景块，直接铺在页面渐变上，顶部紧凑；有封面时叠加模糊封面背景 */}
      <section className="relative pt-3 lg:pt-6 pb-8 overflow-hidden">
        {coverImage && (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={coverImage}
              alt=""
              aria-hidden
              className="absolute inset-0 w-full h-full object-cover blur-2xl scale-110 opacity-50 pointer-events-none"
            />
            <div className="absolute inset-0 bg-gradient-to-b from-white/55 via-white/75 to-white/95 pointer-events-none" />
          </>
        )}
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {showBack && crumbs.length > 0 && (
            <nav className="flex items-center gap-1 text-[13px] text-slate-400 mb-4 flex-wrap">
              {crumbs.map((crumb, idx) => {
                const last = idx === crumbs.length - 1
                return (
                  <span key={idx} className="flex items-center gap-1 min-w-0">
                    {idx > 0 && <ChevronRight className="h-3 w-3 shrink-0 text-slate-300" />}
                    {crumb.href && !last ? (
                      <Link
                        to={crumb.href}
                        className="hover:text-primary transition-colors whitespace-nowrap"
                      >
                        {crumb.label}
                      </Link>
                    ) : (
                      <span
                        className={`whitespace-nowrap ${
                          last ? 'text-slate-700 font-medium truncate max-w-[260px]' : ''
                        }`}
                      >
                        {crumb.label}
                      </span>
                    )}
                  </span>
                )
              })}
            </nav>
          )}

          <div className="flex flex-col md:flex-row md:items-start gap-5">
            {iconImage ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={iconImage.src}
                alt={iconImage.alt}
                className={`h-20 w-20 rounded-3xl object-cover shadow-xl shrink-0 bg-white border border-white/40 ${iconGradient}`}
              />
            ) : Icon ? (
              <div
                className={`h-24 w-24 rounded-3xl bg-gradient-to-br ${iconGradient} flex items-center justify-center text-white shadow-xl shrink-0`}
              >
                <Icon className="w-12 h-12" />
              </div>
            ) : null}
            <div className="flex-1 min-w-0">
              <h1 className="text-2xl md:text-4xl font-extrabold text-slate-900 tracking-tight leading-[1.1] mb-2 break-words">
                {title}
              </h1>
              {subtitle && <p className="text-slate-500 text-base md:text-lg">{subtitle}</p>}
              {badges && badges.length > 0 && (
                <div className="flex flex-wrap items-center gap-2 mt-3">{badges}</div>
              )}
            </div>
          </div>
        </div>
      </section>

      <section className="pb-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {stats && stats.length > 0 && (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-10">
              {stats.map((stat) => (
                <Card key={stat.label} className="border-0 shadow-sm rounded-3xl bg-white">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-4">
                      <div
                        className={`h-12 w-12 rounded-2xl bg-gradient-to-br ${stat.gradient} text-white flex items-center justify-center shadow-lg shrink-0`}
                      >
                        <stat.icon className="h-6 w-6" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-2xl font-extrabold text-slate-900 truncate">{stat.value}</p>
                        <p className="text-xs text-slate-500 font-medium">{stat.label}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}

          <Tabs defaultValue={tabs[0]?.value} className="space-y-6">
            <TabsList className="rounded-2xl p-1 bg-white shadow-sm border border-slate-100">
              {tabs.map((tab) => (
                <TabsTrigger key={tab.value} value={tab.value} className="group rounded-xl">
                  {tab.label}
                  {typeof tab.count === 'number' && (
                    <span className="ml-1.5 rounded-full bg-slate-100 px-1.5 py-0.5 text-[11px] font-medium leading-none text-slate-500 group-data-[state=active]:bg-primary/10 group-data-[state=active]:text-primary">
                      {tab.count}
                    </span>
                  )}
                </TabsTrigger>
              ))}
            </TabsList>
            {tabs.map((tab) => (
              <TabsContent key={tab.value} value={tab.value}>
                {tab.content}
              </TabsContent>
            ))}
          </Tabs>
        </div>
      </section>
    </div>
  )
}
