// frontend/portal-vue/src/views/library/_components/ResourceBatchImportDialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    title="批量上传资源"
    width="560px"
    :close-on-click-modal="!uploading"
    :close-on-press-escape="!uploading"
    :show-close="!uploading"
    @update:model-value="onClose"
  >
    <p class="desc">支持同时选择多个文件，自动以文件名作为资源名称</p>

    <div v-if="!resourceType" class="type-row">
      <span class="type-label">资源类型</span>
      <el-select v-model="selectType" :disabled="uploading" style="flex: 1">
        <el-option
          v-for="(label, key) in RESOURCE_TYPE_LABELS"
          :key="key"
          :label="label"
          :value="key"
          :disabled="!fileTypesWithUpload.includes(key)"
        />
      </el-select>
    </div>

    <div
      class="drop-zone"
      :class="{ disabled: uploading }"
      role="button"
      tabindex="0"
      @click="!uploading && fileInputRef?.click()"
      @keydown.enter.prevent="!uploading && fileInputRef?.click()"
      @keydown.space.prevent="!uploading && fileInputRef?.click()"
      @dragover.prevent
      @drop.prevent="onDrop"
    >
      <input
        ref="fileInputRef"
        type="file"
        multiple
        :accept="resourceTypeAccept[submitType]"
        class="hidden-input"
        @change="onFileInputChange"
      />
      <div class="drop-icon">⬆</div>
      <p class="drop-title">点击或拖拽批量选择文件</p>
      <p class="drop-sub">
        支持 Office 文档、PDF、图片、CAD 图纸、音视频、压缩包、代码文件、电子书 等常见格式，单文件最大 10MB。
      </p>
    </div>

    <div v-if="files.length" class="file-list">
      <div v-for="(f, i) in files" :key="f.name + '-' + i" class="file-item">
        <span class="file-name">{{ f.name }}</span>
        <span class="file-size">{{ formatSize(f.size) }}</span>
        <el-button v-if="!uploading" link type="danger" @click="removeFile(i)">移除</el-button>
      </div>
    </div>

    <template #footer>
      <div v-if="uploading" class="uploading-hint">正在上传 {{ uploadedCount }}/{{ files.length }}...</div>
      <template v-else>
        <el-button @click="onClose(false)">取消</el-button>
        <el-button type="primary" :disabled="files.length === 0" @click="handleImport">
          开始导入（{{ files.length }}）
        </el-button>
      </template>
    </template>
  </el-dialog>

  <!-- 重名确认弹窗 -->
  <el-dialog
    v-model="duplicateOpen"
    title="发现重名资源"
    width="480px"
    append-to-body
    @closed="duplicateItems = null"
  >
    <p class="desc">
      共 {{ files.length }} 个文件，其中 {{ (duplicateItems || []).length }} 个与现有资源重名，{{ createdCount }} 个为新资源。
    </p>
    <div v-if="(duplicateItems || []).length" class="dup-list">
      <div v-for="d in duplicateItems" :key="d.id" class="dup-item">{{ d.name }}</div>
    </div>
    <template #footer>
      <el-button @click="confirmDuplicate('new')">保留为新资源</el-button>
      <el-button @click="confirmDuplicate('skip')">跳过重名</el-button>
      <el-button type="primary" @click="confirmDuplicate('overwrite')">覆盖同名</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { request } from '@/api/http';
import type { ListResponse } from '@/api/http';
import { fileApi } from '@/api/import-export';
import { resourceLibraryApi } from '@/api/library';
import { RESOURCE_TYPE_LABELS } from '@/types/library';
import type { ResourceLibraryItem } from '@/types/library';
import { useAuthStore } from '@/stores/auth';
import { formatSize } from '@/utils/format';
import { fileTypesWithUpload, resourceTypeAccept, validateResourceFile } from './resource-types';

const props = defineProps<{
  modelValue: boolean;
  resourceType?: string;
}>();
const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'imported'): void;
}>();

const auth = useAuthStore();
const currentUserId = computed(() => auth.user?.id || '');

const fileInputRef = ref<HTMLInputElement | null>(null);
const files = ref<File[]>([]);
const selectType = ref('document');
const uploading = ref(false);
const uploadedCount = ref(0);
const duplicateItems = ref<ResourceLibraryItem[] | null>(null);
const duplicateOpen = ref(false);

const submitType = computed(() => props.resourceType || selectType.value);
const createdCount = computed(() => files.value.length - (duplicateItems.value?.length || 0));

function addFiles(incoming: File[]): void {
  if (!fileTypesWithUpload.includes(submitType.value)) return;
  const accepted: File[] = [];
  let skipped = 0;
  for (const file of incoming) {
    const err = validateResourceFile(file, submitType.value);
    if (err) skipped += 1;
    else accepted.push(file);
  }
  if (accepted.length > 0) files.value = [...files.value, ...accepted];
  if (skipped > 0) {
    ElMessage.error(`${skipped} 个文件格式不支持或超过 10MB，已跳过`);
  }
}

function onDrop(e: DragEvent): void {
  if (!uploading.value) addFiles(Array.from(e.dataTransfer?.files || []));
}

function onFileInputChange(e: Event): void {
  const target = e.target as HTMLInputElement;
  if (!uploading.value) addFiles(Array.from(target.files || []));
  target.value = '';
}

function removeFile(i: number): void {
  files.value = files.value.filter((_, idx) => idx !== i);
}

function reset(): void {
  files.value = [];
  uploadedCount.value = 0;
  duplicateItems.value = null;
}

function onClose(v: boolean): void {
  if (uploading.value) return;
  emit('update:modelValue', v);
  if (!v) reset();
}

async function previewImport(names: string[]): Promise<ResourceLibraryItem[]> {
  const res = await request<ListResponse<ResourceLibraryItem>>('/library/resources/import/preview', {
    method: 'POST',
    body: JSON.stringify({ names, resourceType: submitType.value })
  });
  return res.items || [];
}

async function runImport(mode: 'skip' | 'overwrite' | 'new', existing: ResourceLibraryItem[]): Promise<void> {
  const existingByName = new Map(existing.map((item) => [item.name, item]));
  duplicateItems.value = null;
  uploading.value = true;
  uploadedCount.value = 0;
  let success = 0;
  let failed = 0;
  let skipped = 0;
  let permissionSkipped = 0;
  for (let i = 0; i < files.value.length; i++) {
    const file = files.value[i];
    const existingItem = existingByName.get(file.name);
    if (existingItem && mode === 'skip') {
      skipped += 1;
      uploadedCount.value = i + 1;
      continue;
    }
    if (existingItem && mode === 'overwrite' && existingItem.uploadedBy !== currentUserId.value) {
      permissionSkipped += 1;
      uploadedCount.value = i + 1;
      continue;
    }
    try {
      const res = await fileApi.upload(file);
      const payload: Record<string, unknown> = {
        name: file.name,
        resourceType: submitType.value,
        url: res.url,
        thumbnail: submitType.value === 'image' ? res.url : undefined,
        fileSize: res.size
      };
      if (existingItem && mode === 'overwrite') {
        await resourceLibraryApi.update(existingItem.id, payload as never);
      } else {
        if (existingItem) {
          payload.name = `${file.name}-${Math.floor(1000 + Math.random() * 9000)}`;
        }
        await resourceLibraryApi.create(payload as never);
      }
      success += 1;
    } catch {
      failed += 1;
    }
    uploadedCount.value = i + 1;
  }
  uploading.value = false;

  const skippedMsg = skipped > 0 ? `，跳过 ${skipped} 个同名资源` : '';
  const permissionMsg = permissionSkipped > 0 ? `，${permissionSkipped} 个资源非本人创建，已跳过覆盖` : '';
  if (failed > 0) {
    ElMessage.error(`批量上传完成：成功 ${success} 个，失败 ${failed} 个${skippedMsg}${permissionMsg}`);
  } else {
    ElMessage.success(`批量上传成功：成功导入 ${success} 个资源${skippedMsg}${permissionMsg}`);
  }
  emit('imported');
  emit('update:modelValue', false);
  reset();
}

async function handleImport(): Promise<void> {
  if (files.value.length === 0) return;
  if (!fileTypesWithUpload.includes(submitType.value)) return;
  let existing: ResourceLibraryItem[] = [];
  try {
    existing = await previewImport(files.value.map((f) => f.name));
  } catch {
    /* 重名校验失败时按普通导入执行，容忍小概率异常 */
  }
  if (existing.length > 0) {
    duplicateItems.value = existing;
    duplicateOpen.value = true;
    return;
  }
  await runImport('skip', []);
}

async function confirmDuplicate(mode: 'skip' | 'overwrite' | 'new'): Promise<void> {
  duplicateOpen.value = false;
  await runImport(mode, duplicateItems.value || []);
}
</script>

<style scoped>
.desc {
  margin: 0 0 12px;
  font-size: 13px;
  color: #94a3b8;
}
.type-row {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
}
.type-label {
  font-size: 13px;
  color: #334155;
  flex-shrink: 0;
}
.drop-zone {
  border: 2px dashed #d1d5db;
  border-radius: 12px;
  padding: 24px 16px;
  text-align: center;
  cursor: pointer;
  transition: all 0.2s;
}
.drop-zone:hover {
  border-color: #409eff;
  background: #f9fafb;
}
.drop-zone.disabled {
  cursor: not-allowed;
  opacity: 0.6;
}
.drop-icon {
  font-size: 24px;
  color: #9ca3af;
  margin-bottom: 8px;
}
.drop-title {
  margin: 0 0 4px;
  font-size: 14px;
  font-weight: 500;
  color: #374151;
}
.drop-sub {
  margin: 0;
  font-size: 12px;
  color: #9ca3af;
  word-break: break-word;
}
.hidden-input {
  display: none;
}
.file-list {
  margin-top: 12px;
  max-height: 200px;
  overflow-y: auto;
}
.file-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border: 1px solid #f1f5f9;
  border-radius: 8px;
  background: #f8fafc;
  margin-bottom: 6px;
}
.file-name {
  flex: 1;
  font-size: 13px;
  color: #374151;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.file-size {
  font-size: 12px;
  color: #9ca3af;
}
.uploading-hint {
  font-size: 13px;
  color: #6b7280;
}
.dup-list {
  max-height: 200px;
  overflow-y: auto;
  margin-top: 8px;
}
.dup-item {
  padding: 6px 8px;
  border-bottom: 1px solid #f1f5f9;
  font-size: 13px;
  color: #374151;
}
</style>

// apps/edu/app/library/resources/_components/resource-batch-import-dialog.tsx
'use client'

import { useCallback, useRef, useState } from 'react'
import { Upload, File, Loader2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { useToast } from '@zhiyu/ui'
import { fileApi, resourceLibraryApi } from '@/lib/api'
import { RESOURCE_TYPE_LABELS, type ResourceLibraryItem } from '@/lib/types/library'
import { ImportConfirmDialog } from '@/components/shared/import-confirm-dialog'
import { useAuth } from '@/components/auth-provider'
import {
  fileTypesWithUpload,
  resourceTypeAccept,
  validateResourceFile,
} from '@/lib/resource-type-constants'
import { useT } from '@/lib/i18n/locale-provider'

interface ResourceBatchImportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** 单类型视图传入固定类型；总览视图不传，由用户在选择文件中自行选择 */
  resourceType?: string
  onImported: () => void
}

export function ResourceBatchImportDialog({
  open,
  onOpenChange,
  resourceType,
  onImported,
}: ResourceBatchImportDialogProps) {
  const t = useT()
  const { toast } = useToast()
  const { user } = useAuth()
  const currentUserId = user?.id ?? ''
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [files, setFiles] = useState<File[]>([])
  const [selectType, setSelectType] = useState('document')
  const [uploading, setUploading] = useState(false)
  const [uploadedCount, setUploadedCount] = useState(0)
  const [duplicateItems, setDuplicateItems] = useState<ResourceLibraryItem[] | null>(null)

  const submitType = resourceType || selectType

  const addFiles = useCallback(
    (incoming: File[]) => {
      if (!fileTypesWithUpload.includes(submitType)) return
      const accepted: File[] = []
      let skipped = 0
      for (const file of incoming) {
        const err = validateResourceFile(file, submitType)
        if (err) {
          skipped += 1
        } else {
          accepted.push(file)
        }
      }
      if (accepted.length > 0) {
        setFiles((prev) => [...prev, ...accepted])
      }
      if (skipped > 0) {
        toast({
          variant: 'destructive',
          title: t('部分文件被跳过'),
          description: t('{n} 个文件格式不支持或超过 100MB，已跳过', { n: skipped }),
        })
      }
    },
    [submitType, toast, t],
  )

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    addFiles(Array.from(e.dataTransfer.files || []))
  }

  const reset = () => {
    setFiles([])
    setUploadedCount(0)
    setDuplicateItems(null)
  }

  const handleClose = (v: boolean) => {
    if (uploading) return
    onOpenChange(v)
    if (!v) reset()
  }

  const runImport = async (mode: 'skip' | 'overwrite' | 'new', existing: ResourceLibraryItem[]) => {
    const existingByName = new Map(existing.map((item) => [item.name, item]))
    setDuplicateItems(null)
    setUploading(true)
    setUploadedCount(0)
    let success = 0
    let failed = 0
    let skipped = 0
    let permissionSkipped = 0
    for (let i = 0; i < files.length; i++) {
      const file = files[i]
      const existingItem = existingByName.get(file.name)
      if (existingItem && mode === 'skip') {
        skipped += 1
        setUploadedCount(i + 1)
        continue
      }
      if (existingItem && mode === 'overwrite' && existingItem.uploadedBy !== currentUserId) {
        permissionSkipped += 1
        setUploadedCount(i + 1)
        continue
      }
      try {
        const res = await fileApi.upload(file)
        const payload = {
          name: file.name,
          resourceType: submitType as any,
          url: res.url,
          thumbnail: submitType === 'image' ? res.url : undefined,
          fileSize: res.size,
          description: undefined,
        }
        if (existingItem && mode === 'overwrite') {
          await resourceLibraryApi.update(existingItem.id, payload as any)
        } else {
          if (existingItem) {
            payload.name = `${file.name}-${Math.floor(1000 + Math.random() * 9000)}`
          }
          await resourceLibraryApi.create(payload as any)
        }
        success += 1
      } catch {
        failed += 1
      }
      setUploadedCount(i + 1)
    }
    setUploading(false)
    const skippedMsg = skipped > 0 ? t('，跳过 {n} 个同名资源', { n: skipped }) : ''
    const permissionMsg =
      permissionSkipped > 0
        ? t('，{n} 个资源非本人创建，已跳过覆盖', { n: permissionSkipped })
        : ''
    if (failed > 0) {
      toast({
        variant: 'destructive',
        title: t('批量上传完成'),
        description: t('成功 {ok} 个，失败 {fail} 个', {
          ok: success,
          fail: failed,
        }) + skippedMsg + permissionMsg,
      })
    } else {
      toast({
        title: t('批量上传成功'),
        description: t('成功导入 {n} 个资源', { n: success }) + skippedMsg + permissionMsg,
      })
    }
    onImported()
    onOpenChange(false)
    reset()
  }

  const handleImport = async () => {
    if (files.length === 0) return
    if (!fileTypesWithUpload.includes(submitType)) return
    let existing: ResourceLibraryItem[] = []
    try {
      const res = await resourceLibraryApi.previewImport(
        files.map((f) => f.name),
        submitType,
      )
      existing = res.items || []
    } catch {
      // 重名校验失败时按普通导入执行，容忍小概率异常
    }
    if (existing.length > 0) {
      setDuplicateItems(existing)
      return
    }
    await runImport('skip', [])
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{t('批量上传资源')}</DialogTitle>
          <DialogDescription>{t('支持同时选择多个文件，自动以文件名作为资源名称')}</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-2">
          {!resourceType && (
            <div>
              <Label>{t('资源类型')}</Label>
              <Select value={selectType} onValueChange={setSelectType}>
                <SelectTrigger className="mt-1.5">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(RESOURCE_TYPE_LABELS).map(([key, label]) => (
                    <SelectItem key={key} value={key} disabled={!fileTypesWithUpload.includes(key)}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}
          <div
            className="border-2 border-dashed rounded-xl p-6 text-center space-y-3 transition-colors cursor-pointer hover:border-primary/30 hover:bg-gray-50/50"
            onClick={() => !uploading && fileInputRef.current?.click()}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if ((e.key === 'Enter' || e.key === ' ') && !uploading) {
                e.preventDefault()
                fileInputRef.current?.click()
              }
            }}
            onDragOver={(e) => {
              e.preventDefault()
              e.stopPropagation()
            }}
            onDrop={handleDrop}
          >
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept={resourceTypeAccept[submitType]}
              className="hidden"
              onChange={(e) => {
                addFiles(Array.from(e.target.files || []))
                e.target.value = ''
              }}
            />
            <div className="w-12 h-12 bg-gray-50 rounded-full flex items-center justify-center mx-auto">
              <Upload className="h-6 w-6 text-gray-400" />
            </div>
            <div>
              <p className="text-sm font-medium text-gray-700">{t('点击或拖拽批量选择文件')}</p>
              <p className="text-xs text-gray-500 mt-1 break-words">
                {t('支持 Office 文档、PDF、图片、CAD 图纸、音视频、压缩包、代码文件、电子书 等常见格式，单文件最大 100MB。')}
              </p>
            </div>
          </div>

          {files.length > 0 && (
            <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
              {files.map((f, i) => (
                <div
                  key={`${f.name}-${i}`}
                  className="flex items-center gap-2 rounded-lg border border-slate-100 bg-slate-50/50 px-3 py-2"
                >
                  <File className="size-4 text-gray-400 shrink-0" />
                  <span className="text-sm text-gray-700 truncate flex-1">{f.name}</span>
                  {!uploading && (
                    <button
                      className="text-gray-400 hover:text-gray-600"
                      onClick={() => setFiles((prev) => prev.filter((_, idx) => idx !== i))}
                    >
                      <X className="size-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
        <DialogFooter>
          {uploading ? (
            <div className="flex items-center gap-2 text-sm text-gray-500 w-full justify-center">
              <Loader2 className="h-4 w-4 animate-spin" />
              {t('正在上传 {a}/{b}...', { a: uploadedCount, b: files.length })}
            </div>
          ) : (
            <>
              <Button variant="outline" onClick={() => handleClose(false)}>
                {t('取消')}
              </Button>
              <Button onClick={handleImport} disabled={files.length === 0}>
                {t('开始导入（{n}）', { n: files.length })}
              </Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
      <ImportConfirmDialog
        open={duplicateItems !== null}
        onOpenChange={(open) => {
          if (!open) setDuplicateItems(null)
        }}
        entityLabel="资源"
        created={files.length - (duplicateItems?.length || 0)}
        duplicates={duplicateItems?.length || 0}
        failed={0}
        duplicateItems={(duplicateItems || []).map((item) => ({ key: item.id, name: item.name }))}
        onConfirmOverwrite={() => duplicateItems && runImport('overwrite', duplicateItems)}
        onConfirmSkip={() => duplicateItems && runImport('skip', duplicateItems)}
        onConfirmNew={() => duplicateItems && runImport('new', duplicateItems)}
      />
    </Dialog>
  )
}
