// apps/edu/app/portal/apps/system/resource/industries/page.tsx
'use client'

import { useEffect, useMemo, useState, useCallback } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { FormFieldRow } from '@/components/shared/form-field-row'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Pencil, Trash2 } from 'lucide-react'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { industryApi } from '@/lib/api'
import { useToast } from '@zhiyu/ui'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import type { Industry } from '@/lib/types/backend'

export default function IndustriesPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const [industries, setIndustries] = useState<Industry[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchIndustries = useCallback(async () => {
    if (!tenantId) return
    setLoading(true)
    setError(null)
    try {
      const res = await industryApi.list({ tenantId, limit: 1000 })
      setIndustries(res.items)
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载行业数据失败')
    } finally {
      setLoading(false)
    }
  }, [tenantId])

  useEffect(() => {
    if (authLoading || !tenantId) return
    ;(async () => {
      await fetchIndustries()
    })()
  }, [tenantId, authLoading, fetchIndustries])

  const parentMap = useMemo(() => {
    const map = new Map<string, string>()
    for (const ind of industries) {
      if (ind.parentId) {
        const parent = industries.find((i) => i.id === ind.parentId)
        map.set(ind.parentId, parent?.name ?? ind.parentId)
      }
    }
    return map
  }, [industries])

  const candidateParents = useMemo(() => industries, [industries])

  return (
    <PortalCrudPage
      title="行业管理"
      description="管理行业分类，可为行业设置上级行业并启用/关闭"
      entityLabel="行业"
      searchPlaceholder="搜索行业代码、名称或上级行业..."
      createButtonLabel="新增行业"
      items={industries}
      loading={loading}
      error={error}
      onRetry={fetchIndustries}
      filterItems={(items, searchTerm) =>
        items.filter((ind) => {
          if (!searchTerm) return true
          const parentName = ind.parentId ? parentMap.get(ind.parentId) : ''
          return (
            ind.name.includes(searchTerm) ||
            ind.code.includes(searchTerm) ||
            (parentName ?? '').includes(searchTerm)
          )
        })
      }
      importConfig={{
        importType: 'industries',
        entityLabel: '行业',
        templateFileName: '行业批量导入模板.xlsx',
      }}
      colSpan={7}
      renderTableHeader={() => (
        <>
          <TableHead className="w-28">行业代码</TableHead>
          <TableHead>行业名称</TableHead>
          <TableHead>上级行业</TableHead>
          <TableHead className="w-20 text-center">排序</TableHead>
          <TableHead className="w-24 text-center">状态</TableHead>
          <TableHead className="w-24 text-center">启用/关闭</TableHead>
          <TableHead className="w-20 text-center">操作</TableHead>
        </>
      )}
      renderTableRow={(industry, actions) => (
        <>
          <TableCell className="font-mono text-sm">{industry.code}</TableCell>
          <TableCell className="font-medium">{industry.name}</TableCell>
          <TableCell className="text-muted-foreground">
            {industry.parentId ? (
              (parentMap.get(industry.parentId) ?? industry.parentId)
            ) : (
              <span className="text-gray-300">-</span>
            )}
          </TableCell>
          <TableCell className="text-center text-sm text-muted-foreground">
            {industry.sortOrder}
          </TableCell>
          <TableCell className="text-center">
            <Badge variant={industry.enabled ? 'default' : 'secondary'}>
              {industry.enabled ? '已启用' : '已关闭'}
            </Badge>
          </TableCell>
          <TableCell className="text-center">
            <Switch checked={industry.enabled} onCheckedChange={actions.toggle} />
          </TableCell>
          <TableRowActions>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={actions.edit}>
              <Pencil className="mr-1 h-3 w-3" />
              编辑
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
              onClick={actions.delete}
            >
              <Trash2 className="mr-1 h-3 w-3" />
              删除
            </Button>
          </TableRowActions>
        </>
      )}
      createDefault={() =>
        ({ id: '', code: '', name: '', parentId: '', sortOrder: 0, enabled: true }) as Industry
      }
      renderForm={(item, setItem) => {
        const set = (patch: Partial<Industry>) => setItem({ ...item, ...patch })
        return (
          <>
            <FormFieldRow label="行业代码" required>
              <Input
                placeholder="如：IT"
                value={item.code}
                onChange={(e) => set({ code: e.target.value })}
                disabled={!!item.id}
              />
            </FormFieldRow>
            <FormFieldRow label="行业名称" required>
              <Input
                placeholder="如：信息技术"
                value={item.name}
                onChange={(e) => set({ name: e.target.value })}
              />
            </FormFieldRow>
            <FormFieldRow label="上级行业">
              <Select
                value={item.parentId || '__none__'}
                onValueChange={(val) => set({ parentId: val === '__none__' ? '' : val })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="无（顶级行业）" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">无（顶级行业）</SelectItem>
                  {candidateParents
                    .filter((i) => i.id !== item.id)
                    .map((ind) => (
                      <SelectItem key={ind.id} value={ind.id}>
                        {ind.name} ({ind.code})
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </FormFieldRow>
            <FormFieldRow label="排序">
              <Input
                type="number"
                placeholder="0"
                value={item.sortOrder}
                onChange={(e) => set({ sortOrder: Number(e.target.value) || 0 })}
              />
            </FormFieldRow>
          </>
        )
      }}
      getDeleteDescription={(item) => (
        <>
          确定要删除行业 <span className="font-medium">{item.name}</span>（{item.code}
          ）吗？此操作不可撤销。
        </>
      )}
      onSave={async (item, isEdit) => {
        if (!tenantId) {
          toast({ variant: 'destructive', title: '保存失败', description: '未获取到租户信息' })
          return
        }
        if (!item.code.trim() || !item.name.trim()) return
        if (isEdit) {
          await industryApi.update(item.id, {
            code: item.code.trim(),
            name: item.name.trim(),
            parentId: item.parentId || undefined,
            enabled: item.enabled,
            sortOrder: item.sortOrder,
          })
          toast({ title: '保存成功', description: '行业信息已更新' })
        } else {
          await industryApi.create({
            tenantId,
            code: item.code.trim(),
            name: item.name.trim(),
            parentId: item.parentId || undefined,
            enabled: true,
            sortOrder: item.sortOrder,
          })
          toast({ title: '创建成功', description: '新行业已添加' })
        }
      }}
      onDelete={async (item) => {
        await industryApi.delete(item.id)
      }}
      onToggleEnabled={async (item) => {
        await industryApi.update(item.id, {
          code: item.code,
          name: item.name,
          parentId: item.parentId || undefined,
          enabled: !item.enabled,
          sortOrder: item.sortOrder,
        })
        toast({ title: !item.enabled ? '已启用' : '已关闭' })
      }}
    />
  )
}

// frontend/portal-vue/src/views/system/industries.vue
<template>
  <div class="list-page">
    <div class="page-header">
      <div>
        <h1 class="page-title">行业管理</h1>
        <p class="page-desc">管理行业分类，可为行业设置上级行业并启用/关闭</p>
      </div>
      <div class="header-actions">
        <el-button @click="importDialog = true">批量导入</el-button>
      </div>
    </div>

    <el-input
      v-model="keyword"
      placeholder="搜索行业代码、名称或上级行业..."
      clearable
      style="max-width: 320px; margin-bottom: 16px"
    />

    <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon style="margin-bottom: 16px">
      <template #default>
        <el-button size="small" text type="primary" @click="loadItems">重试</el-button>
      </template>
    </el-alert>

    <el-card shadow="never">
      <el-table v-loading="loading" :data="filteredItems" stripe :empty-text="loading ? '加载中...' : '暂无行业数据'">
        <el-table-column prop="code" label="行业代码" width="120">
          <template #default="{ row }"><span class="cell-mono">{{ row.code }}</span></template>
        </el-table-column>
        <el-table-column prop="name" label="行业名称" min-width="140" show-overflow-tooltip>
          <template #default="{ row }"><span class="cell-strong">{{ row.name }}</span></template>
        </el-table-column>
        <el-table-column label="上级行业" min-width="140">
          <template #default="{ row }">{{ parentName(row.parentId) }}</template>
        </el-table-column>
        <el-table-column prop="sortOrder" label="排序" width="80" align="center" />
        <el-table-column label="状态" width="90">
          <template #default="{ row }">
            <el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '已启用' : '已关闭' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="启用/关闭" width="100" align="center">
          <template #default="{ row }">
            <el-switch :model-value="row.enabled" @change="onToggle(row)" />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openDialog(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialog" title="编辑行业" width="480px">
      <el-form label-width="90px">
        <el-form-item label="行业代码" required>
          <el-input v-model="form.code" placeholder="如：IT" :disabled="!!editing" />
        </el-form-item>
        <el-form-item label="行业名称" required>
          <el-input v-model="form.name" placeholder="如：信息技术" />
        </el-form-item>
        <el-form-item label="上级行业">
          <el-select v-model="form.parentId" clearable style="width: 100%" placeholder="无（顶级行业）">
            <el-option
              v-for="i in parentOptions"
              :key="i.id"
              :label="`${i.name} (${i.code})`"
              :value="i.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="form.sortOrder" :min="0" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="importDialog" title="批量导入行业" width="560px">
      <ImportExport entity="industries" :on-imported="loadItems" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';
import { industryApi } from '@/api/system';
import type { Industry } from '@/types/system';
import ImportExport from '@/components/ImportExport.vue';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const items = ref<Industry[]>([]);
const loading = ref(false);
const error = ref('');
const keyword = ref('');
const dialog = ref(false);
const importDialog = ref(false);
const saving = ref(false);
const editing = ref<Industry | null>(null);
const form = reactive({ code: '', name: '', parentId: '', sortOrder: 0 });

const parentMap = computed<Map<string, string>>(() => {
  const byId = new Map(items.value.map((i) => [i.id, i]));
  const map = new Map<string, string>();
  for (const ind of items.value) {
    if (ind.parentId) {
      map.set(ind.parentId, byId.get(ind.parentId)?.name ?? ind.parentId);
    }
  }
  return map;
});

const parentOptions = computed<Industry[]>(() => {
  if (!editing.value) return items.value;
  return items.value.filter((i) => i.id !== editing.value!.id);
});

function parentName(id?: string): string {
  if (!id) return '-';
  return parentMap.value.get(id) ?? id;
}

const filteredItems = computed<Industry[]>(() => {
  const k = keyword.value.trim();
  if (!k) return items.value;
  return items.value.filter((ind) => {
    const pName = ind.parentId ? parentMap.value.get(ind.parentId) : '';
    return ind.name.includes(k) || ind.code.includes(k) || (pName ?? '').includes(k);
  });
});

async function loadItems() {
  if (!tenantId.value) return;
  loading.value = true;
  error.value = '';
  try {
    const res = await industryApi.list({ tenantId: tenantId.value, limit: 1000 });
    items.value = res.items;
  } catch (e) {
    error.value = (e as Error).message || '加载失败';
  } finally {
    loading.value = false;
  }
}

function openDialog(row: Industry) {
  editing.value = row;
  form.code = row.code;
  form.name = row.name;
  form.parentId = row.parentId || '';
  form.sortOrder = row.sortOrder ?? 0;
  dialog.value = true;
}

async function save() {
  if (!form.code.trim() || !form.name.trim()) {
    ElMessage.warning('请填写行业代码与名称');
    return;
  }
  if (!editing.value) {
    ElMessage.error('未获取到行业信息');
    return;
  }
  saving.value = true;
  try {
    await industryApi.update(editing.value.id, {
      code: form.code.trim(),
      name: form.name.trim(),
      parentId: form.parentId || undefined,
      enabled: editing.value.enabled,
      sortOrder: form.sortOrder
    });
    ElMessage.success('行业信息已更新');
    dialog.value = false;
    await loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function onToggle(row: Industry) {
  try {
    await industryApi.update(row.id, {
      code: row.code,
      name: row.name,
      parentId: row.parentId || undefined,
      enabled: !row.enabled,
      sortOrder: row.sortOrder
    });
    ElMessage.success(row.enabled ? '已关闭' : '已启用');
    await loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
    await loadItems();
  }
}

async function confirmDelete(row: Industry) {
  try {
    await ElMessageBox.confirm(
      `确定要删除行业「${row.name}」（${row.code}）吗？此操作不可撤销。`,
      '确认删除',
      { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }
    );
  } catch {
    return;
  }
  try {
    await industryApi.delete(row.id);
    ElMessage.success('删除成功');
    await loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(loadItems);
</script>

<style scoped>
.list-page { padding: 16px; }
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}
.page-title { font-size: 20px; font-weight: 600; margin: 0; }
.page-desc { color: #909399; font-size: 13px; margin: 4px 0 0; }
.header-actions { display: flex; gap: 8px; }
.cell-strong { font-weight: 500; }
.cell-mono { font-family: monospace; font-size: 13px; }
</style>
