// apps/edu/components/shared/cover-image-upload.tsx
'use client'

import { useRef, useState } from 'react'
import { Loader2, Upload } from 'lucide-react'
import { toast } from '@zhiyu/ui'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'

import { ImageEditorDialog } from './image-editor-dialog'
import { isPassthroughImage, isUndecodableImage } from './image-upload-utils'

interface CoverImageUploadProps {
  imageUrl: string
  uploading: boolean
  label: string
  alt: string
  onUpload: (file: File) => void
  onRemove: () => void
}

export function CoverImageUpload({
  imageUrl,
  uploading,
  label,
  alt,
  onUpload,
  onRemove,
}: CoverImageUploadProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [editTarget, setEditTarget] = useState<{ src: string; file: File } | null>(null)

  const triggerUpload = () => {
    if (!uploading) inputRef.current?.click()
  }

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    e.target.value = ''
    if (!file) return
    if (isUndecodableImage(file)) {
      toast({ title: '暂不支持 HEIC/HEIF 格式，请先转换后再上传', variant: 'destructive' })
      return
    }
    if (isPassthroughImage(file)) {
      onUpload(file)
      return
    }
    setEditTarget({ src: URL.createObjectURL(file), file })
  }

  const finishEdit = (file?: File) => {
    const target = editTarget
    setEditTarget(null)
    if (target) URL.revokeObjectURL(target.src)
    if (file) onUpload(file)
  }

  return (
    <>
      <Label className="block mb-3">{label}</Label>
      <div
        className="aspect-video bg-gray-100 rounded-lg border-2 border-dashed border-gray-200 flex flex-col items-center justify-center cursor-pointer hover:bg-gray-50 transition-colors overflow-hidden relative group"
        onClick={triggerUpload}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault()
            triggerUpload()
          }
        }}
      >
        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={handleFileSelect}
        />
        {imageUrl ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={imageUrl} alt={alt} className="object-cover w-full h-full absolute inset-0" />
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
              <Button
                variant="outline"
                size="sm"
                className="bg-white/90 text-gray-800 border-white hover:bg-white"
                onClick={(e) => {
                  e.stopPropagation()
                  triggerUpload()
                }}
                disabled={uploading}
              >
                {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : '更换封面'}
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="bg-white/90 text-gray-800 border-white hover:bg-white"
                onClick={(e) => {
                  e.stopPropagation()
                  onRemove()
                }}
                disabled={uploading}
              >
                移除封面
              </Button>
            </div>
          </>
        ) : (
          <div className="flex flex-col items-center">
            {uploading ? (
              <Loader2 className="h-8 w-8 text-gray-400 mb-2 animate-spin" />
            ) : (
              <Upload className="h-8 w-8 text-gray-400 mb-2" />
            )}
            <span className="text-sm text-gray-500">
              {uploading ? '上传中...' : `点击上传${label.replace('封面', '')}封面`}
            </span>
          </div>
        )}
      </div>
      <ImageEditorDialog
        open={!!editTarget}
        src={editTarget?.src || ''}
        fileName={editTarget?.file.name || 'image'}
        mimeType={editTarget?.file.type || 'image/png'}
        onConfirm={(file) => finishEdit(file)}
        onCancel={() => finishEdit()}
      />
    </>
  )
}

// frontend/portal-vue/src/views/job/position-builder/CoverImageUpload.vue
<template>
  <!-- 封面上传（对齐 React frontend/edu/components/shared/cover-image-upload.tsx） -->
  <div>
    <div class="cover-label">{{ label }}</div>
    <div class="cover-box" role="button" tabindex="0" @click="triggerUpload" @keydown.enter.prevent="triggerUpload">
      <input ref="inputRef" type="file" accept="image/*" class="cover-input" @change="onFileSelect" />
      <template v-if="imageUrl">
        <img :src="imageUrl" :alt="alt" class="cover-img" />
        <div class="cover-mask">
          <el-button size="small" :loading="uploading" @click.stop="triggerUpload">更换封面</el-button>
          <el-button size="small" :disabled="uploading" @click.stop="emit('remove')">移除封面</el-button>
        </div>
      </template>
      <div v-else class="cover-empty">
        <el-icon v-if="uploading" class="is-loading" :size="28"><Loading /></el-icon>
        <el-icon v-else :size="28"><UploadFilled /></el-icon>
        <span class="cover-tip">{{ uploading ? '上传中...' : `点击上传${label}` }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ElMessage } from 'element-plus';
import { Loading, UploadFilled } from '@element-plus/icons-vue';

const props = defineProps<{
  imageUrl: string;
  uploading: boolean;
  label: string;
  alt: string;
}>();

const emit = defineEmits<{
  (e: 'upload', file: File): void;
  (e: 'remove'): void;
}>();

const inputRef = ref<HTMLInputElement | null>(null);

function triggerUpload() {
  if (!props.uploading) inputRef.value?.click();
}

/** HEIC/HEIF 浏览器无法解码，与 React image-upload-utils.isUndecodableImage 一致直接拒绝 */
function isUndecodableImage(file: File): boolean {
  const name = file.name.toLowerCase();
  return (
    file.type === 'image/heic' ||
    file.type === 'image/heif' ||
    name.endsWith('.heic') ||
    name.endsWith('.heif')
  );
}

function onFileSelect(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  input.value = '';
  if (!file) return;
  if (isUndecodableImage(file)) {
    ElMessage.error('暂不支持 HEIC/HEIF 格式，请先转换后再上传');
    return;
  }
  emit('upload', file);
}
</script>

<style scoped>
.cover-label {
  margin-bottom: 10px;
  font-size: 13px;
  font-weight: 500;
  color: #303133;
}
.cover-box {
  position: relative;
  aspect-ratio: 16 / 9;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  cursor: pointer;
  border: 2px dashed #dcdfe6;
  border-radius: 8px;
  background: #f5f7fa;
  transition: background 0.2s;
}
.cover-box:hover {
  background: #f0f2f5;
}
.cover-input {
  display: none;
}
.cover-img {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.cover-mask {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: rgba(0, 0, 0, 0.45);
  opacity: 0;
  transition: opacity 0.2s;
}
.cover-box:hover .cover-mask {
  opacity: 1;
}
.cover-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: #909399;
}
.cover-tip {
  font-size: 13px;
}
</style>
