// frontend/edu/app/not-found.tsx
'use client'

import { Link } from 'react-router'
import { Button } from '@/components/ui/button'
import { useT } from '@/lib/i18n/locale-provider'

export default function NotFound() {
  const t = useT()
  return (
    <div className="flex min-h-dvh flex-col items-center justify-center gap-4 px-4 text-center">
      <p className="text-5xl">404</p>
      <p className="text-sm text-muted-foreground">{t('页面不存在或已被移除')}</p>
      <Button asChild variant="outline">
        <Link to="/portal/workspace">{t('返回工作台')}</Link>
      </Button>
    </div>
  )
}

// frontend/portal-vue/src/views/not-found.vue
<template>
  <div class="not-found">
    <p class="code">404</p>
    <p class="desc">页面不存在或已被移除</p>
    <el-button @click="$router.push('/portal/workspace')">返回工作台</el-button>
  </div>
</template>

<script setup lang="ts">
// 对齐 React app/not-found.tsx：未命中路由展示 404 页
</script>

<style scoped>
.not-found {
  min-height: 60vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 16px;
  text-align: center;
  padding: 0 16px;
}
.code {
  font-size: 48px;
  font-weight: 700;
  margin: 0;
  color: #303133;
}
.desc {
  font-size: 14px;
  color: #909399;
  margin: 0;
}
</style>
