// apps/edu/app/partner/schools/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { partnerSchoolApi, type PartnerSchoolStatus } from '@/lib/api'
import { useAsync, useToast } from '@zhiyu/ui'
import { allianceLabel } from '@zhiyu/shared-types'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { formatDate } from '@/lib/format-utils'
import { usePartnerAuth } from '@/components/partner-auth-provider'
import { useT } from '@/lib/i18n/locale-provider'

export default function PartnerSchoolsPage() {
  const { user, loading: authLoading } = usePartnerAuth()
  const { toast } = useToast()
  const t = useT()
  const [actingId, setActingId] = useState<string | null>(null)
  const [terminateTarget, setTerminateTarget] = useState<{ tenantId: string; schoolName: string } | null>(null)
  const [terminating, setTerminating] = useState(false)

  const { data, loading, error, refresh } = useAsync(
    async () => {
      if (authLoading || !user) return []
      const res = await partnerSchoolApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [authLoading, user?.id], onError: () => true },
  )

  const schools = (data ?? []).map((s) => ({ ...s, id: s.tenantId }))

  const updateStatus = async (tenantId: string, status: PartnerSchoolStatus) => {
    setActingId(tenantId)
    try {
      await partnerSchoolApi.updateStatus(tenantId, status)
      toast({ title: t('合作状态已更新') })
      await refresh()
    } catch (e: any) {
      toast({
        title: t('操作失败'),
        description: e instanceof Error ? e.message : t('未知错误'),
        variant: 'destructive',
      })
    } finally {
      setActingId(null)
    }
  }

  const confirmTerminate = async () => {
    if (!terminateTarget) return
    setTerminating(true)
    try {
      await partnerSchoolApi.updateStatus(terminateTarget.tenantId, 'terminated')
      toast({ title: t('合作已终止') })
      setTerminateTarget(null)
      await refresh()
    } catch (e: any) {
      toast({
        title: t('操作失败'),
        description: e instanceof Error ? e.message : t('未知错误'),
        variant: 'destructive',
      })
    } finally {
      setTerminating(false)
    }
  }

  return (
    <PortalCrudPage
      title={t('合作学校')}
      description={t('已引入本企业的学校列表；企业可确认、暂停或终止合作，合作评级由学校侧维护。')}
      entityLabel={t('合作学校')}
      searchPlaceholder={t('搜索学校名称...')}
      items={schools}
      loading={loading || authLoading}
      error={error?.message ?? null}
      onRetry={refresh}
      filterItems={(items, search) =>
        items.filter(
          (s) => !search || s.schoolName.toLowerCase().includes(search.toLowerCase()),
        )
      }
      hideCreate
      colSpan={6}
      renderTableHeader={() => (
        <>
          <TableHead>{t('学校名称')}</TableHead>
          <TableHead>{t('合作状态')}</TableHead>
          <TableHead>{t('合作评级')}</TableHead>
          <TableHead>{t('学校前台展示')}</TableHead>
          <TableHead>{t('引入时间')}</TableHead>
          <TableHead>{t('操作')}</TableHead>
        </>
      )}
      renderTableRow={(s) => (
        <>
          <TableCell className="font-medium">{s.schoolName}</TableCell>
          <TableCell>{allianceLabel('enterpriseStatus', s.status)}</TableCell>
          <TableCell>{allianceLabel('enterpriseRating', s.rating)}</TableCell>
          <TableCell>{s.isPublic ? t('是') : t('否')}</TableCell>
          <TableCell>{formatDate(s.createdAt)}</TableCell>
          <TableCell>
            <div className="flex items-center gap-2">
              {s.status === 'negotiating' && (
                <Button
                  size="sm"
                  variant="outline"
                  disabled={actingId === s.tenantId}
                  onClick={() => updateStatus(s.tenantId, 'active')}
                >
                  {t('确认合作')}
                </Button>
              )}
              {s.status === 'active' && (
                <Button
                  size="sm"
                  variant="outline"
                  disabled={actingId === s.tenantId}
                  onClick={() => updateStatus(s.tenantId, 'paused')}
                >
                  {t('暂停合作')}
                </Button>
              )}
              {s.status === 'paused' && (
                <Button
                  size="sm"
                  variant="outline"
                  disabled={actingId === s.tenantId}
                  onClick={() => updateStatus(s.tenantId, 'active')}
                >
                  {t('恢复合作')}
                </Button>
              )}
              {s.status !== 'terminated' && (
                <Button
                  size="sm"
                  variant="ghost"
                  className="text-destructive hover:text-destructive"
                  disabled={actingId === s.tenantId}
                  onClick={() => setTerminateTarget({ tenantId: s.tenantId, schoolName: s.schoolName })}
                >
                  {t('终止合作')}
                </Button>
              )}
            </div>
          </TableCell>
        </>
      )}
    >
      <ConfirmDialog
        open={terminateTarget !== null}
        onOpenChange={(open) => {
          if (!open) setTerminateTarget(null)
        }}
        title={t('终止合作')}
        description={
          terminateTarget
            ? t('确定要终止与 {name} 的合作吗？终止后不可恢复。', {
                name: terminateTarget.schoolName,
              })
            : ''
        }
        pending={terminating}
        variant="destructive"
        confirmText={t('终止合作')}
        onConfirm={confirmTerminate}
      />
    </PortalCrudPage>
  )
}

// frontend/portal-vue/src/views/partner/schools.vue
<template>
  <div class="list-page">
    <div class="page-header">
      <h2 class="page-title">合作学校</h2>
      <p class="page-sub">已引入本企业的学校列表；企业可确认、暂停或终止合作，合作评级由学校侧维护。</p>
    </div>

    <el-card shadow="never">
      <el-input v-model="keyword" placeholder="搜索学校名称..." clearable style="max-width: 300px; margin-bottom: 12px" />
      <el-table v-loading="loading" :data="filteredSchools" stripe>
        <el-table-column label="学校名称" prop="schoolName" min-width="160" />
        <el-table-column label="合作状态" width="110">
          <template #default="{ row }">{{ statusLabel(row.status) }}</template>
        </el-table-column>
        <el-table-column label="合作评级" width="100">
          <template #default="{ row }">{{ ratingLabel(row.rating) }}</template>
        </el-table-column>
        <el-table-column label="学校前台展示" width="110">
          <template #default="{ row }">{{ row.isPublic ? '是' : '否' }}</template>
        </el-table-column>
        <el-table-column label="引入时间" width="120">
          <template #default="{ row }">{{ fmt(row.createdAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" align="right">
          <template #default="{ row }">
            <el-button v-if="row.status === 'negotiating'" size="small" :disabled="actingId === row.tenantId" @click="updateStatus(row, 'active')">确认合作</el-button>
            <el-button v-if="row.status === 'active'" size="small" :disabled="actingId === row.tenantId" @click="updateStatus(row, 'paused')">暂停合作</el-button>
            <el-button v-if="row.status === 'paused'" size="small" :disabled="actingId === row.tenantId" @click="updateStatus(row, 'active')">恢复合作</el-button>
            <el-button v-if="row.status !== 'terminated'" size="small" type="danger" :disabled="actingId === row.tenantId" @click="confirmTerminate(row)">终止合作</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="terminateDialog" title="终止合作" width="440px">
      <p>确定要终止与 {{ terminateTarget?.schoolName }} 的合作吗？终止后不可恢复。</p>
      <template #footer>
        <el-button @click="terminateDialog = false">取消</el-button>
        <el-button type="danger" :loading="terminating" @click="doTerminate">终止合作</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { partnerSchoolApi } from '@/api/partner';
import type { PartnerSchool } from '@/types/partner';

const schools = ref<PartnerSchool[]>([]);
const keyword = ref('');
const loading = ref(true);
const actingId = ref<string | null>(null);
const terminating = ref(false);
const terminateDialog = ref(false);
const terminateTarget = ref<PartnerSchool | null>(null);

const filteredSchools = computed(() => {
  const q = keyword.value.trim().toLowerCase();
  if (!q) return schools.value;
  return schools.value.filter((s) => s.schoolName.toLowerCase().includes(q));
});

function statusLabel(s: string) {
  const labels: Record<string, string> = { negotiating: '洽谈中', active: '合作中', paused: '已暂停', terminated: '已终止' };
  return labels[s] || s;
}
function ratingLabel(r?: string) {
  // 合作评级由学校侧维护，取联盟字典 enterpriseRating（战略/深度/一般合作）
  const labels: Record<string, string> = { strategic: '战略合作', deep: '深度合作', general: '一般合作' };
  return r ? labels[r] || r : '-';
}
function fmt(d?: string) {
  return d ? String(d).slice(0, 10) : '-';
}

async function load() {
  loading.value = true;
  try {
    const res = await partnerSchoolApi.list({ limit: 200 });
    schools.value = res.items || [];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

async function updateStatus(row: PartnerSchool, status: 'active' | 'paused' | 'terminated') {
  actingId.value = row.tenantId;
  try {
    await partnerSchoolApi.updateStatus(row.tenantId, status);
    ElMessage.success('合作状态已更新');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    actingId.value = null;
  }
}

function confirmTerminate(row: PartnerSchool) {
  terminateTarget.value = row;
  terminateDialog.value = true;
}
async function doTerminate() {
  if (!terminateTarget.value) return;
  terminating.value = true;
  try {
    await partnerSchoolApi.updateStatus(terminateTarget.value.tenantId, 'terminated');
    ElMessage.success('合作已终止');
    terminateDialog.value = false;
    terminateTarget.value = null;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    terminating.value = false;
  }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.page-header { margin-bottom: 16px; }
.page-title { font-size: 20px; font-weight: 700; margin: 0; }
.page-sub { color: #909399; margin: 8px 0 0; }
</style>
