// frontend/portal-vue/src/views/ai/components/SourceList.vue
<template>
  <div v-if="sources && sources.length" class="source-list">
    <el-button text size="small" class="source-toggle" @click="open = !open">
      <el-icon><component :is="open ? ArrowDown : ArrowRight" /></el-icon>
      参考来源（{{ sources.length }}）
    </el-button>
    <ul v-if="open" class="source-items">
      <li v-for="(s, i) in sources" :key="`${s.docId}-${s.seq}-${i}`" class="source-item">
        <div class="source-head">
          <el-icon class="file-icon"><Document /></el-icon>
          <span class="source-name">{{ s.docName }}</span>
          <span class="source-seq">第 {{ s.seq }} 段</span>
        </div>
        <p class="source-snippet">{{ s.snippet }}</p>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ArrowDown, ArrowRight, Document } from '@element-plus/icons-vue';
import type { AIMessageSource } from '../ai-api';

defineProps<{ sources: AIMessageSource[] }>();
const open = ref(false);
</script>

<style scoped>
.source-list {
  margin-top: 8px;
  border-top: 1px solid #f0f0f0;
  padding-top: 8px;
}
.source-toggle {
  color: #909399;
  font-size: 12px;
  padding: 0;
}
.source-items {
  list-style: none;
  margin: 8px 0 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.source-item {
  border: 1px solid #f0f0f0;
  background: #fafafa;
  border-radius: 6px;
  padding: 8px 10px;
  font-size: 12px;
}
.source-head {
  display: flex;
  align-items: center;
  gap: 6px;
  font-weight: 500;
  color: #303133;
}
.file-icon {
  color: #909399;
}
.source-name {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.source-seq {
  color: #909399;
  flex-shrink: 0;
}
.source-snippet {
  margin: 6px 0 0;
  color: #909399;
  white-space: pre-wrap;
  word-break: break-word;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// apps/edu/app/portal/apps/ai/_components/source-list.tsx
'use client'

// 引用溯源展示（spec §5.5 sources 事件 / 历史消息 message.sources）：
// 折叠「参考来源（N）」区，展开后列出 docName + 第{seq}段 + snippet。
import { useState } from 'react'
import { ChevronDown, ChevronRight, FileText } from 'lucide-react'
import type { AIMessageSource } from '@/lib/api'
import { useT } from '@/lib/i18n/locale-provider'

export function AISourceList({ sources }: { sources: AIMessageSource[] }) {
  const t = useT()
  const [open, setOpen] = useState(false)
  if (!sources || sources.length === 0) return null
  return (
    <div className="mt-2 border-t border-gray-100 pt-2">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
      >
        {open ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
        {t('参考来源（{count}）', { count: sources.length })}
      </button>
      {open && (
        <ul className="mt-2 space-y-2">
          {sources.map((s, i) => (
            <li
              key={`${s.docId}-${s.seq}-${i}`}
              className="rounded-md bg-background/60 border border-gray-100 px-3 py-2 text-xs"
            >
              <div className="flex items-center gap-1.5 font-medium text-foreground">
                <FileText className="h-3 w-3 shrink-0 text-muted-foreground" />
                <span className="truncate">{s.docName}</span>
                <span className="text-muted-foreground shrink-0">
                  {t('第 {seq} 段', { seq: s.seq })}
                </span>
              </div>
              <p className="mt-1 text-muted-foreground whitespace-pre-wrap break-words line-clamp-3">
                {s.snippet}
              </p>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
