// frontend/portal-vue/src/views/scene/evaluation-rules/BankQuestionSelectorPanel.vue
<template>
  <div class="bank-panel">
    <!-- 左：题库列表 / 题库内题目 -->
    <div class="panel-left">
      <template v-if="selectedBankId">
        <div class="back-row">
          <el-button link size="small" @click="handleBackToBanks">
            <el-icon><ArrowLeft /></el-icon> 返回题库列表
          </el-button>
          <span class="bank-name">{{ selectedBankName }}</span>
        </div>
        <el-input v-model="questionSearch" size="small" placeholder="搜索题目内容..." clearable class="search">
          <template #prefix><el-icon><Search /></el-icon></template>
        </el-input>
        <div class="scroll-area">
          <div v-if="loadingQuestions" class="loading">加载中...</div>
          <el-empty
            v-else-if="filteredQuestions.length === 0"
            :description="bankQuestions.length === 0 ? '该题库暂无题目' : '没有找到匹配的题目'"
            :image-size="60"
          />
          <el-table v-else :data="filteredQuestions" size="small" @row-click="(row: any) => emit('toggle-question', row.id)">
            <el-table-column label="题目内容" min-width="200">
              <template #default="{ row }">
                <div class="q-content">
                  <span class="check-box" :class="{ on: isSelected(row.id) }">
                    <el-icon v-if="isSelected(row.id)" :size="11"><Check /></el-icon>
                  </span>
                  <span class="q-text">{{ questionContent(row) }}</span>
                </div>
              </template>
            </el-table-column>
            <el-table-column label="题型" width="92">
              <template #default="{ row }">
                <el-tag size="small" disable-transitions :color="typeColor(row.type)" style="color: #fff; border: none">
                  {{ typeLabel(row.type) }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column label="难度" width="70">
              <template #default="{ row }">
                <span class="dim">{{ difficultyLabel(row.difficulty) }}</span>
              </template>
            </el-table-column>
            <el-table-column label="操作" width="90" align="right">
              <template #default="{ row }">
                <el-button
                  size="small"
                  :type="isSelected(row.id) ? 'default' : 'primary'"
                  :plain="isSelected(row.id)"
                  @click.stop="emit('toggle-question', row.id)"
                >
                  {{ isSelected(row.id) ? '取消' : '使用' }}
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </template>
      <template v-else>
        <el-radio-group v-model="bankTab" size="small" class="bank-tabs">
          <el-radio-button value="my">我的</el-radio-button>
          <el-radio-button value="collab">共建</el-radio-button>
          <el-radio-button value="public">公共题库</el-radio-button>
        </el-radio-group>
        <el-input v-model="bankSearch" size="small" placeholder="搜索题库名称..." clearable class="search">
          <template #prefix><el-icon><Search /></el-icon></template>
        </el-input>
        <div class="scroll-area">
          <div v-if="loadingBanks" class="loading">加载中...</div>
          <el-empty v-else-if="filteredBanks.length === 0" description="暂无题库" :image-size="60" />
          <div v-else class="bank-list">
            <div
              v-for="bank in filteredBanks"
              :key="bank.id"
              class="bank-card"
              @click="handleSelectBank(bank.id, bank.name)"
            >
              <div class="bank-row">
                <el-icon color="#909399"><Collection /></el-icon>
                <span class="bank-label">{{ bank.name }}</span>
                <el-tag size="small" type="info" disable-transitions>{{ bank.questionCount ?? 0 }} 题</el-tag>
                <el-icon class="arrow" color="#c0c4cc"><ArrowRight /></el-icon>
              </div>
              <p v-if="bank.description" class="bank-desc">{{ bank.description }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- 右：已选题目 -->
    <div class="panel-right">
      <div class="right-head">
        <p class="right-title">已选择题目 ({{ selectedIds.length }}<span v-if="maxCount">/{{ maxCount }}</span>)</p>
        <el-dropdown v-if="selectedIds.length > 0" trigger="click" @command="onScoreCommand">
          <el-button size="small" plain>
            <el-icon><Operation /></el-icon> 分数配置
          </el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item command="even">均匀分配 — 将 100 分均匀分给每道题，余数从第一题起加 1 分</el-dropdown-item>
              <el-dropdown-item command="byType">题型分配 — 为每种题型分配总分（合计 100），各题型内均匀分配</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </div>
      <div class="scroll-area">
        <el-empty v-if="selectedIds.length === 0" description="从左侧搜索并选择题目" :image-size="60" />
        <div v-else class="selected-list">
          <div v-for="qid in selectedIds" :key="qid" class="selected-card">
            <div class="selected-head">
              <span class="selected-text">{{ questionContent(resolveQuestion(qid)) }}</span>
              <el-button link size="small" @click="emit('toggle-question', qid)">
                <el-icon><Close /></el-icon>
              </el-button>
            </div>
            <div class="selected-meta">
              <el-tag
                size="small"
                disable-transitions
                :color="typeColor(resolveQuestion(qid)?.type)"
                style="color: #fff; border: none"
              >
                {{ typeLabel(resolveQuestion(qid)?.type) }}
              </el-tag>
              <span class="dim">{{ difficultyLabel(resolveQuestion(qid)?.difficulty) }}</span>
              <div class="score-box">
                <span class="dim">分值</span>
                <el-input-number
                  :model-value="questionScores?.[qid] ?? resolveQuestion(qid)?.score ?? 0"
                  :min="0"
                  :max="100"
                  :precision="0"
                  size="small"
                  controls-position="right"
                  class="score-input"
                  @update:model-value="(v: number | undefined) => emit('update-scores', { [qid]: Math.max(0, Math.min(100, v || 0)) })"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <ScoreConfigDialog
      v-model="scoreDialogOpen"
      :questions="selectedQuestionItems"
      @apply="(scores) => emit('update-scores', scores)"
    />
  </div>
</template>

<script setup lang="ts">
/**
 * 题库选题面板：对齐原 React 版 bank-question-selector-panel.tsx
 * 题库 Tab（我的/共建/公共题库）→ 题库搜索 → 进入题库选题 → 右侧已选题目与分值配置（均匀/题型分配）。
 */
import { computed, onMounted, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { ArrowLeft, ArrowRight, Check, Close, Collection, Operation, Search } from '@element-plus/icons-vue';
import { questionApi, questionBankApi } from '@/api/evaluation';
import { fetchAllPages } from '@/views/lesson/lesson-edit-utils';
import ScoreConfigDialog from './ScoreConfigDialog.vue';
import { DIFFICULTY_LABELS, QUESTION_TYPE_COLORS, QUESTION_TYPE_LABELS } from './types';

const props = defineProps<{
  field: 'questionBankQuestions' | 'quizQuestions';
  selectedIds: string[];
  maxCount?: number;
  questionScores?: Record<string, number>;
}>();

const emit = defineEmits<{
  (e: 'toggle-question', qid: string): void;
  (e: 'update-scores', scores: Record<string, number>): void;
}>();

const banks = ref<any[]>([]);
const bankQuestions = ref<any[]>([]);
const questionCache = ref<Record<string, any>>({});
const selectedBankId = ref<string | null>(null);
const selectedBankName = ref('');
const loadingBanks = ref(false);
const loadingQuestions = ref(false);
const bankTab = ref<'my' | 'collab' | 'public'>('my');
const bankSearch = ref('');
const questionSearch = ref('');
const scoreDialogOpen = ref(false);
// 题库切换请求序号：丢弃过期响应，避免旧题库题目覆盖新题库
let loadSeq = 0;

async function loadBanks() {
  loadingBanks.value = true;
  try {
    banks.value = await fetchAllPages<any>(({ limit, offset }) => questionBankApi.list({ limit, offset }));
  } catch (err) {
    ElMessage.error((err as Error).message || '加载题库列表失败');
  } finally {
    loadingBanks.value = false;
  }
}

async function loadQuestions(bankId: string) {
  const seq = ++loadSeq;
  loadingQuestions.value = true;
  try {
    const res = await questionApi.list({ bankId, limit: 1000 });
    if (seq !== loadSeq) return;
    const items = (res.items || []) as any[];
    items.forEach((q) => (questionCache.value[q.id] = q));
    bankQuestions.value = items;
  } catch (err) {
    if (seq !== loadSeq) return;
    ElMessage.error((err as Error).message || '加载题库题目失败');
  } finally {
    if (seq === loadSeq) loadingQuestions.value = false;
  }
}

/** 已选但未在当前题库列表中的题目：逐个补拉详情，保证右侧展示题干/题型/分值 */
async function preloadSelected() {
  const missing = props.selectedIds.filter((qid) => !questionCache.value[qid]);
  if (missing.length === 0) return;
  await Promise.all(
    missing.map(async (qid) => {
      try {
        const q = await questionApi.get(qid);
        questionCache.value[qid] = q;
      } catch {
        // 单题详情失败不阻塞其他题目
      }
    })
  );
}

onMounted(() => {
  loadBanks();
  preloadSelected();
});

watch(() => props.selectedIds.join(','), () => void preloadSelected());

function handleSelectBank(bankId: string, bankName: string) {
  selectedBankId.value = bankId;
  selectedBankName.value = bankName;
  questionSearch.value = '';
  loadQuestions(bankId);
}

function handleBackToBanks() {
  selectedBankId.value = null;
  selectedBankName.value = '';
  bankQuestions.value = [];
  questionSearch.value = '';
}

const tabBanks = computed(() => {
  switch (bankTab.value) {
    case 'my':
      return banks.value.filter((b) => b.ownerType === 'mine' || !b.ownerType);
    case 'collab':
      return banks.value.filter((b) => (b.collaboratorIds || []).length > 0);
    default:
      return banks.value.filter((b) => b.status === 'published');
  }
});

const filteredBanks = computed(() => {
  const q = bankSearch.value.trim().toLowerCase();
  if (!q) return tabBanks.value;
  return tabBanks.value.filter(
    (b) => (b.name || '').toLowerCase().includes(q) || (b.description || '').toLowerCase().includes(q)
  );
});

const filteredQuestions = computed(() => {
  const q = questionSearch.value.trim().toLowerCase();
  if (!q) return bankQuestions.value;
  return bankQuestions.value.filter(
    (qu) => (qu.content || '').toLowerCase().includes(q) || (qu.name || '').toLowerCase().includes(q)
  );
});

function isSelected(qid: string): boolean {
  return props.selectedIds.includes(qid);
}

function resolveQuestion(qid: string): any | undefined {
  return bankQuestions.value.find((q) => q.id === qid) || questionCache.value[qid];
}

function questionContent(q: any): string {
  const raw = q?.content || q?.name || '未命名题目';
  const stripped = String(raw).replace(/<[^>]+>/g, '');
  return stripped.length > 60 ? `${stripped.slice(0, 60)}...` : stripped;
}

function typeLabel(type?: string): string {
  return type ? QUESTION_TYPE_LABELS[type] || type : '-';
}

function typeColor(type?: string): string {
  return (type && QUESTION_TYPE_COLORS[type]) || '#909399';
}

function difficultyLabel(d?: string): string {
  return d ? DIFFICULTY_LABELS[d] || d : '-';
}

const selectedQuestionItems = computed(() =>
  props.selectedIds.map((qid) => ({ questionId: qid, type: resolveQuestion(qid)?.type || 'single' }))
);

function onScoreCommand(cmd: string) {
  if (cmd === 'even') {
    handleEvenDistribution();
    return;
  }
  scoreDialogOpen.value = true;
}

function handleEvenDistribution() {
  const n = props.selectedIds.length;
  if (n === 0) return;
  const base = Math.floor(100 / n);
  const remainder = 100 - base * n;
  const scores: Record<string, number> = {};
  props.selectedIds.forEach((qid, idx) => {
    scores[qid] = base + (idx < remainder ? 1 : 0);
  });
  emit('update-scores', scores);
}
</script>

<style scoped>
.bank-panel {
  display: flex;
  gap: 16px;
  min-height: 0;
}
.panel-left {
  width: 60%;
  display: flex;
  flex-direction: column;
  border: 1px solid #ebeef5;
  border-radius: 10px;
  padding: 12px;
  min-width: 0;
}
.panel-right {
  width: 40%;
  display: flex;
  flex-direction: column;
  border: 1px solid #ebeef5;
  border-radius: 10px;
  padding: 12px;
  min-width: 0;
}
.back-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 10px;
}
.bank-name {
  font-size: 13px;
  font-weight: 500;
  color: #303133;
}
.bank-tabs,
.search {
  margin-bottom: 10px;
}
.scroll-area {
  flex: 1;
  min-height: 220px;
  max-height: 420px;
  overflow-y: auto;
}
.loading {
  text-align: center;
  color: #a8abb2;
  font-size: 13px;
  padding: 24px 0;
}
.bank-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.bank-card {
  border: 1px solid #ebeef5;
  border-radius: 8px;
  padding: 10px 12px;
  cursor: pointer;
  transition: all 0.2s;
}
.bank-card:hover {
  border-color: #a0cfff;
  background: #f7fbff;
}
.bank-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
.bank-label {
  font-size: 13px;
  font-weight: 500;
}
.arrow {
  margin-left: auto;
}
.bank-desc {
  margin: 6px 0 0;
  font-size: 12px;
  color: #a8abb2;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.q-content {
  display: flex;
  align-items: center;
  gap: 8px;
}
.check-box {
  width: 16px;
  height: 16px;
  border: 1px solid #dcdfe6;
  border-radius: 3px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  color: #fff;
}
.check-box.on {
  background: #409eff;
  border-color: #409eff;
}
.q-text {
  font-size: 13px;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.right-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
  gap: 8px;
}
.right-title {
  margin: 0;
  font-size: 13px;
  font-weight: 500;
  color: #606266;
}
.selected-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.selected-card {
  border: 1px solid #d9ecff;
  background: #f7fbff;
  border-radius: 8px;
  padding: 8px 10px;
}
.selected-head {
  display: flex;
  align-items: center;
  gap: 6px;
}
.selected-text {
  flex: 1;
  font-size: 12px;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.selected-meta {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 4px;
}
.dim {
  font-size: 11px;
  color: #a8abb2;
}
.score-box {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-left: auto;
}
.score-input {
  width: 92px;
}
</style>

// apps/edu/components/evaluation-rules/bank-question-selector-panel.tsx
'use client'

import { useState, useMemo, useEffect, useCallback } from 'react'
import {
  ChevronLeft,
  Search,
  FileQuestion,
  Loader2,
  Check,
  X,
  Database,
  ChevronRight,
  SlidersHorizontal,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { cn } from '@/lib/utils'
import { useT } from '@/lib/i18n/locale-provider'
import { ScoreConfigDialog } from '@/components/evaluation/score-config-dialog'
import { questionBankApi, questionApi } from '@/lib/api'
import { reportError } from '@/lib/error-handling'
import type { QuestionType } from '@/lib/types'
import {
  getAllQuestions,
  getCachedQuestion,
  hasCachedQuestion,
  setCachedQuestion,
  setCachedQuestions,
  typeColorMap,
  questionTypeLabels,
  difficultyLabels,
  type CachedQuestion,
} from './shared-defs'

interface BankQuestionSelectorPanelProps {
  field: 'questionBankQuestions' | 'quizQuestions'
  selectedIds: string[]
  maxCount?: number
  onToggleQuestion: (qid: string) => void
  questionScores?: Record<string, number>
  onUpdateQuestionScore?: (qid: string, score: number) => void
  onUpdateQuestionScores?: (scores: Record<string, number>) => void
}

export function BankQuestionSelectorPanel({
  field,
  selectedIds,
  maxCount,
  onToggleQuestion,
  questionScores,
  onUpdateQuestionScore,
  onUpdateQuestionScores,
}: BankQuestionSelectorPanelProps) {
  const t = useT()
  const [banks, setBanks] = useState<any[]>([])
  const [bankQuestions, setBankQuestions] = useState<any[]>([])
  const [selectedBankId, setSelectedBankId] = useState<string | null>(null)
  const [selectedBankName, setSelectedBankName] = useState('')
  const [loadingBanks, setLoadingBanks] = useState(false)
  const [loadingQuestions, setLoadingQuestions] = useState(false)
  const [bankTab, setBankTab] = useState<'my' | 'collab' | 'public'>('my')
  const [bankSearch, setBankSearch] = useState('')
  const [questionSearch, setQuestionSearch] = useState('')
  const [scoreDialogOpen, setScoreDialogOpen] = useState(false)
  const [preloadedQuestions, setPreloadedQuestions] = useState<any[]>([])

  const loadBanks = useCallback(async () => {
    setLoadingBanks(true)
    try {
      const res = (await questionBankApi.list({ limit: 1000 })) as unknown as { items: any[] }
      setBanks(res.items)
    } catch (err) {
      reportError(err, { source: '加载题库列表' })
    } finally {
      setLoadingBanks(false)
    }
  }, [])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      if (!cancelled) await loadBanks()
    })()
    return () => {
      cancelled = true
    }
  }, [loadBanks])

  useEffect(() => {
    const missingIds = selectedIds.filter(
      (qid) => !hasCachedQuestion(qid) && !preloadedQuestions.some((q) => q.id === qid),
    )
    if (missingIds.length === 0) return
    Promise.all(
      missingIds.map(async (qid) => {
        try {
          return (await questionApi.get(qid)) as unknown as any
        } catch (err) {
          reportError(err, { source: '预加载题目详情', extras: { questionId: qid } })
          return null
        }
      }),
    ).then((results) => {
      const loaded = results.filter(Boolean)
      loaded.forEach((q) => setCachedQuestion(q as CachedQuestion))
      setPreloadedQuestions((prev) => [...prev, ...loaded])
    })
  }, [selectedIds, preloadedQuestions])

  const loadQuestions = useCallback(async (bankId: string) => {
    setLoadingQuestions(true)
    try {
      const res = (await questionApi.list({ bankId, limit: 1000 })) as unknown as {
        items: CachedQuestion[]
      }
      setCachedQuestions(res.items)
      setBankQuestions(res.items)
    } catch (err) {
      reportError(err, { source: '加载题库题目', extras: { bankId } })
    } finally {
      setLoadingQuestions(false)
    }
  }, [])

  const handleSelectBank = (bankId: string, bankName: string) => {
    setSelectedBankId(bankId)
    setSelectedBankName(bankName)
    loadQuestions(bankId)
  }

  const handleBackToBanks = () => {
    setSelectedBankId(null)
    setSelectedBankName('')
    setBankQuestions([])
    setQuestionSearch('')
  }

  const tabBanks = useMemo(() => {
    switch (bankTab) {
      case 'my':
        return banks.filter((b: any) => b.ownerType === 'mine' || !b.ownerType)
      case 'collab':
        return banks.filter((b: any) => (b.collaboratorIds || []).length > 0)
      case 'public':
        return banks.filter((b: any) => b.status === 'published')
    }
  }, [banks, bankTab])

  const filteredBanks = useMemo(() => {
    const q = bankSearch.trim().toLowerCase()
    if (!q) return tabBanks
    return tabBanks.filter(
      (b: any) =>
        b.name.toLowerCase().includes(q) || (b.description || '').toLowerCase().includes(q),
    )
  }, [tabBanks, bankSearch])

  const filteredQuestions = useMemo(() => {
    const q = questionSearch.trim().toLowerCase()
    if (!q) return bankQuestions
    return bankQuestions.filter(
      (qu: any) =>
        (qu.content || '').toLowerCase().includes(q) || (qu.name || '').toLowerCase().includes(q),
    )
  }, [bankQuestions, questionSearch])

  const handleEvenDistribution = () => {
    if (selectedIds.length === 0) return
    const n = selectedIds.length
    const base = Math.floor(100 / n)
    const remainder = 100 - base * n
    const scores: Record<string, number> = {}
    selectedIds.forEach((qid, idx) => {
      scores[qid] = base + (idx < remainder ? 1 : 0)
    })
    if (onUpdateQuestionScores) {
      onUpdateQuestionScores(scores)
    } else if (onUpdateQuestionScore) {
      selectedIds.forEach((qid) => {
        onUpdateQuestionScore(qid, scores[qid])
      })
    }
  }

  const handleTypeDistribution = (scores: Record<string, number>) => {
    if (onUpdateQuestionScores) {
      onUpdateQuestionScores(scores)
    } else if (onUpdateQuestionScore) {
      Object.entries(scores).forEach(([qid, score]) => {
        onUpdateQuestionScore(qid, score)
      })
    }
  }

  const resolveQuestion = useCallback(
    (qid: string): CachedQuestion | undefined => {
      return (
        bankQuestions.find((bq: any) => bq.id === qid) ||
        preloadedQuestions.find((q: any) => q.id === qid) ||
        getCachedQuestion(qid) ||
        getAllQuestions().find((aq) => aq.id === qid)
      )
    },
    [bankQuestions, preloadedQuestions],
  )

  const selectedQuestionItems = useMemo(() => {
    return selectedIds.map((qid) => {
      const q = resolveQuestion(qid)
      return {
        id: qid,
        questionId: qid,
        type: (q?.type ?? 'single') as QuestionType,
        content: q?.content ?? '',
        answer: '',
        score: questionScores?.[qid] ?? q?.score ?? 0,
        order: 0,
      }
    })
  }, [selectedIds, questionScores, resolveQuestion])

  return (
    <>
      <div className="flex flex-col lg:flex-row gap-4 flex-1 min-h-0">
        <div className="w-full lg:w-3/5 flex flex-col min-h-0 min-w-0 border rounded-xl p-3 overflow-hidden">
          {selectedBankId ? (
            <>
              <div className="flex items-center gap-2 mb-3">
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 text-xs"
                  onClick={handleBackToBanks}
                >
                  <ChevronLeft className="h-3.5 w-3.5 mr-0.5" />
                  {t('返回题库列表')}
                </Button>
                <span className="text-sm font-medium text-gray-700">{selectedBankName}</span>
              </div>
              <div className="relative mb-3">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  value={questionSearch}
                  onChange={(e) => setQuestionSearch(e.target.value)}
                  placeholder={t('搜索题目内容...')}
                  className="pl-9"
                />
              </div>
              <div className="flex-1 overflow-y-auto">
                {loadingQuestions ? (
                  <div className="text-center text-gray-400 py-8">
                    <Loader2 className="h-6 w-6 mx-auto animate-spin" />
                    <p className="text-sm mt-2">{t('加载中...')}</p>
                  </div>
                ) : filteredQuestions.length === 0 ? (
                  <div className="text-center text-gray-400 py-8">
                    <FileQuestion className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">
                      {bankQuestions.length === 0 ? t('该题库暂无题目') : t('没有找到匹配的题目')}
                    </p>
                  </div>
                ) : (
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm table-fixed">
                      <thead className="bg-gray-50 sticky top-0 z-10">
                        <tr>
                          <th className="text-left text-xs font-medium text-gray-500 px-3 py-2">
                            {t('题目内容')}
                          </th>
                          <th className="text-left text-xs font-medium text-gray-500 px-3 py-2 w-[88px]">
                            {t('题型')}
                          </th>
                          <th className="text-left text-xs font-medium text-gray-500 px-3 py-2 w-[56px]">
                            {t('难度')}
                          </th>
                          <th className="text-right text-xs font-medium text-gray-500 px-3 py-2 w-[120px]">
                            {t('操作')}
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {filteredQuestions.map((q: any) => {
                          const isSelected = selectedIds.includes(q.id)
                          return (
                            <tr
                              key={q.id}
                              className={cn(
                                'hover:bg-gray-50 transition-colors cursor-pointer',
                                isSelected ? 'bg-primary/[0.03]' : '',
                              )}
                              onClick={() => onToggleQuestion(q.id)}
                            >
                              <td className="px-3 py-2">
                                <div className="flex items-center gap-2">
                                  <div
                                    className={cn(
                                      'w-4 h-4 rounded border flex items-center justify-center shrink-0',
                                      isSelected ? 'bg-primary border-primary' : 'border-gray-300',
                                    )}
                                  >
                                    {isSelected && <Check className="h-3 w-3 text-white" />}
                                  </div>
                                  <span className="text-sm text-gray-800 line-clamp-1">
                                    {q.content || q.name || t('未命名题目')}
                                  </span>
                                </div>
                              </td>
                              <td className="px-3 py-2">
                                <Badge
                                  className={`text-xs text-white hover:opacity-90 whitespace-nowrap ${typeColorMap[q.type ?? ''] || ''}`}
                                >
                                  {t(questionTypeLabels[q.type ?? ''] || (q.type ?? ''))}
                                </Badge>
                              </td>
                              <td className="px-3 py-2">
                                <span className="text-xs text-gray-500 whitespace-nowrap">
                                  {t(difficultyLabels[q.difficulty ?? ''] || (q.difficulty ?? ''))}
                                </span>
                              </td>
                              <td className="px-3 py-2">
                                <div className="flex items-center justify-end gap-1">
                                  {isSelected ? (
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      className="h-6 text-[11px] px-2"
                                      onClick={(e) => {
                                        e.stopPropagation()
                                        onToggleQuestion(q.id)
                                      }}
                                    >
                                      {t('取消')}
                                    </Button>
                                  ) : (
                                    <Button
                                      size="sm"
                                      className="h-6 text-[11px] px-2"
                                      onClick={(e) => {
                                        e.stopPropagation()
                                        onToggleQuestion(q.id)
                                      }}
                                    >
                                      {t('使用')}
                                    </Button>
                                  )}
                                </div>
                              </td>
                            </tr>
                          )
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </>
          ) : (
            <>
              <Tabs
                value={bankTab}
                onValueChange={(v) => setBankTab(v as 'my' | 'collab' | 'public')}
                className="mb-3"
              >
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="my">{t('我的')}</TabsTrigger>
                  <TabsTrigger value="collab">{t('共建')}</TabsTrigger>
                  <TabsTrigger value="public">{t('公共题库')}</TabsTrigger>
                </TabsList>
              </Tabs>
              <div className="relative mb-3">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  value={bankSearch}
                  onChange={(e) => setBankSearch(e.target.value)}
                  placeholder={t('搜索题库名称...')}
                  className="pl-9"
                />
              </div>
              <div className="flex-1 overflow-y-auto">
                {loadingBanks ? (
                  <div className="text-center text-gray-400 py-8">
                    <Loader2 className="h-6 w-6 mx-auto animate-spin" />
                    <p className="text-sm mt-2">{t('加载中...')}</p>
                  </div>
                ) : filteredBanks.length === 0 ? (
                  <div className="text-center text-gray-400 py-8">
                    <Database className="h-8 w-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">{t('暂无题库')}</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    {filteredBanks.map((bank: any) => (
                      <div
                        key={bank.id}
                        onClick={() => handleSelectBank(bank.id, bank.name)}
                        className="p-3 rounded-lg border cursor-pointer hover:border-primary/50 hover:bg-primary/[0.02] transition-all"
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Database className="h-4 w-4 text-gray-400" />
                            <span className="text-sm font-medium">{bank.name}</span>
                            <Badge variant="outline" className="text-[10px]">
                              {t('{n} 题', { n: bank.questionCount ?? 0 })}
                            </Badge>
                          </div>
                          <ChevronRight className="h-4 w-4 text-gray-400" />
                        </div>
                        {bank.description && (
                          <p className="text-xs text-gray-400 mt-1.5 line-clamp-1">
                            {bank.description}
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </>
          )}
        </div>
        <div className="w-full lg:w-2/5 border rounded-xl p-3 flex flex-col min-h-0 min-w-0 overflow-hidden">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm font-medium text-gray-700">
              {t('已选择题目')} ({selectedIds.length}
              {maxCount ? `/${maxCount}` : ''})
            </p>
            {(field === 'questionBankQuestions' || field === 'quizQuestions') &&
              selectedIds.length > 0 &&
              onUpdateQuestionScore && (
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="outline" size="sm" className="h-7 text-[11px] px-2">
                      <SlidersHorizontal className="h-3 w-3 mr-1" />
                      {t('分数配置')}
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-64">
                    <DropdownMenuItem onClick={handleEvenDistribution}>
                      {t('均匀分配 — 将 100 分均匀分给每道题，余数从第一题起加 1 分')}
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => setScoreDialogOpen(true)}>
                      {t('题型分配 — 为每种题型分配总分（合计 100），各题型内均匀分配')}
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              )}
          </div>
          <div className="flex-1 overflow-y-auto">
            {selectedIds.length === 0 ? (
              <div className="text-center text-gray-400 py-8">
                <FileQuestion className="h-8 w-8 mx-auto mb-2 opacity-50" />
                <p className="text-xs">{t('从左侧搜索并选择题目')}</p>
              </div>
            ) : (
              <div className="space-y-2">
                {selectedIds.map((qid) => {
                  const q = resolveQuestion(qid)
                  if (!q) return null
                  return (
                    <div
                      key={qid}
                      className="p-2.5 rounded-lg border border-primary/20 bg-primary/5 relative"
                    >
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-medium flex-1 truncate">
                          {q.content || q.name || t('未命名题目')}
                        </span>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-5 w-5 text-gray-400 -mr-1 -mt-1"
                          onClick={() => onToggleQuestion(qid)}
                        >
                          <X className="h-3 w-3" />
                        </Button>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <Badge
                          className={`text-[10px] text-white hover:opacity-90 ${typeColorMap[q.type ?? ''] || ''}`}
                        >
                          {t(questionTypeLabels[q.type ?? ''] || (q.type ?? ''))}
                        </Badge>
                        <span className="text-[10px] text-gray-400">
                          {t(difficultyLabels[q.difficulty ?? ''] || (q.difficulty ?? ''))}
                        </span>
                        {(field === 'questionBankQuestions' || field === 'quizQuestions') &&
                        onUpdateQuestionScore ? (
                          <div className="flex items-center gap-1 ml-auto">
                            <span className="text-[10px] text-gray-400">{t('分值')}</span>
                            <Input
                              type="number"
                              value={questionScores?.[qid] ?? q.score ?? 0}
                              onChange={(e) => {
                                const val = Math.max(
                                  0,
                                  Math.min(100, parseInt(e.target.value) || 0),
                                )
                                onUpdateQuestionScore(qid, val)
                              }}
                              className="w-14 h-5 text-[10px] px-1 py-0"
                              min={0}
                              max={100}
                            />
                          </div>
                        ) : (
                          <span className="text-[10px] text-gray-400">{t('{n}分', { n: q.score ?? 0 })}</span>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      </div>
      {(field === 'questionBankQuestions' || field === 'quizQuestions') &&
        onUpdateQuestionScore && (
          <ScoreConfigDialog
            open={scoreDialogOpen}
            onOpenChange={setScoreDialogOpen}
            questions={selectedQuestionItems}
            onApply={handleTypeDistribution}
          />
        )}
    </>
  )
}
