// frontend/portal-vue/src/views/scene/evaluation-rules/ExamActivationConfig.vue
<template>
  <div class="activation-config">
    <p class="label">启用条件</p>
    <div class="mode-grid">
      <button
        v-for="m in modes"
        :key="m.key"
        type="button"
        class="mode-card"
        :class="{ active: mode === m.key }"
        @click="emit('change', { activationMode: m.key })"
      >
        <div class="mode-head">
          <span class="radio" :class="{ on: mode === m.key }"><i v-if="mode === m.key" /></span>
          <span class="mode-label">{{ m.label }}</span>
        </div>
        <p class="mode-desc">{{ m.desc }}</p>
      </button>
    </div>
    <div v-if="mode === 'scheduled'" class="schedule-row">
      <div class="field">
        <p class="sub-label">启用时间</p>
        <el-date-picker
          :model-value="value.scheduledTime || ''"
          type="datetime"
          value-format="YYYY-MM-DDTHH:mm"
          format="YYYY-MM-DD HH:mm"
          placeholder="选择启用时间"
          style="width: 100%"
          @update:model-value="(v: string) => emit('change', { scheduledTime: v || '' })"
        />
      </div>
      <div class="field">
        <p class="sub-label">停用时间</p>
        <el-date-picker
          :model-value="value.scheduledEndTime || ''"
          type="datetime"
          value-format="YYYY-MM-DDTHH:mm"
          format="YYYY-MM-DD HH:mm"
          placeholder="选择停用时间"
          style="width: 100%"
          @update:model-value="(v: string) => emit('change', { scheduledEndTime: v || '' })"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// 测评启用条件：手动启用 / 定时启用（起止时间）/ 随时作答
// 对齐 React frontend/edu/components/evaluation-rules/exam-activation-config.tsx
import { computed } from 'vue';
import type { ExamActivationValue } from './types';

const props = defineProps<{ value: ExamActivationValue }>();
const emit = defineEmits<{ (e: 'change', updates: Partial<ExamActivationValue>): void }>();

const mode = computed(() => props.value.activationMode ?? 'manual');

const modes = [
  { key: 'manual', label: '手动启用', desc: '老师手动开启后学生可作答' },
  { key: 'scheduled', label: '定时启用', desc: '预设开始结束时间，到时间自动开启关闭' },
  { key: 'always', label: '随时作答', desc: '创建后立即开放，学生随时可进入作答' }
];
</script>

<style scoped>
.activation-config {
  margin-top: 16px;
  padding-top: 16px;
  border-top: 1px solid #ebeef5;
}
.label {
  margin: 0 0 8px;
  font-size: 12px;
  color: #909399;
}
.sub-label {
  margin: 0 0 4px;
  font-size: 12px;
  color: #909399;
}
.mode-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 12px;
}
.mode-card {
  text-align: left;
  padding: 12px;
  border: 1px solid #dcdfe6;
  border-radius: 8px;
  background: #fff;
  cursor: pointer;
  font: inherit;
  color: #606266;
  transition: all 0.2s;
}
.mode-card:hover {
  border-color: #c0c4cc;
}
.mode-card.active {
  border-color: #409eff;
  background: #f7fbff;
  color: #409eff;
}
.mode-head {
  display: flex;
  align-items: center;
  gap: 8px;
}
.radio {
  width: 15px;
  height: 15px;
  border: 1px solid #dcdfe6;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.radio.on {
  border-color: #409eff;
  background: #409eff;
}
.radio.on i {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #fff;
}
.mode-label {
  font-size: 12px;
  font-weight: 500;
}
.mode-desc {
  margin: 4px 0 0 23px;
  font-size: 11px;
  color: #a8abb2;
}
.schedule-row {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  margin-top: 12px;
}
</style>

// apps/edu/components/evaluation-rules/exam-activation-config.tsx
'use client'

import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { FormFieldRow } from '@/components/shared/form-field-row'
import { cn } from '@/lib/utils'

export interface ExamActivationValue {
  activationMode?: string
  scheduledTime?: string
  scheduledEndTime?: string
}

interface ExamActivationConfigProps {
  value: ExamActivationValue
  onChange: (updates: Partial<ExamActivationValue>) => void
}

/**
 * 测评启用条件公共配置：手动启用 / 定时启用（起止时间）/ 随时作答。
 * 场景任务与课程节点的试卷/题库/随堂测测评方式共用，生成考试安排时按此配置落库起止时间窗。
 */
export function ExamActivationConfig({ value, onChange }: ExamActivationConfigProps) {
  const mode = value.activationMode ?? 'manual'
  return (
    <div className="mt-4 pt-4 border-t">
      <Label className="text-xs text-gray-500 mb-2">启用条件</Label>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-2">
        {[
          { key: 'manual', label: '手动启用', desc: '老师手动开启后学生可作答' },
          {
            key: 'scheduled',
            label: '定时启用',
            desc: '预设开始结束时间，到时间自动开启关闭',
          },
          {
            key: 'always',
            label: '随时作答',
            desc: '创建后立即开放，学生随时可进入作答',
          },
        ].map((m) => (
          <button
            key={m.key}
            onClick={() => onChange({ activationMode: m.key })}
            className={cn(
              'w-full text-left p-3 rounded-lg border transition-all',
              mode === m.key
                ? 'border-primary bg-primary/5 text-primary'
                : 'border-gray-200 text-gray-600 hover:border-gray-300',
            )}
          >
            <div className="flex items-center gap-2">
              <div
                className={cn(
                  'w-4 h-4 rounded-full border flex items-center justify-center shrink-0',
                  mode === m.key ? 'bg-primary border-primary' : 'border-gray-300',
                )}
              >
                {mode === m.key && <div className="w-2 h-2 rounded-full bg-white" />}
              </div>
              <span className="text-xs font-medium">{m.label}</span>
            </div>
            <p className="text-[11px] text-gray-400 mt-1 ml-6">{m.desc}</p>
          </button>
        ))}
      </div>
      {mode === 'scheduled' && (
        <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3">
          <FormFieldRow label="启用时间" labelClassName="text-xs text-gray-500">
            <Input
              type="datetime-local"
              value={value.scheduledTime ?? ''}
              onChange={(e) => onChange({ scheduledTime: e.target.value })}
              onFocus={(e) => e.currentTarget.showPicker?.()}
              className="text-sm"
            />
          </FormFieldRow>
          <FormFieldRow label="停用时间" labelClassName="text-xs text-gray-500">
            <Input
              type="datetime-local"
              value={value.scheduledEndTime ?? ''}
              onChange={(e) => onChange({ scheduledEndTime: e.target.value })}
              onFocus={(e) => e.currentTarget.showPicker?.()}
              className="text-sm"
            />
          </FormFieldRow>
        </div>
      )}
    </div>
  )
}
