// frontend/portal-vue/src/views/evaluation/components/question-form-dialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    :title="question ? '编辑题目' : '新建题目'"
    width="820px"
    top="5vh"
    append-to-body
    destroy-on-close
    @update:model-value="(v: boolean) => emit('update:modelValue', v)"
  >
    <div class="qf-body">
      <!-- 题型切换条 -->
      <div class="qf-types">
        <el-radio-group v-model="type" size="small" @change="handleTypeChange">
          <el-radio-button v-for="t in QUESTION_TYPES" :key="t" :value="t">
            {{ QUESTION_TYPE_LABELS[t] }}
          </el-radio-button>
        </el-radio-group>
      </div>

      <!-- 题干 -->
      <div class="qf-section">
        <div class="qf-section-head">
          <span class="qf-section-title">题目</span>
          <el-button link size="small" @click="content = ''">清空</el-button>
        </div>
        <el-input v-model="content" type="textarea" :rows="3" placeholder="请输入题目内容..." />
        <div v-if="type === 'fill'" class="qf-blank-tip">
          <el-button link type="primary" size="small" @click="insertBlankMarker">插入填空标记 {n}</el-button>
          <span class="dim">已识别 {{ blankCount }} 个空位</span>
        </div>
      </div>

      <!-- 选项（单选/多选） -->
      <div v-if="type === 'single' || type === 'multiple'" class="qf-section">
        <div class="qf-section-head">
          <span class="qf-section-title">选项设置</span>
          <el-button v-if="options.length < MAX_OPTIONS" link type="primary" size="small" @click="addOption">
            添加选项
          </el-button>
        </div>
        <div v-for="(opt, index) in options" :key="index" class="qf-option-row">
          <span class="qf-option-label">{{ String.fromCharCode(65 + index) }}</span>
          <el-radio
            v-if="type === 'single'"
            :model-value="singleAnswer === String(index)"
            class="qf-radio"
            @change="() => toggleSingleAnswer(index)"
          />
          <el-checkbox
            v-else
            :model-value="multipleAnswer.includes(String(index))"
            class="qf-radio"
            @change="() => toggleMultipleAnswer(index)"
          />
          <el-input v-model="options[index]" :placeholder="'选项 ' + String.fromCharCode(65 + index)" size="small" />
          <el-button link size="small" :disabled="index === 0" @click="moveOption(index, -1)">上移</el-button>
          <el-button link size="small" :disabled="index === options.length - 1" @click="moveOption(index, 1)">下移</el-button>
          <el-button link type="danger" size="small" :disabled="options.length <= MIN_OPTIONS" @click="removeOption(index)">
            删除
          </el-button>
        </div>
      </div>

      <!-- 判断题答案 -->
      <div v-else-if="type === 'judge'" class="qf-section">
        <div class="qf-section-head"><span class="qf-section-title">正确答案</span></div>
        <el-radio-group v-model="judgeAnswer">
          <el-radio-button value="true">正确</el-radio-button>
          <el-radio-button value="false">错误</el-radio-button>
        </el-radio-group>
      </div>

      <!-- 填空题答案 -->
      <div v-else-if="type === 'fill'" class="qf-section">
        <div class="qf-section-head"><span class="qf-section-title">空位答案</span></div>
        <el-empty v-if="blankCount === 0" description="在题目中点击「插入填空标记」来创建空位" :image-size="60" />
        <div v-for="idx in blankCount" :key="idx" class="qf-fill-row">
          <el-tag size="small" type="warning">空位 {{ idx }}</el-tag>
          <el-input :model-value="fillAnswer[idx - 1] || ''" size="small" placeholder="标准答案"
            @update:model-value="(v: string) => updateBlankAnswer(idx - 1, v)" />
        </div>
      </div>

      <!-- 问答题/简答题答案 -->
      <div v-else class="qf-section">
        <div class="qf-section-head"><span class="qf-section-title">参考答案</span></div>
        <el-input v-model="essayAnswer" type="textarea" :rows="3" placeholder="请输入参考答案..." />
      </div>

      <!-- 设置 -->
      <div class="qf-section qf-settings">
        <div class="qf-setting-row">
          <span class="qf-label">难度</span>
          <el-select v-model="difficulty" size="small" style="width: 140px">
            <el-option v-for="(label, key) in DIFFICULTY_LABELS" :key="key" :label="label" :value="key" />
          </el-select>
          <span class="qf-label">分值</span>
          <el-input-number v-model="score" :min="0" :step="0.5" size="small" style="width: 120px" />
        </div>
        <div class="qf-setting-row">
          <span class="qf-label">知识点</span>
          <el-select
            v-model="knowledgePointIds"
            multiple
            filterable
            clearable
            size="small"
            placeholder="选择知识点..."
            style="flex: 1"
            :loading="loadingKnowledgePoints"
          >
            <el-option v-for="kp in knowledgePoints" :key="kp.id" :label="kp.name" :value="kp.id" />
          </el-select>
        </div>
        <div v-if="type === 'single' || type === 'multiple'" class="qf-setting-row">
          <el-checkbox v-model="shuffleOptions">选项随机排序</el-checkbox>
        </div>
        <div class="qf-setting-row">
          <span class="qf-label">解析</span>
          <el-input v-model="analysis" type="textarea" :rows="2" placeholder="输入解析内容（选填）" style="flex: 1" />
        </div>
      </div>
    </div>

    <template #footer>
      <el-button @click="emit('update:modelValue', false)">取消</el-button>
      <el-button v-if="!question" :disabled="!content.trim()" @click="handleSubmitAndContinue">保存并继续添加</el-button>
      <el-button type="primary" :disabled="!content.trim()" @click="handleSubmit">保存</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
// 题目编辑弹窗：对齐 React frontend/edu/components/evaluation/question-form-dialog.tsx
import { computed, ref, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { knowledgeApi } from '@/api/lesson';
import { QUESTION_TYPES, QUESTION_TYPE_LABELS, DIFFICULTY_LABELS } from '@/types/evaluation';
import type { Difficulty, Question, QuestionFormData, QuestionType } from '@/types/evaluation';

const MAX_OPTIONS = 8;
const MIN_OPTIONS = 2;

interface EvalKnowledgePoint {
  id: string;
  name: string;
}

const props = withDefaults(
  defineProps<{
    modelValue: boolean;
    question?: Question | null;
    defaultType?: QuestionType;
  }>(),
  { question: null, defaultType: 'single' }
);

const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'submit', data: QuestionFormData): void;
}>();

const type = ref<QuestionType>('single');
const content = ref('');
const options = ref<string[]>(['', '', '', '']);
const answer = ref<string | string[]>('');
const score = ref(0);
const analysis = ref('');
const difficulty = ref<Difficulty>('medium');
const knowledgePointIds = ref<string[]>([]);
const knowledgePoints = ref<EvalKnowledgePoint[]>([]);
const loadingKnowledgePoints = ref(false);
const shuffleOptions = ref(false);

const singleAnswer = computed({
  get: () => (typeof answer.value === 'string' ? answer.value : ''),
  set: (v: string) => (answer.value = v)
});
const multipleAnswer = computed(() => (Array.isArray(answer.value) ? answer.value : []));
const judgeAnswer = computed({
  get: () => (typeof answer.value === 'string' ? answer.value : ''),
  set: (v: string) => (answer.value = v)
});
const essayAnswer = computed({
  get: () => (typeof answer.value === 'string' ? answer.value : ''),
  set: (v: string) => (answer.value = v)
});
const fillAnswer = computed(() => (Array.isArray(answer.value) ? answer.value : []));

const blankCount = computed(() => {
  const matches = content.value.match(/\{(\d+)\}/g);
  return matches ? matches.length : 0;
});

async function loadKnowledgePoints() {
  loadingKnowledgePoints.value = true;
  try {
    const res = await knowledgeApi.list({ limit: 1000 });
    knowledgePoints.value = res.items.map((kp) => ({ id: kp.id, name: kp.name }));
  } catch {
    knowledgePoints.value = [];
  } finally {
    loadingKnowledgePoints.value = false;
  }
}

// 后端存储的选项文本答案转索引（单/多选弹窗内以 A/B/C/D 判断）
function answerToIndexes(ans: string | string[], opts: string[]): string | string[] {
  if (Array.isArray(ans)) {
    return ans.map((a) => String(opts.indexOf(a))).filter((i) => i !== '-1');
  }
  const idx = opts.indexOf(ans as string);
  return idx >= 0 ? String(idx) : '';
}

function loadQuestion() {
  if (props.question) {
    type.value = props.question.type;
    content.value = props.question.content;
    options.value = props.question.options || ['', '', '', ''];
    if (props.question.type === 'single') {
      const indexes = answerToIndexes(props.question.answer, props.question.options || []);
      answer.value = Array.isArray(indexes) ? indexes[0] ?? '' : indexes;
    } else if (props.question.type === 'multiple') {
      answer.value = answerToIndexes(props.question.answer, props.question.options || []);
    } else if (props.question.type === 'judge') {
      answer.value = Array.isArray(props.question.answer)
        ? props.question.answer[0] ?? ''
        : props.question.answer;
    } else if (props.question.type === 'fill') {
      answer.value = Array.isArray(props.question.answer) ? props.question.answer : [];
    } else {
      answer.value = Array.isArray(props.question.answer)
        ? props.question.answer[0] ?? ''
        : props.question.answer;
    }
    analysis.value = props.question.analysis || '';
    difficulty.value = (props.question.difficulty as Difficulty) || 'medium';
    score.value = props.question.score ?? 0;
    knowledgePointIds.value = props.question.knowledgePoints || [];
    shuffleOptions.value = !!props.question.shuffleOptions;
  } else {
    type.value = props.defaultType;
    content.value = '';
    options.value = ['', '', '', ''];
    answer.value = props.defaultType === 'multiple' ? [] : '';
    analysis.value = '';
    difficulty.value = 'medium';
    score.value = 0;
    knowledgePointIds.value = [];
    shuffleOptions.value = false;
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (!open) return;
    loadQuestion();
    void loadKnowledgePoints();
  }
);

function buildFormData(): QuestionFormData {
  let finalAnswer: string[];
  if (type.value === 'single') {
    const chosen = options.value[parseInt(answer.value as string, 10)] || '';
    finalAnswer = chosen ? [chosen] : [];
  } else if (type.value === 'multiple') {
    finalAnswer = (answer.value as string[])
      .map((a) => options.value[parseInt(a, 10)] || '')
      .filter(Boolean);
  } else if (Array.isArray(answer.value)) {
    finalAnswer = [...answer.value];
  } else {
    finalAnswer = [answer.value as string];
  }

  const data: QuestionFormData = {
    type: type.value,
    content: content.value.trim(),
    analysis: analysis.value.trim() || undefined,
    score: score.value,
    answer: finalAnswer,
    difficulty: difficulty.value,
    knowledgePoints: knowledgePointIds.value.length > 0 ? knowledgePointIds.value : undefined,
    shuffleOptions: shuffleOptions.value
  };

  if (type.value === 'single' || type.value === 'multiple') {
    data.options = options.value.filter((o) => o.trim());
  }
  return data;
}

function resetForNext() {
  content.value = '';
  options.value = ['', '', '', ''];
  answer.value = type.value === 'multiple' ? [] : '';
  analysis.value = '';
  shuffleOptions.value = false;
}

function handleSubmit() {
  if (!content.value.trim()) return;
  emit('submit', buildFormData());
  emit('update:modelValue', false);
}

function handleSubmitAndContinue() {
  if (!content.value.trim()) return;
  emit('submit', buildFormData());
  resetForNext();
}

function handleTypeChange() {
  options.value = ['', '', '', ''];
  answer.value = type.value === 'multiple' ? [] : '';
}

function toggleSingleAnswer(index: number) {
  answer.value = String(index);
}

function toggleMultipleAnswer(index: number) {
  const key = String(index);
  const current = Array.isArray(answer.value) ? answer.value : [];
  answer.value = current.includes(key) ? current.filter((a) => a !== key) : [...current, key];
}

function addOption() {
  if (options.value.length < MAX_OPTIONS) options.value = [...options.value, ''];
}

function removeOption(index: number) {
  if (options.value.length <= MIN_OPTIONS) return;
  const next = options.value.filter((_, i) => i !== index);
  const adjust = (a: string): string | null => {
    const idx = parseInt(a, 10);
    if (idx === index) return null;
    if (idx > index) return String(idx - 1);
    return String(idx);
  };
  options.value = next;
  if (Array.isArray(answer.value)) {
    answer.value = answer.value.map(adjust).filter((a): a is string => a !== null);
  } else {
    const adjusted = adjust(answer.value as string);
    answer.value = adjusted === null ? '' : adjusted;
  }
}

function moveOption(index: number, dir: number) {
  const newIndex = index + dir;
  if (newIndex < 0 || newIndex >= options.value.length) return;
  const next = [...options.value];
  const temp = next[index];
  next[index] = next[newIndex];
  next[newIndex] = temp;
  options.value = next;

  const swap = (a: string): string => {
    const idx = parseInt(a, 10);
    if (idx === index) return String(newIndex);
    if (idx === newIndex) return String(index);
    return String(idx);
  };
  if (Array.isArray(answer.value)) {
    answer.value = answer.value.map(swap);
  } else {
    answer.value = swap(answer.value as string);
  }
}

function insertBlankMarker() {
  const marker = `{${blankCount.value + 1}}`;
  content.value = content.value + marker;
}

function updateBlankAnswer(idx: number, value: string) {
  const current = Array.isArray(answer.value) ? [...answer.value] : [];
  current[idx] = value;
  answer.value = current;
}
</script>

<style scoped>
.qf-body {
  max-height: 66vh;
  overflow-y: auto;
  padding-right: 4px;
}
.qf-types {
  margin-bottom: 14px;
  display: flex;
  flex-wrap: wrap;
}
.qf-section {
  margin-bottom: 16px;
}
.qf-section-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}
.qf-section-title {
  font-size: 13px;
  font-weight: 600;
  color: #606266;
}
.qf-blank-tip {
  margin-top: 6px;
  display: flex;
  align-items: center;
  gap: 10px;
}
.dim {
  color: #909399;
  font-size: 12px;
}
.qf-option-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}
.qf-option-label {
  width: 18px;
  text-align: center;
  font-weight: 600;
  color: #909399;
}
.qf-radio {
  flex-shrink: 0;
}
.qf-fill-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}
.qf-settings {
  border-top: 1px solid #ebeef5;
  padding-top: 14px;
}
.qf-setting-row {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  margin-bottom: 12px;
}
.qf-label {
  width: 48px;
  flex-shrink: 0;
  font-size: 13px;
  color: #606266;
  line-height: 32px;
}
</style>

// apps/edu/components/evaluation/question-form-dialog.tsx
// @ts-nocheck
"use client"

import { useState, useEffect, useRef, useCallback, useMemo } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { FieldLabel } from "@/components/ui/field"
import { Checkbox } from "@/components/ui/checkbox"
import { Badge } from "@/components/ui/badge"
import { Plus, X, ArrowUp, ArrowDown, Check, ChevronDown, Settings2 } from "lucide-react"
import type { Question, QuestionType, QuestionFormData, Difficulty, EvalKnowledgePoint } from "@/lib/types"
import { QUESTION_TYPE_LABELS, DIFFICULTY_LABELS } from "@/lib/types"
import { knowledgeApi } from "@/lib/api"

interface QuestionFormDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  question?: Question | null
  defaultType?: QuestionType
  onSubmit: (data: QuestionFormData) => void
}

const MAX_OPTIONS = 8
const MIN_OPTIONS = 2

export function QuestionFormDialog({
  open,
  onOpenChange,
  question,
  defaultType,
  onSubmit,
}: QuestionFormDialogProps) {
  const contentRef = useRef<HTMLTextAreaElement>(null)
  const [type, setType] = useState<QuestionType>("single")
  const [content, setContent] = useState("")
  const [options, setOptions] = useState<string[]>(["", "", "", ""])
  const [answer, setAnswer] = useState<string | string[]>("")
  const [analysis, setAnalysis] = useState("")
  const [difficulty, setDifficulty] = useState<Difficulty>("medium")
  const [knowledgePointIds, setKnowledgePointIds] = useState<string[]>([])
  const [knowledgePoints, setKnowledgePoints] = useState<EvalKnowledgePoint[]>([])
  const [loadingKnowledgePoints, setLoadingKnowledgePoints] = useState(false)
  const [knowledgeOpen, setKnowledgeOpen] = useState(false)
  const [advancedOpen, setAdvancedOpen] = useState(false)
  const knowledgeRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    let cancelled = false
    setLoadingKnowledgePoints(true)
    knowledgeApi.list({ limit: 1000 })
      .then((res) => {
        if (cancelled) return
        setKnowledgePoints(res.items.map((kp) => ({ id: kp.id, name: kp.name })))
      })
      .catch((err) => {
        if (!cancelled) {
          console.error('Failed to load knowledge points', err)
        }
      })
      .finally(() => {
        if (!cancelled) setLoadingKnowledgePoints(false)
      })
    return () => { cancelled = true }
  }, [open])

  useEffect(() => {
    if (question) {
      setType(question.type)
      setContent(question.content)
      setOptions(question.options || ["", "", "", ""])
      setAnswer(question.answer)
      setAnalysis(question.analysis || "")
      setDifficulty(question.difficulty || "medium")
      setKnowledgePointIds(question.knowledgePoints || [])
    } else {
      setType(defaultType || "single")
      setContent("")
      setOptions(["", "", "", ""])
      setAnswer(defaultType === "multiple" ? [] : "")
      setAnalysis("")
      setDifficulty("medium")
      setKnowledgePointIds([])
    }
    setKnowledgeOpen(false)
    setAdvancedOpen(false)
  }, [question, open, defaultType])

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (knowledgeRef.current && !knowledgeRef.current.contains(e.target as Node)) {
        setKnowledgeOpen(false)
      }
    }
    document.addEventListener("mousedown", handleClickOutside)
    return () => document.removeEventListener("mousedown", handleClickOutside)
  }, [])

  const blankCount = useMemo(() => {
    const matches = content.match(/\{(\d+)\}/g)
    if (!matches) return 0
    const nums = matches.map(m => parseInt(m.replace(/[{}]/g, ""), 10))
    return Math.max(0, ...nums)
  }, [content])

  const normalizedFillAnswer = useMemo(() => {
    if (type !== "fill") return []
    return Array.isArray(answer) ? answer : (answer ? [answer as string] : [])
  }, [answer, type])

  useEffect(() => {
    if (type !== "fill") return
    const current = Array.isArray(answer) ? [...answer] : (answer ? [answer as string] : [])
    if (current.length < blankCount) {
      while (current.length < blankCount) current.push("")
      setAnswer(current)
    } else if (current.length > blankCount) {
      setAnswer(current.slice(0, blankCount))
    }
  }, [blankCount, type, answer])

  const buildFormData = useCallback((): QuestionFormData => {
    const data: QuestionFormData = {
      type,
      content: content.trim(),
      analysis: analysis.trim() || undefined,
      score: 0,
      answer: Array.isArray(answer) ? answer : [answer],
      difficulty,
      knowledgePoints: knowledgePointIds.length > 0 ? knowledgePointIds : undefined,
    }

    if (type === "single" || type === "multiple") {
      data.options = options.filter(o => o.trim())
    }

    return data
  }, [type, content, analysis, answer, difficulty, knowledgePointIds, options])

  const resetForNext = useCallback(() => {
    setContent("")
    setOptions(["", "", "", ""])
    setAnswer(type === "multiple" ? [] : "")
    setAnalysis("")
  }, [type])

  const handleSubmit = useCallback(() => {
    if (!content.trim()) return
    onSubmit(buildFormData())
    onOpenChange(false)
  }, [content, buildFormData, onSubmit, onOpenChange])

  const handleSubmitAndContinue = useCallback(() => {
    if (!content.trim()) return
    onSubmit(buildFormData())
    resetForNext()
  }, [content, buildFormData, onSubmit, resetForNext])

  // Ctrl+Enter 保存并新建
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.ctrlKey && e.key === "Enter" && open && !question) {
        e.preventDefault()
        handleSubmitAndContinue()
      }
    }
    document.addEventListener("keydown", handleKeyDown)
    return () => document.removeEventListener("keydown", handleKeyDown)
  }, [open, question, handleSubmitAndContinue])

  const handleTypeChange = useCallback((newType: QuestionType) => {
    setType(newType)
    setOptions(["", "", "", ""])
    setAnswer(newType === "multiple" ? [] : "")
  }, [])

  const handleOptionChange = useCallback((index: number, value: string) => {
    setOptions(prev => {
      const next = [...prev]
      next[index] = value
      return next
    })
  }, [])

  const addOption = useCallback(() => {
    setOptions(prev => prev.length >= MAX_OPTIONS ? prev : [...prev, ""])
  }, [])

  const removeOption = useCallback((index: number) => {
    setOptions(prev => {
      if (prev.length <= MIN_OPTIONS) return prev
      const removedText = prev[index]
      const next = prev.filter((_, i) => i !== index)

      if (type === "single" && answer === removedText) {
        setAnswer("")
      } else if (type === "multiple" && Array.isArray(answer)) {
        const currentAnswers = answer as string[]
        const removeIdx = currentAnswers.indexOf(removedText)
        if (removeIdx >= 0) {
          setAnswer([...currentAnswers.slice(0, removeIdx), ...currentAnswers.slice(removeIdx + 1)])
        }
      }
      return next
    })
  }, [type, answer])

  const moveOption = useCallback((index: number, dir: number) => {
    const newIndex = index + dir
    if (newIndex < 0 || newIndex >= options.length) return
    const newOptions = [...options]
    const temp = newOptions[index]
    newOptions[index] = newOptions[newIndex]
    newOptions[newIndex] = temp
    setOptions(newOptions)
  }, [options])

  const toggleSingleAnswer = useCallback((index: number) => {
    setAnswer(options[index])
  }, [options])

  const toggleMultipleAnswer = useCallback((index: number, checked: boolean) => {
    const optionText = options[index]
    setAnswer(prev => {
      const currentAnswers = Array.isArray(prev) ? prev : []
      if (checked) {
        return [...currentAnswers, optionText]
      } else {
        const removeIdx = currentAnswers.indexOf(optionText)
        if (removeIdx >= 0) {
          return [...currentAnswers.slice(0, removeIdx), ...currentAnswers.slice(removeIdx + 1)]
        }
        return currentAnswers
      }
    })
  }, [options])

  const isMultipleAnswerChecked = useCallback((index: number) => {
    return Array.isArray(answer) && answer.includes(options[index])
  }, [answer, options])

  const insertBlankMarker = useCallback(() => {
    const textarea = contentRef.current
    if (!textarea) return
    const start = textarea.selectionStart
    const end = textarea.selectionEnd
    const marker = `{${blankCount + 1}}`
    const newContent = content.substring(0, start) + marker + content.substring(end)
    setContent(newContent)
    setTimeout(() => {
      textarea.focus()
      const pos = start + marker.length
      textarea.setSelectionRange(pos, pos)
    }, 0)
  }, [blankCount, content])

  const updateBlankAnswer = useCallback((idx: number, value: string) => {
    setAnswer(prev => {
      const current = Array.isArray(prev) ? [...prev] : []
      current[idx] = value
      return current
    })
  }, [])

  const addKnowledgePoint = useCallback((kpId: string) => {
    setKnowledgePointIds(prev => prev.includes(kpId) ? prev : [...prev, kpId])
  }, [])

  const removeKnowledgePoint = useCallback((kpId: string) => {
    setKnowledgePointIds(prev => prev.filter(id => id !== kpId))
  }, [])

  const getKnowledgePointName = useCallback((id: string) => {
    return knowledgePoints.find(kp => kp.id === id)?.name || id
  }, [knowledgePoints])

  const renderOptionEditor = (isMultiple: boolean) => (
    <div className="flex flex-col gap-3">
      <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">选项设置</label>
      <div className="flex flex-col gap-2">
        {options.map((option, index) => (
          <div
            key={index}
            className="group flex items-center gap-2 rounded-md p-1 transition-colors hover:bg-muted/50"
          >
            {isMultiple ? (
              <Checkbox
                checked={isMultipleAnswerChecked(index)}
                onCheckedChange={(checked) => toggleMultipleAnswer(index, !!checked)}
                className="shrink-0"
              />
            ) : (
              <input
                type="radio"
                name="correct-single"
                checked={answer === option && option.trim() !== ""}
                onChange={() => toggleSingleAnswer(index)}
                className="size-4 accent-primary shrink-0"
              />
            )}
            <span className="w-6 shrink-0 text-center font-mono text-xs text-muted-foreground">
              {String.fromCharCode(65 + index)}.
            </span>
            <Input
              value={option}
              onChange={(e) => handleOptionChange(index, e.target.value)}
              placeholder={`选项 ${String.fromCharCode(65 + index)}`}
              className="h-8 flex-1"
            />
            <div className="flex opacity-0 transition-opacity group-hover:opacity-100">
              <Button type="button" variant="ghost" size="icon" className="size-7" onClick={() => moveOption(index, -1)} disabled={index === 0}>
                <ArrowUp className="size-3.5" />
              </Button>
              <Button type="button" variant="ghost" size="icon" className="size-7" onClick={() => moveOption(index, 1)} disabled={index === options.length - 1}>
                <ArrowDown className="size-3.5" />
              </Button>
              <Button type="button" variant="ghost" size="icon" className="size-7 hover:text-destructive" onClick={() => removeOption(index)} disabled={options.length <= MIN_OPTIONS}>
                <X className="size-3.5" />
              </Button>
            </div>
          </div>
        ))}
      </div>
      {options.length < MAX_OPTIONS && (
        <Button type="button" variant="outline" size="sm" onClick={addOption} className="w-fit">
          <Plus className="mr-1 size-3.5" />
          添加选项
        </Button>
      )}
    </div>
  )

  const renderLeftPane = () => {
    return (
      <div className="flex flex-1 flex-col gap-4">
        {/* 题干 */}
        <div className="rounded-lg border bg-card p-4 shadow-sm">
          <label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            题干 <span className="text-destructive">*</span>
          </label>
          <Textarea
            ref={contentRef}
            value={content}
            onChange={(e) => setContent(e.target.value)}
            placeholder="请输入题目内容..."
            className="min-h-[90px] resize-none"
            required
          />
          <div className="mt-2 flex gap-2">
            {type === "fill" && (
              <Button type="button" variant="outline" size="sm" onClick={insertBlankMarker}>
                <Plus className="mr-1 size-3.5" />
                插入填空标记
              </Button>
            )}
            <Button type="button" variant="ghost" size="sm" onClick={() => setContent("")}>
              清空
            </Button>
          </div>
        </div>

        {/* 题型专属编辑区 */}
        <div className="flex flex-1 flex-col rounded-lg border bg-card p-4 shadow-sm">
          {type === "single" && renderOptionEditor(false)}
          {type === "multiple" && renderOptionEditor(true)}
          {type === "judge" && (
            <div className="flex flex-1 flex-col gap-3">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">正确答案</label>
              <div className="flex flex-1 gap-3">
                <button
                  type="button"
                  onClick={() => setAnswer("true")}
                  className={`flex flex-1 items-center justify-center gap-2 rounded-xl border-2 text-base font-semibold transition-colors ${
                    answer === "true"
                      ? "border-green-500 bg-green-50 text-green-600"
                      : "border-border bg-background text-muted-foreground hover:border-muted"
                  }`}
                >
                  <Check className="size-5" />
                  正确
                </button>
                <button
                  type="button"
                  onClick={() => setAnswer("false")}
                  className={`flex flex-1 items-center justify-center gap-2 rounded-xl border-2 text-base font-semibold transition-colors ${
                    answer === "false"
                      ? "border-destructive bg-red-50 text-destructive"
                      : "border-border bg-background text-muted-foreground hover:border-muted"
                  }`}
                >
                  <X className="size-5" />
                  错误
                </button>
              </div>
            </div>
          )}
          {type === "fill" && (
            <div className="flex flex-col gap-3">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">空位答案</label>
              {blankCount === 0 ? (
                <div className="text-sm text-muted-foreground">在题干中点击「插入填空标记」来创建空位</div>
              ) : (
                <div className="flex flex-col gap-2">
                  {Array.from({ length: blankCount }).map((_, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <span className="w-14 shrink-0 text-xs text-muted-foreground">空位 {idx + 1}:</span>
                      <Input
                        value={normalizedFillAnswer[idx] || ""}
                        onChange={(e) => updateBlankAnswer(idx, e.target.value)}
                        placeholder="标准答案"
                        className="h-8 flex-1"
                      />
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
          {(type === "essay" || type === "short_answer") && (
            <div className="flex flex-1 flex-col gap-3">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">参考答案</label>
              <Textarea
                value={answer as string}
                onChange={(e) => setAnswer(e.target.value)}
                placeholder="请输入参考答案..."
                className="min-h-0 flex-1 resize-none"
              />
            </div>
          )}
        </div>
      </div>
    )
  }

  const renderRightAnswer = () => {
    if (type === "single") {
      return (
        <div className="flex flex-col gap-2">
          <label className="text-xs text-muted-foreground">正确答案</label>
          <div className="flex flex-col gap-1">
            {options.map((option, index) => (
              <label
                key={index}
                className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors hover:bg-muted"
              >
                <input
                  type="radio"
                  name="right-correct-single"
                  checked={answer === option && option.trim() !== ""}
                  onChange={() => toggleSingleAnswer(index)}
                  className="size-4 accent-primary"
                />
                <span>{String.fromCharCode(65 + index)}. {option}</span>
              </label>
            ))}
          </div>
        </div>
      )
    }

    if (type === "multiple") {
      return (
        <div className="flex flex-col gap-2">
          <label className="text-xs text-muted-foreground">正确答案（可多选）</label>
          <div className="flex flex-col gap-1">
            {options.map((option, index) => (
              <label
                key={index}
                className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors hover:bg-muted"
              >
                <Checkbox
                  checked={isMultipleAnswerChecked(index)}
                  onCheckedChange={(checked) => toggleMultipleAnswer(index, !!checked)}
                />
                <span>{String.fromCharCode(65 + index)}. {option}</span>
              </label>
            ))}
          </div>
        </div>
      )
    }

    if (type === "judge") {
      return (
        <div className="flex flex-col gap-2">
          <label className="text-xs text-muted-foreground">正确答案</label>
          <div className={`inline-flex w-fit items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${
            answer === "false" ? "bg-red-50 text-destructive" : "bg-green-50 text-green-600"
          }`}>
            {answer === "false" ? <X className="size-4" /> : <Check className="size-4" />}
            {answer === "false" ? "错误" : "正确"}
          </div>
        </div>
      )
    }

    if (type === "fill") {
      return (
        <div className="flex flex-col gap-2">
          <label className="text-xs text-muted-foreground">空位摘要</label>
          {blankCount === 0 ? (
            <span className="text-sm text-muted-foreground">暂无空位</span>
          ) : (
            <div className="flex flex-wrap gap-2">
              {Array.from({ length: blankCount }).map((_, idx) => (
                <Badge key={idx} variant="secondary" className="text-xs">
                  空位{idx + 1}: {normalizedFillAnswer[idx] || "(未填写)"}
                </Badge>
              ))}
            </div>
          )}
        </div>
      )
    }

    return (
      <div className="flex flex-col gap-2">
        <label className="text-xs text-muted-foreground">评分关键词（可选，用于自动评分）</label>
        <Input placeholder="用逗号分隔关键词" disabled className="h-8" />
      </div>
    )
  }

  const renderRightPane = () => {
    return (
      <div className="flex flex-col gap-4">
        {/* 基础设置 */}
        <div className="rounded-lg border bg-card p-4 shadow-sm">
          <label className="mb-3 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">基础设置</label>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="mb-1 block text-xs text-muted-foreground">难度</label>
              <Select value={difficulty} onValueChange={(v) => setDifficulty(v as Difficulty)}>
                <SelectTrigger className="h-9 w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {(Object.keys(DIFFICULTY_LABELS) as Difficulty[]).map((d) => (
                      <SelectItem key={d} value={d}>{DIFFICULTY_LABELS[d]}</SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
            </div>
            <div ref={knowledgeRef} className="relative">
              <label className="mb-1 block text-xs text-muted-foreground">关联知识点</label>
              <button
                type="button"
                onClick={() => setKnowledgeOpen(!knowledgeOpen)}
                className={`flex h-9 w-full items-center justify-between rounded-md border bg-background px-3 py-2 text-sm transition-colors ${
                  knowledgeOpen ? "border-primary ring-1 ring-primary" : "border-input hover:border-muted-foreground"
                }`}
              >
                <span className={knowledgePointIds.length ? "text-foreground" : "text-muted-foreground"}>
                  {knowledgePointIds.length ? `已选择 ${knowledgePointIds.length} 项` : "选择知识点..."}
                </span>
                <ChevronDown className={`size-3.5 text-muted-foreground transition-transform ${knowledgeOpen ? "rotate-180" : ""}`} />
              </button>
              {knowledgeOpen && (
                <div className="absolute top-full z-50 mt-1 max-h-48 w-full overflow-auto rounded-md border bg-popover p-1 shadow-md">
                  {loadingKnowledgePoints ? (
                    <div className="p-2 text-sm text-muted-foreground">加载中...</div>
                  ) : knowledgePoints.length === 0 ? (
                    <div className="p-2 text-sm text-muted-foreground">暂无知识点</div>
                  ) : (
                    knowledgePoints.map((kp) => (
                      <label
                        key={kp.id}
                        className="flex cursor-pointer items-center gap-2 rounded px-2 py-1.5 text-sm hover:bg-accent"
                      >
                        <Checkbox
                          checked={knowledgePointIds.includes(kp.id)}
                          onCheckedChange={(checked) => {
                            if (checked) addKnowledgePoint(kp.id)
                            else removeKnowledgePoint(kp.id)
                          }}
                        />
                        <span>{kp.name}</span>
                      </label>
                    ))
                  )}
                </div>
              )}
              {knowledgePointIds.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {knowledgePointIds.map(id => (
                    <Badge key={id} variant="secondary" className="gap-1 text-xs">
                      {getKnowledgePointName(id)}
                      <button type="button" onClick={() => removeKnowledgePoint(id)} className="ml-0.5 rounded-full hover:bg-muted">
                        <X className="size-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* 答案设置 */}
        <div className="rounded-lg border bg-card p-4 shadow-sm">
          <label className="mb-3 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">答案设置</label>
          {renderRightAnswer()}
        </div>

        {/* 答案解析 */}
        <div className="rounded-lg border bg-card p-4 shadow-sm">
          <label className="mb-2 block text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            答案解析 <span className="font-normal normal-case text-muted-foreground/60">(选填)</span>
          </label>
          <Textarea
            value={analysis}
            onChange={(e) => setAnalysis(e.target.value)}
            placeholder="输入解析内容，帮助学生理解..."
            className="h-20 min-h-0 resize-none"
          />
        </div>

        {/* 高级设置 */}
        {(type === "single" || type === "multiple") && (
          <div className="overflow-hidden rounded-lg border bg-card p-0 shadow-sm">
            <button
              type="button"
              onClick={() => setAdvancedOpen(!advancedOpen)}
              className="flex w-full items-center justify-between px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground hover:bg-accent/50"
            >
              <span className="flex items-center gap-1.5"><Settings2 className="size-3.5" /> 高级设置</span>
              <ChevronDown className={`size-3.5 text-muted-foreground transition-transform ${advancedOpen ? "rotate-180" : ""}`} />
            </button>
            {advancedOpen && (
              <div className="px-4 pb-3">
                <label className="flex items-center justify-between text-sm">
                  <span>选项随机排序</span>
                  <Checkbox disabled />
                </label>
              </div>
            )}
          </div>
        )}
      </div>
    )
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        size="xl"
        className="flex max-h-[92vh] max-w-[1100px] flex-col overflow-hidden p-0"
        annotationContext="question-form"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b px-5 py-3">
          <DialogHeader className="m-0 gap-1 text-left">
            <DialogTitle className="text-base">{question ? "编辑题目" : "新建题目"}</DialogTitle>
            <DialogDescription className="text-xs">
              {question ? "修改题目内容和答案" : "添加新题目到当前题库"}
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-center gap-2">
            <Button type="button" variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              取消
            </Button>
            {!question && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                disabled={!content.trim()}
                onClick={handleSubmitAndContinue}
              >
                保存并新建
              </Button>
            )}
            <Button type="button" size="sm" disabled={!content.trim()} onClick={handleSubmit}>
              {question ? "保存" : "创建"}
            </Button>
          </div>
        </div>

        {/* 题型条 */}
        <div className="flex items-center gap-2 border-b bg-card px-5 py-2">
          <span className="text-xs text-muted-foreground">题型:</span>
          {(Object.keys(QUESTION_TYPE_LABELS) as QuestionType[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => handleTypeChange(t)}
              className={`rounded-md border px-3 py-1 text-xs font-medium transition-colors ${
                type === t
                  ? "border-primary bg-primary/10 text-primary"
                  : "border-transparent bg-transparent text-muted-foreground hover:bg-muted"
              }`}
            >
              {QUESTION_TYPE_LABELS[t]}
            </button>
          ))}
        </div>

        {/* 双栏主体 */}
        <div className="flex flex-1 overflow-hidden bg-muted/30">
          <div className="flex w-[55%] flex-col gap-4 overflow-y-auto p-5">
            {renderLeftPane()}
          </div>
          <div className="my-5 w-px bg-border" />
          <div className="flex w-[45%] flex-col gap-4 overflow-y-auto p-5">
            {renderRightPane()}
          </div>
        </div>

        {/* 底部状态栏 */}
        <div className="flex h-8 items-center justify-between border-t bg-card px-5 text-xs text-muted-foreground">
          <span>就绪 | 当前题型: {QUESTION_TYPE_LABELS[type]}</span>
          <span>Ctrl+Enter 保存并新建</span>
        </div>
      </DialogContent>
    </Dialog>
  )
}
