// plus-ui/src-portal/views/system/accounts.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <span class="card-title">账户管理</span>
            <span class="card-sub">管理系统登录账户，绑定角色并维护账户状态</span>
          </div>
          <el-button v-if="selectedIds.length" type="danger" :loading="batchDeleting" @click="confirmBatchDelete">
            批量删除({{ selectedIds.length }})
          </el-button>
        </div>
      </template>

      <!-- 角色筛选 tabs -->
      <el-radio-group v-model="roleCode" class="filter-bar" @change="onRoleChange">
        <el-radio-button value="">全部</el-radio-button>
        <el-radio-button v-for="r in roles" :key="r.id" :value="r.code">{{ r.name }}</el-radio-button>
      </el-radio-group>

      <el-input v-model="searchText" placeholder="搜索姓名或账户..." clearable style="max-width: 320px; margin-bottom: 12px" @input="onSearch" @clear="onSearch" />

      <el-table v-loading="loading" :data="accounts" stripe @selection-change="onSelectionChange">
        <el-table-column type="selection" width="45" />
        <el-table-column prop="name" label="姓名" min-width="110" />
        <el-table-column label="角色" min-width="160">
          <template #default="{ row }">
            <template v-if="row.roleNames.length">
              <el-tag v-for="rn in row.roleNames" :key="rn" size="small" class="tag">{{ rn }}</el-tag>
            </template>
            <span v-else>—</span>
          </template>
        </el-table-column>
        <el-table-column label="所属组织" min-width="160">
          <template #default="{ row }">
            <span>{{ row.orgNodeName }}</span>
            <el-tag v-if="row.orgTypeName" size="small" type="info" class="tag">{{ row.orgTypeName }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="账户登录名" prop="loginName" min-width="140" show-overflow-tooltip />
        <el-table-column label="状态" width="90">
          <template #default="{ row }">
            <el-tag :type="row.status === 'active' ? 'success' : 'info'">{{ row.status === 'active' ? '启用' : '停用' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="最后登录时间" prop="lastLogin" min-width="160" show-overflow-tooltip />
        <el-table-column label="操作" width="260" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openBindRoles(row)">绑定角色</el-button>
            <el-button size="small" @click="openResetPwd(row)">重置密码</el-button>
            <el-button size="small" :type="row.status === 'active' ? 'danger' : 'success'" @click="toggleStatus(row)">
              {{ row.status === 'active' ? '禁用账户' : '启用账户' }}
            </el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="load"
      />
    </el-card>

    <!-- 绑定角色 -->
    <el-dialog v-model="bindDialog" :title="`绑定角色 - ${bindTarget?.name || ''}`" width="440px">
      <div class="bind-tip">为用户绑定 1 个或多个角色，用户登录后可在顶栏切换当前角色</div>
      <el-select v-model="bindRoleIds" multiple filterable style="width: 100%" placeholder="搜索并选择角色...">
        <el-option v-for="r in roles" :key="r.id" :label="r.name" :value="r.id">
          <span>{{ r.name }}</span>
          <span class="opt-sub">{{ r.code }}</span>
        </el-option>
      </el-select>
      <div class="bind-tags">
        <el-tag v-for="id in bindRoleIds" :key="id" closable class="tag" @close="bindRoleIds = bindRoleIds.filter((i) => i !== id)">
          {{ roleName(id) }}
        </el-tag>
        <span v-if="!bindRoleIds.length" class="bind-empty">至少需要绑定一个角色</span>
      </div>
      <template #footer>
        <el-button @click="bindDialog = false">取消</el-button>
        <el-button type="primary" :loading="bindSaving" :disabled="!bindRoleIds.length" @click="saveBindRoles">保存</el-button>
      </template>
    </el-dialog>

    <!-- 重置密码 -->
    <el-dialog v-model="resetDialog" :title="`重置密码 - ${resetTarget?.name || ''}`" width="420px">
      <el-input v-model="resetPassword" type="password" show-password placeholder="输入新密码" />
      <template #footer>
        <el-button @click="resetDialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveResetPwd">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { userManagementApi } from '@/api/portal';
import { roleApi, organizationApi, orgTypeApi } from '@/api/system';
import { useAuthStore } from '@/stores/auth';
import type { Role } from '@/types/system';
import type { User } from '@/types/user';

interface AccountRow {
  id: string;
  name: string;
  roleNames: string[];
  roleIds: string[];
  orgNodeName: string;
  orgTypeName?: string;
  loginName: string;
  status: string;
  lastLogin: string;
}

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const PAGE_SIZE = 20;
const accounts = ref<AccountRow[]>([]);
const users = ref<User[]>([]);
const roles = ref<Role[]>([]);
const orgMap = ref<Map<string, { name: string; typeId: string }>>(new Map());
const orgTypeMap = ref<Map<string, string>>(new Map());
const loading = ref(false);
const searchText = ref('');
const roleCode = ref('');
const page = ref(1);
const total = ref(0);
const pageSize = PAGE_SIZE;

const selectedIds = ref<string[]>([]);
const batchDeleting = ref(false);
const saving = ref(false);

const bindDialog = ref(false);
const bindTarget = ref<AccountRow | null>(null);
const bindRoleIds = ref<string[]>([]);
const bindSaving = ref(false);

const resetDialog = ref(false);
const resetTarget = ref<AccountRow | null>(null);
const resetPassword = ref('');

async function loadMeta() {
  try {
    const [roleRes, orgRes, orgTypeRes] = await Promise.all([
      roleApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 1000 }),
      organizationApi.tree({ ...(tenantId.value ? { tenantId: tenantId.value } : {}) }),
      orgTypeApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 1000 })
    ]);
    roles.value = roleRes.items;
    const om = new Map<string, { name: string; typeId: string }>();
    const walk = (nodes: typeof orgRes.items) => {
      for (const n of nodes) {
        om.set(n.id, { name: n.name, typeId: n.typeId });
        if (n.children?.length) walk(n.children);
      }
    };
    walk(orgRes.items || []);
    orgMap.value = om;
    const tm = new Map<string, string>();
    (orgTypeRes.items || []).forEach((t) => tm.set(t.id, t.name));
    orgTypeMap.value = tm;
  } catch {
    /* 元数据加载失败不阻断列表 */
  }
}

async function load() {
  loading.value = true;
  try {
    const res = await userManagementApi.list({
      ...(tenantId.value ? { tenantId: tenantId.value } : {}),
      ...(searchText.value.trim() ? { search: searchText.value.trim() } : {}),
      ...(roleCode.value ? { roleCode: roleCode.value } : {}),
      limit: PAGE_SIZE,
      offset: (page.value - 1) * PAGE_SIZE
    });
    users.value = res.items;
    total.value = res.total ?? 0;
    accounts.value = res.items.map((u) => {
      const orgNode = u.orgNodeId ? orgMap.value.get(u.orgNodeId) : undefined;
      const orgTypeName = orgNode ? orgTypeMap.value.get(orgNode.typeId) : undefined;
      return {
        id: u.id,
        name: u.name,
        roleNames: u.roleNames ?? [],
        roleIds: u.roleIds ?? [],
        orgNodeName: orgNode?.name || '—',
        orgTypeName,
        loginName: u.username || u.loginName || '',
        status: u.status,
        lastLogin: u.lastLoginAt || '—'
      };
    });
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSelectionChange(rows: AccountRow[]) {
  selectedIds.value = rows.map((r) => r.id);
}

function onRoleChange() {
  page.value = 1;
  selectedIds.value = [];
  load();
}

function onSearch() {
  page.value = 1;
  selectedIds.value = [];
  load();
}

function roleName(id: string) {
  return roles.value.find((r) => r.id === id)?.name || id;
}

function openBindRoles(row: AccountRow) {
  bindTarget.value = row;
  bindRoleIds.value = [...row.roleIds];
  bindDialog.value = true;
}

async function saveBindRoles() {
  if (!bindTarget.value || !bindRoleIds.value.length) return;
  bindSaving.value = true;
  try {
    await userManagementApi.bindRoles(bindTarget.value.id, bindRoleIds.value);
    ElMessage.success('角色绑定成功');
    bindDialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '绑定失败');
  } finally {
    bindSaving.value = false;
  }
}

function openResetPwd(row: AccountRow) {
  resetTarget.value = row;
  resetPassword.value = '';
  resetDialog.value = true;
}

async function saveResetPwd() {
  if (!resetTarget.value || !resetPassword.value) {
    ElMessage.warning('请输入新密码');
    return;
  }
  saving.value = true;
  try {
    await userManagementApi.resetPassword(resetTarget.value.id, resetPassword.value);
    ElMessage.success('密码重置成功');
    resetDialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '重置失败');
  } finally {
    saving.value = false;
  }
}

async function toggleStatus(row: AccountRow) {
  const next = row.status === 'active' ? 'disabled' : 'active';
  try {
    await userManagementApi.updateStatus(row.id, next);
    ElMessage.success(next === 'active' ? '账户已启用' : '账户已禁用');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: AccountRow) {
  try {
    await ElMessageBox.confirm(`确定要删除账户「${row.name}」吗？此操作不可撤销。`, '确认删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  try {
    await userManagementApi.delete(row.id);
    ElMessage.success('删除成功');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

async function confirmBatchDelete() {
  if (!selectedIds.value.length) return;
  try {
    await ElMessageBox.confirm(`确定要删除选中的 ${selectedIds.value.length} 个账户吗？此操作不可撤销。`, '确认批量删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  batchDeleting.value = true;
  try {
    await userManagementApi.batchDelete(selectedIds.value);
    ElMessage.success(`成功删除 ${selectedIds.value.length} 个账户`);
    selectedIds.value = [];
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '批量删除失败');
  } finally {
    batchDeleting.value = false;
  }
}

onMounted(async () => {
  await loadMeta();
  load();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; margin-left: 8px; }
.filter-bar { margin-bottom: 12px; }
.tag { margin-right: 4px; }
.pagination { margin-top: 16px; justify-content: flex-end; }
.bind-tip { color: #909399; font-size: 13px; margin-bottom: 12px; }
.bind-tags { min-height: 32px; margin-top: 12px; display: flex; flex-wrap: wrap; gap: 6px; }
.bind-empty { color: #909399; font-size: 13px; }
.opt-sub { float: right; color: #c0c4cc; font-size: 12px; margin-left: 12px; }
</style>

// apps/edu/app/portal/apps/system/org-user/accounts/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { ComboboxSelect } from '@/components/shared/combobox-select'

import { usePortalUsers } from '@/hooks/use-portal-users'
import { useOrgTree } from '@/hooks/use-org-tree'
import { portalUserManagementApi } from '@/lib/api'
import { Badge } from '@/components/ui/badge'
import { useToast, StatusBadge } from '@zhiyu/ui'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { ResetPasswordDialog } from '@/components/shared/reset-password-dialog'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PaginationBar } from '@/components/shared/pagination-bar'
import {
  Search,
  Trash2,
  Loader2,
  AlertCircle,
  RotateCcw,
  Check,
  X,
  Users,
  KeyRound,
  Power,
} from 'lucide-react'

export default function AccountsPage() {
  const { toast } = useToast()
  const { tenantId } = usePortalAuth()
  const [searchText, setSearchText] = useState('')
  const { users, roles, total, page, pageSize, setPage, loading, error, refetch } = usePortalUsers({
    search: searchText || undefined,
  })
  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const { orgMap, orgTypeMap } = useOrgTree(tenantId)

  const [selectedAccounts, setSelectedAccounts] = useState<string[]>([])
  const [batchDeleting, setBatchDeleting] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; name: string } | null>(null)
  const [batchDeleteTarget, setBatchDeleteTarget] = useState<string[] | null>(null)

  const [bindTarget, setBindTarget] = useState<{ id: string; name: string } | null>(null)
  const [bindRoleIds, setBindRoleIds] = useState<string[]>([])
  const [bindSaving, setBindSaving] = useState(false)

  const [resetTarget, setResetTarget] = useState<{ id: string; name: string } | null>(null)

  const openBindDialog = (account: { id: string; name: string; roleIds: string[] }) => {
    setBindTarget({ id: account.id, name: account.name })
    setBindRoleIds(account.roleIds)
  }

  const handleBindRoles = async () => {
    if (!bindTarget || bindRoleIds.length === 0) return
    setBindSaving(true)
    try {
      await portalUserManagementApi.bindRoles(bindTarget.id, bindRoleIds)
      toast({ title: '角色绑定成功' })
      setBindTarget(null)
      await refetch()
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '绑定失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    } finally {
      setBindSaving(false)
    }
  }

  const handleResetPassword = (id: string, name: string) => {
    setResetTarget({ id, name })
  }

  const handleToggleStatus = async (id: string, currentStatus: string) => {
    const nextStatus = currentStatus === 'active' ? 'disabled' : 'active'
    try {
      await portalUserManagementApi.updateStatus(id, nextStatus)
      toast({ title: nextStatus === 'active' ? '账户已启用' : '账户已禁用' })
      await refetch()
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '操作失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    }
  }

  const handleDelete = (id: string, name: string) => {
    setDeleteTarget({ id, name })
  }

  const confirmDelete = async () => {
    if (!deleteTarget) return
    try {
      await portalUserManagementApi.delete(deleteTarget.id)
      toast({ title: '删除成功' })
      await refetch()
      setDeleteTarget(null)
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '删除失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    }
  }

  const toggleSelectAccount = (id: string) => {
    setSelectedAccounts((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id],
    )
  }

  const toggleSelectAll = () => {
    if (selectedAccounts.length === accounts.length && accounts.length > 0) {
      setSelectedAccounts([])
    } else {
      setSelectedAccounts(accounts.map((a) => a.id))
    }
  }

  const handleBatchDelete = () => {
    if (selectedAccounts.length === 0) return
    setBatchDeleteTarget([...selectedAccounts])
  }

  const confirmBatchDelete = async () => {
    if (!batchDeleteTarget || batchDeleteTarget.length === 0) return
    setBatchDeleting(true)
    try {
      await portalUserManagementApi.batchDelete(batchDeleteTarget)
      toast({ title: `成功删除 ${batchDeleteTarget.length} 个账户` })
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '批量删除失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    } finally {
      setBatchDeleting(false)
      setSelectedAccounts([])
      setBatchDeleteTarget(null)
    }
    await refetch()
  }

  const accounts = users.map((user) => {
    const orgNode = user.orgNodeId ? orgMap.get(user.orgNodeId) : undefined
    const orgTypeName = orgNode ? orgTypeMap.get(orgNode.typeId)?.name : undefined
    return {
      id: user.id,
      name: user.name,
      roleNames: user.roleNames ?? [],
      roleIds: user.roleIds ?? [],
      orgNodeName: orgNode?.name || '—',
      orgTypeName: orgTypeName || undefined,
      loginName: user.username || user.loginName || '',
      rawLoginName: user.loginName || '',
      status: user.status,
      lastLogin: user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString('zh-CN') : '—',
    }
  })

  return (
    <div className="min-h-full">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground">账户管理</h1>
          <p className="mt-1 text-sm text-muted-foreground">管理系统登录账户，绑定角色并维护账户状态</p>
        </div>
        <div className="flex items-center gap-2">
          {selectedAccounts.length > 0 && (
            <Button
              variant="destructive"
              size="sm"
              disabled={batchDeleting}
              onClick={handleBatchDelete}
            >
              {batchDeleting ? (
                <Loader2 className="h-4 w-4 animate-spin mr-1" />
              ) : (
                <Trash2 className="h-4 w-4 mr-1" />
              )}
              批量删除({selectedAccounts.length})
            </Button>
          )}
        </div>
      </div>

      <div className="mb-4">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="搜索姓名或账户..."
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            className="pl-9"
          />
        </div>
      </div>

      {error && (
        <div className="mb-4 rounded border border-destructive/20 bg-destructive/10 p-4 text-destructive flex items-start gap-3">
          <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="font-medium">加载失败</p>
            <p className="text-sm opacity-90">{error}</p>
          </div>
          <Button variant="outline" size="sm" onClick={refetch}>
            <RotateCcw className="h-4 w-4 mr-1" />
            重试
          </Button>
        </div>
      )}

      <div className="rounded-lg border border-gray-100 bg-white shadow-sm">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-12">
                <Checkbox
                  checked={selectedAccounts.length === accounts.length && accounts.length > 0}
                  onCheckedChange={toggleSelectAll}
                />
              </TableHead>
              <TableHead>姓名</TableHead>
              <TableHead>角色</TableHead>
              <TableHead>所属组织</TableHead>
              <TableHead>账户登录名</TableHead>
              <TableHead>状态</TableHead>
              <TableHead>最后登录时间</TableHead>
              <TableHead className="w-24 text-center">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={9} className="text-center py-12">
                  <Loader2 className="h-6 w-6 animate-spin mx-auto text-muted-foreground" />
                  <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
                </TableCell>
              </TableRow>
            ) : accounts.length === 0 ? (
              <TableRow>
                <TableCell colSpan={9} className="text-center text-muted-foreground py-12">
                  {searchText ? '未找到匹配的账户' : '暂无账户数据'}
                </TableCell>
              </TableRow>
            ) : (
              accounts.map((account) => (
                <TableRow key={account.id} className="group">
                  <TableCell>
                    <Checkbox
                      checked={selectedAccounts.includes(account.id)}
                      onCheckedChange={() => toggleSelectAccount(account.id)}
                    />
                  </TableCell>
                  <TableCell className="font-medium">{account.name}</TableCell>
                  <TableCell>
                    <div className="flex flex-wrap gap-1">
                      {account.roleNames.length > 0 ? (
                        account.roleNames.map((rn) => (
                          <span
                            key={rn}
                            className="px-2 py-1 rounded text-xs bg-primary/10 text-primary"
                          >
                            {rn}
                          </span>
                        ))
                      ) : (
                        <span className="text-muted-foreground">—</span>
                      )}
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      <span>{account.orgNodeName}</span>
                      {account.orgTypeName && (
                        <span className="px-1.5 py-0.5 rounded text-[10px] bg-muted text-muted-foreground">
                          {account.orgTypeName}
                        </span>
                      )}
                    </div>
                  </TableCell>
                  <TableCell>{account.loginName}</TableCell>
                  <TableCell>
                    <StatusBadge status={account.status} />
                  </TableCell>
                  <TableCell className="text-muted-foreground">{account.lastLogin}</TableCell>
                  <TableRowActions>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2 text-xs"
                      onClick={() => openBindDialog(account)}
                    >
                      <Users className="mr-1 h-3 w-3" />
                      绑定角色
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2 text-xs"
                      onClick={() => handleResetPassword(account.id, account.name)}
                    >
                      <KeyRound className="mr-1 h-3 w-3" />
                      重置密码
                    </Button>
                    {account.status === 'active' ? (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                        onClick={() => handleToggleStatus(account.id, account.status)}
                      >
                        <Power className="mr-1 h-3 w-3" />
                        禁用账户
                      </Button>
                    ) : (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs text-emerald-600 hover:text-emerald-700"
                        onClick={() => handleToggleStatus(account.id, account.status)}
                      >
                        <Power className="mr-1 h-3 w-3" />
                        启用账户
                      </Button>
                    )}
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                      onClick={() => handleDelete(account.id, account.name)}
                    >
                      <Trash2 className="mr-1 h-3 w-3" />
                      删除
                    </Button>
                  </TableRowActions>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      {total > 0 && (
        <div className="mt-4 flex items-center justify-between">
          <span className="text-sm text-muted-foreground">共 {total} 条记录</span>
          <PaginationBar page={page} totalPages={totalPages} onPageChange={setPage} />
        </div>
      )}

      <Dialog
        open={!!bindTarget}
        onOpenChange={(open) => {
          if (!open) setBindTarget(null)
        }}
      >
        <DialogContent size="sm">
          <DialogHeader>
            <DialogTitle>绑定角色 - {bindTarget?.name}</DialogTitle>
            <DialogDescription>
              为用户绑定 1 个或多个角色，用户登录后可在顶栏切换当前角色
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3 py-2">
            <ComboboxSelect
              multiple
              value={bindRoleIds}
              onChange={setBindRoleIds}
              options={roles.map((r) => ({ value: r.id, label: r.name }))}
              placeholder="搜索并选择角色..."
              searchPlaceholder="搜索角色名称或编码..."
              emptyText="未找到角色"
              className="w-full"
              renderOption={(o, selected) => (
                <>
                  <span className="flex-1">{o.label}</span>
                  <span className="mr-2 font-mono text-xs text-muted-foreground">
                    {roles.find((r) => r.id === o.value)?.code}
                  </span>
                  {selected && <Check className="h-4 w-4 text-primary" />}
                </>
              )}
            />

            <div className="flex min-h-8 flex-wrap gap-1.5">
              {bindRoleIds.map((id) => {
                const r = roles.find((x) => x.id === id)
                if (!r) return null
                return (
                  <Badge key={id} variant="secondary" className="gap-1">
                    {r.name}
                    <button
                      type="button"
                      onClick={() => setBindRoleIds((prev) => prev.filter((i) => i !== id))}
                      className="ml-0.5 rounded-full hover:text-destructive"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </Badge>
                )
              })}
              {bindRoleIds.length === 0 && (
                <span className="text-sm text-muted-foreground">至少需要绑定一个角色</span>
              )}
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setBindTarget(null)} disabled={bindSaving}>
              取消
            </Button>
            <Button onClick={handleBindRoles} disabled={bindSaving || bindRoleIds.length === 0}>
              {bindSaving ? <Loader2 className="mr-1 h-4 w-4 animate-spin" /> : null}
              保存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ResetPasswordDialog
        open={!!resetTarget}
        onOpenChange={(open) => {
          if (!open) setResetTarget(null)
        }}
        userId={resetTarget?.id}
        userName={resetTarget?.name}
        onSuccess={async () => {
          toast({ title: '密码重置成功' })
          await refetch()
        }}
      />

      <ConfirmDialog
        open={deleteTarget !== null}
        onOpenChange={(open) => {
          if (!open) setDeleteTarget(null)
        }}
        title="确认删除"
        description={`确定要删除账户「${deleteTarget?.name}」吗？此操作不可撤销。`}
        variant="destructive"
        onConfirm={confirmDelete}
      />

      <ConfirmDialog
        open={batchDeleteTarget !== null}
        onOpenChange={(open) => {
          if (!open) setBatchDeleteTarget(null)
        }}
        title="确认批量删除"
        description={`确定要删除选中的 ${batchDeleteTarget?.length || 0} 个账户吗？此操作不可撤销。`}
        variant="destructive"
        onConfirm={confirmBatchDelete}
      />
    </div>
  )
}
