// apps/edu/app/lesson/admin/_components/ability/ability-point-selector.tsx
'use client'

import { useState, useMemo } from 'react'
import { Search, Plus, X, Award } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { cn } from '@/lib/utils'

export interface AbilityPointItem {
  id: string
  name: string
  code?: string
  description?: string
}

interface AbilityPointSelectorProps {
  selected: AbilityPointItem[]
  pool: AbilityPointItem[]
  onChange?: (selected: AbilityPointItem[]) => void
  onAddCustom?: (name: string, description?: string) => void
}

export function AbilityPointSelector({
  selected,
  pool,
  onChange,
  onAddCustom,
}: AbilityPointSelectorProps) {
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [newName, setNewName] = useState('')
  const [newDesc, setNewDesc] = useState('')
  const [adding, setAdding] = useState(false)

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    if (!q) return pool
    return pool.filter(
      (ap) =>
        (ap.name || '').toLowerCase().includes(q) ||
        (ap.code || '').toLowerCase().includes(q) ||
        (ap.description || '').toLowerCase().includes(q),
    )
  }, [pool, search])

  const toggle = (ap: AbilityPointItem) => {
    const exists = selected.find((s) => s.id === ap.id)
    if (exists) {
      onChange?.(selected.filter((s) => s.id !== ap.id))
    } else {
      onChange?.([...selected, ap])
    }
  }

  const handleAddCustom = () => {
    if (!newName.trim()) return
    onAddCustom?.(newName.trim(), newDesc.trim())
    setNewName('')
    setNewDesc('')
    setAdding(false)
  }

  return (
    <div className="space-y-3">
      {selected.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {selected.map((ap) => (
            <Badge key={ap.id} variant="secondary" className="flex items-center gap-1 px-2 py-1">
              <Award className="h-3 w-3" />
              <span>{ap.name}</span>
              <button onClick={() => toggle(ap)} className="ml-1 rounded-full hover:bg-muted p-0.5">
                <X className="h-3 w-3" />
              </button>
            </Badge>
          ))}
        </div>
      )}
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <Button variant="outline" size="sm" className="text-xs h-9">
            <Award className="h-3.5 w-3.5 mr-1.5" />
            {selected.length > 0 ? '调整能力点' : '关联能力点'}
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-lg max-h-[85vh] flex flex-col">
          <DialogHeader>
            <DialogTitle>关联能力点</DialogTitle>
          </DialogHeader>
          <div className="relative my-2">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="搜索能力点名称、编码、描述"
              className="pl-9 text-sm h-9"
            />
          </div>
          <div className="flex-1 min-h-0 overflow-y-auto space-y-2 pr-1">
            {filtered.length === 0 && !adding && (
              <p className="text-sm text-gray-400 text-center py-4">未找到匹配的能力点</p>
            )}
            {filtered.map((ap) => {
              const isSelected = selected.some((s) => s.id === ap.id)
              return (
                <button
                  key={ap.id}
                  onClick={() => toggle(ap)}
                  className={cn(
                    'w-full text-left p-3 rounded-lg border transition-all flex items-start gap-3',
                    isSelected
                      ? 'border-primary bg-primary/5 ring-1 ring-primary/20'
                      : 'border-gray-200 hover:border-primary/40 bg-white',
                  )}
                >
                  <div
                    className={cn(
                      'w-5 h-5 rounded border flex items-center justify-center shrink-0 mt-0.5',
                      isSelected ? 'bg-primary border-primary' : 'border-gray-300',
                    )}
                  >
                    {isSelected && <span className="text-white text-xs">✓</span>}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">{ap.name}</p>
                    {ap.code && <p className="text-[10px] text-gray-400">{ap.code}</p>}
                    {ap.description && (
                      <p className="text-xs text-gray-500 truncate mt-0.5">{ap.description}</p>
                    )}
                  </div>
                </button>
              )
            })}
          </div>
          {adding ? (
            <div className="space-y-2 py-2 border-t">
              <Label className="text-xs">新增能力点</Label>
              <Input
                value={newName}
                onChange={(e) => setNewName(e.target.value)}
                placeholder="名称"
                className="h-9 text-sm"
              />
              <Input
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                placeholder="描述（可选）"
                className="h-9 text-sm"
              />
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => setAdding(false)}
                >
                  取消
                </Button>
                <Button
                  size="sm"
                  className="text-xs"
                  onClick={handleAddCustom}
                  disabled={!newName.trim()}
                >
                  添加
                </Button>
              </div>
            </div>
          ) : (
            onAddCustom && (
              <Button
                variant="ghost"
                size="sm"
                className="text-xs mt-2"
                onClick={() => setAdding(true)}
              >
                <Plus className="h-3.5 w-3.5 mr-1" />
                自定义能力点
              </Button>
            )
          )}
          <DialogFooter>
            <Button size="sm" onClick={() => setOpen(false)}>
              完成
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/portal-vue/src/views/lesson/ability-point-selector.vue
<template>
  <div class="ability-selector">
    <div v-if="selected.length > 0" class="selected-tags">
      <el-tag v-for="ap in selected" :key="ap.id" type="primary" effect="plain" closable class="ap-tag" @close="toggle(ap)">
        {{ ap.name }}
      </el-tag>
    </div>
    <el-button plain size="small" class="trigger-btn" @click="open = true">
      <el-icon><Award /></el-icon>
      {{ selected.length > 0 ? '调整能力点' : '关联能力点' }}
    </el-button>

    <el-dialog v-model="open" title="关联能力点" width="520px" append-to-body destroy-on-close>
      <el-input v-model="search" placeholder="搜索能力点名称、编码、描述" clearable class="search-input">
        <template #prefix><el-icon><Search /></el-icon></template>
      </el-input>
      <div class="list">
        <el-empty v-if="filtered.length === 0 && !adding" description="未找到匹配的能力点" :image-size="56" />
        <div
          v-for="ap in filtered"
          :key="ap.id"
          class="ap-item"
          :class="{ selected: isSelected(ap.id) }"
          @click="toggle(ap)"
        >
          <el-icon class="ap-check" :color="isSelected(ap.id) ? '#409eff' : '#c0c4cc'">
            <CircleCheck v-if="isSelected(ap.id)" />
            <CircleCheckFilled v-else class="unchecked" />
          </el-icon>
          <div class="ap-info">
            <p class="ap-name">{{ ap.name }}</p>
            <p v-if="ap.code" class="ap-code">{{ ap.code }}</p>
            <p v-if="ap.description" class="ap-desc">{{ ap.description }}</p>
          </div>
        </div>
      </div>

      <template v-if="adding">
        <div class="add-form">
          <p class="add-title">新增能力点</p>
          <el-input v-model="newName" placeholder="名称" class="add-input" />
          <el-input v-model="newDesc" placeholder="描述（可选）" class="add-input" />
          <div class="add-actions">
            <el-button size="small" @click="adding = false">取消</el-button>
            <el-button size="small" type="primary" :disabled="!newName.trim()" @click="handleAddCustom">添加</el-button>
          </div>
        </div>
      </template>
      <el-button v-else link type="primary" size="small" class="custom-btn" @click="adding = true">
        <el-icon><Plus /></el-icon> 自定义能力点
      </el-button>

      <template #footer>
        <el-button type="primary" @click="open = false">完成</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import type { AbilityPointItem } from './lesson-edit-utils';

const props = defineProps<{
  selected: AbilityPointItem[];
  pool: AbilityPointItem[];
}>();

const emit = defineEmits<{
  (e: 'change', selected: AbilityPointItem[]): void;
  (e: 'addCustom', name: string, description?: string): void;
}>();

const open = ref(false);
const search = ref('');
const newName = ref('');
const newDesc = ref('');
const adding = ref(false);

const filtered = computed(() => {
  const q = search.value.trim().toLowerCase();
  if (!q) return props.pool;
  return props.pool.filter(
    (ap) =>
      (ap.name || '').toLowerCase().includes(q) ||
      (ap.code || '').toLowerCase().includes(q) ||
      (ap.description || '').toLowerCase().includes(q)
  );
});

function isSelected(id: string): boolean {
  return props.selected.some((s) => s.id === id);
}

function toggle(ap: AbilityPointItem) {
  const exists = isSelected(ap.id);
  if (exists) {
    emit('change', props.selected.filter((s) => s.id !== ap.id));
  } else {
    emit('change', [...props.selected, ap]);
  }
}

function handleAddCustom() {
  if (!newName.value.trim()) return;
  emit('addCustom', newName.value.trim(), newDesc.value.trim());
  newName.value = '';
  newDesc.value = '';
  adding.value = false;
}
</script>

<style scoped>
.selected-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 8px;
}
.ap-tag {
  font-weight: normal;
}
.trigger-btn {
  font-size: 12px;
}
.search-input {
  margin-bottom: 10px;
}
.list {
  max-height: 320px;
  overflow-y: auto;
}
.ap-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  padding: 10px 12px;
  border-radius: 8px;
  border: 1px solid #e4e7ed;
  margin-bottom: 8px;
  cursor: pointer;
  transition: all 0.15s;
}
.ap-item:hover {
  border-color: #a0cfff;
}
.ap-item.selected {
  border-color: #409eff;
  background: #ecf5ff;
}
.ap-check {
  margin-top: 2px;
  flex-shrink: 0;
}
.ap-check .unchecked {
  color: #dcdfe6;
}
.ap-info {
  flex: 1;
  min-width: 0;
}
.ap-name {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
  margin: 0;
}
.ap-code {
  font-size: 10px;
  color: #c0c4cc;
  margin: 2px 0 0;
}
.ap-desc {
  font-size: 12px;
  color: #909399;
  margin: 4px 0 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.add-form {
  border-top: 1px solid #ebeef5;
  padding-top: 12px;
  margin-top: 8px;
}
.add-title {
  font-size: 12px;
  color: #606266;
  margin: 0 0 8px;
}
.add-input {
  margin-bottom: 8px;
}
.add-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.custom-btn {
  margin-top: 8px;
}
</style>
