// apps/edu/app/lesson/admin/archive/page.tsx
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

import { courseApi, lessonBatchApi } from '@/lib/api'
import type { Course, LessonBatch } from '@/lib/types/lesson'

import { useToast, StatusBadge } from '@zhiyu/ui'
import { ArchiveListPage, type ArchiveColumn } from '@/components/shared/archive-list-page'

export default function LessonArchivePage() {
  const { toast } = useToast()
  const [courses, setCourses] = useState<Course[]>([])
  const [batches, setBatches] = useState<LessonBatch[]>([])
  const [loading, setLoading] = useState(false)
  const [search, setSearch] = useState('')
  const [selectedMajor, setSelectedMajor] = useState<string | null>(null)

  const loadData = useCallback(async () => {
    setLoading(true)
    try {
      const [courseRes, batchRes] = await Promise.all([
        courseApi.list({ status: 'archived', limit: 1000 }),
        lessonBatchApi.list({ limit: 1000 }),
      ])
      setCourses(courseRes.items)
      setBatches(batchRes.items)
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: '加载失败',
        description: err.message || '无法获取归档数据',
      })
    } finally {
      setLoading(false)
    }
  }, [toast])

  useEffect(() => {
    ;(async () => {
      await loadData()
    })()
  }, [loadData])

  const majors = useMemo(() => {
    const set = new Set<string>()
    courses.forEach((c) => {
      if (c.majorName) set.add(c.majorName)
    })
    return Array.from(set).sort()
  }, [courses])

  const filtered = useMemo(() => {
    let result = courses
    if (selectedMajor) {
      result = result.filter((c) => c.majorName === selectedMajor)
    }
    if (search.trim()) {
      const q = search.toLowerCase()
      result = result.filter(
        (c) =>
          c.name.toLowerCase().includes(q) ||
          (c.code || '').toLowerCase().includes(q) ||
          (c.majorName || '').toLowerCase().includes(q) ||
          (c.category || '').toLowerCase().includes(q),
      )
    }
    return result
  }, [courses, selectedMajor, search])

  const batchMap = useMemo(() => new Map(batches.map((b) => [b.id, b])), [batches])

  const handleRestore = async (course: Course) => {
    try {
      await courseApi.saveDraft(course.id)
      await loadData()
      toast({ title: '已恢复' })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: '恢复失败',
        description: err.message || '请稍后重试',
      })
    }
  }

  const editHref = (type: Course['type'], id: string) => {
    if (type === 'system') return `/lesson/admin/system/add?id=${id}`
    if (type === 'granular') return `/lesson/admin/granular/add?id=${id}`
    return `/lesson/admin/hybrid/add?id=${id}`
  }

  const columns: ArchiveColumn<Course>[] = [
    {
      header: '课程名称',
      cell: (course) => (
        <div>
          <span className="font-medium">{course.name}</span>
          <p className="text-xs text-muted-foreground">
            {course.category || '-'} · {course.majorName || '-'}
          </p>
        </div>
      ),
    },
    {
      header: '课程编码',
      cell: (course) => <span className="text-sm text-muted-foreground">{course.code}</span>,
    },
    {
      header: '课程类型',
      cell: (course) => (
        <span className="text-sm">
          {course.type === 'system' ? '体系课' : course.type === 'granular' ? '颗粒课' : '混合课'}
        </span>
      ),
    },
    {
      header: '版本',
      cell: (course) => <span className="text-sm">{course.version || '-'}</span>,
    },
    {
      header: '适用专业',
      cell: (course) => <span className="text-sm">{course.majorName || '-'}</span>,
    },
    {
      header: '所属批次分组',
      cell: (course) => (
        <span className="text-sm">
          {course.batchId ? batchMap.get(course.batchId)?.name || course.batchId : '-'}
        </span>
      ),
    },
    {
      header: '归档时间',
      cell: (course) => (
        <span className="text-sm text-muted-foreground">
          {new Date(course.updatedAt).toLocaleDateString()}
        </span>
      ),
    },
  ]

  const renderStatus = (course: Course) => <StatusBadge status={course.status} />

  return (
    <ArchiveListPage
      entityLabel="课程"
      pageTitle="课程历史档案库"
      pageDescription="查看已归档的课程记录，支持恢复为草稿继续编辑"
      sidebarTitle="按专业归档"
      sidebarItems={majors.map((m) => ({ id: m, name: m }))}
      sidebarSelectedId={selectedMajor}
      onSidebarSelect={setSelectedMajor}
      items={filtered}
      loading={loading}
      onRestore={handleRestore}
      detailHref={(item) => editHref(item.type, item.id)}
      searchPlaceholder="搜索课程名称 / 编码 / 专业 / 分类"
      searchValue={search}
      onSearchChange={setSearch}
      columns={columns}
      renderStatus={renderStatus}
    />
  )
}

// frontend/portal-vue/src/views/lesson/archive.vue
<template>
  <!-- 对齐 React frontend/edu/app/lesson/admin/archive/page.tsx（ArchiveListPage 用法） -->
  <ArchiveListPage
    entity-label="课程"
    page-title="课程历史档案库"
    page-description="查看已归档的课程记录，支持恢复为草稿继续编辑"
    sidebar-title="按专业归档"
    :sidebar-items="majors"
    :sidebar-selected-id="selectedMajor"
    :on-sidebar-select="onSidebarSelect"
    :items="filtered"
    :loading="loading"
    :on-restore="restore"
    :detail-href="detailHref"
    search-placeholder="搜索课程名称 / 编码 / 专业 / 分类"
    :search-value="search"
    :on-search-change="onSearchChange"
    :columns="columns"
    :render-status="renderStatus"
  />
</template>

<script setup lang="ts">
import { computed, h, onMounted, ref, type VNode } from 'vue';
import { ElMessage } from 'element-plus';
import ArchiveListPage from '@/components/archive-list-page.vue';
import { fetchAllPages } from '@/components/common/content-list-page.types';
import { courseApi, lessonBatchApi } from '@/api/lesson';
import type { Course } from '@/types/lesson';

type Row = Record<string, any>;

// 与 archive-list-page.vue 的 ArchiveColumn 结构保持一致（避免跨 .vue 类型导入的复杂度）。
interface ArchiveColumn {
  label: string;
  prop?: string;
  width?: string | number;
  minWidth?: string | number;
  formatter?: (row: Row) => string;
  cell?: (row: Row) => VNode | string;
}

// ─── 数据加载：全量拉取归档课程 + 全量批次（对齐 React archive/page.tsx） ──────
const courses = ref<Course[]>([]);
const batches = ref<any[]>([]);
const loading = ref(false);

const search = ref('');
const selectedMajor = ref<string | null>(null);

async function loadData() {
  loading.value = true;
  try {
    const [courseRes, batchRes] = await Promise.all([
      fetchAllPages<Course>((page, pageSize) =>
        courseApi.list({ status: 'archived', limit: pageSize, offset: page * pageSize })
      ),
      fetchAllPages<any>((page, pageSize) =>
        lessonBatchApi.list({ limit: pageSize, offset: page * pageSize })
      )
    ]);
    courses.value = courseRes;
    batches.value = batchRes;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

onMounted(loadData);

// ─── 专业侧栏 / 过滤（对齐 React：按 majorName 归类去重排序） ─────────────────
const majors = computed(() => {
  const set = new Set<string>();
  for (const c of courses.value) {
    if (c.majorName) set.add(c.majorName);
  }
  return Array.from(set)
    .sort()
    .map((name) => ({ id: name, name }));
});

function onSidebarSelect(id: string | null) {
  selectedMajor.value = id;
}

function onSearchChange(value: string) {
  search.value = value;
}

const filtered = computed<Course[]>(() => {
  let result = courses.value;
  if (selectedMajor.value) {
    result = result.filter((c) => c.majorName === selectedMajor.value);
  }
  const q = search.value.trim().toLowerCase();
  if (q) {
    result = result.filter(
      (c) =>
        (c.name || '').toLowerCase().includes(q) ||
        (c.code || '').toLowerCase().includes(q) ||
        (c.majorName || '').toLowerCase().includes(q) ||
        (c.category || '').toLowerCase().includes(q)
    );
  }
  return result;
});

const batchMap = computed(() => new Map(batches.value.map((b) => [b.id, b])));

function formatDate(value?: string): string {
  if (!value) return '-';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '-';
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

const COURSE_TYPE_TEXT: Record<string, string> = {
  system: '体系课',
  granular: '颗粒课',
  hybrid: '混合课'
};

function courseTypeText(type?: string): string {
  return type ? COURSE_TYPE_TEXT[type] || '混合课' : '混合课';
}

// 对齐 React StatusBadge（archived → 已归档）
const STATUS_LABELS: Record<string, string> = {
  draft: '草稿',
  pending: '审核中',
  approved: '已通过',
  rejected: '已驳回',
  published: '已发布',
  archived: '已归档'
};

function renderStatus(row: Row): string {
  return STATUS_LABELS[String(row.status)] || String(row.status ?? '-');
}

// ─── 列定义（对齐 React：名称/编码/类型/版本/专业/批次/归档时间） ─────────────
const columns = computed<ArchiveColumn[]>(() => [
  {
    label: '课程名称',
    minWidth: 200,
    cell: (row: Row) =>
      h('div', { style: 'max-width:200px;overflow:hidden;' }, [
        h(
          'span',
          {
            style:
              'display:block;font-weight:500;color:#303133;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;'
          },
          String(row.name ?? '')
        ),
        h(
          'p',
          {
            style:
              'margin:2px 0 0;font-size:12px;color:#909399;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;'
          },
          `${row.category || '-'} · ${row.majorName || '-'}`
        )
      ])
  },
  {
    label: '课程编码',
    prop: 'code',
    width: 120
  },
  {
    label: '课程类型',
    width: 100,
    formatter: (row: Row) => courseTypeText(row.type)
  },
  {
    label: '版本',
    prop: 'version',
    width: 80
  },
  {
    label: '适用专业',
    width: 120,
    formatter: (row: Row) => row.majorName || '-'
  },
  {
    label: '所属批次分组',
    width: 140,
    formatter: (row: Row) =>
      row.batchId ? (batchMap.value.get(row.batchId)?.name as string) || String(row.batchId) : '-'
  },
  {
    label: '归档时间',
    width: 120,
    formatter: (row: Row) => formatDate(row.updatedAt)
  }
]);

// ─── 操作（对齐 React：查看跳编辑页 / saveDraft 恢复为草稿） ──────────────────
function editHref(type: string | undefined, id: string): string {
  if (type === 'system') return `/lesson/admin/system/add?id=${id}`;
  if (type === 'granular') return `/lesson/admin/granular/add?id=${id}`;
  return `/lesson/admin/hybrid/add?id=${id}`;
}

function detailHref(item: Row): string {
  return editHref(item.type as string | undefined, String(item.id));
}

async function restore(item: Row) {
  try {
    await courseApi.saveDraft(String(item.id));
    ElMessage.success('已恢复');
    await loadData();
  } catch (e) {
    ElMessage.error((e as Error).message || '恢复失败');
  }
}
</script>
