// frontend/edu/app/portal/apps/alliance/agreements/page.tsx
'use client'

import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { DateInput } from '@/components/shared/date-input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'
import { Pencil, Trash2, ExternalLink } from 'lucide-react'
import { Link } from 'react-router'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceAgreementApi, allianceEnterpriseApi, allianceProjectApi } from '@/lib/api'
import { listAll } from '@zhiyu/api-client'
import { useToast, useAsync } from '@zhiyu/ui'
import { usePagedList } from '@/hooks/use-paged-list'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { FormFieldRow, FormFieldGrid } from '@/components/shared/form-field-row'
import { formatDate } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import { useAllianceDictionary, mergeDictOptions } from '@/lib/alliance-dicts'
import type { AllianceAgreement } from '@/lib/types'

export default function AllianceAgreementsPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()
  const { items: typeItems } = useAllianceDictionary('agreement_type', tenantId)
  const { items: statusItems } = useAllianceDictionary('agreement_status', tenantId)
  const { data: refsData } = useAsync(
    async () => {
      if (!tenantId) return { enterprises: [], projects: [] }
      const [ents, projs] = await Promise.all([
        // 全量拉取企业/项目列表，避免 limit 截断导致名称解析退化为原始 id
        listAll((page, pageSize) =>
          allianceEnterpriseApi.list({ limit: pageSize, offset: page * pageSize }),
        ),
        listAll((page, pageSize) =>
          allianceProjectApi.list({ limit: pageSize, offset: page * pageSize }),
        ),
      ])
      return { enterprises: ents, projects: projs }
    },
    { deps: [tenantId, authLoading], onError: () => true },
  )
  const { enterprises, projects } = refsData ?? { enterprises: [], projects: [] }

  // 服务端分页列表
  const list = usePagedList(
    async ({ page, limit, search }) => {
      if (!tenantId) return { items: [], total: 0 }
      const data = await allianceAgreementApi.list({ page, limit, search })
      return { items: data.items || [], total: data.total }
    },
    [tenantId, authLoading],
  )
  const items = list.items

  return (
    <PortalCrudPage
      title={t('合作协议管理')}
      description={t('管理校企合作协议的独立记录')}
      entityLabel={t('合作协议')}
      searchPlaceholder={t('搜索协议名称...')}
      createButtonLabel={t('新建协议')}
      items={items}
      loading={list.loading}
      error={list.error?.message ?? null}
      onRetry={list.refresh}
      searchValue={list.search}
      onSearchChange={(v: string) => {
        list.setSearch(v)
        list.setPage(1)
      }}
      pagination={list.pagination}
      importConfig={{
        importType: 'alliance-agreements',
        entityLabel: t('合作协议'),
        templateFileName: t('合作协议批量导入模板.xlsx'),
      }}
      createHref="/portal/apps/alliance/agreements/new"
      colSpan={6}
      renderTableHeader={() => (
        <>
          <TableHead>{t('协议名称')}</TableHead>
          <TableHead>{t('合作企业')}</TableHead>
          <TableHead>{t('关联项目')}</TableHead>
          <TableHead>{t('生效日期')}</TableHead>
          <TableHead>{t('到期日期')}</TableHead>
          <TableHead>{t('操作')}</TableHead>
        </>
      )}
      renderTableRow={(item: any, actions: any) => {
        const entIds: string[] = (item.enterpriseIds || []).map(String)
        const entNames =
          entIds.length > 0
            ? entIds
                .map((eid) => (enterprises ?? []).find((e) => e.id === eid)?.name || eid)
                .join('、')
            : '-'
        const expiring =
          item.endDate &&
          (() => {
            const days = (new Date(item.endDate).getTime() - Date.now()) / 86400000
            return days >= 0 && days <= 90
          })()
        return (
          <>
            <TableCell className="font-medium">
              <Link
                to={`/portal/apps/alliance/agreements/${item.id}`}
                className="hover:underline"
              >
                {item.name}
              </Link>
            </TableCell>
            <TableCell className="max-w-[160px] truncate" title={entNames}>
              {entNames}
            </TableCell>
            <TableCell>
              {(item.projectIds || []).length > 0
                ? (projects ?? []).find((p) => p.id === (item.projectIds || [])[0])?.name || '-'
                : '-'}
            </TableCell>
            <TableCell>{formatDate(item.startDate)}</TableCell>
            <TableCell className={expiring ? 'text-amber-600 font-medium' : ''}>
              {formatDate(item.endDate)}
              {expiring && <span className="ml-1 text-xs">{t('（即将到期）')}</span>}
            </TableCell>
            <TableRowActions>
              <Link to={`/portal/apps/alliance/agreements/${item.id}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="h-3.5 w-3.5 mr-1" />
                  {t('查看')}
                </Button>
              </Link>
              <Link to={`/portal/apps/alliance/agreements/${item.id}/edit`}>
                <Button variant="ghost" size="sm">
                  <Pencil className="h-3.5 w-3.5 mr-1" />
                  {t('编辑')}
                </Button>
              </Link>
              <Button variant="ghost" size="sm" className="text-red-600" onClick={actions.delete}>
                <Trash2 className="h-3.5 w-3.5 mr-1" />
                {t('删除')}
              </Button>
            </TableRowActions>
          </>
        )
      }}
      createDefault={() =>
        ({
          id: '',
          name: '',
          type: '',
          status: 'draft',
          startDate: '',
          endDate: '',
          content: '',
          enabled: true as any,
          createdAt: '',
          updatedAt: '',
        }) as AllianceAgreement & { enabled?: boolean }
      }
      renderForm={(item: any, setItem: any) => (
        <div className="space-y-4">
          <FormFieldRow label={t('协议名称')} required>
            <Input
              value={item.name || ''}
              onChange={(e: any) => setItem({ ...item, name: e.target.value })}
            />
          </FormFieldRow>
          <FormFieldRow label={t('协议类型')}>
            <Select
              value={item.type || ''}
              onValueChange={(v: any) => setItem({ ...item, type: v })}
            >
              <SelectTrigger>
                <SelectValue placeholder={t('请选择协议类型')} />
              </SelectTrigger>
              <SelectContent>
                {mergeDictOptions(typeItems, item.type).map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {t(opt.label)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldRow label={t('状态')}>
            <Select
              value={item.status || 'draft'}
              onValueChange={(v: any) => setItem({ ...item, status: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {mergeDictOptions(statusItems, item.status || 'draft').map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {t(opt.label)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldGrid>
            <FormFieldRow label={t('开始日期')}>
              <DateInput
                type="date"
                value={item.startDate || ''}
                onChange={(e: any) => setItem({ ...item, startDate: e.target.value })}
              />
            </FormFieldRow>
            <FormFieldRow label={t('结束日期')}>
              <DateInput
                type="date"
                value={item.endDate || ''}
                onChange={(e: any) => setItem({ ...item, endDate: e.target.value })}
              />
            </FormFieldRow>
          </FormFieldGrid>
          <FormFieldRow label={t('协议内容')}>
            <Textarea
              value={item.content || ''}
              onChange={(e: any) => setItem({ ...item, content: e.target.value })}
              rows={4}
            />
          </FormFieldRow>
          <div className="flex items-center gap-2">
            <Switch
              checked={!!item.isPublic}
              onCheckedChange={(v: any) => setItem({ ...item, isPublic: v })}
            />
            <Label>{t('前台展示')}</Label>
          </div>
        </div>
      )}
      getDeleteDescription={(item: any) => (
        <>{t('确定要删除协议「{name}」吗？', { name: item.name })}</>
      )}
      onSave={async (item: any, isEdit: boolean) => {
        if (isEdit) {
          await allianceAgreementApi.update(item.id, item)
        } else {
          await allianceAgreementApi.create(item)
        }
        toast({ title: t('协议已{action}', { action: isEdit ? t('更新') : t('创建') }) })
        await list.refresh()
      }}
      onDelete={async (item: any) => {
        await allianceAgreementApi.delete(item.id)
        toast({ title: t('协议已删除') })
        await list.refresh()
      }}
    />
  )
}

// plus-ui/src-portal/views/portal/apps/alliance/agreements.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div>
        <h1 class="page-title">合作协议管理</h1>
        <p class="page-sub">管理校企合作协议的独立记录</p>
      </div>
      <div>
        <el-button style="margin-right: 8px" @click="importDialog = true">批量导入</el-button>
        <el-button type="primary" @click="router.push('/portal/apps/alliance/agreements/new')">
          <el-icon><Plus /></el-icon>
          新建协议
        </el-button>
      </div>
    </div>

    <el-card shadow="never">
      <el-input
        v-model="search"
        placeholder="搜索协议名称..."
        clearable
        style="max-width: 320px; margin-bottom: 12px"
        @input="onSearch"
        @clear="onSearch"
      />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="协议名称" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" @click="router.push(`/portal/apps/alliance/agreements/${row.id}`)">
              {{ row.name }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="合作企业" min-width="160" show-overflow-tooltip>
          <template #default="{ row }">{{ enterpriseNames(row) }}</template>
        </el-table-column>
        <el-table-column label="关联项目" min-width="140" show-overflow-tooltip>
          <template #default="{ row }">{{ projectName(row) }}</template>
        </el-table-column>
        <el-table-column label="生效日期" width="120">
          <template #default="{ row }">{{ formatDate(row.startDate) }}</template>
        </el-table-column>
        <el-table-column label="到期日期" width="160">
          <template #default="{ row }">
            <span :class="{ 'expiring': isExpiring(row.endDate) }">{{ formatDate(row.endDate) }}</span>
            <span v-if="isExpiring(row.endDate)" class="expiring-hint">（即将到期）</span>
          </template>
        </el-table-column>
        <el-table-column label="前台展示" width="100">
          <template #default="{ row }">
            <el-switch :model-value="row.isPublic || false" @change="togglePublic(row)" />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/agreements/${row.id}`)">查看</el-button>
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/agreements/${row.id}/edit`)">编辑</el-button>
            <el-button link type="danger" size="small" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>

    <!-- 批量导入（对齐 React importConfig：alliance-agreements，走 Java 泛化导入 /import/{entity}/excel） -->
    <el-dialog v-model="importDialog" title="批量导入合作协议" width="560px">
      <ImportExport entity="alliance-agreements" :on-imported="loadItems" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import ImportExport from '@/components/ImportExport.vue';
import {
  allianceAgreementApi,
  listAllEnterprises,
  listAllProjects,
  formatDate,
  type AllianceAgreement,
  type AllianceEnterprise,
  type AllianceProject,
} from './crud-shared';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');
const router = useRouter();

const items = ref<AllianceAgreement[]>([]);
const loading = ref(false);
const search = ref('');
const page = ref(1);
const pageSize = 20;
const total = ref(0);
const importDialog = ref(false);
const enterprises = ref<AllianceEnterprise[]>([]);
const projects = ref<AllianceProject[]>([]);

async function loadRefs() {
  try {
    const [ents, projs] = await Promise.all([listAllEnterprises(), listAllProjects()]);
    enterprises.value = ents;
    projects.value = projs;
  } catch {
    // 忽略
  }
}

function enterpriseNames(row: AllianceAgreement): string {
  const ids = (row.enterpriseIds || []).map(String);
  if (ids.length === 0) return '-';
  return ids
    .map((eid) => enterprises.value.find((e) => e.id === eid)?.name || eid)
    .join('、');
}

function projectName(row: AllianceAgreement): string {
  const pid = (row.projectIds || [])[0];
  if (!pid) return '-';
  return projects.value.find((p) => p.id === pid)?.name || '-';
}

function isExpiring(endDate?: string): boolean {
  if (!endDate) return false;
  const days = (new Date(endDate).getTime() - Date.now()) / 86400000;
  return days >= 0 && days <= 90;
}

async function loadItems() {
  loading.value = true;
  try {
    const res = await allianceAgreementApi.list({
      search: search.value.trim() || undefined,
      limit: pageSize,
      offset: (page.value - 1) * pageSize,
    });
    items.value = res.items;
    total.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSearch() {
  page.value = 1;
  loadItems();
}

async function togglePublic(row: AllianceAgreement) {
  const next = !row.isPublic;
  try {
    await allianceAgreementApi.update(row.id, { ...row, isPublic: next });
    row.isPublic = next;
    ElMessage.success(next ? '已开启前台展示' : '已取消前台展示');
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: AllianceAgreement) {
  try {
    await ElMessageBox.confirm(`确定要删除协议「${row.name}」吗？`, '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    });
  } catch {
    return;
  }
  try {
    await allianceAgreementApi.delete(row.id);
    ElMessage.success('协议已删除');
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(async () => {
  if (!auth.user) {
    try {
      await auth.fetchMe();
    } catch {
      // 忽略
    }
  }
  loadRefs();
  loadItems();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.page-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 16px; }
.page-title { margin: 0; font-size: 20px; font-weight: 600; }
.page-sub { margin: 4px 0 0; font-size: 13px; color: #909399; }
.pagination { margin-top: 16px; justify-content: flex-end; }
.expiring { color: #e6a23c; font-weight: 500; }
.expiring-hint { margin-left: 4px; font-size: 12px; }
</style>
