// apps/edu/app/portal/apps/alliance/dictionaries/page.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Table, TableHeader, TableBody, TableRow, TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Plus, Trash2, Pencil } from 'lucide-react'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { portalRequest } from '@/lib/api'
import { UnderlineTabs, useToast, TableEmptyRow } from '@zhiyu/ui'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { FormFieldRow } from '@/components/shared/form-field-row'
import type { AllianceDictionary, AllianceListResponse } from '@/lib/types'
import { reportError } from '@/lib/error-handling'
import { useT } from '@/lib/i18n/locale-provider'

function DictionaryTab({ dictType }: { dictType: string }) {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()
  const [items, setItems] = useState<AllianceDictionary[]>([])
  const [loading, setLoading] = useState(true)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [formItem, setFormItem] = useState<{ code: string; name: string; sortOrder: number }>({
    code: '',
    name: '',
    sortOrder: 0,
  })
  const [editId, setEditId] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<AllianceDictionary | null>(null)
  const fetchItems = useCallback(async () => {
    if (!tenantId) return

    try {
      const data = await portalRequest<AllianceListResponse<AllianceDictionary>>(
        `/alliance/dictionaries/${dictType}`,
      )
      setItems(data.items || [])
    } catch (err) {
      reportError(err, '加载联盟字典列表')
    } finally {
      setLoading(false)
    }
  }, [tenantId, dictType])

  useEffect(() => {
    if (authLoading || !tenantId) return
    // 首屏加载：async IIFE 包裹，避免在 effect 体内同步触发 setState
    ;(async () => {
      await fetchItems()
    })()
  }, [tenantId, authLoading, fetchItems])

  const handleSave = async () => {
    setSaving(true)
    try {
      if (editId) {
        await portalRequest(`/alliance/dictionaries/${dictType}/${editId}`, {
          method: 'PUT',
          body: JSON.stringify(formItem),
        })
      } else {
        await portalRequest(`/alliance/dictionaries/${dictType}`, {
          method: 'POST',
          body: JSON.stringify(formItem),
        })
      }
      setDialogOpen(false)
      setEditId(null)
      await fetchItems()
      toast({ title: t('已保存') })
    } catch (e: any) {
      toast({ title: t('保存失败'), description: e.message, variant: 'destructive' })
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!deleteTarget) return
    try {
      await portalRequest(`/alliance/dictionaries/${dictType}/${deleteTarget.id}`, {
        method: 'DELETE',
      })
      setDeleteTarget(null)
      await fetchItems()
      toast({ title: t('已删除') })
    } catch (e: any) {
      toast({ title: t('删除失败'), description: e.message, variant: 'destructive' })
    } finally {
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Button
          size="sm"
          onClick={() => {
            setFormItem({ code: '', name: '', sortOrder: items.length })
            setEditId(null)
            setDialogOpen(true)
          }}
        >
          <Plus className="h-4 w-4 mr-1" />
          {t('新增')}
        </Button>
        <span className="text-sm text-muted-foreground">
          {t('共 {count} 项', { count: items.length })}
        </span>
      </div>
      <div className="rounded-md border">
        <Table className="min-w-[560px]">
          <TableHeader className="bg-muted/50">
            <TableRow>
              <TableHead>{t('编码')}</TableHead>
              <TableHead>{t('名称')}</TableHead>
              <TableHead>{t('排序')}</TableHead>
              <TableHead>{t('操作')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={4} className="text-center py-8 text-muted-foreground">
                  {t('加载中...')}
                </TableCell>
              </TableRow>
            ) : items.length === 0 ? (
              <TableEmptyRow colSpan={4} className="py-8">
                {t('暂无')}
              </TableEmptyRow>
            ) : (
              items.map((d) => (
                <TableRow key={d.id}>
                  <TableCell className="font-mono text-sm">{d.code}</TableCell>
                  <TableCell>{d.name}</TableCell>
                  <TableCell>{d.sortOrder}</TableCell>
                  <TableCell>
                    <TableRowActions>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => {
                          setFormItem({ code: d.code, name: d.name, sortOrder: d.sortOrder })
                          setEditId(d.id)
                          setDialogOpen(true)
                        }}
                      >
                        <Pencil className="h-4 w-4 mr-1" />
                        {t('编辑')}
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-red-600"
                        onClick={() => setDeleteTarget(d)}
                      >
                        <Trash2 className="h-4 w-4 mr-1" />
                        {t('删除')}
                      </Button>
                    </TableRowActions>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>{editId ? t('编辑字典项') : t('新增字典项')}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <FormFieldRow label={t('编码')} required>
              <Input
                value={formItem.code}
                onChange={(e) => setFormItem({ ...formItem, code: e.target.value })}
                disabled={!!editId}
              />
            </FormFieldRow>
            <FormFieldRow label={t('名称')} required>
              <Input
                value={formItem.name}
                onChange={(e) => setFormItem({ ...formItem, name: e.target.value })}
              />
            </FormFieldRow>
            <FormFieldRow label={t('排序')}>
              <Input
                type="number"
                value={formItem.sortOrder}
                onChange={(e) =>
                  setFormItem({ ...formItem, sortOrder: parseInt(e.target.value) || 0 })
                }
              />
            </FormFieldRow>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>
              {t('取消')}
            </Button>
            <Button onClick={handleSave} disabled={saving || !formItem.code || !formItem.name}>
              {saving ? t('保存中...') : t('保存')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      <ConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(v) => {
          if (!v) setDeleteTarget(null)
        }}
        title={t('确认删除')}
        description={deleteTarget ? t('确定要删除「{name}」吗？', { name: deleteTarget.name }) : ''}
        variant="destructive"
        confirmText={t('删除')}
        onConfirm={handleDelete}
      />
    </div>
  )
}

export default function AllianceDictionariesPage() {
  const t = useT()
  const tabs = [
    {
      dictType: 'cooperation_type',
      label: t('合作类型'),
      desc: t('校企合作类型字典（人才培养/实习实训/技术研发等）'),
    },
    {
      dictType: 'cooperation_rating',
      label: t('合作评级'),
      desc: t('企业合作评级字典（战略合作/深度合作/一般合作）'),
    },
    {
      dictType: 'enterprise_status',
      label: t('合作状态'),
      desc: t('企业合作状态字典（洽谈中/合作中/已暂停/已终止）'),
    },
    {
      dictType: 'achievement_type',
      label: t('成果类型'),
      desc: t('合作成果类型字典（岗位/场景/课程/自定义）'),
    },
    {
      dictType: 'agreement_type',
      label: t('协议类型'),
      desc: t('合作协议类型字典'),
    },
    {
      dictType: 'agreement_status',
      label: t('协议状态'),
      desc: t('合作协议状态字典'),
    },
    {
      dictType: 'expert_rating',
      label: t('专家评级'),
      desc: t('专家评级字典（金牌/银牌/铜牌）'),
    },
    {
      dictType: 'project_type',
      label: t('项目类型'),
      desc: t('合作项目类型字典'),
    },
  ]
  const [active, setActive] = useState(tabs[0].dictType)

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-foreground">{t('字典管理')}</h1>
        <p className="text-muted-foreground text-sm mt-1">
          {t('维护联盟业务字典，供各模块下拉使用')}
        </p>
      </div>
      <UnderlineTabs
        items={tabs.map((tab) => ({ key: tab.dictType, label: tab.label }))}
        activeKey={active}
        onSelect={setActive}
        className="gap-1"
      />
      {tabs
        .filter((tab) => tab.dictType === active)
        .map((tab) => (
          <div key={tab.dictType} className="rounded-lg border p-6">
            <h2 className="text-lg font-semibold mb-1">{t('{label}字典', { label: tab.label })}</h2>
            <p className="text-sm text-muted-foreground mb-4">{tab.desc}</p>
            <DictionaryTab dictType={tab.dictType} />
          </div>
        ))}
    </div>
  )
}

// plus-ui/src-portal/views/portal/apps/alliance/dictionaries.vue
<template>
  <div class="dict-page">
    <div class="page-head">
      <h1 class="page-title">字典管理</h1>
      <p class="page-desc">维护联盟业务字典，供各模块下拉使用</p>
    </div>

    <el-tabs v-model="activeType" class="dict-tabs">
      <el-tab-pane v-for="tab in tabs" :key="tab.dictType" :name="tab.dictType" :label="tab.label" />
    </el-tabs>

    <div class="card">
      <h2 class="card-title">{{ activeLabel }}字典</h2>
      <p class="card-desc">{{ activeDesc }}</p>

      <div class="dict-toolbar">
        <el-button type="primary" size="small" @click="openCreate">
          <el-icon class="mr-4"><Plus /></el-icon>
          新增
        </el-button>
        <span class="dict-count">共 {{ items.length }} 项</span>
      </div>

      <div class="table-card">
        <el-table v-loading="loading" :data="items" style="width: 100%">
          <el-table-column label="编码" min-width="160">
            <template #default="{ row }">
              <span class="cell-mono">{{ row.code }}</span>
            </template>
          </el-table-column>
          <el-table-column label="名称" min-width="200">
            <template #default="{ row }">{{ row.name }}</template>
          </el-table-column>
          <el-table-column label="排序" width="100">
            <template #default="{ row }">{{ row.sortOrder }}</template>
          </el-table-column>
          <el-table-column label="操作" width="160" align="right">
            <template #default="{ row }">
              <el-button link type="primary" size="small" @click="openEdit(row)">编辑</el-button>
              <el-button link type="danger" size="small" @click="confirmDelete(row)">删除</el-button>
            </template>
          </el-table-column>
          <template #empty>
            <el-empty description="暂无" :image-size="60" />
          </template>
        </el-table>
      </div>
    </div>

    <el-dialog v-model="dialogOpen" :title="editId ? '编辑字典项' : '新增字典项'" width="420px">
      <el-form :model="form" label-width="60px">
        <el-form-item label="编码" required>
          <el-input v-model="form.code" :disabled="!!editId" placeholder="编码" />
        </el-form-item>
        <el-form-item label="名称" required>
          <el-input v-model="form.name" placeholder="名称" />
        </el-form-item>
        <el-form-item label="排序">
          <el-input v-model.number="form.sortOrder" type="number" placeholder="排序" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogOpen = false">取消</el-button>
        <el-button type="primary" :loading="saving" :disabled="!form.code || !form.name" @click="save">
          保存
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus } from '@element-plus/icons-vue';
import { portalRequest } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import type { AllianceDictionary } from './shared';

const auth = useAuthStore();
const tenantId = () => (auth.user?.tenantId as string) || '';

const tabs = [
  { dictType: 'cooperation_type', label: '合作类型', desc: '校企合作类型字典（人才培养/实习实训/技术研发等）' },
  { dictType: 'cooperation_rating', label: '合作评级', desc: '企业合作评级字典（战略合作/深度合作/一般合作）' },
  { dictType: 'enterprise_status', label: '合作状态', desc: '企业合作状态字典（洽谈中/合作中/已暂停/已终止）' },
  { dictType: 'achievement_type', label: '成果类型', desc: '合作成果类型字典（岗位/场景/课程/自定义）' },
  { dictType: 'agreement_type', label: '协议类型', desc: '合作协议类型字典' },
  { dictType: 'agreement_status', label: '协议状态', desc: '合作协议状态字典' },
  { dictType: 'expert_rating', label: '专家评级', desc: '专家评级字典（金牌/银牌/铜牌）' },
  { dictType: 'project_type', label: '项目类型', desc: '合作项目类型字典' },
];

const activeType = ref(tabs[0].dictType);
const activeLabel = computed(() => tabs.find((t) => t.dictType === activeType.value)?.label ?? '');
const activeDesc = computed(() => tabs.find((t) => t.dictType === activeType.value)?.desc ?? '');

const items = ref<AllianceDictionary[]>([]);
const loading = ref(false);
const dialogOpen = ref(false);
const editId = ref<string | null>(null);
const saving = ref(false);
const form = ref({ code: '', name: '', sortOrder: 0 });

async function load() {
  if (!tenantId()) return;
  loading.value = true;
  try {
    const data = await portalRequest<{ items: AllianceDictionary[] }>(
      `/alliance/dictionaries/${activeType.value}`,
    );
    items.value = data.items || [];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function openCreate() {
  form.value = { code: '', name: '', sortOrder: items.value.length };
  editId.value = null;
  dialogOpen.value = true;
}

function openEdit(row: AllianceDictionary) {
  form.value = { code: row.code, name: row.name, sortOrder: row.sortOrder };
  editId.value = row.id;
  dialogOpen.value = true;
}

async function save() {
  saving.value = true;
  try {
    const body = JSON.stringify(form.value);
    if (editId.value) {
      await portalRequest(`/alliance/dictionaries/${activeType.value}/${editId.value}`, {
        method: 'PUT',
        body,
      });
    } else {
      await portalRequest(`/alliance/dictionaries/${activeType.value}`, {
        method: 'POST',
        body,
      });
    }
    ElMessage.success('已保存');
    dialogOpen.value = false;
    editId.value = null;
    await load();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function confirmDelete(row: AllianceDictionary) {
  try {
    await ElMessageBox.confirm(`确定要删除「${row.name}」吗？`, '确认删除', {
      confirmButtonText: '删除',
      cancelButtonText: '取消',
      type: 'warning',
    });
  } catch {
    return;
  }
  try {
    await portalRequest(`/alliance/dictionaries/${activeType.value}/${row.id}`, { method: 'DELETE' });
    ElMessage.success('已删除');
    await load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

watch(activeType, () => {
  load();
});

onMounted(load);
</script>

<style scoped>
.dict-page {
  min-height: 100%;
}
.page-head {
  margin-bottom: 20px;
}
.page-title {
  font-size: 20px;
  font-weight: 600;
  color: #0f172a;
  margin: 0;
}
.page-desc {
  margin-top: 4px;
  font-size: 13px;
  color: #64748b;
}
.dict-tabs {
  margin-bottom: 16px;
}
.card {
  border: 1px solid #e7e5e4;
  border-radius: 12px;
  background: #fff;
  padding: 20px;
}
.card-title {
  font-size: 16px;
  font-weight: 600;
  color: #0f172a;
  margin: 0 0 4px;
}
.card-desc {
  font-size: 13px;
  color: #64748b;
  margin: 0 0 16px;
}
.dict-toolbar {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}
.dict-count {
  font-size: 13px;
  color: #64748b;
}
.mr-4 {
  margin-right: 4px;
}
.table-card {
  border: 1px solid #f1f5f9;
  border-radius: 8px;
  overflow: hidden;
}
.cell-mono {
  font-family: monospace;
  font-size: 13px;
}
</style>
