// frontend/edu/app/portal/apps/alliance/employmentproject/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Pencil, Trash2 } from 'lucide-react'
import { Link } from 'react-router'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceEmploymentProjectApi } from '@/lib/api'
import { useToast } from '@zhiyu/ui'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { usePagedList } from '@/hooks/use-paged-list'
import { formatDate } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import {
  EMPLOYMENT_PROJECT_TYPE_LABELS,
  EMPLOYMENT_PROJECT_PHASE_LABELS,
  deriveEmploymentProjectPhase,
  type EmploymentProject,
} from '@/lib/types'

/** 类型展示：内置枚举用标签，custom:<文本> 展示自定义文本，其余未知值原样。 */
function employmentTypeLabel(type: string | undefined): string {
  if (!type) return '-'
  if (type.startsWith('custom:')) return type.slice('custom:'.length)
  return EMPLOYMENT_PROJECT_TYPE_LABELS[type] ?? type
}

export default function EmploymentProjectListPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()

  const [publishStatus, setPublishStatus] = useState('all')
  const [typeFilter, setTypeFilter] = useState('all')

  const list = usePagedList(
    async ({ page, limit, search }) => {
      if (!tenantId) return { items: [], total: 0 }
      const data = await allianceEmploymentProjectApi.list({
        page,
        limit,
        search,
        publishStatus: publishStatus === 'all' ? undefined : publishStatus,
        type: typeFilter === 'all' ? undefined : typeFilter,
      })
      return { items: data.items || [], total: data.total }
    },
    [tenantId, authLoading, publishStatus, typeFilter],
  )

  const togglePublish = async (p: EmploymentProject) => {
    const next = p.publishStatus === 'published' ? 'draft' : 'published'
    try {
      await allianceEmploymentProjectApi.update(p.id, { publishStatus: next })
      toast({ title: next === 'published' ? t('已发布') : t('已取消发布') })
      await list.refresh()
    } catch (e: any) {
      toast({ title: t('操作失败'), description: e.message, variant: 'destructive' })
    }
  }

  return (
    <PortalCrudPage
      title={t('就业项目管理')}
      description={t('管理人才与岗位供需服务大厅的就业项目。')}
      entityLabel={t('就业项目')}
      searchPlaceholder={t('搜索项目名称...')}
      createButtonLabel={t('新建项目')}
      items={list.items}
      loading={list.loading}
      error={list.error?.message ?? null}
      onRetry={list.refresh}
      searchValue={list.search}
      onSearchChange={list.setSearch}
      pagination={list.pagination}
      createHref="/portal/apps/alliance/employmentproject/new"
      colSpan={7}
      searchRight={
        <div className="flex flex-wrap items-center gap-2">
          <Select value={publishStatus} onValueChange={(v) => { setPublishStatus(v); list.setPage(1) }}>
            <SelectTrigger className="w-32">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('全部发布状态')}</SelectItem>
              <SelectItem value="published">{t('已发布')}</SelectItem>
              <SelectItem value="draft">{t('草稿')}</SelectItem>
            </SelectContent>
          </Select>
          <Select value={typeFilter} onValueChange={(v) => { setTypeFilter(v); list.setPage(1) }}>
            <SelectTrigger className="w-36">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('全部类型')}</SelectItem>
              {['spring', 'autumn', 'directed', 'order'].map((v) => (
                <SelectItem key={v} value={v}>
                  {EMPLOYMENT_PROJECT_TYPE_LABELS[v]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      }
      renderTableHeader={() => (
        <>
          <TableHead>{t('项目名称')}</TableHead>
          <TableHead>{t('类型')}</TableHead>
          <TableHead>{t('发起单位')}</TableHead>
          <TableHead>{t('起止日期')}</TableHead>
          <TableHead>{t('展示状态')}</TableHead>
          <TableHead>{t('发布状态')}</TableHead>
          <TableHead>{t('操作')}</TableHead>
        </>
      )}
      renderTableRow={(p: any, actions: any) => {
        const phase = deriveEmploymentProjectPhase(p)
        const phaseVariant =
          phase === 'ongoing' ? 'default' : phase === 'ended' ? 'outline' : 'secondary'
        return (
          <>
            <TableCell className="font-medium">
              <Link
                to={`/portal/apps/alliance/employmentproject/${p.id}`}
                className="hover:underline"
              >
                {p.name}
              </Link>
            </TableCell>
            <TableCell>{employmentTypeLabel(p.type)}</TableCell>
            <TableCell>{p.organizer || '-'}</TableCell>
            <TableCell className="whitespace-nowrap">
              {formatDate(p.startDate)} ~ {formatDate(p.endDate)}
            </TableCell>
            <TableCell>
              <Badge variant={phaseVariant as any}>{EMPLOYMENT_PROJECT_PHASE_LABELS[phase]}</Badge>
            </TableCell>
            <TableCell>
              <Badge variant={p.publishStatus === 'published' ? 'default' : 'secondary'}>
                {p.publishStatus === 'published' ? t('已发布') : t('草稿')}
              </Badge>
            </TableCell>
            <TableRowActions>
              <Link to={`/portal/apps/alliance/employmentproject/${p.id}`}>
                <Button variant="ghost" size="sm">
                  <Pencil className="h-3.5 w-3.5 mr-1" />
                  {t('编辑')}
                </Button>
              </Link>
              <Button variant="ghost" size="sm" onClick={() => togglePublish(p)}>
                {p.publishStatus === 'published' ? t('取消发布') : t('发布')}
              </Button>
              <Button variant="ghost" size="sm" className="text-red-600" onClick={actions.delete}>
                <Trash2 className="h-3.5 w-3.5 mr-1" />
                {t('删除')}
              </Button>
            </TableRowActions>
          </>
        )
      }}
      getDeleteDescription={(item: any) => (
        <>{t('确定要删除就业项目 {name} 吗？', { name: item.name })}</>
      )}
      onDelete={async (item: any) => {
        await allianceEmploymentProjectApi.delete(item.id)
        toast({ title: t('已删除') })
        await list.refresh()
      }}
    />
  )
}

// plus-ui/src-portal/views/portal/apps/alliance/employmentproject.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <div class="card-title">就业项目管理</div>
            <div class="card-sub">管理人才与岗位供需服务大厅的就业项目。</div>
          </div>
          <el-button type="primary" size="small" @click="router.push('/portal/apps/alliance/employmentproject/new')">新建项目</el-button>
        </div>
      </template>

      <div class="toolbar">
        <el-input v-model="search" placeholder="搜索项目名称..." clearable style="max-width: 280px" @input="onSearchInput" @clear="reloadList" @keyup.enter="reloadList" />
        <el-select v-model="publishStatus" style="width: 140px" @change="onFilterChange">
          <el-option label="全部发布状态" value="all" />
          <el-option label="已发布" value="published" />
          <el-option label="草稿" value="draft" />
        </el-select>
        <el-select v-model="typeFilter" style="width: 140px" @change="onFilterChange">
          <el-option label="全部类型" value="all" />
          <el-option v-for="(label, v) in EMPLOYMENT_PROJECT_TYPE_LABELS" :key="v" :label="label" :value="v" />
        </el-select>
      </div>

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="项目名称" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" :underline="false" @click="goDetail(row.id)">{{ row.name }}</el-link>
          </template>
        </el-table-column>
        <el-table-column label="类型" width="120"><template #default="{ row }">{{ employmentTypeLabel(row.type) }}</template></el-table-column>
        <el-table-column label="发起单位" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.organizer || '-' }}</template></el-table-column>
        <el-table-column label="起止日期" width="200"><template #default="{ row }">{{ formatDate(row.startDate) }} ~ {{ formatDate(row.endDate) }}</template></el-table-column>
        <el-table-column label="展示状态" width="100">
          <template #default="{ row }">
            <el-tag :type="phaseTagType(deriveEmploymentProjectPhase(row))">{{ EMPLOYMENT_PROJECT_PHASE_LABELS[deriveEmploymentProjectPhase(row)] }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="发布状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.publishStatus === 'published' ? 'success' : 'info'">{{ row.publishStatus === 'published' ? '已发布' : '草稿' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="190" fixed="right">
          <template #default="{ row }">
            <el-button size="small" text type="primary" @click="goDetail(row.id)">编辑</el-button>
            <el-button size="small" text type="primary" @click="togglePublish(row)">{{ row.publishStatus === 'published' ? '取消发布' : '发布' }}</el-button>
            <el-button size="small" text type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadList"
      />
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { portalRequest, buildQuery } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import {
  EMPLOYMENT_PROJECT_TYPE_LABELS,
  EMPLOYMENT_PROJECT_PHASE_LABELS,
  deriveEmploymentProjectPhase,
  formatDate,
  employmentTypeLabel,
} from './alliance-admin';
import type { EmploymentProject, ListResponse } from './alliance-admin';
import { useAllianceListPage } from './crud-pages';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const publishStatus = ref('all');
const typeFilter = ref('all');

function phaseTagType(phase: string): 'success' | 'warning' | 'info' {
  if (phase === 'ongoing') return 'success';
  if (phase === 'ended') return 'info';
  return 'warning';
}

const {
  router,
  items,
  loading,
  search,
  page,
  pageSize,
  total,
  loadItems: loadList,
  resetAndLoad,
  confirmDelete,
} = useAllianceListPage<EmploymentProject>({
  fetchList: (query) =>
    portalRequest<ListResponse<EmploymentProject>>(
      `/alliance/employment-projects${buildQuery({
        ...query,
        publishStatus: publishStatus.value === 'all' ? undefined : publishStatus.value,
        type: typeFilter.value === 'all' ? undefined : typeFilter.value,
      })}`,
    ),
  loadGuard: () => !!tenantId.value,
  ensureAuth: false,
  remove: {
    confirmText: (p) => `确定要删除就业项目 ${p.name} 吗？`,
    deleteRow: (p) => portalRequest(`/alliance/employment-projects/${p.id}`, { method: 'DELETE' }),
    successText: '已删除',
  },
});

let searchTimer: ReturnType<typeof setTimeout> | undefined;
function onSearchInput() {
  if (searchTimer) clearTimeout(searchTimer);
  searchTimer = setTimeout(resetAndLoad, 300);
}
function reloadList() {
  if (searchTimer) clearTimeout(searchTimer);
  resetAndLoad();
}
function onFilterChange() {
  resetAndLoad();
}

function goDetail(id: string) {
  router.push(`/portal/apps/alliance/employmentproject/${id}`);
}

async function togglePublish(p: EmploymentProject) {
  const next = p.publishStatus === 'published' ? 'draft' : 'published';
  try {
    await portalRequest(`/alliance/employment-projects/${p.id}`, {
      method: 'PUT',
      body: JSON.stringify({ publishStatus: next }),
    });
    ElMessage.success(next === 'published' ? '已发布' : '已取消发布');
    await loadList();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { margin-top: 4px; font-size: 12px; color: #909399; }
.toolbar { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }
.pagination { margin-top: 16px; justify-content: flex-end; }
</style>
