// apps/edu/app/portal/apps/alliance/enterprises/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog'
import {
  Pencil,
  ExternalLink,
  Link2,
  Unlink,
  Building2,
  PlusCircle,
} from 'lucide-react'
import Link from 'next/link'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import {
  allianceEnterpriseApi,
  allianceProjectApi,
  allianceAchievementApi,
  allianceAgreementApi,
} from '@/lib/api'
import { useToast, useAsync, FormDialogFooter, ComboboxSelect } from '@zhiyu/ui'
import { allianceLabel } from '@zhiyu/shared-types'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { SearchInput } from '@/components/shared/search-input'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { FormFieldRow } from '@/components/shared/form-field-row'
import { formatDate } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import { useSecondaryColleges } from '@/hooks/use-secondary-colleges'
import { useAllianceDictionary, mergeDictOptions } from '@/lib/alliance-dicts'
import type { AllianceEnterprise } from '@/lib/types'

export default function AllianceEnterprisesPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()
  const { colleges: secondaryCollegeOptions } = useSecondaryColleges(tenantId)
  const { items: statusItems } = useAllianceDictionary('enterprise_status', tenantId)
  const { items: ratingItems } = useAllianceDictionary('cooperation_rating', tenantId)
  const { data, loading, error, refresh } = useAsync(
    async () => {
      if (!tenantId) return { enterprises: [], projects: [], achievements: [], agreements: [] }
      const [ent, proj, ach, agr] = await Promise.all([
        allianceEnterpriseApi.list(),
        allianceProjectApi.list({ limit: 200 }),
        allianceAchievementApi.list({ limit: 200 }),
        allianceAgreementApi.list({ limit: 200 }),
      ])
      return {
        enterprises: ent.items || [],
        projects: proj.items || [],
        achievements: ach.items || [],
        agreements: agr.items || [],
      }
    },
    { deps: [tenantId, authLoading], onError: () => true },
  )

  const { enterprises, projects, achievements, agreements } = data ?? {}

  // ── 引入企业（全局企业池搜索 → link） ─────────────────────
  const [linkDialog, setLinkDialog] = useState(false)
  const [searchKeyword, setSearchKeyword] = useState('')
  const [searchResults, setSearchResults] = useState<AllianceEnterprise[] | null>(null)
  const [searching, setSearching] = useState(false)
  const [linkingId, setLinkingId] = useState<string | null>(null)

  const doSearch = async () => {
    setSearching(true)
    try {
      const res = await allianceEnterpriseApi.search(searchKeyword)
      setSearchResults(res.items || [])
    } catch (e: any) {
      toast({ title: t('搜索失败'), description: e.message, variant: 'destructive' })
    } finally {
      setSearching(false)
    }
  }

  const doLink = async (id: string) => {
    setLinkingId(id)
    try {
      await allianceEnterpriseApi.link(id)
      toast({ title: t('企业已引入') })
      setLinkDialog(false)
      setSearchResults(null)
      setSearchKeyword('')
      await refresh()
    } catch (e: any) {
      toast({ title: t('引入失败'), description: e.message, variant: 'destructive' })
    } finally {
      setLinkingId(null)
    }
  }

  // ── 代注册企业（学校为企业创建租户+账号，直接建立合作关联） ───────
  const [registerDialog, setRegisterDialog] = useState(false)
  const [registering, setRegistering] = useState(false)
  const [reg, setReg] = useState({
    enterpriseName: '',
    unifiedSocialCreditCode: '',
    contactPerson: '',
    contactPhone: '',
    contactEmail: '',
    username: '',
    password: '',
    confirmPassword: '',
  })

  const doRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    if (reg.password !== reg.confirmPassword) {
      toast({ title: t('两次输入的密码不一致'), variant: 'destructive' })
      return
    }
    setRegistering(true)
    try {
      await allianceEnterpriseApi.register({
        enterpriseName: reg.enterpriseName,
        unifiedSocialCreditCode: reg.unifiedSocialCreditCode || undefined,
        contactPerson: reg.contactPerson || undefined,
        contactPhone: reg.contactPhone || undefined,
        contactEmail: reg.contactEmail || undefined,
        username: reg.username,
        password: reg.password,
      })
      toast({
        title: t('代注册成功'),
        description: t(
          '已创建企业账号 {username}，请将用户名和密码转交企业，企业即可登录企业服务台',
          {
            username: reg.username,
          },
        ),
      })
      setRegisterDialog(false)
      setReg({
        enterpriseName: '',
        unifiedSocialCreditCode: '',
        contactPerson: '',
        contactPhone: '',
        contactEmail: '',
        username: '',
        password: '',
        confirmPassword: '',
      })
      await refresh()
    } catch (err: any) {
      toast({
        title: t('代注册失败'),
        description: err.message || t('未知错误'),
        variant: 'destructive',
      })
    } finally {
      setRegistering(false)
    }
  }

  // ── 解除引入 ──────────────────────────────────────────────
  const [unlinkTarget, setUnlinkTarget] = useState<AllianceEnterprise | null>(null)
  const [unlinking, setUnlinking] = useState(false)

  const confirmUnlink = async () => {
    if (!unlinkTarget) return
    setUnlinking(true)
    try {
      await allianceEnterpriseApi.unlink(unlinkTarget.id)
      toast({ title: t('已解除引入') })
      setUnlinkTarget(null)
      await refresh()
    } catch (e: any) {
      toast({ title: t('操作失败'), description: e.message, variant: 'destructive' })
    } finally {
      setUnlinking(false)
    }
  }

  const countBy = (arr: any[], field: string, id: string) =>
    arr.filter((x) => (x[field] || []).includes?.(id)).length

  const linkedIds = new Set((enterprises ?? []).map((e) => e.id))

  return (
    <>
      <PortalCrudPage
        title={t('合作企业管理')}
        description={t('从全局企业池引入合作企业，维护本校合作关系（评级/状态/前台展示）。')}
        entityLabel={t('合作企业')}
        searchPlaceholder={t('搜索企业名称或行业...')}
        items={enterprises ?? []}
        loading={loading}
        error={error?.message ?? null}
        onRetry={refresh}
        filterItems={(items, search) =>
          items.filter(
            (e) =>
              !search ||
              e.name.toLowerCase().includes(search.toLowerCase()) ||
              (e.industry || '').toLowerCase().includes(search.toLowerCase()),
          )
        }
        headerActions={
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" onClick={() => setRegisterDialog(true)}>
              <Building2 className="h-4 w-4 mr-1" />
              {t('代注册企业')}
            </Button>
            <Button size="sm" onClick={() => setLinkDialog(true)}>
              <Link2 className="h-4 w-4 mr-1" />
              {t('引入企业')}
            </Button>
          </div>
        }
        hideCreate
        colSpan={11}
        renderTableHeader={() => (
          <>
            <TableHead>{t('企业名称')}</TableHead>
            <TableHead>{t('前台展示')}</TableHead>
            <TableHead>{t('类型')}</TableHead>
            <TableHead>{t('地址')}</TableHead>
            <TableHead>{t('状态')}</TableHead>
            <TableHead>{t('评级')}</TableHead>
            <TableHead>{t('合作协议')}</TableHead>
            <TableHead>{t('合作项目')}</TableHead>
            <TableHead>{t('合作成果')}</TableHead>
            <TableHead>{t('更新时间')}</TableHead>
            <TableHead>{t('操作')}</TableHead>
          </>
        )}
        renderTableRow={(enterprise: AllianceEnterprise, actions: any) => (
          <>
            <TableCell className="font-medium max-w-[180px] truncate">
              <Link
                href={`/portal/apps/alliance/enterprises/${enterprise.id}`}
                className="hover:underline"
              >
                {enterprise.name}
              </Link>
            </TableCell>
            <TableCell>
              <Switch checked={enterprise.isPublic || false} onCheckedChange={actions.toggle} />
            </TableCell>
            <TableCell>{allianceLabel('enterpriseType', enterprise.enterpriseType)}</TableCell>
            <TableCell className="max-w-[140px] truncate">{enterprise.address || '-'}</TableCell>
            <TableCell>{allianceLabel('enterpriseStatus', enterprise.status)}</TableCell>
            {/* 评级：与编辑弹窗一致，未设置时按默认评级 general 展示 */}
            <TableCell>
              {allianceLabel('enterpriseRating', enterprise.rating || 'general')}
            </TableCell>
            <TableCell>
              <Link
                href={`/portal/apps/alliance/enterprises/${enterprise.id}?tab=agreements`}
                className="text-primary hover:underline"
              >
                {
                  (agreements ?? []).filter((a) =>
                    (a.enterpriseIds || []).includes?.(enterprise.id),
                  ).length
                }
              </Link>
            </TableCell>
            <TableCell>
              <Link
                href={`/portal/apps/alliance/enterprises/${enterprise.id}?tab=projects`}
                className="text-primary hover:underline"
              >
                {countBy(projects ?? [], 'enterpriseIds', enterprise.id)}
              </Link>
            </TableCell>
            <TableCell>
              <Link
                href={`/portal/apps/alliance/enterprises/${enterprise.id}?tab=achievements`}
                className="text-primary hover:underline"
              >
                {countBy(achievements ?? [], 'enterpriseIds', enterprise.id)}
              </Link>
            </TableCell>
            <TableCell className="whitespace-nowrap">{formatDate(enterprise.updatedAt)}</TableCell>
            <TableRowActions>
              <Link href={`/portal/apps/alliance/enterprises/${enterprise.id}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="h-3.5 w-3.5 mr-1" />
                  {t('查看')}
                </Button>
              </Link>
              <Button variant="ghost" size="sm" onClick={actions.edit}>
                <Pencil className="h-3.5 w-3.5 mr-1" />
                {t('编辑')}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="text-red-600"
                onClick={() => setUnlinkTarget(enterprise)}
              >
                <Unlink className="h-3.5 w-3.5 mr-1" />
                {t('解除引入')}
              </Button>
            </TableRowActions>
          </>
        )}
        createDefault={() => ({}) as AllianceEnterprise}
        renderForm={(item: any, setItem: any) => (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              {t('企业主体信息由企业侧维护，此处仅维护本校合作关系字段。')}
            </p>
            <FormFieldRow label={t('企业类型')}>
              <Select
                value={item.enterpriseType || 'cooperation'}
                onValueChange={(v: any) => setItem({ ...item, enterpriseType: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="cooperation">{t('合作企业')}</SelectItem>
                  <SelectItem value="third-party">{t('第三方雇主企业')}</SelectItem>
                </SelectContent>
              </Select>
            </FormFieldRow>
            <FormFieldRow label={t('合作状态')}>
              <Select
                value={item.status || 'negotiating'}
                onValueChange={(v: any) => setItem({ ...item, status: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {mergeDictOptions(statusItems, item.status || 'negotiating').map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {t(opt.label)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormFieldRow>
            <FormFieldRow label={t('合作评级')}>
              <Select
                value={item.rating || 'general'}
                onValueChange={(v: any) => setItem({ ...item, rating: v })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {mergeDictOptions(ratingItems, item.rating || 'general').map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {t(opt.label)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FormFieldRow>
            <FormFieldRow label={t('关联二级学院')}>
              <ComboboxSelect
                multiple
                className="w-full"
                options={secondaryCollegeOptions.map((name) => ({ label: name, value: name }))}
                value={item.secondaryColleges || []}
                onChange={(v: string[]) => setItem({ ...item, secondaryColleges: v })}
                placeholder={t('选择归属学院')}
              />
            </FormFieldRow>
            <div className="flex items-center gap-2">
              <Switch
                checked={item.isPublic || false}
                onCheckedChange={(v: any) => setItem({ ...item, isPublic: v })}
              />
              <Label>{t('在本校前台展示')}</Label>
            </div>
          </div>
        )}
        onSave={async (item: any) => {
          await allianceEnterpriseApi.update(item.id, {
            enterpriseType: item.enterpriseType,
            status: item.status,
            rating: item.rating,
            isPublic: item.isPublic,
            secondaryColleges: item.secondaryColleges,
          })
          toast({ title: t('合作关系已更新') })
          await refresh()
        }}
        onToggleEnabled={async (item: any) => {
          await allianceEnterpriseApi.update(item.id, { isPublic: !item.isPublic })
          await refresh()
        }}
      />

      {/* 引入企业：全局企业池搜索 */}
      <Dialog
        open={linkDialog}
        onOpenChange={(o) => {
          setLinkDialog(o)
          if (!o) {
            setSearchResults(null)
            setSearchKeyword('')
          }
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('引入企业')}</DialogTitle>
            <DialogDescription>
              {t('从全局企业池搜索已注册的企业，引入后建立校企合作关系。')}
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2">
            <SearchInput
              wrapperClassName="flex-1"
              placeholder={t('输入企业名称关键词...')}
              value={searchKeyword}
              onChange={setSearchKeyword}
              onSearch={doSearch}
            />
            <Button variant="outline" onClick={doSearch} loading={searching}>
              {t('搜索')}
            </Button>
          </div>
          <div className="max-h-[50vh] overflow-y-auto space-y-2">
            {searchResults === null ? (
              <p className="text-center py-6 text-sm text-muted-foreground">
                {t('输入关键词搜索企业')}
              </p>
            ) : searchResults.length === 0 ? (
              <p className="text-center py-6 text-sm text-muted-foreground">
                {t('未找到匹配的企业')}
              </p>
            ) : (
              searchResults.map((e) => (
                <div key={e.id} className="flex items-center gap-2 p-2 rounded border">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{e.name}</p>
                    <p className="text-xs text-muted-foreground">
                      {[e.industry, e.region].filter(Boolean).join(' · ') || t('未填写行业地区')}
                    </p>
                  </div>
                  {linkedIds.has(e.id) ? (
                    <span className="text-xs text-muted-foreground shrink-0">{t('已引入')}</span>
                  ) : (
                    <Button
                      size="sm"
                      onClick={() => doLink(e.id)}
                      disabled={linkingId !== null && linkingId !== e.id}
                      loading={linkingId === e.id}
                    >
                      {t('引入')}
                    </Button>
                  )}
                </div>
              ))
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setLinkDialog(false)}>
              {t('关闭')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 代注册企业：学校为企业创建租户+管理员账号 */}
      <Dialog
        open={registerDialog}
        onOpenChange={(o) => {
          setRegisterDialog(o)
          if (!o)
            setReg({
              enterpriseName: '',
              unifiedSocialCreditCode: '',
              contactPerson: '',
              contactPhone: '',
              contactEmail: '',
              username: '',
              password: '',
              confirmPassword: '',
            })
        }}
      >
        <DialogContent className="max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{t('代注册企业')}</DialogTitle>
            <DialogDescription>
              {t('为企业创建账号，注册后直接建立本校合作关联；请将用户名和密码转交企业。')}
            </DialogDescription>
          </DialogHeader>
          <form onSubmit={doRegister} className="space-y-4 py-2">
            <div className="space-y-1.5">
              <Label>
                {t('企业名称')} <span className="text-destructive">*</span>
              </Label>
              <Input
                placeholder={t('请输入企业全称')}
                value={reg.enterpriseName}
                onChange={(e) => setReg((p) => ({ ...p, enterpriseName: e.target.value }))}
                required
              />
            </div>
            <div className="space-y-1.5">
              <Label>{t('统一社会信用代码')}</Label>
              <Input
                placeholder={t('如：91320594MA1P7XXXX1')}
                value={reg.unifiedSocialCreditCode}
                onChange={(e) => setReg((p) => ({ ...p, unifiedSocialCreditCode: e.target.value }))}
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>{t('联系人')}</Label>
                <Input
                  placeholder={t('请输入联系人姓名')}
                  value={reg.contactPerson}
                  onChange={(e) => setReg((p) => ({ ...p, contactPerson: e.target.value }))}
                />
              </div>
              <div className="space-y-1.5">
                <Label>{t('手机号')}</Label>
                <Input
                  placeholder={t('请输入手机号')}
                  value={reg.contactPhone}
                  onChange={(e) => setReg((p) => ({ ...p, contactPhone: e.target.value }))}
                />
              </div>
            </div>
            <div className="space-y-1.5">
              <Label>{t('联系邮箱（选填）')}</Label>
              <Input
                type="email"
                placeholder={t('请输入联系邮箱')}
                value={reg.contactEmail}
                onChange={(e) => setReg((p) => ({ ...p, contactEmail: e.target.value }))}
              />
            </div>
            <div className="space-y-1.5">
              <Label>
                {t('用户名')} <span className="text-destructive">*</span>
              </Label>
              <Input
                placeholder={t('设置登录用户名（企业内唯一）')}
                value={reg.username}
                onChange={(e) => setReg((p) => ({ ...p, username: e.target.value }))}
                autoComplete="username"
                required
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>
                  {t('密码')} <span className="text-destructive">*</span>
                </Label>
                <Input
                  type="password"
                  placeholder={t('设置登录密码')}
                  value={reg.password}
                  onChange={(e) => setReg((p) => ({ ...p, password: e.target.value }))}
                  autoComplete="new-password"
                  required
                />
              </div>
              <div className="space-y-1.5">
                <Label>
                  {t('确认密码')} <span className="text-destructive">*</span>
                </Label>
                <Input
                  type="password"
                  placeholder={t('再次输入密码')}
                  value={reg.confirmPassword}
                  onChange={(e) => setReg((p) => ({ ...p, confirmPassword: e.target.value }))}
                  autoComplete="new-password"
                  required
                />
              </div>
            </div>
            <FormDialogFooter
              onCancel={() => setRegisterDialog(false)}
              confirmText={
                <>
                  <PlusCircle className="h-4 w-4 mr-1" />
                  {t('代注册并关联')}
                </>
              }
              loading={registering}
            />
          </form>
        </DialogContent>
      </Dialog>

      {/* 解除引入确认 */}
      <ConfirmDialog
        open={unlinkTarget !== null}
        onOpenChange={(open) => {
          if (!open) setUnlinkTarget(null)
        }}
        title={t('解除引入')}
        description={
          unlinkTarget
            ? t('确定要解除与 {name} 的引入关系吗？历史协议/项目/成果引用保留，但页面不再展示。', {
                name: unlinkTarget.name,
              })
            : ''
        }
        pending={unlinking}
        variant="destructive"
        confirmText={unlinking ? t('解除中...') : t('解除引入')}
        onConfirm={confirmUnlink}
      />
    </>
  )
}

// plus-ui/src-portal/views/portal/apps/alliance/enterprises.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <div class="card-title">合作企业管理</div>
            <div class="card-sub">从全局企业池引入合作企业，维护本校合作关系（评级/状态/前台展示）。</div>
          </div>
          <div class="header-actions">
            <el-button size="small" @click="openRegister">代注册企业</el-button>
            <el-button size="small" type="primary" @click="openLink">引入企业</el-button>
          </div>
        </div>
      </template>

      <div class="toolbar">
        <el-input
          v-model="search"
          placeholder="搜索企业名称或行业..."
          clearable
          style="max-width: 320px"
          @input="onSearchInput"
          @clear="onSearchClear"
          @keyup.enter="reloadList"
        />
      </div>

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="企业名称" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" :underline="false" @click="goDetail(row.id)">{{ row.name }}</el-link>
          </template>
        </el-table-column>
        <el-table-column label="前台展示" width="90">
          <template #default="{ row }">
            <el-switch :model-value="row.isPublic || false" @change="(v: any) => togglePublic(row, Boolean(v))" />
          </template>
        </el-table-column>
        <el-table-column label="类型" width="130">
          <template #default="{ row }">{{ enterpriseTypeText(row.enterpriseType) }}</template>
        </el-table-column>
        <el-table-column label="地址" min-width="140" show-overflow-tooltip>
          <template #default="{ row }">{{ row.address || '-' }}</template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">{{ allianceLabel('enterpriseStatus', row.status) }}</template>
        </el-table-column>
        <el-table-column label="评级" width="100">
          <template #default="{ row }">{{ allianceLabel('enterpriseRating', row.rating || 'general') }}</template>
        </el-table-column>
        <el-table-column label="合作协议" width="90">
          <template #default="{ row }">
            <el-link type="primary" :underline="false" @click="goDetail(row.id, 'agreements')">
              {{ countBy(agreements, 'enterpriseIds', row.id) }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="合作项目" width="90">
          <template #default="{ row }">
            <el-link type="primary" :underline="false" @click="goDetail(row.id, 'projects')">
              {{ countBy(projects, 'enterpriseIds', row.id) }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="合作成果" width="90">
          <template #default="{ row }">
            <el-link type="primary" :underline="false" @click="goDetail(row.id, 'achievements')">
              {{ countBy(achievements, 'enterpriseIds', row.id) }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="更新时间" width="120">
          <template #default="{ row }">{{ formatDate(row.updatedAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button size="small" text type="primary" @click="goDetail(row.id)">查看</el-button>
            <el-button size="small" text type="primary" @click="openEdit(row)">编辑</el-button>
            <el-button size="small" text type="danger" @click="confirmUnlink(row)">解除引入</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadList"
      />
    </el-card>

    <!-- 引入企业 -->
    <el-dialog v-model="linkDialog" title="引入企业" width="560px">
      <p class="dialog-desc">从全局企业池搜索已注册的企业，引入后建立校企合作关系。</p>
      <div class="link-search">
        <el-input
          v-model="searchKeyword"
          placeholder="输入企业名称关键词..."
          clearable
          @keyup.enter="doSearch"
        />
        <el-button :loading="searching" @click="doSearch">搜索</el-button>
      </div>
      <div class="link-results">
        <p v-if="searchResults === null" class="empty-hint">输入关键词搜索企业</p>
        <p v-else-if="searchResults.length === 0" class="empty-hint">未找到匹配的企业</p>
        <div v-else v-for="e in searchResults" :key="e.id" class="link-result-item">
          <div class="link-result-main">
            <div class="link-result-name">{{ e.name }}</div>
            <div class="link-result-sub">{{ [e.industry, e.region].filter(Boolean).join(' · ') || '未填写行业地区' }}</div>
          </div>
          <span v-if="linkedIds.has(e.id)" class="linked-mark">已引入</span>
          <el-button
            v-else
            size="small"
            type="primary"
            :loading="linkingId === e.id"
            :disabled="linkingId !== null && linkingId !== e.id"
            @click="doLink(e.id)"
          >
            引入
          </el-button>
        </div>
      </div>
      <template #footer>
        <el-button @click="linkDialog = false">关闭</el-button>
      </template>
    </el-dialog>

    <!-- 代注册企业 -->
    <el-dialog v-model="registerDialog" title="代注册企业" width="640px">
      <p class="dialog-desc">为企业创建账号，注册后直接建立本校合作关联；请将用户名和密码转交企业。</p>
      <el-form :model="reg" label-width="140px">
        <el-form-item label="企业名称" required>
          <el-input v-model="reg.enterpriseName" placeholder="请输入企业全称" />
        </el-form-item>
        <el-form-item label="统一社会信用代码">
          <el-input v-model="reg.unifiedSocialCreditCode" placeholder="如：91320594MA1P7XXXX1" />
        </el-form-item>
        <el-form-item label="联系人">
          <el-input v-model="reg.contactPerson" placeholder="请输入联系人姓名" />
        </el-form-item>
        <el-form-item label="手机号">
          <el-input v-model="reg.contactPhone" placeholder="请输入手机号" />
        </el-form-item>
        <el-form-item label="联系邮箱（选填）">
          <el-input v-model="reg.contactEmail" placeholder="请输入联系邮箱" />
        </el-form-item>
        <el-form-item label="用户名" required>
          <el-input v-model="reg.username" placeholder="设置登录用户名（企业内唯一）" autocomplete="username" />
        </el-form-item>
        <el-form-item label="密码" required>
          <el-input v-model="reg.password" type="password" placeholder="设置登录密码" show-password autocomplete="new-password" />
        </el-form-item>
        <el-form-item label="确认密码" required>
          <el-input v-model="reg.confirmPassword" type="password" placeholder="再次输入密码" show-password autocomplete="new-password" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="registerDialog = false">取消</el-button>
        <el-button type="primary" :loading="registering" @click="doRegister">代注册并关联</el-button>
      </template>
    </el-dialog>

    <!-- 编辑合作关系 -->
    <el-dialog v-model="editDialog" title="编辑合作关系" width="520px">
      <p class="dialog-desc">企业主体信息由企业侧维护，此处仅维护本校合作关系字段。</p>
      <el-form :model="editForm" label-width="120px">
        <el-form-item label="企业类型">
          <el-select v-model="editForm.enterpriseType" style="width: 100%">
            <el-option label="合作企业" value="cooperation" />
            <el-option label="第三方雇主企业" value="third-party" />
          </el-select>
        </el-form-item>
        <el-form-item label="合作状态">
          <el-select v-model="editForm.status" style="width: 100%">
            <el-option
              v-for="opt in mergeDictOptions(statusDict, editForm.status)"
              :key="opt.value"
              :label="opt.label"
              :value="opt.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="合作评级">
          <el-select v-model="editForm.rating" style="width: 100%">
            <el-option
              v-for="opt in mergeDictOptions(ratingDict, editForm.rating)"
              :key="opt.value"
              :label="opt.label"
              :value="opt.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="关联二级学院">
          <el-select v-model="editForm.secondaryColleges" multiple filterable placeholder="选择归属学院" style="width: 100%">
            <el-option v-for="name in secondaryColleges" :key="name" :label="name" :value="name" />
          </el-select>
        </el-form-item>
        <el-form-item label="前台展示">
          <el-switch v-model="editForm.isPublic" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="editDialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveEdit">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { portalRequest, buildQuery } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import { organizationApi, orgTypeApi } from '@/api/system';
import type { Organization } from '@/types/system';
import { allianceLabel, formatDate, mergeDictOptions } from './alliance-admin';
import type { AllianceEnterprise, AllianceDictItem, ListResponse } from './alliance-admin';

const router = useRouter();
const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const PAGE_SIZE = 20;
const items = ref<AllianceEnterprise[]>([]);
const loading = ref(false);
const total = ref(0);
const page = ref(1);
const pageSize = PAGE_SIZE;
const search = ref('');

const projects = ref<{ id: string; enterpriseIds?: string[] }[]>([]);
const achievements = ref<{ id: string; enterpriseIds?: string[] }[]>([]);
const agreements = ref<{ id: string; enterpriseIds?: string[] }[]>([]);
const linkedIds = ref<Set<string>>(new Set());

const statusDict = ref<AllianceDictItem[]>([]);
const ratingDict = ref<AllianceDictItem[]>([]);
const secondaryColleges = ref<string[]>([]);

const linkDialog = ref(false);
const searchKeyword = ref('');
const searchResults = ref<AllianceEnterprise[] | null>(null);
const searching = ref(false);
const linkingId = ref<string | null>(null);

const registerDialog = ref(false);
const registering = ref(false);
const reg = reactive({
  enterpriseName: '',
  unifiedSocialCreditCode: '',
  contactPerson: '',
  contactPhone: '',
  contactEmail: '',
  username: '',
  password: '',
  confirmPassword: '',
});

const editDialog = ref(false);
const saving = ref(false);
const editItem = ref<AllianceEnterprise | null>(null);
const editForm = reactive({
  enterpriseType: 'cooperation',
  status: 'negotiating',
  rating: 'general',
  isPublic: false,
  secondaryColleges: [] as string[],
});

function enterpriseTypeText(v: string): string {
  const map: Record<string, string> = {
    cooperation: '合作企业',
    'third-party': '第三方雇主企业',
    platform: '第三方雇主企业',
    'school-based': '合作企业',
  };
  return map[v] ?? v ?? '-';
}

function countBy(arr: { enterpriseIds?: string[] }[], field: string, id: string): number {
  return arr.filter((x) => ((x as unknown as Record<string, string[] | undefined>)[field] || []).includes?.(id)).length;
}

async function loadList() {
  if (!tenantId.value) return;
  loading.value = true;
  try {
    const res = await portalRequest<ListResponse<AllianceEnterprise>>(
      `/alliance/enterprises${buildQuery({
        limit: PAGE_SIZE,
        offset: (page.value - 1) * PAGE_SIZE,
        search: search.value.trim() || undefined,
      })}`,
    );
    items.value = res.items || [];
    total.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

let searchTimer: ReturnType<typeof setTimeout> | undefined;
function onSearchInput() {
  if (searchTimer) clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    page.value = 1;
    loadList();
  }, 300);
}
function onSearchClear() {
  page.value = 1;
  loadList();
}
function reloadList() {
  if (searchTimer) clearTimeout(searchTimer);
  page.value = 1;
  loadList();
}

async function loadRefs() {
  if (!tenantId.value) return;
  try {
    const [proj, ach, agr, linked] = await Promise.all([
      portalRequest<ListResponse<{ id: string; enterpriseIds?: string[] }>>('/alliance/projects?limit=200'),
      portalRequest<ListResponse<{ id: string; enterpriseIds?: string[] }>>('/alliance/achievements?limit=200'),
      portalRequest<ListResponse<{ id: string; enterpriseIds?: string[] }>>('/alliance/agreements?limit=200'),
      portalRequest<ListResponse<AllianceEnterprise>>('/alliance/enterprises?limit=200'),
    ]);
    projects.value = proj.items || [];
    achievements.value = ach.items || [];
    agreements.value = agr.items || [];
    linkedIds.value = new Set((linked.items || []).map((e) => e.id));
  } catch {
    // 引用数据加载失败不阻断主流程
  }
}

async function loadSecondaryColleges() {
  if (!tenantId.value) return;
  try {
    const [treeRes, typesRes] = await Promise.all([
      organizationApi.tree({ tenantId: tenantId.value }),
      orgTypeApi.list({ tenantId: tenantId.value, limit: 1000 }),
    ]);
    const typeNameMap = new Map<string, string>();
    (typesRes.items || []).forEach((t) => typeNameMap.set(t.id, t.name));
    const collegeTypeIds = new Set<string>();
    typeNameMap.forEach((name, id) => {
      if (name === '二级学院') collegeTypeIds.add(id);
    });
    const names: string[] = [];
    const walk = (nodes: Organization[]) => {
      for (const n of nodes) {
        if (collegeTypeIds.has(n.typeId)) names.push(n.name);
        if (n.children && n.children.length) walk(n.children);
      }
    };
    walk(treeRes.items || []);
    secondaryColleges.value = Array.from(new Set(names));
  } catch {
    // 二级学院选项加载失败不阻断主流程
  }
}

async function loadDicts() {
  if (!tenantId.value) return;
  try {
    const [s, r] = await Promise.all([
      portalRequest<{ items: AllianceDictItem[] }>('/alliance/dictionaries/enterprise_status'),
      portalRequest<{ items: AllianceDictItem[] }>('/alliance/dictionaries/cooperation_rating'),
    ]);
    statusDict.value = s.items || [];
    ratingDict.value = r.items || [];
  } catch {
    // 字典加载失败时回退静态映射
  }
}

function goDetail(id: string, tab?: string) {
  router.push(`/portal/apps/alliance/enterprises/${id}${tab ? `?tab=${tab}` : ''}`);
}

async function togglePublic(item: AllianceEnterprise, v: boolean) {
  try {
    await portalRequest(`/alliance/enterprises/${item.id}`, {
      method: 'PUT',
      body: JSON.stringify({ isPublic: v }),
    });
    item.isPublic = v;
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

function openEdit(item: AllianceEnterprise) {
  editItem.value = item;
  editForm.enterpriseType = item.enterpriseType || 'cooperation';
  editForm.status = item.status || 'negotiating';
  editForm.rating = item.rating || 'general';
  editForm.isPublic = item.isPublic || false;
  editForm.secondaryColleges = [...(item.secondaryColleges || [])];
  editDialog.value = true;
}

async function saveEdit() {
  if (!editItem.value) return;
  saving.value = true;
  try {
    await portalRequest(`/alliance/enterprises/${editItem.value.id}`, {
      method: 'PUT',
      body: JSON.stringify({
        enterpriseType: editForm.enterpriseType,
        status: editForm.status,
        rating: editForm.rating,
        isPublic: editForm.isPublic,
        secondaryColleges: editForm.secondaryColleges,
      }),
    });
    ElMessage.success('合作关系已更新');
    editDialog.value = false;
    await loadList();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

function openLink() {
  searchResults.value = null;
  searchKeyword.value = '';
  linkDialog.value = true;
}

async function doSearch() {
  searching.value = true;
  try {
    const res = await portalRequest<ListResponse<AllianceEnterprise>>(
      `/alliance/enterprises/search${buildQuery({ keyword: searchKeyword.value })}`,
    );
    searchResults.value = res.items || [];
  } catch (e) {
    ElMessage.error((e as Error).message || '搜索失败');
  } finally {
    searching.value = false;
  }
}

async function doLink(id: string) {
  linkingId.value = id;
  try {
    await portalRequest(`/alliance/enterprises/${id}/link`, { method: 'POST' });
    ElMessage.success('企业已引入');
    linkDialog.value = false;
    searchResults.value = null;
    searchKeyword.value = '';
    await Promise.all([loadList(), loadRefs()]);
  } catch (e) {
    ElMessage.error((e as Error).message || '引入失败');
  } finally {
    linkingId.value = null;
  }
}

function openRegister() {
  Object.assign(reg, {
    enterpriseName: '',
    unifiedSocialCreditCode: '',
    contactPerson: '',
    contactPhone: '',
    contactEmail: '',
    username: '',
    password: '',
    confirmPassword: '',
  });
  registerDialog.value = true;
}

async function doRegister() {
  if (!reg.enterpriseName.trim() || !reg.username.trim() || !reg.password) {
    ElMessage.warning('请填写必填项');
    return;
  }
  if (reg.password !== reg.confirmPassword) {
    ElMessage.warning('两次输入的密码不一致');
    return;
  }
  registering.value = true;
  try {
    await portalRequest('/alliance/enterprises/register', {
      method: 'POST',
      body: JSON.stringify({
        enterpriseName: reg.enterpriseName,
        unifiedSocialCreditCode: reg.unifiedSocialCreditCode || undefined,
        contactPerson: reg.contactPerson || undefined,
        contactPhone: reg.contactPhone || undefined,
        contactEmail: reg.contactEmail || undefined,
        username: reg.username,
        password: reg.password,
      }),
    });
    ElMessage.success(`代注册成功，已创建企业账号 ${reg.username}，请将用户名和密码转交企业，企业即可登录企业服务台`);
    registerDialog.value = false;
    await loadList();
  } catch (e) {
    ElMessage.error((e as Error).message || '代注册失败');
  } finally {
    registering.value = false;
  }
}

async function confirmUnlink(item: AllianceEnterprise) {
  try {
    await ElMessageBox.confirm(
      `确定要解除与 ${item.name} 的引入关系吗？历史协议/项目/成果引用保留，但页面不再展示。`,
      '解除引入',
      { type: 'warning', confirmButtonText: '解除引入', cancelButtonText: '取消' },
    );
  } catch {
    return;
  }
  try {
    await portalRequest(`/alliance/enterprises/${item.id}/link`, { method: 'DELETE' });
    ElMessage.success('已解除引入');
    await Promise.all([loadList(), loadRefs()]);
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

onMounted(() => {
  loadList();
  loadRefs();
  loadSecondaryColleges();
  loadDicts();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { margin-top: 4px; font-size: 12px; color: #909399; }
.header-actions { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.toolbar { margin-bottom: 12px; }
.pagination { margin-top: 16px; justify-content: flex-end; }
.dialog-desc { margin: 0 0 12px; font-size: 13px; color: #909399; }
.link-search { display: flex; gap: 8px; margin-bottom: 12px; }
.link-results { max-height: 50vh; overflow-y: auto; }
.empty-hint { text-align: center; padding: 24px 0; font-size: 13px; color: #909399; }
.link-result-item { display: flex; align-items: center; gap: 8px; padding: 8px; border: 1px solid #e5e7eb; border-radius: 6px; margin-bottom: 8px; }
.link-result-main { flex: 1; min-width: 0; }
.link-result-name { font-size: 13px; font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.link-result-sub { font-size: 12px; color: #909399; }
.linked-mark { font-size: 12px; color: #909399; flex-shrink: 0; }
</style>
