// apps/edu/app/portal/apps/alliance/projects/page.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Progress } from '@/components/ui/progress'
import { Pencil, Trash2, ExternalLink } from 'lucide-react'
import Link from 'next/link'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceEnterpriseApi, allianceProjectApi } from '@/lib/api'
import { useToast } from '@zhiyu/ui'
import { allianceLabel } from '@zhiyu/shared-types'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'
import { FormFieldRow, FormFieldGrid } from '@/components/shared/form-field-row'
import type { AllianceProject, AllianceEnterprise, AllianceProjectMilestone } from '@/lib/types'

export default function AllianceProjectsPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const [projects, setProjects] = useState<AllianceProject[]>([])
  const [enterprises, setEnterprises] = useState<AllianceEnterprise[]>([])
  const [milestones, setMilestones] = useState<Record<string, AllianceProjectMilestone[]>>({})
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchProjects = useCallback(async () => {
    if (!tenantId) return
    setLoading(true)
    setError(null)
    try {
      const [data, ents] = await Promise.all([
        allianceProjectApi.list(),
        allianceEnterpriseApi.list({ limit: 1000 }),
      ])
      setProjects(data.items || [])
      setEnterprises(ents.items || [])
      const ms: Record<string, AllianceProjectMilestone[]> = {}
      for (const p of data.items || []) {
        try {
          const m = await allianceProjectApi.listMilestones(p.id)
          ms[p.id] = m.items || []
        } catch {
          ms[p.id] = []
        }
      }
      setMilestones(ms)
    } catch (e: any) {
      setError(e.message || '加载失败')
    } finally {
      setLoading(false)
    }
  }, [tenantId])

  useEffect(() => {
    if (authLoading || !tenantId) return
    // 首屏加载：async IIFE 包裹，避免在 effect 体内同步触发 setState
    ;(async () => {
      await fetchProjects()
    })()
  }, [tenantId, authLoading, fetchProjects])

  const entName = (id: string) => enterprises.find((e) => e.id === id)?.name || id
  const fmtDate = (d?: string) => (d ? new Date(d).toLocaleDateString('zh-CN') : '-')

  return (
    <PortalCrudPage
      title="合作项目管理"
      description="管理校企合作项目，追踪项目阶段与里程碑。"
      entityLabel="合作项目"
      searchPlaceholder="搜索项目名称..."
      createButtonLabel="新增项目"
      items={projects}
      loading={loading}
      error={error}
      onRetry={fetchProjects}
      filterItems={(items, search) =>
        items.filter((p) => !search || p.name.toLowerCase().includes(search.toLowerCase()))
      }
      importConfig={{
        importType: 'alliance-projects',
        entityLabel: '合作项目',
        templateFileName: '合作项目批量导入模板.xlsx',
      }}
      createHref="/portal/apps/alliance/projects/new"
      colSpan={9}
      renderTableHeader={() => (
        <>
          <TableHead>项目名称</TableHead>
          <TableHead>前台展示</TableHead>
          <TableHead>合作企业</TableHead>
          <TableHead>合作类型</TableHead>
          <TableHead>起止时间</TableHead>
          <TableHead>里程碑进度</TableHead>
          <TableHead>阶段</TableHead>
          <TableHead>更新时间</TableHead>
          <TableHead>操作</TableHead>
        </>
      )}
      renderTableRow={(p: any, actions: any) => {
        const ms = milestones[p.id] || []
        const done = ms.filter((m) => m.isCompleted).length
        const progress = ms.length > 0 ? Math.round((done / ms.length) * 100) : 0
        const entIds: string[] = (p.enterpriseIds || []).map(String)
        return (
          <>
            <TableCell className="font-medium">
              <Link href={`/portal/apps/alliance/projects/${p.id}`} className="hover:underline">
                {p.name}
              </Link>
            </TableCell>
            <TableCell>
              <Switch checked={p.isPublic || false} onCheckedChange={actions.toggle} />
            </TableCell>
            <TableCell className="max-w-[180px]">
              {entIds.length > 0 ? entIds.map(entName).join('、') : '-'}
            </TableCell>
            <TableCell>{p.type || '-'}</TableCell>
            <TableCell className="whitespace-nowrap">
              {fmtDate(p.startDate)} ~ {fmtDate(p.endDate)}
            </TableCell>
            <TableCell>
              <div className="flex items-center gap-2">
                <Progress value={progress} className="w-20 h-2" />
                <span className="text-xs text-muted-foreground">{progress}%</span>
              </div>
            </TableCell>
            <TableCell>{allianceLabel('projectPhase', p.phase)}</TableCell>
            <TableCell>{fmtDate(p.updatedAt)}</TableCell>
            <TableRowActions>
              <Link href={`/portal/apps/alliance/projects/${p.id}`}>
                <Button variant="ghost" size="sm">
                  <ExternalLink className="h-3.5 w-3.5 mr-1" />
                  查看
                </Button>
              </Link>
              <Link href={`/portal/apps/alliance/projects/${p.id}/edit`}>
                <Button variant="ghost" size="sm">
                  <Pencil className="h-3.5 w-3.5 mr-1" />
                  编辑
                </Button>
              </Link>
              <Button variant="ghost" size="sm" className="text-red-600" onClick={actions.delete}>
                <Trash2 className="h-3.5 w-3.5 mr-1" />
                删除
              </Button>
            </TableRowActions>
          </>
        )
      }}
      createDefault={() =>
        ({
          id: '',
          name: '',
          phase: 'initiation',
          publishStatus: 'draft',
          isPublic: false as any,
          createdAt: '',
          updatedAt: '',
        }) as any
      }
      renderForm={(item: any, setItem: any) => (
        <div className="space-y-4">
          <FormFieldRow label="项目名称" required>
            <Input
              value={item.name || ''}
              onChange={(e: any) => setItem({ ...item, name: e.target.value })}
            />
          </FormFieldRow>
          <FormFieldRow label="阶段">
            <Select
              value={item.phase || ''}
              onValueChange={(v: any) => setItem({ ...item, phase: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {['initiation', 'execution', 'acceptance', 'closure', 'archived', 'terminated'].map(
                  (v) => (
                    <SelectItem key={v} value={v}>
                      {v}
                    </SelectItem>
                  ),
                )}
              </SelectContent>
            </Select>
          </FormFieldRow>
          <FormFieldGrid>
            <FormFieldRow label="开始日期">
              <Input
                type="date"
                value={item.startDate || ''}
                onChange={(e: any) => setItem({ ...item, startDate: e.target.value })}
              />
            </FormFieldRow>
            <FormFieldRow label="结束日期">
              <Input
                type="date"
                value={item.endDate || ''}
                onChange={(e: any) => setItem({ ...item, endDate: e.target.value })}
              />
            </FormFieldRow>
          </FormFieldGrid>
          <FormFieldRow label="描述">
            <Textarea
              value={item.description || ''}
              onChange={(e: any) => setItem({ ...item, description: e.target.value })}
              rows={3}
            />
          </FormFieldRow>
        </div>
      )}
      getDeleteDescription={(item: any) => (
        <>
          确定要删除项目 <b>{item.name}</b> 吗？
        </>
      )}
      onSave={async (item: any, isEdit: boolean) => {
        if (isEdit) await allianceProjectApi.update(item.id, item)
        else await allianceProjectApi.create(item)
        toast({ title: `项目已${isEdit ? '更新' : '创建'}` })
        await fetchProjects()
      }}
      onDelete={async (item: any) => {
        await allianceProjectApi.delete(item.id)
        toast({ title: '已删除' })
        await fetchProjects()
      }}
      onToggleEnabled={async (item: any) => {
        await allianceProjectApi.update(item.id, { isPublic: !item.isPublic })
        toast({ title: `已${item.isPublic ? '取消' : '设为'}前台展示` })
        await fetchProjects()
      }}
    />
  )
}

// plus-ui/src-portal/views/portal/apps/alliance/projects.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div>
        <h1 class="page-title">合作项目管理</h1>
        <p class="page-sub">管理校企合作项目，追踪项目阶段与里程碑。</p>
      </div>
      <div>
        <el-button style="margin-right: 8px" @click="importDialog = true">批量导入</el-button>
        <el-button type="primary" @click="router.push('/portal/apps/alliance/projects/new')">
          <el-icon><Plus /></el-icon>
          新建项目
        </el-button>
      </div>
    </div>

    <el-card shadow="never">
      <el-input
        v-model="search"
        placeholder="搜索项目名称..."
        clearable
        style="max-width: 320px; margin-bottom: 12px"
        @input="onSearch"
        @clear="onSearch"
      />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="项目名称" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <el-link type="primary" @click="router.push(`/portal/apps/alliance/projects/${row.id}`)">
              {{ row.name }}
            </el-link>
          </template>
        </el-table-column>
        <el-table-column label="前台展示" width="100">
          <template #default="{ row }">
            <el-switch :model-value="row.isPublic || false" @change="togglePublic(row)" />
          </template>
        </el-table-column>
        <el-table-column label="合作企业" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ enterpriseNames(row) }}</template>
        </el-table-column>
        <el-table-column label="合作类型" width="120">
          <template #default="{ row }">{{ row.type || '-' }}</template>
        </el-table-column>
        <el-table-column label="起止时间" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">{{ formatDate(row.startDate) }} ~ {{ formatDate(row.endDate) }}</template>
        </el-table-column>
        <el-table-column label="里程碑进度" width="180">
          <template #default="{ row }">
            <div class="progress-cell">
              <el-progress :percentage="progressOf(row)" :stroke-width="8" style="flex: 1" />
              <span class="progress-text">{{ progressOf(row) }}%</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column label="阶段" width="110">
          <template #default="{ row }">{{ phaseLabel(row.phase) }}</template>
        </el-table-column>
        <el-table-column label="更新时间" width="120">
          <template #default="{ row }">{{ formatDate(row.updatedAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/projects/${row.id}`)">查看</el-button>
            <el-button link type="primary" size="small" @click="router.push(`/portal/apps/alliance/projects/${row.id}/edit`)">编辑</el-button>
            <el-button link type="danger" size="small" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="total > pageSize"
        v-model:current-page="page"
        :page-size="pageSize"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>

    <!-- 批量导入（对齐 React importConfig：alliance-projects，走 Java 泛化导入 /import/{entity}/excel） -->
    <el-dialog v-model="importDialog" title="批量导入合作项目" width="560px">
      <ImportExport entity="alliance-projects" :on-imported="loadItems" />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import ImportExport from '@/components/ImportExport.vue';
import {
  allianceProjectApi,
  enterpriseApi,
  milestoneApi,
  allianceLabel,
  formatDate,
  type AllianceProject,
  type AllianceEnterprise,
  type AllianceProjectMilestone,
} from './crud-shared';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');
const router = useRouter();

const items = ref<AllianceProject[]>([]);
const loading = ref(false);
const search = ref('');
const page = ref(1);
const pageSize = 20;
const total = ref(0);
const importDialog = ref(false);
const enterprises = ref<AllianceEnterprise[]>([]);
const milestones = ref<Record<string, AllianceProjectMilestone[]>>({});

async function loadEnterprises() {
  try {
    const res = await enterpriseApi.list({ limit: 200 });
    enterprises.value = res.items || [];
  } catch {
    // 忽略
  }
}

function enterpriseNames(row: AllianceProject): string {
  const ids = (row.enterpriseIds || []).map(String);
  if (ids.length === 0) return '-';
  return ids
    .map((eid) => enterprises.value.find((e) => e.id === eid)?.name || eid)
    .join('、');
}

function phaseLabel(v?: string): string {
  return allianceLabel('projectPhase', v);
}

function progressOf(row: AllianceProject): number {
  const ms = milestones.value[row.id] || [];
  if (ms.length === 0) return 0;
  const done = ms.filter((m) => m.isCompleted).length;
  return Math.round((done / ms.length) * 100);
}

async function loadItems() {
  loading.value = true;
  try {
    const res = await allianceProjectApi.list({
      search: search.value.trim() || undefined,
      limit: pageSize,
      offset: (page.value - 1) * pageSize,
    });
    items.value = res.items;
    total.value = res.total ?? 0;

    const map: Record<string, AllianceProjectMilestone[]> = {};
    const results = await Promise.all(
      res.items.map((p) => milestoneApi.list(p.id).catch(() => ({ items: [] as AllianceProjectMilestone[] }))),
    );
    res.items.forEach((p, i) => {
      map[p.id] = results[i].items || [];
    });
    milestones.value = map;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSearch() {
  page.value = 1;
  loadItems();
}

async function togglePublic(row: AllianceProject) {
  const next = !row.isPublic;
  try {
    await allianceProjectApi.update(row.id, { isPublic: next });
    row.isPublic = next;
    ElMessage.success(next ? '已设为前台展示' : '已取消前台展示');
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: AllianceProject) {
  try {
    await ElMessageBox.confirm(`确定要删除项目 ${row.name} 吗？`, '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    });
  } catch {
    return;
  }
  try {
    await allianceProjectApi.delete(row.id);
    ElMessage.success('已删除');
    loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(async () => {
  if (!auth.user) {
    try {
      await auth.fetchMe();
    } catch {
      // 忽略
    }
  }
  loadEnterprises();
  loadItems();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.page-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 16px; }
.page-title { margin: 0; font-size: 20px; font-weight: 600; }
.page-sub { margin: 4px 0 0; font-size: 13px; color: #909399; }
.pagination { margin-top: 16px; justify-content: flex-end; }
.progress-cell { display: flex; align-items: center; gap: 8px; }
.progress-text { font-size: 12px; color: #909399; }
</style>
