// frontend/edu/app/portal/apps/ai/_components/studio-section.tsx
'use client'

// 我的工坊区块（spec docs/spec/ai-service-center.md §7 F2/F5）：我的知识库 + 我的智能体管理。
// 由落地页（landing）嵌入；/studio 旧路由重定向至 landing#studio。
// v1.4 卡片化：对齐 evaluation/landing 考试中心卡片模式——封面横幅（coverImage，无则渐变兜底）
// + 右上角状态徽标 + 正文统计 + 操作按钮；卡片带 data-smoke-card 供验收 flow clickCard 定位。
// v2.0 面板化（对标考试中心大面板）：图标头部 + 胶囊 CTA + 左侧状态环图 + 右侧分组卡片，
// 取消 Tabs（一个面板全看到）。
import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  BarChart3,
  BookOpen,
  FileText,
  HelpCircle,
  Loader2,
  MessageSquare,
  Pencil,
  Plus,
  Send,
  Trash2,
  Undo2,
  Wrench,
} from 'lucide-react'
import { PieChart as RePieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts'
import { useToast } from '@zhiyu/ui'
import { aiCenterAgentApi, aiCenterKbApi } from '@/lib/api'
import type { AIAgent, AIKnowledgeBase } from '@/lib/api'
import { useT } from '@/lib/i18n/locale-provider'
import { coverGradientFor } from '@/lib/cover-gradients'
import { AIStatusBadge } from '../studio/components/ai-status-badge'

/** 卡片封面横幅：有封面图用图，无则渐变 + 居中图标（对齐 ExamCenterCard） */
function CardCover({
  cover,
  seed,
  icon,
  status,
}: {
  cover?: string
  seed: string
  icon: React.ReactNode
  status: React.ReactNode
}) {
  return (
    <div
      className="h-24 flex items-center justify-center shrink-0 relative"
      style={
        cover
          ? { backgroundImage: `url('${cover}')`, backgroundSize: 'cover', backgroundPosition: 'center' }
          : { background: coverGradientFor(seed) }
      }
    >
      {!cover && icon}
      <div className="absolute top-3 right-3 [&_span]:bg-white/90 [&_span]:backdrop-blur-sm [&_span]:shadow-sm">
        {status}
      </div>
    </div>
  )
}

const cardClass =
  'bg-white rounded-2xl border border-[#e7e5e4] overflow-hidden flex flex-col shadow-[0_2px_6px_rgba(0,0,0,0.04)] hover:shadow-[0_12px_32px_rgba(0,0,0,0.1)] hover:-translate-y-1 transition-all'

export function StudioSection() {
  const t = useT()
  const router = useRouter()
  const { toast } = useToast()

  // ---------- 知识库 ----------
  const [myKbs, setMyKbs] = useState<AIKnowledgeBase[]>([])
  const [sharedKbs, setSharedKbs] = useState<AIKnowledgeBase[]>([])
  const [kbLoading, setKbLoading] = useState(true)
  // v2.6.1：新建知识库改为独立编辑页（/studio/kb/new），不再弹窗

  // ---------- 智能体 ----------
  const [agents, setAgents] = useState<AIAgent[]>([])
  const [agentLoading, setAgentLoading] = useState(true)

  // ---------- 通用 ----------
  const [acting, setActing] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{ kind: 'kb' | 'agent'; id: string; name: string } | null>(null)
  const [warnings, setWarnings] = useState<string[] | null>(null)

  // setState 只发生在 fetch 回调里（react-hooks/set-state-in-effect）；重新加载由事件处理器触发，loading 初值为 true 仅覆盖首屏
  const loadKbs = useCallback(() => {
    Promise.all([
      aiCenterKbApi.listMine({ scope: 'owned' }),
      aiCenterKbApi.listMine({ scope: 'collaborating' }),
    ])
      .then(([mine, shared]) => {
        setMyKbs(mine.items)
        setSharedKbs(shared.items)
      })
      .catch((err: unknown) =>
        toast({
          title: t('加载失败'),
          description: err instanceof Error ? err.message : undefined,
          variant: 'destructive',
        }),
      )
      .finally(() => setKbLoading(false))
  }, [t, toast])

  const loadAgents = useCallback(() => {
    aiCenterAgentApi
      .listMine()
      .then((res) => setAgents(res.items))
      .catch((err: unknown) =>
        toast({
          title: t('加载失败'),
          description: err instanceof Error ? err.message : undefined,
          variant: 'destructive',
        }),
      )
      .finally(() => setAgentLoading(false))
  }, [t, toast])

  useEffect(() => {
    loadKbs()
    loadAgents()
  }, [loadKbs, loadAgents])


  const runAction = async (fn: () => Promise<unknown>, successTitle: string, reload: () => void) => {
    if (acting) return
    setActing(true)
    try {
      await fn()
      toast({ title: successTitle })
      reload()
    } catch (err) {
      toast({
        title: t('操作失败'),
        description: err instanceof Error ? err.message : undefined,
        variant: 'destructive',
      })
    } finally {
      setActing(false)
    }
  }

  const handleSubmitKb = (id: string) =>
    runAction(() => aiCenterKbApi.submit(id), t('已提交，等待管理员审核'), loadKbs)

  const handleUnpublishKb = (id: string) =>
    runAction(() => aiCenterKbApi.unpublish(id), t('已下架'), loadKbs)

  const handleSubmitAgent = async (id: string) => {
    if (acting) return
    setActing(true)
    try {
      const res = await aiCenterAgentApi.submit(id)
      if (res.warnings && res.warnings.length > 0) {
        // 关联私有库等提示：逐条展示（spec §3.1 AG-2）
        setWarnings(res.warnings)
      } else {
        toast({ title: t('已提交，等待管理员审核') })
      }
      loadAgents()
    } catch (err) {
      toast({
        title: t('操作失败'),
        description: err instanceof Error ? err.message : undefined,
        variant: 'destructive',
      })
    } finally {
      setActing(false)
    }
  }

  const handleUnpublishAgent = (id: string) =>
    runAction(() => aiCenterAgentApi.unpublish(id), t('已下架'), loadAgents)

  const handleDelete = async () => {
    if (!deleteTarget || acting) return
    setActing(true)
    try {
      if (deleteTarget.kind === 'kb') {
        await aiCenterKbApi.remove(deleteTarget.id)
      } else {
        await aiCenterAgentApi.remove(deleteTarget.id)
      }
      toast({ title: t('已删除') })
      setDeleteTarget(null)
      if (deleteTarget.kind === 'kb') loadKbs()
      else loadAgents()
    } catch (err) {
      toast({
        title: t('操作失败'),
        description: err instanceof Error ? err.message : undefined,
        variant: 'destructive',
      })
    } finally {
      setActing(false)
    }
  }

  const renderKbCard = (kb: AIKnowledgeBase) => {
    const role = kb.myRole ?? 'owner'
    const canEdit = role === 'owner' || role === 'editor'
    const isOwner = role === 'owner'
    return (
      <div key={kb.id} data-smoke-card className={cardClass}>
        <CardCover
          cover={kb.coverImage}
          seed={kb.id}
          icon={<BookOpen className="w-10 h-10 text-white/80" />}
          status={<AIStatusBadge status={kb.status} />}
        />
        <div className="p-4 flex-1 flex flex-col">
          <h3 className="text-[15px] font-semibold text-slate-800 truncate">{kb.name}</h3>
          {kb.description && (
            <p className="text-xs text-slate-400 mt-1 truncate">{kb.description}</p>
          )}
          {kb.tags.length > 0 && (
            <div className="mt-1.5 flex items-center gap-1 flex-wrap">
              {kb.tags.map((tag) => (
                <span key={tag} className="rounded bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">
                  {tag}
                </span>
              ))}
            </div>
          )}
          {kb.status === 'rejected' && kb.reviewComment && (
            <p className="mt-1 text-xs text-red-600">
              {t('驳回原因')}：{kb.reviewComment}
            </p>
          )}
          <div className="flex items-center gap-4 text-[11px] text-slate-400 py-2.5 mt-2 border-b border-slate-50">
            <span className="flex items-center gap-1">
              <FileText className="w-3 h-3" /> {t('{count} 个文档', { count: kb.docCount })}
            </span>
            <span className="flex items-center gap-1">
              <HelpCircle className="w-3 h-3" /> {t('{count} 次提问', { count: kb.askCount })}
            </span>
          </div>
          <div className="flex flex-wrap gap-1 pt-2.5">
            {canEdit && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => router.push(`/portal/apps/ai/studio/kb/${kb.id}`)}
              >
                <Pencil className="w-3.5 h-3.5 mr-1" />
                {t('编辑')}
              </Button>
            )}
            {isOwner && (kb.status === 'private' || kb.status === 'rejected') && (
              <Button variant="ghost" size="sm" disabled={acting} onClick={() => handleSubmitKb(kb.id)}>
                <Send className="w-3.5 h-3.5 mr-1" />
                {t('提交审核')}
              </Button>
            )}
            {isOwner && kb.status === 'published' && (
              <Button variant="ghost" size="sm" disabled={acting} onClick={() => handleUnpublishKb(kb.id)}>
                <Undo2 className="w-3.5 h-3.5 mr-1" />
                {t('下架')}
              </Button>
            )}
            {isOwner && (kb.status === 'private' || kb.status === 'rejected') && (
              <Button
                variant="ghost"
                size="sm"
                className="text-red-600 hover:text-red-700"
                disabled={acting}
                onClick={() => setDeleteTarget({ kind: 'kb', id: kb.id, name: kb.name })}
              >
                <Trash2 className="w-3.5 h-3.5 mr-1" />
                {t('删除')}
              </Button>
            )}
          </div>
        </div>
      </div>
    )
  }

  const renderAgentCard = (agent: AIAgent) => (
    <div key={agent.id} data-smoke-card className={cardClass}>
      <CardCover
        cover={agent.coverImage}
        seed={agent.id}
        icon={<span className="text-4xl">{agent.avatar || '🤖'}</span>}
        status={<AIStatusBadge status={agent.status} />}
      />
      <div className="p-4 flex-1 flex flex-col">
        <h3 className="text-[15px] font-semibold text-slate-800 truncate">{agent.name}</h3>
        {agent.description && (
          <p className="text-xs text-slate-400 mt-1 truncate">{agent.description}</p>
        )}
        {agent.status === 'rejected' && agent.reviewComment && (
          <p className="mt-1 text-xs text-red-600">
            {t('驳回原因')}：{agent.reviewComment}
          </p>
        )}
        <div className="flex items-center gap-4 text-[11px] text-slate-400 py-2.5 mt-2 border-b border-slate-50">
          <span className="flex items-center gap-1">
            <MessageSquare className="w-3 h-3" /> {t('{count} 次对话', { count: agent.chatCount })}
          </span>
        </div>
        <div className="flex flex-wrap gap-1 pt-2.5">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.push(`/portal/apps/ai/studio/agents/${agent.id}`)}
          >
            <Pencil className="w-3.5 h-3.5 mr-1" />
            {t('编辑')}
          </Button>
          {(agent.status === 'private' || agent.status === 'rejected') && (
            <Button variant="ghost" size="sm" disabled={acting} onClick={() => handleSubmitAgent(agent.id)}>
              <Send className="w-3.5 h-3.5 mr-1" />
              {t('提交审核')}
            </Button>
          )}
          {agent.status === 'published' && (
            <>
              <Button variant="ghost" size="sm" disabled={acting} onClick={() => handleUnpublishAgent(agent.id)}>
                <Undo2 className="w-3.5 h-3.5 mr-1" />
                {t('下架')}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => router.push(`/portal/apps/ai/agents/${agent.id}`)}
              >
                <MessageSquare className="w-3.5 h-3.5 mr-1" />
                {t('对话')}
              </Button>
            </>
          )}
          {(agent.status === 'private' || agent.status === 'rejected') && (
            <Button
              variant="ghost"
              size="sm"
              className="text-red-600 hover:text-red-700"
              disabled={acting}
              onClick={() => setDeleteTarget({ kind: 'agent', id: agent.id, name: agent.name })}
            >
              <Trash2 className="w-3.5 h-3.5 mr-1" />
              {t('删除')}
            </Button>
          )}
        </div>
      </div>
    </div>
  )

  const renderLoading = (
    <div className="px-4 py-10 flex items-center justify-center gap-2 text-sm text-muted-foreground">
      <Loader2 className="h-4 w-4 animate-spin" />
      {t('加载中...')}
    </div>
  )

  const emptyBox = (text: string) => (
    <div className="rounded-2xl border border-dashed border-border py-10 text-center text-sm text-muted-foreground">
      {text}
    </div>
  )


  const totalMine = myKbs.length + agents.length

  // 类型占比环图：我的知识库 / 我的智能体 / 共享给我的（v2.1，纯前端聚合）
  const typePie = [
    { name: t('知识库'), value: myKbs.length, color: 'hsl(var(--primary))' },
    { name: t('智能体'), value: agents.length, color: '#10b981' },
    { name: t('共享给我的'), value: sharedKbs.length, color: '#f59e0b' },
  ].filter((d) => d.value > 0)
  const totalAll = totalMine + sharedKbs.length

  return (
    <div className="max-w-[1400px] mx-auto">
      {/* 工坊大面板（对标考试中心面板） */}
      <div className="bg-white rounded-2xl border border-[#e7e5e4] shadow-[0_4px_20px_rgba(0,0,0,0.04)] overflow-hidden">
        <div className="px-6 pt-6 pb-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-100">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-2xl bg-primary/10 border border-primary/10 flex items-center justify-center shrink-0">
              <Wrench className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-[#0f172a]">{t('我的工坊')}</h2>
              <p className="text-sm text-slate-500 mt-1 max-w-xl">
                {t('创建并管理你的知识库与智能体，提交审核后发布到广场')}
              </p>
            </div>
          </div>
          <div className="flex gap-2.5 shrink-0">
            <Button
              className="rounded-full px-5 h-10 text-sm font-semibold bg-primary text-white hover:bg-primary/90 hover:-translate-y-0.5 shadow-lg shadow-primary/20 transition-all"
              onClick={() => router.push('/portal/apps/ai/studio/kb/new')}
            >
              <Plus className="w-4 h-4 mr-1" />
              {t('新建知识库')}
            </Button>
            <Button
              variant="outline"
              className="rounded-full px-5 h-10 text-sm font-semibold hover:-translate-y-0.5 transition-all"
              onClick={() => router.push('/portal/apps/ai/studio/agents/new')}
            >
              <Plus className="w-4 h-4 mr-1" />
              {t('新建智能体')}
            </Button>
          </div>
        </div>

        <div className="p-5">
          {kbLoading || agentLoading ? (
            renderLoading
          ) : totalAll === 0 ? (
            emptyBox(t('还没有产出，点击右上角新建知识库或智能体开始'))
          ) : (
            <div className="flex flex-col lg:flex-row gap-5">
              {/* 左栏：类型占比环图（知识库 vs 智能体 vs 共享） */}
              <div className="lg:w-[220px] shrink-0">
                <div className="bg-[#f8fafc] border border-[#eef2f7] rounded-2xl p-4 h-full">
                  <div className="text-sm font-bold text-[#0f172a] flex items-center gap-2 mb-2">
                    <BarChart3 className="w-4 h-4 text-primary" /> {t('类型占比')}
                  </div>
                  <div className="relative">
                    <ResponsiveContainer width="100%" height={130}>
                      <RePieChart>
                        <Pie
                          data={typePie}
                          cx="50%"
                          cy="50%"
                          innerRadius={36}
                          outerRadius={52}
                          paddingAngle={3}
                          dataKey="value"
                          strokeWidth={0}
                        >
                          {typePie.map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={entry.color} />
                          ))}
                        </Pie>
                        <Tooltip formatter={(value: number, name: string) => [t('{n} 项', { n: value }), name]} />
                      </RePieChart>
                    </ResponsiveContainer>
                    <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                      <div className="text-[18px] font-bold text-[#0f172a] leading-none">{totalAll}</div>
                      <div className="text-[11px] text-[#64748b] mt-1">{t('全部')}</div>
                    </div>
                  </div>
                  <div className="space-y-1.5 mt-3">
                    {typePie.map((d) => (
                      <div key={d.name} className="flex items-center justify-between text-xs">
                        <span className="flex items-center gap-2 text-[#475569]">
                          <span className="w-2.5 h-2.5 rounded-full" style={{ background: d.color }} />
                          {d.name}
                        </span>
                        <span className="font-semibold text-[#0f172a]">{d.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              {/* 右栏：混排卡片网格 */}
              <div className="flex-1 min-w-0 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-5 content-start">
                {[
                  ...myKbs.map(renderKbCard),
                  ...agents.map(renderAgentCard),
                  ...sharedKbs.map(renderKbCard),
                ]}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* 新建知识库 */}

      {/* 删除二次确认 */}
      <Dialog open={!!deleteTarget} onOpenChange={(open) => !open && setDeleteTarget(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('确认删除')}</DialogTitle>
            <DialogDescription>
              {t('删除后不可恢复，确定删除「{name}」吗？', { name: deleteTarget?.name ?? '' })}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteTarget(null)}>
              {t('取消')}
            </Button>
            <Button variant="destructive" onClick={handleDelete} disabled={acting}>
              {acting && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
              {t('删除')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 提交审核 warnings 提示（spec §3.1 AG-2：关联私有库对他人不可见） */}
      <Dialog open={!!warnings} onOpenChange={(open) => !open && setWarnings(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('已提交，等待管理员审核')}</DialogTitle>
            <DialogDescription>{t('提交成功，但请注意以下事项')}</DialogDescription>
          </DialogHeader>
          <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
            {(warnings ?? []).map((w, i) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
          <DialogFooter>
            <Button onClick={() => setWarnings(null)}>{t('确认')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/portal-vue/src/views/ai/studio-section.vue
<template>
  <div class="studio-panel">
    <div class="panel-head">
      <div class="head-left">
        <div class="head-icon"><el-icon><Tools /></el-icon></div>
        <div>
          <h2>我的工坊</h2>
          <p>创建并管理你的知识库与智能体，提交审核后发布到广场</p>
        </div>
      </div>
      <div class="head-actions">
        <el-button type="primary" round @click="router.push('/portal/apps/ai/studio/kb/new')">
          <el-icon><Plus /></el-icon>新建知识库
        </el-button>
        <el-button round @click="router.push('/portal/apps/ai/studio/agents/new')">
          <el-icon><Plus /></el-icon>新建智能体
        </el-button>
      </div>
    </div>

    <div class="panel-body">
      <div v-if="loading" class="loading-box">加载中...</div>
      <div v-else-if="totalAll === 0" class="empty-box">还没有产出，点击右上角新建知识库或智能体开始</div>
      <div v-else class="studio-grid">
        <div class="donut-col">
          <div class="donut-card">
            <div class="donut-title"><el-icon><DataLine /></el-icon>类型占比</div>
            <DonutChart :data="typePie" :size="140" :thickness="18">
              <div class="donut-center">
                <div class="donut-total">{{ totalAll }}</div>
                <div class="donut-label">全部</div>
              </div>
            </DonutChart>
            <div class="donut-legend">
              <div v-for="d in typePie" :key="d.name" class="legend-row">
                <span class="legend-dot" :style="{ background: d.color }" />
                <span class="legend-name">{{ d.name }}</span>
                <span class="legend-value">{{ d.value }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="cards-col">
          <div v-for="kb in myKbs" :key="kb.id" class="studio-card">
            <div class="card-cover" :style="coverStyle(kb.coverImage, kb.id)">
              <el-icon v-if="!kb.coverImage" class="cover-icon"><Collection /></el-icon>
              <div class="cover-status"><AiStatusBadge :status="kb.status" /></div>
            </div>
            <div class="card-body">
              <h3 class="card-title">{{ kb.name }}</h3>
              <p v-if="kb.description" class="card-desc">{{ kb.description }}</p>
              <div v-if="kb.tags.length" class="card-tags">
                <el-tag v-for="t in kb.tags" :key="t" size="small" type="info">{{ t }}</el-tag>
              </div>
              <p v-if="kb.status === 'rejected' && kb.reviewComment" class="reject-reason">驳回原因：{{ kb.reviewComment }}</p>
              <div class="card-stats">
                <span><el-icon><Document /></el-icon>{{ kb.docCount }} 个文档</span>
                <span><el-icon><QuestionFilled /></el-icon>{{ kb.askCount }} 次提问</span>
              </div>
              <div class="card-actions">
                <el-button v-if="kbCanEdit(kb)" size="small" text @click="router.push(`/portal/apps/ai/studio/kb/${kb.id}`)">编辑</el-button>
                <el-button v-if="kbIsOwner(kb) && (kb.status === 'private' || kb.status === 'rejected')" size="small" text @click="submitKb(kb.id)">提交审核</el-button>
                <el-button v-if="kbIsOwner(kb) && kb.status === 'published'" size="small" text @click="unpublishKb(kb.id)">下架</el-button>
                <el-button v-if="kbIsOwner(kb) && (kb.status === 'private' || kb.status === 'rejected')" size="small" text type="danger" @click="askDelete('kb', kb.id, kb.name)">删除</el-button>
              </div>
            </div>
          </div>

          <div v-for="a in agents" :key="a.id" class="studio-card">
            <div class="card-cover" :style="coverStyle(a.coverImage, a.id)">
              <span v-if="!a.coverImage" class="cover-emoji">{{ a.avatar || '🤖' }}</span>
              <div class="cover-status"><AiStatusBadge :status="a.status" /></div>
            </div>
            <div class="card-body">
              <h3 class="card-title">{{ a.name }}</h3>
              <p v-if="a.description" class="card-desc">{{ a.description }}</p>
              <p v-if="a.status === 'rejected' && a.reviewComment" class="reject-reason">驳回原因：{{ a.reviewComment }}</p>
              <div class="card-stats">
                <span><el-icon><ChatDotRound /></el-icon>{{ a.chatCount }} 次对话</span>
              </div>
              <div class="card-actions">
                <el-button size="small" text @click="router.push(`/portal/apps/ai/studio/agents/${a.id}`)">编辑</el-button>
                <el-button v-if="a.status === 'private' || a.status === 'rejected'" size="small" text @click="submitAgent(a.id)">提交审核</el-button>
                <template v-if="a.status === 'published'">
                  <el-button size="small" text @click="unpublishAgent(a.id)">下架</el-button>
                  <el-button size="small" text @click="router.push(`/portal/apps/ai/agents/${a.id}`)">对话</el-button>
                </template>
                <el-button v-if="a.status === 'private' || a.status === 'rejected'" size="small" text type="danger" @click="askDelete('agent', a.id, a.name)">删除</el-button>
              </div>
            </div>
          </div>

          <div v-for="kb in sharedKbs" :key="kb.id" class="studio-card">
            <div class="card-cover" :style="coverStyle(kb.coverImage, kb.id)">
              <el-icon v-if="!kb.coverImage" class="cover-icon"><Collection /></el-icon>
              <div class="cover-status"><AiStatusBadge :status="kb.status" /></div>
            </div>
            <div class="card-body">
              <h3 class="card-title">{{ kb.name }}</h3>
              <p v-if="kb.description" class="card-desc">{{ kb.description }}</p>
              <div class="card-stats">
                <span><el-icon><Document /></el-icon>{{ kb.docCount }} 个文档</span>
                <span><el-icon><QuestionFilled /></el-icon>{{ kb.askCount }} 次提问</span>
              </div>
              <div class="card-actions">
                <el-button v-if="kbCanEdit(kb)" size="small" text @click="router.push(`/portal/apps/ai/studio/kb/${kb.id}`)">编辑</el-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 删除确认 -->
    <el-dialog v-model="deleteDialog" title="确认删除" width="440px">
      <p>删除后不可恢复，确定删除「{{ deleteTarget?.name }}」吗？</p>
      <template #footer>
        <el-button @click="deleteDialog = false">取消</el-button>
        <el-button type="danger" :loading="acting" @click="doDelete">删除</el-button>
      </template>
    </el-dialog>

    <!-- 提交审核 warnings -->
    <el-dialog v-model="warningsDialog" title="已提交，等待管理员审核" width="480px">
      <p class="warn-sub">提交成功，但请注意以下事项</p>
      <ul class="warn-list">
        <li v-for="(w, i) in warnings" :key="i">{{ w }}</li>
      </ul>
      <template #footer>
        <el-button type="primary" @click="warningsDialog = false">确认</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { ChatDotRound, Collection, DataLine, Document, Plus, QuestionFilled, Tools } from '@element-plus/icons-vue';
import { aiCenterAgentApi, aiCenterKbApi } from '@/api/ai';
import type { AIAgent, AIKnowledgeBase } from '@/types/ai';
import { aiAgentExt, aiKbExt, coverGradientFor } from './ai-api';
import AiStatusBadge from './components/AiStatusBadge.vue';
import DonutChart from '../landing/DonutChart.vue';

const router = useRouter();

const myKbs = ref<AIKnowledgeBase[]>([]);
const sharedKbs = ref<AIKnowledgeBase[]>([]);
const agents = ref<AIAgent[]>([]);
const loading = ref(true);
const acting = ref(false);
const deleteDialog = ref(false);
const deleteTarget = ref<{ kind: 'kb' | 'agent'; id: string; name: string } | null>(null);
const warningsDialog = ref(false);
const warnings = ref<string[]>([]);

const totalMine = computed(() => myKbs.value.length + agents.value.length);
const totalAll = computed(() => totalMine.value + sharedKbs.value.length);

const typePie = computed(() =>
  [
    { name: '知识库', value: myKbs.value.length, color: '#409eff' },
    { name: '智能体', value: agents.value.length, color: '#10b981' },
    { name: '共享给我的', value: sharedKbs.value.length, color: '#f59e0b' }
  ].filter((d) => d.value > 0)
);

function coverStyle(cover?: string, seed?: string) {
  return cover
    ? { backgroundImage: `url('${cover}')`, backgroundSize: 'cover', backgroundPosition: 'center' }
    : { background: coverGradientFor(seed || '') };
}

function kbCanEdit(kb: AIKnowledgeBase) {
  const role = (kb as AIKnowledgeBase & { myRole?: string }).myRole ?? 'owner';
  return role === 'owner' || role === 'editor';
}
function kbIsOwner(kb: AIKnowledgeBase) {
  return ((kb as AIKnowledgeBase & { myRole?: string }).myRole ?? 'owner') === 'owner';
}

async function loadKbs() {
  try {
    const [mine, shared] = await Promise.all([
      aiKbExt.listMine({ scope: 'owned' }),
      aiKbExt.listMine({ scope: 'collaborating' })
    ]);
    myKbs.value = mine.items;
    sharedKbs.value = shared.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  }
}
async function loadAgents() {
  try {
    const res = await aiCenterAgentApi.listMine();
    agents.value = res.items ?? [];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  }
}

async function load() {
  loading.value = true;
  await Promise.all([loadKbs(), loadAgents()]);
  loading.value = false;
}

async function submitKb(id: string) {
  try {
    await aiKbExt.submit(id);
    ElMessage.success('已提交，等待管理员审核');
    loadKbs();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}
async function unpublishKb(id: string) {
  try {
    await aiKbExt.unpublish(id);
    ElMessage.success('已下架');
    loadKbs();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}
async function submitAgent(id: string) {
  if (acting.value) return;
  acting.value = true;
  try {
    const res = await aiAgentExt.submit(id);
    if (res.warnings && res.warnings.length > 0) {
      warnings.value = res.warnings;
      warningsDialog.value = true;
    } else {
      ElMessage.success('已提交，等待管理员审核');
    }
    loadAgents();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    acting.value = false;
  }
}
async function unpublishAgent(id: string) {
  try {
    await aiAgentExt.unpublish(id);
    ElMessage.success('已下架');
    loadAgents();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

function askDelete(kind: 'kb' | 'agent', id: string, name: string) {
  deleteTarget.value = { kind, id, name };
  deleteDialog.value = true;
}

async function doDelete() {
  if (!deleteTarget.value || acting.value) return;
  acting.value = true;
  try {
    if (deleteTarget.value.kind === 'kb') {
      await aiCenterKbApi.remove(deleteTarget.value.id);
    } else {
      await aiCenterAgentApi.remove(deleteTarget.value.id);
    }
    ElMessage.success('已删除');
    deleteDialog.value = false;
    deleteTarget.value = null;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    acting.value = false;
  }
}

onMounted(load);
</script>

<style scoped>
.studio-panel {
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.04);
  overflow: hidden;
}
.panel-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  padding: 24px;
  border-bottom: 1px solid #f0f0f0;
  flex-wrap: wrap;
}
.head-left {
  display: flex;
  align-items: center;
  gap: 16px;
}
.head-icon {
  width: 48px;
  height: 48px;
  border-radius: 16px;
  background: var(--el-color-primary-light-9);
  border: 1px solid var(--el-color-primary-light-7);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--el-color-primary);
  font-size: 24px;
  flex-shrink: 0;
}
.head-left h2 {
  font-size: 18px;
  font-weight: 700;
  margin: 0;
  color: #0f172a;
}
.head-left p {
  color: #64748b;
  font-size: 14px;
  margin: 4px 0 0;
}
.head-actions {
  display: flex;
  gap: 10px;
  flex-shrink: 0;
}
.panel-body {
  padding: 20px;
}
.loading-box,
.empty-box {
  text-align: center;
  color: #909399;
  font-size: 14px;
  padding: 40px 0;
}
.empty-box {
  border: 1px dashed #e4e7ed;
  border-radius: 16px;
}
.studio-grid {
  display: flex;
  gap: 20px;
  align-items: flex-start;
}
.donut-col {
  width: 220px;
  flex-shrink: 0;
}
.donut-card {
  background: #f8fafc;
  border: 1px solid #eef2f7;
  border-radius: 16px;
  padding: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
}
.donut-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-weight: 700;
  color: #0f172a;
  margin-bottom: 12px;
  width: 100%;
}
.donut-center {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.donut-total {
  font-size: 18px;
  font-weight: 700;
  color: #0f172a;
  line-height: 1;
}
.donut-label {
  font-size: 11px;
  color: #64748b;
  margin-top: 4px;
}
.donut-legend {
  width: 100%;
  margin-top: 12px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.legend-row {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}
.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
}
.legend-name {
  flex: 1;
  color: #475569;
}
.legend-value {
  font-weight: 600;
  color: #0f172a;
}
.cards-col {
  flex: 1;
  min-width: 0;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 20px;
  align-content: start;
}
.studio-card {
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.04);
  transition: all 0.2s;
}
.studio-card:hover {
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.1);
  transform: translateY(-4px);
}
.card-cover {
  height: 96px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
}
.cover-icon {
  font-size: 40px;
  color: rgba(255, 255, 255, 0.8);
}
.cover-emoji {
  font-size: 40px;
}
.cover-status {
  position: absolute;
  top: 12px;
  right: 12px;
}
.card-body {
  padding: 16px;
  flex: 1;
  display: flex;
  flex-direction: column;
}
.card-title {
  font-size: 15px;
  font-weight: 600;
  color: #1f2937;
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.card-desc {
  color: #9ca3af;
  font-size: 12px;
  margin: 4px 0 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.card-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 6px;
}
.reject-reason {
  color: #f56c6c;
  font-size: 12px;
  margin: 6px 0 0;
}
.card-stats {
  display: flex;
  gap: 16px;
  color: #9ca3af;
  font-size: 11px;
  padding: 10px 0;
  margin-top: 8px;
  border-bottom: 1px solid #f8fafc;
}
.card-stats span {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.card-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  padding-top: 10px;
}
.warn-sub {
  color: #909399;
  margin: 0 0 12px;
}
.warn-list {
  margin: 0;
  padding-left: 20px;
  color: #606266;
  font-size: 14px;
}
</style>
