// apps/edu/app/portal/apps/system/org-user/org-types/page.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { FormFieldRow } from '@/components/shared/form-field-row'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty'
import { Spinner } from '@/components/ui/spinner'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Plus, Pencil, Trash2, Search, Upload, Download, AlertCircle } from 'lucide-react'
import { orgTypeApi } from '@/lib/api'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { TableRowActions } from '@/components/shared/table-row-actions'
import type { OrgType } from '@/lib/types/backend'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { useToast } from '@zhiyu/ui'

const categoryLabels = { internal: '内部组织', business: '业务组织', external: '外部协作组织' }
const categoryColors = {
  internal: 'bg-blue-100 text-blue-700',
  business: 'bg-green-100 text-green-700',
  external: 'bg-orange-100 text-orange-700',
}

export default function OrgTypesPage() {
  const { tenantId } = usePortalAuth()
  const { toast } = useToast()
  const [orgTypes, setOrgTypes] = useState<OrgType[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [selectedType, setSelectedType] = useState<OrgType | null>(null)
  const [searchTerm, setSearchTerm] = useState('')
  const [formName, setFormName] = useState('')
  const [formCategory, setFormCategory] = useState<string>('internal')
  const [isSaving, setIsSaving] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<OrgType | null>(null)

  const fetchData = useCallback(async () => {
    if (!tenantId) {
      setIsLoading(false)
      setError('未获取到租户信息，请重新登录')
      return
    }
    setIsLoading(true)
    setError(null)
    try {
      const res = await orgTypeApi.list({ tenantId, search: searchTerm || undefined, limit: 1000 })
      setOrgTypes(res.items)
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载组织类型失败')
    } finally {
      setIsLoading(false)
    }
  }, [tenantId, searchTerm])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      if (!cancelled) await fetchData()
    })()
    return () => {
      cancelled = true
    }
  }, [fetchData])

  const filteredTypes = orgTypes.filter((type) => type.name.includes(searchTerm))

  const confirmDelete = async () => {
    if (!deleteTarget) return
    try {
      await orgTypeApi.delete(deleteTarget.id)
      setOrgTypes((prev) => prev.filter((t) => t.id !== deleteTarget.id))
      setDeleteTarget(null)
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '删除失败',
        description: err instanceof Error ? err.message : '删除组织类型失败',
      })
    }
  }

  return (
    <div className="min-h-full">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground">组织类型管理</h1>
          <p className="mt-1 text-sm text-muted-foreground">管理组织架构中的节点类型</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" disabled title="即将上线">
            <Upload className="h-4 w-4 mr-1" />
            批量导入
          </Button>
          <Button variant="outline" size="sm" disabled title="即将上线">
            <Download className="h-4 w-4 mr-1" />
            批量导出
          </Button>
          <Button
            size="sm"
            onClick={() => {
              setSelectedType(null)
              setFormName('')
              setFormCategory('internal')
              setIsDialogOpen(true)
            }}
          >
            <Plus className="h-4 w-4 mr-1" />
            新增类型
          </Button>
        </div>
      </div>

      <div className="mb-4">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="搜索类型名称..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9"
          />
        </div>
      </div>

      {error && (
        <Alert variant="destructive" className="mb-4">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>加载失败</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {isLoading ? (
        <div className="flex h-64 items-center justify-center gap-2 text-muted-foreground">
          <Spinner className="h-5 w-5" />
          加载中...
        </div>
      ) : (
        <>
          <div className="rounded-lg border border-gray-100 bg-white shadow-sm">
            <Table>
              <TableHeader>
                <TableRow className="border-border">
                  <TableHead>类型名称</TableHead>
                  <TableHead>类型分类</TableHead>
                  <TableHead>创建时间</TableHead>
                  <TableHead className="text-right">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredTypes.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={4} className="h-48 text-center">
                      <Empty className="h-full">
                        <EmptyHeader>
                          <EmptyTitle>暂无组织类型</EmptyTitle>
                          <EmptyDescription>
                            {searchTerm ? '未找到匹配的组织类型' : '当前租户下尚未创建组织类型'}
                          </EmptyDescription>
                        </EmptyHeader>
                      </Empty>
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredTypes.map((type) => (
                    <TableRow key={type.id} className="border-border group">
                      <TableCell className="font-medium">
                        <div className="flex items-center gap-2">
                          {type.name}
                          {type.isDefault && (
                            <Badge variant="outline" className="text-xs">
                              系统默认
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge className={categoryColors[type.category]}>
                          {categoryLabels[type.category]}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-muted-foreground">{type.createdAt}</TableCell>
                      <TableRowActions>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() => {
                            setSelectedType(type)
                            setFormName(type.name)
                            setFormCategory(type.category)
                            setIsDialogOpen(true)
                          }}
                        >
                          <Pencil className="mr-1 h-3 w-3" />
                          编辑
                        </Button>
                        {!type.isDefault ? (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                            onClick={() => setDeleteTarget(type)}
                          >
                            <Trash2 className="mr-1 h-3 w-3" />
                            删除
                          </Button>
                        ) : (
                          <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" disabled>
                            <Trash2 className="mr-1 h-3 w-3" />
                            系统默认类型不可删除
                          </Button>
                        )}
                      </TableRowActions>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          <div className="mt-4 text-sm text-muted-foreground">共 {filteredTypes.length} 条记录</div>
        </>
      )}

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{selectedType ? '编辑类型' : '新增类型'}</DialogTitle>
            <DialogDescription>组织类型用于组织架构节点分类</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <FormFieldRow label="类型名称">
              <Input
                placeholder="如：二级学院"
                value={formName}
                onChange={(e) => setFormName(e.target.value)}
              />
            </FormFieldRow>
            <FormFieldRow label="类型分类">
              <Select value={formCategory} onValueChange={setFormCategory}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="internal">内部组织</SelectItem>
                  <SelectItem value="business">业务组织</SelectItem>
                  <SelectItem value="external">外部协作组织</SelectItem>
                </SelectContent>
              </Select>
            </FormFieldRow>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)} disabled={isSaving}>
              取消
            </Button>
            <Button
              disabled={isSaving || !formName.trim()}
              onClick={async () => {
                setIsSaving(true)
                try {
                  if (selectedType) {
                    const updated = await orgTypeApi.update(selectedType.id, {
                      name: formName.trim(),
                      category: formCategory as OrgType['category'],
                      tenantId: tenantId!,
                    })
                    setOrgTypes((prev) => prev.map((t) => (t.id === updated.id ? updated : t)))
                  } else {
                    const created = await orgTypeApi.create({
                      name: formName.trim(),
                      category: formCategory as OrgType['category'],
                      tenantId: tenantId!,
                    })
                    setOrgTypes((prev) => [...prev, created])
                  }
                  setIsDialogOpen(false)
                } catch (err) {
                  toast({
                    variant: 'destructive',
                    title: selectedType ? '保存失败' : '创建失败',
                    description: err instanceof Error ? err.message : '保存组织类型失败',
                  })
                } finally {
                  setIsSaving(false)
                }
              }}
            >
              {isSaving ? '保存中...' : '保存'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(open) => !open && setDeleteTarget(null)}
        title="确认删除"
        description={`确定删除组织类型「${deleteTarget?.name}」吗？如果该类型仍被组织使用，删除可能会失败。`}
        confirmText="删除"
        variant="destructive"
        onConfirm={confirmDelete}
      />
    </div>
  )
}

// plus-ui/src-portal/views/system/org-types.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <span class="card-title">组织类型管理</span>
            <span class="card-sub">管理组织架构中的节点类型</span>
          </div>
          <el-button type="primary" @click="openDialog()">新建类型</el-button>
        </div>
      </template>

      <el-input v-model="keyword" placeholder="搜索类型名称..." clearable style="max-width: 320px; margin-bottom: 12px" />

      <el-table v-loading="loading" :data="filtered" stripe>
        <el-table-column label="类型名称" min-width="160">
          <template #default="{ row }">
            <span class="type-name">{{ row.name }}</span>
            <el-tag v-if="row.isDefault" size="small" class="default-tag">系统默认</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="类型分类" width="160">
          <template #default="{ row }">
            <el-tag :type="categoryTagType(row.category)">{{ categoryLabel(row.category) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" min-width="160" show-overflow-tooltip />
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openDialog(row)">编辑</el-button>
            <el-button v-if="!row.isDefault" size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
            <el-button v-else size="small" type="info" disabled>系统默认类型不可删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新建/编辑 -->
    <el-dialog v-model="dialog" :title="editing ? '编辑组织类型' : '新建组织类型'" width="440px">
      <el-form label-width="90px">
        <el-form-item label="类型名称" required><el-input v-model="form.name" placeholder="如：二级学院" /></el-form-item>
        <el-form-item label="类型分类" required>
          <el-select v-model="form.category" style="width: 100%">
            <el-option label="内部组织" value="internal" />
            <el-option label="业务组织" value="business" />
            <el-option label="外部协作组织" value="external" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { orgTypeApi } from '@/api/system';
import { useAuthStore } from '@/stores/auth';
import type { OrgType } from '@/types/system';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const items = ref<OrgType[]>([]);
const loading = ref(false);
const keyword = ref('');
const dialog = ref(false);
const saving = ref(false);
const editing = ref<OrgType | null>(null);
const form = reactive({ name: '', category: 'internal' as OrgType['category'] });

const filtered = computed(() => {
  const q = keyword.value.trim();
  if (!q) return items.value;
  return items.value.filter((i) => i.name.includes(q));
});

function categoryLabel(c: string) {
  const map: Record<string, string> = { internal: '内部组织', business: '业务组织', external: '外部协作组织' };
  return map[c] || c;
}
function categoryTagType(c: string) {
  if (c === 'internal') return 'primary';
  if (c === 'business') return 'success';
  return 'warning';
}

async function load() {
  loading.value = true;
  try {
    const res = await orgTypeApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 1000 });
    items.value = res.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function openDialog(row?: OrgType) {
  editing.value = row || null;
  form.name = row?.name || '';
  form.category = row?.category || 'internal';
  dialog.value = true;
}

async function save() {
  if (!form.name.trim()) {
    ElMessage.warning('请输入类型名称');
    return;
  }
  saving.value = true;
  try {
    const payload = { ...(tenantId.value ? { tenantId: tenantId.value } : {}), name: form.name.trim(), category: form.category };
    if (editing.value) {
      await orgTypeApi.update(editing.value.id, payload);
      ElMessage.success('保存成功');
    } else {
      await orgTypeApi.create(payload);
      ElMessage.success('创建成功');
    }
    dialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function confirmDelete(row: OrgType) {
  try {
    await ElMessageBox.confirm(`确定删除组织类型「${row.name}」吗？如果该类型仍被组织使用，删除可能会失败。`, '确认删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  try {
    await orgTypeApi.delete(row.id);
    ElMessage.success('删除成功');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; margin-left: 8px; }
.type-name { font-weight: 500; }
.default-tag { margin-left: 8px; }
</style>
