// apps/edu/app/portal/apps/system/org-user/relations/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { TableCell, TableHead } from '@/components/ui/table'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Trash2 } from 'lucide-react'
import { portalUserRelationApi } from '@/lib/api'
import { useToast, useAsync } from '@zhiyu/ui'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { UserSelector } from '@/components/shared/user-selector'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { PortalCrudPage } from '@/components/shared/portal-crud-page'

interface RelationItem {
  id: string
  initiatorId: string
  initiatorName?: string
  initiatorDept?: string
  targetId: string
  targetName?: string
  targetDept?: string
  relationType: string
  createdAt?: string
}

const relationTypes = [
  { value: 'superior', label: '上下级' },
  { value: 'collaboration', label: '业务协同' },
  { value: 'management', label: '管理关系' },
  { value: 'service', label: '服务关系' },
  { value: 'project', label: '项目参与' },
  { value: 'external', label: '外部合作' },
]

const typeLabelMap: Record<string, string> = Object.fromEntries(
  relationTypes.map((t) => [t.value, t.label]),
)

export default function RelationsPage() {
  const { toast } = useToast()
  const { tenantId } = usePortalAuth()
  const [searchText, setSearchText] = useState('')

  const {
    data: relations,
    loading,
    error,
    refresh,
  } = useAsync(
    async () => {
      const res = await portalUserRelationApi.list({ search: searchText || undefined })
      return res.items as RelationItem[]
    },
    { deps: [searchText], onError: () => true },
  )

  const handleCreate = async (item: RelationItem) => {
    try {
      await portalUserRelationApi.create({
        initiatorId: item.initiatorId,
        targetId: item.targetId,
        relationType: item.relationType,
      })
      toast({ title: '创建成功' })
      setSearchText('')
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '创建失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await portalUserRelationApi.delete(id)
      toast({ title: '删除成功' })
      await refresh()
    } catch (err) {
      toast({
        variant: 'destructive',
        title: '删除失败',
        description: err instanceof Error ? err.message : '未知错误',
      })
    }
  }

  return (
    <PortalCrudPage<RelationItem>
      title="人员关系管理"
      description="维护用户之间的上下级、协同等业务关系"
      entityLabel="关系"
      items={relations ?? []}
      loading={loading}
      error={error?.message ?? null}
      onRetry={refresh}
      colSpan={8}
      searchPlaceholder="搜索关系..."
      searchValue={searchText}
      onSearchChange={setSearchText}
      hideImport
      createButtonLabel="新建人员关系"
      createDefault={() => ({ id: '', initiatorId: '', targetId: '', relationType: '' })}
      renderForm={(item, setItem) => (
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">关系发起人</label>
            <UserSelector
              value={item.initiatorId ? [item.initiatorId] : []}
              onChange={(ids) => setItem({ ...item, initiatorId: ids[0] || '' })}
              multiple={false}
              placeholder="搜索选择用户..."
              tenantId={tenantId}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">关系目标人</label>
            <UserSelector
              value={item.targetId ? [item.targetId] : []}
              onChange={(ids) => setItem({ ...item, targetId: ids[0] || '' })}
              multiple={false}
              placeholder="搜索选择用户..."
              tenantId={tenantId}
            />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">关系类型</label>
            <Select
              value={item.relationType}
              onValueChange={(v) => setItem({ ...item, relationType: v })}
            >
              <SelectTrigger>
                <SelectValue placeholder="请选择关系类型" />
              </SelectTrigger>
              <SelectContent>
                {relationTypes.map((type) => (
                  <SelectItem key={type.value} value={type.value}>
                    {type.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
      )}
      onSave={async (item) => {
        await handleCreate(item)
      }}
      renderTableHeader={() => (
        <>
          <TableHead className="w-12">序号</TableHead>
          <TableHead>关系发起人</TableHead>
          <TableHead>所属部门</TableHead>
          <TableHead>关系目标人</TableHead>
          <TableHead>所属部门</TableHead>
          <TableHead>关系类型</TableHead>
          <TableHead>创建时间</TableHead>
          <TableHead className="w-32 text-center">操作</TableHead>
        </>
      )}
      renderTableRow={(relation, actions) => (
        <>
          <TableCell className="text-muted-foreground">
            {(relations ?? []).indexOf(relation) + 1}
          </TableCell>
          <TableCell className="font-medium">{relation.initiatorName}</TableCell>
          <TableCell className="text-muted-foreground">{relation.initiatorDept || '—'}</TableCell>
          <TableCell className="font-medium">{relation.targetName}</TableCell>
          <TableCell className="text-muted-foreground">{relation.targetDept || '—'}</TableCell>
          <TableCell>
            <span className="px-2 py-1 rounded text-xs bg-primary/10 text-primary">
              {typeLabelMap[relation.relationType] || relation.relationType}
            </span>
          </TableCell>
          <TableCell className="text-muted-foreground">{relation.createdAt}</TableCell>
          <TableRowActions>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
              onClick={actions.delete}
            >
              <Trash2 className="mr-1 h-3 w-3" />
              删除
            </Button>
          </TableRowActions>
        </>
      )}
      getDeleteDescription={() => <>确定要删除该关系吗？此操作不可撤销。</>}
      onDelete={async (relation) => {
        await handleDelete(relation.id)
      }}
    />
  )
}

// plus-ui/src-portal/views/system/relations.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <span class="card-title">人员关系管理</span>
            <span class="card-sub">维护用户之间的上下级、协同等业务关系</span>
          </div>
          <el-button type="primary" @click="openDialog()">新建人员关系</el-button>
        </div>
      </template>

      <el-input v-model="searchText" placeholder="搜索关系..." clearable style="max-width: 320px; margin-bottom: 12px" />

      <el-table v-loading="loading" :data="relations" stripe>
        <el-table-column label="序号" width="60">
          <template #default="{ $index }">{{ $index + 1 }}</template>
        </el-table-column>
        <el-table-column prop="initiatorName" label="关系发起人" min-width="120" show-overflow-tooltip />
        <el-table-column prop="initiatorDept" label="所属部门" min-width="140" show-overflow-tooltip>
          <template #default="{ row }">{{ row.initiatorDept || '—' }}</template>
        </el-table-column>
        <el-table-column prop="targetName" label="关系目标人" min-width="120" show-overflow-tooltip />
        <el-table-column prop="targetDept" label="所属部门" min-width="140" show-overflow-tooltip>
          <template #default="{ row }">{{ row.targetDept || '—' }}</template>
        </el-table-column>
        <el-table-column label="关系类型" width="120">
          <template #default="{ row }">
            <el-tag size="small">{{ typeLabel(row.relationType) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" min-width="160" show-overflow-tooltip />
        <el-table-column label="操作" width="90" fixed="right">
          <template #default="{ row }">
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新建人员关系 -->
    <el-dialog v-model="dialog" title="新建人员关系" width="480px">
      <el-form label-width="100px">
        <el-form-item label="关系发起人" required>
          <el-select
            v-model="form.initiatorId"
            filterable
            remote
            :remote-method="searchInitiators"
            :loading="initiatorLoading"
            placeholder="搜索选择用户..."
            style="width: 100%"
          >
            <el-option v-for="u in initiatorOptions" :key="u.id" :label="u.name" :value="u.id">
              <span>{{ u.name }}</span>
              <span class="opt-sub">{{ u.username || u.loginName }}</span>
            </el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="关系目标人" required>
          <el-select
            v-model="form.targetId"
            filterable
            remote
            :remote-method="searchTargets"
            :loading="targetLoading"
            placeholder="搜索选择用户..."
            style="width: 100%"
          >
            <el-option v-for="u in targetOptions" :key="u.id" :label="u.name" :value="u.id">
              <span>{{ u.name }}</span>
              <span class="opt-sub">{{ u.username || u.loginName }}</span>
            </el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="关系类型" required>
          <el-select v-model="form.relationType" placeholder="请选择关系类型" style="width: 100%">
            <el-option v-for="t in relationTypes" :key="t.value" :label="t.label" :value="t.value" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '@/api/http';
import { userManagementApi } from '@/api/portal';
import { useAuthStore } from '@/stores/auth';
import type { User } from '@/types/user';

interface RelationItem {
  id: string;
  initiatorId: string;
  initiatorName?: string;
  initiatorDept?: string;
  targetId: string;
  targetName?: string;
  targetDept?: string;
  relationType: string;
  createdAt?: string;
}

const relationTypes = [
  { value: 'superior', label: '上下级' },
  { value: 'collaboration', label: '业务协同' },
  { value: 'management', label: '管理关系' },
  { value: 'service', label: '服务关系' },
  { value: 'project', label: '项目参与' },
  { value: 'external', label: '外部合作' }
];

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const relations = ref<RelationItem[]>([]);
const loading = ref(false);
const searchText = ref('');

const dialog = ref(false);
const saving = ref(false);
const form = reactive({ initiatorId: '', targetId: '', relationType: '' });

const initiatorOptions = ref<User[]>([]);
const targetOptions = ref<User[]>([]);
const initiatorLoading = ref(false);
const targetLoading = ref(false);

function typeLabel(v: string) {
  return relationTypes.find((t) => t.value === v)?.label || v;
}

async function load() {
  loading.value = true;
  try {
    const q = searchText.value.trim();
    const res = await request<{ items: RelationItem[]; total: number }>(
      `/user-relations${q ? `?search=${encodeURIComponent(q)}` : ''}`
    );
    relations.value = res.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

async function searchUsers(q: string): Promise<User[]> {
  const res = await userManagementApi.list({
    ...(tenantId.value ? { tenantId: tenantId.value } : {}),
    ...(q ? { search: q } : {}),
    limit: 20
  });
  return res.items;
}

async function searchInitiators(q: string) {
  initiatorLoading.value = true;
  try {
    initiatorOptions.value = await searchUsers(q);
  } catch (e) {
    ElMessage.error((e as Error).message || '搜索用户失败');
  } finally {
    initiatorLoading.value = false;
  }
}

async function searchTargets(q: string) {
  targetLoading.value = true;
  try {
    targetOptions.value = await searchUsers(q);
  } catch (e) {
    ElMessage.error((e as Error).message || '搜索用户失败');
  } finally {
    targetLoading.value = false;
  }
}

function openDialog() {
  form.initiatorId = '';
  form.targetId = '';
  form.relationType = '';
  initiatorOptions.value = [];
  targetOptions.value = [];
  dialog.value = true;
}

async function save() {
  if (!form.initiatorId || !form.targetId || !form.relationType) {
    ElMessage.warning('请选择关系发起人、目标人与关系类型');
    return;
  }
  if (form.initiatorId === form.targetId) {
    ElMessage.warning('发起人与目标人不能相同');
    return;
  }
  saving.value = true;
  try {
    await request('/user-relations', {
      method: 'POST',
      body: JSON.stringify({ initiatorId: form.initiatorId, targetId: form.targetId, relationType: form.relationType })
    });
    ElMessage.success('创建成功');
    dialog.value = false;
    searchText.value = '';
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '创建失败');
  } finally {
    saving.value = false;
  }
}

async function confirmDelete(row: RelationItem) {
  try {
    await ElMessageBox.confirm('确定要删除该关系吗？此操作不可撤销。', '确认删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  try {
    await request(`/user-relations/${row.id}`, { method: 'DELETE' });
    ElMessage.success('删除成功');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

// 搜索防抖：输入停止 300ms 后重新拉取
let debounceTimer: ReturnType<typeof setTimeout> | undefined;
watch(searchText, () => {
  if (debounceTimer) clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => load(), 300);
});

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; margin-left: 8px; }
.opt-sub { float: right; color: #c0c4cc; font-size: 12px; margin-left: 12px; }
</style>
