// frontend/portal-vue/src/views/portal/apps/alliance/employmentjob.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div class="page-title">岗位与投递</div>
      <div class="page-sub">管理服务大厅岗位发布状态，查看学生投递记录。</div>
    </div>

    <el-card shadow="never">
      <el-tabs v-model="activeTab">
        <el-tab-pane label="岗位" name="jobs">
          <div class="filters">
            <el-input v-model="jobSearch" placeholder="搜索岗位名称..." clearable style="max-width: 240px" @input="onJobSearchInput" @clear="reloadJobs" @keyup.enter="reloadJobs" />
            <el-select v-model="jobStatus" style="width: 120px" @change="onJobFilterChange">
              <el-option label="全部状态" value="all" />
              <el-option v-for="(label, v) in EMPLOYMENT_JOB_STATUS_LABELS" :key="v" :label="label" :value="v" />
            </el-select>
            <el-select v-model="jobProjectId" style="width: 160px" @change="onJobFilterChange">
              <el-option label="全部项目" value="all" />
              <el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id" />
            </el-select>
            <el-select v-model="jobEnterpriseId" style="width: 160px" @change="onJobFilterChange">
              <el-option label="全部企业" value="all" />
              <el-option v-for="e in enterprises" :key="e.id" :label="e.name" :value="e.id" />
            </el-select>
          </div>

          <el-table v-loading="jobsLoading" :data="jobs" stripe>
            <el-table-column prop="title" label="岗位" min-width="160" show-overflow-tooltip />
            <el-table-column label="企业" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.enterpriseName || '-' }}</template></el-table-column>
            <el-table-column label="项目" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.projectName || '独立岗位' }}</template></el-table-column>
            <el-table-column label="类型" width="90"><template #default="{ row }">{{ EMPLOYMENT_JOB_TYPE_LABELS[row.jobType] ?? row.jobType }}</template></el-table-column>
            <el-table-column label="状态" width="100">
              <template #default="{ row }">
                <el-tag :type="jobStatusTagType(row.status)">{{ EMPLOYMENT_JOB_STATUS_LABELS[row.status] ?? row.status }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="applicationCount" label="投递数" width="80" />
            <el-table-column label="创建时间" width="160"><template #default="{ row }">{{ formatDateTime(row.createdAt) }}</template></el-table-column>
            <el-table-column label="操作" width="90" fixed="right">
              <template #default="{ row }">
                <span v-if="row.status === 'draft'" class="muted">-</span>
                <el-button v-else size="small" text type="primary" @click="changeStatus(row)">{{ row.status === 'published' ? '下架' : '恢复' }}</el-button>
              </template>
            </el-table-column>
          </el-table>

          <div class="pager-row">
            <span class="total-text">共 {{ jobTotal }} 条记录</span>
            <el-pagination
              v-if="jobTotal > JOB_PAGE_SIZE"
              v-model:current-page="jobPage"
              :page-size="JOB_PAGE_SIZE"
              :total="jobTotal"
              layout="prev, pager, next"
              @current-change="loadJobs"
            />
          </div>
        </el-tab-pane>

        <el-tab-pane label="投递" name="applications">
          <div class="filters">
            <el-input v-model="appSearch" placeholder="搜索学生姓名..." clearable style="max-width: 240px" @input="onAppSearchInput" @clear="reloadApps" @keyup.enter="reloadApps" />
            <el-select v-model="appProjectId" style="width: 160px" @change="onAppFilterChange">
              <el-option label="全部项目" value="all" />
              <el-option v-for="p in projects" :key="p.id" :label="p.name" :value="p.id" />
            </el-select>
            <el-select v-model="appEnterpriseId" style="width: 160px" @change="onAppFilterChange">
              <el-option label="全部企业" value="all" />
              <el-option v-for="e in enterprises" :key="e.id" :label="e.name" :value="e.id" />
            </el-select>
          </div>

          <el-table v-loading="appsLoading" :data="apps" stripe>
            <el-table-column label="学生" min-width="120"><template #default="{ row }">{{ row.studentName || '-' }}</template></el-table-column>
            <el-table-column label="学号" min-width="120"><template #default="{ row }">{{ row.studentNo || '-' }}</template></el-table-column>
            <el-table-column label="专业" min-width="120" show-overflow-tooltip><template #default="{ row }">{{ row.majorName || '-' }}</template></el-table-column>
            <el-table-column label="班级" min-width="120" show-overflow-tooltip><template #default="{ row }">{{ row.className || '-' }}</template></el-table-column>
            <el-table-column label="岗位" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.jobTitle || '-' }}</template></el-table-column>
            <el-table-column label="企业" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.enterpriseName || '-' }}</template></el-table-column>
            <el-table-column label="项目" min-width="140" show-overflow-tooltip><template #default="{ row }">{{ row.projectName || '-' }}</template></el-table-column>
            <el-table-column label="投递时间" width="160"><template #default="{ row }">{{ formatDateTime(row.createdAt) }}</template></el-table-column>
            <el-table-column label="操作" width="80" fixed="right">
              <template #default="{ row }">
                <el-button size="small" text type="primary" @click="viewing = row">查看</el-button>
              </template>
            </el-table-column>
          </el-table>

          <div class="pager-row">
            <span class="total-text">共 {{ appTotal }} 条记录</span>
            <el-pagination
              v-if="appTotal > JOB_PAGE_SIZE"
              v-model:current-page="appPage"
              :page-size="JOB_PAGE_SIZE"
              :total="appTotal"
              layout="prev, pager, next"
              @current-change="loadApps"
            />
          </div>
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <el-dialog v-model="viewDialog" title="投递详情" width="520px">
      <el-descriptions v-if="viewing" :column="1" border>
        <el-descriptions-item label="学生">{{ viewing.studentName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="学号">{{ viewing.studentNo || '-' }}</el-descriptions-item>
        <el-descriptions-item label="专业">{{ viewing.majorName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="班级">{{ viewing.className || '-' }}</el-descriptions-item>
        <el-descriptions-item label="联系电话">{{ viewing.phone || '-' }}</el-descriptions-item>
        <el-descriptions-item label="邮箱">{{ viewing.email || '-' }}</el-descriptions-item>
        <el-descriptions-item label="岗位">{{ viewing.jobTitle || '-' }}</el-descriptions-item>
        <el-descriptions-item label="企业">{{ viewing.enterpriseName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="项目">{{ viewing.projectName || '-' }}</el-descriptions-item>
        <el-descriptions-item label="投递时间">{{ formatDateTime(viewing.createdAt) }}</el-descriptions-item>
        <el-descriptions-item label="求职信"><span class="pre-wrap">{{ viewing.coverLetter || '-' }}</span></el-descriptions-item>
      </el-descriptions>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { portalRequest, buildQuery } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import {
  EMPLOYMENT_JOB_TYPE_LABELS,
  EMPLOYMENT_JOB_STATUS_LABELS,
  formatDateTime,
} from './alliance-admin';
import type { EmploymentJob, EmploymentProject, EmploymentApplication, ListResponse } from './alliance-admin';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const JOB_PAGE_SIZE = 20;
const activeTab = ref('jobs');

const projects = ref<{ id: string; name: string }[]>([]);
const enterprises = ref<{ id: string; name: string }[]>([]);

// 岗位
const jobs = ref<EmploymentJob[]>([]);
const jobsLoading = ref(false);
const jobTotal = ref(0);
const jobPage = ref(1);
const jobSearch = ref('');
const jobStatus = ref('all');
const jobProjectId = ref('all');
const jobEnterpriseId = ref('all');

// 投递
const apps = ref<EmploymentApplication[]>([]);
const appsLoading = ref(false);
const appTotal = ref(0);
const appPage = ref(1);
const appSearch = ref('');
const appProjectId = ref('all');
const appEnterpriseId = ref('all');

const viewing = ref<EmploymentApplication | null>(null);
const viewDialog = ref(false);

function jobStatusTagType(s: string): 'success' | 'warning' | 'info' {
  if (s === 'published') return 'success';
  if (s === 'closed') return 'info';
  return 'warning';
}

async function loadRefs() {
  if (!tenantId.value) return;
  try {
    const [p, e] = await Promise.all([
      portalRequest<ListResponse<EmploymentProject>>('/alliance/employment-projects?limit=200'),
      portalRequest<ListResponse<{ id: string; name: string }>>('/alliance/enterprises?limit=200'),
    ]);
    projects.value = (p.items || []).map((x) => ({ id: x.id, name: x.name }));
    enterprises.value = (e.items || []).map((x) => ({ id: x.id, name: x.name }));
  } catch {
    // 筛选数据源加载失败不阻断主流程
  }
}

async function loadJobs() {
  if (!tenantId.value) return;
  jobsLoading.value = true;
  try {
    const res = await portalRequest<ListResponse<EmploymentJob>>(
      `/alliance/employment-jobs${buildQuery({
        limit: JOB_PAGE_SIZE,
        offset: (jobPage.value - 1) * JOB_PAGE_SIZE,
        search: jobSearch.value.trim() || undefined,
        status: jobStatus.value === 'all' ? undefined : jobStatus.value,
        projectId: jobProjectId.value === 'all' ? undefined : jobProjectId.value,
        enterpriseId: jobEnterpriseId.value === 'all' ? undefined : jobEnterpriseId.value,
      })}`,
    );
    jobs.value = res.items || [];
    jobTotal.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载岗位失败');
  } finally {
    jobsLoading.value = false;
  }
}

async function loadApps() {
  if (!tenantId.value) return;
  appsLoading.value = true;
  try {
    const res = await portalRequest<ListResponse<EmploymentApplication>>(
      `/alliance/employment-applications${buildQuery({
        limit: JOB_PAGE_SIZE,
        offset: (appPage.value - 1) * JOB_PAGE_SIZE,
        search: appSearch.value.trim() || undefined,
        projectId: appProjectId.value === 'all' ? undefined : appProjectId.value,
        enterpriseId: appEnterpriseId.value === 'all' ? undefined : appEnterpriseId.value,
      })}`,
    );
    apps.value = res.items || [];
    appTotal.value = res.total ?? 0;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载投递失败');
  } finally {
    appsLoading.value = false;
  }
}

let jobTimer: ReturnType<typeof setTimeout> | undefined;
function onJobSearchInput() {
  if (jobTimer) clearTimeout(jobTimer);
  jobTimer = setTimeout(() => {
    jobPage.value = 1;
    loadJobs();
  }, 300);
}
function reloadJobs() {
  if (jobTimer) clearTimeout(jobTimer);
  jobPage.value = 1;
  loadJobs();
}
function onJobFilterChange() {
  jobPage.value = 1;
  loadJobs();
}

let appTimer: ReturnType<typeof setTimeout> | undefined;
function onAppSearchInput() {
  if (appTimer) clearTimeout(appTimer);
  appTimer = setTimeout(() => {
    appPage.value = 1;
    loadApps();
  }, 300);
}
function reloadApps() {
  if (appTimer) clearTimeout(appTimer);
  appPage.value = 1;
  loadApps();
}
function onAppFilterChange() {
  appPage.value = 1;
  loadApps();
}

async function changeStatus(job: EmploymentJob) {
  if (job.status === 'draft') return;
  const next = job.status === 'published' ? 'closed' : 'published';
  try {
    await portalRequest(`/alliance/employment-jobs/${job.id}/status`, {
      method: 'PUT',
      body: JSON.stringify({ status: next }),
    });
    ElMessage.success(next === 'closed' ? '已下架' : '已恢复');
    await loadJobs();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

onMounted(() => {
  loadRefs();
  loadJobs();
  loadApps();
});
</script>

<style scoped>
.list-page { padding: 16px; }
.page-head { margin-bottom: 16px; }
.page-title { font-size: 20px; font-weight: 600; }
.page-sub { margin-top: 4px; font-size: 13px; color: #909399; }
.filters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }
.pager-row { display: flex; align-items: center; justify-content: space-between; margin-top: 16px; }
.total-text { font-size: 13px; color: #909399; }
.muted { font-size: 13px; color: #909399; }
.pre-wrap { white-space: pre-wrap; word-break: break-word; }
</style>

// frontend/edu/app/portal/apps/alliance/employmentjob/page.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { SearchInput } from '@/components/shared/search-input'
import { PaginationBar } from '@/components/shared/pagination-bar'
import { Loader2 } from 'lucide-react'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import {
  allianceEmploymentAdminApi,
  allianceEmploymentProjectApi,
  allianceEnterpriseApi,
} from '@/lib/api'
import { useToast, useAsync, UnderlineTabs, TableEmptyRow } from '@zhiyu/ui'
import { formatDateTime } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'
import {
  EMPLOYMENT_JOB_TYPE_LABELS,
  EMPLOYMENT_JOB_STATUS_LABELS,
  type EmploymentJob,
  type EmploymentApplication,
} from '@/lib/types'

const PAGE_SIZE = 20

function jobStatusVariant(status: string): 'default' | 'secondary' | 'outline' {
  if (status === 'published') return 'default'
  if (status === 'closed') return 'outline'
  return 'secondary'
}

function Field({ label, value }: { label: string; value?: string }) {
  return (
    <div className="flex gap-2">
      <span className="text-muted-foreground shrink-0">{label}：</span>
      <span className="break-all">{value || '-'}</span>
    </div>
  )
}

function JobsOverviewTab({ tenantId }: { tenantId?: string }) {
  const t = useT()
  const { toast } = useToast()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('all')
  const [projectId, setProjectId] = useState('all')
  const [enterpriseId, setEnterpriseId] = useState('all')
  const [page, setPage] = useState(1)

  const { data: projects } = useAsync(
    async () => {
      if (!tenantId) return []
      const res = await allianceEmploymentProjectApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [tenantId], onError: () => true },
  )

  const { data: enterprises } = useAsync(
    async () => {
      if (!tenantId) return []
      const res = await allianceEnterpriseApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [tenantId], onError: () => true },
  )

  const { data, loading, error, refresh } = useAsync(
    async () => {
      if (!tenantId) return { items: [], total: 0 }
      const res = await allianceEmploymentAdminApi.listJobs({
        page,
        limit: PAGE_SIZE,
        search: search.trim() || undefined,
        status: status === 'all' ? undefined : status,
        projectId: projectId === 'all' ? undefined : projectId,
        enterpriseId: enterpriseId === 'all' ? undefined : enterpriseId,
      })
      return { items: res.items || [], total: res.total }
    },
    { deps: [tenantId, page, search, status, projectId, enterpriseId], onError: () => true },
  )

  const items = data?.items ?? []
  const total = data?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))

  const changeStatus = async (job: EmploymentJob) => {
    if (job.status === 'draft') return
    const next = job.status === 'published' ? 'closed' : 'published'
    try {
      await allianceEmploymentAdminApi.setJobStatus(job.id, next)
      toast({ title: next === 'closed' ? t('已下架') : t('已恢复') })
      await refresh()
    } catch (e: any) {
      toast({ title: t('操作失败'), description: e.message, variant: 'destructive' })
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <SearchInput
          wrapperClassName="w-full sm:max-w-xs"
          placeholder={t('搜索岗位名称...')}
          value={search}
          onChange={(v) => {
            setSearch(v)
            setPage(1)
          }}
        />
        <Select
          value={status}
          onValueChange={(v) => {
            setStatus(v)
            setPage(1)
          }}
        >
          <SelectTrigger className="w-32">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">{t('全部状态')}</SelectItem>
            {(['draft', 'published', 'closed'] as const).map((v) => (
              <SelectItem key={v} value={v}>
                {EMPLOYMENT_JOB_STATUS_LABELS[v]}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select
          value={projectId}
          onValueChange={(v) => {
            setProjectId(v)
            setPage(1)
          }}
        >
          <SelectTrigger className="w-40">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">{t('全部项目')}</SelectItem>
            {(projects ?? []).map((p) => (
              <SelectItem key={p.id} value={p.id}>
                {p.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select
          value={enterpriseId}
          onValueChange={(v) => {
            setEnterpriseId(v)
            setPage(1)
          }}
        >
          <SelectTrigger className="w-40">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">{t('全部企业')}</SelectItem>
            {(enterprises ?? []).map((e) => (
              <SelectItem key={e.id} value={e.id}>
                {e.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="rounded-md border">
        <Table className="min-w-[860px]">
          <TableHeader className="bg-muted/50 border-b">
            <TableRow>
              <TableHead>{t('岗位')}</TableHead>
              <TableHead>{t('企业')}</TableHead>
              <TableHead>{t('项目')}</TableHead>
              <TableHead>{t('类型')}</TableHead>
              <TableHead>{t('状态')}</TableHead>
              <TableHead>{t('投递数')}</TableHead>
              <TableHead>{t('创建时间')}</TableHead>
              <TableHead>{t('操作')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={8} className="text-center py-8">
                  <Loader2 className="h-5 w-5 animate-spin mx-auto text-muted-foreground" />
                </TableCell>
              </TableRow>
            ) : items.length === 0 ? (
              <TableEmptyRow colSpan={8} className="py-8">
                {t('暂无岗位')}
              </TableEmptyRow>
            ) : (
              items.map((job) => (
                <TableRow key={job.id} className="border-b">
                  <TableCell className="font-medium">{job.title}</TableCell>
                  <TableCell>{job.enterpriseName || '-'}</TableCell>
                  <TableCell>{job.projectName || t('独立岗位')}</TableCell>
                  <TableCell>{EMPLOYMENT_JOB_TYPE_LABELS[job.jobType] ?? job.jobType}</TableCell>
                  <TableCell>
                    <Badge variant={jobStatusVariant(job.status) as any}>
                      {EMPLOYMENT_JOB_STATUS_LABELS[job.status] ?? job.status}
                    </Badge>
                  </TableCell>
                  <TableCell>{job.applicationCount}</TableCell>
                  <TableCell className="whitespace-nowrap">{formatDateTime(job.createdAt)}</TableCell>
                  <TableCell>
                    {job.status === 'draft' ? (
                      <span className="text-sm text-muted-foreground">-</span>
                    ) : (
                      <Button variant="ghost" size="sm" onClick={() => changeStatus(job)}>
                        {job.status === 'published' ? t('下架') : t('恢复')}
                      </Button>
                    )}
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
        {error && (
          <div className="p-4 text-center text-sm text-muted-foreground">{error.message}</div>
        )}
      </div>

      <div className="flex items-center justify-between">
        <span className="text-sm text-muted-foreground">{t('共 {total} 条记录', { total })}</span>
        <PaginationBar page={page} totalPages={totalPages} onPageChange={setPage} />
      </div>
    </div>
  )
}

function ApplicationsOverviewTab({ tenantId }: { tenantId?: string }) {
  const t = useT()
  const [search, setSearch] = useState('')
  const [projectId, setProjectId] = useState('all')
  const [enterpriseId, setEnterpriseId] = useState('all')
  const [page, setPage] = useState(1)
  const [viewing, setViewing] = useState<EmploymentApplication | null>(null)

  const { data: projects } = useAsync(
    async () => {
      if (!tenantId) return []
      const res = await allianceEmploymentProjectApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [tenantId], onError: () => true },
  )

  const { data: enterprises } = useAsync(
    async () => {
      if (!tenantId) return []
      const res = await allianceEnterpriseApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [tenantId], onError: () => true },
  )

  const { data, loading, error } = useAsync(
    async () => {
      if (!tenantId) return { items: [], total: 0 }
      const res = await allianceEmploymentAdminApi.listApplications({
        page,
        limit: PAGE_SIZE,
        search: search.trim() || undefined,
        projectId: projectId === 'all' ? undefined : projectId,
        enterpriseId: enterpriseId === 'all' ? undefined : enterpriseId,
      })
      return { items: res.items || [], total: res.total }
    },
    { deps: [tenantId, page, search, projectId, enterpriseId], onError: () => true },
  )

  const items = data?.items ?? []
  const total = data?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))

  return (
    <>
      <div className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          <SearchInput
            wrapperClassName="w-full sm:max-w-xs"
            placeholder={t('搜索学生姓名...')}
            value={search}
            onChange={(v) => {
              setSearch(v)
              setPage(1)
            }}
          />
          <Select
            value={projectId}
            onValueChange={(v) => {
              setProjectId(v)
              setPage(1)
            }}
          >
            <SelectTrigger className="w-40">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('全部项目')}</SelectItem>
              {(projects ?? []).map((p) => (
                <SelectItem key={p.id} value={p.id}>
                  {p.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select
            value={enterpriseId}
            onValueChange={(v) => {
              setEnterpriseId(v)
              setPage(1)
            }}
          >
            <SelectTrigger className="w-40">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('全部企业')}</SelectItem>
              {(enterprises ?? []).map((e) => (
                <SelectItem key={e.id} value={e.id}>
                  {e.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="rounded-md border">
          <Table className="min-w-[960px]">
            <TableHeader className="bg-muted/50 border-b">
              <TableRow>
                <TableHead>{t('学生')}</TableHead>
                <TableHead>{t('学号')}</TableHead>
                <TableHead>{t('专业')}</TableHead>
                <TableHead>{t('班级')}</TableHead>
                <TableHead>{t('岗位')}</TableHead>
                <TableHead>{t('企业')}</TableHead>
                <TableHead>{t('项目')}</TableHead>
                <TableHead>{t('投递时间')}</TableHead>
                <TableHead>{t('操作')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={9} className="text-center py-8">
                    <Loader2 className="h-5 w-5 animate-spin mx-auto text-muted-foreground" />
                  </TableCell>
                </TableRow>
              ) : items.length === 0 ? (
                <TableEmptyRow colSpan={9} className="py-8">
                  {t('暂无投递')}
                </TableEmptyRow>
              ) : (
                items.map((a) => (
                  <TableRow key={a.id} className="border-b">
                    <TableCell className="font-medium">{a.studentName || '-'}</TableCell>
                    <TableCell>{a.studentNo || '-'}</TableCell>
                    <TableCell>{a.majorName || '-'}</TableCell>
                    <TableCell>{a.className || '-'}</TableCell>
                    <TableCell>{a.jobTitle || '-'}</TableCell>
                    <TableCell>{a.enterpriseName || '-'}</TableCell>
                    <TableCell>{a.projectName || '-'}</TableCell>
                    <TableCell className="whitespace-nowrap">{formatDateTime(a.createdAt)}</TableCell>
                    <TableCell>
                      <Button variant="ghost" size="sm" onClick={() => setViewing(a)}>
                        {t('查看')}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
          {error && (
            <div className="p-4 text-center text-sm text-muted-foreground">{error.message}</div>
          )}
        </div>

        <div className="flex items-center justify-between">
          <span className="text-sm text-muted-foreground">{t('共 {total} 条记录', { total })}</span>
          <PaginationBar page={page} totalPages={totalPages} onPageChange={setPage} />
        </div>
      </div>

      <Dialog open={viewing !== null} onOpenChange={(o) => !o && setViewing(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('投递详情')}</DialogTitle>
          </DialogHeader>
          {viewing && (
            <div className="grid gap-2 text-sm max-h-[60vh] overflow-y-auto">
              <Field label={t('学生')} value={viewing.studentName} />
              <Field label={t('学号')} value={viewing.studentNo} />
              <Field label={t('专业')} value={viewing.majorName} />
              <Field label={t('班级')} value={viewing.className} />
              <Field label={t('联系电话')} value={viewing.phone} />
              <Field label={t('邮箱')} value={viewing.email} />
              <Field label={t('岗位')} value={viewing.jobTitle} />
              <Field label={t('企业')} value={viewing.enterpriseName} />
              <Field label={t('项目')} value={viewing.projectName} />
              <Field label={t('投递时间')} value={formatDateTime(viewing.createdAt)} />
              <div className="pt-2">
                <p className="text-muted-foreground">{t('求职信')}</p>
                <p className="mt-1 whitespace-pre-wrap rounded-md border bg-muted/30 p-3">
                  {viewing.coverLetter || '-'}
                </p>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  )
}

export default function EmploymentJobOverviewPage() {
  const { tenantId } = usePortalAuth()
  const t = useT()
  const [activeTab, setActiveTab] = useState('jobs')

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-foreground">{t('岗位与投递')}</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {t('管理服务大厅岗位发布状态，查看学生投递记录。')}
        </p>
      </div>

      <UnderlineTabs
        items={[
          { key: 'jobs', label: t('岗位') },
          { key: 'applications', label: t('投递') },
        ]}
        activeKey={activeTab}
        onSelect={setActiveTab}
      />

      {activeTab === 'jobs' ? (
        <JobsOverviewTab tenantId={tenantId} />
      ) : (
        <ApplicationsOverviewTab tenantId={tenantId} />
      )}
    </div>
  )
}
