// frontend/portal-vue/src/views/system/students.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <span class="card-title">学生管理</span>
            <span class="card-sub">管理学生基础信息与学籍数据</span>
          </div>
          <div>
            <el-button v-if="selectedIds.length" type="danger" :loading="batchDeleting" @click="confirmBatchDelete">批量删除({{ selectedIds.length }})</el-button>
            <el-button v-if="selectedIds.length" :loading="graduateLoading" @click="confirmBatchGraduate">批量毕业({{ selectedIds.length }})</el-button>
            <el-button v-if="selectedIds.length" @click="joinDialog = true">批量加入班级({{ selectedIds.length }})</el-button>
            <el-button @click="exportStudents">批量导出</el-button>
            <el-button type="primary" @click="openCreate">新建学生</el-button>
          </div>
        </div>
      </template>

      <div class="filter-row">
        <el-input v-model="keyword" placeholder="搜索姓名、登录账号..." clearable style="max-width: 320px" />
        <el-select v-model="statusFilter" style="width: 140px">
          <el-option label="全部状态" value="all" />
          <el-option label="正常" value="正常" />
          <el-option label="禁用" value="禁用" />
          <el-option label="毕业" value="毕业" />
        </el-select>
      </div>

      <el-table v-loading="loading" :data="filteredStudents" stripe @selection-change="onSelectionChange">
        <el-table-column type="selection" width="45" />
        <el-table-column label="登录账号（学号）" prop="loginAccount" width="160" />
        <el-table-column label="姓名" prop="name" width="120" />
        <el-table-column label="所属院系" prop="department" min-width="140" show-overflow-tooltip />
        <el-table-column label="班级" prop="className" min-width="120" show-overflow-tooltip />
        <el-table-column label="状态" width="90">
          <template #default="{ row }">
            <el-tag :type="statusType(row.status)">{{ row.status }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="300" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openEdit(row)">编辑</el-button>
            <el-button size="small" @click="openResetPwd(row)">重置密码</el-button>
            <el-button size="small" @click="changeStatus(row, '正常')" :disabled="row.status === '正常'">设为正常</el-button>
            <el-button size="small" @click="changeStatus(row, '禁用')" :disabled="row.status === '禁用'">设为禁用</el-button>
            <el-button size="small" @click="changeStatus(row, '毕业')" :disabled="row.status === '毕业'">设为毕业</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新建/编辑 -->
    <el-dialog v-model="dialog" :title="editing ? '编辑学生' : '新建学生'" width="480px">
      <el-form label-width="120px">
        <el-form-item label="姓名" required><el-input v-model="form.name" placeholder="请输入姓名" /></el-form-item>
        <el-form-item label="登录账号（学号）" required><el-input v-model="form.loginAccount" placeholder="如：S2024001" /></el-form-item>
        <el-form-item v-if="!editing" label="密码" required><el-input v-model="form.password" type="password" show-password placeholder="请输入密码" /></el-form-item>
        <el-form-item label="班级" required>
          <el-tree-select
            v-model="form.classNodeId"
            :data="classTreeData"
            node-key="value"
            :props="{ label: 'label', children: 'children' }"
            placeholder="选择班级"
            check-strictly
            default-expand-all
            style="width: 100%"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>

    <!-- 重置密码 -->
    <el-dialog v-model="resetDialog" :title="`重置密码：${resetTarget?.name || ''}`" width="420px">
      <el-input v-model="resetPassword" type="password" show-password placeholder="输入新密码" />
      <template #footer>
        <el-button @click="resetDialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveResetPwd">确定</el-button>
      </template>
    </el-dialog>

    <!-- 批量加入班级 -->
    <el-dialog v-model="joinDialog" title="批量加入班级" width="440px">
      <el-tree-select
        v-model="joinClassNodeId"
        :data="classTreeData"
        node-key="value"
        :props="{ label: 'label', children: 'children' }"
        placeholder="选择班级"
        check-strictly
        default-expand-all
        style="width: 100%"
      />
      <template #footer>
        <el-button @click="joinDialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveJoin">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { userManagementApi } from '@/api/portal';
import { roleApi, organizationApi, orgTypeApi } from '@/api/system';
import { authedFetch } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import type { User } from '@/types/user';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');
const institutionId = computed(() => (auth.user?.institutionId as string) || '');

interface Student {
  id: string;
  name: string;
  loginAccount: string;
  className: string;
  department: string;
  orgNodeId?: string;
  status: '正常' | '禁用' | '毕业';
}

const allUsers = ref<User[]>([]);
const students = ref<Student[]>([]);
const classTreeData = ref<{ value: string; label: string; children?: any[] }[]>([]);
const loading = ref(false);
const keyword = ref('');
const statusFilter = ref('all');
const selectedIds = ref<string[]>([]);
const saving = ref(false);
const batchDeleting = ref(false);
const graduateLoading = ref(false);

const dialog = ref(false);
const editing = ref<Student | null>(null);
const form = reactive({ name: '', loginAccount: '', password: '', classNodeId: '' });

const resetDialog = ref(false);
const resetTarget = ref<Student | null>(null);
const resetPassword = ref('');

const joinDialog = ref(false);
const joinClassNodeId = ref('');

const filteredStudents = computed(() =>
  students.value.filter((s) => {
    if (statusFilter.value !== 'all' && s.status !== statusFilter.value) return false;
    if (!keyword.value.trim()) return true;
    const q = keyword.value.trim();
    return s.name.includes(q) || s.loginAccount.includes(q);
  })
);

function mapStatus(s: string): Student['status'] {
  if (s === 'disabled') return '禁用';
  if (s === 'graduated') return '毕业';
  return '正常';
}
function toBackendStatus(s: Student['status']): string {
  if (s === '禁用') return 'disabled';
  if (s === '毕业') return 'graduated';
  return 'active';
}
function statusType(s: string) {
  if (s === '正常') return 'success';
  if (s === '毕业') return 'warning';
  return 'info';
}

async function load() {
  loading.value = true;
  try {
    const [userRes, orgRes, orgTypeRes] = await Promise.all([
      userManagementApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), roleCode: 'student', limit: 1000 }),
      organizationApi.tree({ ...(tenantId.value ? { tenantId: tenantId.value } : {}) }),
      orgTypeApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 200 })
    ]);
    allUsers.value = userRes.items;
    const orgs = orgRes.items || [];
    const typeMap = new Map((orgTypeRes.items || []).map((t) => [t.id, t.name]));
    const classTypeIds = new Set((orgTypeRes.items || []).filter((t) => t.name === '班级').map((t) => t.id));
    const byId = new Map<string, any>();
    const buildTree = (nodes: any[]): any[] => nodes.map((n) => {
      byId.set(n.id, n);
      return { value: n.id, label: n.name, children: n.children ? buildTree(n.children) : [] };
    });
    const fullTree = buildTree(orgs);
    const filterClassTree = (nodes: any[]): any[] =>
      nodes
        .map((n) => ({ ...n, children: filterClassTree(n.children || []) }))
        .filter((n) => n.children.length > 0 || classTypeIds.has(n.value));
    classTreeData.value = filterClassTree(fullTree);

    students.value = allUsers.value.map((u) => {
      const classNode = u.orgNodeId ? byId.get(u.orgNodeId) : undefined;
      const className = classNode?.name || '—';
      let department = '—';
      if (classNode) {
        let cur = classNode;
        while (cur) {
          if (typeMap.get(cur.typeId) === '二级学院') { department = cur.name; break; }
          cur = cur.parentId ? byId.get(cur.parentId) : undefined;
        }
      }
      return {
        id: u.id,
        name: u.name,
        loginAccount: u.username || u.loginName || '',
        className,
        department,
        orgNodeId: u.orgNodeId,
        status: mapStatus(u.status)
      };
    });
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function onSelectionChange(rows: Student[]) {
  selectedIds.value = rows.map((r) => r.id);
}

function openCreate() {
  editing.value = null;
  form.name = '';
  form.loginAccount = '';
  form.password = '';
  form.classNodeId = '';
  dialog.value = true;
}
function openEdit(row: Student) {
  editing.value = row;
  form.name = row.name;
  form.loginAccount = row.loginAccount;
  form.password = '';
  form.classNodeId = row.orgNodeId || '';
  dialog.value = true;
}

async function save() {
  if (!form.name.trim() || !form.loginAccount.trim() || (!editing.value && !form.password) || !form.classNodeId) {
    ElMessage.warning('姓名、学号、班级必填，新建需填写密码');
    return;
  }
  saving.value = true;
  try {
    if (editing.value) {
      const original = allUsers.value.find((u) => u.id === editing.value!.id);
      if (!original) throw new Error('未找到原始用户数据');
      await userManagementApi.update(editing.value.id, {
        institutionId: original.institutionId,
        orgNodeId: form.classNodeId || undefined,
        majorId: original.majorId,
        role: original.role,
        loginName: form.loginAccount.trim(),
        username: form.loginAccount.trim(),
        name: form.name.trim(),
        email: original.email,
        phone: original.phone,
        avatarUrl: original.avatarUrl,
        studentNo: original.studentNo,
        workId: original.workId,
        idCard: original.idCard
      });
      ElMessage.success('保存成功');
    } else {
      if (!tenantId.value) throw new Error('未获取到租户信息');
      const roles = await roleApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 200 });
      const studentRole = roles.items.find((r) => r.code === 'student');
      if (!studentRole) throw new Error('未找到学生角色');
      await userManagementApi.create({
        tenantId: tenantId.value,
        institutionId: institutionId.value,
        roleId: studentRole.id,
        role: 'school',
        platform: 'portal',
        loginName: form.loginAccount.trim(),
        username: form.loginAccount.trim(),
        password: form.password,
        name: form.name.trim(),
        orgNodeId: form.classNodeId
      });
      ElMessage.success('创建成功');
    }
    dialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function changeStatus(row: Student, target: Student['status']) {
  if (row.status === target) return;
  try {
    await userManagementApi.updateStatus(row.id, toBackendStatus(target));
    ElMessage.success('状态已更新');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

function openResetPwd(row: Student) {
  resetTarget.value = row;
  resetPassword.value = '';
  resetDialog.value = true;
}
async function saveResetPwd() {
  if (!resetTarget.value || !resetPassword.value) {
    ElMessage.warning('请输入新密码');
    return;
  }
  saving.value = true;
  try {
    await userManagementApi.resetPassword(resetTarget.value.id, resetPassword.value);
    ElMessage.success('密码已重置');
    resetDialog.value = false;
  } catch (e) {
    ElMessage.error((e as Error).message || '重置失败');
  } finally {
    saving.value = false;
  }
}

async function confirmDelete(row: Student) {
  try { await ElMessageBox.confirm(`确定要删除学生「${row.name}」吗？`, '确认删除', { type: 'warning' }); } catch { return; }
  try {
    await userManagementApi.delete(row.id);
    ElMessage.success('删除成功');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

async function confirmBatchDelete() {
  if (!selectedIds.value.length) return;
  try { await ElMessageBox.confirm(`确定要删除选中的 ${selectedIds.value.length} 名学生吗？此操作不可撤销。`, '确认批量删除', { type: 'warning' }); } catch { return; }
  batchDeleting.value = true;
  try {
    await userManagementApi.batchDelete(selectedIds.value);
    ElMessage.success(`成功删除 ${selectedIds.value.length} 名学生`);
    selectedIds.value = [];
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '批量删除失败');
  } finally {
    batchDeleting.value = false;
  }
}

async function confirmBatchGraduate() {
  if (!selectedIds.value.length) return;
  try {
    await ElMessageBox.confirm(`确定将选中的 ${selectedIds.value.length} 名学生状态改为毕业吗？此操作不可撤销。`, '确认批量毕业', { type: 'warning' });
  } catch {
    return;
  }
  graduateLoading.value = true;
  try {
    await userManagementApi.batchGraduate({ userIds: selectedIds.value });
    ElMessage.success(`已将 ${selectedIds.value.length} 名学生状态改为毕业`);
    selectedIds.value = [];
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '批量毕业失败');
  } finally {
    graduateLoading.value = false;
  }
}

async function saveJoin() {
  if (!joinClassNodeId.value) {
    ElMessage.warning('请选择班级');
    return;
  }
  saving.value = true;
  try {
    await userManagementApi.batchUpdateOrgNode({ userIds: selectedIds.value, orgNodeId: joinClassNodeId.value });
    ElMessage.success('批量加入班级成功');
    joinDialog.value = false;
    selectedIds.value = [];
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '批量加入班级失败');
  } finally {
    saving.value = false;
  }
}

async function exportStudents() {
  try {
    const res = await authedFetch('/export/students/excel', { method: 'POST', body: JSON.stringify({ ids: selectedIds.value }) });
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error((data as { error?: string }).error || `HTTP ${res.status}`);
    }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = selectedIds.value.length > 0 ? '学生导出.xlsx' : '学生导出.xlsx';
    a.click();
    URL.revokeObjectURL(url);
    ElMessage.success(selectedIds.value.length > 0 ? `已导出 ${selectedIds.value.length} 名学生` : '导出完成');
  } catch (e) {
    ElMessage.error((e as Error).message || '导出失败');
  }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; margin-left: 8px; }
.filter-row { display: flex; gap: 12px; margin-bottom: 12px; }
</style>

// apps/edu/app/portal/apps/system/org-user/students/page.tsx
"use client"

import { useState, useEffect, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { TableCell, TableHead } from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { usePortalAuth } from "@/contexts/portal-auth-context"
import { usePortalUsers } from "@/hooks/use-portal-users"
import { useOrgTree, findOrgAncestor } from "@/hooks/use-org-tree"
import { OrgNodePicker } from "@/components/shared/org-node-picker"
import { TableRowActions } from "@/components/shared/table-row-actions"
import { ConfirmDialog } from "@/components/shared/confirm-dialog"
import { portalUserManagementApi, importExportApi } from "@/lib/api"
import type { Organization } from "@/lib/types/backend"
import { useToast } from "@zhiyu/ui"
import { PortalSidebarCrudPage } from "@/components/shared/portal-sidebar-crud-page"
import { Pencil, Power, Trash2, Key, Award, Users, Loader2 } from "lucide-react"

const DEPT_TYPE = "二级学院"
const CLASS_TYPE = "班级"

interface Student {
  id: string
  name: string
  loginAccount: string
  className: string
  department: string
  orgNodeId?: string
  status: "正常" | "禁用" | "毕业"
}

const statusColor: Record<string, string> = {
  "正常": "default",
  "禁用": "destructive",
  "毕业": "secondary",
}

function classBadge(variant: string) {
  if (variant === "destructive") return "destructive" as const
  if (variant === "secondary") return "secondary" as const
  return "default" as const
}

function mapStudentStatus(status: string): Student["status"] {
  if (status === "active") return "正常"
  if (status === "disabled") return "禁用"
  if (status === "graduated") return "毕业"
  return "正常"
}

function toBackendStatus(status: Student["status"]): string {
  if (status === "正常") return "active"
  if (status === "禁用") return "disabled"
  if (status === "毕业") return "graduated"
  return "active"
}

function getOrgTypeName(org: Organization | undefined, orgTypeMap: Map<string, { name: string }>): string | undefined {
  if (!org) return undefined
  return orgTypeMap.get(org.typeId)?.name
}

export default function StudentsPage() {
  const { institution, institutionId, tenantId } = usePortalAuth()
  const { toast } = useToast()
  const { users, roles: tenantRoles, total, page, pageSize, setPage, loading, error, refetch } = usePortalUsers({
    roleCode: "student",
  })
  const { orgs, orgMap, orgTypeMap, loading: orgLoading } = useOrgTree(tenantId)

  const [students, setStudents] = useState<Student[]>([])
  const [statusFilter, setStatusFilter] = useState("正常")

  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null)
  const [saving, setSaving] = useState(false)
  const [graduateLoading, setGraduateLoading] = useState(false)
  const [batchDeleting, setBatchDeleting] = useState(false)
  const [batchDeleteTarget, setBatchDeleteTarget] = useState<string[] | null>(null)

  const [formName, setFormName] = useState("")
  const [formUsername, setFormUsername] = useState("")
  const [formPassword, setFormPassword] = useState("")
  const [formClassNodeId, setFormClassNodeId] = useState("")

  useEffect(() => {
    ;(async () => {
      setStudents(
        users.map((u) => {
          const classNode = u.orgNodeId ? orgMap.get(u.orgNodeId) : undefined
          const className = classNode?.name || "—"
          let departmentName = institution?.name || "—"
          if (classNode) {
            const deptNode = findOrgAncestor(orgMap, classNode.id, (org) => getOrgTypeName(org, orgTypeMap) === DEPT_TYPE)
            departmentName = deptNode?.name || institution?.name || "—"
          }
          return {
            id: u.id,
            name: u.name,
            loginAccount: u.username || u.loginName || "",
            className,
            department: departmentName,
            orgNodeId: u.orgNodeId,
            status: mapStudentStatus(u.status),
          }
        })
      )
    })()
  }, [users, institution, orgMap, orgTypeMap])

  const resetForm = () => {
    setFormName("")
    setFormUsername("")
    setFormPassword("")
    setFormClassNodeId("")
  }

  const changeStatus = async (student: Student, targetStatus: Student["status"]) => {
    try {
      await portalUserManagementApi.updateStatus(student.id, toBackendStatus(targetStatus))
      toast({ title: "状态已更新" })
      await refetch()
    } catch (err) {
      toast({ variant: "destructive", title: "操作失败", description: err instanceof Error ? err.message : "未知错误" })
    }
  }

  const confirmBatchDelete = async () => {
    if (!batchDeleteTarget || batchDeleteTarget.length === 0) return
    setBatchDeleting(true)
    try {
      await portalUserManagementApi.batchDelete(batchDeleteTarget)
      toast({ title: `成功删除 ${batchDeleteTarget.length} 名学生` })
    } catch (err) {
      toast({ variant: "destructive", title: "批量删除失败", description: err instanceof Error ? err.message : "未知错误" })
    } finally {
      setBatchDeleting(false)
      setBatchDeleteTarget(null)
    }
    await refetch()
  }

  const formValid = formName.trim() && formUsername.trim() && !!formClassNodeId && (!!selectedStudent || formPassword.trim())

  return (
    <>
      <PortalSidebarCrudPage
      title="学生管理"
      description="管理学生基础信息与学籍数据"
      entityLabel="学生"
      searchPlaceholder="搜索姓名、登录账号..."
      createButtonLabel="新生录入"
      items={students}
      loading={loading}
      error={error}
      total={total}
      page={page}
      pageSize={pageSize}
      setPage={setPage}
      refetch={refetch}
      orgs={orgs}
      orgMap={orgMap}
      orgTypeMap={orgTypeMap}
      orgLoading={orgLoading}
      sidebarAllLabel="全部学生"
      statusFilter={statusFilter}
      setStatusFilter={setStatusFilter}
      statusOptions={[
        { value: "all", label: "全部状态" },
        { value: "正常", label: "正常" },
        { value: "禁用", label: "禁用" },
        { value: "毕业", label: "毕业" },
      ]}
      filterItems={(items, search, status) =>
        items.filter((s) => {
          if (status !== "all" && s.status !== status) return false
          if (!search) return true
          return s.name.includes(search) || s.loginAccount.includes(search)
        })
      }
      getItemOrgNodeId={(item) => item.orgNodeId}
      importConfig={{ importType: "students", entityLabel: "学生", templateFileName: "学生批量导入模板.xlsx" }}
      colSpan={6}
      renderTableHeader={() => (
        <>
          <TableHead>登录账号（学号）</TableHead>
          <TableHead>姓名</TableHead>
          <TableHead>所属院系</TableHead>
          <TableHead>班级</TableHead>
          <TableHead>状态</TableHead>
          <TableHead className="text-right">操作</TableHead>
        </>
      )}
      renderTableRow={(student, actions) => (
        <>
          <TableCell className="font-mono text-sm">{student.loginAccount}</TableCell>
          <TableCell className="font-medium">{student.name}</TableCell>
          <TableCell>{student.department}</TableCell>
          <TableCell>{student.className}</TableCell>
          <TableCell>
            <Badge variant={classBadge(statusColor[student.status])}>{student.status}</Badge>
          </TableCell>
          <TableRowActions>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={actions.edit}>
              <Pencil className="mr-1 h-3 w-3" />
              编辑
            </Button>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={actions.onResetPwd}>
              <Key className="mr-1 h-3 w-3" />
              重置密码
            </Button>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={() => changeStatus(student, "正常")}>
              <Power className="mr-1 h-3 w-3" />
              {student.status !== "正常" ? "设为正常" : "正常"}
            </Button>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs text-red-500 hover:text-red-600" onClick={() => changeStatus(student, "禁用")}>
              <Power className="mr-1 h-3 w-3" />
              {student.status !== "禁用" ? "设为禁用" : "禁用"}
            </Button>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs" onClick={() => changeStatus(student, "毕业")}>
              <Award className="mr-1 h-3 w-3" />
              {student.status !== "毕业" ? "设为毕业" : "毕业"}
            </Button>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-xs text-red-500 hover:text-red-600" onClick={actions.onDelete}>
              <Trash2 className="mr-1 h-3 w-3" />
              删除
            </Button>
          </TableRowActions>
        </>
      )}
      headerActions={(selectedIds, openJoinDialog) => (
        <>
          <Button
            variant="outline"
            size="sm"
            disabled={selectedIds.length === 0 || graduateLoading || batchDeleting}
            onClick={async () => {
              if (!tenantId) return
              setGraduateLoading(true)
              try {
                await portalUserManagementApi.batchGraduate({ userIds: selectedIds })
                toast({ title: "批量毕业成功", description: `已将 ${selectedIds.length} 名学生状态改为毕业` })
                await refetch()
              } catch (err) {
                toast({ variant: "destructive", title: "批量毕业失败", description: err instanceof Error ? err.message : "未知错误" })
              } finally {
                setGraduateLoading(false)
              }
            }}
          >
            {graduateLoading ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Award className="h-4 w-4 mr-1" />}
            {selectedIds.length > 0 ? `批量毕业(${selectedIds.length})` : "批量毕业"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={selectedIds.length === 0 || graduateLoading || batchDeleting}
            onClick={openJoinDialog}
          >
            <Users className="h-4 w-4 mr-1" />
            {selectedIds.length > 0 ? `批量加入班级(${selectedIds.length})` : "批量加入班级"}
          </Button>
          <Button
            variant="destructive"
            size="sm"
            disabled={selectedIds.length === 0 || batchDeleting}
            onClick={() => {
              if (selectedIds.length === 0) return
              setBatchDeleteTarget([...selectedIds])
            }}
          >
            {batchDeleting ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : <Trash2 className="h-4 w-4 mr-1" />}
            批量删除({selectedIds.length})
          </Button>
        </>
      )}
      onOpenCreate={() => { setSelectedStudent(null); resetForm(); setIsDialogOpen(true) }}
      onOpenEdit={(student) => {
        setSelectedStudent(student)
        setFormName(student.name)
        setFormUsername(student.loginAccount)
        setFormPassword("")
        setFormClassNodeId(student.orgNodeId || "")
        setIsDialogOpen(true)
      }}
      isEditDialogOpen={isDialogOpen}
      setIsEditDialogOpen={setIsDialogOpen}
      editDialogTitle={selectedStudent ? "编辑学生" : "新生录入"}
      editDialogDescription={selectedStudent ? "修改学生基本信息与班级归属" : "填写学生基本信息，并关联到真实班级"}
      renderForm={() => (
        <>
          <div className="grid gap-2">
            <Label>姓名 <span className="text-destructive">*</span></Label>
            <Input placeholder="请输入姓名" value={formName} onChange={(e) => setFormName(e.target.value)} />
          </div>
          <div className="grid gap-2">
            <Label>登录账号（学号） <span className="text-destructive">*</span></Label>
            <Input placeholder="如：S2024001" value={formUsername} onChange={(e) => setFormUsername(e.target.value)} />
          </div>
          {!selectedStudent && (
            <div className="grid gap-2">
              <Label>密码 <span className="text-destructive">*</span></Label>
              <Input type="text" placeholder="请输入密码" value={formPassword} onChange={(e) => setFormPassword(e.target.value)} />
            </div>
          )}
          <div className="grid gap-2">
            <Label>班级 <span className="text-destructive">*</span></Label>
            <OrgNodePicker
              tenantId={tenantId}
              value={formClassNodeId}
              onChange={(value) => setFormClassNodeId(value || "")}
              selectableTypes={[CLASS_TYPE]}
              placeholder="选择班级"
              title="选择班级"
            />
          </div>
        </>
      )}
      formValid={!!formValid}
      saving={saving}
      onFormSave={async () => {
        setSaving(true)
        try {
          if (selectedStudent) {
            const original = users.find((u) => u.id === selectedStudent.id)
            if (!original) {
              toast({ variant: "destructive", title: "保存失败", description: "未找到原始用户数据" })
              return
            }
            await portalUserManagementApi.update(selectedStudent.id, {
              institutionId: original.institutionId,
              orgNodeId: formClassNodeId || undefined,
              majorId: original.majorId,
              role: original.role,
              loginName: formUsername.trim(),
              username: formUsername.trim(),
              name: formName.trim(),
              email: original.email,
              phone: original.phone,
              avatarUrl: original.avatarUrl,
              studentNo: original.studentNo,
              workId: original.workId,
              idCard: original.idCard,
              titleIds: original.titleIds,
            })
            toast({ title: "保存成功" })
          } else {
            if (!tenantId) {
              toast({ variant: "destructive", title: "创建失败", description: "未获取到租户信息" })
              return
            }
            if (!formClassNodeId) {
              toast({ variant: "destructive", title: "创建失败", description: "请选择班级" })
              return
            }
            const studentRole = tenantRoles.find((r) => r.code === "student")
            if (!studentRole) {
              toast({ variant: "destructive", title: "创建失败", description: "未找到学生角色" })
              return
            }
            await portalUserManagementApi.create({
              tenantId,
              institutionId,
              roleId: studentRole.id,
              role: "school",
              platform: "portal",
              loginName: formUsername.trim(),
              username: formUsername.trim(),
              password: formPassword.trim(),
              name: formName.trim(),
              orgNodeId: formClassNodeId,
            })
            toast({ title: "创建成功" })
          }
          setIsDialogOpen(false)
          resetForm()
          setSelectedStudent(null)
          await refetch()
        } catch (err) {
          toast({ variant: "destructive", title: "保存失败", description: err instanceof Error ? err.message : "未知错误" })
        } finally {
          setSaving(false)
        }
      }}
      onDelete={async (id) => {
        await portalUserManagementApi.delete(id)
      }}
      onExport={async (selectedIds) => {
        const res = await importExportApi.exportStudentsExcel(selectedIds)
        const blob = await res.blob()
        const url = window.URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = "学生导出.xlsx"
        document.body.appendChild(a)
        a.click()
        a.remove()
        window.URL.revokeObjectURL(url)
        toast({ title: selectedIds.length > 0 ? `已导出 ${selectedIds.length} 名学生` : "导出完成" })
      }}
      joinEntityLabel="班级"
      onBatchJoin={async (orgNodeId, userIds) => {
        await portalUserManagementApi.batchUpdateOrgNode({ userIds, orgNodeId })
      }}
      orgNodePickerProps={{ selectableTypes: [CLASS_TYPE], placeholder: "选择班级", title: "选择班级" }}
      />
      <ConfirmDialog
        open={batchDeleteTarget !== null}
        onOpenChange={(open) => { if (!open) setBatchDeleteTarget(null) }}
        title="确认批量删除"
        description={`确定要删除选中的 ${batchDeleteTarget?.length || 0} 名学生吗？此操作不可撤销。`}
        variant="destructive"
        onConfirm={confirmBatchDelete}
      />
    </>
  )
}
