// frontend/portal-vue/src/views/job/learn-roads.vue
<template>
  <div class="learn-roads">
    <!-- 列表视图 -->
    <template v-if="view === 'list'">
      <div class="page-header">
        <div>
          <h2 class="page-title">岗位学习路径管理</h2>
          <p class="page-sub">按岗位管理学习路径中场景与任务的展示顺序</p>
        </div>
      </div>

      <el-card shadow="never" class="filter-card">
        <div class="filter-row">
          <el-input v-model="searchQuery" placeholder="搜索岗位名称、简称..." clearable style="max-width: 320px" />
          <el-select v-model="filterStatus" placeholder="全部状态" style="width: 140px">
            <el-option label="全部状态" value="all" />
            <el-option label="草稿" value="draft" />
            <el-option label="审批中" value="pending" />
            <el-option label="已通过" value="approved" />
            <el-option label="已驳回" value="rejected" />
            <el-option label="已发布" value="published" />
          </el-select>
        </div>
      </el-card>

      <el-card shadow="never">
        <template #header>
          <div class="card-header">
            <span class="card-title">岗位列表</span>
            <span class="card-sub">共 {{ filteredPositions.length }} 个岗位</span>
          </div>
        </template>
        <el-table v-loading="listLoading" :data="filteredPositions" stripe>
          <el-table-column label="岗位名称" min-width="200">
            <template #default="{ row }">
              <div class="pos-name">{{ row.name }}</div>
              <div class="sub">{{ row.shortName }}</div>
            </template>
          </el-table-column>
          <el-table-column label="场景数" width="100">
            <template #default="{ row }">
              <el-tag>{{ sceneStats.get(row.id)?.sceneCount ?? 0 }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="任务数" width="100">
            <template #default="{ row }">
              <el-tag type="info">{{ sceneStats.get(row.id)?.taskCount ?? 0 }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="操作" width="140" align="right">
            <template #default="{ row }">
              <el-button size="small" :disabled="editLoading" @click="handleEdit(row)">编辑学习路径</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </template>

    <!-- 编辑视图 -->
    <template v-else>
      <div class="page-header">
        <div class="header-left">
          <el-button @click="handleBack" :disabled="editLoading">返回岗位列表</el-button>
          <div>
            <h2 class="page-title">{{ editingPosition?.name }}</h2>
            <p class="page-sub">已加载 {{ scenes.length }} 个场景 · 点击场景查看任务</p>
          </div>
        </div>
        <el-button type="primary" :loading="saving" @click="handleSave">{{ saved ? '已保存' : '保存顺序' }}</el-button>
      </div>

      <el-card shadow="never" v-loading="editLoading">
        <template #header>
          <div class="card-header">
            <span class="card-title">场景顺序</span>
            <span class="card-sub">通过上移/下移调整场景顺序，点击场景查看任务</span>
          </div>
        </template>
        <el-empty v-if="scenes.length === 0" description="暂无可排序的场景" />
        <div v-else class="scene-list">
          <div
            v-for="(scene, index) in scenes"
            :key="scene.id"
            class="scene-item"
            :class="{ selected: selectedSceneId === scene.id }"
            @click="selectedSceneId = scene.id"
          >
            <span class="scene-index">{{ index + 1 }}</span>
            <div class="scene-info">
              <div class="scene-name">{{ scene.name }}</div>
              <div class="scene-meta">{{ scene.tasks.length }} 任务 · {{ scene.hours }} 课时</div>
            </div>
            <div class="scene-actions" @click.stop>
              <el-button size="small" :disabled="index === 0" @click="moveScene(index, -1)">上移</el-button>
              <el-button size="small" :disabled="index === scenes.length - 1" @click="moveScene(index, 1)">下移</el-button>
            </div>
          </div>
        </div>
      </el-card>

      <el-card v-if="selectedScene" shadow="never" class="task-card">
        <template #header>
          <span class="card-title">{{ selectedScene.name }} · 任务列表</span>
        </template>
        <el-table :data="selectedScene.tasks" stripe>
          <el-table-column label="任务名称" prop="name" />
          <el-table-column label="课时" prop="estimatedHours" width="100" />
        </el-table>
      </el-card>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { positionApi, batchApi, learnRoadApi } from '@/api/job';
import { scenarioApi, taskApi } from '@/api/scene';
import type { CareerPosition, LearnRoad, LearnRoadStep } from '@/types/job';
import type { Scenario, ScenarioTask } from '@/types/scene';

interface SceneItem {
  id: string;
  name: string;
  hours: number;
  tasks: { id: string; name: string; estimatedHours?: number }[];
}

const view = ref<'list' | 'edit'>('list');
const positions = ref<CareerPosition[]>([]);
const allScenarios = ref<Scenario[]>([]);
const listLoading = ref(false);
const editLoading = ref(false);
const saving = ref(false);
const saved = ref(false);

const searchQuery = ref('');
const filterStatus = ref('all');

const editingPosition = ref<CareerPosition | null>(null);
const scenes = ref<SceneItem[]>([]);
const selectedSceneId = ref<string | null>(null);
const learnRoadId = ref<string | null>(null);
let learnRoadsCache: LearnRoad[] | null = null;

const sceneStats = computed(() => {
  const m = new Map<string, { sceneCount: number; taskCount: number }>();
  for (const s of allScenarios.value) {
    if (!s.careerPositionId) continue;
    const cur = m.get(s.careerPositionId) ?? { sceneCount: 0, taskCount: 0 };
    cur.sceneCount += 1;
    cur.taskCount += s.taskCount ?? 0;
    m.set(s.careerPositionId, cur);
  }
  return m;
});

const filteredPositions = computed(() => {
  let result = positions.value;
  const q = searchQuery.value.trim().toLowerCase();
  if (q) {
    result = result.filter((p) => p.name.toLowerCase().includes(q) || (p.shortName || '').toLowerCase().includes(q));
  }
  if (filterStatus.value !== 'all') {
    result = result.filter((p) => p.status === filterStatus.value);
  }
  return result;
});

const selectedScene = computed(() => scenes.value.find((s) => s.id === selectedSceneId.value) || null);

async function loadList() {
  listLoading.value = true;
  try {
    const [posRes, roadRes, scenarioRes] = await Promise.all([
      positionApi.list({ limit: 1000 }),
      learnRoadApi.list({ limit: 1000 }),
      scenarioApi.list({ limit: 1000 })
    ]);
    positions.value = posRes.items;
    learnRoadsCache = roadRes.items;
    allScenarios.value = scenarioRes.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    listLoading.value = false;
  }
}

function tasksToSceneItems(scenario: Scenario, tasks: ScenarioTask[]): SceneItem {
  const scenarioTasks = tasks
    .filter((t) => t.scenarioId === scenario.id)
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((t) => ({ id: t.id, name: t.name, estimatedHours: t.estimatedHours }));
  return {
    id: scenario.id,
    name: scenario.name,
    hours: scenarioTasks.reduce((sum, t) => sum + (t.estimatedHours || 0), 0),
    tasks: scenarioTasks
  };
}

function orderScenesByRoad(roads: LearnRoad[], scenarios: Scenario[]): Scenario[] {
  const steps = (roads[0]?.steps || []) as LearnRoadStep[];
  const ordered: Scenario[] = [];
  const used = new Set<string>();
  for (const step of steps) {
    if (!step.scenarioId) continue;
    const s = scenarios.find((x) => x.id === step.scenarioId);
    if (s && !used.has(s.id)) {
      ordered.push(s);
      used.add(s.id);
    }
  }
  for (const s of scenarios) {
    if (!used.has(s.id)) ordered.push(s);
  }
  return ordered;
}

async function handleEdit(position: CareerPosition) {
  view.value = 'edit';
  editingPosition.value = position;
  saved.value = false;
  editLoading.value = true;
  try {
    const scenarioRes = await scenarioApi.list({ careerPositionId: position.id, limit: 1000 });
    const scens = (scenarioRes.items || []).filter((s) => s.status && s.status !== 'archived');
    const taskResults = scens.length
      ? await Promise.all(scens.map((s) => taskApi.list({ scenarioId: s.id, limit: 1000 })))
      : [];
    const allTasks = taskResults.flatMap((r) => r.items || []);

    const roads = learnRoadsCache ?? (await learnRoadApi.list({ limit: 1000 })).items;
    learnRoadsCache = roads;
    const existing = roads.find((r) => r.positionIds?.includes(position.id));
    learnRoadId.value = existing?.id || null;

    const ordered = existing ? orderScenesByRoad([existing], scens) : scens;
    scenes.value = ordered.map((s) => tasksToSceneItems(s, allTasks));
    selectedSceneId.value = scenes.value[0]?.id || null;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
    scenes.value = [];
    selectedSceneId.value = null;
  } finally {
    editLoading.value = false;
  }
}

function handleBack() {
  view.value = 'list';
  editingPosition.value = null;
  scenes.value = [];
  selectedSceneId.value = null;
  learnRoadId.value = null;
  saved.value = false;
}

function moveScene(index: number, direction: -1 | 1) {
  const newIndex = index + direction;
  if (newIndex < 0 || newIndex >= scenes.value.length) return;
  const arr = [...scenes.value];
  const [moved] = arr.splice(index, 1);
  arr.splice(newIndex, 0, moved);
  scenes.value = arr;
  saved.value = false;
}

async function handleSave() {
  const position = editingPosition.value;
  if (!position) return;
  const steps: LearnRoadStep[] = scenes.value.map((s) => ({
    name: s.name,
    scenarioId: s.id,
    tasks: s.tasks.map((t) => ({ id: t.id, name: t.name }))
  }));
  saving.value = true;
  try {
    let id = learnRoadId.value;
    if (!id) {
      const created = await learnRoadApi.create({
        name: `${position.name}学习路径`,
        positionIds: [position.id],
        steps
      });
      id = created.id;
      learnRoadId.value = id;
      if (learnRoadsCache) learnRoadsCache = [created, ...learnRoadsCache];
    } else {
      await learnRoadApi.update(id, {
        name: `${position.name}学习路径`,
        positionIds: [position.id],
        steps
      });
    }
    saved.value = true;
    ElMessage.success('学习路径顺序已更新');
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

onMounted(loadList);
</script>

<style scoped>
.learn-roads { padding: 16px; }
.page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px; }
.header-left { display: flex; align-items: center; gap: 12px; }
.page-title { font-size: 20px; font-weight: 700; margin: 0; }
.page-sub { color: #909399; margin: 8px 0 0; }
.filter-card { margin-bottom: 16px; }
.filter-row { display: flex; gap: 12px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; }
.pos-name { font-weight: 600; }
.sub { color: #909399; font-size: 12px; }
.scene-list { display: flex; flex-direction: column; gap: 8px; }
.scene-item {
  display: flex; align-items: center; gap: 12px; padding: 12px 14px;
  border: 1px solid #e4e7ed; border-radius: 8px; cursor: pointer; transition: all .2s;
}
.scene-item:hover { background: #f5f7fa; }
.scene-item.selected { border-color: #409eff; background: #ecf5ff; }
.scene-index { display: inline-flex; width: 28px; height: 28px; align-items: center; justify-content: center; border-radius: 50%; background: #e4e7ed; color: #606266; font-weight: 600; }
.scene-item.selected .scene-index { background: #409eff; color: #fff; }
.scene-info { flex: 1; }
.scene-name { font-weight: 600; }
.scene-meta { color: #909399; font-size: 12px; margin-top: 2px; }
.scene-actions { display: flex; gap: 4px; }
.task-card { margin-top: 16px; }
</style>

// apps/edu/app/job/learn-roads/page.tsx
'use client'

import { useState, useEffect, useMemo, useRef, useCallback } from 'react'
import Image from 'next/image'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  ArrowUp,
  ArrowDown,
  Save,
  Search,
  ArrowLeft,
  Pencil,
  FolderOpen,
  ChevronRight,
  Flag,
  ShoppingCart,
  Smartphone,
  BarChart3,
  GitBranch,
  Users,
  Layers,
  ChevronLeft,
  GripVertical,
  Loader2,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { positionApi, batchApi, learnRoadApi, scenarioApi, taskApi } from '@/lib/api'

import {
  convertCareerPositionToPosition,
  convertJobBatchToBatch,
} from '@/lib/converters/job-converters'
import { useToast } from '@zhiyu/ui'
import type { Position, PositionStatus, Batch } from '@/lib/types/job-source'
import type { LearnRoad, LearnRoadStep } from '@/lib/types/job'
import type { Scenario, ScenarioTask } from '@/lib/types/scene'
import { TableRowActions } from '@/components/shared/table-row-actions'

interface Task {
  id: string
  name: string
  estimatedHours?: number
}

interface Scene {
  id: string
  name: string
  coverImage?: string
  hours: number
  tasks: Task[]
}

const NODE_ICONS = [Flag, ShoppingCart, Smartphone, BarChart3, GitBranch, Users, Layers]
const NODE_COLORS = [
  { bg: 'bg-blue-500' },
  { bg: 'bg-green-500' },
  { bg: 'bg-amber-400' },
  { bg: 'bg-pink-500' },
  { bg: 'bg-purple-500' },
  { bg: 'bg-indigo-500' },
  { bg: 'bg-rose-500' },
]

function tasksForScenario(scenarioId: string, allTasks: ScenarioTask[]): Task[] {
  return allTasks
    .filter((t) => t.scenarioId === scenarioId)
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((t) => ({ id: t.id, name: t.name, estimatedHours: t.estimatedHours }))
}

function scenarioToScene(scenario: Scenario, allTasks: ScenarioTask[]): Scene {
  const tasks = tasksForScenario(scenario.id, allTasks)
  return {
    id: scenario.id,
    name: scenario.name,
    coverImage: scenario.coverImage,
    hours: tasks.reduce((sum, t) => sum + (t.estimatedHours || 0), 0),
    tasks,
  }
}

function stepsToScenes(
  steps: LearnRoadStep[],
  scenarios: Scenario[],
  allTasks: ScenarioTask[],
): Scene[] {
  const scenarioMap = new Map(scenarios.map((s) => [s.id, s]))
  const result: Scene[] = []
  const usedScenarioIds = new Set<string>()

  for (const step of steps) {
    if (step.scenarioId && scenarioMap.has(step.scenarioId)) {
      const sc = scenarioMap.get(step.scenarioId)!
      result.push(scenarioToScene(sc, allTasks))
      usedScenarioIds.add(sc.id)
      continue
    }
    // 兼容旧数据：按名称匹配场景
    const matched = scenarios.find((s) => s.name === step.name && !usedScenarioIds.has(s.id))
    if (matched) {
      result.push(scenarioToScene(matched, allTasks))
      usedScenarioIds.add(matched.id)
      continue
    }
    // 未匹配到真实场景的步骤，保留名称和缓存的任务
    const orphanTasks = Array.isArray(step.tasks)
      ? step.tasks.map((t) => ({ id: String(t.id), name: String(t.name) }))
      : []
    result.push({
      id: `orphan-${step.name}-${Math.random().toString(36).slice(2, 8)}`,
      name: step.name,
      hours: 0,
      tasks: orphanTasks,
    })
  }

  // 追加尚未纳入学习路径的新场景
  for (const sc of scenarios) {
    if (!usedScenarioIds.has(sc.id)) {
      result.push(scenarioToScene(sc, allTasks))
    }
  }

  return result
}

function scenesToSteps(scenes: Scene[]): LearnRoadStep[] {
  return scenes.map((scene) => ({
    name: scene.name,
    scenarioId: scene.id.startsWith('orphan-') ? undefined : scene.id,
    tasks: scene.tasks,
  }))
}

function countScenesAndTasks(road?: LearnRoad): { sceneCount: number; taskCount: number } {
  const steps = road?.steps || []
  return {
    sceneCount: steps.length,
    taskCount: steps.reduce(
      (sum, step) => sum + (Array.isArray(step.tasks) ? step.tasks.length : 0),
      0,
    ),
  }
}

interface EditViewProps {
  editingPosition: Position
  batches: Batch[]
  scenes: Scene[]
  setScenes: React.Dispatch<React.SetStateAction<Scene[]>>
  selectedSceneId: string | null
  setSelectedSceneId: React.Dispatch<React.SetStateAction<string | null>>
  positionScenarios: Scenario[]
  positionTasks: ScenarioTask[]
  editLoading: boolean
  saving: boolean
  saved: boolean
  onBack: () => void
  onSave: () => void
  setSaved: React.Dispatch<React.SetStateAction<boolean>>
  moveScene: (index: number, direction: -1 | 1) => void
}

function EditView({
  editingPosition,
  batches,
  scenes,
  setScenes,
  selectedSceneId,
  setSelectedSceneId,
  positionScenarios,
  positionTasks,
  editLoading,
  saving,
  saved,
  onBack,
  onSave,
  setSaved,
  moveScene,
}: EditViewProps) {
  const timelineRef = useRef<HTMLDivElement>(null)
  const [draggingIndex, setDraggingIndex] = useState<number | null>(null)
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)

  const batch = batches.find((b) => b.id === editingPosition.batchId)

  const scrollTimeline = (direction: -1 | 1) => {
    timelineRef.current?.scrollBy({ left: direction * 200, behavior: 'smooth' })
  }

  const handleDragStart = (index: number) => {
    setDraggingIndex(index)
  }

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault()
    setDragOverIndex(index)
  }

  const handleDrop = (e: React.DragEvent, targetIndex: number) => {
    e.preventDefault()
    if (draggingIndex === null || draggingIndex === targetIndex) {
      setDraggingIndex(null)
      setDragOverIndex(null)
      return
    }
    const newScenes = [...scenes]
    const [moved] = newScenes.splice(draggingIndex, 1)
    newScenes.splice(targetIndex, 0, moved)
    setScenes(newScenes)
    setSaved(false)
    setDraggingIndex(null)
    setDragOverIndex(null)
  }

  const handleDragEnd = () => {
    setDraggingIndex(null)
    setDragOverIndex(null)
  }

  return (
    <div className="space-y-6 relative">
      {editLoading && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-white/70 backdrop-blur-sm rounded-lg">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={onBack} disabled={editLoading}>
            <ArrowLeft className="mr-1 h-4 w-4" />
            返回岗位列表
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-foreground">{editingPosition.name}</h1>
            <p className="text-muted-foreground mt-1">
              {batch ? batch.name : '未关联批次'} · {editingPosition.shortName}
            </p>
            <p className="text-xs text-muted-foreground mt-1">
              已加载 {positionScenarios.length} 个场景，{positionTasks.length} 个任务
              {scenes.length === 0 &&
                positionScenarios.length > 0 &&
                ' · 点击下方“保存顺序”生成学习路径'}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button onClick={onSave} disabled={editLoading || saving}>
            {saving ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Save className="mr-2 h-4 w-4" />
            )}
            {saved ? '已保存' : '保存顺序'}
          </Button>
        </div>
      </div>

      <div className="space-y-6">
        <div className="rounded-2xl bg-[#f8f5f0] p-6 sm:p-8 relative overflow-hidden">
          <h2 className="text-center text-xl sm:text-2xl font-bold text-slate-800">
            {editingPosition.name}学习路径
          </h2>
          <p className="text-center text-sm text-slate-500 mt-2">
            点击上方阶段图标，查看该阶段的学习任务
          </p>
          <div className="relative mt-8">
            <button
              onClick={() => scrollTimeline(-1)}
              className="absolute left-0 top-1/2 -translate-y-1/2 z-20 flex h-8 w-8 items-center justify-center rounded-full bg-white/80 text-slate-500 shadow-sm hover:bg-white"
            >
              <ChevronLeft className="h-5 w-5" />
            </button>
            <button
              onClick={() => scrollTimeline(1)}
              className="absolute right-0 top-1/2 -translate-y-1/2 z-20 flex h-8 w-8 items-center justify-center rounded-full bg-white/80 text-slate-500 shadow-sm hover:bg-white"
            >
              <ChevronRight className="h-5 w-5" />
            </button>
            <div ref={timelineRef} className="overflow-x-auto pb-4 px-8">
              <div className="relative flex items-start justify-between min-w-max">
                <div className="absolute top-14 left-0 right-0 h-1.5 rounded-full bg-gradient-to-r from-blue-400 via-green-400 via-amber-400 via-pink-400 via-purple-500 to-rose-500" />
                {scenes.map((scene, idx) => {
                  const Icon = NODE_ICONS[idx % NODE_ICONS.length]
                  const color = NODE_COLORS[idx % NODE_COLORS.length]
                  const isSelected = selectedSceneId === scene.id
                  return (
                    <button
                      key={scene.id}
                      onClick={() => setSelectedSceneId(scene.id)}
                      className="relative z-10 flex flex-col items-center min-w-[150px] mx-3 first:ml-4 last:mr-4"
                    >
                      <div className="h-5 text-xs text-slate-400">
                        {idx === 0 ? 'START · 第1站' : `第${idx + 1}站`}
                      </div>
                      {scene.coverImage ? (
                        <div
                          className={cn(
                            'relative mt-2 flex h-14 w-14 items-center justify-center rounded-full overflow-hidden shadow-lg transition-transform bg-white',
                            isSelected && 'ring-4 ring-white scale-110',
                          )}
                        >
                          <Image
                            src={scene.coverImage}
                            alt={scene.name}
                            fill
                            className="object-cover"
                          />
                        </div>
                      ) : (
                        <div
                          className={cn(
                            'mt-2 flex h-14 w-14 items-center justify-center rounded-full text-white shadow-lg transition-transform',
                            color.bg,
                            isSelected && 'ring-4 ring-white scale-110',
                          )}
                        >
                          <Icon className="h-6 w-6" />
                        </div>
                      )}
                      <div
                        className={cn(
                          'mt-3 text-sm font-bold text-center max-w-[140px]',
                          isSelected ? 'text-blue-600' : 'text-slate-800',
                        )}
                      >
                        {scene.name}
                      </div>
                      <div className="text-xs text-slate-500 mt-1">
                        {scene.tasks.length} 任务 · {scene.hours} 课时
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>
          </div>
          {scenes.length === 0 && !editLoading && (
            <div className="text-center py-10 text-slate-500">
              <Layers className="h-10 w-10 mx-auto mb-2 opacity-40" />
              <p>该岗位下暂无已发布场景，请先创建并发布场景</p>
            </div>
          )}
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">场景顺序</CardTitle>
            <CardDescription>拖拽场景卡片可调整顺序，点击场景查看任务</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {scenes.map((scene, index) => {
              const isSelected = selectedSceneId === scene.id
              return (
                <div
                  key={scene.id}
                  draggable
                  onDragStart={() => handleDragStart(index)}
                  onDragOver={(e) => handleDragOver(e, index)}
                  onDrop={(e) => handleDrop(e, index)}
                  onDragLeave={() => setDragOverIndex(null)}
                  onDragEnd={handleDragEnd}
                  onClick={() => setSelectedSceneId(scene.id)}
                  className={cn(
                    'group flex cursor-pointer items-center justify-between rounded-lg border p-4 transition-all',
                    isSelected
                      ? 'border-blue-500 bg-blue-50 shadow-sm'
                      : 'border-slate-200 bg-white hover:bg-slate-50',
                    draggingIndex === index && 'opacity-40',
                    dragOverIndex === index &&
                      dragOverIndex !== draggingIndex &&
                      'border-blue-400 bg-blue-50/60',
                  )}
                >
                  <div className="flex items-center gap-3">
                    <span
                      className="cursor-grab text-slate-400 hover:text-slate-600 active:cursor-grabbing"
                      onMouseDown={(e) => e.stopPropagation()}
                    >
                      <GripVertical className="h-5 w-5" />
                    </span>
                    {scene.coverImage ? (
                      <Image
                        src={scene.coverImage}
                        alt={scene.name}
                        width={32}
                        height={32}
                        className="rounded-full object-cover border border-slate-200"
                      />
                    ) : (
                      <span
                        className={cn(
                          'flex h-8 w-8 items-center justify-center rounded-full text-sm font-medium transition-colors',
                          isSelected
                            ? 'bg-blue-500 text-white'
                            : 'bg-slate-100 text-slate-600 group-hover:bg-slate-200',
                        )}
                      >
                        {index + 1}
                      </span>
                    )}
                    <div>
                      <div
                        className={cn(
                          'font-medium transition-colors',
                          isSelected ? 'text-blue-700' : 'text-slate-900',
                        )}
                      >
                        {scene.name}
                      </div>
                      <div className="text-xs text-slate-500">
                        {scene.tasks.length} 任务 · {scene.hours} 课时
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-1">
                    {isSelected && (
                      <ChevronRight className="h-5 w-5 text-blue-500 animate-in fade-in duration-200" />
                    )}
                    <Button
                      variant="ghost"
                      size="icon"
                      disabled={index === 0}
                      onClick={(e) => {
                        e.stopPropagation()
                        moveScene(index, -1)
                      }}
                    >
                      <ArrowUp className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      disabled={index === scenes.length - 1}
                      onClick={(e) => {
                        e.stopPropagation()
                        moveScene(index, 1)
                      }}
                    >
                      <ArrowDown className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              )
            })}
            {scenes.length === 0 && !editLoading && (
              <div className="text-center py-8 text-slate-500">
                <FolderOpen className="h-8 w-8 mx-auto mb-2 opacity-40" />
                <p>暂无可排序的场景</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

export default function LearnRoadsPage() {
  const { toast } = useToast()

  const [positions, setPositions] = useState<Position[]>([])
  const [batches, setBatches] = useState<Batch[]>([])
  const [dataLoading, setDataLoading] = useState(false)

  const [view, setView] = useState<'list' | 'edit'>('list')
  const [editingPosition, setEditingPosition] = useState<Position | null>(null)

  const [scenes, setScenes] = useState<Scene[]>([])
  const [selectedSceneId, setSelectedSceneId] = useState<string | null>(null)
  const [saved, setSaved] = useState(false)
  const [learnRoadId, setLearnRoadId] = useState<string | null>(null)
  const [learnRoads, setLearnRoads] = useState<LearnRoad[]>([])
  const [positionScenarios, setPositionScenarios] = useState<Scenario[]>([])
  const [positionTasks, setPositionTasks] = useState<ScenarioTask[]>([])

  const [listLoading, setListLoading] = useState(false)
  const [editLoading, setEditLoading] = useState(false)
  const [saving, setSaving] = useState(false)

  const [searchQuery, setSearchQuery] = useState('')
  const [filterStatus, setFilterStatus] = useState<'all' | PositionStatus>('all')

  const loadJobData = useCallback(async () => {
    setDataLoading(true)
    try {
      const [posRes, batchRes] = await Promise.all([
        positionApi.list({ limit: 1000 }),
        batchApi.list({ limit: 1000 }),
      ])
      setPositions(posRes.items.map(convertCareerPositionToPosition))
      setBatches(batchRes.items.map(convertJobBatchToBatch))
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: '加载失败',
        description: err?.message || '请稍后重试',
      })
    } finally {
      setDataLoading(false)
    }
  }, [toast])

  useEffect(() => {
    ;(async () => {
      await loadJobData()
    })()
  }, [loadJobData])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      setListLoading(true)
      try {
        const res = await learnRoadApi.list({ limit: 1000 })
        if (!cancelled) setLearnRoads(res.items || [])
      } catch (err) {
        toast({
          title: '加载失败',
          description: err instanceof Error ? err.message : '无法获取学习路径数据',
          variant: 'destructive',
        })
      } finally {
        if (!cancelled) setListLoading(false)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [toast])

  const getRoadForPosition = (positionId: string) =>
    learnRoads.find((r) => r.positionIds?.includes(positionId))

  const filteredPositions = useMemo(() => {
    let result = positions
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase()
      result = result.filter(
        (p) => p.name.toLowerCase().includes(q) || p.shortName.toLowerCase().includes(q),
      )
    }
    if (filterStatus !== 'all') {
      result = result.filter((p) => p.status === filterStatus)
    }
    return result
  }, [positions, searchQuery, filterStatus])

  const loadPositionScenes = useCallback(
    async (positionId: string) => {
      try {
        const scenarioRes = await scenarioApi.list({
          careerPositionId: positionId,
          limit: 1000,
        })
        const scens = (scenarioRes.items || []).filter((s) => s.status && s.status !== 'archived')
        const taskResults = scens.length
          ? await Promise.all(scens.map((s) => taskApi.list({ scenarioId: s.id, limit: 1000 })))
          : []
        const allTasks = taskResults.flatMap((r) => r.items || [])
        setPositionScenarios(scens)
        setPositionTasks(allTasks)
        return { scenarios: scens, tasks: allTasks }
      } catch (err) {
        console.error('[learn-roads] load scenes failed', err)
        toast({
          title: '加载场景失败',
          description: err instanceof Error ? err.message : '请稍后重试',
          variant: 'destructive',
        })
        setPositionScenarios([])
        setPositionTasks([])
        return { scenarios: [] as Scenario[], tasks: [] as ScenarioTask[] }
      }
    },
    [toast],
  )

  const handleEdit = useCallback(
    async (position: Position) => {
      setEditingPosition(position)
      setView('edit')
      setSaved(false)
      setEditLoading(true)

      try {
        const [{ items: roads = [] }, { scenarios, tasks }] = await Promise.all([
          learnRoadApi.list({ limit: 1000 }),
          loadPositionScenes(position.id),
        ])
        setLearnRoads(roads)

        const existing = roads.find((r) => r.positionIds?.includes(position.id))
        let loadedScenes: Scene[] = []
        if (existing?.id) {
          setLearnRoadId(existing.id)
          loadedScenes = stepsToScenes(existing.steps || [], scenarios, tasks)
        } else {
          // 无已有路径时不立即写库，进入本地编辑态，保存时才创建
          setLearnRoadId(null)
          loadedScenes = scenarios.length
            ? scenarios.map((s) => scenarioToScene(s, tasks))
            : []
        }
        setScenes(loadedScenes)
        setSelectedSceneId(loadedScenes[0]?.id || null)
      } catch (err) {
        toast({
          title: '加载失败',
          description: err instanceof Error ? err.message : '请稍后重试',
          variant: 'destructive',
        })
        setLearnRoadId(null)
        setScenes([])
        setSelectedSceneId(null)
        setPositionScenarios([])
        setPositionTasks([])
      } finally {
        setEditLoading(false)
      }
    },
    [loadPositionScenes, toast],
  )

  const handleBack = () => {
    setView('list')
    setEditingPosition(null)
    setSaved(false)
    setLearnRoadId(null)
    setScenes([])
    setSelectedSceneId(null)
    setPositionScenarios([])
    setPositionTasks([])
  }

  const moveScene = (index: number, direction: -1 | 1) => {
    const newIndex = index + direction
    if (newIndex < 0 || newIndex >= scenes.length) return
    const newScenes = [...scenes]
    const [moved] = newScenes.splice(index, 1)
    newScenes.splice(newIndex, 0, moved)
    setScenes(newScenes)
    setSaved(false)
  }

  const handleSave = async () => {
    if (!editingPosition) return
    setSaving(true)
    try {
      const steps = scenesToSteps(scenes)
      let id = learnRoadId
      // 本地编辑态下尚无路径记录，先创建再更新
      if (!id) {
        const created = await learnRoadApi.create({
          name: `${editingPosition.name}学习路径`,
          positionIds: [editingPosition.id],
          steps,
        })
        id = created.id
        setLearnRoads((prev) => [created, ...prev])
        setLearnRoadId(id)
      }
      const updated = await learnRoadApi.update(id, {
        name: `${editingPosition.name}学习路径`,
        positionIds: [editingPosition.id],
        steps,
      })
      setLearnRoads((prev) => prev.map((r) => (r.id === updated.id ? updated : r)))
      setSaved(true)
      setTimeout(() => setSaved(false), 2000)
      toast({ title: '保存成功', description: '学习路径顺序已更新' })
    } catch (err) {
      toast({
        title: '保存失败',
        description: err instanceof Error ? err.message : '请稍后重试',
        variant: 'destructive',
      })
    } finally {
      setSaving(false)
    }
  }

  const ListView = () => (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">岗位学习路径管理</h1>
        <p className="text-muted-foreground mt-1">按岗位管理学习路径中场景与任务的展示顺序</p>
      </div>

      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="搜索岗位名称、简称..."
                className="pl-9"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            <Select
              value={filterStatus}
              onValueChange={(v) => setFilterStatus(v as typeof filterStatus)}
            >
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">全部状态</SelectItem>
                <SelectItem value="draft">草稿</SelectItem>
                <SelectItem value="pending">审批中</SelectItem>
                <SelectItem value="approved">已通过</SelectItem>
                <SelectItem value="rejected">已驳回</SelectItem>
                <SelectItem value="published">已发布</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <CardTitle>岗位列表</CardTitle>
            {(listLoading || dataLoading) && (
              <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
            )}
          </div>
          <CardDescription>共 {filteredPositions.length} 个岗位</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>岗位名称</TableHead>
                <TableHead>场景数</TableHead>
                <TableHead>任务数</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredPositions.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={4} className="h-32 text-center">
                    <div className="flex flex-col items-center justify-center text-muted-foreground">
                      <FolderOpen className="h-10 w-10 mb-2" />
                      <p>暂无岗位数据</p>
                    </div>
                  </TableCell>
                </TableRow>
              ) : (
                filteredPositions.map((position) => {
                  const { sceneCount, taskCount } = countScenesAndTasks(
                    getRoadForPosition(position.id),
                  )

                  return (
                    <TableRow key={position.id} className="group">
                      <TableCell>
                        <span className="font-medium text-foreground">{position.name}</span>
                        <p className="text-xs text-muted-foreground mt-0.5">{position.shortName}</p>
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant="secondary"
                          className="bg-blue-50 text-blue-600 hover:bg-blue-50"
                        >
                          {sceneCount}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant="secondary"
                          className="bg-purple-50 text-purple-600 hover:bg-purple-50"
                        >
                          {taskCount}
                        </Badge>
                      </TableCell>
                      <TableRowActions>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() => handleEdit(position)}
                          disabled={editLoading}
                        >
                          <Pencil className="mr-1 h-3 w-3" />
                          编辑学习路径
                        </Button>
                      </TableRowActions>
                    </TableRow>
                  )
                })
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )

  return (
    <div className="space-y-6">
      {view === 'list' ? (
        ListView()
      ) : editingPosition ? (
        <EditView
          editingPosition={editingPosition}
          batches={batches}
          scenes={scenes}
          setScenes={setScenes}
          selectedSceneId={selectedSceneId}
          setSelectedSceneId={setSelectedSceneId}
          positionScenarios={positionScenarios}
          positionTasks={positionTasks}
          editLoading={editLoading}
          saving={saving}
          saved={saved}
          onBack={handleBack}
          onSave={handleSave}
          setSaved={setSaved}
          moveScene={moveScene}
        />
      ) : null}
    </div>
  )
}
