// frontend/portal-vue/src/views/portal/alliance/enterprises.vue
<template>
  <PublicListShell
    title="合作企业"
    subtitle="查看全部校企合作企业，按合作等级筛选"
    :icon="OfficeBuilding"
    :tabs="tabs"
    :active-tab="tab"
    :keyword="keyword"
    placeholder="搜索企业名称、行业或地区..."
    :loading="loading"
    @update:active-tab="tab = $event"
    @update:keyword="keyword = $event"
  >
    <div v-if="filtered.length === 0" class="empty">
      <el-icon :size="48" class="empty-icon"><OfficeBuilding /></el-icon>
      <div class="empty-title">暂无合作企业</div>
      <div class="empty-hint">发布后的合作企业会展示在这里</div>
    </div>
    <div v-else class="grid-3">
      <EnterpriseCard v-for="item in filtered" :key="item.id" :enterprise="item" />
    </div>
  </PublicListShell>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { OfficeBuilding } from '@element-plus/icons-vue';
import { portalRequest } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import PublicListShell from './components/PublicListShell.vue';
import EnterpriseCard from './components/EnterpriseCard.vue';
import { fetchAllPages, type AllianceEnterprise } from './shared';

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const items = ref<AllianceEnterprise[]>([]);
const loading = ref(true);
const tab = ref('all');
const keyword = ref('');

const RATING_TABS = [
  { value: 'strategic', label: '战略合作' },
  { value: 'deep', label: '深度合作' },
  { value: 'general', label: '一般合作' },
];

const tabs = computed(() => [
  { value: 'all', label: '全部企业', count: items.value.length },
  ...RATING_TABS.map((t) => ({
    value: t.value,
    label: t.label,
    count: items.value.filter((i) => i.rating === t.value).length,
  })),
]);

const filtered = computed(() => {
  let list = items.value;
  if (tab.value !== 'all') list = list.filter((i) => i.rating === tab.value);
  if (keyword.value.trim()) {
    const q = keyword.value.trim().toLowerCase();
    list = list.filter(
      (i) =>
        i.name.toLowerCase().includes(q) ||
        (i.industry ?? '').toLowerCase().includes(q) ||
        (i.region ?? '').toLowerCase().includes(q),
    );
  }
  return list;
});

async function load() {
  if (!tenantId.value) {
    loading.value = false;
    return;
  }
  loading.value = true;
  try {
    const list = await fetchAllPages((page, pageSize) =>
      portalRequest<{ items: AllianceEnterprise[] }>(
        `/alliance/public/enterprises?tenantId=${tenantId.value}&limit=${pageSize}&offset=${page * pageSize}`,
      ),
    );
    items.value = list;
  } catch {
    items.value = [];
  } finally {
    loading.value = false;
  }
}

onMounted(load);
</script>

<style scoped>
.grid-3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
.empty { text-align: center; padding: 80px 0; color: #94a3b8; background: #fff; border-radius: 16px; border: 1px solid #e7e5e4; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
.empty-icon { margin: 0 auto 16px; opacity: 0.3; }
.empty-title { font-size: 15px; font-weight: 500; color: #475569; }
.empty-hint { font-size: 13px; margin-top: 4px; }
@media (max-width: 992px) { .grid-3 { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 640px) { .grid-3 { grid-template-columns: 1fr; } }
</style>

// apps/edu/app/portal/alliance/enterprises/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { Building2 } from 'lucide-react'
import { portalRequest } from '@/lib/api'
import type { AllianceEnterprise } from '@/lib/types'
import { reportError } from '@/lib/error-handling'
import { EnterpriseCard } from '@/components/alliance/public-cards'
import { PublicListShell } from '@/components/alliance/public-list-shell'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { fetchAllPages } from '@/lib/fetch-all'

import { useT } from '@/lib/i18n/locale-provider'
const RATING_TABS = [
  { value: 'strategic', label: '战略合作' },
  { value: 'deep', label: '深度合作' },
  { value: 'general', label: '一般合作' },
]

export default function AlliancePublicEnterprisesPage() {
  const t = useT()
  const { tenantId } = usePortalAuth()
  const [items, setItems] = useState<AllianceEnterprise[]>([])
  const [loading, setLoading] = useState(true)
  const [tab, setTab] = useState('all')
  const [keyword, setKeyword] = useState('')

  useEffect(() => {
    if (!tenantId) return
    // 与后台 /portal/apps/alliance/enterprises 一致：仅展示本校链接且企业愿意展示的；
    // 分页全量拉取避免 public 接口 100 条截断导致搜索/评级筛选不全
    const q = `?tenantId=${tenantId}`
    fetchAllPages((page, pageSize) =>
      portalRequest<{ items: AllianceEnterprise[] }>(
        `/alliance/public/enterprises${q}${q ? '&' : '?'}limit=${pageSize}&offset=${page * pageSize}`,
      ),
    )
      .then((items) => setItems(items))
      .catch((err) => {
        reportError(err, { source: '加载合作企业列表' })
      })
      .finally(() => setLoading(false))
  }, [tenantId])

  const tabs = useMemo(
    () => [
      { value: 'all', label: t('全部企业'), count: items.length },
      ...RATING_TABS.map((tab) => ({
        value: tab.value,
        label: t(tab.label),
        count: items.filter((i) => i.rating === tab.value).length,
      })),
    ],
    [items, t],
  )

  const filtered = useMemo(() => {
    let list = items
    if (tab !== 'all') list = list.filter((i) => i.rating === tab)
    if (keyword.trim()) {
      const q = keyword.trim().toLowerCase()
      list = list.filter(
        (i) =>
          i.name.toLowerCase().includes(q) ||
          (i.industry ?? '').toLowerCase().includes(q) ||
          (i.region ?? '').toLowerCase().includes(q),
      )
    }
    return list
  }, [items, tab, keyword])

  return (
    <PublicListShell
      title={t('合作企业')}
      subtitle={t('查看全部校企合作企业，按合作等级筛选')}
      icon={<Building2 className="w-7 h-7 text-white" />}
      tabs={tabs}
      activeTab={tab}
      onTabChange={setTab}
      keyword={keyword}
      onKeywordChange={setKeyword}
      placeholder={t('搜索企业名称、行业或地区...')}
      loading={loading}
    >
      {filtered.length === 0 ? (
        <div className="text-center py-20 text-[#94a3b8] bg-white rounded-2xl border border-[#e7e5e4] shadow-sm">
          <Building2 className="h-12 w-12 mx-auto mb-4 opacity-30" />
          <div className="text-[15px] font-medium text-[#475569]">{t('暂无合作企业')}</div>
          <div className="text-[13px] mt-1">{t('发布后的合作企业会展示在这里')}</div>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {filtered.map((item) => (
            <EnterpriseCard key={item.id} enterprise={item} />
          ))}
        </div>
      )}
    </PublicListShell>
  )
}
