// frontend/portal-vue/src/components/batch-group-page.vue
<template>
  <div class="list-page">
    <!-- 页头：标题 + 副标题 + 新建批次 -->
    <div class="page-header">
      <div>
        <h2 class="page-title">{{ title }}</h2>
        <p v-if="subtitle" class="page-subtitle">{{ subtitle }}</p>
      </div>
      <el-button type="primary" @click="openCreate">
        <el-icon><Plus /></el-icon>
        新建批次
      </el-button>
    </div>

    <!-- 搜索 / 状态筛选 -->
    <el-card shadow="never" class="filter-card">
      <div class="filter-row">
        <el-input
          v-model="searchQuery"
          :placeholder="searchPlaceholder"
          clearable
          class="search-input"
        >
          <template #prefix><el-icon><Search /></el-icon></template>
        </el-input>
        <el-select v-model="filterStatus" class="status-select">
          <el-option label="全部状态" value="all" />
          <el-option label="开放中" value="open" />
          <el-option label="已截止" value="closed" />
        </el-select>
        <el-button v-if="searchQuery || filterStatus !== 'all'" @click="resetFilters">
          <el-icon><RefreshLeft /></el-icon>
          重置
        </el-button>
      </div>
    </el-card>

    <!-- 批次列表 -->
    <el-card shadow="never">
      <template #header>
        <div class="table-header">
          <span class="card-title">批次列表</span>
          <span class="count">共 {{ filteredBatches.length }} 个批次分组</span>
        </div>
      </template>
      <el-table v-loading="loading" :data="filteredBatches" stripe>
        <el-table-column label="分组名称" min-width="180">
          <template #default="{ row }">
            <router-link v-if="detailHref" :to="detailHref(row.id)" class="name-link">
              {{ row.name }}
            </router-link>
            <span v-else>{{ row.name }}</span>
          </template>
        </el-table-column>
        <el-table-column label="批次编号" width="150">
          <template #default="{ row }">{{ row.code || '-' }}</template>
        </el-table-column>
        <el-table-column label="审批流程" width="180">
          <template #default="{ row }">
            <el-tag v-if="row.workflowName" type="info" effect="plain">{{ row.workflowName }}</el-tag>
            <span v-else>-</span>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.status === 'open' ? 'success' : 'info'">
              {{ row.status === 'open' ? '开放中' : '已截止' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="220" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openEdit(row)">编辑</el-button>
            <el-button v-if="canToggleStatus" size="small" @click="toggleStatus(row)">
              {{ row.status === 'open' ? '截止批次' : '重新开放' }}
            </el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新建 / 编辑批次对话框 -->
    <el-dialog v-model="dialogVisible" :title="editing ? '编辑批次' : '新增批次'" width="520px">
      <el-form label-position="top">
        <el-form-item label="分组名称" required>
          <el-input v-model="form.name" :placeholder="namePlaceholder || '请输入批次名称'" />
        </el-form-item>
        <el-form-item label="关联审批流" required>
          <el-tabs v-if="majors.length > 0" v-model="selectedMajorId" class="major-tabs">
            <el-tab-pane label="全部专业" name="all" />
            <el-tab-pane v-for="m in majors" :key="m.id" :label="m.name" :name="m.id" />
          </el-tabs>
          <div class="workflow-list">
            <el-empty v-if="filteredWorkflows.length === 0" description="暂无审批流程" :image-size="60" />
            <div
              v-for="wf in filteredWorkflows"
              :key="wf.id"
              class="workflow-item"
              :class="{ selected: form.workflowId === wf.id }"
              @click="form.workflowId = wf.id"
            >
              <div class="workflow-main">
                <div class="workflow-name">{{ wf.name }}</div>
                <div v-if="wf.description" class="workflow-desc">{{ wf.description }}</div>
                <div class="workflow-steps">{{ (wf.steps || []).length }} 个审批步骤</div>
              </div>
              <el-icon v-if="form.workflowId === wf.id" class="check-icon"><Check /></el-icon>
            </div>
          </div>
          <p v-if="workflowHint" class="workflow-hint">{{ workflowHint }}</p>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button
          type="primary"
          :loading="saving"
          :disabled="!form.name.trim() || !form.workflowId"
          @click="save"
        >
          {{ editing ? '保存修改' : '创建批次' }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Check, Plus, RefreshLeft, Search } from '@element-plus/icons-vue';
import { majorApi, workflowApi } from '@/api/system';
import type { Major, Workflow } from '@/types/system';

interface BatchApi {
  list: (params?: Record<string, string | number | boolean | undefined>) => Promise<{ items: any[]; total?: number }>;
  create: (req: Record<string, unknown>) => Promise<unknown>;
  update: (id: string, req: Record<string, unknown>) => Promise<unknown>;
  delete: (id: string) => Promise<unknown>;
  updateStatus?: (id: string, status: string) => Promise<unknown>;
}

const props = defineProps<{
  title: string;
  subtitle?: string;
  api: BatchApi;
  namePlaceholder?: string;
  workflowHint?: string;
  searchPlaceholder?: string;
  detailHref?: (id: string) => string;
}>();

const batches = ref<any[]>([]);
const workflows = ref<Workflow[]>([]);
const majors = ref<Major[]>([]);
const loading = ref(false);
const searchQuery = ref('');
const filterStatus = ref<'all' | 'open' | 'closed'>('all');
const dialogVisible = ref(false);
const saving = ref(false);
const editing = ref<any | null>(null);
const form = reactive({ name: '', workflowId: '' });
const selectedMajorId = ref('all');

const canToggleStatus = computed(() => typeof props.api.updateStatus === 'function');

const filteredWorkflows = computed(() => {
  if (selectedMajorId.value === 'all') return workflows.value;
  return workflows.value.filter((wf) => (wf.majorIds || []).includes(selectedMajorId.value));
});

const filteredBatches = computed(() => {
  const q = searchQuery.value.trim().toLowerCase();
  return batches.value.filter((batch) => {
    const matchesSearch =
      !q ||
      String(batch.name || '').toLowerCase().includes(q) ||
      String(batch.code || '').toLowerCase().includes(q);
    const matchesStatus = filterStatus.value === 'all' || batch.status === filterStatus.value;
    return matchesSearch && matchesStatus;
  });
});

async function loadMajors() {
  try {
    const res = await majorApi.list({ limit: 1000 });
    majors.value = res.items.filter((m) => m.enabled);
  } catch {
    majors.value = [];
  }
}

async function loadData() {
  loading.value = true;
  try {
    const [batchRes, wfRes] = await Promise.all([
      props.api.list({ limit: 1000 }),
      workflowApi.list({ limit: 1000 })
    ]);
    workflows.value = wfRes.items;
    const wfMap = new Map(wfRes.items.map((w) => [w.id, w.name]));
    batches.value = (batchRes.items as any[]).map((b) => ({
      ...b,
      workflowName: b.workflowId ? wfMap.get(b.workflowId) : undefined
    }));
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function resetForm() {
  form.name = '';
  form.workflowId = '';
  selectedMajorId.value = 'all';
  editing.value = null;
}

function openCreate() {
  resetForm();
  dialogVisible.value = true;
}

function openEdit(row: any) {
  editing.value = row;
  form.name = row.name || '';
  form.workflowId = row.workflowId || '';
  selectedMajorId.value = 'all';
  dialogVisible.value = true;
}

async function save() {
  if (!form.name.trim() || !form.workflowId) return;
  saving.value = true;
  try {
    const code =
      editing.value?.code ??
      'BG-' + new Date().getFullYear() + '-' + String(Math.floor(Math.random() * 10000)).padStart(4, '0');
    const payload: Record<string, unknown> = {
      name: form.name.trim(),
      code,
      workflowId: form.workflowId,
      status: editing.value?.status ?? 'open'
    };
    if (editing.value) {
      await props.api.update(editing.value.id, payload);
      ElMessage.success('保存成功');
    } else {
      await props.api.create(payload);
      ElMessage.success('创建成功');
    }
    dialogVisible.value = false;
    await loadData();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function toggleStatus(row: any) {
  if (!props.api.updateStatus) return;
  const newStatus = row.status === 'open' ? 'closed' : 'open';
  try {
    await props.api.updateStatus(row.id, newStatus);
    ElMessage.success(newStatus === 'open' ? '批次已重新开放' : '批次已截止');
    await loadData();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function confirmDelete(row: any) {
  try {
    await ElMessageBox.confirm('确定删除该批次吗？', '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消'
    });
  } catch {
    return;
  }
  try {
    await props.api.delete(row.id);
    ElMessage.success('删除成功');
    await loadData();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

function resetFilters() {
  searchQuery.value = '';
  filterStatus.value = 'all';
}

onMounted(() => {
  loadMajors();
  loadData();
});
</script>

<style scoped>
.list-page {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.page-title {
  font-size: 20px;
  font-weight: 600;
  margin: 0;
}
.page-subtitle {
  font-size: 13px;
  color: #909399;
  margin: 4px 0 0;
}
.filter-card :deep(.el-card__body) {
  padding: 16px;
}
.filter-row {
  display: flex;
  gap: 12px;
  align-items: center;
  flex-wrap: wrap;
}
.search-input {
  flex: 1;
  min-width: 220px;
}
.status-select {
  width: 140px;
}
.table-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.card-title {
  font-size: 16px;
  font-weight: 600;
}
.count {
  font-size: 13px;
  color: #909399;
}
.name-link {
  color: #409eff;
  text-decoration: none;
}
.name-link:hover {
  text-decoration: underline;
}
.major-tabs {
  margin-bottom: 8px;
}
.workflow-list {
  max-height: 260px;
  overflow-y: auto;
  border: 1px solid #dcdfe6;
  border-radius: 6px;
}
.workflow-item {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 16px;
  cursor: pointer;
  border-bottom: 1px solid #ebeef5;
}
.workflow-item:last-child {
  border-bottom: none;
}
.workflow-item:hover {
  background: #f5f7fa;
}
.workflow-item.selected {
  background: #ecf5ff;
}
.workflow-main {
  min-width: 0;
}
.workflow-name {
  font-size: 14px;
  font-weight: 500;
}
.workflow-item.selected .workflow-name {
  color: #409eff;
}
.workflow-desc {
  font-size: 12px;
  color: #909399;
  margin-top: 2px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.workflow-steps {
  font-size: 12px;
  color: #c0c4cc;
  margin-top: 4px;
}
.check-icon {
  color: #409eff;
  flex-shrink: 0;
  margin-top: 2px;
}
.workflow-hint {
  font-size: 12px;
  color: #909399;
  margin: 8px 0 0;
}
</style>

// frontend/edu/components/shared/batch-group-page.tsx
'use client'

import { Check, FolderKanban, Pencil, Plus, Power, RotateCcw, Trash2 } from 'lucide-react'
import { Link } from 'react-router'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { SearchInput } from '@/components/shared/search-input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useAuth } from '@/components/auth-provider'
import { StatusBadge } from '@/components/shared/status-badge'
import { workflowApi, majorApi } from '@/lib/api'
import type { Workflow, Major } from '@/lib/types/backend'
import { useToast, EmptyState, TableEmptyRow, FormDialogFooter } from '@zhiyu/ui'
import { cn } from '@/lib/utils'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { useT } from '@/lib/i18n/locale-provider'

export interface BatchGroupItem {
  id: string
  name: string
  code?: string
  workflowId?: string
  status: 'open' | 'closed'
}

export interface BatchGroupApi {
  list: (
    params?: Record<string, string | number | boolean | undefined>,
  ) => Promise<{ items: BatchGroupItem[] }>
  create: (body: Omit<BatchGroupItem, 'id'>) => Promise<BatchGroupItem>
  update: (id: string, body: Partial<Omit<BatchGroupItem, 'id'>>) => Promise<BatchGroupItem>
  delete: (id: string) => Promise<{ id: string }>
  updateStatus: (id: string, status: string) => Promise<BatchGroupItem>
}

interface BatchGroupPageProps {
  api: BatchGroupApi
  subtitle: string
  namePlaceholder: string
  workflowHint: string
  detailHref?: (id: string) => string
}

interface BatchView extends BatchGroupItem {
  workflowName?: string
}

export function BatchGroupPage({
  api,
  subtitle,
  namePlaceholder,
  workflowHint,
  detailHref,
}: BatchGroupPageProps) {
  const { toast } = useToast()
  const { tenantId } = useAuth()
  const t = useT()
  const [batches, setBatches] = useState<BatchView[]>([])
  const [workflows, setWorkflows] = useState<Workflow[]>([])
  const [majors, setMajors] = useState<Major[]>([])
  const [loading, setLoading] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [filterStatus, setFilterStatus] = useState<'all' | 'open' | 'closed'>('all')
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [editingBatch, setEditingBatch] = useState<BatchView | null>(null)
  const [newBatchName, setNewBatchName] = useState('')
  const [newBatchWorkflow, setNewBatchWorkflow] = useState('')
  const [selectedMajorId, setSelectedMajorId] = useState('all')
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null)

  useEffect(() => {
    if (!tenantId) {
      queueMicrotask(() => setMajors([]))
      return
    }
    let cancelled = false
    ;(async () => {
      try {
        const res = await majorApi.list({ tenantId, limit: 1000 })
        if (!cancelled) setMajors(res.items.filter((m) => m.enabled))
      } catch (err: any) {
        if (!cancelled) {
          toast({
            variant: 'destructive',
            title: t('加载专业失败'),
            description: err.message || t('请稍后重试'),
          })
        }
      }
    })()
    return () => {
      cancelled = true
    }
  }, [tenantId, toast, t])

  const loadData = useCallback(async () => {
    setLoading(true)
    try {
      const [batchRes, wfRes] = await Promise.all([
        api.list({ limit: 1000 }),
        workflowApi.list({ limit: 1000 }),
      ])
      setWorkflows(wfRes.items)
      const wfMap = new Map(wfRes.items.map((w) => [w.id, w.name]))
      setBatches(
        (batchRes.items as BatchGroupItem[]).map((b) => ({
          ...b,
          workflowName: b.workflowId ? wfMap.get(b.workflowId) : undefined,
        })),
      )
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('加载失败'),
        description: err.message || t('无法获取批次数据'),
      })
    } finally {
      setLoading(false)
    }
  }, [api, toast, t])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      if (!cancelled) await loadData()
    })()
    return () => {
      cancelled = true
    }
  }, [loadData])

  const filteredWorkflows = useMemo(() => {
    if (selectedMajorId === 'all') return workflows
    return workflows.filter((wf) => (wf.majorIds || []).includes(selectedMajorId))
  }, [workflows, selectedMajorId])

  const filteredBatches = useMemo(() => {
    const q = searchQuery.trim().toLowerCase()
    return batches.filter((batch) => {
      const matchesSearch =
        !q || batch.name.toLowerCase().includes(q) || (batch.code || '').toLowerCase().includes(q)
      const matchesStatus = filterStatus === 'all' || batch.status === filterStatus
      return matchesSearch && matchesStatus
    })
  }, [batches, searchQuery, filterStatus])

  const resetForm = () => {
    setNewBatchName('')
    setNewBatchWorkflow('')
    setSelectedMajorId('all')
    setEditingBatch(null)
  }

  const handleAddBatch = async () => {
    if (!newBatchName || !newBatchWorkflow) return
    try {
      await api.create({
        name: newBatchName,
        code:
          'BG-' +
          new Date().getFullYear() +
          '-' +
          String(Math.floor(Math.random() * 10000)).padStart(4, '0'),
        workflowId: newBatchWorkflow,
        status: 'open',
      })
      await loadData()
      setIsCreateDialogOpen(false)
      resetForm()
      toast({ title: t('创建成功') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('创建失败'),
        description: err.message || t('请稍后重试'),
      })
    }
  }

  const openEdit = (batch: BatchView) => {
    setEditingBatch(batch)
    setNewBatchName(batch.name)
    setNewBatchWorkflow(batch.workflowId || '')
    setSelectedMajorId('all')
    setIsEditDialogOpen(true)
  }

  const handleUpdateBatch = async () => {
    if (!editingBatch || !newBatchName || !newBatchWorkflow) return
    try {
      await api.update(editingBatch.id, {
        name: newBatchName,
        code: editingBatch.code,
        workflowId: newBatchWorkflow,
        status: editingBatch.status,
      })
      await loadData()
      setIsEditDialogOpen(false)
      resetForm()
      toast({ title: t('保存成功') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('保存失败'),
        description: err.message || t('请稍后重试'),
      })
    }
  }

  const handleToggleStatus = async (batch: BatchView) => {
    try {
      const newStatus = batch.status === 'open' ? 'closed' : 'open'
      await api.updateStatus(batch.id, newStatus)
      await loadData()
      toast({ title: newStatus === 'open' ? t('批次已重新开放') : t('批次已截止') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('操作失败'),
        description: err.message || t('请稍后重试'),
      })
    }
  }

  const handleDeleteBatch = (id: string) => {
    setDeleteTargetId(id)
  }
  const confirmDeleteBatch = async () => {
    if (!deleteTargetId) return
    try {
      await api.delete(deleteTargetId)
      await loadData()
      toast({ title: t('删除成功') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('删除失败'),
        description: err.message || t('请稍后重试'),
      })
    } finally {
      setDeleteTargetId(null)
    }
  }

  const renderForm = () => (
    <div className="grid gap-4 py-4">
      <div className="grid gap-2">
        <Label htmlFor="batchName">{t('分组名称')}</Label>
        <Input
          id="batchName"
          value={newBatchName}
          onChange={(e) => setNewBatchName(e.target.value)}
          placeholder={namePlaceholder}
        />
      </div>
      <div className="grid gap-2">
        <Label htmlFor="workflow">
          {t('关联审批流')} <span className="text-red-500">*</span>
        </Label>
        {majors.length > 0 && (
          <Tabs value={selectedMajorId} onValueChange={setSelectedMajorId}>
            <TabsList className="h-auto flex-wrap justify-start">
              <TabsTrigger value="all">{t('全部专业')}</TabsTrigger>
              {majors.map((m) => (
                <TabsTrigger key={m.id} value={m.id}>
                  {m.name}
                </TabsTrigger>
              ))}
            </TabsList>
          </Tabs>
        )}
        <div className="rounded-lg border border-slate-200 bg-white overflow-hidden max-h-[260px] overflow-y-auto">
          {filteredWorkflows.length === 0 ? (
            <EmptyState
              title={t('暂无审批流程')}
              titleClassName="text-gray-500"
              className="px-4 py-6"
            />
          ) : (
            filteredWorkflows.map((wf) => {
              const selected = newBatchWorkflow === wf.id
              return (
                <div
                  key={wf.id}
                  onClick={() => setNewBatchWorkflow(wf.id)}
                  className={cn(
                    'px-4 py-3 cursor-pointer border-b border-slate-100 last:border-b-0 hover:bg-slate-50 flex items-start justify-between gap-3',
                    selected && 'bg-primary/5',
                  )}
                >
                  <div className="min-w-0">
                    <div className={cn('font-medium text-sm', selected && 'text-primary')}>
                      {wf.name}
                    </div>
                    {wf.description ? (
                      <div className="text-xs text-gray-500 mt-0.5 truncate">{wf.description}</div>
                    ) : null}
                    <div className="text-xs text-gray-400 mt-1">
                      {t('{n} 个审批步骤', { n: (wf.steps || []).length })}
                    </div>
                  </div>
                  {selected && <Check className="h-4 w-4 text-primary shrink-0 mt-0.5" />}
                </div>
              )
            })
          )}
        </div>
        <p className="text-xs text-gray-500">{workflowHint}</p>
      </div>
    </div>
  )

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground">{t('批次分组管理')}</h1>
          <p className="text-sm text-muted-foreground mt-1">{subtitle}</p>
        </div>
        <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              {t('新建批次')}
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>{t('新增批次')}</DialogTitle>
              <DialogDescription>{t('创建新的批次分组，并关联审批流程。')}</DialogDescription>
            </DialogHeader>
            <form
              onSubmit={(e) => {
                e.preventDefault()
                handleAddBatch()
              }}
              className="grid gap-4"
            >
              {renderForm()}
              <FormDialogFooter
                onCancel={() => setIsCreateDialogOpen(false)}
                confirmText={t('创建批次')}
                cancelText={t('取消')}
                confirmDisabled={!newBatchName || !newBatchWorkflow}
              />
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>{t('编辑批次')}</DialogTitle>
            <DialogDescription>{t('修改批次名称与关联审批流程。')}</DialogDescription>
          </DialogHeader>
          <form
            onSubmit={(e) => {
              e.preventDefault()
              handleUpdateBatch()
            }}
            className="grid gap-4"
          >
            {renderForm()}
            <FormDialogFooter
              onCancel={() => setIsEditDialogOpen(false)}
              confirmText={t('保存修改')}
              cancelText={t('取消')}
              confirmDisabled={!newBatchName || !newBatchWorkflow}
            />
          </form>
        </DialogContent>
      </Dialog>

      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
            <SearchInput
              wrapperClassName="flex-1"
              placeholder={t('搜索批次名称、编号...')}
              value={searchQuery}
              onChange={setSearchQuery}
            />
            <Select
              value={filterStatus}
              onValueChange={(v) => setFilterStatus(v as typeof filterStatus)}
            >
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{t('全部状态')}</SelectItem>
                <SelectItem value="open">{t('开放中')}</SelectItem>
                <SelectItem value="closed">{t('已截止')}</SelectItem>
              </SelectContent>
            </Select>
            {(searchQuery || filterStatus !== 'all') && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  setSearchQuery('')
                  setFilterStatus('all')
                }}
              >
                <RotateCcw className="mr-1 h-3.5 w-3.5" />
                {t('重置')}
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FolderKanban className="h-4 w-4" />
            {t('批次列表')}
          </CardTitle>
          <CardDescription>{t('共 {n} 个批次分组', { n: filteredBatches.length })}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-lg border border-slate-200 bg-white overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="bg-slate-50">
                  <TableHead className="text-xs font-medium text-slate-500">
                    {t('分组名称')}
                  </TableHead>
                  <TableHead className="text-xs font-medium text-slate-500">
                    {t('批次编号')}
                  </TableHead>
                  <TableHead className="text-xs font-medium text-slate-500">
                    {t('审批流程')}
                  </TableHead>
                  <TableHead className="text-xs font-medium text-slate-500">{t('状态')}</TableHead>
                  <TableHead className="w-12"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={5} className="text-center py-8 text-gray-500">
                      {t('加载中...')}
                    </TableCell>
                  </TableRow>
                ) : filteredBatches.length === 0 ? (
                  <TableEmptyRow colSpan={5} className="py-8 text-gray-500">
                    {t('暂无批次数据')}
                  </TableEmptyRow>
                ) : (
                  filteredBatches.map((batch) => (
                    <TableRow key={batch.id} className="group">
                      <TableCell className="font-medium">
                        {detailHref ? (
                          <Link
                            to={detailHref(batch.id)}
                            prefetch="none"
                            className="hover:text-primary"
                          >
                            {batch.name}
                          </Link>
                        ) : (
                          batch.name
                        )}
                      </TableCell>
                      <TableCell className="text-sm text-gray-600">{batch.code || '-'}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="text-xs">
                          {batch.workflowName || '-'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-sm text-gray-600">
                        <StatusBadge
                          status={batch.status}
                          label={batch.status === 'open' ? t('开放中') : t('已截止')}
                        />
                      </TableCell>
                      <TableRowActions>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() => openEdit(batch)}
                        >
                          <Pencil className="mr-1 h-3 w-3" />
                          {t('编辑')}
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() => handleToggleStatus(batch)}
                        >
                          <Power className="mr-1 h-3 w-3" />
                          {batch.status === 'open' ? t('截止批次') : t('重新开放')}
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                          onClick={() => handleDeleteBatch(batch.id)}
                        >
                          <Trash2 className="mr-1 h-3 w-3" />
                          {t('删除')}
                        </Button>
                      </TableRowActions>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
      <ConfirmDialog
        open={deleteTargetId !== null}
        onOpenChange={(open) => {
          if (!open) setDeleteTargetId(null)
        }}
        title={t('确认删除')}
        description={t('确定删除该批次吗？')}
        variant="destructive"
        onConfirm={confirmDeleteBatch}
      />
    </div>
  )
}
