// frontend/portal-vue/src/views/job/archive.vue
<template>
  <ArchiveListPage
    entity-label="岗位"
    page-title="岗位历史档案库"
    page-description="查看已归档的岗位记录，支持恢复为草稿继续编辑"
    sidebar-title="按专业归档"
    :sidebar-items="sidebarItems"
    :sidebar-selected-id="selectedMajor"
    :on-sidebar-select="setSelectedMajor"
    :items="filtered"
    :loading="loading"
    :on-restore="handleRestore"
    :on-delete="handleDelete"
    :on-batch-restore="handleBatchRestore"
    :on-batch-delete="handleBatchDelete"
    :detail-href="detailHref"
    search-placeholder="搜索岗位名称 / 简称 / 行业 / 专业"
    :search-value="search"
    :on-search-change="setSearch"
    :columns="columns"
  />
</template>

<script setup lang="ts">
import { computed, h, onMounted, ref, type VNode } from 'vue';
import { ElMessage } from 'element-plus';
import ArchiveListPage from '@/components/archive-list-page.vue';
import { fetchAllPages } from '@/components/common/content-list-page.types';
import { positionApi, batchApi } from '@/api/job';
import { industryApi, majorApi } from '@/api/system';
import type { CareerPosition, JobBatch } from '@/types/job';
import type { Industry, Major } from '@/types/system';

interface ArchiveColumn {
  label: string;
  prop?: string;
  width?: string | number;
  minWidth?: string | number;
  formatter?: (row: Record<string, any>) => string;
  cell?: (row: Record<string, any>) => VNode | string;
}

const positions = ref<CareerPosition[]>([]);
const batches = ref<JobBatch[]>([]);
const loading = ref(false);
const search = ref('');
const selectedMajor = ref<string | null>(null);

function setSearch(value: string) {
  search.value = value;
}

function setSelectedMajor(id: string | null) {
  selectedMajor.value = id;
}

const industryMap = ref<Record<string, string>>({});
const majorMap = ref<Record<string, string>>({});

async function loadDicts() {
  try {
    const [indRes, majRes] = await Promise.all([
      industryApi.list({ limit: 1000 }),
      majorApi.list({ limit: 1000 })
    ]);
    const im: Record<string, string> = {};
    (indRes.items as Industry[]).forEach((i) => {
      im[i.id] = i.name;
    });
    industryMap.value = im;
    const mm: Record<string, string> = {};
    (majRes.items as Major[]).forEach((m) => {
      mm[m.id] = m.name;
    });
    majorMap.value = mm;
  } catch {
    // 字典加载失败不阻塞列表
  }
}

async function load() {
  loading.value = true;
  try {
    const [posArr, batchArr] = await Promise.all([
      fetchAllPages((page, pageSize) =>
        positionApi.list({ status: 'archived', limit: pageSize, offset: page * pageSize })
      ),
      fetchAllPages((page, pageSize) =>
        batchApi.list({ limit: pageSize, offset: page * pageSize })
      )
    ]);
    positions.value = posArr as CareerPosition[];
    batches.value = batchArr as JobBatch[];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

// ─── 字典 / 筛选 ────────────────────────────────────────────────────────────
function industryNameOf(p: CareerPosition): string {
  return p.industryId ? industryMap.value[p.industryId] || '-' : '-';
}

function majorNamesOf(p: CareerPosition): string {
  const ids = p.majorIds || [];
  if (ids.length === 0) return '-';
  return ids.map((id) => majorMap.value[id] || id).join('，');
}

function batchNameOf(p: CareerPosition): string {
  if (!p.batchId) return '-';
  const b = batches.value.find((x) => x.id === p.batchId);
  return b?.name || '-';
}

const sidebarItems = computed(() => {
  const set = new Set<string>();
  positions.value.forEach((p) => {
    (p.majorIds || []).forEach((id) => {
      const name = majorMap.value[id];
      if (name) set.add(name);
    });
  });
  return Array.from(set)
    .sort()
    .map((name) => ({ id: name, name }));
});

const filtered = computed(() => {
  let result = positions.value;
  if (selectedMajor.value) {
    result = result.filter((p) =>
      (p.majorIds || []).some((id) => majorMap.value[id] === selectedMajor.value)
    );
  }
  const q = search.value.trim().toLowerCase();
  if (q) {
    result = result.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        (p.shortName || '').toLowerCase().includes(q) ||
        industryNameOf(p).toLowerCase().includes(q) ||
        (p.majorIds || []).some((id) => (majorMap.value[id] || '').toLowerCase().includes(q))
    );
  }
  return result;
});

function formatDate(v?: string): string {
  if (!v) return '-';
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return '-';
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

const columns = computed<ArchiveColumn[]>(() => [
  {
    label: '岗位名称',
    minWidth: 200,
    cell: (row) =>
      h('div', { class: 'arc-name' }, [
        h('span', { class: 'arc-name-title' }, String(row.name || '')),
        h(
          'p',
          { class: 'arc-name-sub' },
          `${industryNameOf(row as CareerPosition)} · ${majorNamesOf(row as CareerPosition)}`
        )
      ])
  },
  { label: '简称', width: 120, formatter: (row) => row.shortName || '-' },
  { label: '版本', width: 90, formatter: (row) => row.version || '-' },
  { label: '所属行业', width: 130, formatter: (row) => industryNameOf(row as CareerPosition) },
  { label: '适用专业', width: 160, formatter: (row) => majorNamesOf(row as CareerPosition) },
  { label: '所属批次分组', width: 140, formatter: (row) => batchNameOf(row as CareerPosition) },
  { label: '归档时间', width: 140, formatter: (row) => formatDate((row as CareerPosition).updatedAt) }
]);

// ─── 操作 ────────────────────────────────────────────────────────────────────
function detailHref(item: Record<string, any>): string {
  return `/job/positions/${item.id}/edit`;
}

async function handleRestore(row: Record<string, any>) {
  try {
    await positionApi.saveDraft(row.id);
    ElMessage.success('已恢复');
  } catch (e) {
    ElMessage.error((e as Error).message || '恢复失败');
    throw e;
  } finally {
    await load();
  }
}

async function handleDelete(row: Record<string, any>) {
  try {
    await positionApi.delete(row.id);
    ElMessage.success('已删除');
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
    throw e;
  } finally {
    await load();
  }
}

async function handleBatchRestore(ids: string[]) {
  const results = await Promise.allSettled(ids.map((id) => positionApi.saveDraft(id)));
  const failed = results.filter((r) => r.status === 'rejected').length;
  await load();
  if (failed === 0) {
    ElMessage.success(`已批量恢复 ${ids.length} 个岗位`);
  } else {
    ElMessage.error(`批量恢复部分失败：成功 ${ids.length - failed} 个，失败 ${failed} 个`);
  }
}

async function handleBatchDelete(ids: string[]) {
  const results = await Promise.allSettled(ids.map((id) => positionApi.delete(id)));
  const failed = results.filter((r) => r.status === 'rejected').length;
  await load();
  if (failed === 0) {
    ElMessage.success(`已批量删除 ${ids.length} 个岗位`);
  } else {
    ElMessage.error(`批量删除部分失败：成功 ${ids.length - failed} 个，失败 ${failed} 个`);
  }
}

onMounted(() => {
  loadDicts();
  load();
});
</script>

<style scoped>
.arc-name {
  max-width: 200px;
}
.arc-name-title {
  font-weight: 500;
  color: #303133;
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.arc-name-sub {
  margin: 2px 0 0;
  font-size: 12px;
  color: #909399;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// apps/edu/app/job/archive/page.tsx
'use client'

import { useMemo, useState } from 'react'

import { positionApi, batchApi } from '@/lib/api'
import { fetchAllPages } from '@zhiyu/api-client'
import type { Position } from '@/lib/types/job-source'
import {
  convertCareerPositionToPosition,
  convertJobBatchToBatch,
} from '@/lib/converters/job-converters'
import { useToast, useAsync } from '@zhiyu/ui'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { useIndustryMap, useMajorMap } from '@/lib/use-resource-maps'
import { formatDate } from '@/lib/format-utils'
import { ArchiveListPage, type ArchiveColumn } from '@/components/shared/archive-list-page'
import { useT } from '@/lib/i18n/locale-provider'

export default function PositionArchivePage() {
  const t = useT()
  const { toast } = useToast()
  const [search, setSearch] = useState('')
  const [selectedMajor, setSelectedMajor] = useState<string | null>(null)
  const [batchDeleteTarget, setBatchDeleteTarget] = useState<string[] | null>(null)
  const industryMap = useIndustryMap()
  const majorMap = useMajorMap()

  const { data, loading, refresh } = useAsync(async () => {
    const [posRes, batchRes] = await Promise.all([
      fetchAllPages((page, pageSize) => positionApi.list({ status: 'archived', limit: pageSize, offset: page * pageSize })),
      fetchAllPages((page, pageSize) => batchApi.list({ limit: pageSize, offset: page * pageSize })),
    ])
    return {
      positions: posRes.map(convertCareerPositionToPosition),
      batches: batchRes.map(convertJobBatchToBatch),
    }
  })

  const { positions, batches } = data ?? {}

  const majors = useMemo(() => {
    const set = new Set<string>()
    ;(positions ?? []).forEach((p) => {
      p.majors.forEach((id) => {
        const name = majorMap.get(id)
        if (name) set.add(name)
      })
    })
    return Array.from(set).sort()
  }, [positions, majorMap])

  const filtered = useMemo(() => {
    let result = positions ?? []
    if (selectedMajor) {
      result = result.filter((p) => p.majors.some((id) => majorMap.get(id) === selectedMajor))
    }
    if (search.trim()) {
      const q = search.toLowerCase()
      result = result.filter(
        (p) =>
          p.name.toLowerCase().includes(q) ||
          p.shortName.toLowerCase().includes(q) ||
          (industryMap.get(p.industry) || '').toLowerCase().includes(q) ||
          p.majors.some((id) => (majorMap.get(id) || '').toLowerCase().includes(q)),
      )
    }
    return result
  }, [positions, selectedMajor, search, industryMap, majorMap])

  const batchMap = useMemo(() => new Map((batches ?? []).map((b) => [b.id, b])), [batches])

  const getMajorNames = (ids: string[]) => {
    if (ids.length === 0) return '-'
    return ids.map((id) => majorMap.get(id) || id).join('，')
  }

  const handleRestore = async (position: Position) => {
    try {
      await positionApi.saveDraft(position.id)
      await refresh()
      toast({ title: t('已恢复') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('恢复失败'),
        description: err.message || t('请稍后重试'),
      })
    }
  }

  const handleDelete = async (position: Position) => {
    try {
      await positionApi.delete(position.id)
      await refresh()
      toast({ title: t('已删除') })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('删除失败'),
        description: err.message || t('请稍后重试'),
      })
    }
  }

  const handleBatchRestore = async (ids: string[]) => {
    const results = await Promise.allSettled(ids.map((id) => positionApi.saveDraft(id)))
    const failed = results.filter((r) => r.status === 'rejected').length
    await refresh()
    if (failed === 0) {
      toast({ title: t('已批量恢复 {n} 个岗位', { n: ids.length }) })
    } else {
      toast({
        variant: 'destructive',
        title: t('批量恢复部分失败'),
        description: t('成功 {ok} 个，失败 {fail} 个', { ok: ids.length - failed, fail: failed }),
      })
    }
  }

  const handleBatchDelete = async (ids: string[]) => {
    setBatchDeleteTarget(ids)
  }

  const confirmBatchDelete = async () => {
    if (!batchDeleteTarget || batchDeleteTarget.length === 0) return
    try {
      await Promise.all(batchDeleteTarget.map((id) => positionApi.delete(id)))
      await refresh()
      toast({ title: t('已批量删除 {n} 个岗位', { n: batchDeleteTarget.length }) })
    } catch (err: any) {
      toast({
        variant: 'destructive',
        title: t('批量删除失败'),
        description: err.message || t('请稍后重试'),
      })
    } finally {
      setBatchDeleteTarget(null)
    }
  }

  const columns: ArchiveColumn<Position>[] = [
    {
      header: t('岗位名称'),
      className: 'w-44',
      cell: (entry) => (
        <div className="max-w-44">
          <span className="font-medium line-clamp-1">{entry.name}</span>
          <p className="text-xs text-muted-foreground line-clamp-1">
            {industryMap.get(entry.industry) || '-'} · {getMajorNames(entry.majors)}
          </p>
        </div>
      ),
    },
    {
      header: t('简称'),
      className: 'w-24',
      cell: (entry) => (
        <span className="text-sm text-muted-foreground max-w-24 truncate">
          {entry.shortName || '-'}
        </span>
      ),
    },
    {
      header: t('版本'),
      className: 'w-20',
      cell: (entry) => <span className="text-sm">{entry.version}</span>,
    },
    {
      header: t('所属行业'),
      className: 'w-24',
      cell: (entry) => (
        <span className="text-sm max-w-24 truncate">{industryMap.get(entry.industry) || '-'}</span>
      ),
    },
    {
      header: t('适用专业'),
      className: 'w-32',
      cell: (entry) => (
        <span className="text-sm max-w-32 truncate">{getMajorNames(entry.majors)}</span>
      ),
    },
    {
      header: t('所属批次分组'),
      className: 'w-28',
      cell: (entry) => (
        <span className="text-sm max-w-28 truncate">
          {entry.batchId ? batchMap.get(entry.batchId)?.name || '-' : '-'}
        </span>
      ),
    },
    {
      header: t('归档时间'),
      className: 'w-24',
      cell: (entry) => (
        <span className="text-sm text-muted-foreground whitespace-nowrap">
          {formatDate(entry.updatedAt)}
        </span>
      ),
    },
  ]

  return (
    <>
      <ArchiveListPage
        entityLabel={t('岗位')}
        pageTitle={t('岗位历史档案库')}
        pageDescription={t('查看已归档的岗位记录，支持恢复为草稿继续编辑')}
        sidebarTitle={t('按专业归档')}
        sidebarItems={majors.map((m) => ({ id: m, name: m }))}
        sidebarSelectedId={selectedMajor}
        onSidebarSelect={setSelectedMajor}
        items={filtered}
        loading={loading}
        onRestore={handleRestore}
        onDelete={handleDelete}
        onBatchRestore={handleBatchRestore}
        onBatchDelete={handleBatchDelete}
        detailHref={(item) => `/job/positions/${item.id}/edit`}
        searchPlaceholder={t('搜索岗位名称 / 简称 / 行业 / 专业')}
        searchValue={search}
        onSearchChange={setSearch}
        columns={columns}
      />
      <ConfirmDialog
        open={batchDeleteTarget !== null}
        onOpenChange={(open) => {
          if (!open) setBatchDeleteTarget(null)
        }}
        title={t('确认批量删除')}
        description={t('确定删除选中的 {n} 个岗位吗？删除后不可恢复。', {
          n: batchDeleteTarget?.length || 0,
        })}
        variant="destructive"
        onConfirm={confirmBatchDelete}
      />
    </>
  )
}
