// plus-ui/src-portal/views/partner/login.vue
<template>
  <div class="partner-login-page">
    <div class="login-panel">
      <div class="brand-area">
        <h1 class="brand-title">企业服务台</h1>
      </div>

      <el-card shadow="never" class="login-card">
        <div class="tab-switch">
          <button
            type="button"
            class="tab-btn"
            :class="{ active: tab === 'login' }"
            @click="switchTab('login')"
          >
            账号登录
          </button>
          <button
            type="button"
            class="tab-btn"
            :class="{ active: tab === 'register' }"
            @click="switchTab('register')"
          >
            企业注册
          </button>
        </div>

        <el-alert v-if="error" :title="error" type="error" :closable="false" class="error-alert" show-icon />

        <el-form v-if="tab === 'login'" label-position="top" @submit.prevent="handleLogin">
          <el-form-item label="账号">
            <el-input v-model="username" placeholder="请输入账号" autocomplete="username" />
          </el-form-item>
          <el-form-item label="密码">
            <el-input
              v-model="password"
              type="password"
              placeholder="请输入密码"
              autocomplete="current-password"
              show-password
              @keyup.enter="handleLogin"
            />
          </el-form-item>

          <el-form-item v-if="captchaRequired" label="验证码">
            <div class="captcha-row">
              <el-input
                v-model="captchaCode"
                placeholder="请输入验证码"
                maxlength="6"
                autocomplete="off"
                @keyup.enter="handleLogin"
              />
              <img
                v-if="captcha?.image"
                :src="captcha.image"
                alt="验证码"
                class="captcha-img"
                title="点击刷新验证码"
                @click="loadCaptcha"
              />
              <div v-else class="captcha-loading">验证码加载中...</div>
            </div>
            <div class="captcha-tip">点击图片可刷新验证码</div>
          </el-form-item>

          <el-form-item>
            <el-button type="primary" size="large" class="submit-btn" :loading="loading" @click="handleLogin">
              {{ loading ? '登录中...' : '登 录' }}
            </el-button>
          </el-form-item>
          <p class="form-footnote">忘记密码？请联系平台管理员重置。</p>
        </el-form>

        <el-form v-else label-position="top" @submit.prevent="handleRegister">
          <el-form-item label="企业名称">
            <el-input v-model="reg.enterpriseName" placeholder="请输入企业全称" />
          </el-form-item>
          <el-form-item label="统一社会信用代码">
            <el-input v-model="reg.unifiedSocialCreditCode" placeholder="如：91320594MA1P7XXXX1" />
          </el-form-item>
          <el-row :gutter="12">
            <el-col :span="12">
              <el-form-item label="联系人">
                <el-input v-model="reg.contactPerson" placeholder="请输入联系人姓名" />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="手机号">
                <el-input v-model="reg.contactPhone" placeholder="请输入手机号" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-form-item label="联系邮箱（选填）">
            <el-input v-model="reg.contactEmail" type="email" placeholder="请输入联系邮箱" />
          </el-form-item>
          <el-form-item label="用户名">
            <el-input
              v-model="reg.username"
              placeholder="设置登录用户名（同一账号可加入多个企业）"
              autocomplete="username"
            />
          </el-form-item>
          <el-row :gutter="12">
            <el-col :span="12">
              <el-form-item label="密码">
                <el-input
                  v-model="reg.password"
                  type="password"
                  placeholder="设置登录密码"
                  autocomplete="new-password"
                  show-password
                />
              </el-form-item>
            </el-col>
            <el-col :span="12">
              <el-form-item label="确认密码">
                <el-input
                  v-model="reg.confirmPassword"
                  type="password"
                  placeholder="再次输入密码"
                  autocomplete="new-password"
                  show-password
                />
              </el-form-item>
            </el-col>
          </el-row>

          <el-form-item>
            <el-button type="primary" size="large" class="submit-btn" :loading="loading" @click="handleRegister">
              {{ loading ? '注册中...' : '注册并登录' }}
            </el-button>
          </el-form-item>
          <p class="form-footnote">注册即创建企业管理员账号，无需审核，立即可用；同一用户名可加入多个企业</p>
        </el-form>
      </el-card>

      <p class="copyright">
        版权所有 © 2020-2026 杭州知与未来科技有限公司 ｜ 软件著作权登记号：2020SR0123456 ｜ 京ICP备2025105397号-1
      </p>
    </div>

    <el-dialog v-model="showTenantSelect" title="选择企业" width="420px" :close-on-click-modal="false">
      <p class="tenant-tip">您的账号关联了多个企业，请选择要登录的企业</p>
      <div class="tenant-list">
        <button
          v-for="opt in tenantOptions"
          :key="opt.tenantId"
          type="button"
          class="tenant-item"
          :disabled="selectingTenant"
          @click="handleSelectTenant(opt.tenantId)"
        >
          {{ opt.tenantName }}
        </button>
      </div>
      <el-alert v-if="error" :title="error" type="error" :closable="false" class="error-alert" show-icon />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { setToken, partnerRequest } from '@/api/http';
import { authApi } from '@/api/auth';
import type { CaptchaData, LoginResponse, TenantOption } from '@/api/auth';
import { getDeviceId } from '@/utils/device';

interface RegisterPayload {
  enterpriseName: string;
  unifiedSocialCreditCode: string;
  contactPerson: string;
  contactPhone: string;
  contactEmail?: string;
  username: string;
  password: string;
}

const router = useRouter();

const tab = ref<'login' | 'register'>('login');
const error = ref('');
const loading = ref(false);

const username = ref('');
const password = ref('');

// 多企业候选登录：账号关联多个企业时弹窗选择
const tenantOptions = ref<TenantOption[]>([]);
let preAuthToken = '';
const showTenantSelect = ref(false);
const selectingTenant = ref(false);

const reg = reactive({
  enterpriseName: '',
  unifiedSocialCreditCode: '',
  contactPerson: '',
  contactPhone: '',
  contactEmail: '',
  username: '',
  password: '',
  confirmPassword: ''
});

// 防爆破验证码：后端返回 captcha_required 后展示，输入完成后随登录请求提交
const captchaRequired = ref(false);
const captcha = ref<CaptchaData | null>(null);
const captchaCode = ref('');

async function loadCaptcha() {
  try {
    captcha.value = await authApi.captcha();
  } catch (e) {
    captcha.value = null;
    error.value = (e as Error).message || '验证码加载失败';
  }
  captchaCode.value = '';
}

function switchTab(next: 'login' | 'register') {
  tab.value = next;
  error.value = '';
}

async function doLogin(token: string) {
  setToken(token, 'partner');
  await router.replace('/partner/workspace');
}

async function handleSelectTenant(tenantId: string) {
  selectingTenant.value = true;
  try {
    const res = await partnerRequest<LoginResponse>('/auth/select-tenant', {
      method: 'POST',
      body: JSON.stringify({ preAuthToken, tenantId })
    });
    await doLogin(res.token);
  } catch (e) {
    error.value = (e as Error).message || '选择企业失败';
    showTenantSelect.value = false;
  } finally {
    selectingTenant.value = false;
  }
}

async function handleLogin() {
  error.value = '';
  if (!username.value || !password.value) {
    error.value = '请输入账号和密码';
    return;
  }
  if (captchaRequired.value && !captchaCode.value.trim()) {
    error.value = '请先输入验证码';
    return;
  }
  loading.value = true;
  try {
    const res = await partnerRequest<LoginResponse>('/auth/partner/login', {
      method: 'POST',
      body: JSON.stringify({
        username: username.value,
        password: password.value,
        deviceId: getDeviceId(),
        ...(captchaRequired.value && captcha.value && captchaCode.value.trim()
          ? { captchaId: captcha.value.captchaId, captchaCode: captchaCode.value.trim() }
          : {})
      })
    });
    if (res.needsTenantSelection && res.preAuthToken && res.tenants) {
      tenantOptions.value = res.tenants;
      preAuthToken = res.preAuthToken;
      showTenantSelect.value = true;
      loading.value = false;
      return;
    }
    await doLogin(res.token);
  } catch (e) {
    // http.ts 只透传 error 文案、丢弃 code，故按后端稳定文案区分验证码错误
    const msg = (e as Error).message || '';
    if (msg === '请完成验证码') {
      captchaRequired.value = true;
      await loadCaptcha();
      error.value = '请先输入验证码后再登录';
    } else if (msg === '验证码不正确，请重试') {
      await loadCaptcha();
      error.value = '验证码不正确，请重试';
    } else {
      error.value = msg || '登录失败';
    }
    loading.value = false;
  }
}

async function handleRegister() {
  error.value = '';
  if (reg.password !== reg.confirmPassword) {
    error.value = '两次输入的密码不一致';
    return;
  }
  const required: Array<[string, string]> = [
    ['企业名称', reg.enterpriseName],
    ['统一社会信用代码', reg.unifiedSocialCreditCode],
    ['联系人', reg.contactPerson],
    ['手机号', reg.contactPhone],
    ['用户名', reg.username],
    ['密码', reg.password]
  ];
  for (const [label, value] of required) {
    if (!value.trim()) {
      error.value = `请填写${label}`;
      return;
    }
  }
  loading.value = true;
  try {
    const payload: RegisterPayload = {
      enterpriseName: reg.enterpriseName.trim(),
      unifiedSocialCreditCode: reg.unifiedSocialCreditCode.trim(),
      contactPerson: reg.contactPerson.trim(),
      contactPhone: reg.contactPhone.trim(),
      contactEmail: reg.contactEmail.trim() || undefined,
      username: reg.username.trim(),
      password: reg.password
    };
    const res = await partnerRequest<LoginResponse>('/auth/partner/register', {
      method: 'POST',
      body: JSON.stringify(payload)
    });
    await doLogin(res.token);
  } catch (e) {
    error.value = (e as Error).message || '注册失败';
    loading.value = false;
  }
}
</script>

<style scoped>
.partner-login-page {
  min-height: 100vh;
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding: 40px 16px 48px;
  background: linear-gradient(135deg, #f6f9ff 0%, #f7f9fc 50%, #eef3fb 100%);
}
.login-panel {
  width: 100%;
  max-width: 440px;
}
.brand-area {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  margin-bottom: 28px;
}
.brand-logo {
  height: 64px;
  width: auto;
  object-fit: contain;
}
.brand-title {
  margin: 0;
  font-size: 24px;
  font-weight: 700;
  letter-spacing: 0.5px;
  background: linear-gradient(90deg, #409eff, #66b1ff);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
.login-card {
  border-radius: 14px;
  border: 1px solid #e8ecf3;
  padding: 8px;
}
.tab-switch {
  display: grid;
  grid-template-columns: 1fr 1fr;
  background: #f1f2f5;
  border-radius: 8px;
  padding: 4px;
  margin-bottom: 20px;
}
.tab-btn {
  border: none;
  background: transparent;
  padding: 8px 0;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  color: #909399;
  cursor: pointer;
  transition: all 0.2s;
}
.tab-btn.active {
  background: #fff;
  color: #409eff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
}
.error-alert {
  margin-bottom: 14px;
}
.submit-btn {
  width: 100%;
}
.captcha-row {
  display: flex;
  gap: 8px;
  width: 100%;
  align-items: center;
}
.captcha-img {
  height: 40px;
  width: 110px;
  cursor: pointer;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  flex-shrink: 0;
  object-fit: cover;
}
.captcha-loading {
  height: 40px;
  width: 110px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  font-size: 12px;
  color: #c0c4cc;
}
.captcha-tip {
  margin-top: 4px;
  font-size: 12px;
  color: #c0c4cc;
  line-height: 1.4;
}
.form-footnote {
  margin: 8px 0 0;
  text-align: center;
  font-size: 12px;
  color: #c0c4cc;
  line-height: 1.6;
}
.copyright {
  margin-top: 24px;
  padding: 0 16px;
  text-align: center;
  font-size: 12px;
  line-height: 1.6;
  color: #c0c4cc;
}
.tenant-tip {
  color: #606266;
  margin: 0 0 12px;
  line-height: 1.6;
}
.tenant-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.tenant-item {
  padding: 12px 14px;
  border: 1px solid #e4e7ed;
  border-radius: 6px;
  cursor: pointer;
  text-align: center;
  background: #fff;
  font-size: 14px;
  color: #303133;
  transition: all 0.2s;
}
.tenant-item:hover:not(:disabled) {
  border-color: #409eff;
  color: #409eff;
}
.tenant-item:disabled {
  cursor: not-allowed;
  opacity: 0.6;
}
</style>

// frontend/edu/app/partner/login/page.tsx
'use client'

import { useState } from 'react'
import { useNavigate } from 'react-router'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { PasswordInput } from '@zhiyu/ui'
import { Label } from '@/components/ui/label'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { AlertCircle, User, Lock, Building2, Phone, Mail, IdCard } from 'lucide-react'
import { partnerAuthApi, setToken, getDeviceId } from '@/lib/api'
import type { TenantOption } from '@/lib/api'
import { usePartnerAuth } from '@/components/partner-auth-provider'
import { useT } from '@/lib/i18n/locale-provider'
import CaptchaInput from '@/components/shared/captcha-input'

export default function PartnerLoginPage() {
  const t = useT()
  const navigate = useNavigate()
  const { refresh } = usePartnerAuth()
  const [tab, setTab] = useState<'login' | 'register'>('login')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')

  // 多企业候选登录：账号关联多个企业时弹窗选择
  const [tenantOptions, setTenantOptions] = useState<TenantOption[]>([])
  const [preAuthToken, setPreAuthToken] = useState('')
  const [showTenantSelect, setShowTenantSelect] = useState(false)
  const [selectingTenant, setSelectingTenant] = useState(false)

  const [reg, setReg] = useState({
    enterpriseName: '',
    unifiedSocialCreditCode: '',
    contactPerson: '',
    contactPhone: '',
    contactEmail: '',
    username: '',
    password: '',
    confirmPassword: '',
  })

  // 防爆破验证码：后端返回 captcha_required 后展示，输入完成后随登录请求提交
  const [captchaRequired, setCaptchaRequired] = useState(false)
  const [captchaAnswer, setCaptchaAnswer] = useState<{ id: string; code: string } | null>(null)
  const [captchaVersion, setCaptchaVersion] = useState(0)

  const handleCaptchaPass = (captchaId: string, code: string) => {
    setCaptchaAnswer({ id: captchaId, code })
  }

  const refreshCaptcha = () => {
    setCaptchaVersion((v) => v + 1)
    setCaptchaAnswer(null)
  }

  const doLogin = async (token: string) => {
    setToken(token, 'partner')
    await refresh()
    navigate('/partner/workspace', { replace: true })
  }

  const handleSelectTenant = async (tenantId: string) => {
    setSelectingTenant(true)
    try {
      const res = await partnerAuthApi.selectTenant({ preAuthToken, tenantId })
      await doLogin(res.token)
    } catch (err: any) {
      setError(err.message || t('选择企业失败'))
      setShowTenantSelect(false)
    } finally {
      setSelectingTenant(false)
    }
  }

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')

    if (captchaRequired && !captchaAnswer) {
      setError(t('请先输入验证码'))
      return
    }

    setLoading(true)
    try {
      const res = await partnerAuthApi.login({
        username,
        password,
        deviceId: getDeviceId(),
        ...(captchaAnswer
          ? { captchaId: captchaAnswer.id, captchaCode: captchaAnswer.code }
          : {}),
      })
      if (res.needsTenantSelection && res.preAuthToken && res.tenants) {
        setTenantOptions(res.tenants)
        setPreAuthToken(res.preAuthToken)
        setShowTenantSelect(true)
        setLoading(false)
        return
      }
      await doLogin(res.token)
    } catch (err: any) {
      if (err?.code === 'captcha_required') {
        // 验证码已消费/过期：刷新验证码并清空已填字符（否则旧 id 永远校验失败）
        refreshCaptcha()
        setCaptchaRequired(true)
        setError(t('请先输入验证码后再登录'))
      } else if (err?.code === 'captcha_wrong') {
        refreshCaptcha()
        setError(t('验证码不正确，请重试'))
      } else {
        setError(err.message || t('登录失败'))
      }
      setLoading(false)
    }
  }

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    if (reg.password !== reg.confirmPassword) {
      setError(t('两次输入的密码不一致'))
      return
    }
    setLoading(true)
    try {
      const res = await partnerAuthApi.register({
        enterpriseName: reg.enterpriseName,
        unifiedSocialCreditCode: reg.unifiedSocialCreditCode,
        contactPerson: reg.contactPerson,
        contactPhone: reg.contactPhone,
        contactEmail: reg.contactEmail || undefined,
        username: reg.username,
        password: reg.password,
      })
      await doLogin(res.token)
    } catch (err: any) {
      setError(err.message || t('注册失败'))
      setLoading(false)
    }
  }

  const setRegField = (field: string, value: string) => setReg({ ...reg, [field]: value })

  const errorView = error && (
    <div className="flex items-center gap-2 rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">
      <AlertCircle className="h-4 w-4 shrink-0" />
      <span>{error}</span>
    </div>
  )

  return (
    <div className="relative flex min-h-screen items-start justify-center overflow-hidden bg-gradient-to-br from-[#f6f9ff] via-[#f7f9fc] to-[#eef3fb] p-4 pt-12 sm:pt-16">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -left-40 -top-40 h-[560px] w-[560px] rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute -bottom-40 -right-40 h-[560px] w-[560px] rounded-full bg-primary/10 blur-3xl" />
        <div className="absolute left-1/3 top-1/2 h-64 w-64 rounded-full bg-primary/5 blur-3xl" />
        <div className="absolute left-1/4 top-1/4 h-32 w-32 rounded-full bg-cyan-500/10 blur-2xl" />
      </div>

      <div className="relative w-full max-w-md">
        <div className="relative mb-8 flex flex-col items-center gap-4">
          <img
            src="/logo.png?v=2"
            alt="知育"
            width={369}
            height={139}
            className="h-16 w-auto object-contain drop-shadow-sm"
          />
          <div className="flex flex-col items-center gap-1.5">
            <h1 className="bg-gradient-to-r from-primary via-primary to-primary/60 bg-clip-text text-2xl sm:text-[26px] font-bold tracking-wide text-transparent">
              {t('企业服务台')}
            </h1>
          </div>
        </div>

        <Card className="relative overflow-hidden rounded-2xl border border-[#e8ecf3] bg-white/95 shadow-[0_24px_70px_-28px] shadow-primary/25 backdrop-blur-xl">
          <div className="absolute left-0 right-0 top-0 h-1 bg-gradient-to-r from-primary via-primary/70 to-primary/30" />
          <CardContent className="px-6 py-8 sm:px-9 sm:py-9">
            <div className="mb-7 grid grid-cols-2 rounded-lg bg-slate-100 p-1 text-sm">
              <button
                type="button"
                onClick={() => {
                  setTab('login')
                  setError('')
                }}
                className={`rounded-md py-2 font-medium transition-all ${
                  tab === 'login' ? 'bg-white text-primary shadow-sm' : 'text-slate-500'
                }`}
              >
                {t('账号登录')}
              </button>
              <button
                type="button"
                onClick={() => {
                  setTab('register')
                  setError('')
                }}
                className={`rounded-md py-2 font-medium transition-all ${
                  tab === 'register' ? 'bg-white text-primary shadow-sm' : 'text-slate-500'
                }`}
              >
                {t('企业注册')}
              </button>
            </div>

            {tab === 'login' ? (
              <form onSubmit={handleLogin} className="space-y-5">
                <div className="space-y-1.5">
                  <Label htmlFor="username" className="text-sm font-medium text-slate-600">
                    {t('账号')}
                  </Label>
                  <div className="relative">
                    <User className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <Input
                      id="username"
                      placeholder={t('请输入账号')}
                      className="h-11 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm transition-all placeholder:text-slate-400 hover:border-slate-300 focus-visible:border-primary/60 focus-visible:bg-white focus-visible:ring-primary/20"
                      value={username}
                      onChange={(e) => setUsername(e.target.value)}
                      autoComplete="username"
                      required
                    />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="password" className="text-sm font-medium text-slate-600">
                    {t('密码')}
                  </Label>
                  <div className="relative">
                    <Lock className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <PasswordInput
                      id="password"
                      placeholder={t('请输入密码')}
                      className="h-11 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm transition-all placeholder:text-slate-400 hover:border-slate-300 focus-visible:border-primary/60 focus-visible:bg-white focus-visible:ring-primary/20"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      autoComplete="current-password"
                      required
                    />
                  </div>
                </div>

                {captchaRequired && (
                  <CaptchaInput
                    key={captchaVersion}
                    onPass={handleCaptchaPass}
                    onError={() => setCaptchaRequired(true)}
                  />
                )}

                {errorView}

                <Button
                  type="submit"
                  className="h-11 w-full rounded-lg bg-gradient-to-r from-primary via-primary to-primary/80 text-base shadow-lg shadow-primary/30 transition-all hover:-translate-y-px hover:shadow-xl hover:shadow-primary/30 active:translate-y-0 disabled:translate-y-0"
                  disabled={loading}
                  size="lg"
                >
                  {loading ? t('登录中...') : t('登 录')}
                </Button>
                <p className="text-center text-xs text-slate-400">
                  {t('忘记密码？请联系平台管理员重置。')}
                </p>
              </form>
            ) : (
              <form onSubmit={handleRegister} className="space-y-4">
                <div className="space-y-1.5">
                  <Label className="text-sm font-medium text-slate-600">{t('企业名称')}</Label>
                  <div className="relative">
                    <Building2 className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <Input
                      placeholder={t('请输入企业全称')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm"
                      value={reg.enterpriseName}
                      onChange={(e) => setRegField('enterpriseName', e.target.value)}
                      required
                    />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-sm font-medium text-slate-600">
                    {t('统一社会信用代码')}
                  </Label>
                  <div className="relative">
                    <IdCard className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <Input
                      placeholder={t('如：91320594MA1P7XXXX1')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm"
                      value={reg.unifiedSocialCreditCode}
                      onChange={(e) => setRegField('unifiedSocialCreditCode', e.target.value)}
                      required
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <Label className="text-sm font-medium text-slate-600">{t('联系人')}</Label>
                    <Input
                      placeholder={t('请输入联系人姓名')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 text-sm"
                      value={reg.contactPerson}
                      onChange={(e) => setRegField('contactPerson', e.target.value)}
                      required
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-sm font-medium text-slate-600">{t('手机号')}</Label>
                    <div className="relative">
                      <Phone className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                      <Input
                        placeholder={t('请输入手机号')}
                        className="h-10 rounded-lg border-slate-200 bg-slate-50/80 pl-9 text-sm"
                        value={reg.contactPhone}
                        onChange={(e) => setRegField('contactPhone', e.target.value)}
                        required
                      />
                    </div>
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-sm font-medium text-slate-600">
                    {t('联系邮箱（选填）')}
                  </Label>
                  <div className="relative">
                    <Mail className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <Input
                      type="email"
                      placeholder={t('请输入联系邮箱')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm"
                      value={reg.contactEmail}
                      onChange={(e) => setRegField('contactEmail', e.target.value)}
                    />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-sm font-medium text-slate-600">{t('用户名')}</Label>
                  <div className="relative">
                    <User className="absolute left-3.5 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-slate-400" />
                    <Input
                      placeholder={t('设置登录用户名（同一账号可加入多个企业）')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 pl-10 text-sm"
                      value={reg.username}
                      onChange={(e) => setRegField('username', e.target.value)}
                      autoComplete="username"
                      required
                    />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <Label className="text-sm font-medium text-slate-600">{t('密码')}</Label>
                    <PasswordInput
                      placeholder={t('设置登录密码')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 text-sm"
                      value={reg.password}
                      onChange={(e) => setRegField('password', e.target.value)}
                      autoComplete="new-password"
                      required
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-sm font-medium text-slate-600">{t('确认密码')}</Label>
                    <PasswordInput
                      placeholder={t('再次输入密码')}
                      className="h-10 rounded-lg border-slate-200 bg-slate-50/80 text-sm"
                      value={reg.confirmPassword}
                      onChange={(e) => setRegField('confirmPassword', e.target.value)}
                      autoComplete="new-password"
                      required
                    />
                  </div>
                </div>

                {errorView}

                <Button
                  type="submit"
                  className="h-11 w-full rounded-lg bg-gradient-to-r from-primary via-primary to-primary/80 text-base shadow-lg shadow-primary/30 transition-all hover:-translate-y-px hover:shadow-xl hover:shadow-primary/30 active:translate-y-0 disabled:translate-y-0"
                  disabled={loading}
                  size="lg"
                >
                  {loading ? t('注册中...') : t('注册并登录')}
                </Button>
                <p className="text-center text-xs text-slate-400">
                  {t('注册即创建企业管理员账号，无需审核，立即可用；同一用户名可加入多个企业')}
                </p>
              </form>
            )}
          </CardContent>
        </Card>

        <p className="mt-7 px-6 text-center text-xs leading-relaxed text-slate-400">
          {t(
            '版权所有 © 2020-2026 杭州知与未来科技有限公司 ｜ 软件著作权登记号：2020SR0123456 ｜ 京ICP备2025105397号-1',
          )}
        </p>
      </div>

      {/* 多企业候选登录：选择要登录的企业 */}
      <Dialog open={showTenantSelect} onOpenChange={setShowTenantSelect}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{t('选择企业')}</DialogTitle>
            <DialogDescription>{t('您的账号关联了多个企业，请选择要登录的企业')}</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-2 py-4">
            {tenantOptions.map((opt) => (
              <Button
                key={opt.tenantId}
                variant="outline"
                className="justify-start gap-3 h-auto py-4"
                onClick={() => handleSelectTenant(opt.tenantId)}
                disabled={selectingTenant}
              >
                <Building2 className="h-5 w-5 text-primary shrink-0" />
                <div className="text-left">
                  <div className="font-medium">{opt.tenantName}</div>
                </div>
              </Button>
            ))}
          </div>
          {error && (
            <div className="flex items-center gap-2 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
              <AlertCircle className="h-4 w-4 shrink-0" />
              {error}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
