// frontend/portal-vue/src/views/landing/JobCard.vue
<template>
  <!-- 岗位卡片：对齐 React frontend/edu/components/job/student/job-card.tsx，
       点击跳转岗位详情 /job/landing/:id（路由由详情页对齐任务注册）。 -->
  <router-link :to="`/job/landing/${position.id}`" class="job-card">
    <div class="job-cover" :style="coverStyle">
      <el-icon v-if="!position.coverImage" class="job-cover-icon"><Briefcase /></el-icon>
      <span v-if="isHot" class="hot-badge">
        <el-icon class="hot-badge-icon"><Sunny /></el-icon>
        热门
      </span>
      <div class="cover-chips">
        <span class="cover-chip">{{ position.version || 'V1.0' }}</span>
        <span class="cover-chip">创建人：{{ creatorName }}</span>
      </div>
      <div class="cover-title-block">
        <h3 class="job-title">{{ position.name }}</h3>
        <div class="job-code">岗位编码：{{ position.code || position.id.slice(0, 8) }}</div>
      </div>
    </div>
    <div class="job-body">
      <div class="stat-grid">
        <div class="stat-cell">
          <div class="stat-value">{{ viewCount }}</div>
          <div class="stat-label">浏览次数</div>
        </div>
        <div class="stat-cell">
          <div class="stat-value">{{ scenarioCount }}</div>
          <div class="stat-label">关联场景</div>
        </div>
        <div class="stat-cell">
          <div class="stat-value">{{ abilityCount || '-' }}</div>
          <div class="stat-label">关联能力点</div>
        </div>
      </div>
      <div class="tag-row">
        <span class="tag tag-industry">面向行业：{{ industryName || '未分类' }}</span>
        <span class="tag tag-major">
          <el-icon><Location /></el-icon>
          适用专业：{{ majorName }}
        </span>
      </div>
      <div class="meta-row">
        <span>收录：{{ formatDate(position.createdAt) }}</span>
        <span>更新：{{ formatDate(position.updatedAt) }}</span>
      </div>
    </div>
  </router-link>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Briefcase, Location, Sunny } from '@element-plus/icons-vue';
import type { CareerPosition } from '@/types/job';
import { coverGradientFor, formatDate } from './evaluation-types';

const props = withDefaults(
  defineProps<{
    position: CareerPosition;
    isHot?: boolean;
    scenarioCount?: number;
    abilityCount?: number;
    industryName?: string;
  }>(),
  {
    isHot: false,
    scenarioCount: 0,
    abilityCount: 0,
    industryName: ''
  }
);

const coverStyle = computed(() =>
  props.position.coverImage
    ? {
        backgroundImage: `url('${props.position.coverImage}')`,
        backgroundSize: 'cover',
        backgroundPosition: 'center'
      }
    : { background: coverGradientFor(props.position.id) }
);

const majorName = computed(() => props.position.majorNames?.[0] || '未分类');
const viewCount = computed(() => props.position.viewCount ?? 0);
const creatorName = computed(() => props.position.createdByName || props.position.createdBy?.slice(0, 8) || '-');
</script>

<style scoped>
.job-card {
  display: flex;
  flex-direction: column;
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  overflow: hidden;
  height: 100%;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.04);
  transition: all 0.3s;
  text-decoration: none;
  color: inherit;
}
.job-card:hover {
  transform: translateY(-6px);
  box-shadow: 0 20px 48px rgba(0, 0, 0, 0.1);
  border-color: var(--el-color-primary-light-5);
}

/* ===== 封面 ===== */
.job-cover {
  height: 176px;
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  padding: 16px;
  flex-shrink: 0;
  background-size: cover;
  background-position: center;
}
.job-cover-icon {
  position: absolute;
  inset: 0;
  margin: auto;
  width: 48px;
  height: 48px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 48px;
  pointer-events: none;
}
.hot-badge {
  position: absolute;
  top: 12px;
  right: 12px;
  z-index: 10;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  background: linear-gradient(135deg, #ef4444, #f43f5e);
  color: #fff;
  font-size: 11px;
  font-weight: 700;
  padding: 4px 10px;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(239, 68, 68, 0.25);
}
.hot-badge-icon {
  font-size: 12px;
}
.cover-chips {
  position: absolute;
  top: 12px;
  left: 12px;
  right: 12px;
  z-index: 10;
  display: flex;
  gap: 6px;
}
.cover-chip {
  background: rgba(15, 23, 42, 0.4);
  backdrop-filter: blur(6px);
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 11px;
  color: #fff;
  font-weight: 500;
  border: 1px solid rgba(255, 255, 255, 0.2);
  white-space: nowrap;
}
.cover-title-block {
  position: relative;
  z-index: 1;
}
.job-title {
  margin: 0 0 4px;
  font-size: 16px;
  font-weight: 700;
  line-height: 1.3;
  color: #fff;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.job-code {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.85);
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}

/* ===== 正文 ===== */
.job-body {
  padding: 20px;
  flex: 1;
  display: flex;
  flex-direction: column;
}
.stat-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 8px;
  margin-bottom: 16px;
}
.stat-cell {
  background: #f8fafc;
  border: 1px solid #f1f5f9;
  border-radius: 12px;
  padding: 10px;
  text-align: center;
}
.stat-value {
  font-size: 18px;
  font-weight: 700;
  color: #1e293b;
  line-height: 1.2;
}
.stat-label {
  font-size: 11px;
  color: #94a3b8;
  margin-top: 2px;
}
.tag-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 16px;
}
.tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 11px;
  padding: 4px 10px;
  border-radius: 999px;
  font-weight: 500;
  white-space: nowrap;
}
.tag-industry {
  background: #fff7ed;
  color: #c2410c;
  border: 1px solid #ffedd5;
}
.tag-major {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  border: 1px solid var(--el-color-primary-light-7);
}
.tag-major .el-icon {
  font-size: 12px;
}
.meta-row {
  margin-top: auto;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px 24px;
  font-size: 12px;
  color: #64748b;
}
</style>

// apps/edu/components/job/student/job-card.tsx
'use client'

import Link from 'next/link'
import { Briefcase, MapPin, Flame } from 'lucide-react'
import type { CareerPosition } from '@/lib/types'
import { formatDate } from '@/lib/format-utils'
import { coverGradientFor } from '@/lib/cover-gradients'

interface JobCardProps {
  position: CareerPosition
  index?: number
  isHot?: boolean
  scenarioCount?: number
  abilityCount?: number
  industryName?: string
}

export function JobCard({
  position,
  isHot,
  scenarioCount = 0,
  abilityCount = 0,
  industryName,
}: JobCardProps) {
  const displayTitle = position.name
  const coverStyle = position.coverImage
    ? { backgroundImage: `url('${position.coverImage}')` }
    : { background: coverGradientFor(position.id) }

  const majorName = position.majorNames?.[0] || '未分类'
  const viewCount = position.viewCount ?? 0
  const relatedScenes = scenarioCount
  const creatorName = position.createdByName || position.createdBy?.slice(0, 8) || '-'

  return (
    <Link href={`/job/landing/${position.id}`}>
      <div className="group bg-white rounded-2xl overflow-hidden border border-[#e7e5e4] transition-all duration-300 hover:-translate-y-2 hover:shadow-[0_20px_48px_rgba(0,0,0,0.1)] hover:border-primary/30 cursor-pointer h-full flex flex-col">
        <div
          className="h-44 relative bg-cover bg-center flex flex-col justify-end p-4"
          style={coverStyle}
        >
          {!position.coverImage && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <Briefcase
                className="w-12 h-12 text-white/85 drop-shadow-md"
                strokeWidth={1.5}
              />
            </div>
          )}
          {isHot && (
            <div className="absolute top-3 right-3 z-10 bg-gradient-to-br from-red-500 to-rose-500 text-white text-[11px] font-bold px-2.5 py-1 rounded-lg flex items-center gap-1 shadow-lg shadow-red-500/25">
              <Flame className="w-3 h-3 fill-current" /> 热门
            </div>
          )}
          <div className="absolute top-3 left-3 right-3 z-10 flex justify-between">
            <div className="flex gap-1.5">
              <span className="bg-[#0f172a]/40 backdrop-blur-md px-2.5 py-1 rounded-md text-[11px] text-white font-medium border border-white/20">
                {position.version || 'v1.0'}
              </span>
              <span className="bg-[#0f172a]/40 backdrop-blur-md px-2.5 py-1 rounded-md text-[11px] text-white font-medium border border-white/20">
                创建人：{creatorName}
              </span>
            </div>
          </div>
          <div className="relative z-10">
            <div className="text-base font-bold leading-snug mb-1 line-clamp-2 text-white text-shadow-md group-hover:text-white/90 transition-colors">
              {displayTitle}
            </div>
            <div className="text-xs text-white/85 text-shadow-sm">
              岗位编码：{position.code || position.id.slice(0, 8)}
            </div>
          </div>
        </div>
        <div className="p-5 flex-1 flex flex-col">
          <div className="grid grid-cols-3 gap-2 mb-4">
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{viewCount}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">浏览次数</div>
            </div>
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{relatedScenes}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">关联场景</div>
            </div>
            <div className="bg-slate-50 rounded-xl p-2.5 text-center border border-slate-100">
              <div className="text-lg font-bold text-slate-800">{abilityCount || '-'}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">关联能力点</div>
            </div>
          </div>
          <div className="flex flex-wrap gap-2 mb-4">
            <span className="text-[11px] px-2.5 py-1 rounded-full bg-orange-50 text-orange-700 border border-orange-100 font-medium">
              面向行业：{industryName || '未分类'}
            </span>
            <span className="text-[11px] px-2.5 py-1 rounded-full bg-primary/5 text-primary border border-primary/10 font-medium flex items-center gap-1">
              <MapPin className="w-3 h-3" /> 适用专业：{majorName}
            </span>
          </div>
          <div className="mt-auto grid grid-cols-2 gap-x-6 gap-y-2.5">
            <span className="text-xs text-slate-500">收录：{formatDate(position.createdAt)}</span>
            <span className="text-xs text-slate-500">更新：{formatDate(position.updatedAt)}</span>
          </div>
        </div>
      </div>
    </Link>
  )
}
