// apps/edu/app/evaluation/exam-usage/page.tsx
'use client'

import { useState, useMemo, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Plus, Search, Clock, PlayCircle, CheckCircle2, Trash2, Eye, Send, PencilLine } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

import { Textarea } from '@/components/ui/textarea'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { useData } from '@/components/providers/data-provider'
import { PageHeaderCard } from '@/components/shared/page-header-card'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { StatusBadge } from '@/components/shared/status-badge'
import { MultiOrgNodePicker } from '@/components/shared/multi-org-node-picker'
import { ExamActivationConfig } from '@/components/evaluation-rules/exam-activation-config'
import { useAuth } from '@/components/auth-provider'
import { examUsageApi } from '@/lib/api'
import type { ExamUsage } from '@/lib/types'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { formatDate } from '@/lib/format-utils'
import { reportError } from '@/lib/error-handling'

const TARGET_TYPE_LABELS: Record<NonNullable<ExamUsage['targetType']>, string> = {
  class: '手动创建',
  major: '手动创建',
  department: '手动创建',
  public: '手动创建',
  task: '场景任务',
  node: '课程节点',
  course: '课程',
}

const STATUS_LABELS: Record<string, string> = {
  draft: '未开启',
  pending: '未开启',
  published: '已开启',
  in_progress: '已开启',
  finished: '已结束',
}

// 手动创建的考试安排目标类型（自动创建的不允许编辑/删除）
const MANUAL_TARGET_TYPES = ['class', 'major', 'department', 'public']

type FilterStatus = ExamUsage['status'] | 'all'

export default function ExamUsagePage() {
  const router = useRouter()
  const { exams } = useData()
  const { user } = useAuth()

  const [usages, setUsages] = useState<ExamUsage[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState<FilterStatus>('all')
  const [createDialogOpen, setCreateDialogOpen] = useState(false)
  const [createSubmitting, setCreateSubmitting] = useState(false)
  const [editingUsage, setEditingUsage] = useState<ExamUsage | null>(null)

  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false)
  const [deletingUsageId, setDeletingUsageId] = useState<string | null>(null)

  // 创建考试使用表单
  const [formExamId, setFormExamId] = useState('')
  const [formName, setFormName] = useState('')
  const [formDescription, setFormDescription] = useState('')
  const [formDuration, setFormDuration] = useState('')
  const [formStartTime, setFormStartTime] = useState('')
  const [formEndTime, setFormEndTime] = useState('')
  const [formClassIds, setFormClassIds] = useState<string[]>([])
  const [formActivationMode, setFormActivationMode] = useState<
    'manual' | 'scheduled' | 'always'
  >('manual')

  const loadUsages = async () => {
    setLoading(true)
    try {
      const res = await examUsageApi.list()
      setUsages(res.items)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    // 初始加载：loading 初始值已为 true，无需在此同步设置
    const load = async () => {
      try {
        const res = await examUsageApi.list()
        setUsages(res.items)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  const examMap = useMemo(() => {
    const map = new Map(exams.map((e) => [e.id, e]))
    return map
  }, [exams])

  const filteredUsages = useMemo(() => {
    return usages.filter((usage) => {
      const exam = examMap.get(usage.examId)
      const matchSearch =
        usage.name.toLowerCase().includes(search.toLowerCase()) ||
        (exam?.name || '').toLowerCase().includes(search.toLowerCase())
      const matchStatus =
        statusFilter === 'all' ||
        usage.status === statusFilter ||
        // 兼容旧数据：pending 归入未开启，in_progress 归入已开启
        (statusFilter === 'draft' && usage.status === 'pending') ||
        (statusFilter === 'published' && usage.status === 'in_progress')
      return matchSearch && matchStatus
    })
  }, [search, statusFilter, usages, examMap])

  const stats = useMemo(() => {
    return {
      total: usages.length,
      draft: usages.filter((u) => u.status === 'draft' || u.status === 'pending').length,
      published: usages.filter(
        (u) => u.status === 'published' || u.status === 'in_progress',
      ).length,
      finished: usages.filter((u) => u.status === 'finished').length,
    }
  }, [usages])

  const resetForm = () => {
    setFormExamId('')
    setFormName('')
    setFormDescription('')
    setFormDuration('')
    setFormStartTime('')
    setFormEndTime('')
    setFormClassIds([])
    setFormActivationMode('manual')
  }

  const openCreateDialog = () => {
    setEditingUsage(null)
    resetForm()
    setCreateDialogOpen(true)
  }

  // RFC3339 → datetime-local 值（UTC，与创建时提交格式一致）
  const toDatetimeLocal = (iso?: string) => {
    if (!iso) return ''
    const d = new Date(iso)
    if (Number.isNaN(d.getTime())) return ''
    const pad = (n: number) => String(n).padStart(2, '0')
    return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}T${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}`
  }

  const openEditDialog = (usage: ExamUsage) => {
    setEditingUsage(usage)
    setFormExamId(usage.examId)
    setFormName(usage.name)
    setFormDescription(usage.description || '')
    setFormDuration(usage.duration != null ? String(usage.duration) : '')
    setFormStartTime(toDatetimeLocal(usage.startTime))
    setFormEndTime(toDatetimeLocal(usage.endTime))
    setFormClassIds(usage.targetIds || [])
    setFormActivationMode(
      (usage.activationMode as 'manual' | 'scheduled' | 'always') || 'manual',
    )
    setCreateDialogOpen(true)
  }

  const handleCreate = async () => {
    if (!formName || (!editingUsage && !formExamId)) return
    setCreateSubmitting(true)
    try {
      const payload = {
        name: formName,
        description: formDescription || undefined,
        duration: formDuration ? Number(formDuration) : undefined,
        startTime: formActivationMode === 'scheduled' ? formStartTime || undefined : undefined,
        endTime: formActivationMode === 'scheduled' ? formEndTime || undefined : undefined,
        targetType: 'class' as const,
        targetIds: formClassIds,
        activationMode: formActivationMode,
      }
      if (editingUsage) {
        await examUsageApi.update(editingUsage.id, payload)
      } else {
        await examUsageApi.create({
          ...payload,
          examId: formExamId,
          status: formActivationMode === 'always' ? 'published' : 'draft',
        })
      }
      setCreateDialogOpen(false)
      resetForm()
      setEditingUsage(null)
      await loadUsages()
    } catch (err) {
      reportError(err, editingUsage ? '编辑考试安排' : '创建考试安排')
    } finally {
      setCreateSubmitting(false)
    }
  }

  const handlePublish = async (id: string) => {
    try {
      await examUsageApi.publish(id)
    } catch (err) {
      reportError(err, '开启考试')
      return
    }
    await loadUsages()
  }

  const handleFinish = async (id: string) => {
    try {
      await examUsageApi.finish(id)
    } catch (err) {
      reportError(err, '停止考试')
      return
    }
    await loadUsages()
  }

  const openDeleteDialog = (id: string) => {
    setDeletingUsageId(id)
    setConfirmDeleteOpen(true)
  }

  const handleDelete = async () => {
    if (!deletingUsageId) return
    try {
      await examUsageApi.delete(deletingUsageId)
      setConfirmDeleteOpen(false)
      setDeletingUsageId(null)
      await loadUsages()
    } catch (err) {
      reportError(err, '删除考试安排')
    }
  }

  const canPublish = (status: ExamUsage['status']) => status === 'draft' || status === 'pending'
  const canFinish = (status: ExamUsage['status']) =>
    status === 'published' || status === 'in_progress'
  const canDelete = (usage: ExamUsage) =>
    (usage.status === 'draft' || usage.status === 'finished') &&
    (!usage.targetType || MANUAL_TARGET_TYPES.includes(usage.targetType))
  // 仅未开启的手动创建考试允许编辑（场景任务/课程节点跟随测评方式配置，不允许修改）
  const canEdit = (usage: ExamUsage) =>
    (usage.status === 'draft' || usage.status === 'pending') &&
    (!usage.targetType || MANUAL_TARGET_TYPES.includes(usage.targetType))

  const isFormValid = (editingUsage ? formName : formExamId && formName) && formClassIds.length > 0

  return (
    <div className="space-y-6">
      <PageHeaderCard
        title="考试管理"
        description="查看试卷在各模块的使用情况"
        actions={
          <Button onClick={openCreateDialog}>
            <Plus className="mr-2 size-4" />
            创建考试使用
          </Button>
        }
        stats={[
          {
            label: '考试总数',
            value: stats.total,
            icon: <Clock className="size-4 text-blue-500" />,
            iconClassName: 'bg-blue-50',
          },
          {
            label: '未开启',
            value: stats.draft,
            icon: <Clock className="size-4 text-gray-500" />,
            iconClassName: 'bg-gray-50',
          },
          {
            label: '已开启',
            value: stats.published,
            icon: <PlayCircle className="size-4 text-green-500" />,
            iconClassName: 'bg-green-50',
          },
          {
            label: '已结束',
            value: stats.finished,
            icon: <CheckCircle2 className="size-4 text-gray-500" />,
            iconClassName: 'bg-gray-50',
          },
        ]}
      />

      {/* 筛选栏 */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
        <div className="relative flex-1 sm:max-w-xs">
          <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="搜索考试名称或关联试卷..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select value={statusFilter} onValueChange={(v) => setStatusFilter(v as FilterStatus)}>
          <SelectTrigger className="w-[140px]">
            <SelectValue placeholder="全部状态" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全部状态</SelectItem>
            <SelectItem value="draft">未开启</SelectItem>
            <SelectItem value="published">已开启</SelectItem>
            <SelectItem value="finished">已结束</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* 使用记录列表 */}
      <div className="rounded-lg border bg-white px-4 py-3">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[180px]">考试名称</TableHead>
                <TableHead className="w-[180px]">关联试卷</TableHead>
                <TableHead className="w-[180px]">开放时间</TableHead>
                <TableHead className="w-[100px]">状态</TableHead>
                <TableHead className="w-[120px]">目标类型</TableHead>
                <TableHead className="sticky right-0 w-[140px] bg-white text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center text-muted-foreground">
                    加载中...
                  </TableCell>
                </TableRow>
              ) : filteredUsages.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center text-muted-foreground">
                    暂无使用记录
                  </TableCell>
                </TableRow>
              ) : (
                filteredUsages.map((usage) => {
                  const exam = examMap.get(usage.examId)
                  return (
                    <TableRow key={usage.id} className="group">
                      <TableCell className="font-medium">{usage.name}</TableCell>
                      <TableCell>{exam?.name || '-'}</TableCell>
                      <TableCell className="text-muted-foreground">
                        {usage.startTime || usage.endTime ? (
                          <div className="text-xs">
                            <div>{usage.startTime ? formatDate(usage.startTime) : '-'}</div>
                            <div>至 {usage.endTime ? formatDate(usage.endTime) : '-'}</div>
                          </div>
                        ) : (
                          <span className="text-xs">-</span>
                        )}
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={usage.status} label={STATUS_LABELS[usage.status]} />
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground">
                          {usage.targetType ? TARGET_TYPE_LABELS[usage.targetType] : '-'}
                        </span>
                      </TableCell>
                      <TableRowActions className="sticky right-0 bg-white">
                        {canEdit(usage) && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs text-gray-600 hover:text-gray-800"
                            onClick={() => openEditDialog(usage)}
                          >
                            <PencilLine className="mr-1 h-3 w-3" />
                            编辑
                          </Button>
                        )}
                        {canPublish(usage.status) && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs text-blue-600 hover:text-blue-700"
                            onClick={() => handlePublish(usage.id)}
                          >
                            <Send className="mr-1 h-3 w-3" />
                            开启
                          </Button>
                        )}
                        {canFinish(usage.status) && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs text-amber-600 hover:text-amber-700"
                            onClick={() => handleFinish(usage.id)}
                          >
                            <CheckCircle2 className="mr-1 h-3 w-3" />
                            停止
                          </Button>
                        )}
                        {usage.status === 'finished' && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs"
                            onClick={() =>
                              router.push(`/evaluation/exam-usage/results?usageId=${usage.id}`)
                            }
                          >
                            <Eye className="mr-1 h-3 w-3" />
                            查看考试结果
                          </Button>
                        )}
                        {canDelete(usage) && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                            onClick={() => openDeleteDialog(usage.id)}
                          >
                            <Trash2 className="mr-1 h-3 w-3" />
                            删除
                          </Button>
                        )}
                      </TableRowActions>
                    </TableRow>
                  )
                })
              )}
            </TableBody>
          </Table>
        </div>
      </div>

      {/* 创建/编辑考试使用弹窗 */}
      <Dialog
        open={createDialogOpen}
        onOpenChange={(open) => {
          setCreateDialogOpen(open)
          if (!open) setEditingUsage(null)
        }}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editingUsage ? '编辑考试' : '创建考试使用'}</DialogTitle>
            <DialogDescription>
              {editingUsage ? '修改考试信息，保存后立即生效' : '选择试卷并配置考试使用信息'}
            </DialogDescription>
          </DialogHeader>
          <FieldGroup className="py-4">
            {!editingUsage && (
              <Field>
                <FieldLabel>选择试卷 *</FieldLabel>
                <Select value={formExamId} onValueChange={setFormExamId}>
                  <SelectTrigger>
                    <SelectValue placeholder="请选择一份试卷" />
                  </SelectTrigger>
                  <SelectContent>
                    {exams
                      .filter((exam) => exam.status === 'published')
                      .map((exam) => (
                        <SelectItem key={exam.id} value={exam.id}>
                          {exam.name}
                        </SelectItem>
                      ))}
                  </SelectContent>
                </Select>
              </Field>
            )}

            <Field>
              <FieldLabel>考试名称 *</FieldLabel>
              <Input
                value={formName}
                onChange={(e) => setFormName(e.target.value)}
                placeholder="请输入考试名称"
              />
            </Field>

            <Field>
              <FieldLabel>描述</FieldLabel>
              <Textarea
                value={formDescription}
                onChange={(e) => setFormDescription(e.target.value)}
                placeholder="请输入描述（可选）"
                rows={2}
              />
            </Field>

            <Field>
              <FieldLabel>时长/分钟</FieldLabel>
              <Input
                type="number"
                value={formDuration}
                onChange={(e) => setFormDuration(e.target.value)}
                placeholder="请输入考试时长"
                min={0}
              />
            </Field>

            <Field>
              <FieldLabel>启用条件</FieldLabel>
              <ExamActivationConfig
                value={{
                  activationMode: formActivationMode,
                  scheduledTime: formStartTime,
                  scheduledEndTime: formEndTime,
                }}
                onChange={(updates) => {
                  if (updates.activationMode)
                    setFormActivationMode(updates.activationMode as 'manual' | 'scheduled' | 'always')
                  if (updates.scheduledTime !== undefined) setFormStartTime(updates.scheduledTime)
                  if (updates.scheduledEndTime !== undefined)
                    setFormEndTime(updates.scheduledEndTime)
                }}
              />
              <p className="text-xs text-muted-foreground mt-1">
                随时作答创建后立即开放；定时/手动启停创建为未开启，到时间或手动开启后开放
              </p>
            </Field>

            <Field>
              <FieldLabel>参与班级 *</FieldLabel>
              <MultiOrgNodePicker
                tenantId={user?.tenantId}
                value={formClassIds}
                onChange={setFormClassIds}
                selectableTypes={['班级']}
                title="选择参与班级"
                maxVisible={3}
              />
              <p className="text-xs text-muted-foreground mt-1">
                仅所选班级的学生可见并可参加该考试
              </p>
            </Field>
          </FieldGroup>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setCreateDialogOpen(false)}
              disabled={createSubmitting}
            >
              取消
            </Button>
            <Button onClick={handleCreate} disabled={!isFormValid || createSubmitting}>
              {createSubmitting ? '提交中...' : editingUsage ? '保存' : '创建'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 删除确认弹窗 */}
      <ConfirmDialog
        open={confirmDeleteOpen}
        onOpenChange={setConfirmDeleteOpen}
        title="删除考试使用"
        description="删除后无法恢复，确定要删除吗？"
        onConfirm={handleDelete}
      />
    </div>
  )
}

// frontend/portal-vue/src/views/evaluation/exam-usage.vue
<template>
  <div class="list-page">
    <div class="page-header">
      <div>
        <h2 class="page-title">考试管理</h2>
        <p class="page-sub">查看试卷在各模块的使用情况</p>
      </div>
      <el-button type="primary" @click="openCreate">创建考试使用</el-button>
    </div>

    <el-row :gutter="16" class="stats-row">
      <el-col :span="6"><div class="stat"><div class="stat-value blue">{{ stats.total }}</div><div class="stat-label">考试总数</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value gray">{{ stats.draft }}</div><div class="stat-label">未开启</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value green">{{ stats.published }}</div><div class="stat-label">已开启</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value gray">{{ stats.finished }}</div><div class="stat-label">已结束</div></div></el-col>
    </el-row>

    <el-card shadow="never">
      <div class="filter-row">
        <el-input v-model="search" placeholder="搜索考试名称或关联试卷..." clearable style="max-width: 320px" />
        <el-select v-model="statusFilter" style="width: 140px">
          <el-option label="全部状态" value="all" />
          <el-option label="未开启" value="draft" />
          <el-option label="已开启" value="published" />
          <el-option label="已结束" value="finished" />
        </el-select>
      </div>

      <el-table v-loading="loading" :data="filteredUsages" stripe>
        <el-table-column label="考试名称" prop="name" min-width="160" show-overflow-tooltip />
        <el-table-column label="关联试卷" min-width="160">
          <template #default="{ row }">{{ examName(row.examId) }}</template>
        </el-table-column>
        <el-table-column label="开放时间" min-width="150">
          <template #default="{ row }">
            <template v-if="row.startTime || row.endTime">
              <div>{{ row.startTime ? fmt(row.startTime) : '-' }}</div>
              <div>至 {{ row.endTime ? fmt(row.endTime) : '-' }}</div>
            </template>
            <span v-else>-</span>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="目标类型" width="110">
          <template #default="{ row }">{{ targetTypeLabel(row.targetType) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="260" fixed="right">
          <template #default="{ row }">
            <el-button v-if="canEdit(row)" size="small" @click="openEdit(row)">编辑</el-button>
            <el-button v-if="canPublish(row.status)" size="small" type="primary" @click="publish(row.id)">开启</el-button>
            <el-button v-if="canFinish(row.status)" size="small" type="warning" @click="finish(row.id)">停止</el-button>
            <el-button v-if="row.status === 'finished'" size="small" @click="$router.push(`/evaluation/exam-usage-results?usageId=${row.id}`)">查看考试结果</el-button>
            <el-button v-if="canDelete(row)" size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 创建/编辑弹窗 -->
    <el-dialog v-model="dialog" :title="editing ? '编辑考试' : '创建考试使用'" width="560px">
      <el-form label-width="90px">
        <el-form-item v-if="!editing" label="选择试卷" required>
          <el-select v-model="form.examId" filterable placeholder="请选择一份试卷" style="width: 100%">
            <el-option v-for="e in publishedExams" :key="e.id" :label="e.name" :value="e.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="考试名称" required><el-input v-model="form.name" placeholder="请输入考试名称" /></el-form-item>
        <el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2" placeholder="请输入描述（可选）" /></el-form-item>
        <el-form-item label="时长/分钟"><el-input-number v-model="form.duration" :min="0" placeholder="请输入考试时长" /></el-form-item>
        <el-form-item label="启用条件">
          <el-radio-group v-model="form.activationMode">
            <el-radio value="manual">手动启停</el-radio>
            <el-radio value="scheduled">定时</el-radio>
            <el-radio value="always">随时作答</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item v-if="form.activationMode === 'scheduled'" label="开放时间">
          <div class="time-col">
            <el-date-picker v-model="form.startTime" type="datetime" placeholder="开始时间" />
            <el-date-picker v-model="form.endTime" type="datetime" placeholder="结束时间" />
          </div>
        </el-form-item>
        <el-form-item label="参与班级" required>
          <el-tree-select
            v-model="form.classIds"
            :data="classTreeData"
            node-key="value"
            :props="{ label: 'label', children: 'children' }"
            placeholder="选择参与班级"
            check-strictly
            multiple
            show-checkbox
            default-expand-all
            style="width: 100%"
          />
          <div class="form-hint">仅所选班级的学生可见并可参加该考试</div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" :disabled="!isFormValid" @click="save">{{ editing ? '保存' : '创建' }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { examApi, examUsageApi } from '@/api/evaluation';
import { organizationApi, orgTypeApi } from '@/api/system';
import type { Exam, ExamUsage } from '@/types/evaluation';

const usages = ref<ExamUsage[]>([]);
const exams = ref<Exam[]>([]);
const classTreeData = ref<{ value: string; label: string; children?: any[] }[]>([]);
const loading = ref(false);
const saving = ref(false);
const search = ref('');
const statusFilter = ref('all');
const dialog = ref(false);
const editing = ref<ExamUsage | null>(null);

const form = reactive({
  examId: '', name: '', description: '', duration: undefined as number | undefined,
  startTime: '' as string, endTime: '' as string,
  activationMode: 'manual' as 'manual' | 'scheduled' | 'always',
  classIds: [] as string[]
});

const MANUAL_TYPES = ['class', 'major', 'department', 'public'];
const examMap = computed(() => new Map(exams.value.map((e) => [e.id, e])));
const publishedExams = computed(() => exams.value.filter((e) => e.status === 'published'));

const filteredUsages = computed(() =>
  usages.value.filter((u) => {
    const exam = examMap.value.get(u.examId);
    const matchSearch = u.name.toLowerCase().includes(search.value.toLowerCase()) ||
      (exam?.name || '').toLowerCase().includes(search.value.toLowerCase());
    const matchStatus =
      statusFilter.value === 'all' ||
      u.status === statusFilter.value ||
      (statusFilter.value === 'draft' && u.status === 'pending') ||
      (statusFilter.value === 'published' && u.status === 'in_progress');
    return matchSearch && matchStatus;
  })
);
const stats = computed(() => ({
  total: usages.value.length,
  draft: usages.value.filter((u) => u.status === 'draft' || u.status === 'pending').length,
  published: usages.value.filter((u) => u.status === 'published' || u.status === 'in_progress').length,
  finished: usages.value.filter((u) => u.status === 'finished').length
}));
const isFormValid = computed(() => {
  const nameOk = editing.value ? !!form.name.trim() : !!(form.examId && form.name.trim());
  const targetOk = form.classIds.length > 0 || editing.value?.targetType === 'public';
  return !!(nameOk && targetOk);
});

function examName(id: string) {
  return examMap.value.get(id)?.name || '-';
}
function statusLabel(s: string) {
  const labels: Record<string, string> = { draft: '未开启', pending: '未开启', published: '已开启', in_progress: '已开启', finished: '已结束', scheduled: '未开启' };
  return labels[s] || s;
}
function statusType(s: string) {
  if (s === 'published' || s === 'in_progress') return 'success';
  if (s === 'finished') return 'info';
  return 'warning';
}
function targetTypeLabel(t?: string) {
  const labels: Record<string, string> = { class: '手动创建', major: '手动创建', department: '手动创建', public: '手动创建', task: '场景任务', node: '课程节点', course: '课程' };
  return t ? labels[t] || '-' : '-';
}
function fmt(d?: string) {
  return d ? String(d).slice(0, 16).replace('T', ' ') : '-';
}
function canPublish(s: string) { return s === 'draft' || s === 'pending'; }
function canFinish(s: string) { return s === 'published' || s === 'in_progress'; }
function canDelete(u: ExamUsage) {
  return (u.status === 'draft' || u.status === 'finished') && (!u.targetType || MANUAL_TYPES.includes(u.targetType));
}
function canEdit(u: ExamUsage) {
  return (u.status === 'draft' || u.status === 'pending') && (!u.targetType || MANUAL_TYPES.includes(u.targetType));
}

async function load() {
  loading.value = true;
  try {
    const [usageRes, examRes, orgRes, orgTypeRes] = await Promise.all([
      examUsageApi.list({ limit: 200 }),
      examApi.list({ limit: 200 }),
      organizationApi.tree(),
      orgTypeApi.list({ limit: 200 })
    ]);
    usages.value = usageRes.items;
    exams.value = examRes.items;
    const classTypeIds = new Set((orgTypeRes.items || []).filter((t) => t.name === '班级').map((t) => t.id));
    const buildTree = (nodes: any[]): any[] => nodes.map((n) => ({ value: n.id, label: n.name, children: n.children ? buildTree(n.children) : [] }));
    const fullTree = buildTree(orgRes.items || []);
    const filterClassTree = (nodes: any[]): any[] =>
      nodes.map((n) => ({ ...n, children: filterClassTree(n.children || []) }))
        .filter((n) => n.children.length > 0 || classTypeIds.has(n.value));
    classTreeData.value = filterClassTree(fullTree);
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function resetForm() {
  form.examId = '';
  form.name = '';
  form.description = '';
  form.duration = undefined;
  form.startTime = '';
  form.endTime = '';
  form.activationMode = 'manual';
  form.classIds = [];
}
function openCreate() {
  editing.value = null;
  resetForm();
  dialog.value = true;
}
function openEdit(u: ExamUsage) {
  editing.value = u;
  form.examId = u.examId;
  form.name = u.name;
  form.description = u.description || '';
  form.duration = u.duration;
  form.startTime = u.startTime ? toLocal(u.startTime) : '';
  form.endTime = u.endTime ? toLocal(u.endTime) : '';
  form.activationMode = (u.activationMode as any) || 'manual';
  form.classIds = u.targetIds || [];
  dialog.value = true;
}
function toLocal(iso: string) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function toRfc3339(v?: string) {
  if (!v) return undefined;
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? undefined : d.toISOString();
}

async function save() {
  saving.value = true;
  try {
    const base = {
      name: form.name.trim(),
      description: form.description || undefined,
      duration: form.duration,
      startTime: form.activationMode === 'scheduled' ? toRfc3339(form.startTime) : undefined,
      endTime: form.activationMode === 'scheduled' ? toRfc3339(form.endTime) : undefined,
      activationMode: form.activationMode
    };
    if (editing.value) {
      await examUsageApi.update(editing.value.id, base);
      ElMessage.success('保存成功');
    } else {
      await examUsageApi.create({
        ...base,
        examId: form.examId,
        targetType: 'class',
        targetIds: form.classIds,
        status: form.activationMode === 'always' ? 'published' : 'draft'
      });
      ElMessage.success('创建成功');
    }
    dialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function publish(id: string) {
  try { await examUsageApi.publish(id); load(); } catch (e) { ElMessage.error((e as Error).message || '开启考试失败'); }
}
async function finish(id: string) {
  try { await examUsageApi.finish(id); load(); } catch (e) { ElMessage.error((e as Error).message || '停止考试失败'); }
}
async function confirmDelete(u: ExamUsage) {
  try { await ElMessageBox.confirm('删除后无法恢复，确定要删除吗？', '删除考试使用', { type: 'warning' }); } catch { return; }
  try { await examUsageApi.delete(u.id); ElMessage.success('删除成功'); load(); }
  catch (e) { ElMessage.error((e as Error).message || '删除失败'); }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.page-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 16px; }
.page-title { font-size: 20px; font-weight: 700; margin: 0; }
.page-sub { color: #909399; margin: 8px 0 0; }
.stats-row { margin-bottom: 16px; }
.stat { background: #fff; border-radius: 8px; padding: 16px; text-align: center; }
.stat-value { font-size: 24px; font-weight: 700; }
.stat-value.blue { color: #409eff; }
.stat-value.green { color: #67c23a; }
.stat-value.gray { color: #909399; }
.stat-label { color: #909399; font-size: 13px; margin-top: 4px; }
.filter-row { display: flex; gap: 12px; margin-bottom: 12px; }
.time-col { display: flex; flex-direction: column; gap: 8px; width: 100%; }
.form-hint { color: #909399; font-size: 12px; margin-top: 4px; }
</style>
