// apps/edu/app/evaluation/job-ability/page.tsx
'use client'

import { useState, useMemo, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import {
  Briefcase,
  CheckCircle2,
  FileEdit,
  AlertCircle,
  Settings2,
  Eye,
  Upload,
  Undo2,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { useToast, TableEmptyRow } from '@zhiyu/ui'
import { SearchInput } from '@/components/shared/search-input'
import { PageHeaderCard } from '@/components/shared/page-header-card'
import { StatusBadge } from '@/components/shared/status-badge'
import { TableRowActions } from '@/components/shared/table-row-actions'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { certApi, positionApi } from '@/lib/api'
import type { CareerPosition, CertificationRule } from '@/lib/types'
import { formatDate } from '@/lib/format-utils'
import { useT } from '@/lib/i18n/locale-provider'

export default function JobAbilityPage() {
  const t = useT()
  const router = useRouter()
  const { toast } = useToast()

  const [positions, setPositions] = useState<CareerPosition[]>([])
  const [rules, setRules] = useState<CertificationRule[]>([])
  const [pointCounts, setPointCounts] = useState<Record<string, number>>({})
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [statusTarget, setStatusTarget] = useState<CertificationRule | null>(null)
  const [statusSaving, setStatusSaving] = useState(false)

  useEffect(() => {
    let cancelled = false
    Promise.all([positionApi.list({ limit: 200 }), certApi.listRules({ limit: 200 })])
      .then(async ([positionRes, ruleRes]) => {
        if (cancelled) return
        setPositions(positionRes.items)
        setRules(ruleRes.items)
        // 统计每条规则对应岗位下已配置的能力点数（以岗位能力绑定为准）
        // 同一岗位可能关联多条规则：按岗位 id 去重后只拉一次模型，避免每规则一次 getPositionModel 的 N+1 请求
        const positionIds = Array.from(
          new Set(ruleRes.items.map((rule) => rule.careerPositionId)),
        )
        const modelResults = await Promise.all(
          positionIds.map(async (positionId) => {
            try {
              const model = await certApi.getPositionModel(positionId)
              return {
                positionId,
                count: model.domains.reduce((sum, d) => sum + d.points.length, 0),
              }
            } catch {
              return { positionId, count: 0 }
            }
          }),
        )
        const counts: Record<string, number> = {}
        const countByPosition = new Map(modelResults.map((m) => [m.positionId, m.count]))
        ruleRes.items.forEach((rule) => {
          counts[rule.id] = countByPosition.get(rule.careerPositionId) ?? 0
        })
        if (!cancelled) setPointCounts(counts)
      })
      .catch((err) => {
        if (cancelled) return
        toast({
          title: t('加载失败'),
          description: err instanceof Error ? err.message : t('获取岗位认证数据失败'),
          variant: 'destructive',
        })
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [toast, t])

  const ruleMap = useMemo(() => {
    const map = new Map<string, CertificationRule>()
    rules.forEach((rule) => map.set(rule.careerPositionId, rule))
    return map
  }, [rules])

  const filteredPositions = useMemo(() => {
    const keyword = search.toLowerCase()
    return positions.filter(
      (position) =>
        position.name.toLowerCase().includes(keyword) ||
        (position.code || '').toLowerCase().includes(keyword),
    )
  }, [positions, search])

  // 发布/下线规则：汇聚计算只处理 published 状态的规则
  const handleToggleStatus = async () => {
    if (!statusTarget) return
    const nextStatus = statusTarget.status === 'published' ? 'draft' : 'published'
    setStatusSaving(true)
    try {
      const updated = await certApi.updateRuleStatus(statusTarget.id, nextStatus)
      setRules((prev) => prev.map((r) => (r.id === updated.id ? updated : r)))
      toast({ title: nextStatus === 'published' ? t('规则已发布') : t('规则已下线') })
    } catch (err) {
      toast({
        title: t('操作失败'),
        description: err instanceof Error ? err.message : t('更新规则状态失败'),
        variant: 'destructive',
      })
    } finally {
      setStatusSaving(false)
      setStatusTarget(null)
    }
  }

  const stats = useMemo(() => {
    const ruleStatuses = positions.map((p) => ruleMap.get(p.id)?.status ?? 'none')
    return {
      total: positions.length,
      published: ruleStatuses.filter((s) => s === 'published').length,
      configured: ruleStatuses.filter((s) => s !== 'none' && s !== 'published').length,
      none: ruleStatuses.filter((s) => s === 'none').length,
    }
  }, [positions, ruleMap])

  return (
    <div className="space-y-6">
      <PageHeaderCard
        title={t('岗位能力认定规则')}
        description={t('管理各岗位的能力认定规则配置')}
        stats={[
          {
            label: t('岗位总数'),
            value: stats.total,
            icon: <Briefcase className="size-4 text-blue-500" />,
            iconClassName: 'bg-blue-50',
          },
          {
            label: t('已发布规则'),
            value: stats.published,
            icon: <CheckCircle2 className="size-4 text-green-500" />,
            iconClassName: 'bg-green-50',
          },
          {
            label: t('配置中'),
            value: stats.configured,
            icon: <FileEdit className="size-4 text-amber-500" />,
            iconClassName: 'bg-amber-50',
          },
          {
            label: t('无规则'),
            value: stats.none,
            icon: <AlertCircle className="size-4 text-gray-500" />,
            iconClassName: 'bg-gray-50',
          },
        ]}
      />

      {/* 搜索栏 */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
        <SearchInput
          wrapperClassName="flex-1 sm:max-w-xs"
          placeholder={t('搜索岗位名称或编码...')}
          value={search}
          onChange={setSearch}
        />
      </div>

      {/* 岗位认证列表 */}
      <div className="rounded-lg border bg-white px-4 py-3">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[180px]">{t('岗位名称')}</TableHead>
                <TableHead className="w-[140px]">{t('岗位编码')}</TableHead>
                <TableHead className="w-[160px]">{t('专业方向')}</TableHead>
                <TableHead className="w-[110px] text-center">{t('关联能力点数')}</TableHead>
                <TableHead className="w-[100px]">{t('规则状态')}</TableHead>
                <TableHead className="w-[150px]">{t('更新时间')}</TableHead>
                <TableHead className="sticky right-0 w-[200px] bg-white text-right">{t('操作')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={7} className="h-24 text-center text-muted-foreground">
                    {t('加载中...')}
                  </TableCell>
                </TableRow>
              ) : filteredPositions.length === 0 ? (
                <TableEmptyRow colSpan={7}>{t('暂无岗位数据')}</TableEmptyRow>
              ) : (
                filteredPositions.map((position) => {
                  const rule = ruleMap.get(position.id)
                  const pointCount = rule ? pointCounts[rule.id] : undefined
                  return (
                    <TableRow key={position.id} className="group">
                      <TableCell className="font-medium">{position.name}</TableCell>
                      <TableCell className="text-muted-foreground">
                        {position.code || '-'}
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground line-clamp-1">
                          {position.majorNames && position.majorNames.length > 0
                            ? position.majorNames.join('、')
                            : '-'}
                        </span>
                      </TableCell>
                      <TableCell className="text-center">
                        {rule ? (pointCount ?? '-') : 0}
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={rule?.status ?? 'none'} />
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        <span className="text-xs">
                          {formatDate(rule?.updatedAt ?? position.updatedAt)}
                        </span>
                      </TableCell>
                      <TableRowActions className="sticky right-0 bg-white">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() =>
                            router.push(`/evaluation/job-ability/config/${position.id}`)
                          }
                        >
                          <Settings2 className="mr-1 h-3 w-3" />
                          {t('配置认证规则')}
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-7 px-2 text-xs"
                          onClick={() =>
                            router.push(`/evaluation/job-ability/results?positionId=${position.id}`)
                          }
                        >
                          <Eye className="mr-1 h-3 w-3" />
                          {t('查看结果')}
                        </Button>
                        {rule && (
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 px-2 text-xs"
                            onClick={() => setStatusTarget(rule)}
                          >
                            {rule.status === 'published' ? (
                              <>
                                <Undo2 className="mr-1 h-3 w-3" />
                                {t('下线')}
                              </>
                            ) : (
                              <>
                                <Upload className="mr-1 h-3 w-3" />
                                {t('发布')}
                              </>
                            )}
                          </Button>
                        )}
                      </TableRowActions>
                    </TableRow>
                  )
                })
              )}
            </TableBody>
          </Table>
        </div>
      </div>

      <ConfirmDialog
        open={statusTarget !== null}
        onOpenChange={(open) => {
          if (!open) setStatusTarget(null)
        }}
        title={statusTarget?.status === 'published' ? t('下线认证规则') : t('发布认证规则')}
        description={
          statusTarget?.status === 'published'
            ? t('下线后该岗位的认证规则不再参与能力汇聚计算，已生成的汇聚结果会保留。确认下线？')
            : t('发布后该岗位的认证规则将参与每日定时能力汇聚，也可在结果页手动触发汇聚。确认发布？')
        }
        confirmText={statusSaving ? t('处理中...') : t('确认')}
        onConfirm={handleToggleStatus}
      />
    </div>
  )
}

// frontend/portal-vue/src/views/evaluation/job-ability.vue
<template>
  <div class="list-page">
    <div class="page-header">
      <h2 class="page-title">岗位能力认定规则</h2>
      <p class="page-sub">管理各岗位的能力认定规则配置</p>
    </div>

    <el-row :gutter="16" class="stats-row">
      <el-col :span="6"><div class="stat"><div class="stat-value">{{ stats.total }}</div><div class="stat-label">岗位总数</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value green">{{ stats.published }}</div><div class="stat-label">已发布规则</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value amber">{{ stats.configured }}</div><div class="stat-label">配置中</div></div></el-col>
      <el-col :span="6"><div class="stat"><div class="stat-value gray">{{ stats.none }}</div><div class="stat-label">无规则</div></div></el-col>
    </el-row>

    <el-card shadow="never">
      <div class="filter-row">
        <el-input v-model="search" placeholder="搜索岗位名称或编码..." clearable style="max-width: 320px" />
      </div>
      <el-table v-loading="loading" :data="filteredPositions" stripe>
        <el-table-column label="岗位名称" min-width="160">
          <template #default="{ row }"><span class="strong">{{ row.name }}</span></template>
        </el-table-column>
        <el-table-column label="岗位编码" prop="code" width="130">
          <template #default="{ row }">{{ row.code || '-' }}</template>
        </el-table-column>
        <el-table-column label="专业方向" min-width="140">
          <template #default="{ row }">{{ (row.majorNames && row.majorNames.length) ? row.majorNames.join('、') : '-' }}</template>
        </el-table-column>
        <el-table-column label="关联能力点数" width="110" align="center">
          <template #default="{ row }">
            {{ ruleOf(row) ? (pointCounts[row.id] ?? '-') : 0 }}
          </template>
        </el-table-column>
        <el-table-column label="规则状态" width="100">
          <template #default="{ row }">
            <el-tag :type="statusType(ruleOf(row)?.status)">{{ statusLabel(ruleOf(row)?.status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="更新时间" width="150">
          <template #default="{ row }">{{ fmtDate(ruleOf(row)?.updatedAt || row.updatedAt) }}</template>
        </el-table-column>
        <el-table-column label="操作" width="230" align="right">
          <template #default="{ row }">
            <el-button size="small" @click="$router.push(`/evaluation/job-ability-config/${row.id}`)">配置认证规则</el-button>
            <el-button size="small" @click="$router.push(`/evaluation/job-ability-results?positionId=${row.id}`)">查看结果</el-button>
            <el-button v-if="ruleOf(row)" size="small" @click="confirmToggle(row)">
              {{ ruleOf(row)?.status === 'published' ? '下线' : '发布' }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="toggleDialog" :title="toggleTitle" width="480px">
      <p>{{ toggleDescription }}</p>
      <template #footer>
        <el-button @click="toggleDialog = false">取消</el-button>
        <el-button type="primary" :loading="statusSaving" @click="handleToggle">确认</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { positionApi } from '@/api/job';
import { certApi } from '@/api/evaluation';
import type { CareerPosition } from '@/types/job';
import type { CertificationRule } from '@/types/evaluation';

const positions = ref<CareerPosition[]>([]);
const rules = ref<CertificationRule[]>([]);
const pointCounts = ref<Record<string, number>>({});
const loading = ref(true);
const search = ref('');
const toggleDialog = ref(false);
const statusSaving = ref(false);
const statusTarget = ref<CertificationRule | null>(null);

const ruleMap = computed(() => {
  const m = new Map<string, CertificationRule>();
  rules.value.forEach((r) => m.set(r.careerPositionId, r));
  return m;
});
const filteredPositions = computed(() => {
  const kw = search.value.toLowerCase();
  return positions.value.filter(
    (p) => p.name.toLowerCase().includes(kw) || (p.code || '').toLowerCase().includes(kw)
  );
});
const stats = computed(() => {
  const statuses = positions.value.map((p) => ruleMap.value.get(p.id)?.status ?? 'none');
  return {
    total: positions.value.length,
    published: statuses.filter((s) => s === 'published').length,
    configured: statuses.filter((s) => s !== 'none' && s !== 'published').length,
    none: statuses.filter((s) => s === 'none').length
  };
});

function ruleOf(row: CareerPosition) {
  return ruleMap.value.get(row.id) || null;
}
function statusLabel(s?: string) {
  const labels: Record<string, string> = {
    draft: '草稿', not_submitted: '未提交', reviewing: '审批中', rejected: '已驳回',
    ready: '待发布', published: '已发布', none: '无规则'
  };
  return labels[s || 'none'] || '无规则';
}
function statusType(s?: string) {
  if (s === 'published') return 'success';
  if (s === 'none') return 'info';
  if (s === 'rejected') return 'danger';
  if (s === 'reviewing') return 'warning';
  return 'primary';
}
function fmtDate(d?: string) {
  return d ? String(d).slice(0, 10) : '-';
}

const toggleTitle = computed(() => (statusTarget.value?.status === 'published' ? '下线认证规则' : '发布认证规则'));
const toggleDescription = computed(() =>
  statusTarget.value?.status === 'published'
    ? '下线后该岗位的认证规则不再参与能力汇聚计算，已生成的汇聚结果会保留。确认下线？'
    : '发布后该岗位的认证规则将参与每日定时能力汇聚，也可在结果页手动触发汇聚。确认发布？'
);

async function load() {
  loading.value = true;
  try {
    const [posRes, ruleRes] = await Promise.all([
      positionApi.list({ limit: 1000 }),
      certApi.listRules({ limit: 1000 })
    ]);
    positions.value = posRes.items;
    rules.value = ruleRes.items;

    const positionIds = Array.from(new Set(rules.value.map((r) => r.careerPositionId)));
    const modelResults = await Promise.all(
      positionIds.map(async (positionId) => {
        try {
          const model = await certApi.getPositionModel(positionId);
          return { positionId, count: model.domains.reduce((s, d) => s + d.points.length, 0) };
        } catch {
          return { positionId, count: 0 };
        }
      })
    );
    const counts: Record<string, number> = {};
    const countByPosition = new Map(modelResults.map((m) => [m.positionId, m.count]));
    rules.value.forEach((rule) => {
      counts[rule.id] = countByPosition.get(rule.careerPositionId) ?? 0;
    });
    pointCounts.value = counts;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function confirmToggle(row: CareerPosition) {
  const rule = ruleOf(row);
  if (!rule) return;
  statusTarget.value = rule;
  toggleDialog.value = true;
}
async function handleToggle() {
  const target = statusTarget.value;
  if (!target) return;
  const nextStatus = target.status === 'published' ? 'draft' : 'published';
  statusSaving.value = true;
  try {
    const updated = await certApi.updateRuleStatus(target.id, nextStatus);
    rules.value = rules.value.map((r) => (r.id === updated.id ? updated : r));
    toggleDialog.value = false;
    ElMessage.success(nextStatus === 'published' ? '规则已发布' : '规则已下线');
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  } finally {
    statusSaving.value = false;
    statusTarget.value = null;
  }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.page-header { margin-bottom: 16px; }
.page-title { font-size: 20px; font-weight: 700; margin: 0; }
.page-sub { color: #909399; margin: 8px 0 0; }
.stats-row { margin-bottom: 16px; }
.stat { background: #fff; border-radius: 8px; padding: 16px; text-align: center; }
.stat-value { font-size: 24px; font-weight: 700; color: #409eff; }
.stat-value.green { color: #67c23a; }
.stat-value.amber { color: #e6a23c; }
.stat-value.gray { color: #909399; }
.stat-label { color: #909399; font-size: 13px; margin-top: 4px; }
.filter-row { margin-bottom: 12px; }
.strong { font-weight: 600; }
</style>
