// frontend/portal-vue/src/views/portal/apps/alliance/permissions.vue
<template>
  <div class="list-page">
    <div class="page-head">
      <div class="page-title">合作权限管理</div>
      <div class="page-sub">为企业授予岗位/场景的编辑权限：授权后企业专家可登录企业服务台查看并编辑这些资源（编辑稿需学校审批后生效）。</div>
    </div>

    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div class="card-title">选择企业</div>
          <div class="card-sub">仅可对本校已引入的企业授权</div>
        </div>
      </template>
      <el-select v-model="enterpriseId" placeholder="请选择企业" style="max-width: 420px" :disabled="entLoading" @change="onSelectEnterprise">
        <el-option v-for="e in enterprises" :key="e.id" :label="e.name" :value="e.id" />
      </el-select>
    </el-card>

    <el-card v-if="currentEnterpriseId" shadow="never" class="grant-card">
      <template #header>
        <div class="card-header">
          <div class="card-title">资源授权</div>
          <div class="card-sub">展示本校全部岗位/场景（含各状态与批次分组），勾选即授权该企业编辑权限，保存按类型整组生效。</div>
        </div>
      </template>

      <el-tabs v-model="activeType">
        <el-tab-pane label="岗位" name="position" />
        <el-tab-pane label="场景" name="scene" />
      </el-tabs>

      <div class="filters">
        <el-input
          v-model="search"
          :placeholder="activeType === 'position' ? '搜索岗位名称' : '搜索场景名称'"
          clearable
          style="flex: 1; min-width: 220px"
        />
        <el-select v-model="batchFilter" placeholder="按批次筛选" style="width: 180px">
          <el-option label="全部批次" value="__all__" />
          <el-option v-for="b in batches" :key="b.id" :label="b.name" :value="b.id" />
          <el-option v-if="uncategorized.length > 0" label="未分类" value="__none__" />
        </el-select>
        <el-select v-model="statusFilter" placeholder="按状态筛选" style="width: 130px">
          <el-option label="全部状态" value="__all__" />
          <el-option v-for="opt in STATUS_OPTIONS" :key="opt.value" :label="opt.label" :value="opt.value" />
        </el-select>
        <el-button @click="resetFilters">重置</el-button>
      </div>

      <div class="action-bar">
        <span class="selected-count">已勾选 {{ selectedCount }} 个{{ activeType === 'position' ? '岗位' : '场景' }}</span>
        <el-button v-if="filtered.length > 0" size="small" @click="toggleFilteredAll">
          {{ allFilteredChecked ? '取消当前筛选全选' : '全选当前筛选' }}
        </el-button>
        <div class="flex-1" />
        <el-button type="primary" size="small" :loading="saving" @click="saveCurrentType">
          保存{{ activeType === 'position' ? '岗位' : '场景' }}授权
        </el-button>
      </div>

      <div v-loading="optionsLoading">
        <el-empty v-if="filtered.length === 0" :description="`当前筛选条件下暂无${activeType === 'position' ? '岗位' : '场景'}`" />
        <div v-else class="groups">
          <div v-for="b in filteredBatches" :key="b.id" class="group-card">
            <div class="group-head clickable" @click="toggleBatch(b.id)">
              <div class="group-title">
                <span class="group-name">{{ b.name }}</span>
                <el-tag size="small" type="info">{{ b.items.length }}</el-tag>
              </div>
              <el-button size="small" text @click.stop="toggleGroupAll(b.items)">
                {{ groupAllChecked(b.items) ? '取消全选' : '全选' }}
              </el-button>
            </div>
            <div v-if="!collapsedBatches.has(b.id)" class="group-body">
              <div class="row-grid">
                <div v-for="o in b.items" :key="o.id" class="row-item" :class="{ checked: isChecked(o) }" @click="toggleOne(o)">
                  <el-checkbox :model-value="isChecked(o)" @click.stop @change="toggleOne(o)" />
                  <div class="row-main">
                    <div class="row-name">{{ o.name }}</div>
                    <div class="row-meta">
                      <span class="status-badge" :style="{ color: statusConfigOf(o.status).color, background: statusConfigOf(o.status).bg }">{{ statusConfigOf(o.status).label }}</span>
                      <span class="meta-text">{{ sourceLabel(o) }}</span>
                      <span v-if="o.batchName" class="meta-text">批次：{{ o.batchName }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="filteredUncategorized.length > 0" class="group-card uncategorized">
            <div class="group-head">
              <div class="group-title">
                <span class="group-name">未分类</span>
                <el-tag size="small" type="info">{{ filteredUncategorized.length }}</el-tag>
              </div>
              <el-button size="small" text @click="toggleGroupAll(filteredUncategorized)">
                {{ groupAllChecked(filteredUncategorized) ? '取消全选' : '全选' }}
              </el-button>
            </div>
            <div class="group-body">
              <div class="row-grid">
                <div v-for="o in filteredUncategorized" :key="o.id" class="row-item" :class="{ checked: isChecked(o) }" @click="toggleOne(o)">
                  <el-checkbox :model-value="isChecked(o)" @click.stop @change="toggleOne(o)" />
                  <div class="row-main">
                    <div class="row-name">{{ o.name }}</div>
                    <div class="row-meta">
                      <span class="status-badge" :style="{ color: statusConfigOf(o.status).color, background: statusConfigOf(o.status).bg }">{{ statusConfigOf(o.status).label }}</span>
                      <span class="meta-text">{{ sourceLabel(o) }}</span>
                      <span v-if="o.batchName" class="meta-text">批次：{{ o.batchName }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { portalRequest, buildQuery } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import { STATUS_OPTIONS, statusConfigOf } from './alliance-admin';
import type {
  AllianceEnterprise,
  GrantResourceOption,
  AllianceResourceGrant,
  ListResponse,
} from './alliance-admin';

type ResourceType = 'position' | 'scene';

interface BatchGroup {
  id: string;
  name: string;
  items: GrantResourceOption[];
}

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const enterprises = ref<AllianceEnterprise[]>([]);
const entLoading = ref(false);
const enterpriseId = ref('');
const activeType = ref<ResourceType>('position');
const checked = ref<Record<string, boolean>>({});
const saving = ref(false);

const search = ref('');
const statusFilter = ref('__all__');
const batchFilter = ref('__all__');
const collapsedBatches = ref<Set<string>>(new Set());

const options = ref<GrantResourceOption[]>([]);
const granted = ref<Set<string>>(new Set());
const optionsLoading = ref(false);

const currentEnterpriseId = computed(() => enterpriseId.value || enterprises.value[0]?.id || '');

const typeOptions = computed(() => options.value.filter((o) => o.type === activeType.value));

const batches = computed<BatchGroup[]>(() => {
  const map = new Map<string, { name: string; items: GrantResourceOption[] }>();
  typeOptions.value.forEach((o) => {
    if (!o.batchId || !o.batchName) return;
    if (!map.has(o.batchId)) map.set(o.batchId, { name: o.batchName, items: [] });
    map.get(o.batchId)!.items.push(o);
  });
  return [...map.entries()].map(([id, v]) => ({ id, ...v }));
});

const uncategorized = computed(() => typeOptions.value.filter((o) => !o.batchId || !o.batchName));

const filtered = computed(() => {
  const kw = search.value.trim().toLowerCase();
  return typeOptions.value.filter((o) => {
    if (kw && !o.name.toLowerCase().includes(kw)) return false;
    if (statusFilter.value !== '__all__' && o.status !== statusFilter.value) return false;
    if (batchFilter.value === '__all__') return true;
    if (batchFilter.value === '__none__') return !o.batchId || !o.batchName;
    return o.batchId === batchFilter.value;
  });
});

const filteredBatches = computed(() =>
  batches.value.filter((b) => filtered.value.some((o) => o.batchId === b.id)),
);

const filteredUncategorized = computed(() =>
  uncategorized.value.filter((o) => filtered.value.some((x) => x.id === o.id)),
);

function isChecked(o: GrantResourceOption): boolean {
  return checked.value[o.id] === undefined ? granted.value.has(o.id) : checked.value[o.id];
}

const allFilteredChecked = computed(
  () => filtered.value.length > 0 && filtered.value.every((o) => isChecked(o)),
);

const selectedCount = computed(() => typeOptions.value.filter((o) => isChecked(o)).length);

function groupAllChecked(items: GrantResourceOption[]): boolean {
  return items.length > 0 && items.every((o) => isChecked(o));
}

function sourceLabel(o: GrantResourceOption): string {
  if (o.source === 'school') return '本校自建';
  if (o.sourceEnterpriseId === currentEnterpriseId.value) return '该企业共建';
  return o.sourceEnterpriseName ? `${o.sourceEnterpriseName}共建` : '企业共建';
}

function toggleBatch(batchId: string) {
  const next = new Set(collapsedBatches.value);
  if (next.has(batchId)) next.delete(batchId);
  else next.add(batchId);
  collapsedBatches.value = next;
}

function toggleFilteredAll() {
  const next = { ...checked.value };
  filtered.value.forEach((o) => {
    next[o.id] = !allFilteredChecked.value;
  });
  checked.value = next;
}

function toggleGroupAll(items: GrantResourceOption[]) {
  const groupAll = groupAllChecked(items);
  const next = { ...checked.value };
  items.forEach((o) => {
    next[o.id] = !groupAll;
  });
  checked.value = next;
}

function toggleOne(o: GrantResourceOption) {
  checked.value = { ...checked.value, [o.id]: !isChecked(o) };
}

function resetFilters() {
  search.value = '';
  statusFilter.value = '__all__';
  batchFilter.value = '__all__';
}

async function loadEnterprises() {
  if (!tenantId.value) return;
  entLoading.value = true;
  try {
    const res = await portalRequest<ListResponse<AllianceEnterprise>>('/alliance/enterprises?limit=200');
    enterprises.value = res.items || [];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载企业失败');
  } finally {
    entLoading.value = false;
  }
}

async function loadOptions() {
  if (!tenantId.value || !currentEnterpriseId.value) {
    options.value = [];
    granted.value = new Set();
    return;
  }
  optionsLoading.value = true;
  try {
    const [optRes, grantRes] = await Promise.all([
      portalRequest<ListResponse<GrantResourceOption>>(
        `/alliance/grants/resource-options${buildQuery({ enterpriseId: currentEnterpriseId.value })}`,
      ),
      portalRequest<{ enterpriseId: string; grants: AllianceResourceGrant[] }>(
        `/alliance/grants${buildQuery({ enterpriseId: currentEnterpriseId.value })}`,
      ),
    ]);
    const grantedSet = new Set<string>();
    (grantRes.grants || []).forEach((g) => g.resourceIds.forEach((id) => grantedSet.add(id)));
    options.value = optRes.items || [];
    granted.value = grantedSet;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载资源失败');
  } finally {
    optionsLoading.value = false;
  }
}

function onSelectEnterprise() {
  checked.value = {};
  resetFilters();
  loadOptions();
}

async function saveCurrentType() {
  if (saving.value) return;
  saving.value = true;
  try {
    const ids = typeOptions.value.filter((o) => isChecked(o)).map((o) => o.id);
    await portalRequest('/alliance/grants', {
      method: 'PUT',
      body: JSON.stringify({
        enterpriseId: currentEnterpriseId.value,
        resourceType: activeType.value,
        resourceIds: ids,
      }),
    });
    ElMessage.success('授权已保存');
    checked.value = {};
    await loadOptions();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

onMounted(async () => {
  await loadEnterprises();
  await loadOptions();
});
</script>

<style scoped>
.list-page { padding: 16px; display: flex; flex-direction: column; gap: 16px; }
.page-head { margin-bottom: 4px; }
.page-title { font-size: 20px; font-weight: 600; }
.page-sub { margin-top: 4px; font-size: 13px; color: #909399; }
.card-header { display: flex; align-items: center; gap: 8px; }
.card-title { font-size: 14px; font-weight: 600; }
.card-sub { font-size: 12px; color: #909399; }
.grant-card { min-height: 200px; }
.filters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }
.action-bar { display: flex; align-items: center; gap: 8px; padding: 8px 0 12px; border-top: 1px solid #f1f5f9; }
.selected-count { font-size: 12px; color: #909399; }
.flex-1 { flex: 1; }
.groups { display: flex; flex-direction: column; gap: 12px; }
.group-card { border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden; }
.group-card.uncategorized { border-style: dashed; }
.group-head { display: flex; align-items: center; justify-content: space-between; padding: 10px 16px; background: #f8fafc; }
.group-head.clickable { cursor: pointer; }
.group-title { display: flex; align-items: center; gap: 8px; }
.group-name { font-weight: 600; color: #1f2937; }
.group-body { padding: 12px; }
.row-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
.row-item { display: flex; align-items: flex-start; gap: 8px; padding: 8px 10px; border: 1px solid #f1f5f9; border-radius: 8px; cursor: pointer; }
.row-item.checked { border-color: #b3d8ff; background: #f0f7ff; }
.row-main { min-width: 0; flex: 1; }
.row-name { font-size: 13px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.row-meta { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; margin-top: 2px; }
.status-badge { font-size: 11px; padding: 1px 6px; border-radius: 4px; }
.meta-text { font-size: 11px; color: #909399; }
@media (max-width: 768px) {
  .row-grid { grid-template-columns: 1fr; }
}
</style>

// apps/edu/app/portal/apps/alliance/permissions/page.tsx
'use client'

import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import {
  Loader2,
  Building2,
  Save,
  Briefcase,
  Workflow,
  Search,
  RotateCcw,
  ChevronDown,
  ChevronRight,
  CheckSquare,
  Square,
} from 'lucide-react'
import { Checkbox } from '@/components/ui/checkbox'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'
import {
  Tabs,
  TabsList,
  TabsTrigger,
} from '@/components/ui/tabs'
import { cn } from '@/lib/utils'
import { usePortalAuth } from '@/contexts/portal-auth-context'
import { allianceEnterpriseApi, allianceGrantApi } from '@/lib/api'
import { useToast, useAsync } from '@zhiyu/ui'
import { useT } from '@/lib/i18n/locale-provider'
import { getStatusConfig } from '@zhiyu/shared-types'
import type { AllianceGrantResourceOption } from '@/lib/api'
import type { AllianceEnterprise } from '@/lib/types'

type GrantOption = AllianceGrantResourceOption
type ResourceType = 'position' | 'scene'

const STATUS_OPTIONS = [
  { value: 'draft', label: '草稿' },
  { value: 'pending', label: '审批中' },
  { value: 'approved', label: '已通过' },
  { value: 'rejected', label: '已驳回' },
  { value: 'published', label: '已发布' },
  { value: 'archived', label: '已归档' },
]

export default function AlliancePermissionsPage() {
  const { tenantId, loading: authLoading } = usePortalAuth()
  const { toast } = useToast()
  const t = useT()

  const { data: enterprises, loading: entLoading } = useAsync(
    async () => {
      if (!tenantId) return []
      const res = await allianceEnterpriseApi.list({ limit: 200 })
      return res.items || []
    },
    { deps: [tenantId, authLoading], onError: () => true },
  )

  const [enterpriseId, setEnterpriseId] = useState('')
  const [activeType, setActiveType] = useState<ResourceType>('position')
  const [checked, setChecked] = useState<Record<string, boolean>>({})
  const [saving, setSaving] = useState(false)

  // 搜索与筛选（仅影响展示，不影响已勾选）
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('__all__')
  const [batchFilter, setBatchFilter] = useState('__all__')

  // 折叠的批次分组（默认全部展开，点击组头折叠）
  const [collapsedBatches, setCollapsedBatches] = useState<Set<string>>(new Set())

  // 未手动选择时默认选中第一个企业，保证页面不空数据
  const currentEnterpriseId = enterpriseId || enterprises?.[0]?.id || ''

  // 选中企业后加载：授权现状 + 资源候选
  const { data, refresh, loading: optionsLoading } = useAsync(
    async () => {
      if (!tenantId || !currentEnterpriseId)
        return { options: [] as GrantOption[], granted: new Set<string>() }
      const [optRes, grantRes] = await Promise.all([
        allianceGrantApi.resourceOptions(currentEnterpriseId),
        allianceGrantApi.list(currentEnterpriseId),
      ])
      const granted = new Set<string>()
      grantRes.grants.forEach((g) => g.resourceIds.forEach((id) => granted.add(id)))
      return { options: optRes.items || [], granted }
    },
    { deps: [tenantId, currentEnterpriseId, authLoading], onError: () => true },
  )

  const options = useMemo(() => data?.options ?? [], [data])
  const granted = useMemo(() => data?.granted ?? new Set<string>(), [data])

  const isChecked = (o: GrantOption) => (checked[o.id] === undefined ? granted.has(o.id) : checked[o.id])

  const typeOptions = useMemo(
    () => options.filter((o) => o.type === activeType),
    [options, activeType],
  )

  // 当前 tab 的批次分组（含未分类）
  const batches = useMemo(() => {
    const map = new Map<string, { name: string; items: GrantOption[] }>()
    typeOptions.forEach((o) => {
      if (!o.batchId || !o.batchName) return
      if (!map.has(o.batchId)) map.set(o.batchId, { name: o.batchName, items: [] })
      map.get(o.batchId)!.items.push(o)
    })
    return [...map.entries()].map(([id, v]) => ({ id, ...v }))
  }, [typeOptions])

  const uncategorized = useMemo(
    () => typeOptions.filter((o) => !o.batchId || !o.batchName),
    [typeOptions],
  )

  // 搜索/状态/批次筛选后的可见列表（用于全选范围）
  const filtered = useMemo(() => {
    const kw = search.trim().toLowerCase()
    return typeOptions.filter((o) => {
      if (kw && !o.name.toLowerCase().includes(kw)) return false
      if (statusFilter !== '__all__' && o.status !== statusFilter) return false
      if (batchFilter === '__all__') return true
      if (batchFilter === '__none__') return !o.batchId || !o.batchName
      return o.batchId === batchFilter
    })
  }, [typeOptions, search, statusFilter, batchFilter])

  const filteredBatches = useMemo(
    () => batches.filter((b) => filtered.some((o) => o.batchId === b.id)),
    [batches, filtered],
  )
  const filteredUncategorized = useMemo(
    () => uncategorized.filter((o) => filtered.some((x) => x.id === o.id)),
    [uncategorized, filtered],
  )

  const allFilteredChecked =
    filtered.length > 0 && filtered.every((o) => isChecked(o))

  const toggleBatch = (batchId: string) => {
    setCollapsedBatches((prev) => {
      const next = new Set(prev)
      next.has(batchId) ? next.delete(batchId) : next.add(batchId)
      return next
    })
  }

  const toggleFilteredAll = () => {
    setChecked((prev) => {
      const next = { ...prev }
      filtered.forEach((o) => {
        next[o.id] = !allFilteredChecked
      })
      return next
    })
  }

  const toggleGroupAll = (items: GrantOption[]) => {
    const groupAll = items.every((o) => isChecked(o))
    setChecked((prev) => {
      const next = { ...prev }
      items.forEach((o) => {
        next[o.id] = !groupAll
      })
      return next
    })
  }

  const toggleOne = (o: GrantOption) => {
    setChecked((prev) => ({ ...prev, [o.id]: !isChecked(o) }))
  }

  const selectEnterprise = (id: string) => {
    setEnterpriseId(id)
    setChecked({})
    setSearch('')
    setStatusFilter('__all__')
    setBatchFilter('__all__')
  }

  const saveCurrentType = async () => {
    if (saving) return
    setSaving(true)
    try {
      const ids = typeOptions.filter((o) => isChecked(o)).map((o) => o.id)
      await allianceGrantApi.save({
        enterpriseId: currentEnterpriseId,
        resourceType: activeType,
        resourceIds: ids,
      })
      toast({ title: t('授权已保存') })
      setChecked({})
      await refresh()
    } catch (e: any) {
      toast({ title: t('保存失败'), description: e.message, variant: 'destructive' })
    } finally {
      setSaving(false)
    }
  }

  const sourceLabel = (o: GrantOption) => {
    if (o.source === 'school') return t('本校自建')
    if (o.sourceEnterpriseId === currentEnterpriseId) return t('该企业共建')
    return o.sourceEnterpriseName ? t('{ent}共建', { ent: o.sourceEnterpriseName }) : t('企业共建')
  }

  const renderRow = (o: GrantOption) => {
    const st = getStatusConfig(o.status)
    const checkedFlag = isChecked(o)
    return (
      <label
        key={o.id}
        className={cn(
          'flex items-center gap-2.5 rounded-lg border px-3 py-2 cursor-pointer hover:bg-muted/40 transition-colors',
          checkedFlag ? 'border-primary/30 bg-primary/[0.03]' : 'border-slate-100',
        )}
      >
        <Checkbox checked={checkedFlag} onCheckedChange={() => toggleOne(o)} />
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium truncate">{o.name}</p>
          <div className="flex flex-wrap items-center gap-1.5 mt-0.5">
            <span
              className="text-[11px] px-1.5 py-px rounded"
              style={{ color: st.color, background: st.bg }}
            >
              {st.label}
            </span>
            <span className="text-[11px] text-muted-foreground">{sourceLabel(o)}</span>
            {o.batchName && (
              <span className="text-[11px] text-muted-foreground">
                {t('批次：{name}', { name: o.batchName })}
              </span>
            )}
          </div>
        </div>
      </label>
    )
  }

  const renderGroup = (items: GrantOption[], groupId: string | null, groupName: string) => {
    const isExpanded = groupId !== null && !collapsedBatches.has(groupId)
    const groupAll = items.length > 0 && items.every((o) => isChecked(o))
    const body = (
      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
        {items.map((o) => renderRow(o))}
      </div>
    )
    if (groupId === null) {
      return (
        <div className="overflow-hidden rounded-xl border border-dashed border-slate-300 bg-white">
          <div className="flex items-center justify-between px-4 py-3 bg-slate-50/80">
            <div className="flex items-center gap-2">
              <span className="font-medium text-gray-800">{groupName}</span>
              <Badge variant="secondary" className="text-xs">
                {items.length}
              </Badge>
            </div>
            <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => toggleGroupAll(items)}>
              {groupAll ? <CheckSquare className="h-3.5 w-3.5 mr-1" /> : <Square className="h-3.5 w-3.5 mr-1" />}
              {groupAll ? t('取消全选') : t('全选')}
            </Button>
          </div>
          <div className="p-3">{body}</div>
        </div>
      )
    }
    return (
      <Collapsible
        key={groupId}
        open={isExpanded}
        onOpenChange={() => toggleBatch(groupId)}
        className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"
      >
        <CollapsibleTrigger asChild>
          <div className="flex cursor-pointer items-center justify-between px-4 py-3 transition-colors hover:bg-slate-50">
            <div className="flex items-center gap-2">
              {isExpanded ? (
                <ChevronDown className="h-4 w-4 text-gray-400" />
              ) : (
                <ChevronRight className="h-4 w-4 text-gray-400" />
              )}
              <span className="font-medium text-gray-800">{groupName}</span>
              <Badge variant="secondary" className="text-xs">
                {items.length}
              </Badge>
            </div>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 text-xs"
              onClick={(e) => {
                e.stopPropagation()
                toggleGroupAll(items)
              }}
            >
              {groupAll ? <CheckSquare className="h-3.5 w-3.5 mr-1" /> : <Square className="h-3.5 w-3.5 mr-1" />}
              {groupAll ? t('取消全选') : t('全选')}
            </Button>
          </div>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="p-3 pt-0">{body}</div>
        </CollapsibleContent>
      </Collapsible>
    )
  }

  const selectedCount = typeOptions.filter((o) => isChecked(o)).length

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-foreground">{t('合作权限管理')}</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          {t(
            '为企业授予岗位/场景的编辑权限：授权后企业专家可登录企业服务台查看并编辑这些资源（编辑稿需学校审批后生效）。',
          )}
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-sm font-semibold">
            <Building2 className="h-4 w-4 text-primary" />
            {t('选择企业')}
          </CardTitle>
          <CardDescription className="text-xs">{t('仅可对本校已引入的企业授权')}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="max-w-md">
            <Select
              value={currentEnterpriseId}
              onValueChange={selectEnterprise}
              disabled={entLoading}
            >
              <SelectTrigger>
                <SelectValue placeholder={t('请选择企业')} />
              </SelectTrigger>
              <SelectContent>
                {(enterprises ?? []).map((e: AllianceEnterprise) => (
                  <SelectItem key={e.id} value={e.id}>
                    {e.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {currentEnterpriseId && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-sm font-semibold">
              <Save className="h-4 w-4 text-primary" />
              {t('资源授权')}
            </CardTitle>
            <CardDescription className="text-xs">
              {t(
                '展示本校全部岗位/场景（含各状态与批次分组），勾选即授权该企业编辑权限，保存按类型整组生效。',
              )}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Tabs
              value={activeType}
              onValueChange={(v) => setActiveType(v as ResourceType)}
            >
              <TabsList className="grid w-full max-w-xs grid-cols-2">
                <TabsTrigger value="position" className="w-full">
                  <Briefcase className="h-4 w-4 mr-1.5" />
                  {t('岗位')}
                </TabsTrigger>
                <TabsTrigger value="scene" className="w-full">
                  <Workflow className="h-4 w-4 mr-1.5" />
                  {t('场景')}
                </TabsTrigger>
              </TabsList>
            </Tabs>

            <div className="flex flex-wrap items-center gap-2">
              <div className="flex items-center gap-2 flex-1 min-w-[220px]">
                <Search className="h-4 w-4 text-slate-400 shrink-0" />
                <Input
                  placeholder={t('搜索{type}名称', { type: activeType === 'position' ? t('岗位') : t('场景') })}
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="h-9 text-sm flex-1"
                />
              </div>
              <Select value={batchFilter} onValueChange={(v) => setBatchFilter(v)}>
                <SelectTrigger className="h-9 text-sm w-44">
                  <SelectValue placeholder={t('按批次筛选')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__all__">{t('全部批次')}</SelectItem>
                  {batches.map((b) => (
                    <SelectItem key={b.id} value={b.id}>
                      {b.name}
                    </SelectItem>
                  ))}
                  {uncategorized.length > 0 && (
                    <SelectItem value="__none__">{t('未分类')}</SelectItem>
                  )}
                </SelectContent>
              </Select>
              <Select value={statusFilter} onValueChange={(v) => setStatusFilter(v)}>
                <SelectTrigger className="h-9 text-sm w-32">
                  <SelectValue placeholder={t('按状态筛选')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__all__">{t('全部状态')}</SelectItem>
                  {STATUS_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Button
                variant="outline"
                size="sm"
                className="h-9"
                onClick={() => {
                  setSearch('')
                  setStatusFilter('__all__')
                  setBatchFilter('__all__')
                }}
              >
                <RotateCcw className="mr-1 h-3.5 w-3.5" />
                {t('重置')}
              </Button>
            </div>

            <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-slate-100">
              <span className="text-xs text-muted-foreground mr-1">
                {t('已勾选 {count} 个{type}', {
                  count: selectedCount,
                  type: activeType === 'position' ? t('岗位') : t('场景'),
                })}
              </span>
              {filtered.length > 0 && (
                <Button variant="outline" size="sm" className="h-8 text-xs" onClick={toggleFilteredAll}>
                  {allFilteredChecked ? <CheckSquare className="h-3.5 w-3.5 mr-1" /> : <Square className="h-3.5 w-3.5 mr-1" />}
                  {allFilteredChecked ? t('取消当前筛选全选') : t('全选当前筛选')}
                </Button>
              )}
              <div className="flex-1" />
              <Button size="sm" disabled={saving} onClick={saveCurrentType}>
                {saving ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Save className="h-4 w-4 mr-1" />}
                {t('保存{type}授权', { type: activeType === 'position' ? t('岗位') : t('场景') })}
              </Button>
            </div>

            {optionsLoading ? (
              <div className="flex items-center justify-center py-16">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : filtered.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <Search className="h-10 w-10 mb-2 opacity-30" />
                <p className="text-sm">{t('当前筛选条件下暂无{type}', { type: activeType === 'position' ? t('岗位') : t('场景') })}</p>
              </div>
            ) : (
              <div className="space-y-3">
                {filteredBatches.map((b) => renderGroup(b.items, b.id, b.name))}
                {filteredUncategorized.length > 0 &&
                  renderGroup(filteredUncategorized, null, t('未分类'))}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  )
}
