// plus-ui/src-portal/views/library/knowledge.vue
<template>
  <div class="library-page">
    <CitationStatsPanel
      entity-label="知识点"
      dialog-title="零引用知识点"
      :stat-count="total"
      stat-label="知识点总数"
      :fetch-stats="fetchStats"
      :fetch-uncited="fetchUncited"
      :delete-item="deleteItem"
      @deleted="loadItems"
    />

    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <span class="card-title">知识点管理</span>
          <el-button type="primary" @click="openAdd">新建知识点</el-button>
        </div>
      </template>

      <div class="search-row">
        <el-input v-model="searchQuery" placeholder="搜索知识点..." clearable style="max-width: 320px" @input="onSearch" @clear="onSearch" />
        <el-button v-if="searchQuery" text type="danger" @click="clearSearch">清除</el-button>
      </div>

      <TagFilterBar :model-value="selectedTagIds" @update:model-value="onTagFilterChange" />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="名称" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.name }}</template>
        </el-table-column>
        <el-table-column label="编码" width="150">
          <template #default="{ row }">{{ row.code || '-' }}</template>
        </el-table-column>
        <el-table-column label="描述" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.description || '-' }}</template>
        </el-table-column>
        <el-table-column label="关联课程" width="100">
          <template #default="{ row }">{{ (row.granularLessonIds || []).length }} 门</template>
        </el-table-column>
        <el-table-column label="标签" min-width="140">
          <template #default="{ row }">
            <TagBadge v-for="t in tagsByResource[row.id] || []" :key="t.id" :tag="t" class="cell-tag" />
            <span v-if="!(tagsByResource[row.id] || []).length" class="muted">-</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openEdit(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="totalPages > 1"
        v-model:current-page="page"
        :page-size="PAGE_SIZE"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>

    <!-- 新增/编辑弹窗 -->
    <el-dialog v-model="dialogOpen" :title="dialogMode === 'add' ? '新增知识点' : '编辑知识点'" width="560px">
      <el-form :model="form" label-width="100px">
        <el-form-item label="知识点名称" required>
          <el-input v-model="form.name" placeholder="输入知识点名称" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="form.description" type="textarea" :rows="3" placeholder="输入知识点描述" />
        </el-form-item>
        <el-form-item label="编码">
          <el-input v-model="form.code" :disabled="dialogMode !== 'edit'" />
          <div class="hint">{{ dialogMode === 'edit' ? '可修改编码' : '系统自动生成，不可修改' }}</div>
        </el-form-item>
        <el-form-item label="标签">
          <TagPicker v-model="form.tagIds" />
        </el-form-item>
        <el-form-item label="关联颗粒课">
          <div class="gl-field">
            <div v-if="selectedGranularLessons.length" class="gl-selected">
              <el-tag
                v-for="gl in selectedGranularLessons"
                :key="gl.id"
                closable
                size="small"
                class="cell-tag"
                @close="removeGranularLesson(gl.id)"
              >
                {{ gl.name }}
              </el-tag>
            </div>
            <div class="gl-btns">
              <el-button size="small" @click="glSelectOpen = true">选择颗粒课</el-button>
              <el-button size="small" @click="onCreateGranularLesson">新建颗粒课</el-button>
            </div>
          </div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogOpen = false">取消</el-button>
        <el-button type="primary" :loading="submitting" :disabled="!form.name.trim()" @click="submit">
          {{ dialogMode === 'add' ? '新增并选中' : '保存修改' }}
        </el-button>
      </template>
    </el-dialog>

    <GranularLessonSelectDialog
      v-model="glSelectOpen"
      :granular-courses="granularCourses"
      :selected-ids="form.granularLessonIds"
      @update:selected-ids="onGranularSelect"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request, buildQuery } from '@/api/http';
import type { ListResponse } from '@/api/http';
import { knowledgeApi, courseApi } from '@/api/lesson';
import type { KnowledgePoint } from '@/types/lesson';
import CitationStatsPanel from './_components/CitationStatsPanel.vue';
import TagFilterBar from './_components/TagFilterBar.vue';
import TagPicker from './_components/TagPicker.vue';
import TagBadge from './_components/TagBadge.vue';
import GranularLessonSelectDialog from './_components/GranularLessonSelectDialog.vue';
import { useLibraryCrud } from './_components/useLibraryCrud';
import { useTagBindings } from './_components/useTagBindings';
import type { CitationStats, UncitedItem, GranularLessonOption } from './_components/types';

const router = useRouter();
const PAGE_SIZE = 200;
const TAG_RESOURCE_TYPE = 'knowledge_point';
const GRANULAR_PAGE_SIZE = 200;

const selectedTagIds = ref<string[]>([]);
const { tagsByResource, loadBindings, saveTags } = useTagBindings(TAG_RESOURCE_TYPE);

const { items, loading, searchQuery, loadItems, total, page, totalPages } = useLibraryCrud<KnowledgePoint>(
  knowledgeApi.list,
  { getParams: () => (selectedTagIds.value.length ? { tagIds: selectedTagIds.value.join(',') } : {}) }
);

const dialogOpen = ref(false);
const editingItem = ref<KnowledgePoint | null>(null);
const dialogMode = ref<'add' | 'edit'>('add');
const linked = ref(false);
const submitting = ref(false);
const granularCourses = ref<GranularLessonOption[]>([]);
const glSelectOpen = ref(false);
const form = reactive({ name: '', description: '', code: '', granularLessonIds: [] as string[], tagIds: [] as string[] });

const selectedGranularLessons = computed(() =>
  granularCourses.value.filter((g) => form.granularLessonIds.includes(g.id))
);

function generateKpCode(): string {
  // 追加随机段，避免同毫秒/跨时段尾数碰撞导致 code 唯一约束冲突
  return `KP-${Date.now().toString().slice(-6)}${Math.random().toString(36).slice(2, 6)}`;
}

async function loadGranularCourses(): Promise<void> {
  try {
    const all: GranularLessonOption[] = [];
    for (let p = 0; p < 1000; p++) {
      const res = await courseApi.list({ type: 'granular', limit: GRANULAR_PAGE_SIZE, offset: p * GRANULAR_PAGE_SIZE });
      const its = res.items || [];
      all.push(...its.map((c) => ({ id: c.id, name: c.name, code: c.code, description: c.description || undefined })));
      if (its.length < GRANULAR_PAGE_SIZE) break;
    }
    granularCourses.value = all;
  } catch {
    granularCourses.value = [];
  }
}

function onSearch(): void {
  page.value = 1;
  void loadItems();
}

function clearSearch(): void {
  searchQuery.value = '';
  page.value = 1;
  void loadItems();
}

function onTagFilterChange(ids: string[]): void {
  selectedTagIds.value = ids;
  page.value = 1;
  void loadItems();
}

function openAdd(): void {
  editingItem.value = null;
  dialogMode.value = 'add';
  linked.value = false;
  form.name = '';
  form.description = '';
  form.code = generateKpCode();
  form.granularLessonIds = [];
  form.tagIds = [];
  dialogOpen.value = true;
}

function openEdit(item: KnowledgePoint): void {
  editingItem.value = item;
  dialogMode.value = 'edit';
  linked.value = item.linked;
  form.name = item.name;
  form.description = item.description || '';
  form.code = item.code || '';
  form.granularLessonIds = [...(item.granularLessonIds || [])];
  form.tagIds = (tagsByResource.value[item.id] || []).map((t) => t.id);
  dialogOpen.value = true;
}

function removeGranularLesson(id: string): void {
  form.granularLessonIds = form.granularLessonIds.filter((x) => x !== id);
}

function onGranularSelect(v: string[]): void {
  form.granularLessonIds = v;
}

async function submit(): Promise<void> {
  if (!form.name.trim()) {
    ElMessage.warning('名称不能为空');
    return;
  }
  submitting.value = true;
  try {
    const payload = {
      name: form.name.trim(),
      code: form.code.trim() || undefined,
      description: form.description.trim() || undefined,
      linked: linked.value,
      granularLessonIds: form.granularLessonIds
    };
    let savedId: string;
    if (editingItem.value) {
      savedId = editingItem.value.id;
      await knowledgeApi.update(editingItem.value.id, payload);
      ElMessage.success('更新成功');
    } else {
      const created = await knowledgeApi.create(payload);
      savedId = created.id;
      ElMessage.success('创建成功');
    }
    try {
      await saveTags(savedId, form.tagIds);
    } catch {
      ElMessage.warning('标签保存失败：实体已保存，标签未关联，可再次保存重试');
    }
    dialogOpen.value = false;
    void loadItems();
    void loadGranularCourses();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    submitting.value = false;
  }
}

async function confirmDelete(item: KnowledgePoint): Promise<void> {
  try {
    await ElMessageBox.confirm('确定要删除该知识点吗？此操作不可恢复。', '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消'
    });
  } catch {
    return;
  }
  try {
    await knowledgeApi.delete(item.id);
    ElMessage.success('删除成功');
    void loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

async function onCreateGranularLesson(): Promise<void> {
  const newId = await handleCreateGranularLesson();
  if (newId && !form.granularLessonIds.includes(newId)) {
    form.granularLessonIds = [...form.granularLessonIds, newId];
  }
}

async function handleCreateGranularLesson(): Promise<string | undefined> {
  const baseName = editingItem.value?.name || '新建颗粒课';
  try {
    const created = await courseApi.create({
      name: `基于「${baseName}」的颗粒课`,
      type: 'granular',
      category: '专业基础'
    });
    granularCourses.value = [
      ...granularCourses.value,
      { id: created.id, name: created.name, code: created.code, description: created.description || undefined }
    ];
    if (editingItem.value) {
      await knowledgeApi.update(editingItem.value.id, {
        name: editingItem.value.name,
        code: editingItem.value.code || undefined,
        description: editingItem.value.description || undefined,
        linked: editingItem.value.linked,
        granularLessonIds: [...(editingItem.value.granularLessonIds || []), created.id]
      });
      void loadItems();
    }
    void promptNavigate(created.id);
    return created.id;
  } catch (e) {
    ElMessage.error((e as Error).message || '创建颗粒课失败');
    return undefined;
  }
}

async function promptNavigate(id: string): Promise<void> {
  try {
    await ElMessageBox.confirm('占位颗粒课已创建并关联，是否立即前往完善？', '前往完善', {
      confirmButtonText: '前往',
      cancelButtonText: '取消',
      type: 'info'
    });
    const href = router.resolve({ name: 'LessonGranularAdd', query: { id } }).href;
    window.open(href, '_blank', 'noopener,noreferrer');
  } catch {
    /* 取消前往 */
  }
}

// 引用统计 / 零引用列表：Vue api/lesson.ts 未提供，直连 React 同款后端端点
async function fetchStats(): Promise<CitationStats> {
  return request<CitationStats>('/lesson/knowledge-points/citation-stats');
}

async function fetchUncited(params: {
  startDate?: string;
  endDate?: string;
  limit: number;
  offset: number;
}): Promise<ListResponse<UncitedItem>> {
  return request<ListResponse<UncitedItem>>(`/lesson/knowledge-points/uncited${buildQuery(params)}`);
}

async function deleteItem(id: string): Promise<unknown> {
  return knowledgeApi.delete(id);
}

watch(items, (v) => {
  if (v.length) void loadBindings(v);
});

onMounted(() => {
  void loadItems();
  void loadGranularCourses();
});
</script>

<style scoped>
.library-page {
  padding: 16px;
}
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.card-title {
  font-size: 16px;
  font-weight: 600;
}
.search-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}
.cell-tag {
  margin-right: 4px;
}
.muted {
  color: #cbd5e1;
  font-size: 12px;
}
.pagination {
  margin-top: 16px;
  justify-content: flex-end;
}
.hint {
  font-size: 12px;
  color: #94a3b8;
  line-height: 1.5;
}
.gl-field {
  width: 100%;
}
.gl-selected {
  margin-bottom: 8px;
}
.gl-btns {
  display: flex;
  gap: 8px;
}
</style>

// apps/edu/app/library/knowledge/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { Pencil, Trash2, BookOpen } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { TableRow, TableHead, TableCell } from '@/components/ui/table'
import { knowledgeApi, courseApi } from '@/lib/api'
import { fetchAllPages } from '@/lib/fetch-all'
import type { KnowledgePoint } from '@/lib/types/lesson'
import { useToast } from '@zhiyu/ui'
import { ConfirmDialog } from '@/components/shared/confirm-dialog'
import { TagBadge } from '@/components/shared/tag-badge'
import { TagFilterBar } from '@/components/shared/tag-filter-bar'
import { useTagBindings } from '@/components/shared/use-tag-bindings'
import { TAG_RESOURCE_TYPES } from '@/lib/types/library'
import { LibraryPageShell } from '../_components/library-page-shell'
import { CitationStatsPanel } from '@/components/shared/citation-stats-panel'
import {
  KnowledgePointFormDialog,
  type KnowledgePointFormValues,
} from './_components/knowledge-point-form-dialog'
import type { GranularLessonOption } from './_components/granular-lesson-select-dialog'
import { useLibraryCrud } from '../_components/use-library-crud'
import { useT } from '@/lib/i18n/locale-provider'

export default function KnowledgePointsPage() {
  const t = useT()
  const { toast } = useToast()
  const [selectedTagIds, setSelectedTagIds] = useState<string[]>([])
  const { tagsByResource, loadBindings, saveTags } = useTagBindings(
    TAG_RESOURCE_TYPES.knowledge_point,
  )
  const {
    items,
    loading,
    searchQuery,
    setSearchQuery,
    loadItems,
    total,
    page,
    setPage,
    totalPages,
  } = useLibraryCrud(knowledgeApi.list, {
    autoLoad: false,
    getParams: () =>
      selectedTagIds.length ? { tagIds: selectedTagIds.join(',') } : {},
  })
  useEffect(() => {
    void loadItems()
  }, [loadItems])
  useEffect(() => {
    if (items.length) void loadBindings(items)
  }, [items, loadBindings])
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<KnowledgePoint | null>(null)
  const [dialogMode, setDialogMode] = useState<'add' | 'edit'>('add')
  const [linked, setLinked] = useState(false)
  const [granularCourses, setGranularCourses] = useState<GranularLessonOption[]>([])
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null)
  const [navigateCourseId, setNavigateCourseId] = useState<string | null>(null)

  const loadGranularCourses = async () => {
    try {
      const res = await fetchAllPages((page, pageSize) => courseApi.list({ type: 'granular', limit: pageSize, offset: page * pageSize }))
      setGranularCourses(
        res.map((c) => ({
          id: c.id,
          name: c.name,
          code: c.code,
          description: c.description || undefined,
        })),
      )
    } catch {
      setGranularCourses([])
    }
  }

  useEffect(() => {
    ;(async () => {
      await loadGranularCourses()
    })()
  }, [])

  const handleOpenAdd = () => {
    setEditingItem(null)
    setDialogMode('add')
    setLinked(false)
    setIsDialogOpen(true)
  }
  const handleOpenEdit = (item: KnowledgePoint) => {
    setEditingItem(item)
    setDialogMode('edit')
    setLinked(item.linked)
    setIsDialogOpen(true)
  }
  const handleTagFilterChange = (tagIds: string[]) => {
    setSelectedTagIds(tagIds)
    setPage(1)
  }
  const confirmDelete = async () => {
    if (!deleteTarget) return
    try {
      await knowledgeApi.delete(deleteTarget)
      toast({ title: t('删除成功') })
      loadItems()
    } catch (err: any) {
      toast({ variant: 'destructive', title: t('删除失败'), description: err.message })
    } finally {
      setDeleteTarget(null)
    }
  }

  const handleSave = async (values: KnowledgePointFormValues) => {
    try {
      let savedId: string
      if (editingItem) {
        savedId = editingItem.id
        await knowledgeApi.update(editingItem.id, {
          name: values.name,
          code: values.code || undefined,
          description: values.description || undefined,
          linked,
          granularLessonIds: values.granularLessonIds,
        } as any)
        toast({ title: t('更新成功') })
      } else {
        const created = await knowledgeApi.create({
          name: values.name,
          code: values.code || undefined,
          description: values.description || undefined,
          linked,
          granularLessonIds: values.granularLessonIds,
        } as any)
        savedId = created.id
        toast({ title: t('创建成功') })
      }
      try {
        await saveTags(savedId, values.tagIds)
      } catch {
        toast({ variant: 'destructive', title: t('标签保存失败'), description: t('实体已保存，标签未关联，可再次保存重试') })
      }
      setIsDialogOpen(false)
      loadItems()
      loadGranularCourses()
    } catch (err: any) {
      toast({ variant: 'destructive', title: t('保存失败'), description: err.message })
    }
  }

  const handleCreateGranularLesson = async (): Promise<string | undefined> => {
    const baseName = editingItem?.name || t('新建颗粒课')
    try {
      const created = await courseApi.create({
        name: t('基于「{name}」的颗粒课', { name: baseName }),
        type: 'granular',
        category: t('专业基础'),
      } as any)
      setGranularCourses((prev) => [
        ...prev,
        {
          id: created.id,
          name: created.name,
          code: created.code,
          description: created.description || undefined,
        },
      ])
      if (editingItem) {
        await knowledgeApi.update(editingItem.id, {
          name: editingItem.name,
          code: editingItem.code || undefined,
          description: editingItem.description || undefined,
          linked: editingItem.linked,
          granularLessonIds: [...(editingItem.granularLessonIds || []), created.id],
        } as any)
        loadItems()
      }
      setNavigateCourseId(created.id)
      return created.id
    } catch (err: any) {
      toast({ variant: 'destructive', title: t('创建颗粒课失败'), description: err.message })
      return undefined
    }
  }

  return (
    <>
      <LibraryPageShell
        title={t('知识点管理')}
        statLabel={t('知识点总数')}
        statIcon={
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
            <BookOpen className="size-5 text-primary" />
          </div>
        }
        statGradient="from-primary/5 to-primary/10"
        statCount={total}
        statsExtra={
          <CitationStatsPanel
            entityLabel={t('知识点')}
            dialogTitle={t('零引用知识点')}
            fetchStats={() => knowledgeApi.citationStats()}
            fetchUncited={(params) => knowledgeApi.uncited(params)}
            deleteItem={(id) => knowledgeApi.delete(id)}
            onDeleted={loadItems}
            statCount={total}
            statLabel={t('知识点总数')}
            statIcon={<BookOpen className="size-5 text-primary" />}
          />
        }
        searchPlaceholder={t('搜索知识点...')}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        onAdd={handleOpenAdd}
        addLabel={t('新建知识点')}
        loading={loading}
        items={items}
        deleteTarget={deleteTarget}
        onDeleteCancel={() => setDeleteTarget(null)}
        onDeleteConfirm={confirmDelete}
        deleteLabel={t('知识点')}
        tableHeaders={
          <>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">
              {t('名称')}
            </TableHead>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">
              {t('编码')}
            </TableHead>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden md:table-cell">
              {t('描述')}
            </TableHead>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden md:table-cell">
              {t('关联课程')}
            </TableHead>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden lg:table-cell">
              {t('标签')}
            </TableHead>
            <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">
              {t('操作')}
            </TableHead>
          </>
        }
        tableBody={(item) => (
          <TableRow key={item.id} className="hover:bg-slate-50/50">
            <TableCell className="p-3">
              <div className="flex items-center gap-2">
                <BookOpen className="size-4 text-primary" />
                <span className="text-sm font-medium text-slate-700">{item.name}</span>
              </div>
            </TableCell>
            <TableCell className="p-3 text-sm text-slate-400">{item.code || '-'}</TableCell>
            <TableCell className="p-3 text-sm text-slate-400 hidden md:table-cell max-w-[300px] truncate">
              {item.description || '-'}
            </TableCell>
            <TableCell className="p-3 text-sm text-slate-400 hidden md:table-cell">
              {t('{n} 门', { n: item.granularLessonIds?.length || 0 })}
            </TableCell>
            <TableCell className="p-3 hidden lg:table-cell">
              <div className="flex flex-wrap gap-1.5">
                {(tagsByResource[item.id] || []).map((tag) => (
                  <TagBadge key={tag.id} tag={tag} />
                ))}
                {(tagsByResource[item.id] || []).length === 0 && (
                  <span className="text-xs text-slate-300">-</span>
                )}
              </div>
            </TableCell>
            <TableCell className="p-3 text-right whitespace-nowrap">
              <Button variant="ghost" size="sm" onClick={() => handleOpenEdit(item)}>
                <Pencil className="size-4" />
              </Button>
              <Button variant="ghost" size="sm" onClick={() => setDeleteTarget(item.id)}>
                <Trash2 className="size-4 text-destructive" />
              </Button>
            </TableCell>
          </TableRow>
        )}
        dialog={<></>}
        pagination={{ page, totalPages, onPageChange: setPage }}
      >
        <TagFilterBar value={selectedTagIds} onChange={handleTagFilterChange} className="mb-4" />
      </LibraryPageShell>
      <ConfirmDialog
        open={navigateCourseId !== null}
        onOpenChange={(open) => {
          if (!open) setNavigateCourseId(null)
        }}
        title={t('前往完善')}
        description={t('占位颗粒课已创建并关联，是否立即前往完善？')}
        confirmText={t('前往')}
        onConfirm={() => {
          if (navigateCourseId) {
            window.open(`/lesson/admin/granular/add?id=${navigateCourseId}`, '_blank')
            setNavigateCourseId(null)
          }
        }}
      />
      <KnowledgePointFormDialog
        open={isDialogOpen}
        onOpenChange={setIsDialogOpen}
        mode={dialogMode}
        initialValues={
          editingItem
            ? {
                name: editingItem.name,
                description: editingItem.description || '',
                code: editingItem.code || '',
                granularLessonIds: editingItem.granularLessonIds || [],
                tagIds: (tagsByResource[editingItem.id] || []).map((t) => t.id),
              }
            : undefined
        }
        granularCourses={granularCourses}
        onSave={handleSave}
        onCreateGranularLesson={handleCreateGranularLesson}
      />
    </>
  )
}
