// frontend/portal-vue/src/views/library/questions.vue
<template>
  <div class="questions-page">
    <div class="stat-card">
      <div class="stat-count">{{ total }}</div>
      <div class="stat-label">题目总数</div>
    </div>

    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <span class="card-title">现场问答题库</span>
          <el-button type="primary" @click="openDialog()">新建现场问答题</el-button>
        </div>
      </template>

      <div class="search-row">
        <el-input v-model="searchQuery" placeholder="搜索题目名称..." clearable style="max-width: 320px" @input="onSearch" @clear="onSearch" />
        <el-button v-if="searchQuery" text type="danger" @click="clearSearch">清除</el-button>
      </div>

      <TagFilterBar :model-value="selectedTagIds" @update:model-value="onTagFilterChange" />

      <el-table v-loading="loading" :data="items" stripe>
        <el-table-column label="题目名称" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.name }}</template>
        </el-table-column>
        <el-table-column label="题目描述" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.description || '-' }}</template>
        </el-table-column>
        <el-table-column label="适用专业" width="150">
          <template #default="{ row }">
            <el-tag size="small">{{ row.majorName || majorNameMap[row.majorId] || '-' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="标签" min-width="140">
          <template #default="{ row }">
            <TagBadge v-for="t in tagsByResource[row.id] || []" :key="t.id" :tag="t" class="cell-tag" />
            <span v-if="!(tagsByResource[row.id] || []).length" class="muted">-</span>
          </template>
        </el-table-column>
        <el-table-column label="答案" min-width="180" show-overflow-tooltip>
          <template #default="{ row }">{{ row.answer || '-' }}</template>
        </el-table-column>
        <el-table-column label="操作" width="140" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openDialog(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-if="totalPages > 1"
        v-model:current-page="page"
        :page-size="PAGE_SIZE"
        :total="total"
        layout="prev, pager, next, total"
        class="pagination"
        @current-change="loadItems"
      />
    </el-card>

    <el-dialog v-model="dialog" :title="editing ? '编辑现场问答题' : '新增现场问答题'" width="560px">
      <el-form label-width="100px">
        <el-form-item label="题目名称" required>
          <el-input v-model="form.name" placeholder="输入题目名称" />
        </el-form-item>
        <el-form-item label="适用专业">
          <el-select v-model="form.majorId" clearable placeholder="选择适用专业" style="width: 100%">
            <el-option v-for="m in majors" :key="m.id" :label="m.name" :value="m.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="题目描述">
          <el-input v-model="form.description" type="textarea" :rows="3" placeholder="输入题目描述" />
        </el-form-item>
        <el-form-item label="题目答案">
          <el-input v-model="form.answer" type="textarea" :rows="3" placeholder="输入题目答案" />
        </el-form-item>
        <el-form-item label="标签">
          <TagPicker v-model="form.tagIds" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" :disabled="!form.name.trim()" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { createCrudApi } from '@/api/http';
import { majorApi } from '@/api/system';
import TagFilterBar from './_components/TagFilterBar.vue';
import TagPicker from './_components/TagPicker.vue';
import TagBadge from './_components/TagBadge.vue';
import { useLibraryCrud } from './_components/useLibraryCrud';
import { useTagBindings } from './_components/useTagBindings';

// 现场问答题库（后端为 /evaluation/random-draw-questions，React 侧 randomDrawQuestionApi）
interface RandomDrawQuestion {
  id: string;
  name: string;
  description?: string;
  answer?: string;
  majorId?: string;
  majorName?: string;
  createdAt: string;
  updatedAt: string;
}

const PAGE_SIZE = 200;
const TAG_RESOURCE_TYPE = 'random_draw_question';

const randomDrawQuestionApi = createCrudApi<
  RandomDrawQuestion,
  Partial<Omit<RandomDrawQuestion, 'id' | 'createdAt' | 'updatedAt'>>,
  Partial<Omit<RandomDrawQuestion, 'id' | 'createdAt' | 'updatedAt'>>
>('/evaluation/random-draw-questions');

const selectedTagIds = ref<string[]>([]);
const { tagsByResource, loadBindings, saveTags } = useTagBindings(TAG_RESOURCE_TYPE);

const { items, loading, searchQuery, loadItems, total, page, totalPages } = useLibraryCrud<RandomDrawQuestion>(
  randomDrawQuestionApi.list,
  { getParams: () => (selectedTagIds.value.length ? { tagIds: selectedTagIds.value.join(',') } : {}) }
);

const dialog = ref(false);
const saving = ref(false);
const editing = ref<RandomDrawQuestion | null>(null);
const majors = ref<{ id: string; name: string }[]>([]);
const form = reactive({ name: '', description: '', answer: '', majorId: '', tagIds: [] as string[] });

const majorNameMap = computed<Record<string, string>>(() => {
  const map: Record<string, string> = {};
  for (const m of majors.value) map[m.id] = m.name;
  return map;
});

async function loadMajors(): Promise<void> {
  try {
    // 专业列表分页全量拉取，避免超过后端分页上限时姓名/专业缺失
    const all: { id: string; name: string }[] = [];
    for (let p = 0; p < 1000; p++) {
      const res = await majorApi.list({ limit: 200, offset: p * 200 });
      const its = res.items || [];
      all.push(...its.map((m) => ({ id: m.id, name: m.name })));
      if (its.length < 200) break;
    }
    majors.value = all;
  } catch {
    /* ignore */
  }
}

function onSearch(): void {
  page.value = 1;
  void loadItems();
}

function clearSearch(): void {
  searchQuery.value = '';
  page.value = 1;
  void loadItems();
}

function onTagFilterChange(ids: string[]): void {
  selectedTagIds.value = ids;
  page.value = 1;
  void loadItems();
}

function openDialog(row?: RandomDrawQuestion): void {
  editing.value = row || null;
  form.name = row?.name || '';
  form.description = row?.description || '';
  form.answer = row?.answer || '';
  form.majorId = row?.majorId || '';
  form.tagIds = row ? (tagsByResource.value[row.id] || []).map((t) => t.id) : [];
  dialog.value = true;
}

async function save(): Promise<void> {
  if (!form.name.trim()) {
    ElMessage.warning('题目名称不能为空');
    return;
  }
  saving.value = true;
  try {
    const payload = {
      name: form.name.trim(),
      description: form.description.trim() || undefined,
      answer: form.answer.trim() || undefined,
      majorId: form.majorId || undefined
    };
    let savedId: string;
    if (editing.value) {
      savedId = editing.value.id;
      await randomDrawQuestionApi.update(editing.value.id, payload);
      ElMessage.success('更新成功');
    } else {
      const created = await randomDrawQuestionApi.create(payload);
      savedId = created.id;
      ElMessage.success('创建成功');
    }
    try {
      await saveTags(savedId, form.tagIds);
    } catch {
      ElMessage.warning('标签保存失败：实体已保存，标签未关联，可再次保存重试');
    }
    dialog.value = false;
    void loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function confirmDelete(row: RandomDrawQuestion): Promise<void> {
  try {
    await ElMessageBox.confirm('确定要删除该现场问答题吗？此操作不可恢复。', '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消'
    });
  } catch {
    return;
  }
  try {
    await randomDrawQuestionApi.delete(row.id);
    ElMessage.success('删除成功');
    void loadItems();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

watch(items, (v) => {
  if (v.length) void loadBindings(v);
});

onMounted(() => {
  void loadItems();
  void loadMajors();
});
</script>

<style scoped>
.questions-page {
  padding: 16px;
}
.stat-card {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px;
  margin-bottom: 16px;
  border-radius: 12px;
  background: linear-gradient(135deg, #eef2ff, #f5f7ff);
}
.stat-count {
  font-size: 24px;
  font-weight: 700;
  color: #303133;
}
.stat-label {
  font-size: 12px;
  color: #94a3b8;
}
.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.card-title {
  font-size: 16px;
  font-weight: 600;
}
.search-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}
.cell-tag {
  margin-right: 4px;
}
.muted {
  color: #cbd5e1;
  font-size: 12px;
}
.pagination {
  margin-top: 16px;
  justify-content: flex-end;
}
</style>

// apps/edu/app/library/questions/page.tsx
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Pencil, Trash2, MessageSquare } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { FormFieldRow } from '@/components/shared/form-field-row'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { TableHead, TableCell, TableRow } from '@/components/ui/table'
import { randomDrawQuestionApi, majorApi } from '@/lib/api'
import { useToast, FormDialogFooter } from '@zhiyu/ui'
import { TagBadge } from '@/components/shared/tag-badge'
import { TagFilterBar } from '@/components/shared/tag-filter-bar'
import { TagPicker } from '@/components/shared/tag-picker'
import { useTagBindings } from '@/components/shared/use-tag-bindings'
import { TAG_RESOURCE_TYPES } from '@/lib/types/library'
import { useLibraryCrud } from '../_components/use-library-crud'
import { LibraryPageShell } from '../_components/library-page-shell'
import { useT } from '@/lib/i18n/locale-provider'

export default function QuestionsPage() {
  const t = useT()
  const { toast } = useToast()
  const [selectedTagIds, setSelectedTagIds] = useState<string[]>([])
  const { tagsByResource, loadBindings, saveTags } = useTagBindings(
    TAG_RESOURCE_TYPES.random_draw_question,
  )

  const {
    items,
    loading,
    searchQuery,
    setSearchQuery,
    loadItems,
    page,
    setPage,
    totalPages,
    total,
  } = useLibraryCrud(randomDrawQuestionApi.list, {
    limit: 200,
    autoLoad: false,
    getParams: () =>
      selectedTagIds.length ? { tagIds: selectedTagIds.join(',') } : {},
  })
  useEffect(() => {
    void loadItems()
  }, [loadItems])
  useEffect(() => {
    if (items.length) void loadBindings(items)
  }, [items, loadBindings])
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState<any | null>(null)
  const [name, setName] = useState('')
  const [desc, setDesc] = useState('')
  const [answer, setAnswer] = useState('')
  const [majorId, setMajorId] = useState('')
  const [tagIds, setTagIds] = useState<string[]>([])
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null)
  const [majors, setMajors] = useState<any[]>([])
  const majorNameMap = useMemo(() => {
    const map: Record<string, string> = {}
    majors.forEach((m: any) => {
      map[m.id] = m.name
    })
    return map
  }, [majors])

  const loadMajors = useCallback(async () => {
    try {
      const res = await majorApi.list({ limit: 1000 })
      setMajors((res.items || []).map((m: any) => ({ id: m.id, name: m.name })))
    } catch {
      /* ignore */
    }
  }, [])

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- 首次加载数据需要同步 setState
    loadMajors()
  }, [loadMajors])

  const handleAdd = () => {
    setEditing(null)
    setName('')
    setDesc('')
    setAnswer('')
    setMajorId('')
    setTagIds([])
    setDialogOpen(true)
  }
  const handleEdit = (item: any) => {
    setEditing(item)
    setName(item.name)
    setDesc(item.description || '')
    setAnswer(item.answer || '')
    setMajorId(item.majorId || '')
    setTagIds((tagsByResource[item.id] || []).map((t) => t.id))
    setDialogOpen(true)
  }
  const handleTagFilterChange = (ids: string[]) => {
    setSelectedTagIds(ids)
    setPage(1)
  }
  const confirmDelete = async () => {
    if (!deleteTarget) return
    try {
      await randomDrawQuestionApi.delete(deleteTarget)
      toast({ title: t('删除成功') })
      loadItems()
    } catch (err: any) {
      toast({ variant: 'destructive', title: t('删除失败'), description: err.message })
    } finally {
      setDeleteTarget(null)
    }
  }
  const handleSubmit = async () => {
    if (!name.trim()) {
      toast({ variant: 'destructive', title: t('题目名称不能为空') })
      return
    }
    try {
      const payload = {
        name: name.trim(),
        description: desc.trim() || undefined,
        answer: answer.trim() || undefined,
        majorId: majorId || undefined,
      }
      if (editing) {
        await randomDrawQuestionApi.update(editing.id, payload as any)
        toast({ title: t('更新成功') })
        try {
          await saveTags(editing.id, tagIds)
        } catch {
          toast({ variant: 'destructive', title: t('标签保存失败'), description: t('实体已保存，标签未关联，可再次保存重试') })
        }
      } else {
        const created = await randomDrawQuestionApi.create(payload as any)
        toast({ title: t('创建成功') })
        try {
          await saveTags(created.id, tagIds)
        } catch {
          toast({ variant: 'destructive', title: t('标签保存失败'), description: t('实体已保存，标签未关联，可再次保存重试') })
        }
      }
      setDialogOpen(false)
      loadItems()
    } catch (err: any) {
      toast({ variant: 'destructive', title: t('保存失败'), description: err.message })
    }
  }

  return (
    <LibraryPageShell
      title={t('现场问答题库')}
      statLabel={t('题目总数')}
      statIcon={
        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
          <MessageSquare className="size-5 text-primary" />
        </div>
      }
      statGradient="from-primary/5 to-primary/10"
      statCount={total}
      searchPlaceholder={t('搜索题目名称...')}
      searchQuery={searchQuery}
      onSearchChange={setSearchQuery}
      onAdd={handleAdd}
      addLabel={t('新建现场问答题')}
      loading={loading}
      items={items}
      deleteTarget={deleteTarget}
      onDeleteCancel={() => setDeleteTarget(null)}
      onDeleteConfirm={confirmDelete}
      deleteLabel={t('现场问答题')}
      tableHeaders={
        <>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">
            {t('题目名称')}
          </TableHead>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">
            {t('题目描述')}
          </TableHead>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden md:table-cell">
            {t('适用专业')}
          </TableHead>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden md:table-cell">
            {t('标签')}
          </TableHead>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider hidden md:table-cell">
            {t('答案')}
          </TableHead>
          <TableHead className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">
            {t('操作')}
          </TableHead>
        </>
      }
      tableBody={(item: any) => (
        <TableRow key={item.id} className="hover:bg-slate-50/50">
          <TableCell className="p-3">
            <span className="text-sm font-medium text-slate-700">{item.name}</span>
          </TableCell>
          <TableCell className="p-3">
            <span className="text-xs text-slate-500 line-clamp-2">{item.description || '-'}</span>
          </TableCell>
          <TableCell className="p-3 hidden md:table-cell">
            <Badge variant="secondary" className="text-xs">
              {item.majorName || majorNameMap[item.majorId] || '-'}
            </Badge>
          </TableCell>
          <TableCell className="p-3 hidden md:table-cell">
            <div className="flex flex-wrap gap-1.5">
              {(tagsByResource[item.id] || []).map((tag) => (
                <TagBadge key={tag.id} tag={tag} />
              ))}
              {(tagsByResource[item.id] || []).length === 0 && (
                <span className="text-xs text-slate-300">-</span>
              )}
            </div>
          </TableCell>
          <TableCell className="p-3 text-xs text-slate-400 hidden md:table-cell line-clamp-2">
            {item.answer || '-'}
          </TableCell>
          <TableCell className="p-3 text-right whitespace-nowrap">
            <Button variant="ghost" size="sm" onClick={() => handleEdit(item)}>
              <Pencil className="size-4" />
            </Button>
            <Button variant="ghost" size="sm" onClick={() => setDeleteTarget(item.id)}>
              <Trash2 className="size-4 text-destructive" />
            </Button>
          </TableCell>
        </TableRow>
      )}
      dialog={
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogContent className="max-w-lg">
            <DialogHeader>
              <DialogTitle>{editing ? t('编辑现场问答题') : t('新增现场问答题')}</DialogTitle>
            </DialogHeader>
            <form
              onSubmit={(e) => {
                e.preventDefault()
                handleSubmit()
              }}
              className="grid gap-4"
            >
              <div className="space-y-4">
              <FormFieldRow label={t('题目名称')} required>
                <Input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder={t('输入题目名称')}
                />
              </FormFieldRow>
              <FormFieldRow label={t('适用专业')}>
                <Select value={majorId} onValueChange={setMajorId}>
                  <SelectTrigger>
                    <SelectValue placeholder={t('选择适用专业')} />
                  </SelectTrigger>
                  <SelectContent>
                    {majors.map((m: any) => (
                      <SelectItem key={m.id} value={m.id}>
                        {m.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </FormFieldRow>
              <FormFieldRow label={t('题目描述')}>
                <Textarea
                  value={desc}
                  onChange={(e) => setDesc(e.target.value)}
                  placeholder={t('输入题目描述')}
                  rows={3}
                />
              </FormFieldRow>
              <FormFieldRow label={t('题目答案')}>
                <Textarea
                  value={answer}
                  onChange={(e) => setAnswer(e.target.value)}
                  placeholder={t('输入题目答案')}
                  rows={3}
                />
              </FormFieldRow>
              <FormFieldRow label={t('标签')}>
                <TagPicker value={tagIds} onChange={setTagIds} />
              </FormFieldRow>
              </div>
              <FormDialogFooter
                onCancel={() => setDialogOpen(false)}
                confirmDisabled={!name.trim()}
              />
            </form>
          </DialogContent>
        </Dialog>
      }
      pagination={{ page, totalPages, onPageChange: setPage }}
    >
      <TagFilterBar value={selectedTagIds} onChange={handleTagFilterChange} className="mb-4" />
    </LibraryPageShell>
  )
}
