// frontend/portal-vue/src/views/ai/hall/kbs.vue
<template>
  <div class="hall-page">
    <div class="hall-header">
      <router-link class="back" to="/portal/apps/ai/landing">
        <el-icon><ArrowLeft /></el-icon>返回首页
      </router-link>
      <div class="header-row">
        <div class="header-icon"><el-icon><Collection /></el-icon></div>
        <div>
          <h1>知识库大厅</h1>
          <p>租户内已发布的全部知识库，点击进入详情并可向知识库提问</p>
        </div>
      </div>
    </div>

    <div class="toolbar">
      <LandingFilterRow
        label="院系"
        :items="deptLabels"
        :selected="deptSelectedLabel"
        @update:selected="onDeptSelect"
      />
      <LandingFilterRow
        label="专业"
        :items="majorLabels"
        :selected="majorSelectedLabel"
        @update:selected="onMajorSelect"
      />
      <LandingFilterRow
        label="类型"
        :items="typeLabels"
        :selected="typeSelectedLabel"
        @update:selected="onTypeSelect"
      />
      <LandingFilterRow
        label="时间"
        :items="updatedLabels"
        :selected="updatedSelectedLabel"
        :show-border="false"
        @update:selected="onUpdatedSelect"
      />

      <div v-if="tagOptions.length" class="tag-row">
        <span class="tag-label">按标签：</span>
        <el-tag :effect="!tag ? 'dark' : 'plain'" class="tag-chip" @click="setQuery({ tag: '', page: '' })">全部</el-tag>
        <el-tag
          v-for="t in tagOptions"
          :key="t"
          :effect="tag === t ? 'dark' : 'plain'"
          class="tag-chip"
          @click="setQuery({ tag: tag === t ? '' : t, page: '' })"
        >{{ t }}</el-tag>
      </div>

      <div class="toolbar-bottom">
        <span class="total">共 {{ total }} 个</span>
        <div class="sorts">
          <el-button
            v-for="o in sortOptions"
            :key="o.value"
            size="small"
            :type="sort === o.value ? 'primary' : 'default'"
            :plain="sort !== o.value"
            @click="setQuery({ sort: o.value === 'hot' ? '' : o.value, page: '' })"
          >{{ o.label }}</el-button>
        </div>
        <el-input v-model="qInput" class="search" placeholder="搜索知识库" clearable @keyup.enter="applySearch" @clear="applySearch" />
        <el-button size="small" @click="applySearch">搜索</el-button>
      </div>
    </div>

    <div v-loading="loading" class="content">
      <el-empty v-if="!loading && !kbs.length" description="还没有已发布的知识库，去工坊创建第一个吧">
        <el-button type="primary" @click="router.push('/portal/apps/ai/studio/kb/new')">去创建</el-button>
      </el-empty>
      <template v-else>
        <div class="card-grid">
          <KbHallCard v-for="kb in kbs" :key="kb.id" :kb="kb" />
        </div>
        <div v-if="totalPages > 1" class="pager">
          <el-pagination
            layout="prev, pager, next"
            :total="total"
            :page-size="PAGE_SIZE"
            :current-page="page"
            @current-change="(p: number) => setQuery({ page: p > 1 ? String(p) : '' })"
          />
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { ArrowLeft, Collection } from '@element-plus/icons-vue';
import { aiCenterSquareApi } from '@/api/ai';
import type { AIKBType, AIKnowledgeBase } from '@/types/ai';
import { AI_KB_TYPE_LABELS, useClassifyDicts } from '../ai-api';
import KbHallCard from '../components/KbHallCard.vue';
import LandingFilterRow from '../../landing/LandingFilterRow.vue';

const PAGE_SIZE = 12;
const SORTS = ['hot', 'new', 'updated', 'docs', 'views'] as const;
type KbSort = (typeof SORTS)[number];

const route = useRoute();
const router = useRouter();
const { majors, departments } = useClassifyDicts();

const kbs = ref<AIKnowledgeBase[]>([]);
const total = ref(0);
const qInput = ref(String(route.query.q || ''));
const loadedKey = ref<string | null>(null);

const appliedQ = computed(() => String(route.query.q || ''));
const sort = computed<KbSort>(() => {
  const s = route.query.sort;
  return (SORTS as readonly string[]).includes(String(s)) ? (String(s) as KbSort) : 'hot';
});
const tag = computed(() => String(route.query.tag || ''));
const majorId = computed(() => String(route.query.major || ''));
const departmentId = computed(() => String(route.query.dept || ''));
const kbType = computed(() => String(route.query.type || ''));
const updated = computed(() => String(route.query.updated || ''));
const page = computed(() => Math.max(1, parseInt(String(route.query.page || '1'), 10) || 1));
const totalPages = computed(() => Math.max(1, Math.ceil(total.value / PAGE_SIZE)));

const reqKey = computed(() => `${appliedQ.value}|${tag.value}|${sort.value}|${majorId.value}|${departmentId.value}|${kbType.value}|${updated.value}|${page.value}`);
const loading = computed(() => loadedKey.value !== reqKey.value);

const sortOptions = [
  { value: 'hot', label: '综合排序' },
  { value: 'new', label: '最新创建' },
  { value: 'updated', label: '最近更新' },
  { value: 'docs', label: '资源最多' },
  { value: 'views', label: '浏览最多' }
];
const updatedOptions = [
  { v: '', label: '全部' },
  { v: '7d', label: '最近一周' },
  { v: '30d', label: '最近一月' },
  { v: '180d', label: '最近半年' }
];
const typeEntries = Object.entries(AI_KB_TYPE_LABELS) as [AIKBType, string][];

const majorLabels = computed(() => ['全部', ...majors.value.map((m) => m.name)]);
const deptLabels = computed(() => ['全部', ...departments.value.map((d) => d.name)]);
const updatedLabels = computed(() => updatedOptions.map((o) => o.label));
const typeLabels = computed(() => ['全部', ...typeEntries.map(([, l]) => l)]);
const majorSelectedLabel = computed(() => majorId.value ? majors.value.find((m) => m.id === majorId.value)?.name || '全部' : '全部');
const deptSelectedLabel = computed(() => departmentId.value ? departments.value.find((d) => d.id === departmentId.value)?.name || '全部' : '全部');
const updatedSelectedLabel = computed(() => updatedOptions.find((o) => o.v === updated.value)?.label || '全部');
const typeSelectedLabel = computed(() => kbType.value ? AI_KB_TYPE_LABELS[kbType.value as AIKBType] || '全部' : '全部');

const tagOptions = computed(() => {
  const set = new Set<string>();
  if (tag.value) set.add(tag.value);
  kbs.value.forEach((k) => (k.tags || []).forEach((t) => set.add(t)));
  return Array.from(set);
});

function setQuery(patch: Record<string, string>) {
  const params = new URLSearchParams(route.query as Record<string, string>);
  for (const [k, v] of Object.entries(patch)) {
    if (v) params.set(k, v);
    else params.delete(k);
  }
  router.replace({ query: Object.fromEntries(params) });
}

async function load() {
  try {
    const res = await aiCenterSquareApi.kbs({
      q: appliedQ.value || undefined,
      tag: tag.value || undefined,
      sort: sort.value,
      page: page.value,
      pageSize: PAGE_SIZE,
      majorId: majorId.value || undefined,
      departmentId: departmentId.value || undefined,
      kbType: (kbType.value || undefined) as AIKBType | undefined,
      updated: (updated.value || undefined) as '7d' | '30d' | '180d' | undefined
    });
    kbs.value = res.items;
    total.value = res.total;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loadedKey.value = reqKey.value;
  }
}

function applySearch() {
  setQuery({ q: qInput.value.trim(), page: '' });
}
function onDeptSelect(label: string) {
  setQuery({ dept: departments.value.find((d) => d.name === label)?.id || '', page: '' });
}
function onMajorSelect(label: string) {
  setQuery({ major: majors.value.find((m) => m.name === label)?.id || '', page: '' });
}
function onUpdatedSelect(label: string) {
  setQuery({ updated: updatedOptions.find((o) => o.label === label)?.v || '', page: '' });
}
function onTypeSelect(label: string) {
  const entry = typeEntries.find(([, l]) => l === label);
  setQuery({ type: entry?.[0] || '', page: '' });
}

watch(reqKey, load, { immediate: true });
</script>

<style scoped>
.hall-page {
  max-width: 1400px;
  margin: 0 auto;
}
.hall-header {
  background: linear-gradient(135deg, #409eff, #79bbff);
  border-radius: 0 0 16px 16px;
  padding: 24px 28px;
  color: #fff;
}
.back {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  color: rgba(255, 255, 255, 0.85);
  font-size: 14px;
  text-decoration: none;
  margin-bottom: 12px;
}
.back:hover {
  color: #fff;
}
.header-row {
  display: flex;
  align-items: center;
  gap: 16px;
}
.header-icon {
  width: 48px;
  height: 48px;
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.15);
  border: 1px solid rgba(255, 255, 255, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
}
.header-row h1 {
  font-size: 20px;
  font-weight: 700;
  margin: 0;
}
.header-row p {
  font-size: 14px;
  color: rgba(255, 255, 255, 0.85);
  margin: 4px 0 0;
}
.toolbar {
  background: #fff;
  border: 1px solid #e7e5e4;
  border-radius: 16px;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.04);
  padding: 4px 20px;
  margin-top: 16px;
}
.tag-row {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  padding: 8px 0;
}
.tag-label {
  color: #909399;
  font-size: 14px;
}
.tag-chip {
  cursor: pointer;
}
.toolbar-bottom {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  padding: 12px 0;
  border-top: 1px solid #f0f0f0;
}
.total {
  color: #909399;
  font-size: 14px;
}
.sorts {
  display: flex;
  gap: 4px;
}
.search {
  width: 260px;
  margin-left: auto;
}
.content {
  margin-top: 16px;
  min-height: 200px;
}
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap: 20px;
}
.pager {
  display: flex;
  justify-content: center;
  padding: 20px 0 24px;
}
</style>

// apps/edu/app/portal/apps/ai/hall/kbs/page.tsx
'use client'

// 知识库大厅（/portal/apps/ai/hall/kbs）：首页「查看更多」进入的全量列表页。
// 样式对齐 docs/demo 知识库大厅原型；排序映射（spec §2.1 Q2-a）：
// 综合排序=hot(提问数) / 最新创建=new / 最近更新=updated / 资源最多=docs / 浏览最多=views(v2.2)。
// v2.2 A3：搜索/标签/排序/页码全部同步到 URL query，刷新/分享不丢状态；加载更多 → 页码分页。
import { Suspense, useCallback, useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { BookOpen } from 'lucide-react'
import { aiCenterSquareApi, type AIKnowledgeBase } from '@/lib/api'
import { useToast, EmptyState } from '@zhiyu/ui'
import { useT } from '@/lib/i18n/locale-provider'
import { HallShell } from '../../_components/hall-shell'
import { KbHallCard } from '../../_components/hall-cards'
import { LandingPagination } from '@/components/shared/landing-pagination'
import { LandingFilterRow } from '@/components/shared/landing-filter-row'
import { AI_KB_TYPE_LABELS, type AIKBType } from '@/lib/api'
import { useClassifyDicts } from '../../_components/classify-dicts'

const PAGE_SIZE = 12

type KbSort = 'hot' | 'new' | 'updated' | 'docs' | 'views'
const SORTS: KbSort[] = ['hot', 'new', 'updated', 'docs', 'views']

function KbHallInner() {
  const t = useT()
  const { toast } = useToast()
  const router = useRouter()
  const searchParams = useSearchParams()

  // URL 为唯一事实源（A3）
  const appliedQ = searchParams.get('q') || ''
  const rawSort = searchParams.get('sort') || 'hot'
  const sort = (SORTS.includes(rawSort as KbSort) ? rawSort : 'hot') as KbSort
  const tag = searchParams.get('tag') || ''
  const majorId = searchParams.get('major') || ''
  const departmentId = searchParams.get('dept') || ''
  const kbType = searchParams.get('type') || ''
  const updated = searchParams.get('updated') || ''
  const page = Math.max(1, parseInt(searchParams.get('page') || '1', 10) || 1)

  const [qInput, setQInput] = useState(appliedQ)
  const [kbs, setKbs] = useState<AIKnowledgeBase[]>([])
  const [total, setTotal] = useState(0)
  // 加载态派生：已完成请求钥匙 ≠ 当前参数钥匙 即加载中（避免 effect 内同步 setState）
  const reqKey = `${appliedQ}|${tag}|${sort}|${majorId}|${departmentId}|${kbType}|${updated}|${page}`
  const [loadedKey, setLoadedKey] = useState<string | null>(null)
  const loading = loadedKey !== reqKey

  const setQuery = useCallback(
    (patch: Record<string, string>) => {
      const params = new URLSearchParams(searchParams.toString())
      for (const [k, v] of Object.entries(patch)) {
        if (v) params.set(k, v)
        else params.delete(k)
      }
      router.replace(`?${params.toString()}`, { scroll: false })
    },
    [router, searchParams],
  )

  useEffect(() => {
    let alive = true
    aiCenterSquareApi
      .kbs({
        q: appliedQ || undefined,
        tag: tag || undefined,
        sort,
        page,
        pageSize: PAGE_SIZE,
        majorId: majorId || undefined,
        departmentId: departmentId || undefined,
        kbType: (kbType || undefined) as AIKBType | undefined,
        updated: (updated || undefined) as '7d' | '30d' | '180d' | undefined,
      })
      .then((res) => {
        if (!alive) return
        setKbs(res.items)
        setTotal(res.total)
      })
      .catch((err: unknown) =>
        toast({
          title: t('加载失败'),
          description: err instanceof Error ? err.message : undefined,
          variant: 'destructive',
        }),
      )
      .finally(() => {
        if (alive) setLoadedKey(reqKey)
      })
    return () => {
      alive = false
    }
  }, [appliedQ, tag, sort, page, majorId, departmentId, kbType, updated, reqKey, toast, t])

  // 标签筛选 chips：当前结果集标签并集 + 已选标签（保证可取消）
  const tagOptions = Array.from(
    new Set([...(tag ? [tag] : []), ...kbs.flatMap((k) => k.tags || [])]),
  )
  const { majors, departments } = useClassifyDicts()
  const UPDATED_OPTIONS = [
    { v: '', label: t('全部') },
    { v: '7d', label: t('最近一周') },
    { v: '30d', label: t('最近一月') },
    { v: '180d', label: t('最近半年') },
  ]

  return (
    <HallShell
      title={t('知识库大厅')}
      headerIcon={<BookOpen className="w-6 h-6 text-white" />}
      subtitle={t('租户内已发布的全部知识库，点击进入详情并可向知识库提问')}
      tags={tagOptions}
      activeTag={tag}
      onTagChange={(v) => setQuery({ tag: v, page: '' })}
      sortOptions={[
        { value: 'hot', label: t('综合排序') },
        { value: 'new', label: t('最新创建') },
        { value: 'updated', label: t('最近更新') },
        { value: 'docs', label: t('资源最多') },
        { value: 'views', label: t('浏览最多') },
      ]}
      sort={sort}
      onSortChange={(v) => setQuery({ sort: v === 'hot' ? '' : v, page: '' })}
      searchValue={qInput}
      onSearchChange={setQInput}
      onSearch={() => setQuery({ q: qInput.trim(), page: '' })}
      filters={
        <>
          <LandingFilterRow
            label={t('院系')}
            items={[t('全部'), ...departments.map((d) => d.name)]}
            selected={departmentId ? departments.find((d) => d.id === departmentId)?.name || t('全部') : t('全部')}
            onSelect={(label) =>
              setQuery({ dept: departments.find((d) => d.name === label)?.id || '', page: '' })
            }
            accentColor="primary"
          />
          <LandingFilterRow
            label={t('专业')}
            items={[t('全部'), ...majors.map((m) => m.name)]}
            selected={majorId ? majors.find((m) => m.id === majorId)?.name || t('全部') : t('全部')}
            onSelect={(label) =>
              setQuery({ major: majors.find((m) => m.name === label)?.id || '', page: '' })
            }
            accentColor="primary"
          />
          <LandingFilterRow
            label={t('类型')}
            items={[t('全部'), ...Object.values(AI_KB_TYPE_LABELS).map((l) => t(l))]}
            selected={kbType ? t(AI_KB_TYPE_LABELS[kbType as AIKBType] || kbType) : t('全部')}
            onSelect={(label) => {
              const entry = (Object.entries(AI_KB_TYPE_LABELS) as [AIKBType, string][]).find(
                ([, l]) => t(l) === label,
              )
              setQuery({ type: entry?.[0] || '', page: '' })
            }}
            accentColor="primary"
          />
          <LandingFilterRow
            label={t('时间')}
            items={UPDATED_OPTIONS.map((o) => o.label)}
            selected={UPDATED_OPTIONS.find((o) => o.v === updated)?.label || t('全部')}
            onSelect={(label) =>
              setQuery({ updated: UPDATED_OPTIONS.find((o) => o.label === label)?.v || '', page: '' })
            }
            accentColor="primary"
            showBorder={false}
          />
        </>
      }
      searchPlaceholder={t('搜索知识库')}
      total={total}
      loading={loading}
    >
      {kbs.length === 0 && !loading ? (
        <EmptyState
          icon={<BookOpen className="h-10 w-10" />}
          title={t('暂无内容')}
          description={t('还没有已发布的知识库，去工坊创建第一个吧')}
          action={
            <a
              href="/portal/apps/ai/landing#studio"
              className="inline-flex items-center rounded-full bg-primary text-white px-5 h-9 text-sm font-medium hover:bg-primary/90"
            >
              {t('去创建')}
            </a>
          }
        />
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {kbs.map((kb) => (
              <KbHallCard key={kb.id} kb={kb} />
            ))}
          </div>
          <div className="flex justify-center pt-2 pb-6">
            <LandingPagination
              currentPage={page}
              totalPages={Math.ceil(total / PAGE_SIZE)}
              onPageChange={(p) => setQuery({ page: p > 1 ? String(p) : '' })}
            />
          </div>
        </>
      )}
    </HallShell>
  )
}

export default function KbHallPage() {
  return (
    <Suspense>
      <KbHallInner />
    </Suspense>
  )
}
