// frontend/edu/app/affairs/programs/page.tsx
'use client'

import { useRouter } from 'next/navigation'
import { ContentListPage } from '@/components/shared/content-list-page'
import { StatusBadge } from '@/components/shared/status-badge'
import { StatusActionBar } from '@/components/shared/status-action-bar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { programApi, affairsBatchApi, approvalApi, importExportApi } from '@/lib/api'
import type { TrainingProgram, AffairsBatch } from '@/lib/types'
import { STATUS_FILTER_OPTIONS } from '@zhiyu/shared-types'
import { TableEmptyRow } from '@zhiyu/ui'
import { useT } from '@/lib/i18n/locale-provider'

function mapProgram(backend: any) {
  return {
    ...backend,
    creatorId: backend.createdBy || '',
    coCreatorIds: backend.collaborators || [],
  }
}
function mapBatch(backend: any) {
  return { id: backend.id, name: backend.name, workflowId: backend.workflowId }
}

export default function ProgramsPage() {
  const t = useT()
  const router = useRouter()
  return (
    <ContentListPage<
      TrainingProgram & { creatorId: string; coCreatorIds: string[] },
      TrainingProgram,
      AffairsBatch
    >
      title={t('人才培养方案')}
      subtitle={t('维护专业人才培养方案及课程设置，发布后可生成学期教学计划')}
      entityLabel={t('人培方案')}
      addHref="/affairs/programs"
      permissionModule="affairs"
      permissionResource="programs"
      itemApi={programApi}
      batchApi={affairsBatchApi}
      approvalApi={approvalApi}
      importExportApi={importExportApi}
      approvalTargetType="training_program"
      coBuilderField="collaborators"
      createRedirectUrl={(id) => `/affairs/programs/${id}?new=true`}
      statusFilterOptions={STATUS_FILTER_OPTIONS}
      mapItem={mapProgram}
      mapBatch={mapBatch}
      createPayload={() => ({
        name: t('新建人培方案'),
        entryYear: new Date().getFullYear(),
        level: '本科',
        duration: 4,
        totalCredits: 0,
        status: 'draft',
        collaborators: [],
      })}
      renderList={(props: any) => {
        const {
          activeTab,
          items,
          selectedIds,
          onSelectId,
          onSelectAll,
          onClone,
          onDelete,
          onSubmitApproval,
          onWithdrawApproval,
          onPublish,
          onUnpublish,
          onArchive,
          onInviteCoBuild,
        } = props
        return (
          <div className="rounded-lg border bg-white px-4 py-3">
            <Table resizable storageKey="affairs.programs.list">
              <TableHeader>
                <TableRow className="border-b">
                  <TableHead
                    columnKey="select"
                    defaultWidth={32}
                    minWidth={32}
                    resizable={false}
                    className="px-2 py-2"
                  >
                    <input type="checkbox" onChange={(e) => onSelectAll(e.target.checked)} />
                  </TableHead>
                  <TableHead
                    columnKey="name"
                    defaultWidth={180}
                    minWidth={120}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('方案名称')}
                  </TableHead>
                  <TableHead
                    columnKey="major"
                    defaultWidth={120}
                    minWidth={80}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('专业')}
                  </TableHead>
                  <TableHead
                    columnKey="entryYear"
                    defaultWidth={80}
                    minWidth={56}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('年级')}
                  </TableHead>
                  <TableHead
                    columnKey="courseCount"
                    defaultWidth={80}
                    minWidth={56}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('课程数')}
                  </TableHead>
                  <TableHead
                    columnKey="batch"
                    defaultWidth={120}
                    minWidth={80}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('批次')}
                  </TableHead>
                  <TableHead
                    columnKey="status"
                    defaultWidth={80}
                    minWidth={56}
                    className="px-2 py-2 text-left text-xs font-medium text-muted-foreground"
                  >
                    {t('状态')}
                  </TableHead>
                  <TableHead
                    columnKey="actions"
                    defaultWidth={180}
                    minWidth={120}
                    className="sticky right-0 bg-white px-2 py-2 text-right text-xs font-medium text-muted-foreground"
                  >
                    {t('操作')}
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {items.length === 0 ? (
                  <TableEmptyRow colSpan={8}>{t('暂无人培方案')}</TableEmptyRow>
                ) : (
                  items.map((item: any) => (
                    <TableRow key={item.id} className="border-t hover:bg-muted/30 group">
                      <TableCell className="px-2 py-2">
                        <input
                          type="checkbox"
                          checked={selectedIds?.includes(item.id)}
                          onChange={() => onSelectId?.(item.id)}
                        />
                      </TableCell>
                      <TableCell className="px-2 py-2">
                        <div className="font-medium text-sm truncate">{item.name}</div>
                        {item.code && (
                          <div className="text-xs text-muted-foreground truncate">{item.code}</div>
                        )}
                      </TableCell>
                      <TableCell className="px-2 py-2 text-sm text-muted-foreground truncate">
                        {item.majorName || '-'}
                      </TableCell>
                      <TableCell className="px-2 py-2 text-sm">
                        {t('{n}级', { n: item.entryYear })}
                      </TableCell>
                      <TableCell className="px-2 py-2 text-sm">{item.courseCount}</TableCell>
                      <TableCell className="px-2 py-2 text-sm text-muted-foreground truncate">
                        {item.batchName || '-'}
                      </TableCell>
                      <TableCell className="px-2 py-2">
                        <StatusBadge status={item.status} />
                      </TableCell>
                      <TableCell className="sticky right-0 bg-white px-2 py-2">
                        <StatusActionBar
                          status={item.status}
                          isPublicPool={activeTab === 'public'}
                          onEdit={() => router.push(`/affairs/programs/${item.id}`)}
                          onSubmit={onSubmitApproval ? () => onSubmitApproval(item) : undefined}
                          onWithdraw={
                            onWithdrawApproval ? () => onWithdrawApproval(item) : undefined
                          }
                          onPublish={onPublish ? () => onPublish(item) : undefined}
                          onUnpublish={onUnpublish ? () => onUnpublish(item) : undefined}
                          onArchive={onArchive ? () => onArchive(item) : undefined}
                          onClone={onClone ? () => onClone(item) : undefined}
                          onDelete={onDelete ? () => onDelete(item) : undefined}
                          onInvite={onInviteCoBuild ? () => onInviteCoBuild(item) : undefined}
                        />
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        )
      }}
    />
  )
}

// frontend/portal-vue/src/views/affairs/programs.vue
<template>
  <ContentListPage :config="config">
    <template #list="slot">
      <el-card shadow="never" class="programs-table-card">
        <el-table :data="slot.items" stripe>
          <el-table-column width="50">
            <template #header>
              <el-checkbox
                :model-value="allSelected(slot)"
                :indeterminate="someSelected(slot)"
                @change="slot.handleSelectAll($event as boolean)"
              />
            </template>
            <template #default="{ row }">
              <el-checkbox
                :model-value="slot.selectedIds.includes(row.id)"
                @change="slot.handleSelectId(row.id, $event as boolean)"
              />
            </template>
          </el-table-column>

          <el-table-column label="方案名称" min-width="200" show-overflow-tooltip>
            <template #default="{ row }">
              <div class="prog-name">{{ row.name }}</div>
              <div v-if="row.code" class="prog-code">{{ row.code }}</div>
            </template>
          </el-table-column>

          <el-table-column label="专业" width="140" show-overflow-tooltip>
            <template #default="{ row }">{{ row.majorName || '-' }}</template>
          </el-table-column>

          <el-table-column label="年级" width="90">
            <template #default="{ row }">{{ row.entryYear }}级</template>
          </el-table-column>

          <el-table-column label="课程数" width="90">
            <template #default="{ row }">{{ row.courseCount ?? '-' }}</template>
          </el-table-column>

          <el-table-column label="批次" width="140" show-overflow-tooltip>
            <template #default="{ row }">{{ batchName(slot, row) }}</template>
          </el-table-column>

          <el-table-column label="状态" width="100">
            <template #default="{ row }">
              <el-tag :type="statusTagType(row.status)" size="small">
                {{ contentStatusLabel(row.status) }}
              </el-tag>
            </template>
          </el-table-column>

          <el-table-column label="操作" min-width="300" fixed="right">
            <template #default="{ row }">
              <el-button
                v-if="canEdit(row.status)"
                link
                type="primary"
                size="small"
                @click="goEdit(row)"
              >
                编辑
              </el-button>
              <el-button
                v-for="act in slot.rowActions(row)"
                :key="act.key"
                link
                :type="act.type"
                size="small"
                @click="act.handler"
              >
                {{ act.label }}
              </el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </template>
  </ContentListPage>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import ContentListPage from '@/components/common/content-list-page.vue';
import type {
  ContentApi,
  ContentApprovalApi,
  ContentBatchApi,
  ContentImportExportApi,
  ContentListItem,
  ContentListPageConfig,
  ListSlotProps
} from '@/components/common/content-list-page.types';
import { programApi, affairsBatchApi } from '@/api/affairs';
import { approvalApi } from '@/api/approval';
import { importExportApi } from '@/api/import-export';
import type { TrainingProgram } from '@/types/affairs';
import { contentStatusLabel } from '@/types/content-status';

const router = useRouter();

// ─── 状态筛选选项（对齐 React STATUS_FILTER_OPTIONS） ────────────────────────
const STATUS_FILTER_OPTIONS = [
  { value: 'draft', label: '草稿' },
  { value: 'pending', label: '审批中' },
  { value: 'approved', label: '已通过' },
  { value: 'rejected', label: '已驳回' },
  { value: 'published', label: '已发布' },
  { value: 'archived', label: '已归档' }
];

// ─── 映射（对齐 React mapProgram / mapBatch） ────────────────────────────────
function mapProgram(backend: unknown): ContentListItem {
  const p = backend as TrainingProgram;
  return {
    ...p,
    id: p.id,
    name: p.name,
    status: p.status,
    batchId: p.batchId,
    creatorId: p.createdBy || '',
    coCreatorIds: p.collaborators || [],
    code: p.code,
    majorName: p.majorName,
    entryYear: p.entryYear,
    courseCount: p.courseCount,
    batchName: p.batchName
  };
}

function mapBatch(backend: unknown) {
  const b = backend as { id: string; name: string; workflowId?: string };
  return { id: b.id, name: b.name, workflowId: b.workflowId };
}

function createPayload(): Record<string, unknown> {
  return {
    name: '新建人培方案',
    entryYear: new Date().getFullYear(),
    level: '本科',
    duration: 4,
    totalCredits: 0,
    status: 'draft',
    collaborators: []
  };
}

const config: ContentListPageConfig = {
  title: '人才培养方案',
  subtitle: '维护专业人才培养方案及课程设置，发布后可生成学期教学计划',
  entityLabel: '人培方案',
  addHref: '/affairs/programs',
  permissionModule: 'affairs',
  permissionResource: 'programs',
  itemApi: programApi as unknown as ContentApi,
  batchApi: affairsBatchApi as unknown as ContentBatchApi,
  approvalApi: approvalApi as unknown as ContentApprovalApi,
  importExportApi: importExportApi as unknown as ContentImportExportApi,
  approvalTargetType: 'training_program',
  coBuilderField: 'collaborators',
  createRedirectUrl: (id: string) => `/affairs/programs/${id}/edit`,
  statusFilterOptions: STATUS_FILTER_OPTIONS,
  mapItem: mapProgram,
  mapBatch,
  createPayload
};

// ─── 行展示辅助 ────────────────────────────────────────────────────────────
function batchName(slot: ListSlotProps, row: ContentListItem): string {
  if (!row.batchId) return '-';
  const name = (row as { batchName?: string }).batchName;
  return slot.batchMap[row.batchId] || name || row.batchId;
}

function allSelected(slot: { items: ContentListItem[]; selectedIds: string[] }): boolean {
  return slot.items.length > 0 && slot.items.every((i) => slot.selectedIds.includes(i.id));
}

function someSelected(slot: { items: ContentListItem[]; selectedIds: string[] }): boolean {
  return slot.items.some((i) => slot.selectedIds.includes(i.id)) && !allSelected(slot);
}

// ─── 行操作可见性（对齐 React StatusActionBar 的 EDITABLE_STATUSES） ─────────
const EDITABLE_STATUSES = ['draft', 'rejected', 'approved'];
function canEdit(status: string): boolean {
  return EDITABLE_STATUSES.includes(status);
}

function statusTagType(status: string): 'primary' | 'success' | 'info' | 'warning' | 'danger' {
  switch (status) {
    case 'published':
      return 'success';
    case 'rejected':
      return 'danger';
    case 'pending':
      return 'primary';
    case 'approved':
      return 'warning';
    default:
      return 'info';
  }
}

// ─── 导航（对齐 React：详情跳转；Vue 路由为 /affairs/programs/:id/edit） ────
function goEdit(row: ContentListItem) {
  router.push(`/affairs/programs/${row.id}/edit`);
}
</script>

<style scoped>
.programs-table-card :deep(.el-card__body) {
  padding: 0;
}
.prog-name {
  font-weight: 500;
  color: #303133;
}
.prog-code {
  font-size: 12px;
  color: #909399;
}
</style>
