// apps/edu/components/shared/theme-color-picker.tsx
'use client'

import { Button } from '@/components/ui/button'
import { Loader2, RotateCcw } from 'lucide-react'
import { isHexColor } from '@/lib/theme-brand'

export const THEME_PRESETS = [
  '#4862e4',
  '#1677ff',
  '#0b5bd0',
  '#0ea5e9',
  '#7c3aed',
  '#059669',
  '#ea580c',
]

interface ThemeColorPickerProps {
  color: string
  onChange: (color: string) => void
  onSubmit: (color: string) => void | Promise<void>
  submitting?: boolean
  submitLabel?: string
  secondary?: { label: string; onClick: () => void; disabled?: boolean }[]
}

/** 主题色选择器：预设色板 + 取色器 + 手动输入 + 实时预览 + 保存动作（平台级/租户级通用）。 */
export function ThemeColorPicker({
  color,
  onChange,
  onSubmit,
  submitting = false,
  submitLabel = '保存并应用',
  secondary = [],
}: ThemeColorPickerProps) {
  const valid = isHexColor(color)

  return (
    <div>
      <div className="flex flex-wrap items-center gap-2">
        {THEME_PRESETS.map((preset) => (
          <button
            key={preset}
            type="button"
            title={preset}
            aria-label={`主题色 ${preset}`}
            onClick={() => onChange(preset)}
            className={`h-8 w-8 rounded-full transition-transform hover:scale-110 ${
              color.toLowerCase() === preset.toLowerCase()
                ? 'ring-2 ring-offset-2 ring-foreground/30'
                : ''
            }`}
            style={{ backgroundColor: preset }}
          />
        ))}
        <label
          className="flex h-8 w-8 items-center justify-center rounded-full border border-dashed border-gray-300 text-xs text-muted-foreground cursor-pointer hover:border-primary hover:text-primary"
          title="自定义颜色"
        >
          <input
            type="color"
            value={valid ? color : '#000000'}
            onChange={(e) => onChange(e.target.value)}
            className="sr-only"
          />
          +
        </label>
        <input
          value={color}
          onChange={(e) => onChange(e.target.value)}
          className="h-8 w-28 rounded-md border border-gray-200 px-2 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-primary/20"
          placeholder="#RRGGBB"
        />
        <span className="text-xs text-muted-foreground">自定义色值</span>
      </div>

      {/* 实时预览 */}
      <div className="mt-4 flex flex-wrap items-center gap-3 rounded-lg bg-muted/50 p-3">
        <span className="text-xs text-muted-foreground">预览：</span>
        <Button size="sm" style={{ backgroundColor: color }} disabled={!valid}>
          主要按钮
        </Button>
        <Button size="sm" variant="outline" style={{ color }} disabled={!valid}>
          次要按钮
        </Button>
        <span
          className="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium text-white"
          style={{ backgroundColor: color }}
        >
          标签
        </span>
        <span className="text-xs text-muted-foreground">
          当前色值：<span className="font-mono">{color}</span>
        </span>
      </div>

      <div className="mt-4 flex items-center gap-2">
        <Button size="sm" onClick={() => onSubmit(color)} disabled={submitting || !valid}>
          {submitting ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : null}
          {submitLabel}
        </Button>
        {secondary.map((item) => (
          <Button
            key={item.label}
            size="sm"
            variant="outline"
            disabled={item.disabled || submitting}
            onClick={item.onClick}
          >
            <RotateCcw className="h-3.5 w-3.5 mr-1" />
            {item.label}
          </Button>
        ))}
      </div>
    </div>
  )
}

// frontend/portal-vue/src/views/superadmin/theme-color-picker.vue
<template>
  <div class="theme-picker">
    <div class="tp-presets">
      <button
        v-for="preset in THEME_PRESETS"
        :key="preset"
        type="button"
        class="tp-swatch"
        :class="{ 'is-active': color.toLowerCase() === preset.toLowerCase() }"
        :style="{ backgroundColor: preset }"
        :title="preset"
        @click="emit('update:color', preset)"
      />
      <label class="tp-custom" title="自定义颜色">
        <input
          type="color"
          :value="valid ? color : '#000000'"
          class="tp-native-color"
          @input="onNativeColor"
        />
        +
      </label>
      <el-input
        :model-value="color"
        class="tp-hex"
        placeholder="#RRGGBB"
        @update:model-value="emit('update:color', $event)"
      />
      <span class="tp-hint">自定义色值</span>
    </div>

    <div class="tp-preview">
      <span class="tp-preview-label">预览：</span>
      <el-button size="small" :disabled="!valid" :style="{ backgroundColor: valid ? color : undefined }">
        主要按钮
      </el-button>
      <el-button size="small" plain :disabled="!valid" :style="valid ? { color } : undefined">
        次要按钮
      </el-button>
      <span class="tp-tag" :style="{ backgroundColor: valid ? color : '#909399' }">标签</span>
      <span class="tp-current">当前色值：<span class="tp-mono">{{ color }}</span></span>
    </div>

    <div class="tp-actions">
      <el-button size="small" type="primary" :loading="submitting" :disabled="!valid" @click="emit('submit', color)">
        {{ submitLabel || '保存并应用' }}
      </el-button>
      <el-button
        v-for="(item, idx) in secondary"
        :key="item.label"
        size="small"
        :disabled="item.disabled || submitting"
        @click="emit('secondary', idx)"
      >
        {{ item.label }}
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { isHexColor } from '@/api/superadmin';

interface ThemeSecondaryAction {
  label: string;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    color: string;
    submitting?: boolean;
    submitLabel?: string;
    secondary?: ThemeSecondaryAction[];
  }>(),
  { submitting: false, submitLabel: '', secondary: () => [] }
);

const emit = defineEmits<{
  (e: 'update:color', value: string): void;
  (e: 'submit', value: string): void;
  (e: 'secondary', index: number): void;
}>();

const THEME_PRESETS = ['#4862e4', '#1677ff', '#0b5bd0', '#0ea5e9', '#7c3aed', '#059669', '#ea580c'];

const valid = computed(() => isHexColor(props.color));

function onNativeColor(e: Event) {
  emit('update:color', (e.target as HTMLInputElement).value);
}
</script>

<style scoped>
.theme-picker {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
.tp-presets {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
}
.tp-swatch {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  border: none;
  cursor: pointer;
  transition: transform 0.15s ease;
}
.tp-swatch:hover {
  transform: scale(1.1);
}
.tp-swatch.is-active {
  box-shadow: 0 0 0 2px #fff, 0 0 0 4px rgba(0, 0, 0, 0.25);
}
.tp-custom {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  border: 1px dashed #d0d5dd;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  color: #909399;
  font-size: 14px;
  position: relative;
}
.tp-custom:hover {
  border-color: #4862e4;
  color: #4862e4;
}
.tp-native-color {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  cursor: pointer;
}
.tp-hex {
  width: 120px;
}
.tp-hint {
  font-size: 12px;
  color: #909399;
}
.tp-preview {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: 8px;
  background: #f5f7fa;
}
.tp-preview-label {
  font-size: 12px;
  color: #909399;
}
.tp-tag {
  display: inline-flex;
  align-items: center;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 500;
  color: #fff;
}
.tp-current {
  font-size: 12px;
  color: #909399;
}
.tp-mono {
  font-family: monospace;
}
.tp-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>
