// plus-ui/src-portal/views/library/_components/GranularLessonSelectDialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    title="选择颗粒课"
    width="800px"
    @update:model-value="onClose"
  >
    <div class="gl-body">
      <div class="gl-left">
        <el-input v-model="search" placeholder="搜索颗粒课名称或编码..." clearable class="gl-search" />
        <div class="gl-list">
          <div
            v-for="gl in filtered"
            :key="gl.id"
            class="gl-item"
            :class="{ active: isSelected(gl.id) }"
            @click="toggle(gl.id)"
          >
            <div class="gl-check" :class="{ checked: isSelected(gl.id) }">{{ isSelected(gl.id) ? '✓' : '' }}</div>
            <div class="gl-info">
              <div class="gl-name">{{ gl.name }}</div>
              <div v-if="gl.description" class="gl-desc">{{ gl.description }}</div>
            </div>
            <span v-if="gl.code" class="gl-code">{{ gl.code }}</span>
          </div>
          <div v-if="filtered.length === 0" class="gl-empty">未找到匹配的颗粒课</div>
        </div>
      </div>

      <div class="gl-right">
        <p class="gl-selected-title">已选择 ({{ selectedIds.length }})</p>
        <div class="gl-selected-list">
          <div v-if="selectedCourses.length === 0" class="gl-empty">从左侧选择颗粒课</div>
          <div v-for="gl in selectedCourses" :key="gl.id" class="gl-selected-item">
            <span class="gl-selected-name">{{ gl.name }}</span>
            <button type="button" class="gl-remove" @click="toggle(gl.id)">✕</button>
          </div>
        </div>
      </div>
    </div>
    <template #footer>
      <el-button @click="emit('update:modelValue', false)">确定</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import type { GranularLessonOption } from './types';

const props = defineProps<{
  modelValue: boolean;
  granularCourses: GranularLessonOption[];
  selectedIds: string[];
}>();
const emit = defineEmits<{
  (e: 'update:modelValue', v: boolean): void;
  (e: 'update:selectedIds', v: string[]): void;
}>();

const search = ref('');

const filtered = computed(() => {
  const q = search.value.trim();
  if (!q) return props.granularCourses;
  return props.granularCourses.filter(
    (g) => g.name.includes(q) || (g.code ? g.code.includes(q) : false)
  );
});

const selectedCourses = computed(() =>
  props.selectedIds
    .map((id) => props.granularCourses.find((g) => g.id === id))
    .filter((g): g is GranularLessonOption => Boolean(g))
);

function isSelected(id: string): boolean {
  return props.selectedIds.includes(id);
}

function toggle(id: string): void {
  const next = isSelected(id) ? props.selectedIds.filter((x) => x !== id) : [...props.selectedIds, id];
  emit('update:selectedIds', next);
}

function onClose(open: boolean): void {
  if (!open) search.value = '';
  emit('update:modelValue', open);
}
</script>

<style scoped>
.gl-body {
  display: flex;
  gap: 16px;
  height: 50vh;
  min-height: 320px;
}
.gl-left {
  flex: 3;
  display: flex;
  flex-direction: column;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 12px;
  min-height: 0;
}
.gl-search {
  margin-bottom: 12px;
}
.gl-list {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding-right: 4px;
}
.gl-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.15s;
}
.gl-item:hover {
  border-color: #cbd5e1;
}
.gl-item.active {
  border-color: #409eff;
  background: #ecf5ff;
}
.gl-check {
  width: 16px;
  height: 16px;
  border: 1px solid #cbd5e1;
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  color: #fff;
  flex-shrink: 0;
}
.gl-check.checked {
  background: #409eff;
  border-color: #409eff;
}
.gl-info {
  flex: 1;
  min-width: 0;
}
.gl-name {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
}
.gl-desc {
  font-size: 12px;
  color: #94a3b8;
  margin-top: 2px;
}
.gl-code {
  font-size: 10px;
  color: #94a3b8;
  border: 1px solid #e2e8f0;
  border-radius: 4px;
  padding: 1px 6px;
  white-space: nowrap;
}
.gl-right {
  flex: 2;
  display: flex;
  flex-direction: column;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 12px;
  min-height: 0;
}
.gl-selected-title {
  margin: 0 0 12px;
  font-size: 14px;
  font-weight: 500;
  color: #334155;
}
.gl-selected-list {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.gl-selected-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  background: #f8fafc;
}
.gl-selected-name {
  flex: 1;
  font-size: 13px;
  color: #334155;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.gl-remove {
  border: none;
  background: none;
  color: #94a3b8;
  cursor: pointer;
  font-size: 12px;
}
.gl-empty {
  text-align: center;
  color: #94a3b8;
  padding: 24px 0;
  font-size: 13px;
}
</style>

// frontend/edu/app/library/knowledge/_components/granular-lesson-select-dialog.tsx
'use client'

import { useState, useMemo } from 'react'
import { X, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import { SearchInput } from '@/components/shared/search-input'
import { useT } from '@/lib/i18n/locale-provider'

export interface GranularLessonOption {
  id: string
  name: string
  code?: string
  description?: string
}

interface GranularLessonSelectDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  title?: string
  granularCourses: GranularLessonOption[]
  selectedIds: string[]
  onChange: (selectedIds: string[]) => void
}

export function GranularLessonSelectDialog({
  open,
  onOpenChange,
  title = '选择颗粒课',
  granularCourses,
  selectedIds,
  onChange,
}: GranularLessonSelectDialogProps) {
  const t = useT()
  const [search, setSearch] = useState('')

  const filtered = useMemo(
    () =>
      granularCourses.filter(
        (g) => !search || g.name.includes(search) || (g.code && g.code.includes(search)),
      ),
    [granularCourses, search],
  )

  const toggle = (id: string) => {
    onChange(selectedIds.includes(id) ? selectedIds.filter((x) => x !== id) : [...selectedIds, id])
  }

  const selectedCourses = useMemo(
    () =>
      selectedIds
        .map((id) => granularCourses.find((g) => g.id === id))
        .filter(Boolean) as GranularLessonOption[],
    [selectedIds, granularCourses],
  )

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        // 关闭后重置搜索词，避免重新打开时残留上次搜索
        if (!next) setSearch('')
        onOpenChange(next)
      }}
    >
      <DialogContent className="sm:max-w-[800px] max-h-[80vh] h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
        </DialogHeader>
        <div className="flex gap-4 flex-1 min-h-0 py-4">
          <div className="w-3/5 flex flex-col min-h-0 border rounded-xl p-3">
            <SearchInput
              wrapperClassName="mb-3"
              iconClassName="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400"
              value={search}
              onChange={setSearch}
              placeholder={t('搜索颗粒课名称或编码...')}
            />
            <div className="flex-1 overflow-y-auto space-y-2 pr-1">
              {filtered.map((gl) => {
                const isSelected = selectedIds.includes(gl.id)
                return (
                  <div
                    key={gl.id}
                    // role/aria-checked：自绘勾选行需声明语义，弹窗未保存守卫与读屏器都依赖它
                    role="checkbox"
                    aria-checked={isSelected}
                    className={cn(
                      'p-3 rounded-lg border cursor-pointer transition-all',
                      isSelected
                        ? 'border-primary bg-primary/5'
                        : 'border-gray-200 hover:border-gray-300',
                    )}
                    onClick={() => toggle(gl.id)}
                  >
                    <div className="flex items-center gap-2">
                      <div
                        className={cn(
                          'w-4 h-4 rounded border flex items-center justify-center',
                          isSelected ? 'bg-primary border-primary' : 'border-gray-300',
                        )}
                      >
                        {isSelected && <Check className="h-3 w-3 text-white" />}
                      </div>
                      <span className="text-sm font-medium flex-1">{gl.name}</span>
                      {gl.code && (
                        <Badge variant="outline" className="text-[10px]">
                          {gl.code}
                        </Badge>
                      )}
                    </div>
                    {gl.description ? (
                      <p className="text-xs text-gray-500 mt-1 ml-6">{gl.description}</p>
                    ) : null}
                  </div>
                )
              })}
              {filtered.length === 0 && (
                <div className="text-center text-gray-400 py-8">
                  <p className="text-sm">{t('未找到匹配的颗粒课')}</p>
                </div>
              )}
            </div>
          </div>

          <div className="w-2/5 border rounded-xl p-3 flex flex-col min-h-0">
            <p className="text-sm font-medium mb-3 text-gray-700">
              {t('已选择 ({n})', { n: selectedIds.length })}
            </p>
            <div className="flex-1 overflow-y-auto space-y-2">
              {selectedCourses.length === 0 ? (
                <div className="text-center text-gray-400 py-8">
                  <p className="text-xs">{t('从左侧选择颗粒课')}</p>
                </div>
              ) : (
                selectedCourses.map((gl) => (
                  <div
                    key={gl.id}
                    className="flex items-center gap-2 p-2 rounded border bg-gray-50"
                  >
                    <span className="text-sm flex-1 truncate">{gl.name}</span>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6 text-gray-400"
                      onClick={() => toggle(gl.id)}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button onClick={() => onOpenChange(false)}>{t('确定')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
