// frontend/portal-vue/src/views/system/positions.vue
<template>
  <div class="list-page">
    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <div>
            <span class="card-title">职位管理</span>
            <span class="card-sub">管理系统职位信息</span>
          </div>
          <el-button type="primary" @click="openDialog()">新建职位</el-button>
        </div>
      </template>

      <el-input v-model="keyword" placeholder="搜索职位名称或描述..." clearable style="max-width: 320px; margin-bottom: 12px" />

      <el-table v-loading="loading" :data="filteredPositions" stripe>
        <el-table-column prop="name" label="职位名称" min-width="140" />
        <el-table-column label="关联用户数量" width="120">
          <template #default="{ row }">
            <el-tag type="info">{{ row.userCount ?? 0 }} 人</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="90">
          <template #default="{ row }">
            <el-tag :type="row.status === 'active' ? 'success' : 'info'">{{ row.status === 'active' ? '启用' : '停用' }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="createdAt" label="创建时间" min-width="160" show-overflow-tooltip />
        <el-table-column label="操作" width="240" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="openDialog(row)">编辑</el-button>
            <el-button size="small" @click="openUsers(row)">查看用户</el-button>
            <el-button size="small" @click="toggleStatus(row)">{{ row.status === 'active' ? '停用' : '启用' }}</el-button>
            <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新建/编辑 -->
    <el-dialog v-model="dialog" :title="editing ? '编辑职位' : '新建职位'" width="440px">
      <el-form label-width="80px">
        <el-form-item label="职位名称" required><el-input v-model="form.name" placeholder="如：教授" /></el-form-item>
        <el-form-item label="描述"><el-input v-model="form.description" placeholder="可选描述" /></el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="save">保存</el-button>
      </template>
    </el-dialog>

    <!-- 关联用户 -->
    <el-dialog v-model="usersDialog" :title="`关联用户 - ${selected?.name || ''}`" width="520px">
      <div class="users-desc">{{ `共 ${selected?.userCount ?? users.length} 名用户关联此职位` }}</div>
      <div v-loading="loadingUsers">
        <el-empty v-if="!loadingUsers && users.length === 0" description="暂无关联用户" />
        <div v-else class="users-list">
          <div v-for="u in users.slice(0, 5)" :key="u.id" class="users-item">
            <div class="avatar">{{ (u.name || '?')[0] }}</div>
            <span class="uname">{{ u.name }}</span>
            <el-tag size="small" type="info">{{ u.username || u.loginName }}</el-tag>
          </div>
          <div v-if="users.length > 5" class="more">... 还有 {{ users.length - 5 }} 名用户</div>
        </div>
      </div>
      <template #footer>
        <el-button @click="usersDialog = false">关闭</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { staffTitleApi, userManagementApi } from '@/api/portal';
import { request } from '@/api/http';
import { useAuthStore } from '@/stores/auth';
import type { User } from '@/types/user';

interface Position {
  id: string;
  name: string;
  description?: string;
  userCount?: number;
  status?: string;
  createdAt?: string;
}

const auth = useAuthStore();
const tenantId = computed(() => (auth.user?.tenantId as string) || '');

const positions = ref<Position[]>([]);
const loading = ref(false);
const keyword = ref('');
const dialog = ref(false);
const saving = ref(false);
const editing = ref<Position | null>(null);
const form = reactive({ name: '', description: '' });

const usersDialog = ref(false);
const selected = ref<Position | null>(null);
const users = ref<User[]>([]);
const loadingUsers = ref(false);

const filteredPositions = computed(() => {
  const q = keyword.value.trim();
  if (!q) return positions.value;
  return positions.value.filter((p) => p.name.includes(q) || (p.description && p.description.includes(q)));
});

async function load() {
  loading.value = true;
  try {
    const res = await staffTitleApi.list({ ...(tenantId.value ? { tenantId: tenantId.value } : {}), limit: 200 });
    positions.value = res.items as Position[];
  } catch (e) {
    ElMessage.error((e as Error).message || '加载失败');
  } finally {
    loading.value = false;
  }
}

function openDialog(row?: Position) {
  editing.value = row || null;
  form.name = row?.name || '';
  form.description = row?.description || '';
  dialog.value = true;
}

async function save() {
  if (!form.name.trim()) {
    ElMessage.warning('请输入职位名称');
    return;
  }
  saving.value = true;
  try {
    const payload = {
      ...(tenantId.value ? { tenantId: tenantId.value } : {}),
      name: form.name.trim(),
      description: form.description.trim() || undefined
    };
    if (editing.value) {
      await staffTitleApi.update(editing.value.id, payload);
      ElMessage.success('保存成功');
    } else {
      await staffTitleApi.create(payload as { tenantId: string; name: string; description?: string });
      ElMessage.success('创建成功');
    }
    dialog.value = false;
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '保存失败');
  } finally {
    saving.value = false;
  }
}

async function toggleStatus(row: Position) {
  const next = row.status === 'active' ? 'inactive' : 'active';
  try {
    await request(`/staff-titles/${row.id}/status`, { method: 'POST', body: JSON.stringify({ status: next }) });
    ElMessage.success('状态已更新');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '操作失败');
  }
}

async function openUsers(row: Position) {
  selected.value = row;
  users.value = [];
  usersDialog.value = true;
  loadingUsers.value = true;
  try {
    const res = await userManagementApi.list({
      ...(tenantId.value ? { tenantId: tenantId.value } : {}),
      titleId: row.id,
      limit: 200
    });
    users.value = res.items;
  } catch (e) {
    ElMessage.error((e as Error).message || '加载用户失败');
  } finally {
    loadingUsers.value = false;
  }
}

async function confirmDelete(row: Position) {
  try {
    await ElMessageBox.confirm(`确定要删除职位「${row.name}」吗？删除后不可恢复。`, '确认删除', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' });
  } catch {
    return;
  }
  try {
    await staffTitleApi.delete(row.id);
    ElMessage.success('删除成功');
    load();
  } catch (e) {
    ElMessage.error((e as Error).message || '删除失败');
  }
}

onMounted(load);
</script>

<style scoped>
.list-page { padding: 16px; }
.card-header { display: flex; align-items: center; justify-content: space-between; }
.card-title { font-size: 16px; font-weight: 600; }
.card-sub { color: #909399; font-size: 13px; margin-left: 8px; }
.users-desc { color: #909399; font-size: 13px; margin-bottom: 12px; }
.users-list { display: flex; flex-direction: column; gap: 8px; }
.users-item { display: flex; align-items: center; gap: 10px; padding: 8px 12px; background: #f5f7fa; border-radius: 8px; }
.avatar { width: 32px; height: 32px; border-radius: 50%; background: #e6f4ff; color: #1677ff; display: flex; align-items: center; justify-content: center; font-size: 14px; }
.uname { font-size: 14px; }
.more { text-align: center; color: #909399; font-size: 13px; }
</style>

// apps/edu/app/portal/apps/system/org-user/positions/page.tsx
"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { usePortalAuth } from "@/contexts/portal-auth-context"
import { portalStaffTitleApi, portalUserManagementApi, type User } from "@/lib/api"
import { useToast } from "@zhiyu/ui"
import { TableRowActions } from "@/components/shared/table-row-actions"
import { Plus, Pencil, Power, Trash2, Search, Upload, Download, Eye, AlertCircle, Loader2, RotateCcw, Users } from "lucide-react"
import type { StaffTitle } from "@/lib/types/backend"

export default function PositionsPage() {
  const { tenantId } = usePortalAuth()
  const { toast } = useToast()
  const [positions, setPositions] = useState<StaffTitle[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string>()
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isUsersDialogOpen, setIsUsersDialogOpen] = useState(false)
  const [selectedPosition, setSelectedPosition] = useState<StaffTitle | null>(null)
  const [searchTerm, setSearchTerm] = useState("")
  const [dialogName, setDialogName] = useState("")
  const [dialogDescription, setDialogDescription] = useState("")
  const [saving, setSaving] = useState(false)
  const [titleUsers, setTitleUsers] = useState<User[]>([])
  const [loadingUsers, setLoadingUsers] = useState(false)

  const fetchPositions = useCallback(async () => {
    if (!tenantId) return
    setLoading(true)
    setError(undefined)
    try {
      const res = await portalStaffTitleApi.list({ tenantId, limit: 1000 })
      setPositions(res.items)
    } catch (err) {
      setError(err instanceof Error ? err.message : "加载失败")
    } finally {
      setLoading(false)
    }
  }, [tenantId])

  useEffect(() => {
    fetchPositions()
  }, [fetchPositions])

  const filteredPositions = useMemo(() =>
    positions.filter((pos) => pos.name.includes(searchTerm) || (pos.description && pos.description.includes(searchTerm))),
    [positions, searchTerm]
  )

  const openDialog = (position: StaffTitle | null) => {
    setSelectedPosition(position)
    setDialogName(position?.name || "")
    setDialogDescription(position?.description || "")
    setIsDialogOpen(true)
  }

  const handleSave = async () => {
    if (!tenantId) {
      toast({ variant: "destructive", title: "保存失败", description: "未获取到租户信息，请重新登录" })
      return
    }
    if (!dialogName.trim()) return
    setSaving(true)
    try {
      const payload = { tenantId, name: dialogName.trim(), description: dialogDescription.trim() || undefined }
      if (selectedPosition) {
        await portalStaffTitleApi.update(selectedPosition.id, payload)
        toast({ title: "保存成功", description: "职位信息已更新" })
      } else {
        await portalStaffTitleApi.create(payload as Omit<StaffTitle, "id" | "userCount" | "createdAt">)
        toast({ title: "创建成功", description: "新职位已添加" })
      }
      setIsDialogOpen(false)
      await fetchPositions()
    } catch (err) {
      toast({ variant: "destructive", title: "保存失败", description: err instanceof Error ? err.message : "未知错误" })
    } finally {
      setSaving(false)
    }
  }

  const toggleStatus = async (position: StaffTitle) => {
    const nextStatus = position.status === "active" ? "inactive" : "active"
    try {
      await portalStaffTitleApi.toggleStatus(position.id, nextStatus)
      toast({ title: "状态已更新" })
      await fetchPositions()
    } catch (err) {
      toast({ variant: "destructive", title: "操作失败", description: err instanceof Error ? err.message : "未知错误" })
    }
  }

  const deletePosition = async (id: string) => {
    try {
      await portalStaffTitleApi.delete(id)
      toast({ title: "删除成功" })
      await fetchPositions()
    } catch (err) {
      toast({ variant: "destructive", title: "删除失败", description: err instanceof Error ? err.message : "未知错误" })
    }
  }

  const openUsersDialog = async (position: StaffTitle) => {
    setSelectedPosition(position)
    setIsUsersDialogOpen(true)
    setLoadingUsers(true)
    setTitleUsers([])
    try {
      const res = await portalUserManagementApi.list({ tenantId, limit: 1000 })
      const filtered = res.items.filter((u) => u.titleIds?.includes(position.id))
      setTitleUsers(filtered)
    } catch (err) {
      toast({ variant: "destructive", title: "加载用户失败", description: err instanceof Error ? err.message : "未知错误" })
    } finally {
      setLoadingUsers(false)
    }
  }

  return (
    <div className="p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground">职位管理</h1>
          <p className="mt-1 text-sm text-muted-foreground">管理系统职位信息</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" disabled title="即将上线">
            <Upload className="h-4 w-4 mr-1" />
            导入
          </Button>
          <Button variant="outline" size="sm" disabled title="即将上线">
            <Download className="h-4 w-4 mr-1" />
            导出
          </Button>
          <Button size="sm" onClick={() => openDialog(null)}>
            <Plus className="h-4 w-4 mr-1" />
            新增职位
          </Button>
        </div>
      </div>

      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>加载失败</AlertTitle>
          <AlertDescription className="flex items-center gap-4">
            <span className="flex-1">{error}</span>
            <Button variant="outline" size="sm" onClick={fetchPositions}>
              <RotateCcw className="h-4 w-4 mr-1" />重试
            </Button>
          </AlertDescription>
        </Alert>
      )}

      <div className="mb-4">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input placeholder="搜索职位名称..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="pl-9" />
        </div>
      </div>

      <div className="rounded-lg border border-border bg-card">
        <Table>
          <TableHeader>
            <TableRow className="border-border">
              <TableHead>职位名称</TableHead>
              <TableHead>关联用户数量</TableHead>
              <TableHead>状态</TableHead>
              <TableHead>创建时间</TableHead>
              <TableHead className="text-right">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center py-12">
                  <Loader2 className="h-6 w-6 animate-spin mx-auto text-muted-foreground" />
                  <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
                </TableCell>
              </TableRow>
            ) : filteredPositions.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center text-muted-foreground py-8">
                  {searchTerm ? "未找到匹配的职位" : "暂无职位数据"}
                </TableCell>
              </TableRow>
            ) : (
              filteredPositions.map((position) => (
                <TableRow key={position.id} className="border-border group">
                  <TableCell className="font-medium">{position.name}</TableCell>
                  <TableCell>
                    <Badge variant="secondary">{position.userCount} 人</Badge>
                  </TableCell>
                  <TableCell>
                    <Badge variant={position.status === "active" ? "default" : "secondary"}>
                      {position.status === "active" ? "启用" : "停用"}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-muted-foreground">{new Date(position.createdAt).toLocaleString("zh-CN")}</TableCell>
                    <TableRowActions>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs"
                        onClick={() => openDialog(position)}
                      >
                        <Pencil className="mr-1 h-3 w-3" />
                        编辑
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs"
                        onClick={() => openUsersDialog(position)}
                      >
                        <Users className="mr-1 h-3 w-3" />
                        查看用户
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs"
                        onClick={() => toggleStatus(position)}
                      >
                        <Power className="mr-1 h-3 w-3" />
                        {position.status === "active" ? "停用" : "启用"}
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 px-2 text-xs text-red-500 hover:text-red-600"
                        onClick={() => deletePosition(position.id)}
                      >
                        <Trash2 className="mr-1 h-3 w-3" />
                        删除
                      </Button>
                    </TableRowActions>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      <div className="mt-4 text-sm text-muted-foreground">共 {filteredPositions.length} 条记录</div>

      {/* 新增/编辑职位 */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{selectedPosition ? "编辑职位" : "新增职位"}</DialogTitle>
            <DialogDescription>职位用于用户身份标识</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label>职位名称 <span className="text-destructive">*</span></Label>
              <Input placeholder="如：教授" value={dialogName} onChange={(e) => setDialogName(e.target.value)} />
            </div>
            <div className="grid gap-2">
              <Label>描述</Label>
              <Input placeholder="可选描述" value={dialogDescription} onChange={(e) => setDialogDescription(e.target.value)} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDialogOpen(false)} disabled={saving}>取消</Button>
            <Button onClick={handleSave} disabled={saving || !dialogName.trim()}>
              {saving ? <Loader2 className="h-4 w-4 animate-spin mr-1" /> : null}
              保存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 查看关联用户 */}
      <Dialog open={isUsersDialogOpen} onOpenChange={setIsUsersDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>关联用户 - {selectedPosition?.name}</DialogTitle>
            <DialogDescription>共 {titleUsers.length} 名用户关联此职位</DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {loadingUsers ? (
              <div className="text-center py-8">
                <Loader2 className="h-6 w-6 animate-spin mx-auto text-muted-foreground" />
                <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
              </div>
            ) : titleUsers.length === 0 ? (
              <p className="text-center text-sm text-muted-foreground py-4">暂无关联用户</p>
            ) : (
              <div className="space-y-2">
                {titleUsers.slice(0, 5).map((user) => (
                  <div key={user.id} className="flex items-center justify-between p-2 bg-muted rounded-lg">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-medium text-primary">
                        {user.name[0]}
                      </div>
                      <span className="text-sm">{user.name}</span>
                    </div>
                    <Badge variant="outline">{user.username || user.loginName}</Badge>
                  </div>
                ))}
                {titleUsers.length > 5 && (
                  <p className="text-center text-sm text-muted-foreground">... 还有 {titleUsers.length - 5} 名用户</p>
                )}
              </div>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsUsersDialogOpen(false)}>关闭</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
